[WIP] Allow adding rules to cgroup devices.allow on container create/run
moby/moby pull request #22563
Opened 2016-05-06 22:42 UTC by mlaventure

**- What I Did**

This introduce a new `--device-cgroup` flag that allow a user to add
one or more entry to the container cgroup device `devices.allow`

This should hopefully give a solution to issue like the one referred in the #22206 proposal:
  - add a rule to the container cgroup (e.g. 'c 13:* rwm')
  - via udev, execute a script anytime such a device is added. 
  - the script should check whether the device should or should not be added to a given container
  - if the device is to be added, the script can run a docker exec to mknod the device into the container

**- Note**

I will make the required vendoring/engin-api PR once this has been accepted.
**- Description for the changelog**

+ Add the ability to specify extra rule for a container device cgroup devices.allow mechanism

**- A picture of a cute animal (not mandatory but encouraged)**

![](https://s-media-cache-ak0.pinimg.com/736x/89/23/0d/89230d860e49dad02e47d14e91151aa7.jpg)
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

2016-05-23 21:21 UTC, LK4D4 commented
I agree with a feature, but naming is confusing I think. Maybe something like device-cgroup-rule? I dunno

2016-05-23 22:03 UTC, mlaventure commented
@LK4D4 I like the name, thanks! Will update shortly

2016-05-26 14:25 UTC, thaJeztah commented
ping @LK4D4 ptal

2016-06-03 20:41 UTC, mlaventure commented
Added a test

2016-06-04 02:49 UTC, cpuguy83 commented
This seems super low-level  (much more so than any other flag we have, I think).

I don't understand the limitations on the devices cgroup, but... it seems like we should be able to address the use case with `docker update` to deal with adding the device to the whitelist and performing the mknod for the user.

This could also be looked at along with security profiles... some profile option to enable host device update access.

2016-06-04 21:31 UTC, mlaventure commented
ping @tonistiigi , if I'm not wrong he was against a `docker update` solution. I'll let him explain his view :)

2016-09-15 18:52 UTC, tonistiigi commented
Design LGTM

2016-09-15 19:07 UTC, tonistiigi commented
@cpuguy83 I'm not strictly against the update solution but it would be much complicated. Then we also need to do an exec to make the `mknod`. Then someone will ask why we can do devices but not volumes and it may become complicated soon. Anyway, either way looks fine by me.

2016-10-22 19:16 UTC, thaJeztah commented
ping @cpuguy83 @tonistiigi PTAL - too low level for me, haha

2016-11-02 17:17 UTC, cpuguy83 commented
Maybe the low-level is ok, but I think we should have a higher level abstraction as well that the user can say "let me hotplug stuff into my usb ports and propagate to the container".

2016-11-02 17:17 UTC, cpuguy83 commented
But I don't think many humans will actually use this.

2016-11-02 18:15 UTC, mlaventure commented
@cpuguy83 at least on linux this high level interface is not that simple. A usb device can end up creating any sort of `MAJOR:MINOR` combination.

So this would involve playing around with `udev`, `/sys/dev` and `cgroups` (to add them to the allow list).

Also, you may want to prohibit some category of devices to be propagated (or vice-versa).

I'd rather leave this complexity to the user (at least for now).

2016-11-02 19:39 UTC, cpuguy83 commented
Let's just move forward with this low-level bit

2016-11-04 01:32 UTC, cpuguy83 commented
Could you add something to docs so I know how to use this?

2016-11-04 15:53 UTC, mlaventure commented
Updated the man pages with a more detailed example

2016-12-08 16:24 UTC, thaJeztah commented
ping @cpuguy83 😇

2016-12-20 01:11 UTC, cpuguy83 commented on daemon/oci_linux.go
> +		r := regexp.MustCompile("^([acb]) ([0-9]+|\\*):([0-9]+|\\*) ([rwm]{1,3})$")
Can probably throw this up as a package var

2016-12-20 01:13 UTC, cpuguy83 commented
Needs a rebase.
1 minor nit, but otherwise LGTM

2016-12-21 21:43 UTC, cpuguy83 approved these changes
LGTM

2016-12-22 19:11 UTC, thaJeztah commented
ping @tonistiigi PTAL

2016-12-22 19:17 UTC, tonistiigi commented
code LGTM. Hopefully, there is someone who has a use case for this.

2016-12-27 22:55 UTC, thaJeztah requested changes

2016-12-27 22:55 UTC, thaJeztah commented on man/docker-create.1.md
> +   Example: `c 1:3 mr`: allow for character device with major `1` and minor `3` to be created (`m`) and read (`r`)
Can you add this information to the online docs as well (docs/reference.. above)?

Also, can we come up with a full example, and an explanation when this option should be used, as it's not clear to me after reading this :smile:

2017-01-03 13:22 UTC, vdemeester commented
ping @mlaventure

2017-01-03 21:24 UTC, mlaventure commented on man/docker-create.1.md
> +   Example: `c 1:3 mr`: allow for character device with major `1` and minor `3` to be created (`m`) and read (`r`)
Where should I put that example? in `docs/reference/commandline/create.md`?

2017-01-03 22:43 UTC, thaJeztah commented on man/docker-create.1.md
> +   Example: `c 1:3 mr`: allow for character device with major `1` and minor `3` to be created (`m`) and read (`r`)
Yes, it can be in both the man page and the docs/reference/commandline/create.md

(Note that the man page was moved to man/src)

2017-01-13 22:01 UTC, mlaventure commented
@thaJeztah Tried to add an example

2017-01-26 15:00 UTC, cpuguy83 commented on man/src/container/create-example.md
> +created into the container once it is run. This pauses a problem when
s/pauses/poses?

2017-01-26 15:21 UTC, mlaventure commented on man/src/container/create-example.md
> +created into the container once it is run. This pauses a problem when
indeed, thanks.

2017-01-27 10:03 UTC, vdemeester approved these changes
LGTM 🐸

2017-01-27 14:10 UTC, cpuguy83 commented
Moving to docs review.

2017-02-01 15:29 UTC, vdemeester approved these changes
docs LGTM 🐸
/cc @thaJeztah gonna merge that and add docs-revisit 👼

2017-02-01 15:29 UTC, merged

2017-02-02 00:56 UTC, thaJeztah commented on man/src/container/create.md
> -This option is useful in situations where you are running Docker containers on
Why was this section removed?

2017-02-02 00:56 UTC, thaJeztah commented on man/src/container/create.md
> -This option is useful in situations where you are running Docker containers on
oh, I see; moved to the other document

2017-02-02 00:58 UTC, thaJeztah commented
@mlaventure looks like you forgot to update the CLI reference with the example; https://github.com/docker/docker/pull/22563#discussion_r94486713

2017-03-13 17:24 UTC, mlaventure commented
ping @albers I had initially added a basic completion for bash (it's a very old PR), but I think you would do a better job, mind having a second look?

Thanks!

2017-03-14 12:49 UTC, albers commented
@mlaventure I don't think this can be improved because the argument contains a space. AFAIK, bash completion does not work inside quoted arguments.

2017-03-14 14:25 UTC, mlaventure commented
@albers thanks for checking!

2017-08-01 07:21 UTC, hqhq commented
Why not improving `--device` to support something like `--device /dev/sdb*:rx` than to introduce this option?

2017-08-01 18:31 UTC, mlaventure commented
@hqhq what you suggest would require to spawn a goroutine to monitor changes to the filesystem and replicate it within the container. But that would also assume that the container has all the tools necessary for this (e.g. mknod) or force it to be there. 

Also, maybe the right of the device thus newly created would need to be changed within the container.

It's easier to let people set up their own policy with the tool provided.

2018-01-29 19:59 UTC, th3mis commented
@mlaventure 
Why also there is no option to initially add `с 189:* rwm`into devices.list when create new cgroup for container? I suppose it best solution, but I am new in Docker, and maybe I'm wrong here

2018-01-30 00:49 UTC, mlaventure commented
@th3mis that what the option you're providing does.

2018-06-13 14:39 UTC, pamelamei commented
I think this feature is really helpful.