Windows: Support credential specs
moby/moby pull request #23389
Opened 2016-06-08 23:02 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Adds support for a credential spec to be passed through from either the registry or file to support emulated domain identity. @patricklang 

Usage example:

```
FROM windowsservercore
LABEL com.microsoft.credentialspec="file://foo.txt"
CMD echo foo

docker build -t label .
docker start label
```

Or

```
docker run -it --rm -label com.microsoft.credentialspec="registry://foo" windowsservercore echo foo
```

Where in the first example, `foo.txt` exists under the `docker root directory\credentialspecs` and contains the credential blob (defaults to `c:\programfiles\docker\credentialspecs\...`), and in the second example, the key `foo` exists under `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers\CredentialSpecs`, and similarly contains the credential blob. In both cases, the blob is the non-secret identifying part, the contents of which are orthogonal to this PR and to docker - it is managed outside of docker. Docker is opaque to its actual contents.

![image](https://cloud.githubusercontent.com/assets/10522484/15913897/c04cfc90-2d91-11e6-9bdf-feb62173743c.png)

Note needs a revendor of HCSShim which is coming in a separate PR to include https://github.com/Microsoft/hcsshim/pull/47 (@darrenstahlmsft), and a subsequent rebase.

Note also this is not supported by Windows on TP5, and also would require the CI servers to be domain joined, so adding test cases for CI isn't realistic. We're working on that seperately.

@NathanMcCauley

2016-06-08 23:57 UTC, crosbymichael commented
@jhowardmsft don't you need a line in the hack/vendor.sh file with the commit for the change?

2016-06-09 00:26 UTC, jhowardmsft commented
the vendor PR is going in separately covering a few changes.

2016-06-09 18:46 UTC, jhowardmsft commented
Rebased after #23392 merged.

2016-06-10 16:49 UTC, crosbymichael commented
On the design side i'm not sure if labels should be overloaded for this.  Is this the first time we are using labels like this or is it being use for another setting somewhere else?

2016-06-10 17:47 UTC, thaJeztah commented
Wouldn't this be a task for an entrypoint script? e.g. `regedit.exe /s something.reg`, or won't that work?

2016-06-10 17:57 UTC, cpuguy83 commented
I agree with @crosbymichael.
Tend to say labels are for systems that sit above docker, not for docker's subsystems.

2016-06-10 18:33 UTC, jhowardmsft commented
Label was used after a Microsoft/Docker conf call recommendation. Patrick - please fill in the gaps here.

2016-06-10 22:11 UTC, PatrickLang commented
We also considered environment and --security-opts. The problem is that security_opts already has multiple unrelated things in there and we didn't want to contribute to that. Our discussion with @NathanMcCauley was that labels would be a better location, and that its clear its specific to Microsoft for now. Long term we want this to be set by an upper layer along the lines of the DockerCon EU Universal Control Plane prototype. That one used labels.

2016-06-10 22:28 UTC, crosbymichael commented
Was a dedicated flag considered for this? Also is this path a path inside the container or on the host?  If it is on the host this should not be inside a docker at all as it makes images not portable.

2016-06-10 23:07 UTC, PatrickLang commented
It's a path on the host, and its completely optional. The container shouldn't have this data stored in it. If its not provided, the container will use the default built-in Windows accounts the same way they did before.

2016-06-10 23:46 UTC, thaJeztah commented
There's some earlier discussion about using labels for configuration; this was about using labels to configure networking https://github.com/docker/docker/pull/13476

2016-06-10 23:56 UTC, crosbymichael commented
Yes, we should not use labels for this.  

I don't see a problem adding a flag and api field for this.  Maybe a simple `--credentials` or similar may work.  

However, I don't see how we can have this in the dockerfile.  Even if it is optional it makes the images build be non portable since this references a filepath on the host system that may not exist on all systems.  

To move this forward we should discuss a proper flag name that everyone is happy with and remove this feature from the Dockerfile.  Also these API fields  should live in the HostConfig and not the container's Config structure. 

If the Dockerfile requirement is something being that the containers building the image need these credentials to run successfully, we can have a `docker build` flag, the same way we do with the cgroup options to add the correct credentials during build time but ensuring they are not committed to the final result. 

Let me know if you have any questions.  Happy to help get this merged.

2016-06-15 22:46 UTC, jhowardmsft commented
@crosbymichael PR submitted to match ^^. Will submit a PR to engine-api and update further once that is merged and possible to re-vendor. Now has the --credentialspec field to both docker run and docker build. No longer cached in the image.  Note that this is something we would really like as part of 1.12 to show at Dockercon if possible.

2016-06-15 22:49 UTC, crosbymichael commented
@jhowardmsft thanks for updating this. I'll check it out

2016-06-20 17:35 UTC, jhowardmsft commented
Design good now and can move forward to code review? (Appreciate we're all busy at Dockercon though :smile:)

2016-06-27 20:12 UTC, crosbymichael commented
@jhowardmsft the vendor checks are still failing

2016-06-27 21:03 UTC, jhowardmsft commented
@crosbymichael I'm waiting for https://github.com/docker/engine-api/pull/282 to be merged to fix up the vendoring side of this PR.

2016-07-05 18:45 UTC, icecrime commented
Not to diminish the priority of the patch, but removing from the milestone as Windows is not yet aligned to the release process (meaning: we build from master).

2016-07-07 16:34 UTC, jhowardmsft commented
@thaJeztah How can we get this and the engine API PR moved forward? I've got folks really pushing hard for this functionality to demo

2016-07-08 00:36 UTC, thaJeztah commented
let me start with adding an "needs attention" label

2016-07-15 15:52 UTC, PatrickLang commented
Any updates here? I have been running a private build and would like to be able to run off master again.

2016-07-15 15:55 UTC, cpuguy83 commented
For me, I need an understanding of what a credential spec is, what problem it's solving, and if that problem applies to more than just Windows.

2016-07-15 16:01 UTC, PatrickLang commented
This does start-time binding of network credentials to a Windows container. The typical example is that it allows the app running in the container such as a ASP.net website to use an Active Directory (based on Kerberos) group-managed service account to authenticate to a SQL database. No username/password is stored in the container.

The credential spec includes the data needed to identify the right service account from an AD domain controller.

2016-07-15 19:12 UTC, cpuguy83 commented
This sounds pretty similar to RedHat's issues with getting RHEL certificates into the build environment so build containers can access RH repos.

2016-07-15 20:15 UTC, jhowardmsft commented
Not at all. One is outside the container. This is inside the container.

2016-07-16 02:09 UTC, cpuguy83 commented
@jhowardmsft I'm not sure I understand how RHEL's case would be outside the container.

2016-07-16 05:43 UTC, jhowardmsft commented
That was my understanding. But none the less, this is completely different...

2016-07-22 03:11 UTC, jhowardmsft commented
@NathanMcCauley Can you weigh in here? This is as per the previous design discussions. We weren't able to move this forward at the maintainers meeting today, and are sitting in circling pattern. @crosbymichael's feedback has been addressed. Overall this is one of the key scenarios for Windows containers, so moving this forward is something we really would appreciate. :smile:

2016-07-29 18:45 UTC, jhowardmsft commented
@PatrickLang Can you follow up with @friism on how to move this forward now 1.12 is out of the way - I'm out next week. @NathanMcCauley - any feedback here?

2016-08-29 19:47 UTC, PatrickLang commented
@diogomonica - This is the PR we talked about a few months ago. Can we get this in now that v1.12 is done? It's the last thing needed for Windows users to be able to use Windows Active Directory service accounts to secure connections (eg: website to SQL) without storing passwords in config files. I'm happy to go over it in more detail and cover questions - ping me on Slack.

2016-09-06 18:41 UTC, icecrime commented
Apparently there were discussions with @diogomonica and @NathanMcCauley prior to this PR being submitted, so I'll you figure this out.

2016-09-07 21:23 UTC, jhowardmsft commented
Rebased now engine-api is back in docker.

2016-09-12 17:46 UTC, jhowardmsft commented
Rebased again

2016-09-13 01:53 UTC, icecrime commented
I fully agree with @crosbymichael that a dedicated (Windows-specific) flag for `build` and `run` is the right approach (we should hire this guy!).

Regarding the relationship with secrets management:

- I have the feeling that credentials passing on Windows could/should ultimately reuse the same workflow than any platform-agnostic secret, but secret management is not a thing in Docker today so we can't treat that as a blocker. I however would ask you to please consider deprecating `--credentialspec` in favor of regular secrets when that feature lands (and if possible of course).
- It's my understanding that the current secrets design includes a Dockerfile instruction as a mean to express the dependency of an image on the existence of a particular secret: this serves the purpose of allowing to inspect images for runtime dependencies. Again, when that feature lands, I think we should really consider what can be done to encompass that use case.

So I guess design LGTM, moving to code review.

PS: I'm very happy you're having phone calls and brunch on Sundays, but this is an open source project and GitHub is our source of truth. It's extremely frustrating to be asked for an opinion after having missed over half of the discussions, especially when the people involved don't bother replying after a record-breaking 7 pings.

2016-09-13 01:53 UTC, icecrime commented on daemon/oci_windows.go
> +	windowsCredentialSpec          = "com.microsoft.credentialspec"
This is unused now.

2016-09-13 01:54 UTC, icecrime commented on daemon/oci_windows.go
> +		f := strings.SplitAfter(v, "file://")
Maybe this whole block would be simpler using `strings.HasPrefix` and `strings.TrimPrefix`? You wouldn't have to deal with the length of the resulting split string.

2016-09-13 01:55 UTC, icecrime commented on daemon/oci_windows.go
> +		logrus.Warnf("%s could not be opened. Ignoring credential spec %q for container %s", credentialSpecRegistryLocation, name, id)
Is it really just a warning? I wonder if we're not better of failing here that waiting for a potential (likely?) runtime failure as credentials happen to be missing.

2016-09-13 01:55 UTC, icecrime commented on daemon/oci_windows.go
> +		logrus.Warnf("Ignoring credential spec '%s' for container %s as it could not be found", location, id)
Same comment as above.

2016-09-13 01:56 UTC, icecrime commented on runconfig/hostconfig_solaris.go
> +	if hc == nil {
```
if hc != nil && len(hc.CredentialsSpec) != 0 {
    return fmt.Errorf(...)
}
return nil
```

2016-09-13 01:57 UTC, icecrime commented on runconfig/hostconfig_solaris.go
> +	if hc == nil {
Also not sure if we can have this code only written once in a file for anything not Windows.

2016-09-13 01:57 UTC, icecrime commented on runconfig/opts/parse.go
> +
:scream:

2016-09-13 15:43 UTC, jhowardmsft commented on runconfig/opts/parse.go
> +
Your new keyboard :smiling_imp: 

![image](https://cloud.githubusercontent.com/assets/10522484/18480599/1a9dc0b0-798e-11e6-9c7b-bc920d1d1094.png)

2016-09-13 15:44 UTC, jhowardmsft commented on daemon/oci_windows.go
> +	windowsCredentialSpec          = "com.microsoft.credentialspec"
Good catch. Will remove.

2016-09-13 15:47 UTC, jhowardmsft commented on daemon/oci_windows.go
> +		f := strings.SplitAfter(v, "file://")
Yup, agreed. Will rework.

2016-09-13 15:56 UTC, jhowardmsft commented on daemon/oci_windows.go
> +		logrus.Warnf("%s could not be opened. Ignoring credential spec %q for container %s", credentialSpecRegistryLocation, name, id)
This is a good question, one which I somewhat agonised about. I really am not sure what the right answer is, I'm still sitting on the fence. However, I can easily be persuaded that this is an error, which I'll update it to. @PatrickLang unless you have a strong opinion the other way?

2016-09-13 16:03 UTC, jhowardmsft commented on daemon/oci_windows.go
> +		logrus.Warnf("Ignoring credential spec '%s' for container %s as it could not be found", location, id)
Updating as per above comment.

2016-09-13 16:16 UTC, jhowardmsft commented on runconfig/hostconfig_solaris.go
> +	if hc == nil {
Agree with update. Will be in next push.

2016-09-13 16:17 UTC, jhowardmsft commented on runconfig/opts/parse.go
> +
But yes, will remove in next push.

2016-09-13 16:21 UTC, jhowardmsft commented on runconfig/hostconfig_solaris.go
> +	if hc == nil {
The best way to have it only once is to have a common `ValidateCredentialSpec` function in `hostconfig.go` utilising runtime.GOOS in the condition. I've had pushback about doing this having maintainers generally preferring _platform.go files, although sometimes it makes sense to inline it here. Happy to move to `hostconfig.go` if you think it's worth doing here. Haven't done that for the next update though.

2016-09-13 19:02 UTC, ehazlett commented
fwiw this looks fine to me (not a mainainter).  +1 from @icecrime comment that we should revisit the build secret implementation when ready.  i think that could solve this case but i agree it shouldn't be a blocker for this.

2016-09-13 21:15 UTC, jhowardmsft commented
@icecrime - with the one exception I mentioned which I'm not sure is worth it(?), your comments have been addressed. Thanks for the review. I've also added a test to handle failure cases (`TestRunCredentialSpecFailures`), but as I mentioned in the original PR comment, adding end-to-end success CI test cases isn't viable with the amount of additional infrastructure which would be required.

2016-09-13 21:20 UTC, jhowardmsft commented
@icecrime @ehazlett And yes, I concur fully that once a generic implementation is available, this should be ported across to that solution. Happy to be on point for making that happen :smile:

2016-09-16 16:01 UTC, icecrime commented
Thanks @jhowardmsft! LGTM

2016-09-19 21:37 UTC, jhowardmsft commented
Rebased on master

2016-09-20 10:36 UTC, thaJeztah commented
Needs another rebase already :sweat_smile:

2016-09-21 16:31 UTC, jhowardmsft commented
And rebased again :smile:

2016-09-22 19:06 UTC, jhowardmsft commented
And again....

2016-09-22 19:31 UTC, diogomonica commented
I have reservations about adding this flag:
- It's a windows only feature (the fact that there are Linux-only flags is not a good argument as to why this should exist)
- The PR allows changing the build-time behavior, which is something that doesn’t exist in Docker right now, and there are a lot of internal discussions on whether that should be allowed or not.
- This PR is effectively bootstraping secrets on windows. Granted, might be the NLTM secrets, and not certificates, tokens, etc, but they are secrets nonetheless. Seems like using non-OS specific secrets distribution mechanism would be ideal.

This said, given that we don't have an alternative solution right now and that this seems to be a blocker for a legitimate use-case, I'll LGTM.

2016-09-22 19:35 UTC, jhowardmsft commented
@diogomonica There is one alternate I can think of, which is also advantageous in that we don't have to deprecate a field in the hostconfig once a generic solution is available. This is to overload --security-opt instead from the CLI. Currently there are no security options on Windows.

So something like `docker run --security-opt credentialspec=file://foo ...`

Thoughts?

2016-09-22 19:36 UTC, jhowardmsft commented
Edit: Actually that wouldn't work as --security-opt isn't a field to build.

2016-09-23 11:43 UTC, mavenugo commented on daemon/start_windows.go
> +func getCS(prefix, value string) string {
minor nit : why getCS ? `getCredentialSpec` is short enough :)

2016-09-23 11:48 UTC, mavenugo commented on runconfig/hostconfig_unix.go
> +// the credential spec in the hostconfig structure. Solaris does not support
minor nit : copy + paste error on Solaris :)

2016-09-23 11:48 UTC, mavenugo commented on runconfig/hostconfig_windows.go
> +// the credential spec in the hostconfig structure. Linux does not support
minor nit : another platform mix up.

2016-09-23 11:53 UTC, mavenugo commented on runconfig/hostconfig_windows.go
> +func ValidateCredentialSpec(hc *container.HostConfig) error {
where is the validation done and how ?

2016-09-23 11:56 UTC, mavenugo reviewed
Few minor nits and an open question.
It seems the changes are client/api changes, while the actual validation is out of scope (as explained in your description).

Since this falls under the secrets mgmt, I am not fully qualified to give comment on the design / requirements. But the code seems reasonable.

2016-09-23 17:13 UTC, jhowardmsft commented on daemon/start_windows.go
> +func getCS(prefix, value string) string {
Sure, updated. Will be in next push.

2016-09-23 17:14 UTC, jhowardmsft commented on runconfig/hostconfig_unix.go
> +// the credential spec in the hostconfig structure. Solaris does not support
Fixed in next push.

2016-09-23 17:14 UTC, jhowardmsft commented on runconfig/hostconfig_windows.go
> +// the credential spec in the hostconfig structure. Linux does not support
Fixed in next push.

2016-09-23 17:19 UTC, jhowardmsft commented on runconfig/hostconfig_windows.go
> +func ValidateCredentialSpec(hc *container.HostConfig) error {
This is the initial validation where the hostconfig gets passed from the caller into the daemon. The function as you can see is a no-op on Windows. The main point of this function is for similar things  such as `ValidateQoS` or `ValidateIsolation` in `hostconfig_unix.go` to error out if the daemon doesn't support those options. The validation of the value passed is done in `getLibcontainerdCreateOptions` in the update in this PR.

2016-09-23 22:32 UTC, jhowardmsft commented
@icecrime @diogomonica Putting aside the other argument, I have purposefully in a second commit (will squash if acceptable) moved to using the existing security options in the `hostconfig` structure, rather than extending the structure for a field that will be deprecated once a central secrets management solution is in place in the daemon.  This will avoid backwards compatibility in removing the field, which I feel is important for something short-term.

Functionally from the first commit, it's idential.  The difference now is the credential spec is passed as a --security-opt in the CLI such as:

`docker run --it --rm --security-opt credentialspec=file://foo.txt nanoserver cmd`

If this options is attempted against a Linux daemon, the daemon will reject the request.

2016-09-26 14:54 UTC, cpuguy83 commented
Panic in test:

<details>
```
00:37:01 PANIC: docker_cli_run_test.go:4513: DockerSuite.TestRunCredentialSpecFailures
00:37:01 
00:37:01 ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x45B283)
00:37:01 
00:37:01 C:/go/src/runtime/asm_amd64.s:479
00:37:01   in call32
00:37:01 C:/go/src/runtime/panic.go:458
00:37:01   in gopanic
00:37:01 C:/go/src/runtime/panic.go:62
00:37:01   in panicmem
00:37:01 C:/go/src/runtime/signal_windows.go:161
00:37:01   in sigpanic
00:37:01 docker_cli_run_test.go:4525
00:37:01   in DockerSuite.TestRunCredentialSpecFailures
00:37:01 C:/go/src/runtime/asm_amd64.s:479
00:37:01   in call32
00:37:01 C:/go/src/reflect/value.go:434
00:37:01   in Value.call
00:37:01 C:/go/src/reflect/value.go:302
00:37:01   in Value.Call
00:37:01 c:/gopath/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:816
00:37:01   in suiteRunner.forkTest.func1
00:37:01 c:/gopath/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:672
00:37:01   in suiteRunner.forkCall.func1
00:37:01 C:/go/src/runtime/asm_amd64.s:2086
00:37:01   in goexit
```
</details>

2016-09-26 15:06 UTC, jhowardmsft commented
Thanks will look tomorrow - vacation day today.

2016-09-27 16:32 UTC, jhowardmsft commented
Stupid test bug 👿 Fixed and verified locally.

2016-09-27 16:42 UTC, jhowardmsft commented
And rebased. Still in two commits pending feedback as to whether this is a better option.

2016-09-27 16:57 UTC, cpuguy83 commented
Using `SecurityOpt` seems fine to me, especially since we are erroring out completely on non-Windows for build.

2016-09-27 17:00 UTC, diogomonica commented
I also have nothing against it.

2016-09-27 17:09 UTC, jhowardmsft commented
Based on last two comments, squashed the commits.

2016-09-27 17:14 UTC, cpuguy83 requested changes

2016-09-27 17:14 UTC, cpuguy83 commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support --security-opt to build")
Should be BadRequest or Conflict error.
And probably skip the flag and just use `security opts` since this is the daemon?

2016-09-27 17:14 UTC, cpuguy83 commented on daemon/start_windows.go
> +	if _, err := os.Stat(full); os.IsNotExist(err) {
No need to stat here, should be able to pull `os.IsNotExist` from `ioutil.ReadFile`

2016-09-27 17:14 UTC, cpuguy83 commented on integration-cli/docker_cli_run_test.go
> +		{"file://", "invalid credential spec security option - value must be prefixed file:// or registry://"},
I'd expect a different error here since it is prefixed with `file://`, just that there is no value.

2016-09-27 17:14 UTC, cpuguy83 commented on integration-cli/docker_cli_run_test.go
> +		c.Assert(err, checker.NotNil, check.Commentf("%s expected non-nil err", attempt.value))
Any way to test a positive case?

2016-09-27 17:14 UTC, cpuguy83 commented on daemon/start_windows.go
> +		}
What about other error kinds?

2016-09-27 22:25 UTC, jhowardmsft commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support --security-opt to build")
Hmm. Not sure about that. This is consistent with https://github.com/docker/docker/blob/master/api/server/router/build/build_routes.go#L65. And has to be picked up from the options (via `r.Form["securityopt"] a few lines higher).

2016-09-27 22:27 UTC, jhowardmsft commented on daemon/start_windows.go
> +		}
Good point. Will be updated in next push.

2016-09-27 22:28 UTC, jhowardmsft commented on daemon/start_windows.go
> +	if _, err := os.Stat(full); os.IsNotExist(err) {
Fixed in next push.

2016-09-27 22:31 UTC, jhowardmsft commented on integration-cli/docker_cli_run_test.go
> +		c.Assert(err, checker.NotNil, check.Commentf("%s expected non-nil err", attempt.value))
Not in the current CI infrastructure. To validate end-to-end, this requires an active directory domain and other infrastructure services.

2016-09-27 22:37 UTC, jhowardmsft commented on integration-cli/docker_cli_run_test.go
> +		{"file://", "invalid credential spec security option - value must be prefixed file:// or registry://"},
Fair. Updated in next push.

2016-09-27 22:45 UTC, jhowardmsft commented
@cpuguy83 Updated and pushed.

2016-09-28 20:57 UTC, jhowardmsft commented
Rebased

2016-09-28 21:06 UTC, cpuguy83 commented on daemon/start_windows.go
> +		for _, sOpt := range container.HostConfig.SecurityOpt {
sure would be nice if there was a well tested helper function for grabbing k/v pairs out of SecuritryOpt... or rather `[]string`

2016-09-28 21:11 UTC, cpuguy83 commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support --security-opt to build")
I still think we should fix this

2016-09-28 21:12 UTC, cpuguy83 approved these changes
As I don't have a Windows domain controller lying around to test this with, I trust this is well tested at MS :)

LGTM

2016-09-28 21:15 UTC, jhowardmsft commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support --security-opt to build")
Can you give me an example of what you were thinking? Can always do in a follow-up.

2016-09-28 21:17 UTC, cpuguy83 commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support --security-opt to build")
For the status code, just https://github.com/docker/docker/blob/master/api/errors/errors.go#L21

2016-10-05 22:38 UTC, jhowardmsft commented
Rebased

2016-10-06 13:38 UTC, icecrime commented
Still LGTM,

2016-10-06 13:40 UTC, cpuguy83 commented
Moving to docs review.

2016-10-06 16:36 UTC, jhowardmsft commented
@thaJeztah Updated `build.md` and `run.md` (note there didn't seem to be anything at all in run.md saying about security options on Linux, but adding that is a bit beyond this PR. Just FYI). Anything else I should change too?

Note I've deliberately left it light-weight as to how to configure the credential specs and so on. That would be an entire white-paper in its own right, and something which will eventually be in the Microsoft documentation. @PatrickLang I assume that's something you and @neilpeterson are going to be taking care of. Once you have a link, I could hyperlink the docker docs to it.

2016-10-07 16:30 UTC, vdemeester approved these changes
docs LGTM 🐸

2016-10-07 16:32 UTC, merged

2016-11-02 13:18 UTC, soanni commented
hello Docker Team, how can i try this PR? does the credentialspecs option is working in Windows 1.12.2-cs2-ws-beta ??
If not how can i get the nightly build or alpha whatever to try it.
Thank you in advance for your answer.

2016-11-02 16:08 UTC, jhowardmsft commented
@PatrickLang Can you answer this? See email also.

@soanni Yes, this PR is in the latest CS build too.

2016-11-02 16:27 UTC, PatrickLang commented
These docs are in review, I expect them to be on http://aka.ms/windowscontainers by end of week. I'll post a link when they're live.

2016-11-02 16:30 UTC, soanni commented
@PatrickLang @jhowardmsft  thank you a lot!!

2016-11-04 14:42 UTC, soanni commented
@PatrickLang any chance to take a look at these docs this week?

2016-11-05 04:00 UTC, PatrickLang commented
@soanni got a review done today and pushed it live: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_serviceaccounts

The doc source and issue tracking are in this repo: https://github.com/microsoft/virtualization-documentation

2016-11-15 16:10 UTC, mpwagne commented
This will help us a lot to containerize some of our products where we use windows auth for external resources (sql/shares). 

I have a couple of questions that I can't seem to find the definitive answer to. Hopefully someone can clarify for me...?

- I see we need min of Server 2012 on the domain controllers but what min version of the daemon do we need to support this? 
- Do you have a good example of the structure of the file content itself?
- The doc doesn't seem to go into details of the full credentialspec value to use. Is this correct?
   docker run ... --security-opt credentialspec=file://gMSA_Prod.txt myimage powershell
   (and the gMSA_Prod.txt file would be expected to be present on the host under the %programdata%\docker\credentialspecs  folder).
- Compose support for credentialspec...?
- Does this feature help us with the opposite flow, inbound access to an iis app running in the container using windows auth for example?  Or accessing a SQL server in a container using windows auth (mainly for local dev setup help)? 



By the way, I really enjoyed reviewing the history of this important PR. Shows some really good back and forth collaboration between Docker and MS folks.  :-)

2016-11-15 17:35 UTC, PatrickLang commented
@mpwagne re: AD schema - it's in the [gMSA page](https://technet.microsoft.com/en-us/library/jj128431(v=ws.11).aspx#BKMK_gMSA_Req) linked from my document "The Active Directory schema in the gMSA domain’s forest needs to be updated to Windows Server 2012 to create a gMSA."

I'll track the other open Windows doc issues in my repo since they're questions on how Windows Server 2016 works. They'll show up linked here.

I think Docker-Compose should already work since `security_opt` is supported. If it doesn't work, can you open an issue on docker/compose and tag me on it?

2016-11-15 20:32 UTC, mpwagne commented
@PatrickLang ok thanks. I will keep watch for more info.

What is the minimum version of the docker daemon that I need to get this support?

On the Compose, I quickly tried security_opt before and it complained but I was also struggling with syntax. I will create an issue if I still see issues after getting this working with a basic run command (after you fill me in on the syntax/file structure details). 

It might be a while to get that far though, I am still working with folks to get a 2012 based AD Schema that I can use. We seem to be behind a bit...  might have to spin up an isolated test AD myself.  This will be an uphill climb to get everyone on board with this 2012 schema dependency when we are ready to go up the environments to production. :-o

2016-11-22 12:29 UTC, dimitarivanov commented
@mpwagne Compose supports this option
```
version: '2'
services:
  sqlserver:
    ...
    security_opt:
      - "credentialspec=file://sqlserverapp.json"
```
Docker version:
```
PS C:\> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```
Docker Compose version:
```
PS C:\> docker-compose.exe version
docker-compose version 1.8.1, build 004ddae
docker-py version: 1.10.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```