Windows: Added processor count option
moby/moby pull request #24194
Opened 2016-06-30 21:29 UTC by darrenstahlmsft

**- What I did**

Added --cpu-count flag to set the number of CPUs available to the container on Windows daemons

**- How to verify it**

See added tests to confirm the hostconfig gets updated correctly. Manual confirmation that the JSON blob sent to hcsshim contains the correct values.

**- Description for the changelog**

Added flag --cpu-count for Windows daemons

**- A picture of a cute animal (not mandatory but encouraged)**
![Rabbit!](http://rexrabbitsusa.com/wp-content/uploads/2015/03/Bunny-Wallpapers-bunny-rabbits-128637_1024_768.jpg)

Signed-off-by: Darren Stahl <darst@microsoft.com>

2016-07-01 00:31 UTC, jhowardmsft commented on daemon/oci_windows.go
>  	// @darrenstahlmsft implement these resources
Is there anything more or can this comment be removed?

2016-07-01 00:33 UTC, jhowardmsft commented
Minor comment, but LGTM otherwise.

2016-07-01 00:36 UTC, darrenstahlmsft commented on daemon/oci_windows.go
>  	// @darrenstahlmsft implement these resources
This is the last resource item on my plate. I'll remove the comment

2016-07-01 00:48 UTC, thaJeztah commented
Still wondering if we can come with more generic options, because right now it looks like we'll be duplicating all flags (one for Windows, one for Linux)

2016-07-01 00:51 UTC, thaJeztah commented
I'm sorry, but I'm moving this back to design review, we should discuss what options we have

2016-07-01 00:58 UTC, darrenstahlmsft commented
It is unfortunate that this falls so close to --cpuset-cpus, but unfortunately cpu affinity does not make sense in the context of containers on Windows.

2016-07-01 01:03 UTC, thaJeztah commented
Yes, I was already looking at the existing options; alternatively, we should come with more generic ones, and deprecate Linux options (or alias them). Please don't see this as me trying to be a PITA for the Windows options, just trying to see how we can come to a good end result. (Some of the Linux options are really specific, and named after the cgroups, which may not have been the best decision 😞 )

2016-07-01 01:33 UTC, darrenstahlmsft commented
I understand. The duplication of options was something we discussed internally when looking at how to add this as well, but the only potential option was the cpuset. Ignoring the actual processor affinity on Windows was too much of a gap between what the flag says it does, and what it actually does :disappointed:.

How important is cpu affinity to Linux users? I can't imagine removing affinity would be a great solution, but what if --cpu-count was also an option on Linux daemons with which Docker chooses a set of CPUs for the user? This takes some load off the user when choosing cpu resource configuration if they don't care about affinity, but still lets them set affinity if they want to.

2016-07-29 00:14 UTC, justincormack commented
CPU count probably does make more sense on Linux, but not really sure the APIs match that, picking some random CPUs for affinity could end up with pretty bad results. Will look at the APIs and see if there is a way to make it workable.

2016-08-18 18:18 UTC, jhowardmsft commented
@justincormack Did you manage to come up with any thoughts? Thanks :smile:

2016-08-18 18:19 UTC, tianon commented
If we can't find a way to reconcile them, would it be tenable to simply hide the non-applicable flags per-platform? (ie, not even display `--cpu-count` on Linux, instead of just erroring out when it's used)

2016-08-18 18:44 UTC, darrenstahlmsft commented
Unfortunately due to the separation of client and daemon, along with being able to communicate with cross platform daemons, that is not so easy. In order to hide flags on a per-platform basis, the client must know which daemon it is talking to before it makes the call. What happens when a Windows client wants to start a container on a Windows daemon, then start one on a Linux daemon on the next call? Which flags do we show?

2016-08-18 21:23 UTC, tianon commented
Ah right, great point. :disappointed:

2016-08-18 22:45 UTC, thaJeztah commented
ping @aluzzardi IIRC, you had some thoughts about this as well (in light of restricting resources in Swarm mode)

2016-08-31 21:34 UTC, darrenstahlmsft commented
Ping. Any ideas on this?

2016-09-08 15:03 UTC, cpuguy83 commented
I believe on services we have a cpu count.
We should be able to get this where `cpu-quota` = `<ncores>` * `<cpu-period>`

Ping @crosbymichael 

I think it would be super helpful to normal users to provide this higher-level knob.

2016-09-08 16:33 UTC, crosbymichael commented
We will have to bring in the swarm ppl and get their input but I think an abstraction like `--cpus` would work.

It takes a float and the underlying runtime/platform can best fulfill the request.

`docker run --cpus 1.0 busybox sh`
`docker run --cpus 2.5 busybox sh`

On linux we can use cpu-quota for this and it gives us the ability to use partial cpu and not static core reservation.  On windows @darrenstahlmsft can do what he did here and error if someone does not use a whole number.

2016-09-08 17:17 UTC, crosbymichael commented
What are your thoughts @aluzzardi @stevvooe @aaronlehmann

2016-09-08 20:46 UTC, stevvooe commented
I'd really like to see an abstraction here. Understanding `cpu-percent`, `cpu-period`, `cpu-quota`, and `cpu-shares` and how they interact isn't that valuable if you fix the period to the unit (nanoseconds) and convert to a default unit (100 ms for the linux kernel).

For swarm services, we added something called [`nano_cpus`](https://github.com/docker/swarmkit/blob/master/api/types.proto#L26), which is a fixed point representation of the number of cpus assigned to the container. The conversion is at https://github.com/docker/swarmkit/blob/90be98a5f65355faa1b5f63d766a5694894577d3/agent/exec/container/container.go#L318.

This is further subdivided into reservations and limits. Reservations are managed by an orchestrator, ensuring that those cpus are commit, while limits propagate to the container runtime, ensuring the usage doesn't go over the specified limit.

Things like `cpu-percent` and `cpu-shares` also become quite hairy if you're trying to schedule workloads to a cluster of machines, since the workload "usage" (from the abstract reservation perspective) becomes dependent on the node to which it is scheduled. We could probably have nodes report normalized CPU availability based on core throughput if that really becomes a problem. Such a provision would fix the size of a CPU to be roughly equivalent across the cluster (somewhat in the way money works, as it is only a proxy for workload).

Most of the above is based on a model of assigning time-slices of CPU to workloads. If we are looking a discrete, hardware allocation model, this problem becomes slightly different, but overlaps with the `cpuset` use cases. Imagine assigning CPUs in the same way one might assign disks or GPUs -- they are assigned in discrete units. In this model, CPUs are assigned as discrete units, rather than a time-space quantity. This is more relevant to clustered workloads, so this probably off-topic for this PR.

The only component I can think of that is really missing from the swarmkit mode is a burst allowance, but I am not sure the linux kernel (or others) supports that.

__TL; DR__ It would probably be best to port the `limit-cpu` flag from `docker service create`.

2016-09-09 16:40 UTC, crosbymichael commented
@stevvooe limit-cpu/nano_cpus is still a very low level abstraction.  Most people don't reason about cpus in time but in count.

2016-09-13 23:31 UTC, stevvooe commented
> @stevvooe limit-cpu/nano_cpus is still a very low level abstraction. Most people don't reason about cpus in time but in count.

And to use `limit-cpu`/`nano_cpus`, they don't need to know this. My point was that the allocation is a time-space model rather than a discrete resource model.

2016-10-19 18:24 UTC, mlaventure commented
ping @crosbymichael @stevvooe @darrenstahlmsft 

Have you come to an understanding yet? :)

2016-10-19 18:30 UTC, stevvooe commented
@mlaventure Options here:

1. Allow the new flag as a windows-specific option with the meaning of whatever `cpu-count` means on windows.
2. Introduce `limit-cpus` to `docker run` and apply across all OSes as closely as possible. This is dependent on whether `cpu-count` is a discrete allocation model or a time-space model, similar to `limit-cpus`.

I think we need to get input from @darrenstahlmsft on the recent commentary.

2016-10-19 21:34 UTC, darrenstahlmsft commented
`cpu-count` is a bit of both, though I think closer to a discrete resource allocation model.

On Hyper-V containers, it allocates X virtual processors to the container. The number of virtual processors on a given container cannot exceed the number of physical processors of the host, but does not grant exclusive access to the host's physical processors. This is important to allow users to manage, as the ideal number of virtual processors exposed to the container might not be the same for all workloads.

On Windows Server Containers, this limit is approximated to a cap on the cpu usage. This case could likely be aligned with something like `limit-cpus`, but I think the meaning on Hyper-V containers is important, and distinct from something like `limit-cpus`

2016-10-19 21:58 UTC, stevvooe commented
@darrenstahlmsft On HyperV, can you allocate 0.5 of a cpu?

2016-10-19 22:19 UTC, darrenstahlmsft commented
@stevvooe You can only allocate virtual CPUs as whole numbers, but you can also throttle them via `cpu-percent`. So not exactly, but you can add throttling to get the same result as 0.5 of a CPU.

2016-10-28 19:30 UTC, darrenstahlmsft commented
It's important that we have some way to assign a number of CPUs on Hyper-V container in 1.13. Either via cpu-count or some other mechanism. Currently Hyper-V containers have two CPUs in all cases, which is not ideal. It's also important that users are able to specify the number of CPUs separate to the throttling in Hyper-V containers, as there may be a notable perf difference between 4 vCPUs at 50% throttle and 2 vCPUs depending on the container workload. I don't think something like `limit-cpus` fulfills the same role as `cpu-count` unfortunately.

2016-10-28 20:11 UTC, crosbymichael commented
I assigned @stevvooe, @mlaventure  and myself on this so that we can figure out a good model for allocating cpu resources.  

I also added this to the 1.13 milestone so that it gets attention for the upcoming release.

2016-10-31 23:18 UTC, crosbymichael commented
@darrenstahlmsft `--cpu-count` for windows works for us.  We just need to make sure that this is a windows only flag.  

Can you rebase and we will get this merged.  Thanks!

2016-11-01 20:04 UTC, darrenstahlmsft commented
Updated the code. Docs still needs some updates.

2016-11-01 21:28 UTC, crosbymichael commented
Looks like there is an error compiling the tests:

```
./docker_cli_run_unix_test.go:519: (*DockerSuite).TestRunWithCPUShares redeclared in this block
20:12:44 	previous declaration at ./docker_cli_run_test.go:4581
20:12:44 ---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/test-integration-cli)
```

2016-11-01 21:36 UTC, darrenstahlmsft commented
Oops! Fixed.

2016-11-01 23:10 UTC, crosbymichael commented
LGTM

2016-11-02 23:59 UTC, thaJeztah commented
sorry, looks like this needs a rebase @darrenstahlmsft 

also ping @stevvooe PTAL

2016-11-03 00:06 UTC, darrenstahlmsft commented
Thanks for the heads up! Fixed.

It would be nice if Golang had a way to force tests to be in alphabetical order to prevent these merge conflicts at the end of test files... It would also make finding hanging tests easier.

2016-11-03 01:15 UTC, stevvooe commented
LGTM

2016-11-03 01:46 UTC, jhowardmsft commented on daemon/daemon_windows.go
> +		logrus.Warnf("Changing requested CPUCount of %d to minimum allowed of %d", hostConfig.CPUCount, windowsMinCPUCount)
I'm wondering if we should just error in these conditions, not be adaptive?

2016-11-03 01:47 UTC, jhowardmsft commented on daemon/daemon_windows.go
> +				logrus.Warn("Conflicting options: CPU count takes priority over CPU shares on Windows Server Containers. CPU shares discarded")
Again, wondering if we should error here. Be strict from the outset...

2016-11-03 01:48 UTC, jhowardmsft commented on daemon/oci_windows.go
>  	// @darrenstahlmsft implement these resources
Can this comment be removed now? :smile:

2016-11-03 01:51 UTC, jhowardmsft commented
Some minor comments regarding whether to be adaptive to "bad" input, or outright reject them which can be addressed in a follow-up PR.

LGTM though.

2016-11-03 02:15 UTC, thaJeztah commented
moving to docs review 😇

2016-11-03 02:19 UTC, thaJeztah commented on docs/reference/commandline/run.md
> +                                    first, then CPUShares, and CPUPercent last.
We should really look at Cobra to support this output on the command line as well (just a comment :smile:)

/cc @dnephin

2016-11-03 02:21 UTC, thaJeztah requested changes
Can you;
- Add a note to the API changes; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md#v125-api-changes
- Update the man-page for docker run; https://github.com/docker/docker/blob/master/man/docker-run.1.md

Also; if this is supported on `docker run`, it's most likely also supported on `docker create` (or should be)?

2016-11-04 20:19 UTC, darrenstahlmsft commented
@thaJeztah Updated docs and added --cpu-percent to the man-pages for create and run while I was there.

2016-11-04 23:12 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-04 23:13 UTC, merged

2017-04-18 23:16 UTC, jonso4 commented
Sorry to open this discussion back up - why does CPU affinity not make sense for Windows Server containers? I am looking at using it, but it appears that cpu-count is the best option as of now.

2017-04-18 23:26 UTC, darrenstahlmsft commented
The platform implementation of Windows Server containers (Hyper-V containers too for that matter) does not have a method for restricting the hardware CPUs that are used for execution. Windows Server containers in particular, the cpu-count is not (at least currently) a true core limit, but rather a CPU cap is applied that approximates the core count given.