Use a static action in events
moby/moby pull request #25800
Opened 2016-08-17 13:31 UTC by vdemeester

Fixes #25798, using attributes for dynamic data in events 🐅.

When we filter event, we do an exact match. Thus if the Action content is dynamic, we are filtering out some events. The Attributes field is there to pass additional data with events.

Fixing exec_create, exec_start and health_status event in that matter. A possible follow-up of this would be to force a type for Action in these methods to make sure we pass predefined actions.

**- How to verify it**

In one terminal:

```bash
docker events --filter event=health_status
```

In another terminal;

```bash
docker run --name=test -d --health-cmd='stat /etc/passwd || exit 1' --health-interval=2s   busybox sleep 1d
```

**- Expected**

```bash
$ docker events --filter event=health_status

2016-08-17T12:10:34.337301145Z container health_status: healthy da1bab7bc91a424cd8e0571808c1b4638a903a8508eb6612e9cdfc49f9dde555 (image=busybox, name=test)

$ docker events --filter event=exec_create

2016-08-17T12:10:34.198347963Z container exec_create: /bin/sh -c stat /etc/passwd || exit 1 da1bab7bc91a424cd8e0571808c1b4638a903a8508eb6612e9cdfc49f9dde555 (image=busybox, name=test)
2016-08-17T12:10:36.338156681Z container exec_create: /bin/sh -c stat /etc/passwd || exit 1 da1bab7bc91a424cd8e0571808c1b4638a903a8508eb6612e9cdfc49f9dde555 (image=busybox, name=test)

$ docker events --filter event=exec_start

2016-08-17T12:10:34.198549073Z container exec_start: /bin/sh -c stat /etc/passwd || exit 1 da1bab7bc91a424cd8e0571808c1b4638a903a8508eb6612e9cdfc49f9dde555 (image=busybox, name=test)
2016-08-17T12:10:36.338214034Z container exec_start: /bin/sh -c stat /etc/passwd || exit 1 da1bab7bc91a424cd8e0571808c1b4638a903a8508eb6612e9cdfc49f9dde555 (image=busybox, name=test)
```

**- Todo**

- [ ] Add an integrations test for that.
- [ ] Decide if the map key are the right one for these cases.

/cc @thaJeztah @icecrime @tiborvass @stevvooe @calavera @cpuguy83 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2016-08-17 13:39 UTC, thaJeztah commented
"status" and "command" sound good to me

2016-08-17 13:51 UTC, jhorwit2 commented
Thoughts on changing `status` since it's a [deprecated message field](https://github.com/docker/engine-api/blob/master/types/events/events.go#L32)? This PR would mean we have a deprecated `status` and a non-deprecated `status` for `container` events.

2016-08-17 13:52 UTC, vdemeester commented
@jhorwit2 good point :sweat_smile:

2016-08-18 02:04 UTC, stevvooe commented on daemon/health.go
> +		d.LogContainerEventWithAttributes(c, "health_status", map[string]string{
This is an API change. We'll have to update consumers in swarmkit that take health events.

2016-08-18 07:32 UTC, vdemeester commented on daemon/health.go
> +		d.LogContainerEventWithAttributes(c, "health_status", map[string]string{
ah true :+1:

2016-09-04 15:59 UTC, vdemeester commented
Putting the `needs-attention` flag 👼

2016-09-20 15:58 UTC, thaJeztah commented
Design LGTM, but ping @stevvooe PTAL for the changes required in SwarmKit

2016-09-20 15:59 UTC, thaJeztah commented
oh, actually, do we need to do something w.r.t. https://github.com/docker/docker/pull/25800#issuecomment-240417315 ?

2016-09-21 10:51 UTC, thaJeztah commented
ping @talex5 could you have a look as well?

2016-09-21 12:59 UTC, talex5 commented
@thaJeztah: LGTM

2016-09-22 18:15 UTC, thaJeztah commented
This is the issue we need to think about: https://github.com/docker/docker/blob/master/docs/deprecated.md#ambiguous-event-fields-in-api

Anyone have a better name?

2016-09-22 18:16 UTC, thaJeztah commented
We discussed this in the maintainers review, and we're ok with this PR BUT we need a different name 😞

2016-09-23 19:44 UTC, vdemeester commented
@thaJeztah tried out "state" instead of status 👼 (the *state* of the *health_status*, make probably a little more sence than the *status* of the *health_status*)

2016-10-20 18:30 UTC, tianon commented
Do you think anyone's currently doing something like `docker events --filter 'event=health_status: healthy'` to where we might need some compatibility code to handle that (especially since that's the only existing way to consume these events easily)?

2016-10-20 18:31 UTC, thaJeztah commented
Possibly this should be versioned in the API?

We discussed this, and we do want this change as it's really a bug fix

2016-10-20 18:31 UTC, thaJeztah commented
We're ok with naming this "state" btw

2016-10-20 18:33 UTC, thaJeztah commented
Discussing this further; to be really safe we should;

- version this change in the API
- implement a "match" in the client to allow backward compatibility

2016-10-20 19:38 UTC, vdemeester commented
Sounds good to me 😇
@tianon : we kinda do it on traefik so I guess several project does so I do agree we should have some backward compatibility thingy

2016-10-25 16:09 UTC, vdemeester reviewed
Updated the PR to add _versionned_ filters, using a little hack :stuck_out_tongue_closed_eyes:

2016-10-25 16:09 UTC, vdemeester commented on api/server/router/system/system_routes.go
> +			ef.Add("label", fmt.Sprintf("%s=%s", attribute, value))
This is a little bit hacky as `labels` are, in the events, store at the same level as `attributes`, so we can filter on any additionnal attributes using the label filter.

2016-10-25 18:19 UTC, vdemeester commented
Also one question *arise*, is the way to only filter `health_status` event that are `healthy` for example. It is possible to do so, using the hack I'm using : `--filter event="health_status: healthy"` would now be `--filter event=health_status --filter label=healthy` — but it feels really weird to be able to do so with labels (and it's undocumented too).

2016-10-27 19:18 UTC, vdemeester commented
Let's redo that in a less *intrusive* way. If `health_status` is provided as an event filter (without a `:`), then we'll filter `health_status: …` event using *prefix* instead of full match. It does not require any changes of the API and let's us take time to refactor some part of the events 👼

2016-10-27 22:06 UTC, vdemeester commented
Updated to not change the API, or hacking around at all.
/cc @thaJeztah @tiborvass @cpuguy83 👼

2016-10-27 22:28 UTC, thaJeztah commented on daemon/events/filter.go
> +		return ef.filter.FuzzyMatch("event", ev.Action)
We should really rename `FuzzyMatch` to `PrefixMatch` as it's not doing anything "fuzzy", only optimizing a prefix match

2016-10-27 22:31 UTC, thaJeztah requested changes
changes LGTM, but a test would be nice to have

2016-10-27 22:32 UTC, vdemeester commented on daemon/events/filter.go
> +		return ef.filter.FuzzyMatch("event", ev.Action)
That's true :+1:

2016-10-27 23:20 UTC, thaJeztah approved these changes
LGTM

2016-10-27 23:41 UTC, cpuguy83 commented
LGTM

2016-10-28 03:20 UTC, merged

2017-04-26 20:00 UTC, mlilback commented
vdemeester: what is meant by "It does not require any changes of the API and let's us take time to refactor some part of the events"?

I'm running into this problem when observing exec_start via the API. Was an issue created for this refactoring?