Add support for compressing build context during image build
moby/moby pull request #25837
Opened 2016-08-18 09:17 UTC by reaperhulk

**- What I did**

Added support for optionally compressing build contexts when invoking `docker build`. This provides significant performance improvements when sending contexts to remote servers with low bandwidth. It is, however, a performance regression when sending to local sockets or over very high bandwidth connections so it should default to off.

**- How I did it**

Added a new `--compress` boolean flag. If set then a gzip compression argument is passed to the existing `archive.TarWithOptions` which already supports this behavior. For example `docker build --compress .` `xz` and `bz2` support were not added because Go doesn't support compressing these formats, only decompressing them.

**- How to verify it**

If you build it and use `--compress` you can see the size difference when sending a build context. However, I was unable to find any unit tests for this file. I may be blind so please let me know if I'm mistaken (or if there are tests I should add in other places to verify this functionality). I would be happy to add testing if someone can point me in the right direction.

**- Description for the changelog**

* Added support for optionally compressing build contexts (using `--compress`) when invoking `docker build`

2016-08-18 09:22 UTC, reaperhulk commented
Do I need to update `docs/reference/commandline/build.md` with the updated options output from the CLI manually or is that part of an automated release process?

2016-08-18 10:08 UTC, justincormack commented
@reaperhulk yes at present the docs are manual.

I am not entirely sure about having an option, it seems to add a fair amount of complexity for the user. Could we add compression automatically for tcp connections and not for local sockets?

2016-08-18 12:35 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "support-compressing-build-context" git@github.com:reaperhulk/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~2
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Ammending updates the existing PR. You **DO NOT** need to open a new one.

2016-08-18 12:35 UTC, reaperhulk commented
Is there any public API surface for getting the proto that's accessible from `runBuild`? I haven't been able to find anything, but I'm not very familiar with Docker's internals.

I've added the docs as well if the maintainers decide they want to keep the flag.

2016-08-18 12:36 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "support-compressing-build-context" git@github.com:reaperhulk/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~2
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Ammending updates the existing PR. You **DO NOT** need to open a new one.

2016-08-26 17:30 UTC, unclejack commented
@reaperhulk Can you provide some numbers to show what kind of improvement this change provides, please?

2016-08-27 11:18 UTC, reaperhulk commented
@unclejack sure! As an example:

The size of the build context for `docker/docker` right now is 40MB. With `--compress` enabled this drops to 13MB. On my machine (2013 15" rMBP 2.7GHz) generating the build context takes ~0.2s uncompressed, but ~1.4s (wallclock) compressed.

On a constrained bandwidth connection sending to a remote docker this reduction in size can be extremely valuable (I am frequently on connections where I can upload no more than 20-50k/sec when I'm outside the US/EU). Conversely, on a fast connection the overhead of gzip would quite possibly harm performance.

For a more extreme example, one of my personal projects has a docker build context size of 19MB (due to some text sitemaps). With compression enabled this drops to 2.2M, which is the difference between success and failure when sending a build context over a flaky 3G tethering connection.

I've replicated this behavior without native support in `docker` with a shell script:

```
#!/bin/bash
EXCLUDES=''
while read ignore; do
    EXCLUDES+=" --exclude='$ignore'"
done < .dockerignore

echo "Building Docker Context..."
eval tar cfz buildcontext.tar.gz --exclude='buildcontext.tar.gz' $EXCLUDES *
docker build -t my-great-project - < buildcontext.tar.gz
```

This works, but is not particularly elegant or discoverable for users who might be facing similar issues.

2016-09-28 15:04 UTC, thaJeztah commented
ping @unclejack ptal

2016-09-28 15:37 UTC, reaperhulk commented
I am happy to rebase this and resolve the conflict if the docker team decides they want to move forward on this!

2016-09-29 18:19 UTC, thaJeztah commented
We discussed this in the maintainers meeting and are generally ok with this change, so Im moving it to code review

2016-09-29 18:24 UTC, anusha-ragunathan commented on api/client/image/build.go
> +		var compression archive.Compression
Can be simplified as:
```compression := archive.Uncompressed
if options.compress {
   compression = archive.Gzip
}
```

2016-09-29 18:34 UTC, reaperhulk commented on api/client/image/build.go
> +		var compression archive.Compression
👍 done!

2016-09-29 18:54 UTC, anusha-ragunathan commented
LGTM.

2016-09-29 22:44 UTC, thaJeztah commented
can you squash your commits?

2016-09-29 23:04 UTC, reaperhulk commented
@thaJeztah done!

2016-09-30 08:26 UTC, thaJeztah commented on cli/command/image/build.go
> +			compression = archive.Gzip
Just to check before we go ahead; do we expect other compression methods to be added at some point (e.g. `compress=none|gzip|bzip2`) or is that feature creep, and does not have enough advantages to make it worth thinking about?

2016-09-30 08:34 UTC, thaJeztah commented
Thanks @reaperhulk, I left one thought (before it's too late 😇)

Also, I did a quick scan of additional changes that are needed;

- the man page needs an update as well; https://github.com/docker/docker/blob/master/man/docker-build.1.md
- the completion scripts need to be updated; would be great if you could include that in this PR, but it can be done in a follow up if you're not comfortable. For bash, around this line [contrib/completion/bash/docker#L761](https://github.com/docker/docker/blob/5280ba83e55b94b9d4973a15381e18eb10920233/contrib/completion/bash/docker#L761), and for zsh probably in this section [contrib/completion/zsh/_docker#L1510-L1520](https://github.com/docker/docker/blob/5280ba83e55b94b9d4973a15381e18eb10920233/contrib/completion/zsh/_docker#L1510-L1520)
- I _thought_ about adding it [to the builder reference](https://github.com/docker/docker/blob/master/docs/reference/builder.md), but we don't explain many other options there, so I guess it's not really needed (but let me know what you think)

Otherwise looks great

2016-09-30 18:57 UTC, reaperhulk commented on cli/command/image/build.go
> +			compression = archive.Gzip
In general you need a very fast compression algorithm to make this worthwhile unless your bandwidth to the docker daemon is very low. Alternatives like LZMA (or even bzip2) are too slow to be worth the overhead in most cases. I originally spec'd this with support for alternate schemes, but removed it as it became clear the complexity wasn't worth the (potential) future advantage.

2016-09-30 19:00 UTC, reaperhulk commented
Added the docs and shell autocomplete lines as requested!

I don't think adding to the builder reference is useful right now since as you pointed out the majority of the options aren't covered there. It would be nice to eventually find a good place to document that `--compress` can speed build context transfers to bandwidth limited remote docker daemons though.

2016-09-30 21:15 UTC, thaJeztah commented on cli/command/image/build.go
> +			compression = archive.Gzip
Yes, I thought that would be the case, but thanks for confirming (better safe then sorry when making these choices :smile:)

2016-09-30 21:18 UTC, thaJeztah requested changes
two tiny nits, but LGTM otherwise

2016-09-30 21:18 UTC, thaJeztah commented on contrib/completion/bash/docker
> +		--compress
oh! could you keep this list sorted? I know @albers likes it that way

2016-09-30 21:18 UTC, thaJeztah commented on contrib/completion/zsh/_docker
> +                "($help)--compress[Compress the build context using gzip]" \
Same here (sorry, could've mentioned that)

2016-09-30 22:46 UTC, reaperhulk commented
@thaJeztah alphabetized 😄

2016-09-30 22:50 UTC, thaJeztah approved these changes
perfect, LGTM

2016-10-05 19:57 UTC, LK4D4 commented
LGTM

2016-10-05 19:57 UTC, merged