Add -a option to service/node ps to show not running tasks
moby/moby pull request #25983
Opened 2016-08-24 14:43 UTC by jhorwit2

Reopened https://github.com/docker/docker/pull/25251 because of weird github issue. 

closes #25180
closes #25196

**- What I did**

Changed `service ps` and `node ps` to only show tasks that will be or are currently running instead of every task. This is more inline with how `docker ps` works with containers. I added an `-a` and `--all` flag to both commands to show all tasks.

Also changed `node inspect` & `node ps` to default to `self` if the node isn't specified. I kept the `self` support since the GA already went out (let me know if it's OK to kill).

**- How I did it**

Followed how `docker ps` was done with `all=1` optional flag on the http endpoint for `/tasks`.

**- How to verify it**

Look at tests. 

Run `docker service ps` & `docker node ps` on various nodes including `self` to ensure that only tasks are shown that are running or will be running w/o the `-a` flag. Also make sure that adding a filter w/o `-a` selected keeps your filter on `desired-state` (test for this). 

Run `docker node inspect` w/o the `self` flag to make sure it works (test for this). 

**- Description for the changelog**

Fixed service/node ps from showing all tasks by default & removed self arg. 

Signed-off-by: Josh Horwitz <horwitzja@gmail.com>

2016-08-24 14:44 UTC, jhorwit2 commented
cc @thaJeztah @stevvooe @aluzzardi 


Also, I'll try to remove the `self` code later today in favor of the other PR mentioned.

2016-08-24 14:44 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "jah/ps-refactor" git@github.com:jhorwit2/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~2
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Ammending updates the existing PR. You **DO NOT** need to open a new one.

2016-08-24 14:46 UTC, jhorwit2 commented
Whoops, I guess Gordon + Update Branch button = not friends.

2016-08-24 16:14 UTC, dnephin commented on api/client/node/inspect.go
> +		Args:  nil,
Instead of `nil` could you use `cobra.ArbitraryArgs` so it's more explicit about what args are accepted?

2016-08-24 16:16 UTC, jhorwit2 commented on api/client/node/inspect.go
> +		Args:  nil,
I'm gonna be removing this shortly as it's covered in another PR by someone else. The only logic that will be in this one is the `-a` flag stuff.

2016-09-20 13:36 UTC, thaJeztah commented
design LGTM. Moving to code review

2016-09-20 13:38 UTC, thaJeztah commented
for the API - should this change be versioned? (i.e., for API 1.24 ignore the "all" option, and default to "all", for API 1.25 the opposite?)

2016-09-23 23:34 UTC, stevvooe commented on api/types/client.go
> +	All    bool
This shouldn't require such a literal API change. Shouldn't an empty filter send all?

2016-09-23 23:41 UTC, stevvooe requested changes

2016-09-23 23:43 UTC, stevvooe commented
We need to be careful about the meaning of "all" here. In a cluster, this is very tricky. Most of the filtering here should be done on the client-side.

Also, right now, we mostly already show everything, so this PR would restrict to only running tasks (or preparing/starting, as well). Let's make sure that change is what we want.

cc @aluzzardi

2016-09-23 23:45 UTC, jhorwit2 commented on api/types/client.go
> +	All    bool
I was following the same pattern in `docker ps` to keep it consistent. I agree though 👍

2016-09-23 23:53 UTC, jhorwit2 commented
@stevvooe Why do you think filtering should be done client-side? The logic is already in swarm to filter tasks, which reduces bytes over the wire. The result could be pretty large in a bigger cluster. Also, costly _if_ you require quorum on each task returned. 

What exactly are you worried about with "all" here? In this case, it really is all because the daemon is requesting a list from a manager. The UX here seems very similar to that of `docker ps`.

2016-09-26 18:31 UTC, dnephin commented on docs/reference/api/docker_remote_api_v1.24.md
> +
I think v1.24 is already releases, so it shouldn't be added here.

2016-09-26 18:33 UTC, dnephin commented on integration-cli/docker_cli_swarm_test.go
> +}
This looks like it's at least a couple different cases. I think this should be split up into different tests with a descriptive name of each case.

2016-10-12 19:43 UTC, stevvooe commented
> What exactly are you worried about with "all" here?

Does "all" really mean _all_ or will it come to mean the output that is shown with `-a`?

Don't bind UX to API. We keep making this mistake and it makes this project impossible to work on because I keep finding UX buried deep in the backend.

2016-10-25 21:52 UTC, thaJeztah commented
ping @stevvooe what do you suggest for changes? Is there some way to unblock this PR?

2016-11-03 01:23 UTC, stevvooe commented
@thaJeztah By default, without a filter, the tasks endpoint should already return all. The standard mode in CLI should filter by state (all tasks `<=running`) and `-a` should be without a filter.

2016-11-03 01:26 UTC, jhorwit2 commented
Sounds good to me.

2016-11-03 14:05 UTC, jhorwit2 commented
@stevvooe PTAL.

2016-11-03 14:15 UTC, jhorwit2 commented
@thaJeztah you can remove the vendor & api tags now. 

Also, am I missing autocomplete files? Any other doc pages? Hard to remember them all 👼

2016-11-03 19:42 UTC, stevvooe approved these changes

2016-11-03 19:42 UTC, stevvooe commented
LGTM

I think we may need a few tweaks to the conditions but let's go forward with this!

2016-11-04 23:47 UTC, thaJeztah commented on docs/reference/commandline/service_ps.md
> +  -a, --all            Show all tasks (default shows tasks that are or will be running)
nit: `Show all` is one space off

2016-11-04 23:48 UTC, thaJeztah approved these changes
LGTM, moving to docs review

2016-11-04 23:50 UTC, thaJeztah commented
One nit in docs, but LGTM otherwise

> Also, am I missing autocomplete files? 

Yeah, this needs changes to those https://github.com/docker/docker/tree/master/contrib/completion, but we can also do those in a follow up if you prefer

2016-11-06 12:41 UTC, jhorwit2 commented on docs/reference/commandline/service_ps.md
> +  -a, --all            Show all tasks (default shows tasks that are or will be running)
fixed the space

2016-11-06 12:45 UTC, jhorwit2 commented
@thaJeztah follow up PR sounds good to me. I made a ticket #28108

2016-11-07 16:31 UTC, thaJeztah approved these changes
LGTM

/cc @vdemeester

2016-11-07 16:33 UTC, vdemeester approved these changes
LGTM 🐸

2016-11-07 16:33 UTC, merged

2016-11-16 21:50 UTC, aaronlehmann commented
TBH I'm not a fan of this change. It's a big UI change from 1.12.x and I think it will be confusing to users.

I just encountered it while using 1.13.0-rc1. I was trying to understand why a service wasn't starting, and `docker service ps` showed me nothing:

```
# docker service ps my_wordpress_db
NAME  IMAGE  NODE  DESIRED STATE  CURRENT STATE  ERROR  PORTS
```

I eventually discovered `docker service ps -a`, and then I could see the failed tasks.

2016-11-16 21:56 UTC, aaronlehmann commented
I would suggest changing this so that we do show failed tasks by default, if there's no currently running tasks.

2016-11-16 21:56 UTC, jhorwit2 commented
@aaronlehmann this is no different from how you would look into a container in `docker ps` that failed. You think it's good to have different UX across `ps` commands? As a user, that inconsistency has always been confusing to me.