add creation timestamp to `docker network inspect`
moby/moby pull request #26130
Opened 2016-08-30 05:04 UTC by AkihiroSuda

**- What I did**
Add creation timestamp to `docker network inspect`

**- How I did it**
- Add a new field `Created` to `engine-api/types.NetworkResource`
- Add a new method `Created()` to `libnetwork.NetworkInfo`

I'll create corresponding PRs to `engine-api` and `libnetwork` after getting lgtms.

**- How to verify it**
```
$ docker network create foo
```
Then apply this PR
```
$ docker network inspect foo | jq '.[0].Created'
"0001-01-01T00:00:00Z"
$ docker network create bar
$ docker network inspect bar | jq '.[0].Created'
"2016-08-30T04:56:13.391974977Z"
```

It should also work with embedded networks (e.g. "bridge", "host", ..)

**- Description for the changelog**
add creation timestamp to `docker network inspect`

**- A picture of a cute animal (not mandatory but encouraged)**
https://www.whoi.edu/cms/images/mediarelations/Adelie_750_342264.jpg

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2016-08-30 05:09 UTC, AkihiroSuda commented on vendor/src/github.com/docker/engine-api/types/types.go
> +	Created    string                      // String representation of the creation timestamp
Note:
- `Container.Created` is `int64`
- `ContainerJSONBase.Created` is `string`
- `Image.Created` is `int64`
- `ImageHistory.Created` is `int64`
- `ImageInspect.Created` is `string`
- `swarm/Meta.CreatedAt` (not `Create`!) is `time.Time`

https://godoc.org/github.com/docker/engine-api/types
https://godoc.org/github.com/docker/engine-api/types/swarm

2016-08-30 09:06 UTC, vdemeester commented
/cc @mavenugo @mrjana

2016-09-08 14:44 UTC, cpuguy83 commented on vendor/src/github.com/docker/engine-api/types/types.go
> +	Created    string                      // String representation of the creation timestamp
This should be a machine-parsable format. int64 is ok, I'd prefer time.Time generally.
Having the created as a string at the API level was just bad.

2016-09-09 03:19 UTC, AkihiroSuda commented on vendor/src/github.com/docker/engine-api/types/types.go
> +	Created    string                      // String representation of the creation timestamp
OK, updated PR

2016-09-20 16:02 UTC, AkihiroSuda commented
opened PR for libnetwork: https://github.com/docker/libnetwork/pull/1455
@cpuguy83 @vdemeester @mavenugo @mrjana

2016-09-20 16:35 UTC, thaJeztah commented
@AkihiroSuda is there a specific use case for this?

2016-09-20 17:39 UTC, AkihiroSuda commented
@thaJeztah Yes, I'd like to use this feature for the implementation of `docker network prune`: https://github.com/docker/docker/pull/26108#issuecomment-243327732

`docker network prune` will remove orphan networks but keep "young" networks: https://github.com/docker/docker/pull/26108#issuecomment-243327152

2016-09-20 18:11 UTC, thaJeztah commented
Thanks, that makes sense :-)

2016-09-20 18:32 UTC, thaJeztah commented
I'll go ahead and move this to code review, unless @mavenugo @mrjana have objections

2016-10-12 11:01 UTC, justincormack commented
LGTM

2016-10-12 11:26 UTC, cmingxu commented on vendor/src/github.com/docker/libnetwork/network.go
> +	n.Lock()
I'm little confuse about why we need a lock on a read statement?

2016-10-14 05:30 UTC, AkihiroSuda commented on vendor/src/github.com/docker/libnetwork/network.go
> +	n.Lock()
In current libnetwork design, read should block while write (e.g. `CopyTo()`) is in progress 
https://github.com/docker/libnetwork/blob/8dd6270f208ce449ec69140a2b7103d8190189cc/network.go#L1442-L1542

I agree we can optimize locks, but it should be another PR

2016-10-14 07:11 UTC, thaJeztah approved these changes
LGTM

2016-10-14 07:14 UTC, thaJeztah requested changes
Oh, needs a vendor of course; @AkihiroSuda can ~~you open a PR in https://github.com/docker/libnetwork for the vendored changes?~~ https://github.com/docker/libnetwork/pull/1455

2016-10-14 22:41 UTC, aboch commented
Libnetwork changes brought in via https://github.com/docker/docker/pull/27395, which is now merged.
Please rebase.

2016-10-16 08:57 UTC, AkihiroSuda commented
@aboch thank you, rebased

2016-10-16 10:57 UTC, AkihiroSuda commented
failure in windowsRS1 seems unrelated
```
09:28:38 ----------------------------------------------------------------------
09:28:38 FAIL: docker_cli_build_test.go:6549: DockerSuite.TestBuildLabelsOverride
09:28:38 
09:28:38 docker_cli_build_test.go:6641:
09:28:38     c.Assert(err, check.IsNil)
09:28:38 ... value *errors.errorString = &errors.errorString{s:"failed to build the image: Sending build context to Docker daemon 2.048 kB\r\r\nStep 1/2 : FROM scratch\nWindows does not support FROM scratch\n"} ("failed to build the image: Sending build context to Docker daemon 2.048 kB\r\r\nStep 1/2 : FROM scratch\nWindows does not support FROM scratch\n")
09:28:38 
09:29:03 
09:29:03 ----------------------------------------------------------------------
```

2016-10-19 06:11 UTC, AkihiroSuda commented
Please merge?

2016-10-19 06:14 UTC, thaJeztah commented
@AkihiroSuda looks like this needs documentation changes to the API Docs, correct?

2016-10-19 06:28 UTC, AkihiroSuda commented
@thaJeztah uh, sorry for forgetting adding that :sweat_smile: .

Updated docker_remote_api_v1.25.md in the last commit.

2016-10-19 06:34 UTC, thaJeztah commented
Almost there; can you add a note to the API changes as well? https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md#v125-api-changes

Then we're ready to go

2016-10-19 06:39 UTC, AkihiroSuda commented
done :sweat_smile:

2016-10-19 06:42 UTC, thaJeztah approved these changes
LGTM, thanks Akihiro!

2016-10-19 13:47 UTC, vdemeester approved these changes
LGTM 🐸

2016-10-19 13:48 UTC, merged

2016-10-20 00:50 UTC, allencloud commented on docs/reference/api/docker_remote_api.md
> +* `GET /networks/(name)` now returns `Created`.
Thanks @AkihiroSuda . I do like the PR, while I think maybe here is some ambiguous. First I see here, I thought return a status code of Created. I have not thought about adding a field `Created` in response.

2016-10-20 01:03 UTC, thaJeztah commented on docs/reference/api/docker_remote_api.md
> +* `GET /networks/(name)` now returns `Created`.
@allencloud yes, looking at it again, the description may be a bit short; perhaps you could open a PR to improve it?

2016-10-20 01:12 UTC, allencloud commented on docs/reference/api/docker_remote_api.md
> +* `GET /networks/(name)` now returns `Created`.
OK, done in https://github.com/docker/docker/pull/27569