Update docker_remote_api.md
moby/moby pull request #26348
Opened 2016-09-06 21:10 UTC by gerwim

**- What I did**
Changed  docker_remote_api.md
**- How I did it**
 See commit
**- How to verify it**
 See commit
**- Description for the changelog**
Since (I think cURL 7.50.1, atleast > 7.47.1) the URL has been changed for API requests.
See https://github.com/docker/docker/issues/26099#issuecomment-245007539

2016-09-06 21:10 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "gerwim-patch-1" git@github.com:gerwim/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Ammending updates the existing PR. You **DO NOT** need to open a new one.

2016-09-07 20:57 UTC, mstanleyjones commented
Please sign your commit, then LGTM

2016-09-26 18:26 UTC, thaJeztah requested changes
Oops; new GitHub review system; didn't post my review

2016-09-28 00:20 UTC, mdlinville requested changes
Please address @thaJeztah's feedback. If this can't be done by tomorrow Sep 28, this PR will need to be closed and reopened against the unified Docs repo.

2016-09-28 13:39 UTC, dnephin commented
@mstanleyjones it was my understanding that reference docs would remain in this repo, so this PR shouldn't move anywhere.

2016-09-28 21:32 UTC, mstanleyjones commented
You're right, sorry. :)

2016-10-21 18:46 UTC, closed without merging