make GetAll use client.List as the source of truth
moby/moby pull request #26354
Opened 2016-09-06 23:02 UTC by KingEmet

Required by #25851

Modified the native credential store GetAll behavior to use the store's client.List as the source of truth, rather than the file store's "auths" list. This enables 'docker login'-less native credential stores which are compatible with the current behavior of 'docker build'.

Signed-off-by: Jake Sanders <jsand@google.com>

2016-09-07 15:34 UTC, cpuguy83 commented
Tests are failing.

2016-09-07 22:30 UTC, KingEmet commented
FYI output for `make validate`:

---> Making bundle: validate-dco (in bundles/1.13.0-dev/validate-dco)
Congratulations!  All commits are properly signed with the DCO!

---> Making bundle: validate-default-seccomp (in bundles/1.13.0-dev/validate-default-seccomp)

---> Making bundle: validate-gofmt (in bundles/1.13.0-dev/validate-gofmt)
Congratulations!  All Go source files are properly formatted.

---> Making bundle: validate-pkg (in bundles/1.13.0-dev/validate-pkg)
Congratulations! "./pkg/..." is safely isolated from internal code.

---> Making bundle: validate-lint (in bundles/1.13.0-dev/validate-lint)
Congratulations!  All Go source files have been linted.

---> Making bundle: validate-test (in bundles/1.13.0-dev/validate-test)
Congratulations! No testing.T found.

---> Making bundle: validate-toml (in bundles/1.13.0-dev/validate-toml)
Congratulations!  All toml source files changed here have valid syntax.

---> Making bundle: validate-vet (in bundles/1.13.0-dev/validate-vet)
Congratulations!  All Go source files have been vetted.

---> Making bundle: validate-vendor (in bundles/1.13.0-dev/validate-vendor)
Congratulations! All vendoring changes are done the right way.

2016-09-07 23:07 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "fixbranch" git@github.com:KingEmet/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~4
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Ammending updates the existing PR. You **DO NOT** need to open a new one.

2016-09-08 17:10 UTC, KingEmet commented
Looks like the vendor issues got fixed at head, rebased

2016-09-08 17:13 UTC, cpuguy83 commented
Oh, looks like a bad rebase.

2016-09-08 17:20 UTC, KingEmet commented
Yeah my bad, still wrapping my head around how git decides the results of a default rebase. Explicitly rebased my commits onto upstream/master at head.

2016-09-08 19:40 UTC, KingEmet commented
Got there!

2016-09-15 19:58 UTC, KingEmet commented
Note that this doesn't assume that --email has been deprecated yet. Once that's the case, the call to the file store can be removed entirely and GetAll simply becomes the concatenation of all the distinct lists.

2016-09-21 23:35 UTC, KingEmet commented
Ping

2016-09-22 18:21 UTC, thaJeztah commented
ping @aaronlehmann @runcom @dmcgowan PTAL

2016-09-23 12:15 UTC, vdemeester commented
LGTM 🐸

2016-09-23 12:34 UTC, runcom commented
Janky's must be broken, how come there are edits under vendor and the build is green?

2016-09-23 12:34 UTC, runcom commented
Sgtm

2016-09-23 17:01 UTC, KingEmet commented
Rebased on head and consolidated the 2 commits, forgot that vendor check chokes on push --force. However, `make validate` succeeds and `hack/vendor.sh` is a no-op.

2016-09-23 18:17 UTC, KingEmet commented
Looks like a couple test failures at head, I'll periodically rebase.

2016-09-23 18:31 UTC, dmcgowan commented on integration-cli/fixtures/auth/docker-credential-shell-test
> +       	*)
This got converted from tabs to spaces. Looks like the echo line also has some mixed use. The rest of the file uses tabs. A sad world without gofmt :(

2016-09-23 18:35 UTC, dmcgowan requested changes
Change looks good, just one minor formatting issue.

2016-09-23 18:50 UTC, KingEmet commented on integration-cli/fixtures/auth/docker-credential-shell-test
> +       	*)
Good catch, I blame eclipse converting tab -> 2 spaces (Google's shell script format profile, I believe)

T_T
I forgot tabs vs. spaces were even a thing.

2016-09-23 20:22 UTC, KingEmet commented
CI is happy again, CR feedback integrated into the existing commit

2016-09-23 20:26 UTC, dmcgowan approved these changes

2016-09-23 20:26 UTC, dmcgowan commented
LGTM

2016-10-06 17:57 UTC, KingEmet commented
Is this just waiting for 1.12.2?

2016-10-07 14:01 UTC, vdemeester commented
ping @thaJeztah does this need documentation updates

2016-10-24 18:35 UTC, KingEmet commented
ping

2016-10-24 21:24 UTC, vdemeester approved these changes
still LGTM 🐸
Doesn't really need documentation update (but in the future we should have a small documentation or man page about it 👼)

2016-10-24 21:25 UTC, merged