Windows: Move to fstab options as per OCI
moby/moby pull request #26577
Opened 2016-09-14 18:40 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

No functional changes. Minor update to the currently hacked non-OCI compliant `spec` used in Windows to get closer to OCI compliance. Instead of an explicit readonly field, uses the `fstab` style options as per the current OCI spec (even though fstab is strictly meaningless on Windows). 

The mount structure is now identical to https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L84-L95

2016-09-14 18:50 UTC, thaJeztah commented
ping @crosbymichael @stevvooe PTAL

2016-09-15 02:15 UTC, stevvooe commented on libcontainerd/client_windows.go
> +			ReadOnly:      false}
Could you add a newline before `}`? This looks very weird.

2016-09-15 02:16 UTC, stevvooe commented on libcontainerd/windowsoci/oci_windows.go
> +	Options []string `json:"options,omitempty"`
Is this change backwards compatible?

2016-09-15 02:16 UTC, stevvooe requested changes

2016-09-15 02:20 UTC, jhowardmsft commented on libcontainerd/windowsoci/oci_windows.go
> +	Options []string `json:"options,omitempty"`
Fortunately that's not a concern on Windows yet :)

2016-09-15 02:20 UTC, jhowardmsft commented on libcontainerd/client_windows.go
> +			ReadOnly:      false}
Sure. Will do in the morning. It's what gofmt did though...

2016-09-15 02:22 UTC, jhowardmsft commented on libcontainerd/windowsoci/oci_windows.go
> +	Options []string `json:"options,omitempty"`
But yes in this case.

2016-09-15 02:22 UTC, stevvooe commented on libcontainerd/client_windows.go
> +			ReadOnly:      false}
Odd. Did it pull up the newline?

2016-09-15 17:12 UTC, jhowardmsft commented on libcontainerd/client_windows.go
> +			ReadOnly:      false}
@stevvooe Turns out if you omit the last `,`, a `}` on the same line is syntactically correct for the compiler and for godoc. However, if you put the `}` on a new line, the compiler requires the trailing comma. Learn something every day :innocent: 

Anyway, put the brace on the new line instead and pushed an update.

2016-09-15 22:27 UTC, stevvooe approved these changes

2016-09-15 22:32 UTC, jhowardmsft commented
There's some flakey tests on Linux (experimental, janky, userns, win2lin) - occurring on multiple PRs at the moment . Not related to this change at all as the change is entirely in Windows daemon only files.

Have kicked them off again to see if we can get this green.

```
11:02:52 ----------------------------------------------------------------------
11:02:52 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
11:02:52 
11:02:52 docker_cli_search_test.go:72:
11:02:52     c.Assert(outSearchCmdOfficialSlice, checker.HasLen, 3) // 1 header, 1 line, 1 carriage return
11:02:52 ... obtained []string = []string{"NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED", ""}
11:02:52 ... n int = 3
11:02:52 
11:02:53 
11:02:53 ----------------------------------------------------------------------
11:02:53 FAIL: docker_cli_search_test.go:12: DockerSuite.TestSearchOnCentralRegistry
11:02:53 
11:02:53 docker_cli_search_test.go:16:
11:02:53     c.Assert(out, checker.Contains, "Busybox base image.", check.Commentf("couldn't find any repository named (or containing) 'Busybox base image.'"))
11:02:53 ... obtained string = "NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED\n"
11:02:53 ... substring string = "Busybox base image."
11:02:53 ... couldn't find any repository named (or containing) 'Busybox base image.'
11:02:53 
11:02:54 
11:02:54 ----------------------------------------------------------------------
11:02:54 PASS: docker_cli_search_test.go:96: DockerSuite.TestSearchOnCentralRegistryWithDash	1.185s
11:02:54 PASS: docker_cli_search_test.go:19: DockerSuite.TestSearchStarsOptionWithWrongParameter	0.071s
11:02:55 
11:02:55 ----------------------------------------------------------------------
11:02:55 FAIL: docker_cli_search_test.go:103: DockerSuite.TestSearchWithLimit
11:02:55 
11:02:55 docker_cli_search_test.go:110:
11:02:55     c.Assert(outSlice, checker.HasLen, limit+2) // 1 header, 1 carriage return
11:02:55 ... obtained []string = []string{"NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED", ""}
11:02:55 ... n int = 12
11:02:55 
11:03:00 
11:03:00 ----------------------------------------------------------------------
```

2016-09-16 20:49 UTC, thaJeztah commented
LGTM

@stevvooe can you leave your LGTM? (I know the new GitHub features are cool, but I think we still need a 'LGTM')

2016-09-19 17:12 UTC, jhowardmsft commented
@mlaventure @tonistiigi PTAL. Thanks.

2016-09-19 17:13 UTC, tonistiigi approved these changes
LGTM

2016-09-19 17:13 UTC, merged