Windows: Unify OCI user struct
moby/moby pull request #26578
Opened 2016-09-14 18:48 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Convergence closer to OCI compliance - this modified the `User` struct definition in the hacked OCI spec used on Windows to match the existing `user` structure from https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L84-L95, but also adding the required user field which is required on Windows where UID/GID is meaningless.

There are no functional changes in the PR.

2016-09-15 01:14 UTC, AkihiroSuda commented on libcontainerd/windowsoci/oci_windows.go
> +	AdditionalGids []uint32 `json:"additionalGids,omitempty" platform:"linux,solaris"`
maybe `AdditionalGIDs`?

2016-09-15 02:16 UTC, jhowardmsft commented on libcontainerd/windowsoci/oci_windows.go
> +	AdditionalGids []uint32 `json:"additionalGids,omitempty" platform:"linux,solaris"`
Ah no. That is direct from the open containers runtime spec.  Just copied across.

2016-09-15 02:28 UTC, AkihiroSuda commented on libcontainerd/windowsoci/oci_windows.go
> +	AdditionalGids []uint32 `json:"additionalGids,omitempty" platform:"linux,solaris"`
ok

2016-09-15 11:40 UTC, vdemeester commented
/cc @crosbymichael @mlaventure

2016-09-15 14:43 UTC, mlaventure commented on libcontainerd/windowsoci/oci_windows.go
> +	User string `json:"user,omitempty" platform:"windows"`
AFAIK this field isn't part of OCI at the moment, could you update the comment to make it clear?

2016-09-15 14:45 UTC, mlaventure requested changes
Just a little nit, LGTM otherwise

2016-09-15 17:01 UTC, jhowardmsft commented on libcontainerd/windowsoci/oci_windows.go
> +	User string `json:"user,omitempty" platform:"windows"`
Ah, it is as of this morning :smile:, but during the review it was updated to `Username`. Updated this PR accordingly. https://github.com/opencontainers/runtime-spec/pull/565

2016-09-15 17:05 UTC, mlaventure approved these changes

2016-09-15 22:29 UTC, jhowardmsft commented
Looks like there's some flakey search tests - the same 3 tests failed on experimental, janky, userns and win2lin the first attempt. Restarted them, but the failures are completely unrelated to this PR as it's in Windows daemon only code.

2016-09-16 15:57 UTC, mlaventure commented
LGTM

2016-09-18 13:20 UTC, cpuguy83 commented
LGTM

2016-09-18 13:20 UTC, merged