Windows: OCI process struct convergence
moby/moby pull request #26579
Opened 2016-09-14 18:56 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Convergence closer to OCI compliance - this modifies the Process struct definition in the hacked OCI spec used on Windows to match the existing user structure from https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L84-L95, but also adding the required initialConsoleSize field which is required on Windows.

There are no functional changes in the PR.

2016-09-17 23:09 UTC, jhowardmsft commented
@mlaventure @tonistiigi @stevvooe PTAL. Thanks.

2016-09-19 15:39 UTC, mlaventure requested changes

2016-09-19 15:46 UTC, jhowardmsft commented on api/types/container/host_config.go
> +	ConsoleSize [2]uint   // Initial console size
Sure.

2016-09-19 15:51 UTC, jhowardmsft commented on api/types/container/host_config.go
> +	ConsoleSize [2]uint   // Initial console size
@mlaventure Updated.

2016-09-19 15:51 UTC, jhowardmsft commented on api/types/container/host_config.go
> +	ConsoleSize [2]uint   // Initial console size
Actually, thinking about this, I don't have to deal with back compat on Windows yet. I'll change it to a structure.

2016-09-19 16:09 UTC, jhowardmsft commented on api/types/container/host_config.go
> +	ConsoleSize [2]uint   // Initial console size
@mlaventure Updated to use type `Box` as per this comment in the matching OCI spec PR (https://github.com/opencontainers/runtime-spec/pull/563#r79296389). Also updated it to `ConsoleSize` as per https://github.com/opencontainers/runtime-spec/pull/563#issuecomment-247830402, dropping `Initial`. I'll open a follow-up PR to update the HCSShim APIs to also use a structure and re-vendor with the changes once this one is in.

2016-09-19 16:21 UTC, mlaventure approved these changes

2016-09-19 16:21 UTC, mlaventure approved these changes
LGTM

2016-09-19 17:03 UTC, tonistiigi approved these changes
LGTM

2016-09-19 20:52 UTC, thaJeztah commented
all green, merging

2016-09-19 20:52 UTC, merged

2016-09-20 17:07 UTC, runcom commented
@jhowardmsft @mlaventure @tonistiigi @thaJeztah this commit broke backward compatibility - old users cannot post anymore an `[2]int` and get `cannot unmarshal array into Go value of type container.Box`. There should be some sort of backward compatibility

2016-09-20 17:08 UTC, runcom commented
we should check API version for this https://github.com/docker/docker/commit/537744#diff-49c513a9f9836642d75d7f8478e8f521R316

2016-09-20 17:19 UTC, mlaventure commented
@runcom, yes it was in one of my comment.

But, if I'm not mistaken, the Windows support is only going to be considered "stable" once Windows Server 2016 RTM is released.

2016-09-20 17:20 UTC, mlaventure commented
Oh, damned. Just realized this is part of the common `HostConfig struct` :sweat:

2016-09-20 17:21 UTC, runcom commented
> Oh, damned. Just realized this is part of the common HostConfig struct

:) wanna take a peek at this? I'm going ahead and fix it if I can

2016-09-20 17:36 UTC, jhowardmsft commented
Ugh. I can fix unless you have something already in progress @runcom?

2016-09-20 17:38 UTC, jhowardmsft commented
Oh hang on, there's no need to fix this, unless it's broken Linux? Windows compatibility doesn't matter.

2016-09-20 17:41 UTC, runcom commented
> Oh hang on, there's no need to fix this, unless it's broken Linux? Windows compatibility doesn't matter.

@jhowardmsft it's broken on linux as well :( I'm trying to find some time to fix this tomorrow morning - buried into something

2016-09-20 17:56 UTC, jhowardmsft commented
Don't worry - I'll fix shortly. Sorry for not thinking about that.