PoC: Component framework - daemon architecture
moby/moby pull request #26609
Opened 2016-09-15 19:00 UTC by dnephin

This PR implements a "Component framework" (`pkg/component`) and moves the volume logic from the scattered locations around the codebase into a volume component (`components/volume`).

The goal of this framework is to improve the architecture of the docker daemon by organising functional units by their functionality. Currently:
*  the core logic of the daemon is primarily in a single large `daemon` package
* there are no clear interfaces between functional units
* adding new functionality requires expanding the already large `daemon` package , and adding files all over the code base (`daemon/`, `api/types`, `api/server/router`, `cli/command`, `cli/command/formatter`, `client`)

With the component framework:
* the "core logic" of a component is implemented behind an interface so the boundaries between components are explicit
* all the code for a functional unit should be under a single directory tree in `component/<name>`
* the daemon doesn't need to be aware of individual components. It can manage each component through generic lifecycle hooks (`Init()`, `Start()`, `Reload()`, `Shutdown()`).

Index:
* [the component framework](#diff-692effa1b0b7a9ed8c1f7bb49a977b9a)
* [the component registry](#diff-5ff940a33579f5f27b579c0816824a28)
* [the volume component](#diff-c9f56d7adb85f5324d333f7a26cc9364)
* [daemon Init()](#diff-1a1f3e7ad9b1d7584e2d3e7d0c4c3db9R558)
* [daemon Start()](#diff-d3f6b8612a6b46337de40bb2010208b8R284)
* [daemon Reload()](#diff-1a1f3e7ad9b1d7584e2d3e7d0c4c3db9R1049)
* [daemon Shutdown()](#diff-1a1f3e7ad9b1d7584e2d3e7d0c4c3db9R783)

 

Includes #26537

2016-09-16 01:28 UTC, AkihiroSuda commented on component/component.go
> +	// Interface returns the interfaced used by other Components to access the
nit: interfaced -> interface ?

2016-09-16 01:31 UTC, AkihiroSuda commented on component/component.go
> +// Events interface used by components to log events
nit: `Events` -> `EventLogger` or something else? (`Events` looks like as if it is a slice of `Event`, IMO :smiley: )

2016-09-16 01:34 UTC, AkihiroSuda commented on component/registry/registry.go
> +func (r *Registry) ForEach(f func(component.Component) error) error {
IMO one can use `for _, component := range r.All(){..}` instead of this `ForEach()`

2016-09-16 01:38 UTC, AkihiroSuda commented on components/volume/store/errors.go
> +// OperationErr is an error used by the store when operations fail
why not use `OpErr` struct directly?

2016-09-16 14:29 UTC, dnephin commented on component/component.go
> +	// Interface returns the interfaced used by other Components to access the
Ya, I should rework this comment

2016-09-16 14:29 UTC, dnephin commented on component/component.go
> +// Events interface used by components to log events
Ya, I can change this

2016-09-16 14:31 UTC, dnephin commented on components/volume/store/errors.go
> +// OperationErr is an error used by the store when operations fail
I tried that, but I ended up with a bunch of test failures on `if err != nil`. I think it has something to do with go interfaces.

2016-09-23 12:03 UTC, thaJeztah commented
ping @docker/core-engine-maintainers PTAL

2016-09-23 12:09 UTC, thaJeztah commented on component/registry/registry.go
> +package registry
Wonder if naming this "registry" will lead to confusion with the "docker registry" (for images)

2016-09-23 15:29 UTC, mlaventure commented on component/registry/registry.go
> +package registry
I agree, I got confused a bit initially. Maybe using `store` like we do elsewhere may be better?

2016-09-23 15:33 UTC, thaJeztah commented
I like this concept, but wondering; we did a lot of refactoring to make the API a standalone package, and now API types are "spread all over the place"; will this complicate other projects to consume the API code?

2016-09-23 17:43 UTC, dnephin commented on component/registry/registry.go
> +package registry
I believe we generally use the term `store` for things we're storing on disk. I don't know if that fits any better here.

I think it's kind of unfortunate that we can't re-use the term registry. This [really is a registry](https://en.wikipedia.org/wiki/Service_locator_pattern) and calling it anything else seems confusing.

2016-09-23 17:49 UTC, dnephin commented
> we did a lot of refactoring to make the API a standalone package, and now API types are "spread all over the place"; 

I think it's important we remember why we moved the types around. The goal was to ensure that there was a clear distinction between internal types and public interface types. I think we can continue to accomplish this goal without putting them all in the same package. We can actually do an even better job of this by generating the types from a spec, which is something I'm working on as part of https://github.com/docker/engine-api/issues/77. Moving the types closer to the packages where they are used shouldn't interfere with the original goal.

> will this complicate other projects to consume the API code?

It shouldn't, the types are still in a separate package from the application logic. Other projects will primarily interact with the api client. I think the client also needs to move to `components/volume/client`, but that's more involved so I haven't completed that work yet. Working with these packages shouldn't be any more difficult, they are just imported from a different path. The dependencies of the packages don't change.

2016-09-23 17:54 UTC, mlaventure commented
So a client making use of the API would have to import all components types in the end? (i.e.: `"github.com/docker/docker/components/*/types"`

2016-09-23 17:56 UTC, thaJeztah commented
Thanks for explaining @dnephin, sounds good

2016-09-23 17:59 UTC, dnephin commented
> Maybe we should keep the API Types as used when communicating with the daemon in the API package, and have an internal API's for the component.

I was thinking about this as well. I'm not sure if makes sense to have two different API types. The goal of this project is to attempt to structure the code in such a way that the components could eventually be run out-of-process. Given that goal I think that we should considering everything outside of the component as "external". So we're left with only two types: internal types, and external types (current the api types).

The component interface would then only expose methods which used the external types. We wouldn't need two api types, because other components and the client would both use the "external types". The internal types would only be used within the component.


If we were to keep api types in the current `api/types` package I think we don't really accomplish the goal of this architecture. It should be possible to add, remove, or swap a component very easily. If we have types in a separate package, outside of the component hierarchy, that task becomes more difficult.

2016-09-23 18:02 UTC, dnephin commented
> So a client making use of the API would have to import all components types in the end?

It depends on what the client is doing. Right now we assume a docker client just needs access to everything, but I think as that "everything" grows to include more and more things, the reality is that any given client might only interactive with one or two components at a time.

So a client might be concerned with images and containers, and import those two components, or it might be concerned with swarm nodes and services and import the clustering component client.

2016-09-23 18:09 UTC, mlaventure commented
@dnephin thanks for the explanation. SGTM

2016-09-23 22:20 UTC, stevvooe commented on components/volume/types/interface.go
> +	DriverList() []string
Seems orthogonal.

2016-09-23 22:20 UTC, stevvooe commented on components/volume/types/interface.go
> +	ComponentType = "volumes"
What we are calling components somewhat sounds like drivers. Can there be multiple volume components?

2016-09-23 22:21 UTC, stevvooe requested changes

2016-09-23 22:30 UTC, stevvooe commented
@dnephin I don't think `types` packages make sense in the context of most components. This only makes sense in the context of controlled APIs, and even then, the types should be local to the API with which they are used. For example, the API is a component, and the types used with the API should be used together. Where we went wrong initially was trying to share these types between components.

There is better separation today, but we need to be careful not to reintroduce this coupling unless it is a design goal.

My argument may different if we define a component as an APIController, which might make a lot more sense. For example, if a component exports a handler method, we could bind it to a URL path.

2016-09-23 22:32 UTC, stevvooe commented on component/registry/registry.go
> +package registry
`registry` has a specific meaning in docker. I would recommend having a `components` package, with registration tools.

2016-09-26 18:47 UTC, dnephin commented on component/component.go
> +	Routes() []router.Route
I'll move the controller methods to a `Controller` type

2016-09-26 18:48 UTC, dnephin commented on component/component.go
> +type Context struct {
I don't understand. This is a context, it's passing around cross-cutting things.

2016-09-26 18:50 UTC, dnephin commented on components/volume/types/interface.go
> +	ComponentType = "volumes"
No, there is only a single volume component.

2016-09-26 18:52 UTC, thaJeztah commented on component/component.go
> +type Context struct {
I think @stevvooe means possible confusion with https://blog.golang.org/context

2016-09-26 18:54 UTC, dnephin commented
> [`types`] only makes sense in the context of controlled APIs, and even then, the types should be local to the API with which they are used

Yes, that's exactly what is being done here. 

> the API is a component

I disagree. Each component has an API, the API is not a component in itself. 

> My argument may different if we define a component as an APIController, which might make a lot more sense. For example, if a component exports a handler method, we could bind it to a URL path

Instead of exposing handlers, the components expose `Routes()`, but the idea is basically the same. The routes are just handlers + metadata instructing the engine on when to call them.

2016-09-26 19:18 UTC, stevvooe commented on components/volume/types/interface.go
> +	ComponentType = "volumes"
So what is the point of a component type? Why have components if they are just singletons?

2016-09-26 19:20 UTC, stevvooe commented
> I disagree. Each component has an API, the API is not a component in itself.

The docker API is a unified, interconnected HTTP API. If we vertically couple API and implementation, we'll be back in the same place we started.

> Instead of exposing handlers, the components expose Routes(), but the idea is basically the same. The routes are just handlers + metadata instructing the engine on when to call them.

If the idea is the same, why depart from `net/http`? We can decouple the metadata and leave that as part of the registration.

2016-09-26 19:30 UTC, dnephin commented
> why depart from `net/http`?

As I understand it, `net/http` does not provide any way to specify routes. It is a very-low level interface. We are already using http://www.gorillatoolkit.org/pkg/mux, which is what we are continuing to use in this PR.

2016-11-10 16:39 UTC, LK4D4 commented
design LGTM

2016-11-17 18:54 UTC, MHBauer reviewed
Indifferent about this.

With additional work it will be structured more by complete functional unit.

The final `components/volume` directory does look very neat and tidy.

2016-11-17 18:54 UTC, MHBauer commented on component/registry/registry.go
> +	r.components[c.Provides()] = c
I know this is core stuff, but do we think there will ever be a time we'll want more than one of each of these components?

2016-11-22 14:33 UTC, cpuguy83 commented
I think a good indication of the right abstraction here is that we can have a unified way to configure and create containers (as in something just above the raw oci config for runc/containerd) and we have another layer that's for "Containers" (capital "C") that users interact with.

Right now we have 2 container abstractions in the daemon (plugins and "Containers"), not to mention the namespace dancing that libnetwork does and how we'd like to stuff even more work into containers.

So, likewise with volumes. If volumes are a singleton, then other components can't really use them because they are an abstraction for the user only.

2016-12-27 16:59 UTC, dnephin commented
This PR sat long enough that it's probably easier to start from scratch than it is to rebase, so I'm going to close it.

2016-12-27 16:59 UTC, closed without merging

2017-01-05 05:47 UTC, xproax reviewed
🥇