Generalize content addressable and reference storage
moby/moby pull request #26616
Opened 2016-09-16 00:32 UTC by tonistiigi

Currently, reference store and backing store for `imageStore` use a custom `image.ID` type. This is for maximum type safety but means that although these packages have very generic functionality, they can't be used by anything else than image package. This modifies them to be based on `digest.Digest` that is equally as safe. New helper functions are added to avoid accidental casting.

cc @aaronlehmann @dmcgowan 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

2016-09-16 00:47 UTC, dmcgowan commented on distribution/push_v1.go
> +		tagsByImage[image.ID(association.ID)] = append(tagsByImage[image.ID(association.ID)], tagged.Tag())
`image.IDFromDigest` for consistency

2016-09-16 00:54 UTC, dmcgowan commented on image/tarexport/save.go
> +		addAssoc(image.ID(id), ref)
same `IDFromDigest` for consistency

2016-09-16 00:54 UTC, dmcgowan requested changes

2016-09-16 01:02 UTC, dmcgowan approved these changes

2016-09-16 01:03 UTC, tonistiigi commented on distribution/push_v1.go
> +		tagsByImage[image.ID(association.ID)] = append(tagsByImage[image.ID(association.ID)], tagged.Tag())
Fixed

2016-09-16 01:13 UTC, aaronlehmann commented
LGTM

2016-09-16 01:16 UTC, dmcgowan commented
LGTM

2016-09-18 13:40 UTC, cpuguy83 approved these changes
LGTM

2016-09-18 13:40 UTC, merged