Windows: OCI remove first start
moby/moby pull request #26650
Opened 2016-09-16 22:33 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

This PR moves Windows a little closer to OCI compliance for the runtime spec. There are no functional changes in the PR. In the proof of concept PR https://github.com/opencontainers/runtime-spec/pull/504, there was a comment from @wking https://github.com/opencontainers/runtime-spec/pull/504#r67991039 that (rightly) the first start flag didn't belong in the spec and should be moved to the runtime.

This PR does exactly that, and handles the first start optimisation on Windows through a `CreateOption` to libcontainerd.

@mlaventure @tonistiigi PTAL.

/cc @jstarks FYI

2016-09-16 22:58 UTC, jstarks commented on libcontainerd/client_windows.go
> +			configuration.IgnoreFlushesDuringBoot = s.IgnoreFlush
`IgnoreFlush` is a little misleading since this is just during boot.

2016-09-16 22:59 UTC, jstarks requested changes

2016-09-16 23:06 UTC, jhowardmsft commented on libcontainerd/client_windows.go
> +			configuration.IgnoreFlushesDuringBoot = s.IgnoreFlush
@jstarks - updated.

2016-09-17 21:04 UTC, mlaventure commented
LGTM

2016-09-18 13:27 UTC, cpuguy83 commented
LGTM

2016-09-18 13:27 UTC, merged