Fix issue for `--fixed-cidr` when bridge has multiple addresses
moby/moby pull request #26659
Opened 2016-09-17 05:56 UTC by yongtang

**- What I did**

This fix tries to address the issue raised in #26341 where multiple addresses in a bridge may cause `--fixed-cidr` to not have the correct addresses.

The issue is that `netutils.ElectInterfaceAddresses(bridgeName)` only returns the first IPv4 address.

**- How I did it**

This fix (together with the PR created in libnetwork https://github.com/docker/libnetwork/pull/1452) changes `ElectInterfaceAddresses()` and `addresses()` so that all IPv4 addresses are returned. This will allow the possibility of selectively choose the address needed.

In `daemon_unix.go`, bridge address is chosen by comparing with the `--fixed-cidr` first, thus resolve the issue in #26341.

**- How to verify it**
This fix is tested manually, as is described in #26341:
```
brctl addbr cbr0
ip addr add 10.111.111.111/20 dev cbr0 label cbr0:main
ip addr add 10.222.222.222/12 dev cbr0 label cbr0:docker
ip link set cbr0 up
docker daemon --bridge=cbr0 --iptables=false --ip-masq=false --fixed-cidr=10.222.222.222/24
docker run --rm busybox ip route get 8.8.8.8 | grep -Po 'src.*'
src 10.222.222.0
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #26341.

This fix is related to libnetwork PR https://github.com/docker/libnetwork/pull/1452

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-09-17 12:09 UTC, cpuguy83 commented on daemon/daemon_unix.go
> +				return err
Can you use `errors.Wrap()` here from github.com/pkg/errors? It's already vendored.

2016-09-17 12:11 UTC, cpuguy83 commented on vendor/src/github.com/docker/libnetwork/drivers/bridge/interface.go
> +func (i *bridgeInterface) addresses() (netlink.Addr, []netlink.Addr, []netlink.Addr, error) {
This is pretty unwieldy and I really have no idea what each return actually is without reading the comment above.

Seems like we can at least remove the first return and just call `[0]` to get the "first ipv4 address"

2016-09-17 12:15 UTC, cpuguy83 commented on vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go
> +	if config.AddressIPv4 != nil {
Seems like a pretty common pattern in the patch.

2016-09-17 12:15 UTC, cpuguy83 requested changes
ping @mavenugo

2016-09-17 17:02 UTC, yongtang commented on daemon/daemon_unix.go
> +				return err
Fixed.

2016-09-17 17:03 UTC, yongtang commented on vendor/src/github.com/docker/libnetwork/drivers/bridge/interface.go
> +func (i *bridgeInterface) addresses() (netlink.Addr, []netlink.Addr, []netlink.Addr, error) {
Thanks @cpuguy83 the PR has been updated.

2016-09-17 17:03 UTC, yongtang commented on vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go
> +	if config.AddressIPv4 != nil {
Thanks @cpuguy83. The PR has been updated with the logic wrapped into a new func.

2016-09-17 17:04 UTC, yongtang commented
@cpuguy83 Thanks for the review. The PR has been updated. Please take a look and let me know if there are any other issues.

2016-10-21 21:30 UTC, yongtang commented on daemon/daemon_unix.go
> +	if config.bridgeConfig.FixedCIDR != "" {
Thanks @aboch for the review. The PR has been updated with the changes.

2016-10-27 17:32 UTC, yongtang commented
@aboch The PR has been rebased and libnetwork has been vendored as well. Please take a look and let me know if there are any issues.

2016-10-27 20:07 UTC, aboch commented
Thanks @yongtang I will update the issue's description to include which docker PRs the libnetwork vendoring will fix

2016-10-27 20:51 UTC, thaJeztah approved these changes
LGTM

2016-10-28 18:04 UTC, crosbymichael commented
LGTM

2016-10-28 18:05 UTC, merged

2016-11-21 00:23 UTC, rogaha commented
Thanks for working on it @crosbymichael! 👍