Modify short and flags for docker inspect
moby/moby pull request #26683
Opened 2016-09-18 05:13 UTC by yuexiao-wang

Modify short and flags for docker inspect which is inconsistent with inspect.md

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

2016-09-19 20:42 UTC, thaJeztah commented on cli/command/system/inspect.go
> +	flags.BoolVarP(&opts.size, "size", "s", false, "Display total file sizes if the type is container values are \"image\" or \"container\" or \"task\"")
Should probably be:

```
Display total file sizes if the type is \"image\", \"container\", or \"task\"
```

2016-09-19 20:42 UTC, thaJeztah reviewed
Thanks @yuexiao-wang, left a comment

2016-09-20 01:22 UTC, yuexiao-wang commented
@thaJeztah PTAL
I have applied your suggestion to the commit and updated this PR.
Thanks a lot

2016-09-20 13:03 UTC, vdemeester approved these changes
LGTM 🐸

2016-09-23 06:35 UTC, yuexiao-wang commented
@thaJeztah PTAL
Thanks!

2016-09-23 09:34 UTC, thaJeztah commented
Oh, thanks for the ping; I meant to check this because the length of the output is now really long;

```
Usage:	docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on one or multiple containers, images, volumes, networks, nodes, services, or tasks identified by name or ID.

Options:
  -f, --format string   Format the output using the given go template
      --help            Print usage
  -s, --size            Display total file sizes if the type is "image", "container" or "task"
      --type string     Return JSON for specified type
```

And (afaik) we still strive to get the output to fit within a 80 / 90-chars terminal

I wonder if we should wrap the long lines (and not sure how to deal with the ` --size` flag description in that case

ping @duglin any suggestions here?

Also; did we disable the check for output width?

2016-09-28 00:17 UTC, mdlinville approved these changes
LGTM after @thaJeztah's line wrapping comments are addressed.

2016-10-11 01:04 UTC, yuexiao-wang commented
@duglin Could you give me some suggestion?
Thanks!

2016-10-11 18:06 UTC, duglin commented
@yuexiao-wang sorry, I missed @thaJeztah's ping.  How about:
```
Display total file size (image,container,task)
```
that fits within 80 columns.

2016-10-12 04:29 UTC, yuexiao-wang commented
@duglin Thanks for your review and suggestion!
@thaJeztah's questions  :
1. Output of "Short" for the command docker inspect is so long more than 90-chars
2. not sure how to deal with the --size flag description in that case (Display total file sizes if the type is       "image", "container" or "task")

Therefore I suggest that two solution is as follows:
1.  Output of "Short"  is divided to two lines
2.  Remove "values are "image" or "container" or "task" for the option "-s" . 
     Because only support "-s"  to show total file size  when the type is container in code.
       cc @vdemeester PTAL
   
@thaJeztah  PTAL

2016-10-17 07:36 UTC, yuexiao-wang commented
@thaJeztah Could you have any suggestion about the updated PR?
Thanks!

2016-10-30 05:19 UTC, thaJeztah requested changes

2016-10-30 05:19 UTC, thaJeztah commented on docs/reference/commandline/inspect.md
> +network, node, service, or task) identified by name or ID
Can you update the man page as well? https://github.com/docker/docker/blob/master/man/docker-inspect.1.md

2016-10-31 02:24 UTC, yuexiao-wang commented on docs/reference/commandline/inspect.md
> +network, node, service, or task) identified by name or ID
@thaJeztah PTAL
Have done!

2016-10-31 20:39 UTC, thaJeztah approved these changes
LGTM

2016-10-31 20:39 UTC, merged