Ignore failure to set oom_score_adj, as happens in an unprivileged container.
moby/moby pull request #26690
Opened 2016-09-19 02:34 UTC by mwhudson

**- What I did**

Running docker 1.12 in an unprivileged container (e.g. from lxd) fails.

**- How I did it**

Found the places that adjust oom_score_adj and patch them to ignore permission denied (as e.g. systemd does: https://github.com/systemd/systemd/blob/dd8352659c9428b196706d04399eec106a8917ed/src/core/execute.c#L2014-L2028)

**- How to verify it**

https://github.com/mwhudson/debian-docker/blob/ubuntu/debian/tests/docker-in-lxd is a script designed to run in Ubuntu's autopkgtest that tests this functionality.

**- Description for the changelog**

Ignore failure to set oom_score_adj, as happens in an unprivileged container.

**- A picture of a cute animal (not mandatory but encouraged)**

![](http://folksong.org.nz/wottenwood_weta/giantweta.jpg)

Signed-off-by: Michael Hudson-Doyle <michael.hudson@canonical.com>

2016-09-19 08:56 UTC, vdemeester commented
/cc @crosbymichael @mlaventure @estesp

2016-09-19 14:14 UTC, cpuguy83 commented on daemon/daemon_unix.go
> +		// Setting oom_score_adj does not work in an
Maybe we can make a debug log at least.

2016-09-19 14:14 UTC, cpuguy83 commented on libcontainerd/remote_linux.go
> +		// Setting oom_score_adj does not work in an
Same

2016-09-19 14:15 UTC, cpuguy83 requested changes

2016-09-19 15:45 UTC, estesp commented
I think this would be a good use of the check for "am I in a user namespace?" utility function.

Maybe @cpuguy83 would be OK with not logging if we are inside a userns, but definitely we should log if we aren't in a userns and we fail to write oom-score-adj?

Example usage here: https://github.com/docker/docker/blob/master/pkg/archive/archive_unix.go#L84-L87

2016-09-19 15:46 UTC, cpuguy83 commented
Works for me.

2016-09-19 16:43 UTC, justincormack commented
Not sure, I am happy that any privileged operation that fails is just
logged if it is not absolutely required. You can disable oom behaviour
completely so this may be a noop.

On 19 Sep 2016 4:45 p.m., "Phil Estes" <notifications@github.com> wrote:

I think this would be a good use of the check for "am I in a user
namespace?" utility function.

Maybe @cpuguy83 <https://github.com/cpuguy83> would be OK with not logging
if we are inside a userns, but definitely we should log if we aren't in a
userns and we fail to write oom-score-adj?

Example usage here: https://github.com/docker/docker/blob/master/pkg/
archive/archive_unix.go#L84-L87

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/pull/26690#issuecomment-248031289>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AAdcPMEa9QPX4H9WtRFcbzAXfDHZnxu8ks5qrq4dgaJpZM4KAGFN>
.

2016-09-21 07:37 UTC, mwhudson commented
Thanks for the review! Added a log if the write fails and docker is not in a user ns. Let me know what you think.

2016-09-26 15:32 UTC, cpuguy83 approved these changes
LGTM

2016-09-26 17:35 UTC, thaJeztah commented
ping @justincormack PTAL

2016-10-11 01:34 UTC, mwhudson commented
ping?

2016-10-11 09:00 UTC, justincormack commented
LGTM

2016-10-11 09:01 UTC, merged