Speed up network list action
moby/moby pull request #26812
Opened 2016-09-22 12:03 UTC by xianlubird

**- What I did**
Speed up docker network list 

**- How I did it**
concurrent get network detail info

**- How to verify it**
run docker network ls

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-09-22 12:03 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "feature/netowrk_list_speed" git@github.com:xianlubird/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-09-22 12:20 UTC, thaJeztah commented
ping @unclejack @LK4D4 ptal

2016-09-22 12:22 UTC, unclejack commented on api/server/router/network/network_routes.go
> +			list = append(list, resource)
Isn't this a race?

2016-09-23 02:50 UTC, xianlubird commented on api/server/router/network/network_routes.go
> +			list = append(list, resource)
`networkResourceChannel ` is a channel which buffer size is 1. Then the last `goroutine` will only set one value  into channel at the same time.  This routine will read this channel synchronously, it won't cause some race condition. @unclejack

2016-09-26 23:18 UTC, LK4D4 commented
@xianlubird Can you measure performance gain with time and prints and provide it here? Thanks!

2016-09-27 01:56 UTC, xianlubird commented
root@node-1:/home/vagrant# docker network ls
    NETWORK ID          NAME                 DRIVER              SCOPE
    ce83d114a30f        bridge               bridge              local
    284fbe8ee93c        docker_gwbridge      bridge              local
    09f6fa4a3f3f        host                 host                local
    f1f0b403498b        multi-host-network1   overlay             global
    fea0480c6039        multi-host-network2   overlay            global

I run this command `docker network ls` in a machine which have 2 core and 4G memory with 110 containers. With this PR, this commander will cost about 12 seconds to return. After using this PR, it will return at about 5 seconds.

@LK4D4 @unclejack @thaJeztah @LK4D4

2016-09-27 07:32 UTC, allencloud commented
I was wondering if we can call the `Info()` via libnetwork to k/v in batch? since this pr did not decrease the call numbers.
Have we discussed the root cause of the situation?

2016-09-27 08:57 UTC, xianlubird commented
In my opinion, the method `Info()` should only return one network's info, rather than all the subnet info of this overlay.  If we want to get all endpoint of this overlay network, we'd better define a new method to this Interface of libnetwork. However, these will affect many other places. So I think concurrent read these info is the easiest way to reduce API's response time.
@allencloud WDYT ?

2016-10-25 11:47 UTC, xianlubird commented
#27729

2016-12-21 21:30 UTC, cpuguy83 requested changes

2016-12-21 21:30 UTC, cpuguy83 commented on api/server/router/network/network_routes.go
> +	go func() {
This goroutine will run forever

2016-12-23 07:53 UTC, allencloud commented
Need a rebase, @xianlubird

2016-12-23 08:50 UTC, closed without merging

2016-12-28 13:19 UTC, thaJeztah commented
@xianlubird I see something went wrong with your rebase; will you be reopening a PR to replace this?

2016-12-29 01:58 UTC, xianlubird commented
@thaJeztah I won't reopen one to replace this. I think the method of concurrent get network info isn't a good way to speed up network list action. We should add a batch method for k/v interface. So I close this PR.