Use contianer Mounts API for Swarm containers.
moby/moby pull request #26833
Opened 2016-09-22 19:31 UTC by cpuguy83

Instead of converting nicely typed service mounts into untyped `Binds`
when creating containers, use the new `Mounts` API which is a 1-1
mapping between service mounts and container mounts.

2016-09-22 19:42 UTC, cpuguy83 commented on daemon/cluster/executor/container/validate.go
> -func validateMounts(mounts []api.Mount) error {
The required validation will happens in the engine now when using the new API.

2016-09-22 21:56 UTC, thaJeztah commented
s/contianer/container/ in your commit message? :joy:

2016-10-21 18:32 UTC, stevvooe requested changes
The validation of mounts cannot be removed.

2016-10-24 17:35 UTC, cpuguy83 commented on daemon/cluster/executor/container/validate.go
> -func validateMounts(mounts []api.Mount) error {
I'm not sure I understand why the agent would do the validation when the underlying daemon is already going to do it.

2016-10-31 14:01 UTC, cpuguy83 commented
Rebased and added the swarm executor mount validation back.
I still don't think we need this in the executor since now we have validation in two places, but certainly won't hurt things (other than `os.Stat` being relatively expensive).

2016-10-31 14:18 UTC, AkihiroSuda commented
can you convert tmpfs as well? https://github.com/docker/docker/pull/26837

2016-10-31 16:19 UTC, cpuguy83 commented
@AkihiroSuda Sure, updated.

2016-11-21 07:28 UTC, AkihiroSuda commented
Are we going to have this fix in 1.13?
@cpuguy83 @stevvooe

2016-11-21 12:25 UTC, thaJeztah commented
@AkihiroSuda @cpuguy83 @stevvooe @vieux I added this to the board https://github.com/docker/docker/projects/1 for discussion

2016-11-21 23:06 UTC, stevvooe approved these changes

2016-11-21 23:07 UTC, stevvooe commented
LGTM

Don't we need this for 1.13?

2016-11-22 02:03 UTC, cpuguy83 commented
I don't think there's anything strictly depending on it for 1.13, it's just "better".

2016-11-22 02:04 UTC, cpuguy83 commented
This is rebased.

2016-11-22 02:12 UTC, AkihiroSuda commented on volume/volume_linux.go
>  // It will be deduplicated when we migrated the cluster to the new mount scheme.
please remove L14 as well? :smile:

2016-11-22 02:12 UTC, AkihiroSuda commented on integration-cli/docker_cli_service_create_test.go
> +	out, err := d.Cmd("service", "create", "--mount", "type=tmpfs,target=/foo", "busybox", "sh", "-c", "mount | grep foo && sleep 60")
nit: `tail -f /dev/null` would be better than `sleep 60`
Also, I think we should remove this service on exit

2016-11-22 02:12 UTC, AkihiroSuda commented on integration-cli/docker_cli_service_create_test.go
> +	out, err := d.Cmd("service", "create", "--mount", "type=volume,source=foo,target=/foo,volume-nocopy", "busybox", "top")
I think we should remove this service on exit

2016-11-22 18:01 UTC, cpuguy83 commented on integration-cli/docker_cli_service_create_test.go
> +	out, err := d.Cmd("service", "create", "--mount", "type=volume,source=foo,target=/foo,volume-nocopy", "busybox", "top")
Can you explain what you mean?
Everything should be cleaned up when the test is finished.

2016-11-22 18:15 UTC, AkihiroSuda commented on integration-cli/docker_cli_service_create_test.go
> +	out, err := d.Cmd("service", "create", "--mount", "type=volume,source=foo,target=/foo,volume-nocopy", "busybox", "top")
Uh, sorry, please ignore. I was just misthinking 😓

2016-11-22 19:40 UTC, tonistiigi commented
LGTM

2016-11-22 21:48 UTC, thaJeztah commented
All :green:

2016-11-22 21:48 UTC, merged