wip: Implement build cache based on history array
moby/moby pull request #26839
Opened 2016-09-22 22:11 UTC by tonistiigi

carry #24711
fixes #26065 

Adds capability to specify images used as a cache source on build. These images do not need to have local parent chain and can be pulled from other registries. User needs to make sure to only use trusted images as sources.

2016-09-22 22:27 UTC, graingert commented
Is this not going to be plugin based like https://github.com/docker/docker/pull/24711#event-799582657 ?

2016-09-22 22:32 UTC, tonistiigi commented
@graingert If you look at the contents of #24711 it is not about the plugin method. This was changed if favor of #26065 proposal a long time.

2016-09-22 23:53 UTC, tonistiigi commented
cc @stevvooe @aaronlehmann @dmcgowan @KJTsanaktsidis

2016-09-23 00:08 UTC, icecrime commented
I think design was already approved, so I'm tentatively moving to code review.

Thanks for the carry @tonistiigi!

2016-09-23 00:35 UTC, stevvooe requested changes

2016-09-23 00:40 UTC, stevvooe commented
LGTM after the small nit.

2016-09-23 00:41 UTC, aaronlehmann commented on daemon/cache.go
> +		return true
`nil` is considered a valid parent?

2016-09-23 00:43 UTC, aaronlehmann commented on daemon/cache.go
> +		return "", errors.Wrapf(err, "failed to marshal image config")
`errors.Wrap`

2016-09-23 00:43 UTC, aaronlehmann commented on daemon/cache.go
> +		return "", errors.Wrapf(err, "failed to create cache image")
`errors.Wrap`

2016-09-23 00:43 UTC, tonistiigi commented on daemon/cache.go
> +		return true
`nil` means `FROM scratch` so we ignore the parent and only check that the configuration matches

2016-09-23 01:06 UTC, aaronlehmann commented on builder/dockerfile/internals.go
>  func (b *Builder) probeCache() (bool, error) {
Comment should be updated. Right now it says "probeCache checks if `b.docker` implements builder.ImageCache and image-caching is enabled"

2016-09-23 01:27 UTC, aaronlehmann commented
LGTM after nits

2016-09-23 19:44 UTC, tonistiigi commented
@stevvooe @aaronlehmann updated

2016-09-23 21:53 UTC, stevvooe approved these changes

2016-09-23 21:53 UTC, stevvooe commented
LGTM

2016-09-23 22:18 UTC, aaronlehmann approved these changes
LGTM

2016-09-25 23:30 UTC, KJTsanaktsidis commented
LGTM too. Thanks for picking up the ball on this one! Simple and gets the job done.

2016-09-26 10:33 UTC, thaJeztah commented
Thanks! I haven't followed the full discussion, and from just the current description of this flag, it's not really clear to me how to use this feature. Would it be possible to add an actual example / workflow for using this?

2016-09-26 17:31 UTC, icecrime commented
This one probably doesn't require more docs than just the changes to the CLI and API references, so I think we're good to go :+1:

2016-09-26 17:31 UTC, thaJeztah approved these changes
discussed this, and the information is probably sufficient (we can improve in future if desired)

LGTM

2016-09-26 17:31 UTC, merged

2016-11-22 02:28 UTC, VinceMD commented
when is that due to be released?

2016-11-22 10:39 UTC, gajus commented
Where is documentation for this?

I'd like to better understand the implications of using a cache source.

2016-11-22 19:34 UTC, tonistiigi commented
@VinceMD It is included in `v1.13` that is currently in `rc` phase. Stable release expected in ~3 weeks.

@gajus Docs are in this PR. Using a source image should be compatible with build cache from local images.

2016-12-14 23:57 UTC, hstenzel commented
I'm excited for release! 

How would I use `--cache-from` if my `docker build` is itself handled by `docker-compose`? 

Thanks.

2016-12-14 23:58 UTC, tonistiigi commented
@dnephin ^

2016-12-16 20:52 UTC, dnephin commented
You wont be able to  until Compose supports this flag, and I don't see any support for it in the upcoming release.

2017-02-03 09:52 UTC, kachkaev commented
Hi guys,

Is `docker pull myimage:v1.0` strictly necessary? Won't just `docker build --cache-from myimage:v1.0 -t myimage:v1.1 .` do pull as well? https://docs.docker.com/engine/reference/builder/ or CLI help does not explain this unfortunately.

I also struggled to find some explanation of what happens if there are multiple `--cache-from`. I've got a GitLab CI script that builds an image and I'd like it to reuse previous builds to save time. The idea is to grab a previously built image with the current branch tag, then if this fails pull `master` and if both pulls fail, just build from scratch.

Should the following work for all possible states of the "cache"? Or is anything here missing or redundant?

```bash
docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME || docker pull $CI_REGISTRY_IMAGE:master || true
docker build --tag=$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME --cache-from=$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME --cache-from=$CI_REGISTRY_IMAGE:master .
```

This resolves to:
```bash
docker pull registry.gitlab.com/group/repo:my-branch || docker pull registry.gitlab.com/group/repo:master || true
docker build --tag=registry.gitlab.com/group/repo:my-branch --cache-from=registry.gitlab.com/group/repo:my-branch --cache-from=registry.gitlab.com/group/repo:master .
```

2017-02-03 10:55 UTC, gajus commented
As far as my testing goes, `docker build --cache-from` is sufficient.

However, I have written a blog post about using `--cache-from` in my GitLab EE CI setup (https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84#.z3rl5bahm) and someone commented that `docker pull` is missing.

I am not sure whats the relevance of `docker pull` when using `--cache-from` should automatically attempt to pull the image. Is that not the case?

2017-02-03 11:06 UTC, kachkaev commented
Yeah, that's what is unclear to me too. If `--cache-from` does pull an image, what will happen if it does not exist or if there is a problem with logging in? If I use multiple `--cache-from` and the first image exists, will `docker build` attempt to pull the second and the third image and reuse as much layers as possible? If at least one of the images fails to pull, with the whole build command fail? Or will it warn? Or will it just silently build from scratch?

I know that these questions can be answered through several of experiments, but it'd be great if the were documented so that people could write robust CI scripts for themselves without too much iteration.

2017-02-03 11:08 UTC, graingert commented
I'd like to know so I can add --cache-from to shipwright.

2017-02-03 22:46 UTC, tonistiigi commented
`--cache-from` does not pull if an image is not found. There have been discussions about it but the way we would like to enable it is to not pull full images but only pull data that is needed to determine the cache hit and from there decide to actually pull layers.

When using multiple `--cache-from` they are checked for a cache hit in the order that user specified. If one of the images produces a cache hit for a command only that image is used for the rest of the build.

2019-01-28 15:16 UTC, jkp commented
> `--cache-from` does not pull if an image is not found. There have been discussions about it but the way we would like to enable it is to not pull full images but only pull data that is needed to determine the cache hit and from there decide to actually pull layers.
> 
> When using multiple `--cache-from` they are checked for a cache hit in the order that user specified. If one of the images produces a cache hit for a command only that image is used for the rest of the build.

I just ran into this issue and only by digging deep through history to find this PR did I find the answer to explain the behaviour of the flag - it is not documented this way.  Suggestion: could the documentation be updated to include this detail?

2020-01-22 19:09 UTC, Jumblemuddle commented
> 
> 
> `--cache-from` does not pull if an image is not found. There have been discussions about it but the way we would like to enable it is to not pull full images but only pull data that is needed to determine the cache hit and from there decide to actually pull layers.
> 
> When using multiple `--cache-from` they are checked for a cache hit in the order that user specified. If one of the images produces a cache hit for a command only that image is used for the rest of the build.

Was this behavior ever implemented? It looks like `--cache-from` still doesn't work at all unless the full image is pulled first. (I'd like to avoid having to pull the entire image and only have layers which are useful be pulled.)

2020-01-22 19:30 UTC, tonistiigi commented
@Jumblemuddle Yes, if you use buildkit https://github.com/moby/moby/issues/34715#issuecomment-550567523