Fix some places where low-level errors bubbled up
moby/moby pull request #26858
Opened 2016-09-23 14:42 UTC by cpuguy83

Found a couple of places where pretty low level errors were never being
wrapped with any sort of context.

For example, if you try to create a local volume using some bad mount
options, the kernel will return `invalid argument` when we try to mount
it at container start.
What would happen is a user would `docker run` with this volume and get
an error like `Error response from daemon: invalid argument`.

This uses github.com/pkg/errors to provide some context to the error
message without masking the original error.

Signed-off-by: Brian Goff <cpuguy83@gmail.com>

2016-09-23 14:45 UTC, thaJeztah commented on volume/local/local.go
> +			return nil, errors.Wrap(err, "error while persistion volume options")
s/persistion/persisting/

2016-09-23 14:46 UTC, thaJeztah commented on volume/local/local.go
> +		return errors.Wrap(err, "error removing volume path")
should we include the path in the error?

2016-09-23 14:47 UTC, thaJeztah commented on volume/local/local.go
> +				return "", errors.Wrap(err, "error while mounting volume device")
is the `id` interesting information?

2016-09-23 14:47 UTC, thaJeztah commented on volume/local/local.go
> +				return errors.Wrap(err, "got error while unmounting volume")
same here for `v.path` (possibly)

2016-09-23 14:48 UTC, thaJeztah requested changes
Thanks @cpuguy83. Left some comments :)

2016-09-23 14:49 UTC, cpuguy83 commented on volume/local/local.go
> +				return "", errors.Wrap(err, "error while mounting volume device")
nope

2016-09-23 14:50 UTC, cpuguy83 commented on volume/local/local.go
> +			return nil, errors.Wrap(err, "error while persistion volume options")
🐼

2016-09-23 14:51 UTC, thaJeztah commented on volume/local/local.go
> +			return nil, errors.Wrap(err, "error while persistion volume options")
:joy:

2016-09-23 15:27 UTC, cpuguy83 commented
Updated and found a couple of more while testing some of the output.

2016-09-23 15:37 UTC, thaJeztah commented on volume/local/local.go
> +		return nil, errors.Wrap(err, "error while creating volume path")
include the path here? (sorry, must've missed that in the previous review)

2016-09-23 15:38 UTC, thaJeztah reviewed
Found one more nit, but LGTM otherwise

nice!

2016-09-23 20:08 UTC, vdemeester approved these changes
LGTM 🐸

2016-09-23 23:02 UTC, thaJeztah approved these changes
LGTM

2016-09-23 23:46 UTC, aaronlehmann commented
Use `errors.Wrapf` instead of `errors.Wrap(err, fmt.Sprintf(...))`

2016-09-23 23:48 UTC, cpuguy83 commented
I thought he took out Wrapf, but I guess not.

2016-09-23 23:59 UTC, tonistiigi commented on volume/local/local.go
> +		return errors.Wrap(err, fmt.Sprintf("error removing volume path '%s'", realPath))
Usually, the rule is that in-pkg errors shouldn't be wrapped. This may make more sense inside `removePath`. Same with `v.Mount()`.

2016-09-24 01:09 UTC, cpuguy83 commented on volume/local/local.go
> +		return errors.Wrap(err, fmt.Sprintf("error removing volume path '%s'", realPath))
Makes sense.

2016-09-24 01:09 UTC, cpuguy83 commented
Updated

2016-09-24 01:15 UTC, aaronlehmann commented
`volume/local/local.go:245: undefined: realPath`

2016-09-24 12:42 UTC, cpuguy83 commented
Ugh, fixed again.

2016-09-25 15:07 UTC, thaJeztah approved these changes
re-LGTM

2016-09-26 08:44 UTC, aaronlehmann commented
LGTM

2016-09-26 08:44 UTC, merged