Planned 1.13 deprecation: email from login
moby/moby pull request #26868
Opened 2016-09-23 18:54 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

After stumbling across https://github.com/docker/docker/pull/26863, I did a quick git grep and noticed this planned deprecation too - the use of email on login. Removing.

Haven't run CI locally - some tests may need fixing up still.

2016-09-26 21:44 UTC, LK4D4 commented
LGTM
@thaJeztah Does this need docs changes?

2016-09-26 23:51 UTC, thaJeztah commented
Oh! Actually; https://github.com/docker/docker/pull/24572. Looks like this was moved to 1.14; https://github.com/docker/docker/blob/master/docs/deprecated.md#-e-and---email-flags-on-docker-login 😅

2016-09-27 20:04 UTC, jhowardmsft commented
Updating title to 1.14 and closing for now. Will re-open once 1.14.0-dev is open

2016-11-11 20:39 UTC, jhowardmsft commented
Re-opened and rebased now it's bumped to 1.14

2016-11-12 00:10 UTC, thaJeztah requested changes
can you update docs/deprecated.md to "has been removed in 1.14"?

2016-11-12 01:33 UTC, jhowardmsft commented
@thaJeztah Of course. Updated.

2016-11-14 11:41 UTC, thaJeztah approved these changes
LGTM

2016-11-14 11:43 UTC, runcom commented
LGTM, moving to doc review even if doc review has been already done I guess :)

2016-11-15 12:08 UTC, thaJeztah commented
yup docs look good

2016-11-15 12:08 UTC, merged

2017-03-15 17:55 UTC, thaJeztah commented
With the new versioning scheme, we decided to only _remove_ deprecated options in the "quarterly" releases, so this PR will be moved to the 17.06 release (see https://github.com/docker/docker/issues/31862)