add swarm type comments and fix nits
moby/moby pull request #26885
Opened 2016-09-24 15:20 UTC by allencloud

**- What I did**
1. fix some typo in comments;
2. add more specific comment for swarm type.

As when we use docker swarm mode, we first search some details about the api. Currently, there is no specific things about swarm in /api/types/swarm, then it makes hackers inconvenient to go on. I think we had better add these in swarm types.

Signed-off-by: allencloud <allen.sun@daocloud.io>

2016-09-24 19:25 UTC, aaronlehmann commented on api/types/swarm/swarm.go
> +	// Manager is the join token workers may use to join the swarm.
s/workers/managers/

2016-09-24 19:25 UTC, aaronlehmann commented on api/types/swarm/common.go
> +// Meta is base object inherited by most of the other once.
"Meta is a base object..."

2016-09-24 19:26 UTC, aaronlehmann requested changes

2016-09-25 00:24 UTC, allencloud commented
Thanks for you review. Updated now, @aaronlehmann

2016-09-25 15:10 UTC, thaJeztah approved these changes
LGTM

2016-09-26 02:18 UTC, allencloud commented
I think something is wrong in the master's integration test:
```
18:09:49 ----------------------------------------------------------------------
18:09:49 FAIL: docker_cli_swarm_test.go:246: DockerSwarmSuite.TestSwarmContainerAutoStart
18:09:49 
18:09:49 [d668ac2d4687f] waiting for daemon to start
18:09:49 [d668ac2d4687f] daemon started
18:09:49 [d668ac2d4687f] exiting daemon
18:09:49 [d668ac2d4687f] waiting for daemon to start
18:09:49 [d668ac2d4687f] daemon started
18:09:49 docker_cli_swarm_test.go:265:
18:09:49     c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
18:09:49 ... obtained string = ""
18:09:49 ... expected string = ""
```
Since it did nothing in the code rather than comments.

2016-09-26 09:20 UTC, aaronlehmann commented
Issue for the flaky test here: https://github.com/docker/docker/issues/26588

Did you see the failure before or after #26879 was merged to master?

2016-09-26 16:21 UTC, allencloud commented
@aaronlehmann 
I did not notice this kind of error before, while recently it happens.

2016-09-26 21:33 UTC, aaronlehmann approved these changes
LGTM

2016-09-26 21:33 UTC, merged