[WIP] Add `--insecure-registry` to `docker pull`
moby/moby pull request #26886
Opened 2016-09-24 15:40 UTC by icecrime

**- What I did**

Add the ability to override the set of insecure registries (that is, the registries with which communication is allowed over HTTP, or HTTPS using a certificate from an unknown CA) at pull invocation.

This is heavily work in progress: I'm not familiar with this part of the code, so I want to make sure I'm not going in the wrong direction.

Open questions:
1. Is it ok to support overriding `--insecure-registry` for pull only, and not for push?
2. Am I correct that `newIndexInfo` will only be used for `docker search`, and is not much of an issue in that context?

Ping @aaronlehmann @tonistiigi :heartbeat:

2016-09-24 16:44 UTC, justincormack commented
Related issue is https://github.com/docker/docker/issues/8887

2016-09-24 16:53 UTC, justincormack commented
Previous PR for this https://github.com/docker/docker/pull/8935

2016-09-24 19:24 UTC, aaronlehmann commented
> Is it ok to support overriding --insecure-registry for pull only, and not for push?

I think it would be best to support it for all registry operations, including `search` and `login`. It would be inconsistent otherwise.

> Am I correct that newIndexInfo will only be used for docker search, and is not much of an issue in that context?

It looks like it's also used on the client side for `ParseRepositoryInfo`, and for `login` on the daemon side. Content trust seems to use the `Secure` flag to determine whether to use TLS when communicating with notary.

2016-09-28 00:59 UTC, stevvooe requested changes
There are some implications to this change but the initial pass looks okay. I am worried that we have to pass it as an argument everywhere: this tells me we are missing a component.

2016-09-28 00:59 UTC, stevvooe commented on api/server/router/image/backend.go
> +	PullImage(ctx context.Context, image, tag string, metaHeaders map[string][]string, authConfig *types.AuthConfig, insecureRegistries []string, outStream io.Writer) error
I'm not sure if this is relevant to the PR, but let's try to avoid argument bloat.

2016-09-28 00:59 UTC, stevvooe commented on cli/command/image/trust.go
> +		// `--insecure-registry` is specified for a pull operation with Docker Content Trust
With DCT enabled, wouldn't `insecure-registry` be more secure, as we can verify the incoming content against a central authority?

2016-09-28 01:04 UTC, cpuguy83 commented on cli/command/image/trust.go
> +		// `--insecure-registry` is specified for a pull operation with Docker Content Trust
Except we may be sending credentials to an insecure registry.

2016-09-28 01:04 UTC, cpuguy83 commented on cli/command/image/trust.go
> +		// `--insecure-registry` is specified for a pull operation with Docker Content Trust
Not that it matters wrt to DCT :)

2016-09-28 12:24 UTC, thaJeztah commented
I think at some point we discussed that https://github.com/docker/docker/pull/22337 would solve this problem by allowing users to specify insecure registries on the daemon, without the need to restart (which was a main reason for asking for `--insecure-registry` on `docker pull` / `docker push`). Also , doing so, would leave the person responsible for the _daemon_ in control.

If we agree on _this_ PR, would that imply we need to implement `--insecure-registry` also on `docker push`, `docker run`, `docker create`, `docker service create`, `docker service update`, `docker stack deploy` ?

2016-09-28 18:00 UTC, diogomonica commented
I understand that this is a common user request, but ideally we should be incentivizing the use of valid TLS certificates/easier ways of setting up validation, instead of providing a client-side override flag for all commands.

👎

2016-09-28 18:22 UTC, icecrime commented
That's exactly why I think it's worth reopening this discussion :wink: The outcome needs to be one of two things:

- :+1: We merge a patch to support `--insecure-registry` on individual operations (`pull`, `push`, and more).
- :-1: We give a *final* answer on the issue to clearly explain why this is not a good thing to do, and we lock it for good. In my opinion @diogomonica, this should go alongside a plan and a commitment to provide an easier way to set up validation.

@docker/store-maintainers My proposal is to use thumbs up/down reactions on this comment, and feel free to leave extra explanation. I'm on paternity leave for the next 2 weeks, so I'm sure this will give plenty of time to reach a consensus :innocent:

2016-09-29 03:15 UTC, tachim commented
Aren't most instances of docker running on internal networks? Why would these cases require setting up TLS validation? This is insanely frustrating for users, and it's been an open issue for **two years**: https://github.com/docker/docker/issues/8887.

2016-09-29 12:12 UTC, cpuguy83 commented
@tachim Doubtful. Also, all this is is validating that the server is who it says it is. The only difference between an insecure registry and a "secure" one is that the host trust's the CA that signed the certificate being used. There should be no point to even use `--insecure-registry`.

What if instead we had a command like `docker cert trust ./my_ca.crt`

2016-09-29 15:14 UTC, diogomonica commented
@cpuguy83 or some kind of TOFU. `--trust-insecure-registries` enables Trust-On-First-Use for all seen certificates, but fails if certificate changes for the same domain.

2016-09-29 15:32 UTC, aaronlehmann commented
That still requires setting up self-signed certs though... Some people just want to use plain HTTP on their internal network (and given the current state of affairs, I can't blame them).

2016-09-29 15:42 UTC, diogomonica commented
@aaronlehmann could be a multi-phase approach: get the ability to automatically trust self-signed certificates in a TOFU mode; enable easy, automatic generation of self-signed certificates on registries.

2016-10-03 15:07 UTC, stevvooe commented
@diogomonica @icecrime Why don't we revisit something similar to the namespace proposals?

This allowed one to have a configuration to specify policies and remotes. Adding a bunch of flags is going to make their interaction overly complex. We not only have to configure whether or not a registry is secure, but also which cert chain to use, how naming should be resolved, etc. This all needs to be considered together.

cc @dmcgowan

2016-11-03 16:22 UTC, LK4D4 commented
There was no activity for a month and nobody has time to push it forward. Closing it for now. We can revisit this later.

2016-11-03 16:22 UTC, closed without merging