buildIpamResources to only consider operational data
moby/moby pull request #26880
Opened 2016-09-24 02:51 UTC by aboch

Currently `IPAM.Config` entry in `docker network inspect` output  is being filled with the network ipam configuration data if present, otherwise with the ipam operationional data. In my opinion this is confusing and not consistent. End user expectation is to find the subnets and gateway currently used by the network.

Given this,  `buildIpamResources()` only needs to retrieve the information from the operational ipam data.

Fixes #26799 

Signed-off-by: Alessandro Boch <aboch@docker.com>

2016-09-27 23:30 UTC, mrjana commented
@aboch How do I know which one of those `IPAMConfig`s is actually config and which one is operation data? Isn't it better to separate Config and Operational data into two different slices and show them? Right now it will show up in as `IPAM.Config` which is not true.

2016-09-27 23:53 UTC, aboch commented
@mrjana I initially thought of that, but from the issues about the network inspect it seems people are looking for the operational data in the current output, and this PR fixes that.
In fact currently for all the network created with no ipam config, we report the pure ipam data.

Given we fail the network creation if we cannot satisfy the config data, I am not sure whether there is a value in showing both. 
Consider the output may get pretty verbose if we list both config and operational, for then finding that both fields would have pretty much the same content most of the time.

I though of changing `Config` to `Data` to properly identify what we are returning, but that is an API change which I would refrain to do now. And would retain the status quo where user expects to find the ipam operational data in that field.

2016-09-28 00:02 UTC, mrjana commented
@aboch Since we are talking about API representation it is fine if it is verbose as long as it provides unambiguous information. For example if somebody is writing migration code where they are reading the network state from one daemon to another, if they use the api in the current form then they can't recreate the network correctly because there is no way of knowing whether this is is user provided config or system generated operational data. I think we should follow the swarmkit api model of separating `Spec` from `Object`. User provided configuration is `Spec` which should never be modified by the system and the system generated state is in `Object`.

Since this is not going to be released in a patch release I think we can make the necessary API changes and support both versions based on API versioning design.

2016-09-28 00:10 UTC, aboch commented
@mrjana
Yes, the migration is already broken, given today there is no way to know if what we read was a user config.

Ok then, let's reuse this PR to also take care of the config/operational separation.

2016-09-28 00:13 UTC, mrjana commented
@aboch Thanks. Yes I was suggesting to make use of this PR to fix it properly since we are changing this part of the API behavior.

2016-09-28 18:12 UTC, aboch commented
@mrjana Took care of your comment, added the new `IPAM.Data` field and now `IPAM.Config` really represents the user configuration only.

PTAL when you get a chance.

2016-09-28 23:18 UTC, aboch commented
experimental to pass requires docker-py changes

2016-11-03 23:09 UTC, aboch commented
Finally all green. @mrjana PTAL.

2016-11-16 22:07 UTC, mrjana commented
LGTM

2016-12-22 19:51 UTC, cpuguy83 requested changes

2016-12-22 19:51 UTC, cpuguy83 commented on api/types/network/network.go
> +	Data    []IPAMConfig // IPAM operational data
`Data` doesn't seem like a great name... but I'm blanking on a good one atm.

2016-12-22 19:51 UTC, thaJeztah commented
@aboch would it be an idea to use the same concept as the service API; i.e. have a Spec field at the top-level, and anything inside that is the "provided" configuration

2016-12-22 19:52 UTC, cpuguy83 commented
I think this change needs to be done in the swagger spec now?

2016-12-22 20:00 UTC, aboch commented on api/types/network/network.go
> +	Data    []IPAMConfig // IPAM operational data
`Operational`, `OperationalData`, `OperationalState` ?
I am not good at names either. We need to somehow convey this info is the ipam operational state.
Hopefully somebody can propose a good one.

2016-12-22 20:04 UTC, aboch commented
@thaJeztah 
This change is backward compatible for the tools which already check the `Config` field.
I am not sure if we want to change the network inspect o/p structure now.

2016-12-22 20:56 UTC, aboch commented
@cpuguy83 Thanls. I will take care of the swagger specs

2017-01-31 22:58 UTC, LK4D4 commented
ping @aboch 
Is this still a thing or should we close it?
Thanks!

2017-01-31 23:09 UTC, aboch commented
It's still a thing, but do not have time to invastgate/fix the docker-py test failures now.

2017-02-28 23:06 UTC, icecrime commented
Let's reopen when the PR is complete then. Thanks.

2017-02-28 23:06 UTC, closed without merging