In error, the first letter is low-case letter
moby/moby pull request #26898
Opened 2016-09-26 03:14 UTC by YuPengZTE

Signed-off-by: YuPengZTE <yu.peng36@zte.com.cn>

2016-09-26 10:00 UTC, thaJeztah commented on libcontainerd/client_windows.go
> +	return errors.New("windows: Containers cannot be paused")
This should remain uppercase, as the product name is `Windows`

2016-09-26 10:00 UTC, thaJeztah commented on libcontainerd/client_windows.go
> +	return errors.New("windows: Containers cannot be paused")
Same here; this should remain uppercase, as the product name is `Windows`

2016-09-26 10:00 UTC, thaJeztah requested changes
thanks @YuPengZTE, I left two comments

2016-09-27 02:42 UTC, YuPengZTE commented on libcontainerd/client_windows.go
> +	return errors.New("windows: Containers cannot be paused")
Thanks @thaJeztah .
It has been restored.
PTAL.

2016-09-27 02:42 UTC, YuPengZTE commented on libcontainerd/client_windows.go
> +	return errors.New("windows: Containers cannot be paused")
Thanks @thaJeztah .
It has been restored.
PTAL.

2016-09-27 07:43 UTC, thaJeztah approved these changes
LGTM

2016-09-27 14:10 UTC, cpuguy83 commented
LGTM

2016-09-27 14:10 UTC, merged