fix #26890 avoid duplicate overlay drivers in info
moby/moby pull request #26891
Opened 2016-09-25 11:32 UTC by allencloud

fixes #26890 

**- What I did**
Check overlay whether it is in pluginMap, if not add it, otherwise not.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: allencloud <allen.sun@daocloud.io>

2016-09-25 14:09 UTC, thaJeztah commented on daemon/network.go
> +		pluginMap["overlay"] = true
Perhaps move these two lines above the for-loop above, and just initialize pluginList, and pluginMap there;

```go
pluginList := []string{"overlay"}
pluginMap := map[string]bool{"overlay":true}
```

2016-09-25 14:09 UTC, thaJeztah commented on daemon/network.go
> +		pluginMap["overlay"] = true
(and keep the "todo")

2016-09-25 14:09 UTC, thaJeztah requested changes

2016-09-25 15:10 UTC, vdemeester commented
/cc @anusha-ragunathan @vieux @tiborvass

2016-09-25 17:11 UTC, allencloud commented on daemon/network.go
> +		pluginMap["overlay"] = true
Updated, PTAL @thaJeztah

2016-09-25 17:37 UTC, thaJeztah commented on daemon/network.go
> +	pluginMap := map[string]bool{"overlay": true}
perhaps, while we're at it, we could move this below the `if !daemon.NetworkControllerEnabled()` below, but let me know what you think. Also may want to wait until other people reviewed this

2016-09-25 17:38 UTC, thaJeztah commented on daemon/network.go
> +	pluginMap := map[string]bool{"overlay": true}
Oh, and move the "todo" here (I see my comment may have been confusing :blush:

2016-09-25 17:45 UTC, allencloud commented on daemon/network.go
> +	pluginMap := map[string]bool{"overlay": true}
Updated again. I think move it below is better, and also moved TODO here 😄

2016-09-26 15:10 UTC, anusha-ragunathan commented on daemon/network.go
> +	// TODO: Replace this with proper libnetwork API
TODO should be moved to L363

2016-09-26 15:10 UTC, anusha-ragunathan commented on daemon/network.go
> +	// TODO: Replace this with proper libnetwork API
Rest of the change LGTM.

2016-09-26 16:19 UTC, allencloud commented on daemon/network.go
> +	// TODO: Replace this with proper libnetwork API
Updated. Thanks for your review 😄

2016-09-26 16:33 UTC, thaJeztah approved these changes
LGTM

2016-09-26 21:42 UTC, LK4D4 commented
LGTM

2016-09-26 21:42 UTC, merged