Add documentation for docker stats --format
moby/moby pull request #26892
Opened 2016-09-25 14:14 UTC by ripcurld00d

**- What I did**
Added the format documentation to stats.
Used the [`Formatting` section in the images command line documentation](https://github.com/docker/docker/blob/master/docs/reference/commandline/images.md#formatting) as an example

**- How I did it**
Add description in the [stats command line documentation](https://github.com/docker/docker/blob/master/docs/reference/commandline/stats.md)

2016-09-25 14:14 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "stats_format_docs" git@github.com:ripcurld00d/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-09-25 14:14 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "stats_format_docs" git@github.com:ripcurld00d/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-09-25 15:08 UTC, vdemeester commented on docs/reference/commandline/stats.md
> +`.MemPerc`   | Memory percentage (Available only on Linux)
`Only available on Linux` maybe ?

2016-09-25 15:09 UTC, vdemeester approved these changes
Small nit, but LGTM 🐸
/cc @thaJeztah

2016-09-25 15:11 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +`.MemPerc`   | Memory percentage (Available only on Linux)
Yes, that's slightly better

2016-09-25 15:12 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +The formatting option (`--format`) will pretty print container output
s/will pretty print/pretty prints/

2016-09-25 15:13 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +---- | ----
Minor nit: can you make the `|` align here (and for the heading)? Makes it slightly more readable when looking at the Markdown source

2016-09-25 15:14 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +When using the `--format` option, the `stats` command will either
Trying to remove future tense;

```Markdown
When using the `--format` option, the `stats` command either
outputs the data exactly as the template declares or, when using the
`table` directive, includes column headers as well.
```

2016-09-25 15:17 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +    $ docker stats --format "{{.Container}}: {{.CPUPerc}}"
Can you add a `bash` language-hint, and add a space between the "command" and the "output"? We've seen that that makes it a bit clearer what the output is, and what the actually _command_ is. Also looks like the output of your example is missing the colon; So;

    ```bash
    $ docker stats --format "{{.Container}}: {{.CPUPerc}}"

    09d3bb5b1604:        6.61%
    9db7aa4d986d:        9.19%
    3f214c61ad1d:        0.00%
    ```

2016-09-25 15:18 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +To list all containers statistics with their name, CPU percentage and memory usage in a table format you can use:
This is > 80-cahrs, please wrap;

```Markdown
To list all containers statistics with their name, CPU percentage and memory
usage in a table format you can use:
```

2016-09-25 15:18 UTC, thaJeztah commented on docs/reference/commandline/stats.md
> +    $ docker stats --format "table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}"
Can you do the same here? (Bash-hint, and space between command and output)

2016-09-25 15:19 UTC, thaJeztah requested changes
Thanks @ripcurld00d! I left some comments. Also, can you update the man-page with the same changes? https://github.com/docker/docker/blob/master/man/docker-stats.1.md

2016-09-25 19:42 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +`.MemPerc`   | Memory percentage (Available only on Linux)
:+1:

2016-09-25 19:42 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +The formatting option (`--format`) will pretty print container output
:+1:

2016-09-25 19:42 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +---- | ----
:+1:

2016-09-25 19:42 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +When using the `--format` option, the `stats` command will either
:+1:

2016-09-25 19:43 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +To list all containers statistics with their name, CPU percentage and memory usage in a table format you can use:
:+1:

2016-09-25 19:46 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +    $ docker stats --format "table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}"
:+1:

2016-09-25 19:46 UTC, ripcurld00d commented on docs/reference/commandline/stats.md
> +    $ docker stats --format "{{.Container}}: {{.CPUPerc}}"
:+1:

2016-09-25 19:47 UTC, ripcurld00d commented
@thaJeztah @vdemeester thanks a lot!
@thaJeztah I am working now on the man page. Thanks for noticing me :smile:

2016-09-26 06:28 UTC, ripcurld00d commented
@thaJeztah OK, I added `--format` to the stats man page. :rocket:

2016-09-26 08:51 UTC, thaJeztah approved these changes
LGTM, thank you!

2016-09-26 08:52 UTC, merged

2016-09-26 08:57 UTC, ripcurld00d commented
@thaJeztah the pleasure is all mine! I like Docker a lot and giving back to the community is the least that I can do.