The VS and dot is seprated
moby/moby pull request #26914
Opened 2016-09-26 08:41 UTC by YuPengZTE

Signed-off-by: YuPengZTE <yu.peng36@zte.com.cn>

2016-09-26 09:05 UTC, thaJeztah commented on docs/userguide/storagedriver/overlayfs-driver.md
> +For comparison between `overlay` vs. `overlay2`, please also refer to [Select a
I think `vs` should actually be "and" here ("comparison between Foo and Bar")

2016-09-26 09:08 UTC, thaJeztah requested changes
one suggestion, but looks good once addressed

2016-09-26 09:35 UTC, YuPengZTE commented on docs/userguide/storagedriver/overlayfs-driver.md
> +For comparison between `overlay` vs. `overlay2`, please also refer to [Select a
Thanks @thaJeztah 
The 'between and' is better, and I see 'please also refer to [Select a
storage driver](selectadriver.md#overlay-vs-overlay2)', so is it better that 'For comparison between `overlay` vs `overlay2`' is changed to 'For  `overlay` vs `overlay2`' ?

2016-09-26 09:38 UTC, thaJeztah commented on docs/userguide/storagedriver/overlayfs-driver.md
> +For comparison between `overlay` vs. `overlay2`, please also refer to [Select a
I think I actually prefer 

```Markdown
For a comparison between `overlay` and `overlay2`,
please refer to ....
```

Just `For overlay vs overlay2` is not very descriptive

2016-09-26 10:42 UTC, justincormack commented on docs/userguide/storagedriver/overlayfs-driver.md
> +For comparison between `overlay` vs. `overlay2`, please also refer to [Select a
The `.` is definitely incorrect here anyway. You don't put a dot unless there are omitted letters at the end. And between .. versus is wrong too. Use `and`.

2016-09-26 10:44 UTC, thaJeztah commented on docs/userguide/storagedriver/overlayfs-driver.md
> +For comparison between `overlay` vs. `overlay2`, please also refer to [Select a
Seems that US English uses `vs.`, and British English uses `vs` (looked that up earlier)

2016-09-27 02:49 UTC, YuPengZTE commented on docs/userguide/storagedriver/overlayfs-driver.md
> +For comparison between `overlay` vs. `overlay2`, please also refer to [Select a
Thanks @thaJeztah and @justincormack .
PTAL.

2016-09-28 00:12 UTC, mstanleyjones commented
The best fix is to write around 'vs'. It is Latin, and it's not great to include Latin in docs that will be consumed by people with different levels of comfort in English. Why not change these headings to "Differences between A and B"? If you must use "versus", just spell it out. However, I suspect that these changes may conflict with PR #23791

2016-10-10 21:31 UTC, thaJeztah commented
I'm not sure it's worth changing this (just adding the `.`), also the docs/userguide/storagedriver/overlayfs-driver.md file is now published from the https://github.com/docker/docker.github.io repository, so I think it's best to close this PR.

Thanks for contributing though @YuPengZTE !

2016-10-10 21:31 UTC, closed without merging