adde
moby/moby pull request #27083
Opened 2016-09-30 23:58 UTC by RobSkye

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

…AppArmor is enabled or not. It is set in NewDaemon using sysInfo information.

Signed-off-by: Roberto Muñoz Fernández <robertomf@gmail.com>

SetSecurityOptions() now is declared in container_linux.go and container_windows.go in order to set platform dependent security information. In container_linux, AppArmorProfile is set to the default profile when daemon supports apparmor and no profile was defined in the client.

Signed-off-by: Roberto Muñoz Fernández <robertomf@gmail.com>

2016-10-01 00:05 UTC, thaJeztah commented
@RobSkye did you close this on purpose, or by accident?

2016-10-01 00:07 UTC, RobSkye commented
By Accident...laptops and beds are bad combination....I'm editing the description too.

2016-10-01 00:10 UTC, thaJeztah commented
GitHub buttons are also a disaster at times, haha, no worries, thanks!

2016-10-01 00:12 UTC, thaJeztah commented
Guess this fixes https://github.com/docker/docker/issues/25935

2016-10-01 00:17 UTC, RobSkye commented
Yes.

2016-10-07 18:09 UTC, tonistiigi reviewed
Please squash the commits as well.

2016-10-07 18:09 UTC, tonistiigi commented on daemon/container_linux.go
> +		container.AppArmorProfile = "docker-default"
Also need to handle `--privileged`. See https://github.com/docker/docker/blob/master/daemon/oci_linux.go#L709-L714

Even with `privileged` fixed this is a slight behavioral change. If apparmor is enabled after container was created this var will not change. I think if this is only called on inspecting single container we can lazy load the value like we do in container startup.

2016-10-10 16:57 UTC, thaJeztah commented
@RobSkye can you address @tonistiigi's comments, and squash your commits?

2016-10-11 16:03 UTC, RobSkye commented
With the latest push, if you change apparmor configuration and apparmor completely disappear from the dockerhost (I have some comments about this below) the AppArmorProfile is updated with the expected configuration but still there is some issues we have to address:

1. If you do an inspect after an apparmor change and before the start of the container, still shows the old AppArmorProfile.
2. If you create the container with apparmor disabled but with --security-opt apparmor=someprofile, when you enable apparmor in dockerhost, AppArmorProfile will be "docker-default".
3. Apparmor status is checked ONLY checking the existence of /sys/kernel/security/apparmor and is not a good method, you can have apparmor completely shutdown and still that directory exists. see https://github.com/docker/docker/blob/master/pkg/sysinfo/sysinfo_linux.go#L57
4. You can run a container with --security-opt apparmor=someprofile and someprofile will be set in AppArmorProfile whether or not exists as an valid apparmor profile.

I don't know if addressing this issues are in the scope of the main issue. I' have the feeling that implementing a real-time check of the security configuration of containers will require more than a "slight behavioral change". 

I have some ideas of adding security information in the "docker ps" command and a more detailed "docker security" showing all the security settings of a container.

I look forward to your feedback.

2016-10-12 17:35 UTC, tonistiigi commented on daemon/container_linux.go
> +			container.AppArmorProfile = defaultApparmorProfile
Don't understand this. Why is unconfined profile switched back to default.

2016-10-12 18:02 UTC, RobSkye commented on daemon/container_linux.go
> +			container.AppArmorProfile = defaultApparmorProfile
That is actually an error. I was trying to restore "docker-default" to the unconfined containers if the containers were created after apparmor was enabled but i didn't notice the effect of enabling apparmor to the containers with --security-opt app-armor:unconfined.

I'm gonna think on how manage this correctly.

2016-10-12 22:03 UTC, RobSkye commented
I did a little refactor of the patch in the last commit. Now inspect always shows an empty AppArmorProfile when the container is stopped ( maybe empty is not the best value but this can be changed easily to undefined, unconfined or something more clarifying).

The correct value of AppArmorProfile is set at container startup using the actual status of apparmor, the privileged flag and the configured apparmor settings using --security-opt.

2016-11-03 16:39 UTC, LK4D4 commented
@RobSkye I'm not sure that I like an idea of clearing profile on stopped containers - it's breaking change, and indeed it might be useful for debugging. Otherwise, the patch is ok for me.

2016-12-01 18:16 UTC, mlaventure commented
ping @RobSkye , needs a rebase.

I personally don't think showing the previous apparmor profile when inspecting old containers is an issue to be fixed otherwise. It properly reflect how this container was run.

2016-12-04 15:32 UTC, RobSkye commented
Ok, i'll delete that part and rebase/commit.

2016-12-19 10:55 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "25935-show-apparmor-default-profile-in-docker-inspect" git@github.com:RobSkye/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353964288
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-01-12 19:52 UTC, thaJeztah commented
ping @tonistiigi @LK4D4 PTAL what's the status on this one?

2017-01-12 21:29 UTC, tonistiigi requested changes

2017-01-12 21:29 UTC, tonistiigi commented on daemon/container_linux.go
> +func (daemon *Daemon) fixSecurityOptions(container *container.Container) error {
I'd call this `saveApparmorConfig`

2017-01-12 21:29 UTC, tonistiigi commented on daemon/container_linux.go
> +	if daemon.apparmorEnabled && !container.HostConfig.Privileged {
This shows `unconfined` when apparmor is disabled.

2017-01-12 22:51 UTC, RobSkye commented on daemon/container_linux.go
> +	if daemon.apparmorEnabled && !container.HostConfig.Privileged {
Yes, do you want to show "Disabled" instead?

2017-01-12 22:53 UTC, tonistiigi commented on daemon/container_linux.go
> +	if daemon.apparmorEnabled && !container.HostConfig.Privileged {
I think empty would do. `unconfined` implies that special privileged profile was applied(at least to me).

2017-01-19 19:12 UTC, LK4D4 commented
ping @RobSkye 
Would you mind to fix Tonis' comments? Then we can merge

2017-01-30 15:44 UTC, LK4D4 commented
LGTM
ping @tonistiigi

2017-01-30 15:44 UTC, LK4D4 approved these changes

2017-01-30 18:05 UTC, tonistiigi approved these changes
LGTM

2017-01-30 18:05 UTC, merged