Update bind modes with nocopy (fixes #27029)
moby/moby pull request #27089
Opened 2016-10-01 08:24 UTC by dmandalidis

2016-10-03 13:54 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path:ro[,nocopy]` to make the bind mount read-only inside the container. Volume contents are initialized with data from `container-dest`, provided that the volume
Not sure where this `is not declared as VOLUME` came from, it's not true.

2016-10-03 14:00 UTC, dmandalidis commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path:ro[,nocopy]` to make the bind mount read-only inside the container. Volume contents are initialized with data from `container-dest`, provided that the volume
AFAIK, if container-dest is declared as VOLUME, data are not copied. I 'll check again

2016-10-08 07:18 UTC, dmandalidis commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path:ro[,nocopy]` to make the bind mount read-only inside the container. Volume contents are initialized with data from `container-dest`, provided that the volume
Checked again, nothing is copied if container-dest is declared as VOLUME

2016-10-08 07:38 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path:ro[,nocopy]` to make the bind mount read-only inside the container. Volume contents are initialized with data from `container-dest`, provided that the volume
Please check again.
All volumes (and not bind mounts) should be getting data copied to the volume unless `nocopy` is specified.

2016-10-08 07:49 UTC, dmandalidis commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path:ro[,nocopy]` to make the bind mount read-only inside the container. Volume contents are initialized with data from `container-dest`, provided that the volume
You 're right, my mistake. I 've updated the PR

2016-10-11 15:40 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path:ro[,nocopy]` to make the bind mount read-only inside the container. Volume contents are initialized with data from `container-dest`, provided that the volume
Given that there's more options possible than just `:ro` and `no copy` (such as `Z` and `z`), I wonder if we should use `[options]` here, and list the available options (mentioning that it's a comma-separated list). For example this is how it's described in the `docker run` CLI reference;

```
 -v, --volume value                Bind mount a volume (default []). The format
                                    is `[host-src:]container-dest[:<options>]`.
                                    The comma-delimited `options` are [rw|ro],
                                    [z|Z], [[r]shared|[r]slave|[r]private], and
                                    [nocopy]. The 'host-src' is an absolute path
                                    or a name value.
```

That format is not ideal, but a bullet-list could work (and probably more readable) also have a look at https://github.com/docker/docker/pull/26791, which reorganizes the run-reference

2016-10-20 04:57 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[z|Z]` to indicate that two containers share the same volume or that a volume is private, respectively.
This probably should mention "security labels"; some info can be found here https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volumes-from-container---volumes-from

2016-10-20 04:58 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[z|Z]` to indicate that two containers share the same volume or that a volume is private, respectively.
@cpuguy83 can you have another look as well to check if the facts are okay?

2016-11-03 16:24 UTC, LK4D4 commented
ping @thaJeztah

2016-12-01 18:12 UTC, mlaventure commented
let's ping @thaJeztah again :angel:

2017-01-24 02:10 UTC, AkihiroSuda commented
@cpuguy83 @thaJeztah  PTAL?

2017-01-24 13:47 UTC, cpuguy83 requested changes

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `volume_name:container_path[:options]` to bind-mount a volume managed by a volume plugin into the container.
`by a volume driver`

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +        `options` can be a comma-delimited list of:
`options` is a comma-delimited list of

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[z|Z]` The z option tells Docker that two containers share the volume content. As a result, Docker labels the content with a shared content label. Shared volume labels allow all contain
I would take docker out of the mix here, as it's really not telling docker anything, just passing through to the underlying system.

Maybe more like:

The \`z\` (lower) option sets the security label of the bind mount to \`shared\`, allowing other containers to access it. The `Z` (capital) sets the security label to `private`, which prevents any process outside this container from accessing the data. If left unset with selinux set to enforcing mode, the security label will not be modified and the container may not be able to access the data in the bind mount. This option is only applicable to bind mounts from the host.

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[[r]shared|[r]slave|[r]private]` to specify the propagation property only for bind mounted volumes and not for internal volumes or named volumes. For mount propagation to work source mo
Maybe a link to https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt for more details

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[[r]shared|[r]slave|[r]private]` to specify the propagation property only for bind mounted volumes and not for internal volumes or named volumes. For mount propagation to work source mo
s/to specify/specifies/

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `nocopy` to disable automatic copying of data from the container path to the volume, use the `nocopy` flag. The `nocopy` flag can only be set on named volumes.
s/to disable/disables/

2017-01-24 13:47 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[ro|rw]` to mount a volume read-only or read-write, respectively. By default, the volumes are mounted read-write.
s/to mount/mounts/

2017-01-24 13:48 UTC, cpuguy83 commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[[r]shared|[r]slave|[r]private]` to specify the propagation property only for bind mounted volumes and not for internal volumes or named volumes. For mount propagation to work source mo
For these changes, maybe check with @mstanleyjones.
Not sure what the standard should be here.

2017-01-24 16:11 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[ro|rw]` to mount a volume read-only or read-write, respectively. By default, the volumes are mounted read-write.
s/the volumes/volumes/

2017-01-24 17:56 UTC, mstanleyjones commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[[r]shared|[r]slave|[r]private]` to specify the propagation property only for bind mounted volumes and not for internal volumes or named volumes. For mount propagation to work source mo
I think this whole thing would be better as a table with each of these permutations and what it does, followed by some illustrative examples.

2017-01-24 17:56 UTC, mstanleyjones commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[ro|rw]` to mount a volume read-only or read-write, respectively. By default, the volumes are mounted read-write.
Does `rw` actually even do anything, since it's the default?

2017-01-24 17:58 UTC, mstanleyjones commented on docs/reference/api/docker_remote_api_v1.23.md
> +           + `[z|Z]` The z option tells Docker that two containers share the volume content. As a result, Docker labels the content with a shared content label. Shared volume labels allow all contain
Make sure you label `z` and `Z` with backticks everywhere they occur. I'd use a bullet for each of them if you are not going to turn the whole thing into a table. Combining them might lead skim-readers to think that they both do the same thing.

2017-01-26 17:17 UTC, LK4D4 commented
@mstanleyjones can we carry this please? Thanks!

2017-01-26 20:12 UTC, mstanleyjones commented
I added a commit to address the comments left so far. I didn't turn the list into a table, since it is part of a larger multiply-nested list and tables can't easily go into lists. PTAL @LK4D4 @cpuguy83 and check my re-wording.

2017-01-26 22:02 UTC, LK4D4 commented
ping also @thaJeztah

2017-02-10 15:27 UTC, mlaventure commented
ping @thaJeztah @cpuguy83

2017-02-10 15:29 UTC, mlaventure approved these changes
LGTM

2017-02-10 15:30 UTC, cpuguy83 approved these changes
LGTM

2017-02-10 15:30 UTC, merged