nocopy is only applicable for named volumes (fixes #27046)
moby/moby pull request #27090
Opened 2016-10-01 08:42 UTC by dmandalidis

2016-10-02 12:21 UTC, vdemeester commented
@dmandalidis could you add a more *verbose* description on the PR 👼

/cc @cpuguy83

2016-10-02 12:53 UTC, cpuguy83 commented
"Can only be set on", or "is only supported for"

2016-10-21 18:30 UTC, mlaventure requested changes

2016-10-22 05:24 UTC, dmandalidis commented on docs/reference/api/docker_remote_api_v1.25.md
>             + `volume-name:container-dest` to bind-mount a volume managed by a
You 're right but I 'm waiting for https://github.com/docker/docker/pull/27089 to avoid doing the same thing twice.

2016-11-03 16:24 UTC, LK4D4 commented
ping @dmandalidis and @thaJeztah for resurrecting this PRs

2016-11-07 06:11 UTC, dmandalidis commented
@LK4D4 I 'm waiting for #27089 to avoid doing the same thing twice.

2017-01-26 17:17 UTC, LK4D4 commented
pinged @mstanleyjones in #27089

2017-03-16 18:44 UTC, thaJeztah commented
@dmandalidis https://github.com/docker/docker/pull/27089 was merged; do you still want to work on this?

2017-03-16 20:05 UTC, dmandalidis commented
@thaJeztah Nope, thanks

2017-03-16 20:09 UTC, thaJeztah commented
Ok, let's close for now, I'll add it to my list if I have time to carry. Thanks @dmandalidis!!

2017-03-16 20:09 UTC, closed without merging