add a section to plugin manifest for kernel to be modprobed before en…
moby/moby pull request #27135
Opened 2016-10-04 01:16 UTC by vieux

+cleanup documentation

ping @anusha-ragunathan @tiborvass

2016-10-04 18:06 UTC, vieux commented
ping @anusha-ragunathan

2016-10-04 18:19 UTC, anusha-ragunathan commented on api/types/plugin.go
> +	PluginSetting
What is the need for `PluginSetting` here? It doesnt seem to be used anywhere in the code.

2016-10-04 18:21 UTC, anusha-ragunathan commented
Most importantly, Kernel Modules should *always* ask user permission. It should be part of ComputePrivileges. https://github.com/docker/docker/blob/master/plugin/v2/plugin_experimental.go#L124

2016-10-04 18:24 UTC, vieux commented on api/types/plugin.go
> +	PluginSetting
it's never used for now right ? my understanding was at some point `docker plugin set` will allow the user to change the modules, but maybe it shouldnt ?

2016-10-04 18:49 UTC, anusha-ragunathan commented on api/types/plugin.go
> +	PluginSetting
I dont think it should be settable by user.

2016-10-05 00:34 UTC, vieux commented
@anusha-ragunathan PTAL

2016-10-05 22:07 UTC, anusha-ragunathan commented
@vieux : Can you provide output when you tested this?

2016-10-06 12:47 UTC, thaJeztah requested changes

2016-10-06 12:47 UTC, thaJeztah commented on docs/extend/manifest.md
> +          types indicate what interface(s) the plugin currently implements.
This document is now published from https://github.com/docker/docker.github.io, so this change should be reverted, and reopened as a PR in that repository

2016-10-06 13:29 UTC, cpuguy83 commented
What's the use-case for this?
If the plugin requires a kernel module, presumably they will have to have compiled the module for the kernel. What utility is there at that point in probing for the module?

2016-10-06 17:29 UTC, anusha-ragunathan commented
@cpuguy83 : The use case is, when the plugin requires modprobing a kernel module that is part of the standard Linux kernel. For example, open-iscsi is the standard iSCSI initiator and the plugin would require it to modprobed, to be functional. 
This is not intended to download and/or compile the module for the underlying host kernel. It is strictly to modprobe a module that exists across all kernels. If the modprobe fails, the plugin install will fail.

2016-10-06 20:43 UTC, anusha-ragunathan commented
It's a very corner case and very low in priority. Lets close this now and reopen if there are more such usecases

2016-10-11 22:54 UTC, justincormack commented
Generally kernel modules autoload, I don't think you need to manually modprobe them very often at all.

2016-10-20 18:51 UTC, thaJeztah commented on docs/extend/manifest.md
> +          types indicate what interface(s) the plugin currently implements.
@vieux this was reconsidered, so can remain in this PR

2016-10-20 19:14 UTC, thaJeztah commented
Closing, as this was reopened by mistake, and it's no longer needed

2016-10-20 19:14 UTC, closed without merging