Update containerd and runc
moby/moby pull request #27160
Opened 2016-10-05 14:07 UTC by mlaventure

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--

Fixes #25880, #25470

2016-10-05 16:26 UTC, justincormack commented
LGTM

2016-10-05 16:28 UTC, justincormack commented
Doesn't update the libcontainer vendoring, do we want to do that too?

2016-10-05 16:38 UTC, mlaventure commented
Oh, yes, thanks for pointing it out!

2016-10-05 18:13 UTC, vieux commented
LGTM

2016-10-05 18:35 UTC, mlaventure commented
There's another bug in `containerd-shim` that I'm in the process of fixing. If we could wait until I update this. The PR is [here](https://github.com/docker/containerd/pull/326)

2016-10-05 18:54 UTC, mlaventure commented
Updated with aforementioned fix.

2016-10-05 20:22 UTC, LK4D4 commented
@mlaventure hah, rebase :)
LGTM though

2016-10-05 20:26 UTC, mlaventure commented
Rebased :)

2016-10-05 20:35 UTC, LK4D4 requested changes

2016-10-05 20:35 UTC, LK4D4 commented on hack/vendor.sh
> +clone git github.com/opencontainers/runc  02f8fa7863dd3f82909a73e2061897828460d52f # libcontainer
some leading space here

2016-10-05 20:41 UTC, LK4D4 commented on hack/vendor.sh
> +clone git github.com/opencontainers/runc  02f8fa7863dd3f82909a73e2061897828460d52f # libcontainer
Containerd commit should be changed here too I think

2016-10-05 20:43 UTC, LK4D4 approved these changes

2016-10-05 20:48 UTC, mlaventure commented on hack/vendor.sh
> +clone git github.com/opencontainers/runc  02f8fa7863dd3f82909a73e2061897828460d52f # libcontainer
ditto

2016-10-06 00:16 UTC, justincormack commented
The commit for github.com/godbus/dbus in https://github.com/opencontainers/runc/blob/master/Godeps/Godeps.json is v3, not v4.0.0 as it is on docker/docker which is probably an error - noticed this when looking at the vendoring before.

2016-10-06 00:20 UTC, justincormack commented
Also github.com/syndtr/gocapability needs updating and also maybe github.com/golang/protobuf/proto

2016-10-06 14:58 UTC, mlaventure commented
@justincormack 

- `libnetwork` is using v4 for `godbus/dbus` (and runc v3), hence the difference
- for `golang/protobuf`, `containerd` has the most recent vendoring followed by `swarmkit` then `runc` (`docker/docker` has the one from `containerd` atm)
- `libnetwork` is using a older commit than `runc` for `syndtr/gocapability` (which is the one used in `docker/docker` atm)

How do we reconcile this mess? :sweat_smile:

2016-10-06 15:02 UTC, LK4D4 commented
@mlaventure I'd better ignore deps of deps for now and use docker as source of truth - it has most extensive tests among all other projects.

2016-10-06 15:47 UTC, thaJeztah commented
ping @mlaventure - per https://github.com/docker/docker/issues/26995#issuecomment-251742744 this fixes a regression in 1.12.2; are all these changes good to go into 1.12.2?

2016-10-06 15:52 UTC, justincormack commented
@thaJeztah there are new features in here eg ambient capabilities.

2016-10-06 15:53 UTC, justincormack commented
@mlaventure ugh. ok. LGTM, as I don't think this should matter now for the uses here.

2016-10-06 15:54 UTC, mlaventure commented
@thaJeztah going to have to make a different PR for 1.12.2, the `containerd` used in it is based on a branch to avoid pulling all the GRPC changes.

I've opened a PR [here](https://github.com/docker/containerd/pull/327)

Will make one on 1.12.x branch once it's merged

2016-10-06 15:59 UTC, thaJeztah commented
@mlaventure clear, thanks!

2016-10-06 17:36 UTC, merged

2016-10-09 09:05 UTC, thaJeztah commented
ping @mlaventure - was a bump / Cherry-pick for 1.12.2 created?

2016-10-09 09:24 UTC, justincormack commented
Yes I think so.

On 9 Oct 2016 11:05 a.m., "Sebastiaan van Stijn" <notifications@github.com>
wrote:

> ping @mlaventure <https://github.com/mlaventure> - was a bump /
> Cherry-pick for 1.12.2 created?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/27160#issuecomment-252474313>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAdcPDt6U9ly4BquHLPMnFlQQlfBtlgSks5qyK5sgaJpZM4KO2Qm>
> .
>

2016-10-10 14:33 UTC, mlaventure commented
@thaJeztah 

Yes it was: https://github.com/docker/docker/pull/27196