add changelog lines for swarmkit and libnetwork
moby/moby pull request #27216
Opened 2016-10-07 17:23 UTC by andrewhsu

Add missing changelog lines for 1.12.2-rc3 release.

🐲

2016-10-07 17:23 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "add-missing-changelog" git@github.com:andrewhsu/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-10-07 17:25 UTC, andrewhsu commented
/cc @mlaventure @vieux @mavenugo @aboch

2016-10-07 17:29 UTC, mlaventure requested changes

2016-10-07 17:29 UTC, mlaventure commented on CHANGELOG.md
> + - Do not add names to ingress network [docker/libnetwork#1489](https://github.com/docker/libnetwork/pull/1489)
I'd specify service, e.g.: `Do not add service names...`

/cc  @mrjana

2016-10-07 17:29 UTC, andrewhsu commented
@mlaventure do we need verbiage for 3377b4b9b755082070c942cb2a73cec869f063ca ?

2016-10-07 17:31 UTC, andrewhsu commented on CHANGELOG.md
> + - Do not add names to ingress network [docker/libnetwork#1489](https://github.com/docker/libnetwork/pull/1489)
done

2016-10-07 17:37 UTC, mlaventure commented
@andrewhsu it's already in the changelog: `Fix exec's children handling`

2016-10-07 17:37 UTC, mlaventure approved these changes

2016-10-07 17:37 UTC, mlaventure commented
LGTM

2016-10-07 20:11 UTC, andrewhsu commented on CHANGELOG.md
> + - Do not add service names to ingress network [docker/libnetwork#1489](https://github.com/docker/libnetwork/pull/1489)
done

2016-10-07 23:02 UTC, mavenugo commented
@andrewhsu apologies on the delay. LGTM.

2016-10-10 14:31 UTC, mlaventure commented
LGTM

2016-10-10 14:32 UTC, merged

2016-11-15 12:43 UTC, thaJeztah commented
merged to master through https://github.com/docker/docker/pull/27328