Clarify the purpose of ingress network in the documentaiton
moby/moby pull request #27290
Opened 2016-10-11 15:52 UTC by sanimej

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

2016-10-11 16:02 UTC, thaJeztah requested changes
One nit, but otherwise looks good; however this should now be opened in the https://github.com/docker/docker.github.io repository. I'm ok with merging it here as well for as long as those files are still here

2016-10-11 16:02 UTC, thaJeztah commented on docs/swarm/ingress.md
> +**Note** `ingress` network exists only to route the external traffic to the right
_The_ ingress network?

Also this should be formatted as a note;

```Markdown
> **Note**: The `ingress` network....
```

2016-10-19 13:02 UTC, vdemeester commented
ping @sanimej

2016-10-20 00:06 UTC, sanimej commented
@thaJeztah Looks like the doc files have been moved over to docker.github.io. I will close this and open in the doc repo.

2016-10-20 03:46 UTC, thaJeztah commented
Thanks @sanimej

2016-10-20 03:46 UTC, closed without merging