Improve bash completion of containers
moby/moby pull request #27348
Opened 2016-10-13 11:22 UTC by albers

Before this PR, completion of containers was done by getting a list of all container IDs with `docker ps -aq` and then `docker inspect`ing all containers, applying filtering and formatting at this stage.

Now, the "new" filtering and formatting capabilities of `docker ps` are used to do this in just one step, only looking at the required containers. This should yield a significant performance boost.

Other changes that improve consistency with existing completions:
* introduce a helper function that just lists the containers. This is helpful for developing and debugging.
* move the logic of whether names or IDs should be returned into this helper function with `--id|--name`  options.
* a new `--cur` option avoids modifying the global `$cur` variable.

2016-10-14 01:50 UTC, thaJeztah approved these changes
really cool enhancement LGTM!

2016-10-14 01:50 UTC, thaJeztah commented
ping @tianon for review / merge

2016-10-14 17:07 UTC, albers commented
Can you please also take a look at my other pending PRs (#27316, #27239, #27235)?
bash completion for #23614 depends on them.
In addition, completion for #26025 will require massive restructuring, so I'm not going to start work on it before my other PRs are incorporated.

Can you tell me what features will leave experimental in 1.13.0?

2016-10-17 16:17 UTC, mlaventure commented
Just tested this in the DIND container (bash version 4.3.30)

The following 2 cases failed to produce completions for me:
 - `docker ps --filter --before=`
 - `docker run --network container:`

Not sure what's causing them to fail though.

2016-10-17 16:23 UTC, mlaventure requested changes

2016-10-17 16:23 UTC, mlaventure commented on contrib/completion/bash/docker
> +# Returns a list of containers. Additional arguments to `docker ps`
Could you start the sentence with the name of the routine?

2016-10-17 16:23 UTC, mlaventure commented on contrib/completion/bash/docker
> +# Applies completion of containers based on the current value of `$cur` or
Could you start the sentence with the name of the routine?

2016-10-17 16:56 UTC, albers commented on contrib/completion/bash/docker
> +# Returns a list of containers. Additional arguments to `docker ps`
This would be the first and only comments that follow this style.
For consistency, I recommend we keep it as-is.

2016-10-17 16:59 UTC, albers commented
Thanks very much for looking into this, @mlaventure.
You're right with your findings, these were indeed regressions introduced in this PR.
I just pushed fixes.

2016-10-17 17:49 UTC, mlaventure approved these changes

2016-10-17 17:52 UTC, mlaventure commented
Everything seems to work now.

LGTM!

ping @tianon

2016-10-18 20:31 UTC, tianon commented
LGTM :heart_eyes_cat:

2016-10-18 20:31 UTC, merged