Windows: Hint to run client elevated
moby/moby pull request #27394
Opened 2016-10-14 17:20 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

@thaJeztah. I've seen countless reports now where users aren't reading the quick start documentation for Docker on Windows carefully enough, and are confused by the message they get back using the CLI.

eg in French:

![image](https://cloud.githubusercontent.com/assets/10522484/19396308/54d744a0-91f7-11e6-8e2f-64ed1f84de15.png)

or in English:

![image](https://cloud.githubusercontent.com/assets/10522484/19396323/664d143a-91f7-11e6-9d22-c3741caf1b89.png)

So this PR does a little to hopefully address it by adding a hint to the error message to run elevated when using the default configuration named pipe //./pipe/docker_engine.

And the new message:

![image](https://cloud.githubusercontent.com/assets/10522484/19396387/ca5188c6-91f7-11e6-9a79-df344ab2667b.png)

@friism @dmp42 @mavenugo This could be a useful one for consideration.

2016-10-14 18:21 UTC, thaJeztah commented
Should we use the same / similar error as was recently added for Linux? https://github.com/docker/docker/pull/26797/files

Can we distinguish between "access denied" and "not running" on Windows?

2016-10-14 18:38 UTC, jhowardmsft commented
Ah we can't distinguish.

2016-10-18 16:00 UTC, jhowardmsft commented
@thaJeztah You OK with this? It's come up a few times over the past few days too....

2016-10-21 04:27 UTC, thaJeztah commented on client/request.go
> +			err = errors.New(err.Error() + " In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not runni
"In the default daemon configuration on Windows" is probably a bit too verbose; Would this work?

    Make sure the docker daemon is running, and the client is running in elevated mode.

2016-10-21 04:34 UTC, thaJeztah commented on client/request.go
> +			err = errors.New(err.Error() + " In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not runni
I understand, but that's with any setup, I don't think we can take every possibility into account. IIUC, even with a modified setup, Reasons why it doesn't work is;

- daemon not running
- client doesn't have the required permissions

Correct?

2016-10-21 05:20 UTC, jhowardmsft commented on client/request.go
> +			err = errors.New(err.Error() + " In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not runni
Yes, these are the big two I see every day. But always also in the default configuration just following the guides.

2016-10-22 04:33 UTC, jhowardmsft commented
@vdemeester

2016-10-25 00:32 UTC, mdlinville requested changes

2016-10-25 00:32 UTC, mstanleyjones commented on client/request.go
> +			err = errors.New(err.Error() + " In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not runni
How about something like "Either the Docker daemon is not running, it is not elevated, or there is another problem with the configuration of the Docker daemon."

2016-10-25 00:58 UTC, jhowardmsft commented on client/request.go
> +			err = errors.New(err.Error() + " In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not runni
Ah no. Not quite. The #1 reason is the the client is not running elevated. Most likely the daemon is running, but we can't distinguish between lack of elevation of the client and the daemon not running. The daemon not running is very much a secondary issue, but has come up occasionally.

2016-10-25 01:25 UTC, vdemeester reviewed
2 comments (one completely useless :stuck_out_tongue_closed_eyes:)

2016-10-25 01:25 UTC, vdemeester commented on client/request.go
> +		// `open //./pipe/docker_engine: Le fichier spécifié est introuvable.`
:heart:

2016-10-25 01:25 UTC, vdemeester commented on client/request.go
> +			err = errors.New(err.Error() + " In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not runni
@jhowardmsft The client must be elevated only if it's the default setup (or at least if the daemon and client discuss through a named pipe), am I right ? 

If yes, it's a little bit more than *default daemon configuration* ; maybe we could add something about "*if the daemon is listening via named pipe*" or something ?

2016-10-25 01:31 UTC, jhowardmsft commented on client/request.go
> +		// `open //./pipe/docker_engine: Le fichier spécifié est introuvable.`
:France:

2016-10-25 01:36 UTC, jhowardmsft commented
Elevation is required only using names pipe. And only if (as per default) the pipe configuration hasn't been changed such that other Windows groups can access the pipe. By default it's administrators only. The problem I have with saying named pipe explicitly is that I'm not sure it's going to mean much to users starting out with docker.  We only know that the client is attempting to connect to a local named pipe with this change. If remote, I'm not so concerned as the user would likely already know about -H and daemon configuration.

2016-10-25 01:37 UTC, vdemeester commented
@jhowardmsft I see :sweat_smile: 
LGTM for me then 👼

2016-10-25 20:39 UTC, jhowardmsft commented
@mstanleyjones PTAL at the above comments.

2016-10-25 20:59 UTC, mstanleyjones commented
I don't have a strong preference, but I'm not sure if the message actually will alleviate confusion. @friism WDYT?

2016-10-27 01:38 UTC, friism commented
What about "Check that the Docker daemon is up and that the client is running as an elevated process."

If we document this with more detail in the FAQ, hopefully people will find it when googling.

2016-10-27 01:41 UTC, jhowardmsft commented
Yes, but... it would be giving incorrect information(to elevate) potentially unnecessarily.

2016-10-28 18:24 UTC, crosbymichael commented
LGTM

Much better error message than what was originally returned to the user.

2016-10-28 18:25 UTC, merged