Convert Unused ARG error to warning
moby/moby pull request #27412
Opened 2016-10-16 06:01 UTC by addamh

**- How I did it**

Convert error message and failure of build when an unused build-arg is supplied to a successful build and a warning message. Resolves #26249 

**- How to verify it**

1. Create a valid Dockerfile. DO NOT consume the build-arg `test-arg`
2. Build the docker image passing in an unused build-arg
docker build --build-arg test-arg=value -t hello-error .

**- Description for the changelog**

Unused build-args now allowed. A warning is presented instead of an error and failed build.

2016-10-16 06:01 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "26249-make-unused-args-warning" git@github.com:loftylabs/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-10-17 04:10 UTC, duglin commented on integration-cli/docker_cli_build_test.go
> +		c.Fatalf("build failed to complete: %q %q", out, err)
Can we search for the warning message and make sure its there?

2016-10-17 04:25 UTC, addamh commented on integration-cli/docker_cli_build_test.go
> +		c.Fatalf("build failed to complete: %q %q", out, err)
I think that's a good idea. Will update tomorrow :+1:

2016-10-17 04:34 UTC, thaJeztah commented on builder/dockerfile/builder.go
> +		fmt.Fprintf(b.Stdout, "[Warning] One or more build-args %v were not consumed\n", leftoverArgs)
should this be printed to stdout or stderr? (not sure)

2016-10-17 04:40 UTC, addamh commented on builder/dockerfile/builder.go
> +		fmt.Fprintf(b.Stdout, "[Warning] One or more build-args %v were not consumed\n", leftoverArgs)
IMO shouldn't be stderr since not an error, but could see argument for either option

2016-10-17 04:47 UTC, duglin commented on builder/dockerfile/builder.go
> +		fmt.Fprintf(b.Stdout, "[Warning] One or more build-args %v were not consumed\n", leftoverArgs)
A while ago someone posted a link to a web site that made an argument for when to use stdout vs stderr for things like info/warning messages. Their basic premise was that stdout should be reserved for normal/expected output - and therefore including things like info/warning messages in there would do nothing but muck-up any output processing (like grep, sed, ...) that people may have. It convinced me that stderr should be used.  But YMMV

2016-10-17 04:54 UTC, addamh commented on builder/dockerfile/builder.go
> +		fmt.Fprintf(b.Stdout, "[Warning] One or more build-args %v were not consumed\n", leftoverArgs)
Definitely an interesting perspective. I can switch output if that's where the consensus is.

2016-10-22 18:54 UTC, addamh commented
Apologies for the delay, but updated per review comments and tests are passing. Ready for another pass. Thanks!

2016-10-25 00:25 UTC, thaJeztah approved these changes
LGTM

2016-10-25 00:25 UTC, thaJeztah commented
ping @duglin PTAL

2016-10-25 13:51 UTC, duglin commented
just a couple of minor doc edits, otherwise it looks good.

2016-10-29 00:27 UTC, thaJeztah commented
ping @addamh can you update the PR with the changes @duglin requested?

2016-10-29 01:43 UTC, addamh commented
Yes I definitely will before Monday. Sorry for the delay!

2016-11-01 02:31 UTC, thaJeztah requested changes

2016-11-01 02:31 UTC, thaJeztah commented on docs/reference/builder.md
> +[Warning] One or more build-args %v were not consumed.
Oh, i see you included the literal `%v` in the docs; @duglin meant to say that this should show what it looks like if one or more ARGS were not used

2016-11-01 02:31 UTC, thaJeztah commented on man/Dockerfile.5.md
> +  [Warning] One or more build-args %v were not consumed
Same here

2016-11-01 03:53 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-01 03:54 UTC, vdemeester approved these changes
LGTM 🐸

2016-11-01 12:47 UTC, duglin commented
LGTM

2016-11-01 12:47 UTC, merged

2017-05-16 14:08 UTC, slawomirfurtak commented
Hi!
What do you think about disabling/hiding this warning for predefined build ARG variables (like *_proxy)? There is no need setting it inside Dockerfile, but are in fact "consumed" by tools (i.e. yum, apt-get, curl, wget...) inside RUN instruction. This warning  in that case is misleading. Docs says about it:  _"Docker has a set of predefined ARG variables that you can use without a corresponding ARG instruction in the Dockerfile."_

2017-05-16 14:19 UTC, thaJeztah commented
@slawomirfurtak that warning is a bug in docker 17.05 (see https://github.com/moby/moby/issues/33067), and will be addressed in 17.06 through https://github.com/moby/moby/pull/33114

2017-05-16 14:26 UTC, slawomirfurtak commented
Couldn't find that, thank you for fast response!