Fix a link for feature deprecation policy
moby/moby pull request #27435
Opened 2016-10-17 07:01 UTC by yuexiao-wang

**- What I did**
Fix a link for feature deprecation policy which can't to access

**- How I did it**
Update a link for feature deprecation policy

**- How to verify it**
access to the page

**- Description for the changelog**
The new link is https://github.com/docker/docker.github.io/blob/master/engine/index.md#feature-deprecation-policy).

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

2016-10-17 07:16 UTC, thaJeztah commented
Thanks! I'm not sure how we're going to be doing these cross-repo links, so I'll ping @mstanleyjones for input / suggestions

2016-10-17 07:25 UTC, yuexiao-wang commented
Got it and Thanks for your review!

2016-10-17 18:23 UTC, mdlinville requested changes
Please use the link to the live documentation: https://docs.docker.com/engine/deprecated/

Thanks!

2016-10-18 01:56 UTC, yuexiao-wang commented
@mstanleyjones @thaJeztah PTAL
I suggest that use the followed link which can be access directly the document to see the detailed content.
https://docs.docker.com/engine/#feature-deprecation-policy
Thanks!

2016-10-18 02:00 UTC, thaJeztah approved these changes
LGTM

2016-10-18 12:55 UTC, justincormack commented
@mstanleyjones which one should we use?

2016-10-18 16:41 UTC, thaJeztah commented
@justincormack second one looks correct, as the link suggested by @mstanleyjones is pointing to the online version of _this_ document

2016-10-18 17:04 UTC, mdlinville approved these changes

2016-10-18 17:04 UTC, merged