record pid of exec'd process
moby/moby pull request #27470
Opened 2016-10-17 23:37 UTC by runcom

Resurrecting docker/docker#19095 as per @LK4D4 comment docker/docker#18635 (comment). Would be nice for docker to expose exec's pids in order to give an admin full control over execs (e.g. someone spawns run-away processes like tail -f /dev/null which never ends and he wants to kill it directly).

ping @thaJeztah @LK4D4 @mlaventure @crosbymichael

2016-10-18 15:33 UTC, mlaventure requested changes
One nit, but LGTM.

2016-10-18 15:33 UTC, mlaventure commented on integration-cli/docker_api_exec_test.go
> +	c.Assert(execJSON.PID, checker.GreaterOrEqualThan, 0)
`> 1` ?

2016-10-18 15:34 UTC, runcom commented on integration-cli/docker_api_exec_test.go
> +	c.Assert(execJSON.PID, checker.GreaterOrEqualThan, 0)
right

2016-10-18 15:36 UTC, runcom commented on integration-cli/docker_api_exec_test.go
> +	c.Assert(execJSON.PID, checker.GreaterOrEqualThan, 0)
Fixed

2016-10-18 16:10 UTC, mlaventure approved these changes

2016-10-18 16:10 UTC, mlaventure commented
LGTM.

2016-10-19 01:33 UTC, thaJeztah requested changes

2016-10-19 01:33 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
> +      "Pid": "42000"
before I forget, or someone is "trigger happy" and merges; can you add this to the API changes for 1.25; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md#v125-api-changes

2016-10-19 10:40 UTC, runcom commented on docs/reference/api/docker_remote_api_v1.25.md
> +      "Pid": "42000"
@thaJeztah thx!

2016-10-19 10:40 UTC, runcom commented
@thaJeztah fixed your comments, any other doc changes needed?

2016-10-20 06:31 UTC, thaJeztah reviewed
just a few nits, but looks good otherwise

2016-10-20 06:31 UTC, thaJeztah commented on libcontainerd/client_windows.go
>  // container. It's called through docker exec.
Should we update the description of this function to mention it returns the PID?

2016-10-20 06:31 UTC, thaJeztah commented on libcontainerd/client_linux.go
> +func (clnt *client) AddProcess(ctx context.Context, containerID, processFriendlyName string, specp Process) (int, error) {
Can you copy the GoDoc from the windows file?

2016-10-20 08:49 UTC, runcom commented
@thaJeztah fixed

2016-10-20 16:26 UTC, thaJeztah approved these changes
LGTM

2016-10-20 19:36 UTC, vdemeester commented
LGTM 🐸

2016-10-20 19:36 UTC, merged