added editorconfig
moby/moby pull request #27490
Opened 2016-10-18 11:23 UTC by caarlos0

Added `.editorconfig` file, so it's easier to avoid mistakes (like spaces vs tabs, etc).

2016-10-18 13:00 UTC, vdemeester commented
Why not but pretty much all Go editors are "wired" to gofmt (on save) and/or should be (otherwise the build fail here anyway), so it's more a nice-to-have than a requirement.

/cc @thaJeztah @dnephin @justincormack

2016-10-18 13:15 UTC, caarlos0 commented
@vdemeester yeap, but there are also shell scripts and other kinds of files... I thought it would be useful to have them all under the same kind of fomating...

2016-10-18 13:36 UTC, vdemeester commented
/cc @tianon too :angel:

2016-10-18 21:26 UTC, dnephin commented
IMO what is more valuable is a tool to enforce style as a git hook. I use http://pre-commit.com/ with https://gist.github.com/dnephin/c7776ecb5cdcf02eb1a6 to ensure that formatting is correct.

If we're going to add this, it's probably more appropriate under `contrib/` somewhere, instead of the root of the repo. We can add `.editorconfig` to `.gitignore` so that developers can customize their copy as they want.

2016-10-18 21:35 UTC, thaJeztah commented
I'm wondering if this falls in the same category as https://github.com/docker/docker/blob/389d5cde7b5474cd33d251aadc96be1f0bdbc711/.gitignore#L2-L3

2016-10-18 21:50 UTC, dnephin commented
True, we don't need to add it to `.gitignore`.

2016-10-18 21:56 UTC, tianon commented
Yeah, I agree -- this is useful information, and it's nice to see folks trying to standardize the way it's communicated, but I don't think the standard is firm enough yet that committing this at the top-level is warranted (perhaps more prudent once/if more editors start supporting this file out-of-the-box or if it becomes more common).  `contrib/` seems like a great place for it (`contrib/editorconfig`, for example, so that it's not hiding and is easy to find and symlink to `.editorconfig` if folks want to use it via something simple like `ln -s contrib/editorconfig .editorconfig`).

2016-10-19 20:01 UTC, caarlos0 commented
@tianon @thaJeztah @justincormack @vdemeester  Done, what do you guys think?

2016-10-19 23:35 UTC, thaJeztah requested changes

2016-10-19 23:35 UTC, thaJeztah commented on .gitignore
> +.editorconfig
Can you move this up, to keep the list in alphabetical order?

2016-10-20 11:12 UTC, caarlos0 commented on .gitignore
> +.editorconfig
done!

2016-10-20 16:43 UTC, thaJeztah commented on contrib/editorconfig
> +[*]
Actually, just noticing this; should this be limited to `.go` files? We use spaces for Markdown (`.md`)

2016-10-21 00:18 UTC, caarlos0 commented on contrib/editorconfig
> +[*]
@thaJeztah Just added the missing `[*.md]` section.

2016-10-21 15:13 UTC, vdemeester approved these changes
LGTM 🐸

2016-10-21 15:13 UTC, vdemeester commented on contrib/editorconfig
> +[*]
We do use tab for shell script though :angel:, I think it's good as is. `*.md` is handled down :stuck_out_tongue_closed_eyes:

2016-10-21 16:11 UTC, tianon commented
LGTM :+1:

2016-10-21 16:15 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-10-21 16:15 UTC, merged

2016-10-21 22:49 UTC, dnephin commented
I just learned something that changed my opinion on this. github actually supports `.editorconfig`! So if we set 

```
[*]
indent_size = 4
```
Viewing code and diffs will show 4 space tabs instead of 8 space tabs. 

I would be in favor of moving this out of contrib and back into the root of the repo so that we can have nicer looking code and diffs on github.

2016-10-21 23:27 UTC, thaJeztah commented
@dnephin that's nice! Is it only indent size that's taken into account, no other "side effects"?

2016-10-21 23:35 UTC, dnephin commented
I'm not sure, there doesn't seem to be much information out there about it. http://stackoverflow.com/a/33899831/444646 suggests that they never officially announced the support.

I suspect it does support any options that make sense from the UI. Maybe they apply to the in-browser editor as well.

2016-10-22 00:01 UTC, tianon commented
Honestly, I kinda like that GitHub shows tabs at 8 spaces because it makes it much more obvious when someone screws it up in a PR because the 4-real-space-indents don't line up properly. :innocent:

2016-10-22 00:09 UTC, thaJeztah commented
Oh, you've got a point, it has helped me as well (if only GitHub had a `show whitespace` option)

2016-10-22 00:14 UTC, dnephin commented
Shouldn't we have automated style checks for that instead of relying on a human to notice it?

http://pre-commit.com/ with https://gist.github.com/dnephin/c7776ecb5cdcf02eb1a6 is a great option.

2016-10-22 00:20 UTC, thaJeztah commented
That would be good, however, I can imagine there's combinations that are harder to validate strictly