Sync ref docs
moby/moby pull request #27518
Opened 2016-10-18 23:32 UTC by mstanleyjones

@dnephin @thaJeztah PTAL. This is all the files we accidentally edited in docker.github.io repository since the merge.

2016-10-18 23:46 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.18.md
> +-   **Labels** - Adds a map of labels to a container. To specify a map: `{"key":"value"[,"key2":"value2"]}`
These two lines should be reverted

2016-10-19 00:04 UTC, mstanleyjones commented
Hold fire, this should have been based on 1.12x, not master! Need to rebase and it's a little complicated. I'll ping when it's ready.

2016-10-19 00:29 UTC, thaJeztah requested changes
hm, looks like this is going to be tough to sync :cry:

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> +The `URL` is a the location of a Git repository.
see https://github.com/docker/docker/pull/27434

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> -
see https://github.com/docker/docker/pull/26516 for here and other places

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> -registries.
see https://github.com/docker/docker/commit/690882c2e79c3f3742c709cf158584e61594ba00

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> +
Same

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> +
Also looks like most other changes in this document should be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> +`--build-arg <varname>=<value>` flag. If a user specifies a build argument
this is a fix; can stay in

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/builder.md
> +```
This can stay in as well

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +  -v, --version                   Print version information and quit
This should be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> -
same here

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +      --cpu-shares=0             CPU shares (relative weight)
needs to be reverted as well

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +      -v, --version                          Print version information and quit
This as well

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> -    ```
needs to be reverted https://github.com/docker/docker/pull/26212

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +}
Looks like a fix, this can stay

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +
This can be removed https://github.com/docker/docker/pull/27432

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> + - sharing PID or NET namespaces with the host (`--pid=host` or `--network=host`)
This, and other changes below need to be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/inspect.md
> -networks, nodes, services, or tasks identified by name or ID.
Document needs to be reverted as well (other than the metadata, and `{% raw %}`)

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/node_inspect.md
> +**Warning:** this command is part of the Swarm management feature introduced in Docker 1.12, and might be subject to non backward-compatible changes.
Bit confused by this message; what's the backward-incompatibility (as this command didn't exist before); maybe this originally referred to it being an `RC` / preview, so changes could still occur?

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/node_inspect.md
> +  -f, --format string   Format the output using the given go template
Should be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/node_ps.md
> -List tasks running on one or more nodes, defaults to current node.
Changes in this document should be reverted as well

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/ps.md
> +                        - status=(created|restarting|running|paused|exited)
Same for this document (other than meta/raw)

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/service_inspect.md
> +  -f, --format string   Format the output using the given go template
Changes in this document should be reverted (other than meta/raw)

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/service_ps.md
> -      --no-trunc       Do not truncate output
Changes in this document should be reverted (other than meta/raw/links)

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/service_scale.md
> +The scale command enables you to scale one or more services either up or down to the desired number of replicas. The command will return immediatly, but the actual scaling of the service may take som
typo; `immediatly`

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/stack_tasks.md
> +# stack tasks (experimental)
This command no longer exists (is now `stack ps`)

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/version.md
> +  -f, --format string   Format the output using the given go template
Should be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/volume_inspect.md
> +  -f, --format string   Format the output using the given go template
Changes in this document should be reverted (other than meta/raw/links)

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/volume_ls.md
> +  -f, --filter value   Provide filter values (i.e. 'dangling=true') (default [])
Should be reverted https://github.com/docker/docker/pull/25720

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/commandline/volume_ls.md
> +  -f, --filter value   Provide filter values (i.e. 'dangling=true') (default [])
Same for other changes in this document

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/run.md
> -
Should be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/run.md
> -
Should be reverted

2016-10-19 00:29 UTC, thaJeztah commented on docs/reference/run.md
> +| `TERM` | `xterm` if the container is allocated a pseudo-TTY |
Looks like this was a fix, so can be kept https://github.com/docker/docker.github.io/commit/e41a76bf8199558cc4c4c8bf856a65c0dea8c079

2016-10-19 00:34 UTC, thaJeztah commented
oh, LOL, long-live GitHub cache

2016-10-19 17:25 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "sync_ref_docs" git@github.com:mstanleyjones/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~899
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-10-19 17:31 UTC, mstanleyjones commented
OK, this should be rebased now. Let's see how it looks.

2016-10-19 17:32 UTC, mstanleyjones commented on docs/reference/api/docker_remote_api_v1.18.md
> +> See [create a container](docker_remote_api_v1.18.md#create-a-container) for details.
Yeah it should work without the .md file...

2016-10-19 17:42 UTC, thaJeztah requested changes
Only a few left, but much better than the previous changeset 😄

2016-10-19 17:42 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.24.md
> +    HTTP/1.1 200 No Content
@mstanleyjones ^^

2016-10-19 17:42 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
> +    HTTP/1.1 200 No Content
Same here :smile:

2016-10-19 17:42 UTC, thaJeztah commented on docs/reference/commandline/service_scale.md
> +The scale command enables you to scale one or more services either up or down to the desired number of replicas. The command will return immediatly, but the actual scaling of the service may take som
^^ :smile:

2016-10-19 17:53 UTC, mstanleyjones commented on docs/reference/builder.md
> +`--build-arg <varname>=<value>` flag. If a user specifies a build argument
What are you referring to? The typo fix or the line wrapping change?

2016-10-19 17:55 UTC, mstanleyjones commented on docs/reference/commandline/dockerd.md
> +}
This was just reformatting the JSON to be less indented, I think.

2016-10-19 18:25 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.24.md
> +    HTTP/1.1 200 No Content
Looks like it was cherry-picked; https://github.com/docker/docker/pull/26960

2016-10-19 18:25 UTC, thaJeztah commented on docs/reference/builder.md
> +`--build-arg <varname>=<value>` flag. If a user specifies a build argument
Oh, yes, this is ok, no need to change anything

2016-10-19 18:25 UTC, thaJeztah commented on docs/reference/builder.md
> +```
Oh, yes, this is ok as well, no need to change anything

2016-10-19 18:37 UTC, dnephin approved these changes
LGTM

2016-10-19 18:44 UTC, thaJeztah reviewed
changes LGTM, but thinking again if we should update the 1.12.x branch with these changes as the 1.12.x branch has the "old style" docs in it (so full documentation). Changing this is would no longer allow building those docs from the 1.12.x branch.

Sorry for rambling, trying to get my head around it :D

2016-10-19 18:45 UTC, thaJeztah commented
Basically, question is, should we change to "new style" docs in the current release branch (as it's a "breaking" change in what could be considered a "patch" release)

2016-10-19 18:52 UTC, mstanleyjones commented
Yuck, you are right. I don't know the answer. The old docs in v1.12 branch are stranded anyway -- we can't build them to put on docs.docker.com at all anymore. If we leave them alone that means that we can't really touch them at all anymore and therefore can't improve them on docs.docker.com. It also means that the changes @dnephin wants to do will only be available in master.

Whether we take this PR or not, I should try to apply this same changeset to master and resolve any problems, so that we can move forward.

2016-10-19 18:54 UTC, dnephin commented
Oops, you're right. I didn't notice this was a PR against 1.12.x. I think we need the PR against master.

2016-10-19 18:57 UTC, mstanleyjones commented
@dnephin just to remind you, master on docker.github.io is equivalent to 1.12x on docker/docker. For master on docker/docker you need vnext-engine on docker.github.io. So I don't think we have changed much with the docs on the vnext-engine branch at all. The changes that were upsetting you were in master. Anyway I am working on a PR to get these changes into docker/docker master so we can benefit from typo correction etc. Let's see how hard it is to resolve the conflicts.

2016-10-19 19:59 UTC, dnephin commented
I'm not really concerned with what is about to be published, I'm concerned with the "single source of truth" for the reference docs. That is the master branch of docker/docker.  Anything in the docker.github.io repo under the reference section should be considered disposable, regardless of the branch. The problem is we have changes there that are not up-streamed to docker/docker master.

> The changes that were upsetting you were in master.

I don't see any evidence of that. For examples the meta-data on this page: https://raw.githubusercontent.com/docker/docker/master/docs/reference/api/docker_remote_api.md is not the same as the metadata being added in this PR. It looks like someone made a related, but not identical change to this repo.

My concern is that I need to make significant structural changes to the reference doc files. If there are any oustanding changes to these files they will be near impossible to apply after my changes are merged. Or my PR will heavily conflict with any large changes (like the one to the metadata).

I'm trying to avoid that pain by making sure that all of the change that were applied directly in the docs repo are applied here first, so we don't lose them.

2016-10-19 23:52 UTC, thaJeztah commented
So yes, I think we should apply the TOML -> YAML changes and the fixes for the new Markdown generator to master. 

Possibly that would be something like; on docker.github.io rebase master onto vnext-engine, and apply that to docker/master?

2016-10-21 18:06 UTC, closed without merging