Improve error message
moby/moby pull request #27510
Opened 2016-10-18 20:35 UTC by chipironcin

**- What I did**
Add single quotes around container name and container id to improve copy-paste avoiding the extra `.` that slips into the clipboard

**- How I did it**
Adding the single quotes directly editing the file

**- How to verify it**
docker run --name busybox_container busybox echo hello
docker run --name busybox_container busybox echo hello
Check error message

**- Description for the changelog**
Add single quotes around container name and container id to improve copy-paste avoiding the extra `.` that slips into the clipboard

**- A picture of a cute animal (not mandatory but encouraged)**

Add single quotes around container name and container id to improve copy-paste avoiding the extra `.` that slips into the clipboard

Signed-off-by: Jorge Marin <chipironcin@users.noreply.github.com>

2016-10-19 07:12 UTC, chipironcin commented on daemon/names.go
> +			return "", fmt.Errorf("Conflict. The container name '%q' is already in use by container '%s'. You have to remove (or rename) that container to be able to reuse that name.", name, id)
mmmm I was afraid of that, I tried to look for the place where they are added but cannot find it. I guess we'd better use single quotes in both places or none

2016-10-20 11:42 UTC, chipironcin commented
>%q already adds quotes
 
>mmmm I was afraid of that, I tried to look for the place where they are added but cannot find it. I guess we'd better use single quotes in both places or none

anyone?

2016-10-20 16:35 UTC, tonistiigi commented on daemon/names.go
> +			return "", fmt.Errorf("Conflict. The container name '%q' is already in use by container '%s'. You have to remove (or rename) that container to be able to reuse that name.", name, id)
I'm not sure if this is the answer you are looking for but its added by stdib fmt https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/fmt/format.go#L407-L422

2016-10-21 01:19 UTC, thaJeztah commented on daemon/names.go
> +			return "", fmt.Errorf("Conflict. The container name '%q' is already in use by container '%s'. You have to remove (or rename) that container to be able to reuse that name.", name, id)
or try https://play.golang.org/p/EMI-6sMC16

2016-10-28 20:43 UTC, thaJeztah commented
@chipironcin either way is fine with me, what's  the reason you don't like the double quotes added by `%q` though?

2016-10-30 15:57 UTC, cpuguy83 commented on daemon/names.go
> +			return "", fmt.Errorf("Conflict. The container name '%q' is already in use by container '%s'. You have to remove (or rename) that container to be able to reuse that name.", name, id)
`%q` does some escaping too, though, so it can make the output weird.

2016-11-29 22:01 UTC, mlaventure commented
ping @chipironcin

2016-12-05 23:51 UTC, chipironcin commented
Hey guys! I am sorry I have had no time to check this back.
I understand now what is happening (didnt realize `%q = %quoted`)
I prefer single quotes rather than double quotes but keeping in mind `%q` already does the quoting for us maybe we'd better change `%s` for `%q` as @MHBauer 

But @cpuguy83 raised a concern about escaped characters, anyone knows anything about the escape mapping for`%q`?

2016-12-21 21:17 UTC, cpuguy83 commented
We can just change both to `%q`. Strange that it's alternated.

2016-12-23 11:10 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:chipironcin/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353721808
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-23 11:28 UTC, thaJeztah requested changes
thanks! changes look good to me, but can you squash your commits? You can check our [contributors guide](https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently) if you need instructions 👍

2017-01-11 14:57 UTC, AkihiroSuda approved these changes
LGTM if green

2017-01-12 10:50 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:chipironcin/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354206368
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-01-14 13:59 UTC, cpuguy83 commented
Needs a squash

2017-01-14 14:00 UTC, cpuguy83 commented
Also would be really helpful to re-word your commit message so that the commit title fits within the normal title length, then you can add more details in the commit message body.

2017-01-14 22:06 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:chipironcin/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354317888
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-01-16 21:12 UTC, thaJeztah commented
@chipironcin looks like your sign-off got lost during the rebase, can you fix that? Let us know if you need more information on how to do that

2017-01-17 08:20 UTC, chipironcin commented
Yea, I am sorry about the number of updates this thread is getting. Trying to tie all things together and meet requirements is not being that easy though (i.e. squash two commits separated by a lot of other commits while rebasing from a diferent remote 😛 )

2017-01-17 15:21 UTC, thaJeztah approved these changes
LGTM

2017-01-17 21:48 UTC, mlaventure commented
Looks like we hit the flakyness of `TestBuildContextDirIsSymlink` restart janky one more time for good mesure

2017-01-18 16:30 UTC, mlaventure approved these changes
LGTM

2017-01-20 12:47 UTC, merged

2017-01-23 13:45 UTC, chipironcin commented
Finally, thank for your awesome support and review guys! Keep up the good work!

2017-01-23 13:48 UTC, thaJeztah commented
Yes, it took a bit longer than expected, thanks for contributing!