prevent data race in pkg/plugins
moby/moby pull request #27522
Opened 2016-10-19 01:36 UTC by vieux

ping @anusha-ragunathan

2016-10-19 16:40 UTC, aaronlehmann commented
LGTM

Thanks.

2016-10-20 21:07 UTC, aaronlehmann commented
@vieux: Needs a rebase

Would love to get this merged, so I can update vendoring in swarmkit.

2016-10-20 22:14 UTC, mlaventure commented
LGTM, still needs a rebase :)

2016-10-21 01:22 UTC, vieux commented
I'll rebase asap

2016-10-21 01:39 UTC, vieux commented
please @aaronlehmann @mlaventure PTAL

2016-10-21 14:49 UTC, mlaventure requested changes

2016-10-21 14:49 UTC, mlaventure commented on pkg/plugins/plugins.go
> +	handlers.extpointHandlers = make(map[string][]func(string, *Client))
nit, any reason this isn't done when the variable is declared? (Just occurred to me)

2016-10-21 20:28 UTC, vieux commented on pkg/plugins/plugins.go
> +	handlers.extpointHandlers = make(map[string][]func(string, *Client))
no, thanks!

2016-10-21 20:28 UTC, vieux commented on pkg/plugins/plugins.go
> +	handlers.extpointHandlers = make(map[string][]func(string, *Client))
@mlaventure updated

2016-10-21 20:52 UTC, mlaventure approved these changes

2016-10-21 20:52 UTC, mlaventure commented
LGTM

2016-10-21 21:19 UTC, merged