[doc] update docs/reference/commandline/network_inspect.md
moby/moby pull request #27526
Opened 2016-10-19 05:06 UTC by AkihiroSuda

The following sentences (introduced in v1.11 via #21160) were misleading for Swarm mode services (>= v1.12)

  For networks backed by multi-host network driver, such as Overlay,
  this command also shows the container endpoints in other hosts in the
  cluster. These endpoints are represented as "ep-{endpoint-id}" in the output.

Update #24684 
Update #24186

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2016-10-19 05:06 UTC, AkihiroSuda commented
cc @mavenugo

2016-10-21 01:27 UTC, AkihiroSuda commented
cc @mstanleyjones

2016-10-21 04:16 UTC, thaJeztah commented on docs/reference/commandline/network_inspect.md
> +However, for Swarm mode services, only the endpoints that are local to the node
Should this be "for swarm scoped networks"?

2016-10-21 04:16 UTC, thaJeztah commented on docs/reference/commandline/network_inspect.md
> +However, for Swarm mode services, only the endpoints that are local to the node
ping @mrjana PTAL

2016-10-21 16:47 UTC, mdlinville requested changes

2016-10-22 01:55 UTC, thaJeztah commented on docs/reference/commandline/network_inspect.md
> +However, for Swarm mode services, only the endpoints that are local to the node
I think "swarm scoped networks" was the general term we use, but I defer to @mavenugo

2016-10-24 21:39 UTC, mdlinville approved these changes

2016-10-25 02:47 UTC, AkihiroSuda commented
updated PR
```diff
diff --git a/docs/reference/commandline/network_inspect.md b/docs/reference/comm
andline/network_inspect.md
index 943f329..85d4045 100644
--- a/docs/reference/commandline/network_inspect.md
+++ b/docs/reference/commandline/network_inspect.md
@@ -39,8 +39,8 @@ The `network inspect` command shows the containers, by id, in 
its
 results. For networks backed by multi-host network driver, such as Overlay,
 this command also shows the container endpoints in other hosts in the
 cluster. These endpoints are represented as "ep-{endpoint-id}" in the output.
-However, for Swarm mode services, only the endpoints that are local to the node
-are shown.
+However, for swarm-scoped networks, only the endpoints that are local to the
+node are shown.
 
 You can specify an alternate format to execute a given
 template for each result. Go's
```

2016-10-25 04:21 UTC, thaJeztah approved these changes
LGTM thanks again @AkihiroSuda

2016-10-25 04:21 UTC, merged