[nit] add missing changes in API v1.25 (prune) to docker_remote_api.md
moby/moby pull request #27531
Opened 2016-10-19 06:51 UTC by AkihiroSuda

Added the changes about `prune` (#26108)

There is also a change that makes `DELETE /networks/(id)` return 204 (#26960), but IMO we don't need to add it, because it is just a change to implementation.

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2016-10-19 06:52 UTC, AkihiroSuda commented
cc @mlaventure @allencloud

2016-10-19 15:07 UTC, mlaventure requested changes
need a rebase. Aside a nit, LGTM.

Thanks for spotting it!

2016-10-19 15:07 UTC, mlaventure commented on docs/reference/api/docker_remote_api.md
> +* `POST /containers/prune` to prune stopped containers.
`s/to prune/prunes` (same below)

2016-10-20 06:21 UTC, AkihiroSuda commented on docs/reference/api/docker_remote_api.md
> +* `POST /containers/prune` to prune stopped containers.
done

2016-10-20 14:56 UTC, vdemeester approved these changes
LGTM 🐮
/cc @thaJeztah

2016-10-20 15:13 UTC, mlaventure approved these changes

2016-10-20 16:24 UTC, thaJeztah approved these changes
LGTM, but unfortunately needs a rebase 😅

2016-10-21 01:33 UTC, AkihiroSuda commented
rebased

2016-10-21 02:37 UTC, thaJeztah approved these changes
LGTM!

2016-10-21 02:37 UTC, merged