Add `publish` and `expose` filter for `docker ps --filter`
moby/moby pull request #27557
Opened 2016-10-19 19:11 UTC by yongtang

**- What I did**

This fix tries to address the enhancement proposal raised in #27178 for filtering based on published or exposed ports of `docker ps --filter`.

Note: this PR didn't implement the wildcard match initially, as protocol (`tcp/udp`) has to be taken into consideration. But is open to suggestions.

**- How I did it**

In this fix, two filter options, `publish` and `expose` have been added to take either `<port>[/<protocol>]` or `<from>-<to>[/<protocol>]` and filtering on containers.

**- How to verify it**

An integration test has been added to cover the changes.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #27178.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-10-20 12:13 UTC, vdemeester commented
Design SGTM 👼

2016-11-03 23:49 UTC, LK4D4 commented
@yongtang would you mind to rebase? Thanks!

2016-11-04 00:39 UTC, yongtang commented on daemon/list.go
> +			return nil
Thanks @LK4D4. I wasn't sure initially as some of the other filters didn't return the error. The PR has been updated and now `expose` and `publish` will return error.

2016-11-04 00:39 UTC, yongtang commented
Thanks @LK4D4 for the review. The PR has been updated and rebased. Please take a look and let me know if there are any issues.

2016-12-01 18:22 UTC, mlaventure commented on integration-cli/docker_cli_ps_test.go
> +	out, _ = dockerCmd(c, "ps", "--no-trunc", "--filter", "publish=80-8080/udp")
nit: you could add `-q` and use `checker.Equals` instead

2016-12-01 18:23 UTC, mlaventure approved these changes
LGTM with inconsequential nit

2016-12-01 18:23 UTC, mlaventure commented
ping @LK4D4

2016-12-01 19:05 UTC, yongtang commented on integration-cli/docker_cli_ps_test.go
> +	out, _ = dockerCmd(c, "ps", "--no-trunc", "--filter", "publish=80-8080/udp")
Thanks @mlaventure. Done.

2016-12-01 19:05 UTC, yongtang commented
Thanks all for the review. The PR has been updated. Please take a look and let me know if there are any other issues.

2017-01-12 17:07 UTC, vdemeester requested changes
SGTM but I feel the `logrus.Errorf` shouldn't be there 👼

2017-01-12 17:07 UTC, vdemeester commented on daemon/list.go
> +		logrus.Errorf("REDUCE: %+v", ctx.publish)
@yongtang debug message 😅

2017-01-13 01:55 UTC, yongtang commented on daemon/list.go
> +		logrus.Errorf("REDUCE: %+v", ctx.publish)
My bad. How could I have missed this one? 😳

2017-01-13 01:56 UTC, yongtang commented
Thanks @vdemeester. The PR has been updated.

2017-01-13 08:44 UTC, vdemeester approved these changes
LGTM 🐸
/cc @thaJeztah for docs review 👼

2017-01-17 21:45 UTC, mlaventure commented
ping @thaJeztah

2017-01-19 08:44 UTC, AkihiroSuda commented on docs/reference/commandline/ps.md
> +number, port range, and/or protocol. The default protocol is `80` when not specified.
port is 80, protocol is tcp

2017-01-19 11:09 UTC, yongtang commented on docs/reference/commandline/ps.md
> +number, port range, and/or protocol. The default protocol is `80` when not specified.
@AkihiroSuda The PR has been updated. Thanks.

2017-01-27 21:22 UTC, LK4D4 commented
@yongtang needs rebase
@thaJeztah for docs-review

2017-01-27 21:26 UTC, yongtang commented
@LK4D4 @thaJeztah The PR has been rebased. Thanks.

2017-02-01 15:32 UTC, vdemeester approved these changes
docs LGTM
/cc @thaJeztah for revisit 👼

2017-02-01 15:32 UTC, merged

2017-02-02 00:53 UTC, thaJeztah commented
@yongtang can you;

- add a mention of the new filters that are supported in the API history; https://github.com/docker/docker/blob/master/docs/api/version-history.md#v126-api-changes
- update the man-pages accordingly?

2017-02-02 03:12 UTC, yongtang commented
Thanks @thaJeztah. A PR #30661 has been created for the API history and man page. Please take a look.

2020-01-24 07:06 UTC, Tusenka commented
It doesn't work for me( I can filter only port to, not from

2020-01-24 09:58 UTC, thaJeztah commented
Yes, something looks to be off.

Create some containers;


```bash
docker run -d --name test_no_ports nginx:alpine
docker run -d --name test_port_1080 -p 1080:80 nginx:alpine
docker run -d --name test_port_1090 -p 1090:80 nginx:alpine
docker run -d --name test_port_80_random -p 80 nginx:alpine
docker run -d --name test_port_all_random -P nginx:alpine


docker ps --filter name=test_

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
3ce8232cdd04        nginx:alpine        "nginx -g 'daemon of…"   6 seconds ago       Up 6 seconds        0.0.0.0:32775->80/tcp   test_port_all_random
7f8fad7a0eb9        nginx:alpine        "nginx -g 'daemon of…"   7 seconds ago       Up 6 seconds        0.0.0.0:32774->80/tcp   test_port_80_random
3870ccc2f8f7        nginx:alpine        "nginx -g 'daemon of…"   7 seconds ago       Up 6 seconds        0.0.0.0:1090->80/tcp    test_port_1090
aa565211513e        nginx:alpine        "nginx -g 'daemon of…"   8 seconds ago       Up 7 seconds        0.0.0.0:1080->80/tcp    test_port_1080
c4a1c6e0e99b        nginx:alpine        "nginx -g 'daemon of…"   8 seconds ago       Up 7 seconds        80/tcp                  test_no_ports
```

Filtering on the "exposed" port works:

```bash
docker ps --filter name=test_ --filter expose=80

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
3ce8232cdd04        nginx:alpine        "nginx -g 'daemon of…"   20 seconds ago      Up 19 seconds       0.0.0.0:32775->80/tcp   test_port_all_random
7f8fad7a0eb9        nginx:alpine        "nginx -g 'daemon of…"   21 seconds ago      Up 20 seconds       0.0.0.0:32774->80/tcp   test_port_80_random
3870ccc2f8f7        nginx:alpine        "nginx -g 'daemon of…"   21 seconds ago      Up 20 seconds       0.0.0.0:1090->80/tcp    test_port_1090
aa565211513e        nginx:alpine        "nginx -g 'daemon of…"   22 seconds ago      Up 20 seconds       0.0.0.0:1080->80/tcp    test_port_1080
c4a1c6e0e99b        nginx:alpine        "nginx -g 'daemon of…"   22 seconds ago      Up 21 seconds       80/tcp                  test_no_ports

docker ps --filter name=test_ --filter expose=90
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Filtering on the "published" port doesn't (trying some variations below):

```bash
docker ps --filter name=test_ --filter publish=1080
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                 NAME


docker ps --filter name=test_ --filter publish=1080/tcp
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                 NAMES

docker ps --filter name=test_ --filter publish=1080/udp
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                 NAMES
```

However, using the "exposed" port number instead of the "published" port shows _some_ results:


```bash
docker ps --filter name=test_ --filter publish=80
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                   NAMES
7f8fad7a0eb9        nginx:alpine        "nginx -g 'daemon of…"   About a minute ago   Up About a minute   0.0.0.0:32774->80/tcp   test_port_80_random
3870ccc2f8f7        nginx:alpine        "nginx -g 'daemon of…"   About a minute ago   Up About a minute   0.0.0.0:1090->80/tcp    test_port_1090
aa565211513e        nginx:alpine        "nginx -g 'daemon of…"   About a minute ago   Up About a minute   0.0.0.0:1080->80/tcp    test_port_1080
```

It appears it's filtering on the wrong value; also, the container with "random" port-mapping for all ports is missing in this case (perhaps it's filtering on ports that were _explicitly_ configured to be published?)


Note that the `TestPsListContainersFilterPorts` test-case doesn't appear to catch this issue because it appears to be filtering on port `80` (which is published to a _random_ port);


```bash
docker run -d --publish 80 busybox top
537c87330e660cc4d7a7426dcddd771a3b1bb3f7c21c7750a4b1a3358e976b1c

docker ps --filter publish=80
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
537c87330e66        busybox             "top"                    19 seconds ago      Up 18 seconds       0.0.0.0:32776->80/tcp   sleepy_khorana
...
```

2020-01-24 10:01 UTC, thaJeztah commented
opened https://github.com/moby/moby/issues/40405