1.12.3 Changelog
moby/moby pull request #27611
Opened 2016-10-20 23:56 UTC by vieux

ping @thaJeztah

2016-10-21 00:37 UTC, thaJeztah reviewed
couple of nits / suggestions, but LGTM otherwise

2016-10-21 00:37 UTC, thaJeztah commented on CHANGELOG.md
> +* Remount everything as private in new mntns [#27609](https://github.com/docker/docker/pull/27609)
Should probably describe what it's fixing as well; Also should this be in the "Builder" section?

```
* Fix an error when trying to `ADD` or `COPY` files to the root  (`/`) of the container's filesystem
```

@tonistiigi SGTY? ^^

2016-10-21 00:37 UTC, thaJeztah commented on CHANGELOG.md
> + * Avoid restarting a task that has already been restarted [docker/swarmkit#1305]
Missing https://github.com/ here and couple below

2016-10-21 00:49 UTC, tonistiigi commented on CHANGELOG.md
> +* Remount everything as private in new mntns [#27609](https://github.com/docker/docker/pull/27609)
The problem is in file extraction so not directly related to builder. Could probably happen in pull/load/cp as well in certain conditions. I'd add "during extraction ...". Or "Properly handle shared mount propagation in storage directory".

2016-10-21 00:51 UTC, vieux commented on CHANGELOG.md
> +* Remount everything as private in new mntns [#27609](https://github.com/docker/docker/pull/27609)
I like `Properly handle shared mount propagation in storage directory`

2016-10-21 00:53 UTC, thaJeztah commented on CHANGELOG.md
> +* Remount everything as private in new mntns [#27609](https://github.com/docker/docker/pull/27609)
SGTM

2016-10-21 21:18 UTC, vieux commented
please take a look @aaronlehmann @mrjana @riyazdf

2016-10-21 21:27 UTC, mrjana commented on CHANGELOG.md
> +
Add the following as well:
   * Fix a deadlock in networking code [docker/libnetwork#1507](https://github.com/docker/libnetwork/pull/1507)
   * Fix a race in load balancer state [docker/libnetwork#1512](https://github.com/docker/libnetwork/pull/1512)

2016-10-21 21:29 UTC, icecrime requested changes

2016-10-21 21:29 UTC, icecrime commented on CHANGELOG.md
> +* Vendor Swarmkit [#27554](https://github.com/docker/docker/pull/27554)
Maybe "Update" instead of "Vendor"?

2016-10-21 21:29 UTC, icecrime commented on CHANGELOG.md
> + * Avoid restarting a task that has already been restarted [https://github.com/docker/swarmkit/pull/1305]
I don't know if that's intentional, but this isn't a properly formatted markdown link.

2016-10-21 21:44 UTC, riyazdf requested changes

2016-10-21 21:44 UTC, riyazdf commented on CHANGELOG.md
> +- Fix user permissions in containers (CVE-2016-8867) [#27610](https://github.com/docker/docker/pull/27610)
s/Fix user permissions in containers/Fix ambient capability usage in containers/

2016-10-21 21:56 UTC, AkihiroSuda commented on CHANGELOG.md
> +- Fix user permissions in containers (CVE-2016-8867) [#27610](https://github.com/docker/docker/pull/27610)
CVE-2016-8867 not published yet?


http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-8867

2016-10-21 23:50 UTC, vieux commented on CHANGELOG.md
> + * Avoid restarting a task that has already been restarted [https://github.com/docker/swarmkit/pull/1305]
thanks

2016-10-21 23:54 UTC, vieux commented
@icecrime @riyazdf PTAL

2016-10-22 00:06 UTC, riyazdf commented
LGTM

2016-10-22 19:48 UTC, icecrime commented
LGTM

2016-10-22 19:49 UTC, icecrime approved these changes

2016-10-22 19:49 UTC, icecrime commented on CHANGELOG.md
> +### Logging
Minor nit: missing new line.

2016-10-22 19:56 UTC, vieux commented on CHANGELOG.md
> +### Logging
thanks.

2016-10-22 21:54 UTC, riyazdf approved these changes
LGTM

2016-10-24 08:24 UTC, merged