client: add accessor methods for client.customHTTPHeaders
moby/moby pull request #27622
Opened 2016-10-21 05:46 UTC by AkihiroSuda

`client.NewEnvClient()` does not support setting custom HTTP headers, unlike `client.NewClient(host string, version string, client *http.Client, httpHeaders map[string]string)`.

So I suggest adding these methods so that we can set headers for an env client:

 - `*Client.CustomHTTPHeaders() map[string]string`
 - `*Client.UpdateCustomHTTPHeaders(headers map[string]string)`

Example ( see also https://github.com/docker/docker-e2e/pull/21/files ):
```go
cli, err := client.NewEnvClient()
if err != nil { .. }
cli.UpdateClientVersion()
cli.UpdateCustomHTTPHeaders(map[string]string{"User-Agent": "engine-api-cli-1.0"})
```

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2016-10-28 02:27 UTC, AkihiroSuda commented on client/client.go
> +	customHTTPHeadersMu sync.Mutex
removed mutex

2016-10-28 04:04 UTC, thaJeztah commented
ping @vieux @dmcgowan PTAL

2016-11-28 22:29 UTC, mlaventure requested changes

2016-11-28 22:29 UTC, mlaventure commented on client/client.go
> +func (cli *Client) UpdateCustomHTTPHeaders(headers map[string]string) {
Could we call this `SetCustomHTTPHeaders` instead? Being named `Update...` I was assuming it was going to merge both maps at first

2016-11-29 16:10 UTC, mlaventure approved these changes

2016-11-29 18:35 UTC, dmcgowan commented
LGTM

2016-11-29 21:15 UTC, mlaventure commented
LGTM

2016-11-29 21:18 UTC, thaJeztah approved these changes
LGTM, thanks for reviewing @dmcgowan

2016-11-29 21:18 UTC, merged