build debian package for armhf ubuntu-xenial
moby/moby pull request #27628
Opened 2016-10-21 09:33 UTC by flixr

**- What I did**
Add a Dockerfile to build armhf deb package for Ubuntu Xenial (16.04)

**- How to verify it**
Build deb, install, enjoy...

**- Description for the changelog**
Build armhf debian package for Ubuntu 16.04

Signed-off-by: Felix Ruess <felix.ruess@gmail.com>

2016-10-26 13:29 UTC, tophj-ibm commented
tested this on my rpi and everything made / installed correctly. 👍

2016-11-01 06:49 UTC, thaJeztah commented
ping @tianon @tiborvass @andrewhsu PTAL

2016-11-01 07:55 UTC, StefanScherer commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +ENV GO_VERSION 1.7.1
This should be updated to GO_VERSION 1.7.3

2016-11-08 12:25 UTC, justincormack requested changes

2016-11-08 12:25 UTC, justincormack commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN curl -fSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-armv6l.tar.gz" | tar xzC /usr/local
This should be from golang.org see changes in the other ones recently

2016-11-08 12:39 UTC, thaJeztah commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN curl -fSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-armv6l.tar.gz" | tar xzC /usr/local
We should start working on an update/create a generate.sh for armhf, like we have for amd64; https://github.com/docker/docker/blob/master/contrib/builder/deb/amd64/build.sh

2016-11-08 18:17 UTC, andrewhsu commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN curl -fSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-armv6l.tar.gz" | tar xzC /usr/local
fyi justin is referring to #28068

2016-11-08 18:21 UTC, andrewhsu commented
I've confirmed building an image from this `Dockerfile` works on `armv7l`.

2016-11-08 21:47 UTC, flixr commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN curl -fSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-armv6l.tar.gz" | tar xzC /usr/local
Thx, fixed.
And yes, a script would be the way to go... don't have the time for that right now though.

2016-11-15 19:02 UTC, andrewhsu commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN curl -fSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-armv6l.tar.gz" | tar xzC /usr/local
LGTM

2016-11-20 19:20 UTC, andrewhsu commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN apt-get update && apt-get install -y apparmor bash-completion btrfs-tools build-essential curl ca-certificates debhelper dh-apparmor dh-systemd git libapparmor-dev libdevmapper-dev libltdl-dev li
don't forget to keep it alphabetical :)

2016-11-21 11:35 UTC, flixr commented on contrib/builder/deb/armhf/ubuntu-xenial/Dockerfile
> +RUN apt-get update && apt-get install -y apparmor bash-completion btrfs-tools build-essential curl ca-certificates debhelper dh-apparmor dh-systemd git libapparmor-dev libdevmapper-dev libltdl-dev li
done

2016-11-21 11:35 UTC, flixr commented
@justincormack done

2016-11-22 01:24 UTC, andrewhsu commented
LGTM

2016-11-22 09:12 UTC, justincormack approved these changes

2016-11-22 10:47 UTC, thaJeztah approved these changes
LGTM, thank you!

2016-11-22 10:47 UTC, merged