get node before Updating Node
moby/moby pull request #27631
Opened 2016-10-21 10:20 UTC by allencloud

In Node operation, no matter GET, DELETE or UPDATE, I think it is better to getNode first  to avoid some corner case. After that, doing the correct action will be perfect.

**- What I did**
1. In update Node,  make docker engine getNode before updating. This pr makes it consistent with service actions.

ping @aaronlehmann 

Signed-off-by: allencloud <allen.sun@daocloud.io>

2016-10-22 01:08 UTC, allencloud commented
doing this will make engine judge if the node is not found, or has multi choices.
If there is not exact one, engine should return some error like in helper.go
```
if len(rl.Nodes) == 0 {
			return nil, fmt.Errorf("node %s not found", input)
		}

		if l := len(rl.Nodes); l > 1 {
			return nil, fmt.Errorf("node %s is ambiguous (%d matches found)", input, l)
		}
```
instead of directly call `c.client.UpdateNode(`.

2016-10-22 01:18 UTC, aaronlehmann commented
`NodeUpdate` takes a node ID, not a name or prefix.

This is documented in the API reference:

```
### Update a node


`POST /nodes/(id)/update`

Update the node `id`.
```

Also, the CLI client code is written with this in mind:

```go
err = client.NodeUpdate(ctx, node.ID, node.Version, node.Spec)
```

So there is no chance of multiple nodes matching, and it shouldn't be necessary to call `getNode`.

2016-10-22 01:26 UTC, allencloud commented
Oh, great. Thanks a lot for the detailed explanation @aaronlehmann 
I think ID not name string is the key point.
Closing this. Sorry for the bothering.

2016-11-13 04:13 UTC, allencloud commented
ping @aaronlehmann @tonistiigi 
I reopened this PR.
Sorry for the bothering brought to you guys, my friends. To be honest, I wish we could take one time here to check my proposal. And I added more here in the PR description. 

PTAL, thanks.

2016-11-14 18:43 UTC, aaronlehmann commented
I think this is the right direction. It would address https://github.com/docker/docker/issues/25574.

LGTM

2016-11-14 19:14 UTC, tonistiigi commented
LGTM

Seems the delete/get endpoint need the same docs change though. Could be done in a follow up.

2016-11-15 04:10 UTC, allencloud commented
@tonistiigi  
I changed the 1.24 and 1.25 docs for delete/get endpoint. I do not change Update endpoint  in 1.24, because I think it is already frozen.

PTAL

2016-11-15 16:27 UTC, thaJeztah commented
never really been a fan of having `name` in the API, but I guess it's consistent with the other endpoints.

2016-11-15 17:47 UTC, tonistiigi commented
LGTM

2016-11-15 20:08 UTC, thaJeztah requested changes
have some notes (see below)

2016-11-15 20:08 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.24.md
> +`GET /nodes/(id or name)`
We should not include this in the 1.24 documentation, given that docker 1.12 will not support this.

2016-11-15 20:08 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
> +Remove a node `id` from the swarm.
I'd remove `id` here, just "Remove a node from the swarm." that describes what the endpoint does

2016-11-15 20:08 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
>  Update the node `id`.
Perhaps simplify to "Update a node" here as well, or "Update a node, identified by `id` or `name`", but possibly that's too verbose

2016-11-15 20:08 UTC, thaJeztah commented on docs/reference/api/docker_remote_api.md
> +* `POST /node/(id or name)/update` now receives a node name as a parameter.
I'd change "receives", something like;

```
* `POST /node/(id or name)/update` now accepts both `id` or `name` to identify the node to update
```

Should `DELETE` also be mentioned here?

2016-11-15 21:11 UTC, tonistiigi commented on docs/reference/api/docker_remote_api_v1.24.md
> +`GET /nodes/(id or name)`
get/delete already support name in `v1.12` but it was not documented.

2016-11-16 02:23 UTC, allencloud commented on docs/reference/api/docker_remote_api_v1.24.md
> +`GET /nodes/(id or name)`
Yes, get/delete already support name in v1.12, but the document has not addressed that.

2016-11-16 02:23 UTC, allencloud commented on docs/reference/api/docker_remote_api.md
> +* `POST /node/(id or name)/update` now receives a node name as a parameter.
Thanks @thaJeztah 
Updated that. PTAL

2016-11-16 16:23 UTC, allencloud commented
Thanks @thaJeztah 
Now updated. PTAL 😄

2016-11-16 16:39 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-16 16:47 UTC, vdemeester approved these changes
LGTM :frog:

2016-11-16 16:47 UTC, merged