change network route url
moby/moby pull request #27725
Opened 2016-10-25 09:28 UTC by allencloud

I am not sure whether the original code is out of some legacy concern.

While I think the new style is enough. However this PR makes `GET /networks/` behave different.  Maybe a little bit back compatibility has been broken.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: allencloud <allen.sun@daocloud.io>

2016-10-26 16:50 UTC, thaJeztah requested changes

2016-10-26 16:50 UTC, thaJeztah commented on api/server/router/network/network.go
> -		router.NewGetRoute("/networks/", r.getNetworksList),
This route was added on purpose; see https://github.com/docker/docker/pull/24634

2016-10-26 16:52 UTC, thaJeztah commented
@allencloud I'll close this PR as these routes were like this for a reason, but let me know if there's a reason you wanted to change this

2016-10-26 16:52 UTC, closed without merging

2016-10-27 02:38 UTC, allencloud commented
Oh great. @thaJeztah  Thanks for solving my confusion.