Fix stack overflow in ErrInAdequateCapacity.
moby/moby pull request #27758
Opened 2016-10-25 23:28 UTC by anusha-ragunathan

fmt package formats an error by calling its Error() method.
This results in recursion. Fix this. Also remove dead code.

Signed-off-by: Anusha Ragunathan <anusha@docker.com>

2016-10-25 23:54 UTC, anusha-ragunathan commented
cc @riyazdf

2016-10-25 23:57 UTC, riyazdf approved these changes
tested manually with `riyaz/authz-plugin-bad-manifest`, and functionality LGTM.

Wondering if we can add a unit test case for `FilterByCap`?  I can add an integration test with `riyaz/authz-plugin-bad-manifest` in my testing PR.

2016-10-26 00:01 UTC, anusha-ragunathan commented
Thanks for testing @riyazdf. I can add unit test for `FilterByCap`

2016-10-28 18:48 UTC, thaJeztah commented
ping @riyazdf PTAL - unit test was added

also ping @vieux @tiborvass PTAL

2016-10-28 18:52 UTC, tiborvass requested changes

2016-10-28 18:52 UTC, tiborvass commented on plugin/v2/plugin.go
> -	return fmt.Sprintf("plugin does not provide %q capability", cap)
@anusha-ragunathan the fix is to just change `cap` to `string(cap)`

2016-10-28 18:56 UTC, anusha-ragunathan commented on plugin/v2/plugin.go
> -	return fmt.Sprintf("plugin does not provide %q capability", cap)
I'm following the convention used in https://github.com/docker/docker/blob/master/client/errors.go. This is absolutely fine as well.

2016-10-28 18:58 UTC, tiborvass commented
LGTM

2016-10-28 18:58 UTC, tiborvass approved these changes

2016-10-28 20:10 UTC, vieux commented
LGTM

2016-10-28 20:10 UTC, merged

2016-10-29 00:00 UTC, riyazdf commented on plugin/store/store_test.go
> +		t.Fatalf("expected inadequate error, got %v", err)
awesome, thank you for adding these 👍