Service create --group param
moby/moby pull request #27800
Opened 2016-10-26 19:50 UTC by lilybguo

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

--group-add was used for specifying groups for both service create
and service update. For create it was confusing since we don't have
an existing set of groups. Instead I added --group to create, and
moved --group-add to service update only, like --group-rm
This deals with issue 27646

Signed-off-by: Lily Guo <lily.guo@docker.com>

2016-10-26 20:11 UTC, stevvooe commented on cli/command/service/create.go
> +	flags.StringSliceVar(&opts.groups, flagGroup, []string{}, "Set additional user groups to the container")
"Set supplementary user groups", per https://en.wikipedia.org/wiki/Group_identifier#Supplementary_groups.

2016-10-26 20:11 UTC, stevvooe commented
LGTM after minor nit.

2016-10-26 20:12 UTC, stevvooe commented on cli/command/service/create.go
> +	flags.StringSliceVar(&opts.groups, flagGroup, []string{}, "Set additional user groups to the container")
Maybe make it clear that this is a repeated flag:

> Set one or more supplementary user groups for the container

2016-10-26 20:15 UTC, lilybguo commented on cli/command/service/create.go
> +	flags.StringSliceVar(&opts.groups, flagGroup, []string{}, "Set additional user groups to the container")
for update the doc doesn't specify "supplementary", it just says "user groups",  should I update that?

2016-10-27 00:54 UTC, vdemeester approved these changes
LGTM 🐸

2016-10-27 00:57 UTC, thaJeztah requested changes
@lilybguo can you also
- update the completion scripts (which were updated for this in https://github.com/docker/docker/pull/26301, and https://github.com/docker/docker/pull/26478)
- squash your commits

Let us know if you need help on the completion scripts, otherwise it can be handled in a follow up

2016-10-27 00:59 UTC, thaJeztah requested changes

2016-10-27 00:59 UTC, thaJeztah commented on docs/reference/commandline/service_create.md
> +      --group value                      Set additional user groups to the container (default [])
Looks like the documentation doesn't match the actual flag description?

2016-10-27 00:59 UTC, thaJeztah commented on cli/command/service/update.go
> +	flags.Var(newListOptsVar(), flagGroupRemove, "Remove previously added supplementary user groups from the container")
Can you update the documentation to match the new flag descriptions?

2016-10-28 20:06 UTC, crosbymichael commented
@lilybguo can you rebase this and then I'll review today.  Thanks.

2016-10-28 20:57 UTC, thaJeztah approved these changes
LGTM, thanks for contributing @lilybguo

2016-10-28 21:01 UTC, merged