fill the complete address because of no userguide directory
moby/moby pull request #27815
Opened 2016-10-27 07:53 UTC by lixiaobing10051267

fill the complete address because of no userguide directory

2016-10-27 16:03 UTC, vdemeester commented
/cc @thaJeztah @mstanleyjones

2016-10-27 16:11 UTC, thaJeztah requested changes
left some comments

2016-10-27 16:11 UTC, thaJeztah commented on docs/reference/api/hub_registry_spec.md
> +overview](https://docs.docker.com/engine/userguide/eng-image/image_management.md) in the current documentation set.
should be without `.md`; `https://docs.docker.com/engine/userguide/eng-image/image_management/`

2016-10-27 16:11 UTC, thaJeztah commented on docs/reference/builder.md
> +Practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices.md) for a tip-oriented guide.
same here (no `.md`)

2016-10-27 16:11 UTC, thaJeztah commented on docs/reference/builder.md
> +(For more information, see the [Build cache section](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices.md#build-cache)) in the
should be `https://docker.github.io/engine/userguide/eng-image/dockerfile_best-practices/#/build-cache`

2016-10-27 16:11 UTC, thaJeztah commented on docs/reference/builder.md
> +guide](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices.md#build-cache) for more information.
same here; `https://docker.github.io/engine/userguide/eng-image/dockerfile_best-practices/#/build-cache`

2016-10-27 16:11 UTC, thaJeztah commented on docs/reference/builder.md
> +guide](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices.md#build-cache) for more information.
same here `https://docker.github.io/engine/userguide/eng-image/dockerfile_best-practices/#/build-cache`

2016-10-28 02:27 UTC, lixiaobing10051267 commented
ok, has been modified:)

2016-10-28 03:34 UTC, thaJeztah approved these changes
LGTM

2016-10-28 20:03 UTC, mdlinville approved these changes
LGTM, thank you!

2016-10-28 20:04 UTC, merged