Fix install script for multiarch
moby/moby pull request #27835
Opened 2016-10-27 20:16 UTC by tophj-ibm

The current check for uname -m just looks for *64 which hits a lot
more cases than it should (mips64 for ex.), and ignores a few that it shouldn't.

This check will run the install script if on a supported architecture
(x86_64 or amd64) or an unofficial one with a docker repository
(armv6l or armv7l) and will give a more accurate error on an unofficial
64-bit architecture that isn't in the docker repository.

For architectures I just referenced the go list here https://golang.org/doc/install/source,
and couldn't think of any more that should hit these cases.

Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>

![gazelle](http://media.dmnews.com/images/2015/07/13/gazellejumping_800911.jpg)

2016-10-28 00:43 UTC, thaJeztah requested changes
looks like your editor does the same as mine

<img width="267" alt="screen shot 2016-10-27 at 5 42 24 pm" src="https://cloud.githubusercontent.com/assets/1804568/19790415/c4fa00f4-9c6c-11e6-8c96-501510e08a9f.png">

2016-10-28 00:43 UTC, thaJeztah commented
ping @tianon please take a look :heart:

/cc @mlaventure

2016-10-28 13:30 UTC, tophj-ibm commented on hack/install.sh
> +			Error: Docker doesn't officially support $(uname -m) and no Docker $(uname -m) repository exists.
yeah that's probably the sane thing to do 😄

2016-10-28 14:53 UTC, mlaventure commented
LGTM

2016-10-29 17:24 UTC, justincormack requested changes

2016-10-29 17:24 UTC, justincormack commented on hack/install.sh
> +			Error: $architecture is not a recognized 64bit platform or a Raspberry Pi (armv6l/armv7l).
we support non raspberry pi arm, can we just say `not a recognised platform`?

2016-11-02 13:39 UTC, tophj-ibm commented
updated PTAL

2016-11-02 16:42 UTC, thaJeztah approved these changes
LGTM

2016-11-02 17:12 UTC, justincormack approved these changes

2016-11-02 17:14 UTC, merged