Deprecate API calls without a version
moby/moby pull request #27830
Opened 2016-10-27 17:07 UTC by bfirsh

**- What I did**

At some point it would be good to make providing a version to API calls mandatory. See #21157 for more information.

However, this will break clients, so we should mark it as deprecated before making the change. See #27801 for the proposed actual change and discussion around deprecation.

**- Description for the changelog**

Not providing an API version in API calls is now deprecated, and those endpoints will be removed in a future version of Docker. Instead of just requesting, for example, the URL /containers/json, you must now request /v1.25/containers/json.

2016-10-27 17:13 UTC, vdemeester commented
/cc @thaJeztah @icecrime this should be for 1.13 right ? 👼

2016-10-27 17:55 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.18.md
> +    GET /v1.18/images/search?term=sshd HTTP/1.1
hmf, this is gonna be a nightmare to keep the API docs in sync. Well, until we move to Swagger :smile:

2016-10-27 17:57 UTC, thaJeztah commented
It's ok to discuss for 1.13, but no decision was made yet I think.

Should we have a redirect? (does that even work if a socket connection is used?)

2016-10-27 17:58 UTC, bfirsh commented on docs/reference/api/docker_remote_api_v1.18.md
> +    GET /v1.18/images/search?term=sshd HTTP/1.1
Even with static docs, it isn't too bad – you just have to do a big regex search/replace for each new version.

I did something like this: `s/(GET|POST|PATCH|PUT|HEAD|OPTIONS) /(.+?) HTTP/$1 /v1.25/$2 HTTP/`

2016-10-27 18:01 UTC, bfirsh commented
We could have a redirect when it is deprecated, but I don't think we should do it now. It will break clients which do not follow redirects. E.g. even curl doesn't do it by default.

2016-10-27 19:02 UTC, vieux commented
NOT LGTM,


at least `/_ping` without version is necessary for https://github.com/docker/docker/pull/27745

2016-10-27 19:02 UTC, vieux requested changes
`/_ping` without version is required for https://github.com/docker/docker/pull/27745

2016-10-27 20:22 UTC, bfirsh commented
@vieux Perhaps `/_ping` could be the one exception. That seems so simple that it needn't be versioned.

2016-10-27 20:49 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.18.md
> +    GET /v1.18/images/search?term=sshd HTTP/1.1
We should add that to the release-checklist (there's a section in there that explains bumping the API version)

2016-10-28 23:53 UTC, thaJeztah commented
@bfirsh can you add this to https://github.com/docker/docker/blob/master/docs/deprecated.md as well?

2016-10-31 01:15 UTC, MHBauer commented
Idea sounds good to me. We're saying that the version is required, to prepare people and get them ready for the actual change made in a couple of versions, per the deprecation policy. There's no code change, just documentation, because we already support versioned access on the API. Thus we only need doc changes for now. As above, we should mention it in the deprecation section.

I am kind of surprised we didn't have the version hardcoded on each of the version specific pages.

2016-10-31 01:50 UTC, bfirsh commented
@thaJeztah Done! :sparkles:

@vieux Do you think making `/_ping` the only endpoint allowed without a version a reasonable solution? I suppose it should always remain stable, under the definition that it should return some content with a 200 status code.

2016-11-03 08:00 UTC, thaJeztah approved these changes
LGTM

2016-11-08 00:07 UTC, vieux commented
I'm ok with only `ping` accessible without version.

2016-11-08 00:07 UTC, vieux approved these changes

2016-11-09 16:06 UTC, thaJeztah commented
needs a rebase, so carried in https://github.com/docker/docker/pull/28208

2016-11-09 16:06 UTC, closed without merging