Add "userns" to `docker info` security options output
moby/moby pull request #27840
Opened 2016-10-27 22:39 UTC by estesp

Fixes: #27740 

If user namespaces is enabled on the daemon, reveal that via docker info
by adding "userns" to the list of security options reported by the
info endpoint.

Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

2016-10-27 22:49 UTC, vdemeester approved these changes
LGTM 👼

2016-10-27 22:52 UTC, thaJeztah requested changes
just some nits, also, can you;
- make a mention in the API changes; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md#v125-api-changes. It's not a breaking change, but nice to mention that it now returns a possible new value
- Can you add `"userns"` to the output example in https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.25.md#display-system-wide-information.

2016-10-27 22:52 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +not, the output of `docker info` has been expanded. If the daemon is configured
We don't have to explain that "it has been expanded" (since what?); docs reflect current state of the code, not a changelog :smile:

2016-10-28 11:43 UTC, justincormack approved these changes

2016-10-28 23:21 UTC, estesp commented
Thanks @thaJeztah! Latest push has the extra updates and reworked wording in docs

2016-10-28 23:24 UTC, thaJeztah approved these changes
perfect! LGTM thanks!

2016-10-29 00:58 UTC, merged