Adding the hostname option to docker service command
moby/moby pull request #27857
Opened 2016-10-28 12:49 UTC by niau

This PL is in addition to #25437  
**- What I did**
 Added option hostname in docker service create command. 
**- How I did it**
 I changed the docker client, updated the ContainerSpec structures in docker/swarm repo, so that this option is serialized to the swarm agents from the clients.
**- How to verify it**
 docker service create --name test --hostname vasko
docker exec test.1. hostname
**- Description for the changelog**
This pull request will allow to specify hostname option to the docker service create command.
The same hostname will be set on all containers.
**- A picture of a cute animal (not mandatory but encouraged)**
Since the hostname got quite persistent in its unwillingness to be rebased :) You got a picture of the cutest and the most persistent animal on the world ;) 
![water bears](https://cloud.githubusercontent.com/assets/1587485/19778288/bac5fa3a-9c84-11e6-8862-bb9e4963ac76.jpg)

Signed-off-by: Nikolay Milovanov <nmil@itransformers.net>

2016-10-28 18:12 UTC, niau commented
@stevvooe this is second part of the pull request for the docker service hostname feature. In #25437 we got only the vendoring part. To get it feature complete this one has also to go through.

2016-11-01 22:06 UTC, stevvooe commented
LGTM

2016-11-02 07:12 UTC, vdemeester commented
@niau needs a rebase 👼

2016-11-02 16:56 UTC, niau commented
@vdemeester clean as a baby ass :)

2016-11-02 17:02 UTC, vdemeester approved these changes
LGTM 🐸

2016-11-02 17:02 UTC, vdemeester commented
Moving to docs-review
/cc @thaJeztah @mstanleyjones

2016-11-02 18:04 UTC, mdlinville requested changes
Please update the reference docs for `swarm service` as well...

2016-11-02 18:40 UTC, niau commented
@mstanleyjones I assume that this means that I have to do another pull request and updater the documents here  https://github.com/docker/docker.github.io/tree/master/engine/reference

2016-11-02 18:54 UTC, mstanleyjones commented
@niau no, sorry for the confusion. The reference docs are maintained in `docker/docker` and brought into the docs repo periodically and currently manually. So you can update them as part of this PR.

2016-11-03 13:18 UTC, niau commented
@mstanleyjones ping

2016-11-03 18:51 UTC, mdlinville approved these changes
docs LGTM

2016-11-04 14:21 UTC, vdemeester approved these changes
docs LGTM 🐸

2016-11-04 14:22 UTC, merged

2016-11-04 16:47 UTC, thaJeztah commented
Do we need this in `docker service update` as well?

2016-11-04 16:48 UTC, thaJeztah commented
also ping @albers @sdurrheimer for completion scripts

2016-11-04 21:33 UTC, niau commented
@vdemeester, @thaJeztah thanks for merging this.  
In the initial use case that we got with @vasil-yordanov there was no need for `docker service update  --hostname`, however i assume it will be more feature complete if update is also supported. 
If you also think that it would be better to support also the update  I don't mind to try to implement that in a week or two.

2016-11-04 22:18 UTC, thaJeztah commented
@niau overall, my thought is that (for services) anything you can set during `create`, you should be able to change using `update` (there are some exceptions), so personally, I would be +1 to have it on update as well

2016-11-05 11:25 UTC, niau commented
@thaJeztah  thanks will try to make it happen. Once ready will spawn a new pull request. Now since we passed through the process would be much easier ;)

2016-11-26 21:36 UTC, yellowmegaman commented
Great job! Any way it can be used to set hostname like this:

docker service create --name test --hostname vasko --replicas 7
docker exec test.2.whatever ping -c2 vasko.1 vasko2 etc?

Looking for some solution like --hostname for i in replicasl set hostname vasko.$i
It could be really rabbitmq and couchbase friendly.

2016-11-26 22:36 UTC, thaJeztah commented
@yellowmegaman see the templating feature that's added in docker 1.13; https://github.com/docker/docker/pull/28486

2016-11-26 22:49 UTC, yellowmegaman commented
@thaJeztah thanks a bunch!