Auto-detect node IP address
moby/moby pull request #27910
Opened 2016-10-31 17:42 UTC by dperny

**- What I did**
The IP address that an agent connects to the manager from is recorded, stored, and exposed through the API. This is useful for many kinds of internal cluster management tools. The field is `Node.Status.Addr`. 

**- How I did it**
Change in swarmkit to support this behavior, then update docker to expose this in its api

**- How to verify it**
`docker node inspect` now shows node address under `Status`, both with and without `--pretty`.

**- Description for the changelog**

Autodetect, store, and expose node IP address as seen by the manager.

**- A picture of a cute animal (not mandatory but encouraged)**
This bird, the violet-backed starling, is purple.
![image](https://cloud.githubusercontent.com/assets/2367858/19864690/8d640904-9f56-11e6-83ec-11f1de20bedc.png)

2016-10-31 22:30 UTC, thaJeztah commented
don't forget to update the docs (CLI reference, API reference), and API changes

2016-11-01 01:10 UTC, aaronlehmann commented
Design LGTM

2016-11-02 20:53 UTC, dperny commented
Rebased and dropped vendoring commit because docker now has swarmkit vendored far enough.

2016-11-02 21:35 UTC, aluzzardi commented
LGTM

2016-11-02 21:36 UTC, aluzzardi commented
@mstanleyjones Do we need docs review on reference docs updates? This is a small API/CLI change

2016-11-02 21:40 UTC, dperny commented
Squashed 2 commits into 1.

2016-11-02 21:56 UTC, thaJeztah commented
@aluzzardi yes, but for small changes, it's usually @vdemeester and myself doing the docs review, and we'll ping @mstanleyjones if assistance is needed 😅

2016-11-02 21:58 UTC, thaJeztah requested changes
oops, found some JSON errors

2016-11-02 21:58 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
>            "State": "ready"
missing a comma

2016-11-02 21:58 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
>          "State": "ready"
missing a comma 😇

2016-11-02 21:58 UTC, thaJeztah commented on docs/reference/commandline/node_inspect.md
>              "State": "ready"
same here

2016-11-03 15:10 UTC, dperny commented
@thaJeztah Fixed JSON errors. Thanks for the catch.

2016-11-03 17:30 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-03 17:30 UTC, merged