Check authz plugins on daemon startup
moby/moby pull request #27914
Opened 2016-10-31 21:14 UTC by riyazdf

When initializing the daemon and its middlewares, check that the specified authorization plugins are already on-disk, accessible to the daemon, and are correctly typed.

We can revert #27804 in this PR or a subsequent one.  There's also some overlap from https://github.com/docker/docker/pull/27752 so I'll rebase on whichever PR is merged last.

cc @anusha-ragunathan @thaJeztah @liron-l 

Closes https://github.com/docker/docker/issues/27909

<img src="http://cdn.wallpapersafari.com/77/58/QaxDAJ.jpg" width="300">

Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

2016-10-31 21:51 UTC, anusha-ragunathan commented on integration-cli/docker_cli_authz_plugin_v2_test.go
> +	authzPluginBadManifestNameWithTag = "riyaz/authz-plugin-bad-manifest"
nit: the plugins dont have a tag, so remove the `WithTag` from the variable.

2016-10-31 22:52 UTC, riyazdf commented on cmd/dockerd/daemon.go
> +	if err = cli.initMiddlewares(api, serverConfig); err != nil {
added the same call to the `reloadConfig` callback

2016-11-01 15:49 UTC, anusha-ragunathan commented on integration-cli/docker_cli_authz_plugin_v2_test.go
> +	out, err = s.d.Cmd("volume", "ls")
Is it necessary to test *all* types of volume requests? If yes, then `docker volume prune` should also be added.

2016-11-01 16:13 UTC, riyazdf commented on integration-cli/docker_cli_authz_plugin_v2_test.go
> +	out, err = s.d.Cmd("volume", "ls")
The plugin should block it already since it just matches against all volume subcommands, so I'll add `docker volume prune` for completeness :+1:

2016-11-01 21:30 UTC, anusha-ragunathan commented
LGTM (experimental failure is unrelated)

2016-11-01 22:58 UTC, tiborvass requested changes

2016-11-01 22:58 UTC, tiborvass commented on cmd/dockerd/daemon.go
> +	if err = cli.initMiddlewares(api, serverConfig); err != nil {
Is the `err =` on purpose? I find it dangerous, knowing that the function returns a named value. I would prefer `err :=`

2016-11-01 23:07 UTC, riyazdf commented on cmd/dockerd/daemon.go
> +	if err = cli.initMiddlewares(api, serverConfig); err != nil {
good point, done.

2016-11-02 00:35 UTC, tiborvass approved these changes

2016-11-02 00:35 UTC, tiborvass commented
LGTM

2016-11-02 13:37 UTC, vdemeester commented
I'm not sure why, but `experimental` execution is always killed on this PR :sweat: 

```
13:47:32 OK: 1475 passed, 57 skipped
13:47:32 PASS
13:47:32 ---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/test-integration-cli)
13:47:33 ++++ cat bundles/1.13.0-dev/test-integration-cli/d3057fd11ff64/docker.pid
13:47:33 +++ kill 2849
13:47:33 /go/src/github.com/docker/docker/hack/make/.integration-daemon-stop: line 8: kill: (2849) - No such process
14:34:34 Build timed out (after 120 minutes). Marking the build as failed.
14:34:34 Build timed out (after 120 minutes). Marking the build as aborted.
```

Putting back to code-review.

2016-11-02 18:22 UTC, riyazdf commented
@vdemeester: I think I found the culprit: there was bad state from the test daemon tearing itself down before the end of the test.

I added checks that we can restart the daemon with no authorization plugins successfully if it previously tore itself down from a bad or nonexistent plugin, and this passes to completion locally.

2016-11-02 18:24 UTC, anusha-ragunathan commented
The issue is, when the .integration-daemon-stop is trying to kill the test daemon, not the outer daemon.
https://jenkins.dockerproject.org/job/Docker-PRs-experimental/25872/consoleText shows `cat bundles/1.13.0-dev/test-integration-cli/d3057fd11ff64/docker.pid`, instead of `bundles/1.13.0-dev/test-integration-cli/docker.pid`

2016-11-02 20:38 UTC, anusha-ragunathan commented
All tests pass. Merging...

2016-11-02 20:38 UTC, merged