Update for docker volume create
moby/moby pull request #27934
Opened 2016-11-01 07:01 UTC by yuexiao-wang

**- What I did**
Update descriptions for docker volume create

**- How I did it**
**- How to verify it**

**- Description for the changelog**

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

2016-11-02 07:08 UTC, vdemeester commented
/cc @thaJeztah @mstanleyjones

2016-11-02 17:59 UTC, mdlinville requested changes

2016-11-02 17:59 UTC, mstanleyjones commented on cli/command/volume/cmd.go
> +    docker volume COMMAND --help
Is this syntax standard across all the files?

2016-11-02 17:59 UTC, mstanleyjones commented on cli/command/volume/inspect.go
> +Return information about one or more volumes. By default, this command renders
You're not returning, the command is. I think it needs to stay how it was.

2016-11-02 17:59 UTC, mstanleyjones commented on cli/command/volume/create.go
> +Create a new volume that containers can consume and store data in. If a name
You're not creating the volume, the command is. I think it needs to stay how it was.

2016-11-02 17:59 UTC, mstanleyjones commented on cli/command/volume/list.go
> +List all the volumes Docker knows about. You can filter using the **-f** or
I'd keep it how it was, but change 'knows about' to 'manages'.

2016-11-03 01:25 UTC, yuexiao-wang commented on cli/command/volume/cmd.go
> +    docker volume COMMAND --help
I can not find it which is a long  description for CLI command.  I modified it  which referring to the help as follows: 
$ docker volume --help

Usage:	docker volume COMMAND

Manage Docker volumes

Options:
      --help   Print usage

Commands:
  create      Create a volume
  inspect     Display detailed information on one or more volumes
  ls          List volumes
  rm          Remove one or more volumes

Run 'docker volume COMMAND --help' for more information on a command.

2016-11-03 01:26 UTC, yuexiao-wang commented on cli/command/volume/inspect.go
> +Return information about one or more volumes. By default, this command renders
Got it and I will update the PR

2016-11-03 01:26 UTC, yuexiao-wang commented on cli/command/volume/create.go
> +Create a new volume that containers can consume and store data in. If a name
Got it and I will update the PR

2016-11-03 01:26 UTC, yuexiao-wang commented on cli/command/volume/list.go
> +List all the volumes Docker knows about. You can filter using the **-f** or
Got it and I will apply it to this PR.
Thanks

2016-11-03 02:13 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "volume-create" git@github.com:yuexiao-wang/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~2
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-03 02:13 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "volume-create" git@github.com:yuexiao-wang/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~3
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-03 02:31 UTC, yuexiao-wang commented
@mstanleyjones PTAL
Done！

2016-11-03 02:32 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-03 06:10 UTC, vdemeester approved these changes
LGTM 🐸

2016-11-03 06:26 UTC, thaJeztah requested changes

2016-11-03 06:26 UTC, thaJeztah commented on docs/reference/commandline/volume_create.md
> +Create a new volume that containers can consume and store data in. If a name is not specified, Docker generates a random name. You create a volume and then configure the container to use it, for exam
Wait: @yuexiao-wang did you just push again? Looks like this was changed back again

2016-11-03 06:27 UTC, thaJeztah commented on docs/reference/commandline/volume_inspect.md
> +Return information about a volume. By default, this command renders all results
This as well

2016-11-03 06:44 UTC, yuexiao-wang commented on docs/reference/commandline/volume_inspect.md
> +Return information about a volume. By default, this command renders all results
Sorry，it is  careless operation. I want to restart CI when experimental is failed.  I checked it and update the PR.

2016-11-03 06:44 UTC, yuexiao-wang commented
@thaJeztah PTAL

2016-11-03 06:47 UTC, yuexiao-wang commented on docs/reference/commandline/volume_create.md
> +Create a new volume that containers can consume and store data in. If a name is not specified, Docker generates a random name. You create a volume and then configure the container to use it, for exam
Updated

2016-11-03 07:40 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-03 10:12 UTC, merged