Add `--cpus` flag to control cpu resources
moby/moby pull request #27958
Opened 2016-11-01 18:11 UTC by yongtang

**- What I did**

This fix tries to address the proposal raised in #27921 and add `--cpus` flag for `docker run/create`.

**- How I did it**

Basically, `--cpus` will allow user to specify a number (possibly partial) about how many CPUs the container will use. For example, on a 2-CPU system `--cpus 1.5` means the container will take 75% (1.5/2) of the CPU share.

This fix adds a `NanoCPUs` field to `HostConfig` since swarmkit alreay have a concept of NanoCPUs for tasks. The `--cpus` flag will translate the number into reused `NanoCPUs` to be consistent with swarmkit.

Related docs (`docker run` and Remote APIs) have been updated.

**- How to verify it**

This fix adds integration tests to cover the changes.

**- Description for the changelog**

Add `--cpus` flag to control cpu resources for `docker run/create`, and add `NanoCPUs` to `HostConfig`.

**- A picture of a cute animal (not mandatory but encouraged)**

![cute-animals-illu-002](https://cloud.githubusercontent.com/assets/6932348/19901304/e8ae9e50-a023-11e6-8ec8-530841b346e9.jpg)

This fix fixes #27921.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-11-01 18:31 UTC, crosbymichael commented
Thanks for doing this. 

I'm not sure I want to do any of the math on the client side.  I was thinking just passing the raw float from the client and doing the calculations on the server.  I'll look at your implementation more and think about it a little more if we should use swarms nanocpus as what we transfer or not. 

ping @stevvooe @mlaventure wdyt?

2016-11-01 18:48 UTC, mlaventure commented
@crosbymichael had a quick look, it does seem that @yongtang correctly put the computation on the daemon side.

I'm not familiar with the way Swarm handle its scheduling though, I am pretty neutral on that side.

2016-11-01 21:45 UTC, crosbymichael approved these changes
LGTM

2016-11-01 22:23 UTC, stevvooe commented
Confirmed calculations against [swarmkit](https://github.com/docker/swarmkit/blob/master/agent/exec/container/container.go#L393) and [docker executor](https://github.com/docker/docker/blob/master/daemon/cluster/executor/container/container.go#L382).

2016-11-01 22:42 UTC, mlaventure commented on docs/reference/api/docker_remote_api.md
> +* The `HostConfig` field now includes `NanoCPUs` that represents CPU CFS (Completely Fair Scheduler) quota in units of 10<sup>-9</sup> CPU shares.
Just removing the `CFS` reference gives a good enough wording, doesn't it?

2016-11-01 22:43 UTC, mlaventure commented
@stevvooe Any reason why this computation is duplicated? Sounds like it should be in a `utils` package of some sort.

2016-11-02 00:40 UTC, stevvooe commented
@mlaventure Only because "a little copying is better than a little dependency". We'd like to share more code in `swarmkit/agent/exec/container` and `docker/daemon/executor` but don't want to start that without a plan.

2016-11-02 01:07 UTC, cpuguy83 commented
Moved to code review since it seems like this is good.

2016-11-02 01:07 UTC, cpuguy83 requested changes

2016-11-02 01:07 UTC, cpuguy83 commented on daemon/daemon_unix.go
> +		logrus.Warn("Your kernel does not support CPU cfs period/quota or the cgroup is not mounted. NanoCPUs discarded.")
I know for other options we warn, but I feel like we should error out when we can't set this.

2016-11-02 02:13 UTC, yongtang commented on docs/reference/api/docker_remote_api.md
> +* The `HostConfig` field now includes `NanoCPUs` that represents CPU CFS (Completely Fair Scheduler) quota in units of 10<sup>-9</sup> CPU shares.
Thanks @crosbymichael @mlaventure @stevvooe. The wording has been changed to:

The `HostConfig` field now includes `NanoCPUs` that represents CPU quota
in units of 10<sup>-9</sup> CPUs.

2016-11-02 02:14 UTC, yongtang commented on daemon/daemon_unix.go
> +		logrus.Warn("Your kernel does not support CPU cfs period/quota or the cgroup is not mounted. NanoCPUs discarded.")
Thanks @cpuguy83. The warning has been changed to error and PR has been updated.

2016-11-03 07:31 UTC, coolljt0725 reviewed
LGTM, but a typo

2016-11-03 07:31 UTC, coolljt0725 commented on integration-cli/docker_cli_run_unix_test.go
> +	c.Assert(out, checker.Equals, "0", check.Commentf("CPU CFS period shoudl be 0"))
one nit, typo here `shoudl`

2016-11-03 13:56 UTC, yongtang commented
Thanks @coolljt0725. The PR has been updated with typo fixed.

2016-11-03 18:39 UTC, cpuguy83 commented
LGTM but needs a rebase, moving to docs.

2016-11-03 18:50 UTC, yongtang commented
Thanks @cpuguy83. The PR has been rebased.

2016-11-03 18:51 UTC, cpuguy83 approved these changes
LGTM

2016-11-03 18:58 UTC, stevvooe commented on runconfig/opts/parse.go
> +	flags.Float64Var(&copts.cpus, "cpus", 0.0, "Number of CPUs")
There is a type called `nanoCPUs` that can be used here. https://github.com/docker/docker/blob/e93f84a48bb394ed181aa48d9400922b292eb15a/cli/command/service/opts.go#L43

2016-11-03 18:58 UTC, stevvooe commented on man/docker-run.1.md
> +   Number of CPUs. The default is *0.0*.
Clarify that the default means that there is no limit.

2016-11-03 20:19 UTC, yongtang commented on man/docker-run.1.md
> +   Number of CPUs. The default is *0.0*.
Thanks. The docs has been updated.

2016-11-03 20:24 UTC, yongtang commented on runconfig/opts/parse.go
> +	flags.Float64Var(&copts.cpus, "cpus", 0.0, "Number of CPUs")
@stevvooe In #27921 the flag `--cpus` was specified as a float number for the number (could be partial) of cpus (@crosbymichael). Think we need a float here?

2016-11-03 20:37 UTC, stevvooe commented on runconfig/opts/parse.go
> +	flags.Float64Var(&copts.cpus, "cpus", 0.0, "Number of CPUs")
This is not a float. It is a fixed point fractional number. This should be the same as `--limit-cpu` in `docker service create/update`.

2016-11-03 21:54 UTC, yongtang commented on runconfig/opts/parse.go
> +	flags.Float64Var(&copts.cpus, "cpus", 0.0, "Number of CPUs")
@stevvooe I see. Thanks. Let me update the PR shortly.

2016-11-03 22:05 UTC, yongtang commented on runconfig/opts/parse.go
> +	flags.Float64Var(&copts.cpus, "cpus", 0.0, "Number of CPUs")
@stevvooe The PR has been updated. Please take a look and let me know for any issues.

2016-11-03 23:12 UTC, stevvooe approved these changes

2016-11-04 15:58 UTC, mlaventure commented
@yongtang unfortunately this needs one more rebase

2016-11-04 16:47 UTC, yongtang commented
@mlaventure Rebased. Thanks.

2016-11-04 18:11 UTC, crosbymichael commented
LGTM

2016-11-04 18:18 UTC, merged

2016-11-04 18:38 UTC, thaJeztah commented
/cc @albers @sdurrheimer for completion scripts (sorry, there's a lot of new changes recently :smile:)

2016-11-04 18:39 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
> +    -   **NanoCPUs** - CPU quota in units of 10<sup>-9</sup> CPUs.
Should we mention the default here, and what "0" means (unlimited)?

2016-11-04 18:40 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
> +    -   **NanoCPUs** - CPU quota in units of 10<sup>-9</sup> CPUs.
Also, the API takes a different format than the CLI, correct? API is an integer, and CLI a fractional number?

2016-11-04 18:41 UTC, yongtang commented on docs/reference/api/docker_remote_api_v1.25.md
> +    -   **NanoCPUs** - CPU quota in units of 10<sup>-9</sup> CPUs.
@thaJeztah Oh sorry, let me create another PR to catch any additional issues.

2016-11-04 18:43 UTC, thaJeztah commented on docs/reference/api/docker_remote_api_v1.25.md
> +    -   **NanoCPUs** - CPU quota in units of 10<sup>-9</sup> CPUs.
Not your fault, just reading through these, and wondering. So yes, it may need some extra information to prevent confusion

2016-11-04 18:50 UTC, yongtang commented on docs/reference/api/docker_remote_api_v1.25.md
> +    -   **NanoCPUs** - CPU quota in units of 10<sup>-9</sup> CPUs.
Yes. API is an integer in units of 10<sup>-9</sup> CPUs. The CLI is a fraction number that represent the number of 1 CPUs (Could be partial). Created a PR #28075 for that. Please take a look.

2016-11-04 21:16 UTC, thaJeztah commented
@mlaventure @stevvooe I was just discussing with @crosbymichael and realized this is the same thing as `--limit-cpu` on `docker service create`.

For consistency, I think it would make sense to rename the flag so that it matches that WDYT?

2016-11-04 21:52 UTC, tiborvass commented
@thaJeztah what about deprecating `--limit-cpu` and have `--cpu` instead? Shorter.

2016-11-04 22:16 UTC, thaJeztah commented
@tiborvass both could work, although we have `--limit-memory` as well. They _are_ quite descriptive, but I agree it's shorter :smile:

2016-11-05 08:25 UTC, albers commented
I'm in favour of the descriptive variants. Because of their common prefix, they appear grouped in help output, documentation and completions.

2016-11-05 17:25 UTC, thaJeztah commented
@albers @tiborvass I opened https://github.com/docker/docker/issues/28095

2016-11-06 11:26 UTC, sdurrheimer commented
@thaJeztah Will do when we will have finished with `container`, `image` and `system` subcommands.

2017-02-15 01:03 UTC, vincentwoo commented
Hi everyone, any chance we could add `NanoCPUs` to the container update endpoint as well? Right now container updating supports setting `CpuPeriod` and `CpuQuota` already. If `--cpus` or `NanoCPUs` are the new golden-path option for setting these options, I think they should be present in update as well!

2017-02-15 06:29 UTC, thaJeztah commented
@vincentwoo I think that could make sense (as we support other resource options for `docker update`). Can you open an issue for it?