add test plugin install --disable and volume ls
moby/moby pull request #27968
Opened 2016-11-01 22:09 UTC by vieux

add a test for #27924 

ping @anusha-ragunathan @tiborvass

2016-11-01 22:11 UTC, anusha-ragunathan commented
LGTM

2016-11-02 01:34 UTC, cpuguy83 requested changes

2016-11-02 01:34 UTC, cpuguy83 commented on integration-cli/docker_cli_plugins_test.go
> +	_, _, err = dockerCmdWithError("volume", "ls")
Why not `dockerCmd("volume", "ls")`

2016-11-02 01:34 UTC, cpuguy83 commented on integration-cli/docker_cli_plugins_test.go
> +	out, _, err := dockerCmdWithError("plugin", "install", "--grant-all-permissions", "--disable", pName)
Why not `dockerCmd("volume", "ls")`

2016-11-02 01:43 UTC, AkihiroSuda commented
LGTM

2016-11-02 09:24 UTC, vdemeester approved these changes
LGTM once @cpuguy83 comments taken care of 🐸

2016-11-02 21:29 UTC, vieux commented on integration-cli/docker_cli_plugins_test.go
> +	_, _, err = dockerCmdWithError("volume", "ls")
because we want to check the error ?

2016-11-02 21:30 UTC, vdemeester commented on integration-cli/docker_cli_plugins_test.go
> +	_, _, err = dockerCmdWithError("volume", "ls")
@vieux yeah but you check that `err` is nil, that what `dockerCmd("volume", "ls")` basically does 👼

2016-11-03 00:04 UTC, vieux commented
@cpuguy83 PTAL

2016-11-03 00:21 UTC, cpuguy83 approved these changes
LGTM

2016-11-03 00:21 UTC, cpuguy83 commented on integration-cli/docker_cli_plugins_test.go
> +	out, _, err := dockerCmdWithError("plugin", "install", "--grant-all-permissions", "--disable", pName)
Same with this one, can just be `dockerCmd`

2016-11-03 00:39 UTC, vieux commented on integration-cli/docker_cli_plugins_test.go
> +	out, _, err := dockerCmdWithError("plugin", "install", "--grant-all-permissions", "--disable", pName)
here I'm still checking the output for consistency

2016-11-03 00:48 UTC, cpuguy83 commented on integration-cli/docker_cli_plugins_test.go
> +	out, _, err := dockerCmdWithError("plugin", "install", "--grant-all-permissions", "--disable", pName)
Yep, `out, (exitcode) := dockerCmd(...)`

2016-11-03 17:22 UTC, merged