Windows: Rename layers before deletion
moby/moby pull request #27963
Opened 2016-11-01 20:42 UTC by darrenstahlmsft

fixes https://github.com/docker/docker/issues/27570

**- What I did**

Layers are less likely to enter a partially removed state.

**- How I did it**

By renaming the layers to *-removing before removal starts, the rename will fail if the layer is in use, preventing the partial deletion by DestroyLayer.

**- How to verify it**

Manual testing that when a container is leaked, the layer is not partially removed, but instead the rename fails.

Signed-off-by: Darren Stahl <darst@microsoft.com>

2016-11-01 20:50 UTC, MHBauer commented
That seems sane assuming you can't rename an in-use file. Is there any documentation that says so? I am curious more than anything.

Code looks good.

2016-11-01 21:11 UTC, darrenstahlmsft commented
@MHBauer It depends on the flags passed to OpenFile/CreateFile. On Windows, you must request the ability for shared deletion with the FILE_SHARED_DELETE flag at creation, otherwise it cannot be renamed or deleted by other processes. Containers intentionally do not use the FILE_SHARED_DELETE flag, as a result, a rename will fail if the container is in use. There's still the chance for something to grab a file between the rename and the delete, but the layerstore should no longer see the leaked files since they have the -removing in the layer name.

See https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

Thinking about it more, the DestroyLayer errors should be ignored since the folder is already renamed, and we can't do anything about it at that point. It should also be removed from the layer store if the DestroyLayer fails. I've updated the PR slightly.

2016-11-01 21:13 UTC, cpuguy83 requested changes

2016-11-01 21:13 UTC, cpuguy83 commented on daemon/graphdriver/windows/windows.go
> +	tmpLayerPath := path.Join(d.info.HomeDir, tmpID)
How come you are using `path` instead of `filepath`. Won't this create a bunch of `/`?

2016-11-01 21:27 UTC, darrenstahlmsft commented on daemon/graphdriver/windows/windows.go
> +	tmpLayerPath := path.Join(d.info.HomeDir, tmpID)
Ah! That's where the slashes were coming from. Fixed.

2016-11-01 22:49 UTC, darrenstahlmsft commented
/cc @jstarks

2016-11-02 00:45 UTC, cpuguy83 approved these changes
LGTM

2016-11-02 00:51 UTC, jstarks commented on daemon/graphdriver/windows/windows.go
>  	os.RemoveAll(filepath.Join(d.info.HomeDir, "sysfile-backups", rID)) // ok to fail
I believe you can remove this line now. I don't see where we ever populate this directory.

2016-11-02 01:14 UTC, darrenstahlmsft commented on daemon/graphdriver/windows/windows.go
>  	os.RemoveAll(filepath.Join(d.info.HomeDir, "sysfile-backups", rID)) // ok to fail
Yep, removed it.

2016-11-02 01:53 UTC, jstarks commented
LGTM

2016-11-02 09:25 UTC, vdemeester commented
/cc @johnstep

2016-11-03 02:20 UTC, jhowardmsft commented
LGTM. Merging.

2016-11-03 02:20 UTC, merged