Faster validation scripts
moby/moby pull request #27964
Opened 2016-11-01 21:10 UTC by dnephin

Extracted from #27359 

The `hack/make` framework of creating bundle directories and requiring execution of scripts to be run from a driver (hack/make.sh) is "ok" for build tasks that produce artifacts, but has little to no benefit for these validation/check scripts. This PR changes them to source all their dependencies directly, so they no longer require the hack/make.sh driver. Is also moves them from `hack/make` to `hack/validate` so that it's clear they can be run directly without the driver.

They also run as a single process now, so instead of every one of them having to perform a git fetch, hack/validate/all does a single git fetch, reducing the overall runtime of validation.

2016-11-02 03:36 UTC, thaJeztah requested changes
@dnephin some files changed permissions; can you check if that was intentional?

2016-11-02 03:37 UTC, thaJeztah commented
ping @tianon @vdemeester PTAL :heart:

2016-11-02 06:38 UTC, vdemeester reviewed
LGTM 🐸

2016-11-02 06:38 UTC, vdemeester commented on hack/validate/.validate
> -	if [ "$TRAVIS" = 'true' -a "$TRAVIS_PULL_REQUEST" != 'false' ]; then
:heart:

2016-11-02 06:38 UTC, vdemeester commented on Makefile
> +	$(DOCKER_RUN_DOCKER) bash -c 'hack/validate/all && hack/validate/vendor'
Shouldn't `all` be rename default and having a `all` that runs `default` and `vendor ? 👼

2016-11-02 08:10 UTC, thaJeztah approved these changes
nevermind, answering my earlier question; see why they're changed :-) "approving" to neutralize my earlier "request changes"

2016-11-02 15:24 UTC, dnephin commented on Makefile
> +	$(DOCKER_RUN_DOCKER) bash -c 'hack/validate/all && hack/validate/vendor'
hmm, that could work too

2016-11-02 19:04 UTC, tianon reviewed
This is excellent! :heart: :heart:

2016-11-02 19:04 UTC, tianon commented on Makefile
> +	$(DOCKER_RUN_DOCKER) bash -c 'hack/validate/all && hack/validate/vendor'
I agree that `all` is a bit misleading if it doesn't include `vendor` :sweat_smile:

2016-11-02 22:42 UTC, jhowardmsft commented
LGTM. @dnephin Can you open an issue and assign to me once this is merged to cleanup the Windows CI scripts and remove the workarounds. Thanks.

2016-11-02 23:03 UTC, thaJeztah commented
@dnephin can you rename `all`, per https://github.com/docker/docker/pull/27964#discussion_r86219119, then I think we're ready to go

2016-11-03 18:40 UTC, bfirsh commented
Ahah, didn't notice #27964! I'm happy to wait and fix this up after that merges.

2016-11-03 20:25 UTC, dnephin commented
Cool, I moved `all` -> `default` and created a new `all` that is really everything (for `make validate`).

Also rebased

2016-11-03 20:29 UTC, vdemeester approved these changes
Still and even more LGTM 👼

2016-11-03 20:52 UTC, tianon approved these changes

2016-11-03 22:17 UTC, merged