truncate `service ls` command text, add `no-trunc` option. closes #27994
moby/moby pull request #28029
Opened 2016-11-03 14:18 UTC by tealtail

**- What I did**
Added a `--no-trunc` option to `service ls`. 
Truncates display of command text to 20 characters unless `opts.noTrunc` is `True`

**- How I did it**
I used https://github.com/docker/docker/pull/25556 as a guide, but as mentioned in #27994 comments, I fumbled a bit in getting the `noTrunc` bool into `printTable` gracefully. I added a new param to `PrintNotQuiet` to pass it over, but appreciate any advice if there's a better way.
**- How to verify it**
run tests, run command
**- Description for the changelog**
truncate `service ls` command text displayed, new `no-trunc` option

**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://cloud.githubusercontent.com/assets/1327886/19969346/99cf239a-a1ae-11e6-9b3e-05ef8d260527.png)

Signed-off-by: Alicia Lauerman <alicia@eta.im>

2016-11-03 16:49 UTC, aaronlehmann commented
I'd vote for removing the `COMMAND` column instead. I don't think it's very useful. It would keep things simpler not thave this column at all.

2016-11-03 17:48 UTC, tealtail commented
@aaronlehmann okay, yeah, that's much simpler :) I'll update this PR soon to remove the column

2016-11-03 17:55 UTC, thaJeztah commented
We should think about adding a `--format` flag, so that users can customize the output. I'll check if there's an issue for that already, otherwise open one

2016-11-03 18:22 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "27994-add-service-ls-truncate-opt" git@github.com:tealtail/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-03 18:23 UTC, GordonTheTurtle commented
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "27994-add-service-ls-truncate-opt" git@github.com:tealtail/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-03 18:40 UTC, tealtail commented
locally tests pass but the builds triggered by push here failed with 
```
18:33:21 Error response from daemon: No such container: docker-pr-exp26009
[...]
18:33:41 Finished: FAILURE
```

2016-11-03 22:59 UTC, thaJeztah commented
@tealtail looks like this is the actual failure;

```
20:58:29 ---> Making bundle: validate-vet (in bundles/1.13.0-dev/validate-vet)
20:58:29 cli/command/service/list.go:112: missing argument for Fprintf("%s"): format reads arg 5, have only 4 args
20:58:29 cli/command/service/list.go:120: missing argument for Fprintf("%s"): format reads arg 5, have only 4 args
20:58:29 exit status 1
```

2016-11-04 00:19 UTC, tealtail commented
ohhh thanks @thaJeztah okay, so I'm thinking the problem is that `listItemFmt` would need 1 less `%s` now? I'm running tests after making that change and will update the PR again tonight

2016-11-04 19:37 UTC, tealtail commented
all builds are passing now 👍

2016-11-04 21:25 UTC, thaJeztah commented
Awesome!

design LGTM, but a quick check with @aluzzardi if he agrees

2016-11-04 21:27 UTC, aluzzardi commented
LGTM

We actually discussed removing this column a few days ago as it was consuming precious screen real estate with no meaningful use, so 👍

2016-11-04 22:18 UTC, aaronlehmann commented
LGTM

2016-11-04 22:23 UTC, thaJeztah commented
docs changes here LGTM, but ping @mstanleyjones as it's possible other parts of the docs have some example output that needs to be updated

2016-11-04 23:15 UTC, mdlinville requested changes
Does it also affect `service update`, `service rm`, `service inspect`, etc?

2016-11-04 23:21 UTC, tealtail commented
@mstanleyjones yes! some of those still have COMMAND output included in examples. Update incoming.

2016-11-07 20:19 UTC, tealtail commented
@mstanleyjones I've updated this PR with the changes you requested

2016-11-07 22:34 UTC, mstanleyjones commented
LGTM. cc @allencloud please sync #27710 with this change.

2016-11-07 22:39 UTC, merged