Add flag `--add-host` to `docker service create`
moby/moby pull request #28031
Opened 2016-11-03 15:30 UTC by yongtang

**- What I did**

This fix tries to address #27902 by adding a flag `--add-host` to `docker service create`, so that it is possible to specify extra `host:ip` settings in `/etc/hosts`.

*NOTE: 
The flag `--add-host` is to conform to `docker run` but other suggestions are welcomed.
No flag has been added to `docker service update` yet, as I am not sure about what flag should be added for `add/rm` case.*

**- How I did it**

This fix adds `Hosts` in swarmkit's `ContainerSpec` so that it is possible to specify extra hosts during service creation.

Related docs has been updated.

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

Add flag `--add-host` to `docker service create` so that extra host to ip mappings could be added to `/etc/hosts`.

**- A picture of a cute animal (not mandatory but encouraged)**

![super-cute-animals-awsomelycute-com-01586](https://cloud.githubusercontent.com/assets/6932348/19972558/acc316d2-a19f-11e6-9799-dddb1ec9f565.jpg)

This fix fixes #27902.

2016-11-03 16:53 UTC, icecrime commented
Ping @al @mavenugo @dnephin!

2016-11-07 22:38 UTC, aluzzardi requested changes
Great start.

I think we need to support `service update` and also figure out consistency

/cc @icecrime @dnephin @aanand

2016-11-07 22:38 UTC, aluzzardi commented on api/types/swarm/container.go
> +	ExtraHosts      []string                `json:",omitempty"`
This should be `Hosts` like in SwarmKit

2016-11-07 22:38 UTC, aluzzardi commented on cli/command/service/create.go
> +	flags.Var(&opts.extraHosts, flagAddHost, "Add a custom host-to-IP mapping (host:ip)")
To follow convention, this should be:

`--host`

Then, `docker service update` should expose:
- `--host-add`
- `--host-rm`

@dnephin Thoughts?

2016-11-07 22:51 UTC, dnephin commented on cli/command/service/create.go
> +	flags.Var(&opts.extraHosts, flagAddHost, "Add a custom host-to-IP mapping (host:ip)")
ya, I agree

2016-11-08 02:00 UTC, yongtang commented
Thanks @aluzzardi @dnephin @icecrime @aanand for the review. The PR has been updated. Now `service create` takes `--host` flag and `service update` takes `--host-add` and `--host-rm` flag.

Please take a look and let me know for any issues.

2016-11-08 10:53 UTC, vdemeester commented
Desgin LGTM 🐸

2016-11-08 22:18 UTC, dnephin commented on integration-cli/docker_cli_swarm_test.go
> +	d := s.AddDaemon(c, true, true)
I don't think we should have multiple integration tests for every flag. 

Really we only need a couple unit tests for the update function.

2016-11-08 22:28 UTC, stevvooe commented
Design LGTM

2016-11-08 22:41 UTC, aluzzardi commented on docs/reference/commandline/service_create.md
> +      --add-host list                    Add a custom host-to-IP mapping (host:ip) (default [])
Needs to be `--host`
Needs `service update` docs as well

2016-11-08 22:42 UTC, aluzzardi commented
Code LGTM

Need reference docs update: missing `service update` CLI docs and `API` docs

2016-11-08 22:49 UTC, stevvooe commented
After some thought, the new `hosts` API fields should match the [man page for `/etc/hosts`](http://man7.org/linux/man-pages/man5/hosts.5.html). The syntax for each host entry is the following:

```
IP_address canonical_hostname [aliases...]
```

The current format does not correctly represent the concept of aliases, which means we are losing information in transmission. I think we can match this syntax is the swarmkit/services API by insisting on the above syntax.

The approach of keying by hostname should still work here, but ordering control is going to be hard with taking a hosts file as input.

2016-11-09 01:45 UTC, yongtang commented
@stevvooe Do we also want to change the cli input? For example, we might use:
```
docker service create --host "1.2.3.4 myhost" --host "1.1.1.1 example.com example.org"
docker service update --host-rm "example.com" --host-add "5.6.7.8 myhost2"
```

(Currently it is `docker run --add-host "myhost:1.2.3.4")

The advantage is that it is possible for `docker service create --host` to add full record into `/etc/hosts` (it was not possible for `docker run --add-host` to take alias).

The drawback is that it is not consistent with `docker run --add-host`.

2016-11-09 10:29 UTC, vieux commented
@yongtang IMO changing the CLI is a good idea. It might not be consistant with `docker run` but it add more functionalities and we can improve `docker run` later

2016-11-09 11:10 UTC, vdemeester commented
Agreeing with @vieux and @stevvooe, I'm ok to not have the same as `docker run` for `service`. I wonder about `--host-rm` though : for `1.1.1.1 host alias1 alias2`, should we support `--host-rm 1.1.1.1`, `--host-rm host` or both ? (or even with aliases)

2016-11-09 13:52 UTC, thaJeztah commented
I'm not so sure we should change. Changing this to match the format IMO is leaking the underlying implementation, instead of the _intent_ of the user. Now the user has to read the Linux man page for learning the format that `/etc/hosts` uses (is the implementation on Windows the same?)

What if we want to change to a different implementation in future (e.g. add entries to the embedded DNS, instead of updating `/etc/hosts`?)

> The current format does not correctly represent the concept of aliases, which means we are losing information in transmission.

@stevvooe is there a difference between

    1.1.1.1 one two

and

    1.1.1.1 one
    1.1.1.1 two

Both seem to do the same

2016-11-09 14:33 UTC, justincormack commented
Why does docker need to modify the hosts file in swarm mode? Can't we return it to the user to control and stop bind mounting it at all? Docker needs it for `--link` but it is very problematic, eg racy updates and so on. It is only because we provide it that we need a means to update it.

2016-11-09 19:48 UTC, stevvooe commented
@yongtang Do not change the CLI input. I am only advocating that the API adopt the model that represents the problem.

Again, the main problem with the docker API today is that we made it reflect too much of CLI behavior. While they should complement each other, it is more important that the API reflect a realistic data model. The CLI can then bolster that data model with sugar!

2016-11-10 01:59 UTC, yongtang commented on integration-cli/docker_cli_swarm_test.go
> +	d := s.AddDaemon(c, true, true)
Thanks @dnephin. The PR has been updated with this integration test removed. The code change is covered by unit tests now.

2016-11-10 02:02 UTC, yongtang commented
Thanks all for the review. The PR has been updated. The API related to swarmkit will take the suggested format of:
```
IP_address canonical_hostname [aliases...]
```

The cli will remain the same (`<host>:<ip>`). Please take a look and let me know if there are any issues.

2016-11-10 02:33 UTC, stevvooe commented
@yongtang Make sure this change is reflected in swarmkit API and services REST API.

2016-11-10 02:33 UTC, stevvooe commented on api/types/swarm/container.go
> +	//    IP_address canonical_hostname [aliases...]
👌

2016-11-10 02:35 UTC, stevvooe commented on daemon/cluster/executor/container/container.go
> +		parts := strings.Split(entry, " ")
This needs to use `strings.Fields` so it splits on arbitrary whitespace.

2016-11-10 02:45 UTC, stevvooe commented
LGTM after `strings.Fields` fix.

2016-11-10 03:05 UTC, yongtang commented
Thanks @stevvooe for the review. The PR has been updated.

2016-11-10 22:23 UTC, aluzzardi approved these changes

2016-11-10 23:37 UTC, tonistiigi commented
LGTM

2016-11-11 00:55 UTC, merged