Show peer nodes in network inspect for swarm overlay networks
moby/moby pull request #28078
Opened 2016-11-04 19:39 UTC by sanimej

swarm mode overlay networks reply on a functional gossip cluster across all nodes. If there is a firewall blocking the gossip ports or underlay network issue it can lead to inconsistent routing information across nodes leading to hard to debug connectivity issues. 

To improve the debug-ability this fix shows the peer nodes in the network inspect. In healthy state network inspect on all nodes should be consistent.

for ex: in a three node cluster, output from the lead manager..

```
vagrant@net-1:~$ docker network inspect ingress
[
    {
        "Name": "ingress",
....
....
        "Peers": [
            {
                "Name": "net-1-c1ce0cae5ec9",
                "IP": "192.168.33.11"
            },
            {
                "Name": "net-2-dfddfc3f9d91",
                "IP": "192.168.33.12"
            },
            {
                "Name": "net-3-3c4c1a195855",
                "IP": "192.168.33.13"
            }
        ]
    }
] 

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

2016-11-04 21:50 UTC, mavenugo reviewed
Just a minor comment. LGTM otherwise.

2016-11-04 21:50 UTC, mavenugo commented on api/server/router/network/network_routes.go
> +	peers := nw.Info().Peers()
why cant this be simply `info.Peers()` ? (just like other calls above)

2016-11-04 21:51 UTC, mavenugo commented on api/types/types.go
> +	Peers      []network.PeerInfo          // List of peer nodes for an overlay network
I think it is reasonable to add `json:",omitempty"` to this (since it make sense only for global-scoped networks.

2016-11-07 14:40 UTC, sanimej commented on api/server/router/network/network_routes.go
> +	peers := nw.Info().Peers()
yeah, there is no reason to not do that.. will change it.

2016-11-08 07:03 UTC, sanimej commented
@mavenugo Addressed the comments. PTAL.

2016-11-08 19:26 UTC, sanimej commented
@vieux @thaJeztah PTAL

2016-11-08 19:37 UTC, thaJeztah commented
Thanks! This looks useful. Wondering; how will this perform in a 1000 node swarm; should this be made optional?

2016-11-08 21:24 UTC, sanimej commented
@thaJeztah Things like dumping the routing, service discovery table per network should be under an option, for ex: `network inspect verbose`. We are planning to add it. But I think the peer info is more basic which belongs in the `network inspect` output. In bigger clusters it can be longer, same as other commands like `node ls`

2016-11-09 02:18 UTC, mavenugo commented
@sanimej yes. cluster peers in `network inspect` is decent. But for routing states, we would have to come up with another verbose flag.

LGTM.

@thaJeztah i will let you review the docs side of things.

2016-11-09 02:18 UTC, mavenugo commented
@sanimej btw, pls resolve the conflict.

2016-11-09 20:03 UTC, sanimej commented
@thaJeztah API changelog and CLI reference doc has been updated. PTAL

2016-11-09 20:10 UTC, thaJeztah requested changes
docs: some minor nitting, but otherwise looks good

2016-11-09 20:10 UTC, thaJeztah commented on docs/reference/commandline/network_inspect.md
> +peers. Peers are the nodes in the swarm cluster which has atleast one task attached
some minor typos (has -> have, atleast -> at least;
```Markdown
Peers are nodes in the swarm cluster which have at least one task attached 
```

2016-11-09 20:10 UTC, thaJeztah commented on docs/reference/commandline/network_inspect.md
> +to the network. Node name is of the format `hostname-unique ID`.
Perhaps use: `<hostname>-<unique ID>` (I read it as "hostname-unique" space "ID")

2016-11-09 20:10 UTC, thaJeztah commented on docs/reference/commandline/network_inspect.md
> +For swarm mode overlay networks `network inspect` also shows the IP and node name of
IP -> IP address

2016-11-09 21:21 UTC, sanimej commented
@thaJeztah Fixed the doc comments.

2016-11-09 22:17 UTC, thaJeztah approved these changes
docs LGTM

2016-11-09 23:32 UTC, mrjana commented
LGTM

2016-11-09 23:33 UTC, mrjana approved these changes

2016-11-09 23:33 UTC, merged