Modify to improve code readability
moby/moby pull request #28117
Opened 2016-11-07 08:19 UTC by ping035627

This PR modify codes to improve code readability.

2016-11-07 08:29 UTC, vdemeester commented
/cc @tiborvass

2016-11-07 08:32 UTC, AkihiroSuda commented
Please rebase

2016-11-07 08:36 UTC, ping035627 commented
I have rebased, and everything up-to-date.

2016-11-07 08:41 UTC, AkihiroSuda commented
![image](https://cloud.githubusercontent.com/assets/9248427/20051209/2e4f1cea-a511-11e6-80ae-242308a7c04b.png)

@ping035627 Please rebase again

2016-11-07 09:35 UTC, ping035627 commented
sorry, I just operate error, and I have rebased again, thanks.

2016-11-07 09:55 UTC, AkihiroSuda approved these changes
LGTM

2016-11-07 13:12 UTC, thaJeztah requested changes

2016-11-07 13:12 UTC, thaJeztah commented on cli/command/image/build.go
>  		err      error
These should align now with the other lines;

```go
	var (
		buildCtx      io.ReadCloser
		err           error
		contextDir    string
		tempDir       string
		relDockerfile string
		progBuff      io.Writer
		buildBuff     io.Writer
	)
```

2016-11-08 00:41 UTC, ping035627 commented
@thaJeztah ok, I have modified, thanks for reminding.

2016-11-08 00:42 UTC, tiborvass commented
LGTM

2016-11-08 00:42 UTC, tiborvass approved these changes

2016-11-08 00:43 UTC, thaJeztah approved these changes

2016-11-08 08:44 UTC, merged