vendor libnetwork @1861587
moby/moby pull request #28257
Opened 2016-11-10 20:30 UTC by sanimej

Fixes #14041 

With this change if  `ip_forward` is enabled by docker daemon then the iptables FORWARD policy will be set to DROP.  On a docker upgrade if `ip_forward` is already enabled this change will not take effect, because in that case the user might have intended to have the default policy ACCEPT. Changing it to DROP will break such setups. Current users of docker can avoid this issue by either
1) setting the FORWARD policy to DROP manually
2) reload the host before upgrading to 1.13. If docker daemon enabled `ip_forward` its not persistent. So after a reload the fix will take effect and the policy will be set to DROP.

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

2016-11-10 20:49 UTC, mavenugo approved these changes
LGTM

2016-11-10 21:31 UTC, vieux commented
LGTM

2016-11-10 22:01 UTC, merged

2017-01-21 07:48 UTC, AlmirKadric commented
this seems to have broken the following fix #490
whilst you could configure `--ip-forward` inside the daemon config file,
there is no way to manage this via the command line...

2017-01-26 12:36 UTC, 1ma commented
It appears this change of policy broke my use case (PHP debugging with XDebug, which involves opening TCP connections from the container back to the host).

How can I restore the old policy (short of pinning the 1.12.6 version on my development machine)?

2017-01-26 15:51 UTC, 1ma commented
Solved. Note that if you accidentally upgraded to 1.13 its not enough to downgrade back to 1.12, the iptables default policy has to be manually reverted.

2017-01-26 15:56 UTC, PavelPrischepa commented
@1ma what if I remove docker 1.13 and install 1.12, should I fix iptables policy manually?

2017-01-26 17:02 UTC, 1ma commented
Yes, that's what I had to do.

2019-09-02 08:30 UTC, bharathvishwanathan commented
Is Ip-forwarding required to run docker. If i disable ipforwarding will it impact any functionality of docker application.

2019-09-04 09:33 UTC, thaJeztah commented
@bharathvishwanathan please don't use old PR's (this pull request was merged three years ago) to start new discussions.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- [StackOverflow](https://stackoverflow.com/questions/tagged/docker)

2025-07-16 15:48 UTC, Ahmedmeshref280 requested changes
vendor/github.com/docker/libnetwork/iptables/iptables.go