Add support for extra_hosts in compose to swarm
moby/moby pull request #28299
Opened 2016-11-11 10:35 UTC by vdemeester

Adds support for `extra_hosts` in the composefile v3 format, used it `docker stack deploy --compose-file` 🐮.

/cc @dnephin @aanand @icecrime @stevvooe @aaronlehmann @aluzzardi 

This bumps [compose-file](https://github.com/aanand/compose-file) to 8cff34df885ef07824138236bc4d27d359888b17.

🐸

2016-11-11 13:19 UTC, thaJeztah requested changes

2016-11-11 13:19 UTC, thaJeztah commented on cli/command/stack/deploy.go
> +		hosts = append(hosts, fmt.Sprintf("%s:%s", host, ip))
Was discussing with @vdemeester, this is the wrong format :smile: https://github.com/docker/docker/pull/28031/files#diff-728a7fe135201867a6b4b645adc9553dR405

2016-11-11 13:21 UTC, thaJeztah approved these changes
LGTM

2016-11-11 14:07 UTC, cpuguy83 commented on cli/command/stack/deploy.go
> +		hosts = append(hosts, fmt.Sprintf("%s %s", host, ip))
Is this format correct?

2016-11-11 14:35 UTC, thaJeztah commented on cli/command/stack/deploy.go
> +		hosts = append(hosts, fmt.Sprintf("%s %s", host, ip))
I think it is, see https://github.com/docker/docker/pull/28031/files#diff-728a7fe135201867a6b4b645adc9553dR405

2016-11-11 15:49 UTC, cpuguy83 approved these changes
LGTM

2016-11-11 15:54 UTC, cpuguy83 commented
Experimental failure is most certainly unrelated. Merging.

2016-11-11 15:54 UTC, merged

2016-11-18 20:32 UTC, stevvooe commented on cli/command/stack/deploy.go
> +		hosts = append(hosts, fmt.Sprintf("%s %s", host, ip))
This looks backwards.