Bump API to v1.26
moby/moby pull request #28322
Opened 2016-11-11 20:12 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Think I got everything. I wasn't sure about the change to `runconfig\opts\parse.go`, so if someone could verify, would be greatly appreciated!

@tiborvass @vieux @thaJeztah

2016-11-11 21:15 UTC, tiborvass commented
Thanks @jhowardmsft. The SetAnnotations should stay at 1.25, it's the version starting from which the feature exists.

2016-11-12 01:42 UTC, jhowardmsft commented
@tiborvass Got it, thanks! Updated to revert those `SetAnnotations` updates.

2016-11-14 10:59 UTC, thaJeztah commented on cli/command/checkpoint/cmd.go
> +		Tags: map[string]string{"experimental": "", "version": "1.26"},
I think these determine the _minimum_ version that supports these commands, so should not be changed (same for the others below

2016-11-14 17:06 UTC, jhowardmsft commented on cli/command/checkpoint/cmd.go
> +		Tags: map[string]string{"experimental": "", "version": "1.26"},
@thaJeztah Updated. I was clearly way too over-zealous! What about the `NewVersionError` calls?

2016-11-14 18:01 UTC, thaJeztah requested changes
hmf, looks like my comments were still "pending" on GitHub

2016-11-14 22:25 UTC, jhowardmsft commented
@thaJeztah Yup, all your comments addressed in latest update.

2016-11-16 22:57 UTC, tiborvass commented
LGTM

2016-11-16 23:01 UTC, thaJeztah approved these changes
LGTM

2016-11-16 23:01 UTC, merged