#28331: docker stop should give a proper error on container in Create…
moby/moby pull request #28332
Opened 2016-11-12 07:00 UTC by dattatrayakumbhar04

fixes #28331 

- What I did
Implemented code for showing error message for docker stop if container in 'created' state

How I did it
Added method IsCreated() in container/state.go to get container in Created state.
Added changed in daemon/stop.go to show error message if isCreated() outout is true

how to verify it
1. Create a container with 'docker create'
2. stop container in #1.
  it should give an error that container <id> is not Running

2016-11-12 18:20 UTC, allencloud commented on daemon/stop.go
> +			return errNotRunning{container.ID}
Although codes here return an error, I think we still need to pay more attention on the status code docker daemon generated here.
While codes here you added seems to produce a status code of 500 which seems needing more discussion.

2016-11-12 18:25 UTC, allencloud commented on daemon/stop.go
>  		err := fmt.Errorf("Container %s is already stopped", name)
In addition, from my point of view, maybe our taking two steps is just enough:
1. change the error message from `Container %s is already stopped` to `Container %s is not running`;
2. make the status code of 304 and the message above received by client side.

@yongtang WDYT?

2016-11-13 18:43 UTC, yongtang commented on daemon/stop.go
>  		err := fmt.Errorf("Container %s is already stopped", name)
I remember 304 typically returns empty body (for HTTP caching purpose). Not sure the string of `Container %s is already stopped` or `Container %s is not running` is part of the HTTP response.

Maybe we should return an empty message (as 304 already indicates `StatusNotModified`)?

2016-11-15 04:08 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "docker_stop_in_create_state" git@github.com:dattatrayakumbhar04/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354593328
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-15 04:20 UTC, dattatrayakumbhar04 commented
@allencloud 
Updated PR . 
changed error message  and it returns http code status_not_modieifed(304)

	if !container.IsRunning() {
		err := fmt.Errorf("Container %s is not running", name)
  		return errors.NewErrorWithStatusCode(err, http.StatusNotModified)

2016-11-18 19:59 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "docker_stop_in_create_state" git@github.com:dattatrayakumbhar04/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354029336
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-24 05:26 UTC, dattatrayakumbhar04 commented on daemon/stop.go
>  		return errors.NewErrorWithStatusCode(err, http.StatusNotModified)
could you please give some pointer ? how can we achieve it ?

2016-12-01 20:38 UTC, tiborvass commented
LGTM

2016-12-05 05:32 UTC, allencloud commented on daemon/stop.go
>  		return errors.NewErrorWithStatusCode(err, http.StatusNotModified)
maybe we can just use `return errors.NewErrorWithStatusCode(nil, http.StatusNotModified)`

2016-12-05 05:34 UTC, allencloud commented
@tiborvass 
Since the status code is 304, the error will not be returned to client side. I think it is useless to reconstruct the error message.

2016-12-05 18:25 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "docker_stop_in_create_state" git@github.com:dattatrayakumbhar04/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354487480
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-05 18:37 UTC, cpuguy83 requested changes

2016-12-05 18:37 UTC, cpuguy83 commented on daemon/stop.go
> +		nil := fmt.Errorf("Container %s is not running", name)
What is going on here?

2016-12-06 02:57 UTC, allencloud commented on daemon/stop.go
> +		nil := fmt.Errorf("Container %s is not running", name)
Thanks @dattatrayakumbhar04 for your contribution. However I am afraid that this change is not what we want. Maybe the following is better:

original code:
```
		err := fmt.Errorf("Container %s is already stopped", name)
		return errors.NewErrorWithStatusCode(err, http.StatusNotModified)
```

We could change two lines into single one line:
```
return errors.NewErrorWithStatusCode(nil, http.StatusNotModified)
```

2016-12-07 02:48 UTC, allencloud commented
CI fails @dattatrayakumbhar04

2016-12-10 19:37 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "docker_stop_in_create_state" git@github.com:dattatrayakumbhar04/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354535064
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-11 00:07 UTC, dattatrayakumbhar04 commented
@allencloud ptal. 
Sorry for the delay.

2016-12-21 20:53 UTC, cpuguy83 requested changes

2016-12-21 20:53 UTC, cpuguy83 commented on api/errors/errors.go
> +		return apiError{errors.New(""), code}
This is even more weird.
What are we trying to accomplish?

2016-12-22 07:59 UTC, allencloud commented on api/errors/errors.go
> +		return apiError{errors.New(""), code}
I think for status code 3xx, we need to introduce another implementation.

2017-01-12 17:18 UTC, vdemeester commented
ping @dattatrayakumbhar could you take a look at @cpuguy83 comments and rebase too 🙇

2017-01-19 09:16 UTC, AkihiroSuda commented
ping @dattatrayakumbhar

2017-01-19 10:00 UTC, dattatrayakumbhar commented
Yes sure. Will take a look and will make a changes.

2017-01-27 20:31 UTC, LK4D4 commented
friendly ping @dattatrayakumbhar

2017-02-14 13:19 UTC, vdemeester commented
ok let me close that one as not really any activities.
@dattatrayakumbhar `300` code shouldn't be error so I think this implementation is not right (and is confusing). If you still want to fix this behavior, please re-open a PR (or ping me so that I can re-open this one) 👼 :pray:

2017-02-14 13:19 UTC, closed without merging