Change the docker-tag usage text to be clearer
moby/moby pull request #28354
Opened 2016-11-13 08:34 UTC by ripcurld00d

**- What I did**
Changed the tag command usage text to be clearer regarding the order of the images.

**- How I did it**
Changed the `Use` field at `cobra.Command` in cli/command/image/tag.go

**- How to verify it**
Run
```sheel
$ docker tag --help

Usage:  docker tag IMAGE[:TAG] REPOSITORY[:TAG]

Tag an image into a repository

Options:
      --help   Print usage
```

2016-11-13 10:53 UTC, glensc commented
this is not actually clearer. please extend the command description to describe which is the new tag being created.

2016-11-13 13:18 UTC, ripcurld00d commented
@glensc are you suggesting adding the following line below "Tag an image ...":
> For example, `docker tag httpd repo/httpd:v2` will tag the local image `httpd` into the `repo` repository with `v2`.

Thanks

2016-11-13 14:15 UTC, glensc commented
@ripcurld00d yes, add example. but your message assumes that tagging needs remote, i.e you're mixing tagging and pushing commands. the tagging is always "local".

> For example, `docker tag httpd repo/httpd:v2` will create tag named `httpd` referencing to `repo/httpd:v2`

perhaps add more examples, for example tagging with commit hash as well.

2016-11-14 08:32 UTC, ripcurld00d commented
I am afraid adding more examples will make it too much detailed.
I believe that if we are going to add an example, it has to be the most common use case.

2016-11-15 16:35 UTC, thaJeztah commented
/cc @aaronlehmann @stevvooe for suggestions on making this clearer

2016-11-15 17:57 UTC, aaronlehmann commented
Maybe we should take a cue from traditional unix utilities.

```
Usage: mv [-fin] SOURCE DEST
or: mv [-fin] SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY
```

In that vein, I'd suggest something like:

```
Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

Create a tag in the TARGET_IMAGE repository that refers to SOURCE_IMAGE.
```

2016-11-15 21:22 UTC, thaJeztah commented
Good suggestion!

Do we need additional clarification that "repository" is local here? (So tagging does nothing remote, only `push` does?) I can see there's some confusion about that; https://github.com/docker/docker/pull/28354#issuecomment-260188760

2016-11-15 22:00 UTC, glensc commented
is there need to use word `repository`? adds only confusion (what is repository?), it's image that is being tagged, so i propose:

```
Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE.
```

2016-11-17 08:34 UTC, ripcurld00d commented
@thaJeztah can you re-run the windowsRS1 job?
Thanks.

2016-11-17 11:04 UTC, thaJeztah approved these changes
~~LGTM~~

see https://github.com/docker/docker/pull/28354#issuecomment-261286568

2016-11-17 15:30 UTC, glensc commented
@ripcurld00d yes. looks good!

but can you include doc change in this PR as well? it also has that unhelpful `docker tag IMAGE[:TAG] IMAGE[:TAG]` as example.

https://docs.docker.com/engine/reference/commandline/tag/

2016-11-17 15:59 UTC, thaJeztah commented
> but can you include doc change in this PR as well?

oh! I was so focussed on the change, I missed that. Yes docs changes should be included, also the man-page;

- https://github.com/docker/docker/blob/master/docs/reference/commandline/tag.md
- https://github.com/docker/docker/blob/master/man/docker-tag.1.md

2016-11-17 18:44 UTC, ripcurld00d commented
@thaJeztah I thought we have a script that generates this...
n/m it should not be a problem :grinning:

2016-11-18 00:40 UTC, thaJeztah requested changes
> I thought we had a script that generates this...

Not yet for everything :smile:

Found some nits, can you address those? LGTM after that was addressed

2016-11-18 00:40 UTC, thaJeztah commented on man/docker-tag.1.md
> +entire image name including the optional `TAG` after the ':'.
Can you revert the unrelated white space changes?

2016-11-18 00:40 UTC, thaJeztah commented on man/docker-tag.1.md
> +entire image name including the optional `TAG` after the ':'.
(Also in the other places below)

2016-11-18 07:37 UTC, ripcurld00d commented on man/docker-tag.1.md
> +entire image name including the optional `TAG` after the ':'.
Yes, sure.

2016-11-18 11:12 UTC, ripcurld00d commented
@thaJeztah done :)
Thanks for your review.

2016-11-18 12:01 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-18 12:02 UTC, vdemeester approved these changes
LGTM 🐸

2016-11-18 12:02 UTC, merged