Handle `run --rm` against older daemons on the cli
moby/moby pull request #28445
Opened 2016-11-15 17:13 UTC by cpuguy83

For previous versions of Docker, `--rm` was handled client side, as such
there was no support in the daemon for it.
Now it is handled daemon side, but we still need to handle the case of a
newer client talking to an older daemon.

Falls back to client-side removal when the daemon does not support it.

Fixes #28439

2016-11-16 03:54 UTC, WeiZhang555 requested changes

2016-11-16 03:54 UTC, WeiZhang555 commented on cli/command/container/utils.go
> +			if waitRemove && versions.LessThan(dockerCli.Client().ClientVersion(), "1.25") {
I think this should be `dockerCli.Client().ServerVersion().Version`, it should detect daemon version but not the client version.

2016-11-16 06:39 UTC, WeiZhang555 requested changes

2016-11-16 06:39 UTC, WeiZhang555 commented on cli/command/container/utils.go
> +				}
Also, I think if `ContainerRemove` failed and `removeError != nil`, client will still hang. Should we send exitcode to statusChan to make client exit? I mean 
```
				if removeErr != nil {
					logrus.Errorf("error removing container: %v", removeErr)
+					statusChan <- exitCode
					return
				}
```

2016-11-17 03:13 UTC, cpuguy83 commented on cli/command/container/utils.go
> +			if waitRemove && versions.LessThan(dockerCli.Client().ClientVersion(), "1.25") {
No we want `ClientVersions()`, which is negotiated when the CLI is initialized.

2016-11-19 15:24 UTC, thaJeztah commented
ping @mlaventure @tonistiigi PTAL!

2016-11-19 15:24 UTC, thaJeztah commented on cli/command/container/utils.go
> +				}
@cpuguy83 ^^?

2016-11-19 16:13 UTC, cpuguy83 commented on cli/command/container/utils.go
> +				}
Hmm... If container remove fails, removeErr will not be nil, the eventCtx will be cancelled, and the select will hit `eventCtx.Done()` and return.

If container remove does not fail then processing keeps going as usual until it gets the remove event and returns.

2016-11-20 16:25 UTC, cpuguy83 commented on cli/command/container/utils.go
> +				}
I see. This is a little funky sense we're sending the exitCode in the even processor above in the everything is ok case.
Should probably be in a defer or something, WDYT?

2016-11-20 16:47 UTC, cpuguy83 commented on cli/command/container/utils.go
> +				}
Updated, PTAL.

2016-11-21 02:18 UTC, WeiZhang555 commented on cli/command/container/utils.go
> +				}
Looks good :+1:

2016-11-21 06:07 UTC, WeiZhang555 commented on cli/command/container/utils.go
> +			if waitRemove && versions.LessThan(dockerCli.Client().ClientVersion(), "1.25") {
You are right :smile:

2016-11-21 17:31 UTC, mlaventure approved these changes
LGTM with a little nt

2016-11-21 17:31 UTC, mlaventure commented on cli/command/container/utils.go
> +			if waitRemove && versions.LessThan(dockerCli.Client().ClientVersion(), "1.25") {
Nit: this could be an else clause

2016-11-21 18:59 UTC, tiborvass commented
LGTM

2016-11-21 21:51 UTC, vieux commented
LGTM after @mlaventure nit is addressed

2016-11-22 01:56 UTC, cpuguy83 commented
Updated.

2016-11-22 13:24 UTC, vdemeester approved these changes
LGTM :frog:

2016-11-22 13:25 UTC, merged