Split container runtime state from config
moby/moby pull request #28483
Opened 2016-11-16 16:14 UTC by cpuguy83

This is step-1 of implementing a lock-less container object.
This moves the live/runtime state off the container object onto a
separately managed object.

Effectively, these are items on the container struct that cannot (or
should not) be copied, e.g. i/o streams, signal channels, secrets, etc.

The new object is stored in a package level singleton that the container
object is able to get at. The objects are keyed by the container ID,
this means using the singleton should not cause any issues with other
uses (e.g. tests, dep injection, etc) as container ID's are unique.

Signed-off-by: Brian Goff <cpuguy83@gmail.com>

2016-11-16 16:18 UTC, LK4D4 commented
@cpuguy83 I'm not really a fan of singletons. What's problem with creating object on-demand?

2016-11-16 16:32 UTC, cpuguy83 commented
@lk4d4 I'm generally not a fan either, but I think it works out pretty well here, particularly because container ids must be unique.

I'm not sure where else to put this at the moment other than on ththe daemon, which seems worse to me.

2016-11-16 16:43 UTC, LK4D4 requested changes

2016-11-16 16:43 UTC, LK4D4 commented on container/monitor.go
> +	mu             sync.Mutex
let's follow "convention" and put `mu` on top of protected fields.

2016-11-16 16:43 UTC, LK4D4 commented on container/monitor.go
> +	delete(containerState.s, c.ID)
where cleanup of this state happens?

2016-11-16 16:43 UTC, LK4D4 commented on container/monitor.go
> +func addRunState(c *Container, s *runState) {
looks like `add` is not really used as `add`, more like `create`. Maybe remove `s` argument and allocate state here?

2016-11-16 17:48 UTC, LK4D4 commented on container/monitor.go
> +	delete(containerState.s, c.ID)
Yeah, I mean what stops logger and copier and other stuff. Where we make sure that we have no references to fields of state in goroutines.

2016-11-16 17:53 UTC, cpuguy83 commented
Test failure looks legit, taking a look.

2016-11-17 01:00 UTC, cpuguy83 commented
And all green.

2016-11-17 18:17 UTC, cpuguy83 commented
@LK4D4 Maybe I can putt his into container.Store somewhere.

2016-11-22 15:51 UTC, cpuguy83 commented
I think for now I'll just store it on container. This PR will introduce a nice split bewteen config and runtime, can take it further in another PR.

2016-12-06 13:36 UTC, cpuguy83 commented
Would be great to get more eyes on this.

2016-12-10 18:31 UTC, thaJeztah commented
ping @tonistiigi @crosbymichael could you have a look at this one?

2017-01-12 17:17 UTC, vdemeester commented
@cpuguy83 needs a rebase
@tonistiigi @crosbymichael @LK4D4 ptal 🙇

2017-01-12 19:50 UTC, tonistiigi commented
@cpuguy83 Could we have a design outline for "lockless container object" with the description of the steps/problems involved. There maybe general comments first and it would make reviewing the individual steps easier.

2017-01-17 22:32 UTC, cpuguy83 commented
@tonistiigi #30225

2017-01-18 20:42 UTC, estesp commented
@cpuguy83 and other maintainers: given the proposal is being discussed now in the GH issue, should we still be reviewing this code? I had offered to start reviewing, but if you think there might be a shift in direction based on the proposal discussion, I'll hold off.

2017-01-27 19:25 UTC, LK4D4 commented
This still depends on #30225

2017-02-09 19:42 UTC, thaJeztah commented
closing for now while we discuss on https://github.com/docker/docker/issues/30225

2017-02-09 19:42 UTC, closed without merging