Prepare docs and Swagger definition for automatically generated API docs
moby/moby pull request #28506
Opened 2016-11-16 21:42 UTC by bfirsh

**- What I did**

This is some preparation for automatically generating API documentation from a Swagger definition. See https://github.com/docker/docker/issues/22931. It is the Engine half of [this documentation pull request](https://github.com/docker/docker.github.io/pull/606). This pull request should be merged before the documentation pull request.

It consists of a bunch of things:

- Removed the API reference for the latest API version. This is now all in `api/swagger.yaml`, which the documentation is automatically generated from.
- Removed all the other API documentation from this repository. These barely ever change and are mostly not tied to any code change, so they should probably just live in docker/docker.github.io.
- Renamed "Remote API" to "Engine API". See https://github.com/docker/docker/issues/28319 for details.
- Update `api/swagger.yaml` with some more documentation and some recent API changes.

**- A picture of a cute animal (not mandatory but encouraged)**

![robot-cat](https://cloud.githubusercontent.com/assets/40906/20367010/8c6e2f6a-ac45-11e6-83dc-ac78a5e6e0b8.jpg)

2016-11-16 22:38 UTC, johndmulhausen commented
So excited about this, thanks @bfirsh. Slowly, we are killing all these hand-rolled markdown files and I couldn't be happier. To be getting such nice-looking API docs is just an added bonus!

cc @mstanleyjones

2016-11-17 16:18 UTC, thaJeztah commented
Is there an easy way to generate these docs for preview / reviewing pull requests?

2016-11-17 16:47 UTC, bfirsh commented
@thaJeztah I think the easiest way is to copy `swagger.yaml` into the right place in the documentation repo and run the documentation locally.

That could be documented somewhere I suppose. Perhaps a "API documentation" section in the contributing docs?

2016-11-17 17:07 UTC, dnephin reviewed
Some minor requests for changes to OperationID.

Thanks for adding all the missing endpoints.

LGTM

2016-11-17 17:07 UTC, dnephin commented on api/swagger.yaml
> +      operationId: "PluginsPush"
Could we make this `PluginPush` ? I've been normalizing everything to be singular.

2016-11-17 17:07 UTC, dnephin commented on api/swagger.yaml
> +      operationId: "ServicesLogs"
`ServiceLogs`

2016-11-17 17:07 UTC, dnephin commented on api/swagger.yaml
> +      operationId: "SecretsList"
`SecretList`

2016-11-17 17:07 UTC, dnephin commented on api/swagger.yaml
> +      operationId: "SecretsCreate"
`SecretCreate`

2016-11-18 13:58 UTC, bfirsh commented
If we want this included in 1.13, then these changes need cherry-picking to the 1.13 branch. I see no reason why not to include it – it's purely a documentation change.

Following an offline discussion with @thaJeztah, I'm also going to add some docs about how to write and test the API docs.

2016-11-18 14:20 UTC, thaJeztah commented
Adding to the milestone, but /cc @vieux

2016-11-18 18:45 UTC, bfirsh commented
@thaJeztah Documentation added! https://github.com/bfirsh/docker/blob/prepare-api-docs-for-swagger-docs/project/API.md

2016-11-18 18:51 UTC, mdlinville approved these changes
This is so cool!! Thank you so much, @bfirsh !

2016-11-22 14:13 UTC, thaJeztah approved these changes
LGTM

2016-11-22 16:21 UTC, mlaventure requested changes

2016-11-22 16:21 UTC, mlaventure commented on api/README.md
> +Copy `api/swagger.yaml` in this repository to `engine/api/v1.25/swagger.yaml` in the documentation repository, overwriting what is already there. Then, run `docker-compose up` in the documentation re
Replace `v1.25` with something like `<API_VERSION>` so we don't have to update this file every release? (we've already updated master to `v1.26`)

2016-11-22 16:46 UTC, bfirsh commented on api/README.md
> +Copy `api/swagger.yaml` in this repository to `engine/api/v1.25/swagger.yaml` in the documentation repository, overwriting what is already there. Then, run `docker-compose up` in the documentation re
Heh, good point. I'll just remove the version number actually, because `/engine/api/` redirects to `/engine/api/v1.25/`!

2016-11-22 16:47 UTC, bfirsh commented on api/README.md
> +Copy `api/swagger.yaml` in this repository to `engine/api/v1.25/swagger.yaml` in the documentation repository, overwriting what is already there. Then, run `docker-compose up` in the documentation re
@mlaventure Done!

2016-11-22 16:48 UTC, mlaventure approved these changes

2016-11-22 21:27 UTC, vieux commented
LGTM

2016-11-22 21:47 UTC, thaJeztah commented
There we go!

2016-11-22 21:47 UTC, merged

2016-11-23 00:37 UTC, vieux commented
@bfirsh can you create a PR against the 1.13.x branch directly ? this one is tricky to cherry-pick since it's 5 commits and the version changed in master

2016-11-23 00:53 UTC, vieux commented
@bfirsh nevermind I got it

2016-11-23 13:45 UTC, bfirsh commented
@vieux Nice, thank you! Appreciate that, because I realise it was non-trivial...

2016-11-30 00:30 UTC, vieux commented
@bfirsh https://github.com/docker/docker/blob/master/docs/api/version-history.md has 2 broken links, 1.25 and 1.26

2016-11-30 11:41 UTC, bfirsh commented
@vieux They will exist once https://github.com/docker/docker.github.io/pull/606 exists. :)

Well, 1.26 won't, but the `1.13` branch doesn't have that broken link.