Shutdown instead of terminate process on Windows
moby/moby pull request #28563
Opened 2016-11-18 00:10 UTC by darrenstahlmsft

**- What I did**

This is the first step for solving https://github.com/docker/docker/issues/25982. Platform changes are also needed.

**- How I did it**

Changed the behaviour of signaling a Windows container (docker stop) from terminating the init process to shutting down the container.

**- How to verify it**

Manual verification.

Signed-off-by: Darren Stahl <darst@microsoft.com>

2016-11-18 11:26 UTC, vdemeester commented
/cc @jhowardmsft @johnstep

2016-11-18 15:51 UTC, lowenna requested changes
Nit over comment. This is what I expected would need to be done. I'll talk offline about the platform change, but I guess that means it's an RS2 fix only.

2016-11-18 15:51 UTC, jhowardmsft commented on libcontainerd/client_windows.go
>  		// Terminate Process
Comment needs updating

2016-11-18 20:05 UTC, darrenstahlmsft commented
Updated to do an async shutdown rather than using the synchronous wrapper, since signal should not block for the container to exit.

2016-11-18 20:42 UTC, jhowardmsft commented
LGTM

2016-11-18 20:42 UTC, lowenna approved these changes

2016-11-18 20:49 UTC, johnstep approved these changes
LGTM

2016-11-19 17:22 UTC, vdemeester approved these changes
LGTM :frog:

2016-11-19 17:22 UTC, merged

2016-11-19 17:28 UTC, thaJeztah commented
@jhowardmsft wondering; for a future improvement should we use `STOPSIGNAL` to switch between these?

2016-11-19 18:11 UTC, jhowardmsft commented
Ah no, I don't think that makes sense.

2017-03-02 18:13 UTC, godefroi commented
@jhowardmsft Are the "platform changes" going to have to wait until fall 2017 for the release of RS3, or are we going to get a patch/hotfix sometime before that?

2017-03-02 19:26 UTC, jhowardmsft commented
The fix is still being worked on. I can't realistically comment on when it will be available, or whether it will be back-ported at this time.

2017-09-03 16:35 UTC, rgl commented
@darrenstahlmsft @jhowardmsft @johnstep can you comment on the related moby https://github.com/moby/moby/issues/25982 issue?