28600: Docs: network connect for container in Created/Stopped state
moby/moby pull request #28602
Opened 2016-11-18 20:48 UTC by dattatrayakumbhar04

fixes #28600 

Added document for network connect command for created , Stopped container

2016-11-18 20:48 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "nw-connect-paused-container-doc" git@github.com:dattatrayakumbhar04/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-23 19:24 UTC, mdlinville requested changes

2016-11-23 19:24 UTC, mstanleyjones commented on docs/reference/commandline/network_connect.md
> +A container that is connected to a network does not appear on the
I think this can be tightened a bit: A stopped container connects to its configured networks when it runs.

2016-11-23 19:42 UTC, dattatrayakumbhar04 commented on docs/reference/commandline/network_connect.md
> +A container that is connected to a network does not appear on the
You can pause, restart, and stop containers that are connected to a network.		 
A container connects to its configured networks when it runs.

Does it look good ?

2016-11-23 20:22 UTC, dattatrayakumbhar04 commented
@mstanleyjones @thaJeztah 
Updated PR with changes

2016-11-23 23:39 UTC, mdlinville approved these changes
LGTM, thanks!

2016-11-24 14:04 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-24 14:04 UTC, merged

2016-11-24 15:27 UTC, dattatrayakumbhar04 commented
thanks!!