Update deprecation notes about v1 registry
moby/moby pull request #28615
Opened 2016-11-19 01:12 UTC by dmcgowan

Adds section about the hub deprecating the v1 protocol. Adds note about intent to disable by default and remove support.

Change the wording `Though disabled by default`, to `Though enabled by default`, since the current default is disabled equal to false, or enabled. I found this confusing, but there might still be a better way to word it to make it clearer.

I choose 1.14 as disabled by default since we are already in freeze for 1.13 and making such a change seems unnecessary. We did add the flag in 1.9 but did not mention when the default will change, however I don't believe that means we need to wait 3 more releases to change the default if we are already waiting 3 to remove.

follow up to #28100

ping @nwt @dmp42

2016-11-19 14:57 UTC, thaJeztah requested changes
one nit, but LGTM otherwise

2016-11-19 14:57 UTC, thaJeztah commented on docs/deprecated.md
> +Support for the v1 protocol to the public registry was removed in 1.13. Any mirror configurations using v1 should be updated to use a [v2 registry mirror](https://docs.docker.com/registry/recipes/mir
Can you wrap this to 80 chars?

2016-11-19 14:57 UTC, thaJeztah commented on docs/deprecated.md
> +Support for the v1 protocol to the public registry was removed in 1.13. Any mirror configurations using v1 should be updated to use a [v2 registry mirror](https://docs.docker.com/registry/recipes/mir
Possibly the other paragraph as well, but that was already like that

2016-11-20 20:15 UTC, vdemeester approved these changes
LGTM :frog:

2016-11-21 18:09 UTC, dmcgowan commented
@thaJeztah formatting updated

2016-11-21 18:16 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-21 18:16 UTC, merged