Add bash completion for plugin API
moby/moby pull request #28625
Opened 2016-11-19 18:15 UTC by albers

Note for reviewers:
There was already a `__docker_complete_plugins` function that extracted network and volume drivers from `docker info` output. This information was used in completion for several things like volume and network creation and filtering.
Therefore I made the distinction between two kinds of plugins:
- bundled plugins come with Docker and that can be harvested by means of `docker info`:
```bash
docker info
[...]
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
[...]
```
* installed plugins that are managed by the new plugin API.

These concepts are reflected by the new function names `__docker_plugins_{bundled,installed}` and `__docker_complete_plugins_{bundled,installed}`

Please schedule for 1.13.0
Note: zsh already supports the new plugin commands.

2016-11-22 15:07 UTC, thaJeztah commented
ping @anusha-ragunathan @tiborvass ptal

2016-11-23 15:31 UTC, vdemeester requested changes

2016-11-23 15:31 UTC, vdemeester commented on contrib/completion/bash/docker
> +			COMPREPLY=( $( compgen -W "--help" -- "$cur" ) )
@albers Can you add `--timeout` too here ? see https://github.com/docker/docker/pull/28595

2016-11-23 16:10 UTC, albers commented on contrib/completion/bash/docker
> +			COMPREPLY=( $( compgen -W "--help" -- "$cur" ) )
@vdemeester done!

2016-11-23 16:12 UTC, albers commented on contrib/completion/bash/docker
> +			COMPREPLY=( $( compgen -W "--help" -- "$cur" ) )
ping @sdurrheimer for zsh completion: `docker plugin enable --timeout`

2016-11-23 16:49 UTC, vdemeester approved these changes
LGTM :tiger:

2016-11-27 12:46 UTC, albers commented
@mlaventure Would you mind reviewing this bash completion PR?

2016-11-28 16:56 UTC, mlaventure approved these changes
LGTM

One thing I noticed is that for `inspect` (and it applies for all similar commands, not just `plugin inspect`), the completion doesn't take in account already completed plugins (i.e. if plugin `abc` is already on the command line, the completion will propose it again and if it's the only one complete it again).

Just thought I'd point it out, since I managed to fill my command line with `tiborvass/no-remove` quickly before realizing it :)

2016-11-28 16:56 UTC, merged

2016-11-29 09:24 UTC, albers commented
> the completion doesn't take in account already completed plugins

Yes, that's true. Actually there is _no_ place in Docker's bash completion where arguments or options that were already given are removed from the completion.
This encourages users to fire commands that don't make sense.

But this behavior is quite common in bash completion, take a look at `git branch -d` or `git remote prune`, `grep --only-matching --only-matching`, `ls --all --all`.
I think this is mainly because bash completion does not give you access to some kind of AST. All you get is a list of words, the current and previous word. Combined with the limited language features of bash, especially if you are trying to support Mac OS (Bash 3.2 !!), remvoal of duplicates will bloat the completion scripts.

I will keep this in mind. Perhaps I can find a simple sometime, at least for the argument lists. This is nagging me as well.

2016-11-29 16:13 UTC, mlaventure commented
@albers thanks for the summary, actually never had paid attention to it until I tested this PR :angel: