Add `--input` flag for `docker secret create` command
moby/moby pull request #28629
Opened 2016-11-20 01:49 UTC by yongtang

**- What I did**

This fix tries to address the issue raised in #28581 where it was not possible to create a secret from a file (only through STDIN).

**- How I did it**

This fix add a flag `--input` to `docker secret create` so that it is possible to create a secret from a file with:
```
docker secret create --input secret.in secret.name
```

The flag `--input` is for the purpose of match `--input` in `docker load --input`

Related docs has been updated.

**- How to verify it**

An integration test has been added to cover the changes.

**- Description for the changelog**

Add `--input` flag for `docker secret create`.

**- A picture of a cute animal (not mandatory but encouraged)**

![cute-lion-cubs-animals-pictures-pics](https://cloud.githubusercontent.com/assets/6932348/20459716/7d392382-ae80-11e6-9d97-6f28196840b0.jpg)

This fix fixes #28581.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-11-20 15:16 UTC, vdemeester commented
/cc @thaJeztah @ehazlett

2016-11-20 16:24 UTC, thaJeztah commented
I think we should have;

- an `-` option on `docker create secret` (like we have on `docker build` to specify that we want to use `stdin` as input 
- have a `--file` flag

but @diogomonica for thoughts as well

2016-11-20 17:58 UTC, diogomonica commented
Given that I think it's trivial for people to do `cat file | docker secret create`, I don't think we need a file option, and having to specify --input is annoying, so I would say we don't change anything.

This said, I'm fine with whatever makes it more consistent with the rest of docker. 

My requirements are that you can do `openssl rand | docker secret create`

2016-11-21 12:42 UTC, thaJeztah commented
> Given that I think it's trivial for people to do `cat file | docker secret create`, I don't think we need a file option

Perhaps we should check if that's just as easy / common on Windows.

> This said, I'm fine with whatever makes it more consistent with the rest of docker.

I did a quick check on what we have right now. On `docker load`, we have an `--input` flag. For `docker import`, and `docker build`, the file is the first argument (so `-` has to be specified to load from `stdin`).

One improvement we _can_ make is to add better handling if no input is provided. It's confusing that when running `docker secret create`, it seems to "hang". For `docker load` we added a check, and it prints a message if no input was provided;

```bash
docker load
requested load from stdin, but stdin is empty
```

2016-11-21 13:46 UTC, cpuguy83 commented
Typically CLI tools that support input via stdin also have a `--file` (or whatever), so SGTM.

> Perhaps we should check if that's just as easy / common on Windows.
Don't see why it wouldn't work, IIRC shell pipes are supported on Powershell.
@jhowardmsft

2016-11-21 14:58 UTC, thaJeztah commented
Opened https://github.com/docker/docker/pull/28661 to improve  the feedback if no input was provided

2016-11-21 15:08 UTC, ehazlett commented
I'm also SGTM for `--file`.  @thaJeztah +1 for error on no feedback.

2016-12-01 14:10 UTC, yongtang commented
This issue is also related to #28927. From the comment (https://github.com/docker/docker/pull/28629#issuecomment-261963379) in this PR and in #28927, it seems that the consensus is to introduce a `--file [file|-]` flag to explicit specify the input.

I updated the PR to reflect the new changes. The PR description and title has been changed as well.

2016-12-01 14:20 UTC, yongtang commented
/cc @aaronlehmann @aluzzardi @diogomonica @cyli @tianon please take a look as well.

2016-12-01 15:03 UTC, ehazlett commented
LGTM (NAM)

2016-12-01 18:29 UTC, aaronlehmann commented on cli/command/secret/create.go
> +			return fmt.Errorf("Requested from STDIN ('-'), but STDIN is empty")
I think it should be okay to type in the secret on stdin. I don't know of any other unix tools that disallow this. And the error message doesn't seem right for this case.

2016-12-01 19:23 UTC, yongtang commented on cli/command/secret/create.go
> +			return fmt.Errorf("Requested from STDIN ('-'), but STDIN is empty")
Thanks @aaronlehmann. The PR has been updated with the restriction removed.

2016-12-01 19:27 UTC, aaronlehmann commented
LGTM

2016-12-01 19:37 UTC, diogomonica commented
LGTM

2016-12-01 19:46 UTC, aluzzardi commented
Does this also work with:

```
docker secret create name -f file
```

That is, having flags after the secret name?

2016-12-01 20:05 UTC, yongtang commented
Thanks @aluzzardi. Yes the `docker secret create name -f file` works as well. I updated the PR and added a test case to the integration test to cover it. Please take a look.

2016-12-09 17:18 UTC, ehazlett commented
@yongtang would you mind rebasing?  thx

2016-12-09 17:30 UTC, yongtang commented
Thanks @ehazlett. The PR has been rebased.

2016-12-09 17:31 UTC, ehazlett commented
thanks!

On Fri, Dec 9, 2016 at 5:31 PM, Yong Tang <notifications@github.com> wrote:

> Thanks @ehazlett <https://github.com/ehazlett>. The PR has been rebased.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/28629#issuecomment-266072171>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAP6Isy5aCMAlsLWJKoM-TbDpq4dJ8Dxks5rGZBdgaJpZM4K3bQu>
> .
>

2016-12-13 14:27 UTC, thaJeztah commented
@yongtang didn't this PR have a check if stdin is empty (like in https://github.com/docker/docker/pull/28661)? I seem to recall doing this;

```
docker secret create changes -f -
```

produced an error

otherwise LGTM

2016-12-13 14:40 UTC, yongtang commented
@thaJeztah There were some concerns about producing an error in that situation so the check was removed later (see https://github.com/docker/docker/pull/28629#discussion_r90507453)

2016-12-13 15:01 UTC, thaJeztah approved these changes
@yongtang a, I see, I overlooked that (just recalled testing this a while back). Given that it's now an explicit choice to use `stdin`, I think that's ok

LGTM

2016-12-13 15:06 UTC, vdemeester requested changes
Small comments, otherwise looks good

2016-12-13 15:06 UTC, vdemeester commented on cli/command/secret/create.go
> +		return fmt.Errorf("Please specify either a file name or STDIN ('-')  with --file")
nit, but there is one space too much between `('-')` and `with --file` :sweat_smile:

2016-12-13 15:06 UTC, vdemeester commented on integration-cli/docker_cli_secret_create_test.go
> +func (s *DockerSwarmSuite) TestSecretCreateWithFile(c *check.C) {
In the end there could be a unit test for that. But I guess there was no *cli integration test* on `docker secret create` so, I'm ok with that :angel:

2016-12-13 15:38 UTC, yongtang commented on cli/command/secret/create.go
> +		return fmt.Errorf("Please specify either a file name or STDIN ('-')  with --file")
Thanks @vdemeester. That is definitely not easy to spot this place 😅 . The PR has been updated, please take a look.

2016-12-13 15:44 UTC, vdemeester approved these changes
LGTM 🐻

2016-12-13 18:03 UTC, aaronlehmann commented
> > didn't this PR have a check if stdin is empty (like in #28661)?

> There were some concerns about producing an error in that situation so the check was removed later (see https://github.com/docker/docker/pull/28629#discussion_r90507453)

I might be confused, but the comment you linked to seems to be attached to this (removed) code:

```go
	if options.file == "-" {
		// To avoid getting stuck, verify that a file is given in STDIN
		if dockerCli.In().IsTerminal() {
			return fmt.Errorf("Requested from STDIN ('-'), but STDIN is empty")
```

I don't see that checking that stdin is empty, which is why I commented on it ("...And the error message doesn't seem right for this case."). I might be missing some context, though. I would be fine with having a check, but this would have to happen after the data is read, because otherwise how can you know if you receive no data on stdin?

Anyway, there's a check on the swarmkit side, so it doesn't really matter if we check this on the client side.

2016-12-13 18:20 UTC, thaJeztah commented
@aaronlehmann the error was shown if I tried to create a secret from stdin, but didn't provide any content. Right now, the CLI blocks until content is provided. Now that selecting `stdin` is an explicit action (i.e., I need to set `-f -`), I don't think that's a problem (from a UX perspective)

2016-12-13 18:30 UTC, aaronlehmann commented
Agreed. The only thing we might consider adding is an error message if you hit `^D` without typing anything. But as I mentioned, such an error should be sent back from the daemon anyway (mind giving it a try?).

2016-12-13 22:42 UTC, thaJeztah commented
@aaronlehmann Detaching without typing does produce an error, so that looks ok (error presentation could be nicer, but that's for other errors as well);

```
docker secret create foo -f -
^D
Error response from daemon: rpc error: code = 3 desc = secret data must be larger than 0 and less than 512000 bytes
```

2016-12-18 02:04 UTC, merged