allow replacing httpredir mirror for arm
moby/moby pull request #28640
Opened 2016-11-20 22:55 UTC by andrewhsu

**- What I did**

Allow replacing of `httpredir.debian.org` in `/etc/apt/sources.lists` with a user-specified mirror hostname for building the `docker-dev` image on arm.

**- How I did it**

With a docker `--build-arg` arg that will `sed` the hostname, same way [Dockerfile](https://github.com/docker/docker/blob/7d1a72a2866aedbc7492a0cfc5cd4e13646322fe/Dockerfile#L34-L36) does it.

**- How to verify it**

```
$ make DOCKER_BUILD_ARGS=--build-arg=APT_MIRROR=ftp.us.debian.org build
...
docker build  --build-arg=APT_MIRROR=ftp.fr.debian.org -t "docker-dev:apt-mirror-arm" -f "Dockerfile.armhf" .
Sending build context to Docker daemon 159.8 MB
Step 1 : FROM armhf/debian:jessie
 ---> 3ea48732e06c
Step 2 : ARG APT_MIRROR=httpredir.debian.org
 ---> Using cache
 ---> 2ca315200bd0
Step 3 : RUN sed -i s/httpredir.debian.org/$APT_MIRROR/g /etc/apt/sources.list
 ---> Using cache
 ---> fc188f8a4ad0
Step 4 : RUN apt-get update && apt-get install -y       apparmor        aufs-tools      automake        bash-completion         btrfs-tools      build-essential         createrepo      curl    cmake   dpkg-sig        git     iptables        jq      net-tools       libapparmor-dev  libcap-dev      libltdl-dev     libsqlite3-dev  libsystemd-journal-dev  libtool         mercurial       pkg-config      python-dev       python-mock     python-pip      python-websocket        xfsprogs        tar     vim-common      --no-install-recommends         && pip install awscli==1.10.15
 ---> Running in 594ab4f79868
Ign http://ftp.fr.debian.org jessie InRelease
Get:1 http://ftp.fr.debian.org jessie-updates InRelease [145 kB]
Get:2 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:3 http://ftp.fr.debian.org jessie Release.gpg [2373 B]
Get:4 http://ftp.fr.debian.org jessie Release [148 kB]
Get:5 http://ftp.fr.debian.org jessie-updates/main armhf Packages [17.5 kB]
Get:6 http://security.debian.org jessie/updates/main armhf Packages [396 kB]
Get:7 http://ftp.fr.debian.org jessie/main armhf Packages [8864 kB]
Fetched 9636 kB in 11s (834 kB/s)
...
```

**- Description for the changelog**

* apt repo mirror override for building development image

**- A picture of a cute animal (not mandatory but encouraged)**

🐝

2016-11-20 22:55 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "apt-mirror-arm" git@github.com:andrewhsu/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-11-20 22:55 UTC, andrewhsu commented
/cc @mikedougherty

2016-11-21 11:38 UTC, vdemeester approved these changes
LGTM :frog: 
But we wight want to do that for all `Dockerfile` that are based on debian/ubuntu (like `Dockerfile.aarch64`) ?

2016-11-21 13:38 UTC, cpuguy83 commented
ping @tianon 

I believe the x86 debian has already switched to deb.debian.org instead of httpredir, which if/when that happens for this image will make this not work anymore.

2016-11-21 16:16 UTC, thaJeztah requested changes

2016-11-21 16:16 UTC, thaJeztah commented on Dockerfile.armhf
> +RUN sed -i s/httpredir.debian.org/$APT_MIRROR/g /etc/apt/sources.list
@andrewhsu how about using the same here as https://github.com/docker/docker/blob/75091abe76531d4373aba2da680b695e5dbb8fc8/contrib/builder/deb/amd64/debian-jessie/Dockerfile#L7-L9 ?

2016-11-21 21:21 UTC, andrewhsu commented on Dockerfile.armhf
> +RUN sed -i s/httpredir.debian.org/$APT_MIRROR/g /etc/apt/sources.list
Yes, i can do that.

I've confirmed there is armhf for jessie on `deb.debian.org`
https://deb.debian.org/debian/dists/jessie/main/

2016-11-21 21:36 UTC, andrewhsu commented
I've updated the Dockerfiles that are FROM jessie to have the mirror override.

2016-11-21 22:07 UTC, vieux commented
SGTM

2016-11-21 22:33 UTC, thaJeztah approved these changes
LGTM

2016-11-21 23:54 UTC, merged