Parse labels using templates in the json-log driver
moby/moby pull request #28669
Opened 2016-11-21 19:02 UTC by ripcurld00d

**- What I did**
Parse json-log label if it has a template (f.e. {{.Name}}) in its value.

closes #19803

TODO: add unit tests and describe this in the documents.

**- How I did it**
* Created ParseLabels to daemon/logger/context
* Separated the part that creates a new template to a new function and use it in ParseLabels.
* Called ParseLabels in jsonfilelog's New

**- How to verify it**
* docker daemon -D --log-opt labels="com.photobox.full"
* docker run --label="com.photobox.full={{.ImageName}}/{{.Name}}/{{.ID}}" -it ubuntu bash -c "echo ${RANDOM}"
* docker inspect <container-id> | grep com.photobox.full
* Make sure you get `"com.photobox.full": "<image-name>/<container-name>/<container-id>"`
* cat /var/lib/docker/containers/<container-id>/*.log
* Make sure you find `{"log":"15970\r\n","stream":"stdout","attrs":{"com.photobox.full":"<image-name>/<container-name>l/<container-id>"},"time":"2016-11-21T18:44:39.172491031Z"}`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-11-22 00:29 UTC, AkihiroSuda requested changes

2016-11-22 00:29 UTC, AkihiroSuda commented on daemon/logger/context.go
> +			if v, ok := ctx.ContainerLabels[l]; ok && strings.Contains(v, "{{.") {
`strings.Contains(v, "{{.")` is not robust: https://golang.org/pkg/text/template/

Why not just execute the template?

2016-11-22 06:43 UTC, ripcurld00d commented on daemon/logger/context.go
> +			if v, ok := ctx.ContainerLabels[l]; ok && strings.Contains(v, "{{.") {
I thought it would be a waste to execute the template regardless to the value.
I will change that, though.

2016-11-22 09:33 UTC, ripcurld00d commented
My bad, I thought they wanted to parse the labels while what they really wanted is to add `tag` (with parsing capabilities) to the JSON-file logger.
I will fix this...

2016-11-22 11:55 UTC, ripcurld00d commented
OK, after re-reading #19803 (Feature: log-driver json-file with log-opt tag and contextual parsing of labels/envs) I am going to:

* Change this PR to pre-factoring daemon/logger/loggerutils for this feature
* Create another PR that will do contextual parsing on the JSON file driver labels and env
* Create another PR that will support `log-opt tag` in JSON file driver.

The reason for that is to make the code review much easier. I didn't think it will be that big, though.

Does that make sense?

/cc @thaJeztah @AkihiroSuda @ajohnstone

2016-11-22 22:45 UTC, ripcurld00d commented
@AkihiroSuda can you review this. Please note that this PR was changed to add `--log-opt tag` to the JSON file log driver unlike before where it parsed the labels.

Thanks.

2016-12-21 20:34 UTC, cpuguy83 commented
SGTM

2016-12-21 20:47 UTC, AkihiroSuda commented
SGTM, please add docs?

2016-12-22 07:08 UTC, ripcurld commented
@AkihiroSuda - Yes sure. Thanks.

2016-12-25 11:02 UTC, ripcurld commented
Hi @AkihiroSuda

It seems like the documentations regarding the logging options are in https://github.com/docker/docker.github.io so I am going to update the docs there.
Is that good enough?

Thanks

2016-12-25 11:22 UTC, AkihiroSuda commented
I think it is ok

2016-12-25 11:22 UTC, AkihiroSuda approved these changes
LGTM

2016-12-31 20:22 UTC, ripcurld0 commented
Rebased :relaxed:

2017-01-02 16:24 UTC, thaJeztah commented
Hm, ok, trying to see how to actually _use_ this;

- `docker logs` only shows the actual `log:` data (and optionally `timestamp:`)
- fetching logs from the _api_ also gives me just the logged lines
- the only way to see the tags is any directly accessing the container-log files inside `/var/lib/docker/<container-id>`, which is _not_ something that's really supported

Given that the API does not return raw `JSON` entries from the log files; is there actually a way to use this?

2017-01-02 17:17 UTC, ripcurld0 commented
@thaJeztah,
@addykim and @ajohnstone are using filebeat/logstash-forwarder to ship /var/lib/docker/\<container-id\>/*json.log to ELK.

BTW, why not allowing to optionally show the tag in `docker logs` too?

2017-01-04 09:49 UTC, ripcurld0 commented
@thaJeztah I have no idea why DockerSuite.TestAPIStatsNetworkStats keeps failing.
This test is irrelevant to my change. Am I wrong? :confused:

2017-01-04 10:23 UTC, justincormack commented
That is not a supported API.

On 2 Jan 2017 17:17, "bshuster" <notifications@github.com> wrote:

> @thaJeztah <https://github.com/thaJeztah>,
> @addykim <https://github.com/addykim> and @ajohnstone
> <https://github.com/ajohnstone> are using filebeat/logstash-forwarder to
> ship /var/lib/docker/<container-id>/*json.log to ELK.
>
> BTW, why not allowing to optionally show the tag in docker logs too?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/28669#issuecomment-269998461>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAdcPJ8Q8RExS54TnyRpQi651g-VT21Jks5rOTETgaJpZM4K4kiI>
> .
>

2017-01-04 14:19 UTC, cpuguy83 commented
The API is not great, but we do support reading the extra attributes with `--details`

2017-01-10 06:44 UTC, ripcurld0 commented
@cpuguy83 @thaJeztah 
Unfortunately tag isn't in the extra attributes so running `--details` won't do much.
I think there must be a way to concatenate the tag to the log line using `--details`.
Does it make sense?

2017-01-10 18:11 UTC, thaJeztah commented
Yes, I think if we implement this, there should be a way to consume it with `docker logs`. Not sure in what form, but `--details` seems likely

2017-01-10 18:46 UTC, ripcurld0 commented
@thaJeztah @cpuguy83 should I do this in this commit, in a new commit or in a new PR?

2017-01-10 20:44 UTC, stevvooe commented
What exactly is `tag` in this context?

There are ways to access this already with labels. I don't remember the incantation off the top of my head, but this PR seems redundant.

2017-01-10 22:15 UTC, ripcurld0 commented
@stevvooe people want to ship json-file logs using logstash-forwarder/filebeats.
The reason they use json-file rather than fluentd/gelf is because they can run `docker logs`.

2017-01-10 22:22 UTC, stevvooe commented
@ripcurld0 That doesn't answer my question: what is the tag?

2017-01-10 22:43 UTC, ripcurld0 commented
From https://github.com/docker/docker/issues/19803#issuecomment-176456217 and https://github.com/docker/docker/issues/19803#issuecomment-176305523 it is used to filter logs from specific container or to determine what image does the container use.

2017-01-10 22:59 UTC, stevvooe commented
@ripcurld0 Do you mean the image name?

Please be clear in what you want. Adding this kind of thing takes consideration. If you take the time to make it clear what this is actually solving, we may be able to show you an already existing solution.

2017-01-10 23:03 UTC, ripcurld0 commented
@stevvooe I think https://github.com/docker/docker/issues/19803 explains better what this PR attempts to solve.

2017-01-11 00:15 UTC, stevvooe commented
@ripcurld0 That is a bug report. Please restate the problem and the proposed solution.

I don't want to have to dig through a million comments to figure out what you're trying to do.

2017-01-11 07:57 UTC, ripcurld0 commented
Odd, it seems to me that #19803 (Feature: log-driver json-file with log-opt tag and contextual parsing of labels/envs) is an enhancement to json-file.

To be honest, @stevvooe as you can tell, I can't restate the problem because I didn't open the issue. I just volunteered to resolve it.

I am going to close this PR unless @ajohnstone, @addykim, @youngpm, @jessesuen, @yeruisen will come up and give more details what were their problems and why `tag` is the way to do solve these.

Thanks.

2017-01-11 07:57 UTC, closed without merging

2017-01-12 22:30 UTC, stevvooe commented
@ripcurld0 I am not sure how you can solve the problem if you can't restate it.

I would think we would need to answer the following questions before going forward:

Is the proposal to add the image name to every log message?
Why would this be called "tag"? Do you mean "image"?
What data do we already propagate into logs? Won't there be redundant cost to this?

Let's try to solve problems without creating bigger ones.

2017-01-12 23:35 UTC, cpuguy83 commented
@stevvooe I think `tag` is referring to log tags which is supported by some of the other log drivers allows using a template to add more context (specific details about the container, encapsulated by the `LogInfo` struct) to each log message.