Add support for armhf ubuntu-xenial deb
moby/moby pull request #28672
Opened 2016-11-21 19:48 UTC by mlaventure

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

-- 

Stiking to LTS for ubuntu on arm

/cc @andrewhsu @vieux

2016-11-21 20:08 UTC, tonistiigi commented
LGTM

2016-11-21 20:08 UTC, mlaventure commented
I will add support for yakkety later today.

2016-11-21 20:37 UTC, thaJeztah commented
@mlaventure do you have time to copy the `generate.sh` script and update it for armhf?

2016-11-21 21:26 UTC, mlaventure commented
@thaJeztah done, checking to see if the added `seccomp` flag breaks the build though

2016-11-21 21:40 UTC, andrewhsu requested changes

2016-11-21 21:40 UTC, andrewhsu commented on contrib/builder/deb/armhf/debian-jessie/Dockerfile
> +FROM debian:jessie
I don't think this will work when this is run on an arm machine. Gotta have `armhf/debian:jessie`

2016-11-21 21:51 UTC, thaJeztah commented on contrib/builder/deb/armhf/debian-jessie/Dockerfile
> +FROM debian:jessie
Yup, need to add `armhf/` as prefix in the script

2016-11-21 21:52 UTC, thaJeztah commented on contrib/builder/deb/armhf/raspbian-jessie/Dockerfile
> +FROM raspbian:jessie
This one needs an exception as well (alternatively, skip `raspbian` in the script if it's too much different)

2016-11-21 22:58 UTC, mlaventure commented
Updated, tested on xenial

2016-11-21 23:45 UTC, thaJeztah commented on contrib/builder/deb/armhf/raspbian-jessie/Dockerfile
> -ENV GOARM 6
Do we need to keep this? https://github.com/golang/go/wiki/GoArm

2016-11-21 23:46 UTC, thaJeztah commented on contrib/builder/deb/armhf/raspbian-jessie/Dockerfile
> +ENV DOCKER_BUILDTAGS apparmor pkcs11 selinux
Not sure if the `pkcs11` package builds on ARM?

2016-11-22 10:48 UTC, thaJeztah commented
This needs a rebase, because https://github.com/docker/docker/pull/27628 was merged

2016-11-22 12:08 UTC, justincormack commented on contrib/builder/deb/armhf/raspbian-jessie/Dockerfile
> +ENV DOCKER_BUILDTAGS apparmor pkcs11 selinux
it should do, we use it in the main arm Dockerfile which is also based on jessie.

2016-11-22 15:15 UTC, mlaventure commented
Updated, building them all on a C1 server to check, it's going to take a while :sweat_smile:

2016-11-22 18:24 UTC, mlaventure commented
They all built successfully :tada: :green_heart:

2016-11-22 18:54 UTC, thaJeztah approved these changes
LGTM

2016-11-22 18:56 UTC, justincormack approved these changes

2016-11-22 18:57 UTC, merged