Optimize the function 'Context.Name()' and replace 'Context.Container…
moby/moby pull request #28759
Opened 2016-11-23 14:45 UTC by miaoyq

Optimize the function 'Context.Name()' and replace 'Context.Container Name' that need to remove slash with 'Context.Name()'.

Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>

2016-11-23 15:36 UTC, thaJeztah requested changes

2016-11-23 15:36 UTC, thaJeztah commented on daemon/logger/context.go
> +	return ctx.ContainerName
Perhaps better to use `TrimPrefix`, which does exactly the same; https://golang.org/src/strings/strings.go?s=16615:16655#L605

```go
return strings.TrimPrefix(ctx.ContainerName, "/")
```

2016-11-23 15:37 UTC, thaJeztah commented on daemon/logger/context.go
> +	return ctx.ContainerName
Just to be sure; the name is never used without stripping the `/`?

2016-11-24 00:59 UTC, miaoyq commented
Thanks @thaJeztah 
I have updated.

2016-11-24 10:26 UTC, vdemeester approved these changes
LGTM 🐮

2016-11-25 09:33 UTC, justincormack approved these changes

2016-11-25 09:34 UTC, justincormack commented
Unrelated, but `Context` is a terrible name, maybe it could be renamed (in another PR) eg to something like loginfo or something.

2016-11-25 12:24 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-11-25 12:25 UTC, thaJeztah commented
> Unrelated, but Context is a terrible name, maybe it could be renamed (in another PR) eg to something like loginfo or something.

Agreed 👍

2016-11-25 12:25 UTC, merged

2016-11-26 01:50 UTC, miaoyq commented
Thanks for reveiw, I will open  a new PR to rename `context`. @justincormack  @thaJeztah