Fix race with containerd events stream on restore
moby/moby pull request #28782
Opened 2016-11-23 23:06 UTC by mlaventure

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--

Closes #28687

/cc @tonistiigi

2016-11-28 19:09 UTC, tonistiigi commented on libcontainerd/client_linux.go
> +		} else if ev.Pid != InitFriendlyName || ev.Type != StateExit {
Shouldn't this check be in `getContainerLastEventSinceTime`? Also, what is the difference in having no last event(line 457) and having last event that is not exit. Shouldn't we wait in both cases if containerd already knows the container is gone.

2016-11-28 20:26 UTC, tonistiigi commented on libcontainerd/client_linux.go
> +		} else if ev.Pid != InitFriendlyName || ev.Type != StateExit {
How can `getContainer` return nil. I see `appendContainer` only in start/restore paths.

2016-11-28 21:42 UTC, mlaventure commented on libcontainerd/client_linux.go
> +		} else if ev.Pid != InitFriendlyName || ev.Type != StateExit {
duh! 

Well, that leave only the case where the event logs was rotated then, and the call to `getContainer` becomes useless.

2016-11-29 18:41 UTC, mlaventure commented
@tonistiigi updated

2016-11-29 21:24 UTC, LK4D4 requested changes

2016-11-29 21:24 UTC, LK4D4 commented on libcontainerd/client_linux.go
> +			stop := false
not a fan of such pattern, create helper and return from select if you don't like `break LABEL`

2016-11-29 21:24 UTC, LK4D4 commented on libcontainerd/client_linux.go
> +			timeout := time.After(10 * time.Second)
This will leak timer. Better use `time.NewTimer` and Stop it.

2016-11-29 21:24 UTC, LK4D4 commented on libcontainerd/client_linux.go
> +						time.Sleep(100 * time.Millisecond)
I'd better try to use Ticker. Don't like sleeps :)

2016-11-30 16:04 UTC, mlaventure commented on libcontainerd/client_linux.go
> +			stop := false
I had forgotten that `break LABEL` was skipping the for!

2016-11-30 17:13 UTC, LK4D4 commented on libcontainerd/client_linux.go
> +				default:
You just called `getContainerLastEvent`, so you'll call it twice in a row. Replace `default` with `case <-tick.C`

2016-11-30 18:11 UTC, mlaventure commented on libcontainerd/client_linux.go
> +				default:
done

2016-11-30 18:12 UTC, LK4D4 commented on libcontainerd/client_linux.go
> +				default:
not really, just replace default with case <-tick.C :)

2016-11-30 18:15 UTC, mlaventure commented on libcontainerd/client_linux.go
> +				default:
haha, sure :)

2016-11-30 18:37 UTC, LK4D4 approved these changes

2016-11-30 18:37 UTC, LK4D4 commented
LGTM

2016-11-30 18:39 UTC, tonistiigi commented
LGTM

2016-11-30 21:26 UTC, merged