Abrupt shutdown left stale directory in /run and /var/run in OL6
moby/moby pull request #28810
Opened 2016-11-24 18:08 UTC by thtanaka

In a sysvinit base system, /var/run and /run is not a tmpfs, as such
during an abrupt shutdown, the stale directory from the containerd will
prevent docker daemon to start properly.

Signed-off-by: Thomas Tanaka <thomas.tanaka@oracle.com>

2016-11-24 21:28 UTC, thaJeztah commented
Thanks! Should we also update this in the debian version? https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker

ping @tianon @andrewhsu @ijc25

2016-11-25 09:35 UTC, ijc25 commented
Looking at a Debian testing/unstable hybrid system of mine running sysvinit I have:
```
~$ df -h /run /var/run
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           199M  1.3M  198M   1% /run
tmpfs           199M  1.3M  198M   1% /run
```
On that system `/etc/default/tmpfs` says:
```
# /run is always mounted as a tmpfs on systems which support tmpfs
# mounts.
```
and `/var/run` is a symlink to `/run`.

Looking at a different system running Debian Jessie and sysvinit (this is an armel system, shouldn't matter though) I see:
```
$ df -h /run /var/run
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            51M  336K   50M   1% /run
tmpfs            51M  336K   50M   1% /run
```
and the same comments in `/etc/default/tmpfs` and the same symlink.

So I think this change is not required for Debian, at least as far as my systems go (the Jessie one in particular has not been majorly futzed with as far as I remember).

I think OL6 has inherited this behaviour from RH6, at least [this](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/sect-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-File_System_Layout.html#idp5814848) says so by implication. So this PR ought to be correct for RH6 systems too.

The FHS does say `/run` should be a tmpfs these days, so it seems fair to rely on that for modern distros and confine the workarounds to older ones until they are phased out.

2016-11-25 10:25 UTC, ijc25 commented
FYI I also found a Wheezy (oldstable, which ran sysvinit by default) and it has tmpfs everywhere too

2016-11-25 12:55 UTC, thaJeztah requested changes
Thanks for checking @ijc25! SGTM then; I'll leave the code review to @tianon (perhaps @albers wants to look as well)

2016-11-25 12:55 UTC, thaJeztah commented on contrib/init/sysvinit-redhat/docker
> +	done
Looks like there's some mixed tabs/spaces here, and they make @tianon cry 😢 :wink:

<img width="488" alt="screen shot 2016-11-25 at 13 53 34" src="https://cloud.githubusercontent.com/assets/1804568/20625979/ba3924ae-b316-11e6-9f98-6d5728869741.png">

2016-11-25 18:16 UTC, thtanaka commented
Thanks for the review, not sure if it is correct to force push edited commit, if not then please feel free to let me know and any suggestions that I should be aware of. TIA!

2017-01-12 17:01 UTC, vdemeester commented
ping @tianon 🙇

2017-01-27 17:02 UTC, LK4D4 commented
ping @tianon for review

2017-03-09 21:44 UTC, dnephin commented
@thtanaka Thanks for the contribution!

Unfortunately it seems there isn't any interest in this change to contrib from maintainers. If we don't have anyone to review these changes, it might be prudent to remove it entirely.

2017-03-09 21:44 UTC, closed without merging