Modify repoName to PLUGIN for docker plugin create
moby/moby pull request #28822
Opened 2016-11-25 05:13 UTC by yuexiao-wang

**- What I did**
1. Modify repoName to PLUGIN in docker plugin create
2. Fix the difference between code and document  for docker plugin create

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

2016-11-25 05:21 UTC, AkihiroSuda commented
Please clarify the reason for this PR? 
e.g. consistency
(If consistency is your reason, probably you may want to modify push.go as well: https://github.com/yuexiao-wang/docker/blob/1e2f1f816e0e83b258de5e156011daa72fff0cc5/cli/command/plugin/push.go#L17)

PTAL @tiborvass @anusha-ragunathan

2016-11-25 05:22 UTC, AkihiroSuda requested changes

2016-11-25 05:22 UTC, AkihiroSuda commented on cli/command/plugin/create.go
> +
Please remove this extra line

2016-11-25 07:31 UTC, yuexiao-wang commented
@AkihiroSuda  PTAL
Thanks

2016-11-25 07:35 UTC, yuexiao-wang commented
@AkihiroSuda PTAL
Done!

2016-11-25 07:43 UTC, AkihiroSuda approved these changes
LGTM

2016-11-25 08:50 UTC, vdemeester approved these changes
LGTM 🐸

2016-11-28 16:50 UTC, anusha-ragunathan commented
LGTM

2016-11-28 16:52 UTC, merged