add a test for ensuring the behavior of read-only /dev/shm
moby/moby pull request #28823
Opened 2016-11-25 06:09 UTC by AkihiroSuda

**- What I did**

Added a test for ensuring the behavior mentioned in https://github.com/docker/docker/issues/28639#issuecomment-261905176

> The current way to specify a ro (ie non functional) /dev/shm mount is:
> docker run --read-only --mount type=tmpfs,target=/dev/shm,readonly=true ...

**- How I did it**

Added a test

**- How to verify it**

Observe the CI result

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
https://www.youtube.com/watch?v=8ij9VVd6Dp8

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2016-11-25 06:10 UTC, AkihiroSuda commented
cc @diogomonica @justincormack @cpuguy83 @stevvooe

2016-11-25 10:46 UTC, justincormack approved these changes

2016-11-25 10:59 UTC, AkihiroSuda commented
Closing this moment,  in favor of removing --mount

https://github.com/docker/docker/issues/28527

2016-11-25 12:58 UTC, AkihiroSuda commented
Reopening, because we will still keep `--mount` for services. (In future it will be converted to "long" `--volume`)

Please do NOT merge until I migrate the code to use `docker service`

2016-11-25 13:10 UTC, AkihiroSuda commented
Closing again 😅 , because I noticed we don't have `--read-only` for services (so, no one will try to make `/dev/shm` read-only as well)
https://github.com/docker/docker/issues/25303

Is there a reason for not having `--read-only` for services?
@thaJeztah @icecrime @stevvooe

2016-11-25 13:26 UTC, thaJeztah commented
> Is there a reason for not having `--read-only` for services?

I don't think there is, it's just not implemented yet, and I think there have not been requests for it so far. I personally think it would make sense to have it as an option, so feel free to open an issue for it, then I  link it from https://github.com/docker/docker/issues/25303.

(perhaps you would like to start on implementing it as well. I don't think there would be an objection against it, but don't tie me to that 😅 )

2016-11-25 13:45 UTC, justincormack commented
Ugh, not having `--read-only` for services is really bad.

2016-11-25 13:54 UTC, justincormack commented
@AkihiroSuda actually on a LSB compliant system

```
docker run -it --read-only -v /var/empty:/dev/shm:ro alpine sh -c 'mount | grep /dev/shm'
```

should work. Probably good enough for the test...

2016-11-25 16:46 UTC, justincormack commented
Hmm, Debian doesn't seem to have `/var/empty`.

2016-11-25 17:58 UTC, diogomonica commented
Not sure if that should be a flag we add to services. It should be part of the security profile for services instead.

/cc @aluzzardi @cyli

2016-11-25 18:02 UTC, justincormack commented
Yeah that could work too.

On 25 Nov 2016 5:58 p.m., "Diogo Mónica" <notifications@github.com> wrote:

> Not sure if that should be a flag we add to services. It should be part of
> the security profile for services instead.
>
> /cc @aluzzardi <https://github.com/aluzzardi> @cyli
> <https://github.com/cyli>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/28823#issuecomment-263005404>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAdcPB5t181tCtWgLMEK_DtLGBrfn6gSks5rByHagaJpZM4K8IpR>
> .
>

2016-11-29 05:15 UTC, AkihiroSuda commented
Thank you for the suggestion @justincormack , re-re-opened this PR.
In this PR use `ioutil.TempDir()` instead of `/var/empty`.
PTAL.

2016-12-05 04:45 UTC, AkihiroSuda commented
PTAL @diogomonica @justincormack

2016-12-05 14:40 UTC, thaJeztah approved these changes
LGTM

2016-12-05 18:45 UTC, diogomonica commented
LGTM

2016-12-05 18:49 UTC, cpuguy83 commented on integration-cli/docker_cli_run_test.go
> +	testRequires(c, DaemonIsLinux)
Needs `SameHostDaemon` as well.

2016-12-05 18:50 UTC, cpuguy83 requested changes
Couple of nits.

2016-12-06 03:44 UTC, AkihiroSuda commented
done @cpuguy83

2016-12-06 05:20 UTC, AkihiroSuda commented
experimental failure unrelated
```
00:58:02.850 ----------------------------------------------------------------------
00:58:02.850 FAIL: docker_cli_swarm_test.go:999: DockerSwarmSuite.TestSwarmJoinPromoteLocked
00:58:02.850 
00:58:02.850 [dddab4373b008] waiting for daemon to start
00:58:02.851 [dddab4373b008] daemon started
00:58:02.851 [d5386c8e54108] waiting for daemon to start
00:58:02.851 [d5386c8e54108] daemon started
00:58:02.851 [d5386c8e54108] exiting daemon
00:58:02.851 [d5386c8e54108] waiting for daemon to start
00:58:02.851 [d5386c8e54108] daemon started
00:58:02.851 [dd8bd8150205f] waiting for daemon to start
00:58:02.852 [dd8bd8150205f] daemon started
00:58:02.852 [d5386c8e54108] exiting daemon
00:58:02.852 [d5386c8e54108] waiting for daemon to start
00:58:02.852 [d5386c8e54108] daemon started
00:58:02.852 [dd8bd8150205f] exiting daemon
00:58:02.852 [dd8bd8150205f] waiting for daemon to start
00:58:02.853 [dd8bd8150205f] daemon started
00:58:02.853 [dd8bd8150205f] exiting daemon
00:58:02.853 [dd8bd8150205f] waiting for daemon to start
00:58:02.853 [dd8bd8150205f] daemon started
00:58:02.853 [dd8bd8150205f] exiting daemon
00:58:02.853 [dd8bd8150205f] waiting for daemon to start
00:58:02.853 [dd8bd8150205f] daemon started
00:58:02.854 docker_cli_swarm_test.go:1058:
00:58:02.854     checkSwarmLockedToUnlocked(c, d3, unlockKey)
00:58:02.854 docker_cli_swarm_test.go:821:
00:58:02.854     c.Assert(getNodeStatus(c, d), checker.Equals, swarm.LocalNodeStateActive)
00:58:02.854 ... obtained swarm.LocalNodeState = "locked"
00:58:02.854 ... expected swarm.LocalNodeState = "active"
00:58:02.855 
00:58:02.855 [dddab4373b008] exiting daemon
00:58:02.855 [d5386c8e54108] exiting daemon
00:58:02.855 [dd8bd8150205f] exiting daemon
00:58:05.627 
00:58:05.627 ----------------------------------------------------------------------
```

2016-12-06 13:39 UTC, cpuguy83 approved these changes
LGTM

2016-12-06 13:39 UTC, merged

2016-12-06 16:33 UTC, anusha-ragunathan commented
userns CI fails due to this test:
https://jenkins.dockerproject.org/job/Docker%20Master%20%28userns%29/4636/consoleText
https://jenkins.dockerproject.org/job/Docker%20Master%20%28userns%29/4637/consoleText

```
FAIL: docker_cli_run_test.go:4652: DockerSuite.TestRunMountReadOnlyDevShm

docker_cli_run_test.go:4661:
    c.Assert(out, checker.Contains, "Read-only file system")
... obtained string = "" +
...     "container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:102: remounting \\\\\\\"/dev\\\\\\\" as readonly caused \\\\\\\"operation not permitted\\\\\\\"\\\"\"\n" +
...     "/go/src/github.com/docker/docker/bundles/1.14.0-dev/binary-client/docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:102: remounting \\\\\\\"/dev\\\\\\\" as readonly caused \\\\\\\"operation not permitted\\\\\\\"\\\"\".\n" +
...     "time=\"2016-12-06T14:27:14Z\" level=error msg=\"error getting events from daemon: context canceled\" \n"
... substring string = "Read-only file system"
```

2016-12-06 17:25 UTC, crosbymichael commented
Because of the way we handle /dev/shm I think you have to set the ro option here and not have runc do it because of the restrictions in the user namespace.

https://github.com/docker/docker/blob/master/container/container_unix.go#L251

2016-12-06 18:22 UTC, cyli commented
@AkihiroSuda Sorry for the trouble - I think https://github.com/docker/docker/pull/29096 should hopefully fix that test instability

2016-12-07 03:47 UTC, AkihiroSuda commented
@anusha-ragunathan @carlossg 

Oh, sorry for breaking userns Jenkins.. (BTW can we revive it in github's "check" UI?)

I tried to reproduce the failure on local userns, but could not reproduce..

```console
$ docker run  --read-only -v /var/empty:/dev/shm:ro -v /:/host busybox touch /host/this-touch-will-fail-with-EPERM-if-userns-really-working
touch: /host/this-touch-will-fail-with-EPERM-if-userns-really-working: Permission denied
```
(userns is working, it is not failing due to mounting /dev/shm:ro)

```console
$ sudo cat /etc/docker/daemon.json
{
  "storage-driver": "overlay2",
  "log-level": "debug",
  "debug": true,
  "experimental": true,
  "userns-remap": "default"
}
```

```console
$ docker info
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 1
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: ws01
ID: SN3T:CNK6:JKQD:54CY:XKF2:BRX3:CIRU:DQBT:6DVZ:VWQ2:Q5ET:F23L
Docker Root Dir: /var/lib/docker/1083040.1083040
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 22
 System Time: 2016-12-07T03:45:31.080006937Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```


```console
$ docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   eefbf1d
 Built:        Wed Dec  7 01:53:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   eefbf1d
 Built:        Wed Dec  7 01:53:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```