Rename 'context' to 'loginfo' in the logger module
moby/moby pull request #28852
Opened 2016-11-26 05:15 UTC by miaoyq

/cc @thaJeztah @justincormack 

Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>

2016-11-26 09:05 UTC, vdemeester commented
@miaoyq `gofmt` error 👼 

```
05:30:17 Successfully built f049b54837ce
05:30:19 Congratulations!  All commits are properly signed with the DCO!
05:30:19 These files are not properly gofmt'd:
05:30:19  - daemon/logger/gelf/gelf.go
05:30:19 
05:30:19 Please reformat the above files using "gofmt -s -w" and commit the result.
```

2016-11-26 13:10 UTC, miaoyq commented
Thanks @vdemeester 
Fixed

2016-11-26 14:08 UTC, justincormack commented
Another `lint` error
```
13:19:30 Errors from golint:
13:19:30 daemon/logger/loginfo.go:10:1: comment on exported type LogInfo should be of the form "LogInfo ..." (with optional leading article)
13:19:30 
13:19:30 Please fix the above errors. You can test via "golint" and commit the result.
13:19:30 
```

2016-11-26 14:13 UTC, justincormack commented on api/types/container/config.go
> -	Hostname        string                // Hostname
confused as to why spacing changed here, does not seem to be changed in this PR.

2016-11-27 14:45 UTC, miaoyq commented on api/types/container/config.go
> -	Hostname        string                // Hostname
The lint error have been fixed, Thanks so much! @justincormack

2016-12-29 01:10 UTC, miaoyq commented
@vdemeester @justincormack  @AkihiroSuda Could this PR be merged?

2016-12-29 08:10 UTC, vdemeester requested changes

2016-12-29 08:10 UTC, vdemeester commented on api/types/container/config.go
> -	Hostname        string                // Hostname
@miaoyq as it's not related to the changes, could you remove this file from the commit ? 👼 (should be `git checkout HEAD~1 api/types/container/config.go`)

2016-12-29 08:10 UTC, vdemeester commented on daemon/logger/loginfo.go
> +// LogInfo provides enough information for a logging driver to do its function.
As we already are in `logger` package, `LogInfo` seems redondant, maybe just `Info` ? @thaJeztah wdyt 👼 ?

2016-12-29 10:31 UTC, thaJeztah commented on daemon/logger/loginfo.go
> +// LogInfo provides enough information for a logging driver to do its function.
Sounds good to me

2016-12-29 10:47 UTC, miaoyq commented on daemon/logger/loginfo.go
> +// LogInfo provides enough information for a logging driver to do its function.
OK, I will change `LogInfo` to `Info`, Thanks @vdemeester @thaJeztah

2016-12-29 10:56 UTC, miaoyq commented on daemon/logger/loginfo.go
> +// LogInfo provides enough information for a logging driver to do its function.
@vdemeester @thaJeztah
updated. PTAL

2016-12-29 11:47 UTC, miaoyq commented on daemon/logger/loginfo.go
> +// LogInfo provides enough information for a logging driver to do its function.
@vdemeester @thaJeztah 
Updated.  PTAL

2016-12-29 14:20 UTC, vdemeester approved these changes
LGTM 🐸

2016-12-29 16:35 UTC, thaJeztah approved these changes
LGTM

2016-12-30 00:13 UTC, merged