Limit TestEventsLimit to 4 concurrent containers on Windows
moby/moby pull request #28968
Opened 2016-11-30 01:55 UTC by darrenstahlmsft

This hopefully fixes the latest TestEventsLimit failures on windowsRS1.

Signed-off-by: Darren Stahl <darst@microsoft.com>

2016-12-08 01:45 UTC, tonistiigi commented
That seems like a strange fix. If it is a platform bug then can we add a more specific comment about what command fails with what message and if possible a way to check the status of that bug.

2017-01-19 07:54 UTC, AkihiroSuda commented
ping @darrenstahlmsft

2017-01-27 20:22 UTC, LK4D4 requested changes

2017-01-27 20:22 UTC, LK4D4 commented on integration-cli/docker_cli_events_test.go
> +	// Limit to 4 goroutines creating containers in order to prevent timeouts
@darrenstahlmsft this comment looks not true, we still limiting to 8 everywhere apart from Windows.

2017-01-27 20:23 UTC, LK4D4 commented
@darrenstahlmsft Is there a particular bug which will be fixed in windows? Or is it by design?

2017-01-30 19:17 UTC, darrenstahlmsft commented
@LK4D4 Fixed so Windows is the only platform getting concurrency limits in this test.

@tonistiigi Is the new comment enough for you? Unfortunately there is no way to check the status of internal Windows bugs :( I could add a tracking number for Microsoft employees if that helps, but I don't think that will be useful

2017-01-30 19:49 UTC, LK4D4 approved these changes

2017-01-30 19:49 UTC, LK4D4 commented
LGTM

2017-01-30 19:58 UTC, tonistiigi commented
LGTM

2017-01-30 23:09 UTC, merged