Support plugin type in `docker inspect`
moby/moby pull request #28967
Opened 2016-11-30 01:42 UTC by yongtang

**- What I did**

This fix tries to address the proposal raised in #28946 to support plugins in `docker inspect`.

The command `docker inspect` already supports "container", "image", "node", "network", "service", "volume", "task". However, `--type plugin` is not supported yet at the moment.

**- How I did it**

This fix address this issue by adding the support of `--type plugin` for `docker inspect`.

**- How to verify it**

An additional integration test has been added to cover the changes.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

![3840x2160-animals_kitten_cute_kitten_cat-14319](https://cloud.githubusercontent.com/assets/6932348/20736405/138cc730-b65b-11e6-81a5-25c11a5f0ee6.jpg)

This fix fixes #28946.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-11-30 09:03 UTC, vdemeester commented
/cc @icecrime @vieux @tiborvass

2016-11-30 20:13 UTC, LK4D4 commented
LGTM

2016-11-30 22:49 UTC, vieux commented
LGTM ping @tiborvass @anusha-ragunathan

2016-11-30 23:20 UTC, tiborvass requested changes
@yongtang this doesn't handle the default `:latest` tag. `docker inspect tiborvass/sample-volume-plugin` should work after installing it.

2016-12-01 00:34 UTC, yongtang commented
Thanks @tiborvass for the review. This PR is loosely related to #28789 
In case of plugin name without tag. If #28789 is merged in then the issue is resolved.

I added a couple of test cases for plugin name without tag. The test cases will fail at the moment, but should be able to pass after #28789 is in.

Alternatively, if we want to defer the merging of #28789 after 1.13, then I could also update this PR to only include related changes to make the test cases (plugin name without tag) pass for this PR.

Please take a look at this PR and #28789.

2016-12-01 11:56 UTC, albers commented
Very nice, but as @tiborvass mentioned, proper treatment of plugins without version (defaulting to latest) is needed. Perhaps #28789 could go into 1.13.0 as well?

2016-12-01 17:19 UTC, anusha-ragunathan commented on integration-cli/docker_cli_inspect_test.go
> +	out, _, err = dockerCmdWithError("inspect", "--format", "{{.Name}}", pNameWithTag)
Needs a `--type plugin`. Also, how's this different from the inspect command at L426?

2016-12-01 17:20 UTC, anusha-ragunathan commented on integration-cli/docker_cli_inspect_test.go
> +	out, _, err = dockerCmdWithError("inspect", "--format", "{{.Name}}", pNameWithTag)
Ditto for L439.

2016-12-01 17:27 UTC, anusha-ragunathan commented
LGTM. We can merge this after 28789 is merged.

2016-12-02 22:00 UTC, yongtang commented
@tiborvass @anusha-ragunathan Since #28789 has been merged in, I did a rebase to this PR.

Now it is possible to specify `docker inspect ` without the plugin tag. It is shown in the case of the added integration tests.

Please take a look and let me know if there are any issues.

2016-12-02 22:01 UTC, yongtang commented
The Jenkins failure is caused by:
```
21:06:49 Set build name.
21:06:49 Workspace is not accessible
21:06:49 Build was aborted
21:06:49 [PostBuildScript] - Execution post build scripts.
21:06:49 Notifying endpoint 'HTTP:https://leeroy.dockerproject.org/notification/jenkins'
21:06:50 Finished: ABORTED
```

I think triggering the Jenkins for WindowsRS1 again will likely make it pass.

2016-12-05 02:30 UTC, merged

2016-12-05 05:30 UTC, albers commented
Thanks @yongtang!