Windows: Factor out sqlite
moby/moby pull request #28996
Opened 2016-11-30 19:02 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Based on https://github.com/docker/docker/pull/28964#issuecomment-263929569, it's true :smile:. SQLite dependency on Windows is removed.  

@thaJeztah If we can get this into 1.13, I can update #28964 to match.

2016-11-30 20:31 UTC, thaJeztah commented
Just discussed this, but we don't think it's needed for 1.13, but definitely nice for master/next release

2016-11-30 21:05 UTC, cpuguy83 commented
Don't need it at all for 1.14, I think, just need to ensure we tell users "You need to upgrade from a previous version first" if we find a container with old links.

2016-11-30 21:12 UTC, jhowardmsft commented
> I think, just need to ensure we tell users "You need to upgrade from a previous version first" if we find a container with old links.

@cpuguy83 How is that relevant to docker on Windows? This migration pulls in SQLite3 which is in-necessary on Windows.

2016-12-01 11:02 UTC, justincormack commented
If we are going to remove sqlite completely in 1.14 then we dont need this I guess. Shall we just rip it out now?

2016-12-01 11:03 UTC, justincormack requested changes

2016-12-01 11:03 UTC, justincormack commented on daemon/links_unix.go
> +// +build !windows
this is only needed on linux, no other platform (eg solaris) was supported then either.

2016-12-01 11:04 UTC, justincormack commented
I would be inclined to put this into 1.13 though.

2016-12-01 14:08 UTC, cpuguy83 approved these changes
LGTM after changing `_unix` to `_linux` as @justincormack suggested.

2016-12-01 14:09 UTC, cpuguy83 commented
@jhowardmsft You're right, it's helpful to have the split (since Windows doesn't need to error out) even though we want to remove it on Linux too.

2016-12-01 17:43 UTC, jhowardmsft commented
@justincormack @cpuguy83 Updated for Linux only. 

@thaJeztah I do think this does make sense though for 1.13 and the first official Windows release. But will leave that for you and @vieux to decide on.

2016-12-01 20:27 UTC, thaJeztah commented
Just re-discussed this with @vieux, and he's ok with doing it in 1.13

2016-12-01 21:13 UTC, jhowardmsft commented
@justincormack Just needs you to approve the _Linux updates :)

2016-12-01 21:55 UTC, justincormack approved these changes

2016-12-01 21:56 UTC, merged