add some defer closes for pkg
moby/moby pull request #29054
Opened 2016-12-02 07:33 UTC by lixiaobing10051267

in pkg, some files were opened, but not defer closed.

2016-12-02 09:14 UTC, AkihiroSuda requested changes

2016-12-02 09:14 UTC, AkihiroSuda commented on pkg/filenotify/poller.go
> +	defer f.Close()
Already ensured in the watch goroutine

2016-12-02 09:15 UTC, AkihiroSuda requested changes

2016-12-02 09:15 UTC, AkihiroSuda commented on pkg/tarsum/tarsum_test.go
> +			defer fh.Close()
io.Reader lacks Close

2016-12-02 10:26 UTC, allencloud commented on pkg/filenotify/poller.go
> +	defer f.Close()
I disagree to add defer close here.

2016-12-02 13:47 UTC, cpuguy83 commented on pkg/tarsum/tarsum_test.go
> +			defer fh.Close()
And is already being closed later on (After this if block)

2016-12-02 13:47 UTC, cpuguy83 commented on pkg/filenotify/poller.go
> +	defer f.Close()
Agreed, this not correct. This file needs to remain open when this function returns.

2016-12-02 13:48 UTC, cpuguy83 commented
Thanks for looking at this!
However, I'm closing because these changes are not correct.
Feel free to discuss.

2016-12-02 13:48 UTC, closed without merging

2016-12-03 01:48 UTC, lixiaobing10051267 commented
Oh, yes, sorry about that.