Revert "Fix dockerfile parser with empty line after escape"
moby/moby pull request #29064
Opened 2016-12-02 10:01 UTC by vdemeester

This reverts commit 3e1b539e8d0ed4abf695b0a8c42346fba6d5a6b0, in order to fix #29005 but reverting #24725.

The basic idea is the following :

* Reverting that altogether on 1.13 to not break people
* For 1.14, add it back but as a warning first and with a deprecation notice.
* When it's time, no more warning

/ping @yongtang can you work on that for 1.14 ?

/cc @tiborvass @thaJeztah @cpuguy83 @vieux @duglin @tianon @yosifkit

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2016-12-02 10:13 UTC, runcom commented
Sgtm

2016-12-02 10:52 UTC, thaJeztah requested changes

2016-12-02 10:52 UTC, thaJeztah commented on integration-cli/docker_cli_build_test.go
> -func (s *DockerSuite) TestBuildSquashParent(c *check.C) {
Don't think this one must be removed

2016-12-02 10:52 UTC, thaJeztah commented on integration-cli/docker_cli_build_test.go
> -func (s *DockerSuite) TestBuildContChar(c *check.C) {
Don't think this one must be removed

2016-12-02 10:52 UTC, thaJeztah commented on integration-cli/docker_cli_build_test.go
> -func (s *DockerSuite) TestBuildOpaqueDirectory(c *check.C) {
Same

Actually, looks like only the first one has to be removed; https://github.com/docker/docker/commit/3e1b539e8d0ed4abf695b0a8c42346fba6d5a6b0

2016-12-02 13:17 UTC, duglin commented
Should we start the deprecation process in this release?

2016-12-02 13:20 UTC, thaJeztah commented
@duglin I think that was option `C`, and not everyone was sure about that. Could be done in a follow-up for discussion I guess

2016-12-02 13:24 UTC, vdemeester commented
@duglin We're getting pretty close to the release. I would tend to prefer start the depreciation process in the next release to not overdo this release, but as @thaJeztah says, could be done in a follow-up.

2016-12-02 13:35 UTC, thaJeztah approved these changes
LGTM

2016-12-02 13:36 UTC, thaJeztah commented
oh, we should revert the changelog as well, and reopen https://github.com/docker/docker/issues/24693 after this was merged

2016-12-02 16:30 UTC, yongtang commented
Thanks @vdemeester for the PR. I will work on the follow up PR for deprecation/warning based on the discussion in #29005.

2016-12-02 16:32 UTC, thaJeztah commented
Thanks @yongtang, sorry for having this PR in parallel to yours, we wanted to have it ready for the next RC :heart:

2016-12-03 01:08 UTC, tiborvass commented
LGTM

2016-12-03 01:11 UTC, merged