hack/make.sh: fix BUILDTIME
moby/moby pull request #29082
Opened 2016-12-02 18:57 UTC by runcom

Fix https://github.com/docker/docker/issues/28206

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

2016-12-02 18:58 UTC, runcom commented
I'm running `make rpm` to test this out

2016-12-02 20:22 UTC, runcom commented
asked @vdemeester to test this out with and without this line https://github.com/docker/docker/pull/29082/files#diff-c4b8d2fa793507a7ce5835e7ca780464R87 (I have laptop issues right now)

2016-12-02 20:25 UTC, vdemeester commented
/cc @andrewhsu

2016-12-02 20:31 UTC, runcom commented on hack/make.sh
> +	! BUILDTIME=$(date --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/')
@vdemeester please test w/o this line as well

2016-12-02 22:22 UTC, vdemeester approved these changes
```
$ docker version                                                                                                                                                                                                                                                           
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   2675214
 Built:        Fri Dec  2 20:55:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   2675214
 Built:        Fri Dec  2 20:55:39 2016
```

LGTM :angel:

2016-12-02 22:27 UTC, runcom commented
ping @thaJeztah 

@vdemeester so many thanks for the testing :heart:

2016-12-02 23:00 UTC, vdemeester commented on hack/make.sh
> +	! BUILDTIME=$(date --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/')
```
[root@vde-rpm-build docker]# docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   2675214-unsupported
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   2675214-unsupported
 Built:        
 OS/Arch:      linux/amd64
 Experimental: false
```

This one was needed too :scream:

2016-12-02 23:02 UTC, vdemeester requested changes
See https://github.com/docker/docker/pull/29082#discussion_r90735290 :sweat_smile:

2016-12-03 08:09 UTC, runcom commented
@vdemeester PTAL

2016-12-03 10:21 UTC, vdemeester commented on hack/make.sh
> +	! BUILDTIME=$(date --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/')
@runcom yeah, I don't know how, but couldn't reproduce later, my fault :sweat_smile:

2016-12-03 10:23 UTC, runcom commented on hack/make.sh
> +	! BUILDTIME=$(date --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/')
Alright, so it's not needed right? :)

2016-12-03 10:24 UTC, vdemeester commented on hack/make.sh
> +	! BUILDTIME=$(date --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/')
I think the way it is now it the right thing. Building rpms again to make sure :angel:

2016-12-03 11:58 UTC, vdemeester approved these changes
```
[root@fedora-rpms-test ~]# docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   7b1f77d
 Built:        Sat Dec  3 11:20:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   7b1f77d
 Built:        Sat Dec  3 11:20:43 2016
 OS/Arch:      linux/amd64
 Experimental: false
```
LGTM :frog:

2016-12-04 11:16 UTC, runcom commented
ping @thaJeztah :innocent:

2016-12-05 20:40 UTC, jhowardmsft commented
@runcom Nice! Obvious when you see it. That's been there a long time! April 2014 from what I can tell from a quick look: 355ad33087c1c683458b60a6bc9e1f89623ee275

2016-12-05 20:41 UTC, jhowardmsft commented
LGTM assuming @vdemeester also validates RPMs 😇

2016-12-06 00:31 UTC, vieux commented
SGTM

2016-12-06 00:31 UTC, merged