Add credential helper documentation
moby/moby pull request #29092
Opened 2016-12-03 00:06 UTC by KingEmet

Follow-up to #25851 

![sleep tight pupper](http://i.imgur.com/4ybg2jx.jpg)

Signed-off-by: Jake Sanders <jsand@google.com>

2016-12-03 00:07 UTC, KingEmet commented
Dat palendrome doe...

2016-12-05 14:25 UTC, thaJeztah requested changes
Thanks! I left some notes/suggestions

2016-12-05 14:25 UTC, thaJeztah commented on docs/reference/commandline/login.md
> +operations concering credentials of the specified registries.
typo; `concering` -> `concerning`

2016-12-05 14:25 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +        "sfo.unicorn.com": "vcbait"
for documentation, perhaps use the `example.*` domain's, which are intended for that (the domains here may actually exist at some point). e.g., `my-registry.example.com`

2016-12-05 14:25 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +[**Credentials store** section in the `docker login` documentation](login.md)
can you add an anchor tag here? `login.md#credentials-store`

2016-12-05 14:25 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +[**Credential helpers** section in the `docker login` documentation](login.md)
same here; `login.md#credential-helpers`

2016-12-05 14:25 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +is visible on $PATH. If this property is not set, credentials will be stored
Can you put back-tics around `$PATH`?

2016-12-05 19:11 UTC, KingEmet commented on docs/reference/commandline/login.md
> +operations concering credentials of the specified registries.
done

2016-12-05 19:12 UTC, KingEmet commented on docs/reference/commandline/cli.md
> +        "sfo.unicorn.com": "vcbait"
done

2016-12-06 10:00 UTC, vdemeester requested changes

2016-12-06 10:00 UTC, vdemeester commented on docs/reference/commandline/login.md
> +## <a name="credentials-store">Credentials store</a>
Hum, are thous `<a …` required ? first time I see those in our ref doc.

2016-12-06 11:07 UTC, thaJeztah requested changes
Thanks @KingEmet, I left some comments.

Also, can you squash your commits? No need to preserve history for these review comments

2016-12-06 11:07 UTC, thaJeztah commented on docs/reference/commandline/login.md
> +## <a name="credentials-store">Credentials store</a>
No, it's not needed, it's automatically generated when converting the Markdown to HTML (including when reading on GitHub)

2016-12-06 11:07 UTC, thaJeztah commented on docs/reference/commandline/login.md
> +    "example.awesomereg.io": "hip-star",
oh, I meant to use `example.com` or `example.org` as domain name. I know it _should_ be clear to users, but we've had situations where people used the literal examples, and the first domain is actually active (second one is available to buy if you're interested :smile:);

```
Domain Name: REGISTRY.COM
Registrar: GODADDY.COM, LLC
...
Expiration Date: 18-nov-2018
```


perhaps `awesomereg.example.org` ?

2016-12-06 11:07 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +        "example.awesomereg.io": "hip-star",
Same here (domain name)

2016-12-07 18:16 UTC, KingEmet commented
done?

2016-12-07 21:02 UTC, vdemeester approved these changes
LGTM 🐸

2016-12-08 14:29 UTC, thaJeztah approved these changes
LGTM, thanks!!

2016-12-08 14:29 UTC, merged