Fix processing of unset build-args during build
moby/moby pull request #29104
Opened 2016-12-03 19:57 UTC by duglin

Fix processing of unset build-args during build
    
This reverts 26103.  26103 was trying to make it so that if someone did:
`docker build --build-arg FOO .`
and FOO wasn't set as an env var then it would pick-up FOO from the 
Dockerfile's ARG cmd.  However, it went too far and removed the ability
to specify a build arg w/o any value. Meaning it required the --build-arg
param to always be in the form "name=value", and not just "name".
    
This PR does the right fix - it allows just "name" and it'll grab the value
from the env vars if set. If "name" isn't set in the env then it still needs
to send "name" to the server so that a warning can be printed about an
unused --build-arg. And this is why buildArgs in the options is now a
*string instead of just a string - 'nil' == mentioned but no value.
    
Closes #29084
    
Signed-off-by: Doug Davis <dug@us.ibm.com>

2016-12-04 17:30 UTC, vdemeester commented on api/server/router/build/build_routes.go
> +	// jason of the query param:
s/jason/json 👼

2016-12-04 18:24 UTC, duglin commented on api/server/router/build/build_routes.go
> +	// jason of the query param:
fixed

2016-12-04 20:47 UTC, cpuguy83 commented
I'm a bit confused why this requires changing types around, and particularly a string pointer.
Shouldn't this just be an issue on the CLI?

2016-12-04 20:52 UTC, duglin commented
@cpuguy83 I tried that but due to the way we send the data to the daemon (as a json object) we needed to support an arg having a value of "nil" - meaning it was mentioned on the cmd line but no value is associated with it.  The only way to keep the "nil" for an ARG is to have the json property be a *string. When its just a string we can't tell the different between "" meaning "just mentioned" vs "an empty string" value.

2016-12-06 13:51 UTC, cpuguy83 commented
@duglin But couldn't we not send the arg at all if there's nothing to send?
E.g., user does `--build-arg FOO`, `FOO` is not set as environment variable, don't send the the argument.

2016-12-06 14:23 UTC, duglin commented
@cpuguy83 the problem with not sending it all is then the user won't see the warning about specifying a build-arg that's not used in the Dockerfile.

So, for example, `docker build --build-arg FOO=bar` will generate:
```
[Warning] One or more build-args [FOO] were not consumed
```
if there is no `ARG FOO` in the Dockerfile.

I can't remember when we added the warning, but the decision was made to tell the user that they messed up by including a build-arg that's never mentioned in the Dockerfile. This would avoid them thinking that they were providing info that actually was never going to be used.

In order to keep these semantics we need to include the data that they specified it on the cmd line to the daemon.  I decided that even if there is no env var **currently** specified, we should still tell the use they messed up because I would expect the same results no matter what my env looked like. In both cases I specified a build-arg that isn't actually defined in the Dockerfile.

Note - this doesn't change the API at all. I made sure of that. This is just changing how we deal with the data internally to capture the 3 possible states (mentioned/no-value, "", "value").

2016-12-07 15:28 UTC, cpuguy83 requested changes
I guess this makes sense due to the Dockerfile parsing needing to happen in the daemon :(

Would also have preferred `FOO=` to be a nil value rather than an empty string, but we're passed that I guess.

2016-12-07 15:28 UTC, cpuguy83 commented on builder/dockerfile/dispatchers.go
> +	if val, ok := b.options.BuildArgs[name]; (!ok || val == nil) && hasDefault {
Naming here is a bit confusing `val` and `value`.

2016-12-07 15:34 UTC, duglin commented on builder/dockerfile/dispatchers.go
> +	if val, ok := b.options.BuildArgs[name]; (!ok || val == nil) && hasDefault {
yep - renamed "val" to "baValue" (BuildArgValue) and renamed "value" to be "newValue".
Hopefully that helps.

2016-12-07 15:37 UTC, cpuguy83 approved these changes
LGTM

2016-12-07 15:38 UTC, vdemeester approved these changes
LGTM 🐸

2016-12-07 15:39 UTC, vdemeester commented
@duglin oh 

```
15:36:34 # github.com/docker/docker/builder/dockerfile
15:36:34 ..\..\builder\dockerfile\dispatchers.go:748: undefined: newValue
15:36:34 ..\..\builder\dockerfile\dispatchers.go:764: undefined: newValue
```

2016-12-07 15:40 UTC, duglin commented
@cpuguy83 yea, if we were sending the data as just strings (like we do with env vars) then we could have use:  "FOO" vs "FOO=" vs "FOO=value" to differentiate between the cases.

However, even with that, we'd still probably need to use *string in the code itself because "string" can be used to represent "no value".  Unlike the env vars, that are stored in memory as a []string, we store buildArgs in a map[string]string - well, now map[string]*string.  We could store them as []string too but that would make the look-up slower.  A long time ago I tried to switch env vars to use a map too but that's a different story for another day. :-)

2016-12-07 15:40 UTC, duglin commented
@vdemeester oops - push coming in a sec....
thanks!

2016-12-07 15:42 UTC, duglin commented
ok fixed -sorry for being lazy

2016-12-08 01:18 UTC, tonistiigi commented
LGTM

2016-12-08 01:18 UTC, merged