Update the option for docker build
moby/moby pull request #29267
Opened 2016-12-09 07:09 UTC by yuexiao-wang

**- What I did**
1. Update the option 'network' for docker build
2. Update the format of squash  for docker build
3. Update the man document 

**- How I did it**

**- How to verify it**

**- Description for the changelog**
Update for keep consistency for docker build

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

2016-12-09 08:53 UTC, AkihiroSuda requested changes

2016-12-09 08:53 UTC, AkihiroSuda commented on cli/command/image/build.go
> +	flags.StringVar(&options.networkMode, "network", "default", "Set the networking mode for the run commands during build")
SGTM, but I think `RUN instructions` should be better than `run commands`
https://docs.docker.com/engine/reference/builder/

2016-12-09 09:46 UTC, AkihiroSuda commented on docs/reference/commandline/build.md
> +  --squash                      Squash newly built layers into a single new layer (**Experimental Only**)
You can fix this indentation as well

2016-12-09 09:46 UTC, yuexiao-wang commented
@AkihiroSuda PTAL
Done!

2016-12-12 01:16 UTC, yuexiao-wang commented on docs/reference/commandline/build.md
> +  --squash                      Squash newly built layers into a single new layer (**Experimental Only**)
@AkihiroSuda PTAL
Done.
Sorry, response to it late.

2016-12-12 14:39 UTC, thaJeztah approved these changes
LGTM

2016-12-13 01:20 UTC, AkihiroSuda commented on man/docker-build.1.md
> +Any other value is taken as a custom network's name or ID which this container should connect to.
Please add an empty line here

2016-12-13 01:53 UTC, yuexiao-wang commented on man/docker-build.1.md
> +Any other value is taken as a custom network's name or ID which this container should connect to.
@AkihiroSuda PTAL
Done and thanks

2016-12-13 01:55 UTC, AkihiroSuda approved these changes
LGTM

2016-12-13 07:55 UTC, merged