Remove the utils package
moby/moby pull request #29314
Opened 2016-12-11 21:28 UTC by vdemeester

This removes the `github.com/docker/docker/utils` package and move code around in *better* places.

* Move `TestDirectory` function (used in a test in `registry` to `pkg/testutil`)
* Move *process* fuction (`IsProcessAlive`, `KillProcess`, …) to `pkg/system`
* Move debug functions to `cli/debug` are they are mainly used for `cli`
* Move `utils/templates` to `pkg/templates`
* move `ReplaceOrAppendEnvValues` to `container` package
* Move names regexp to the `api` package (I think it made sense)

I did separate commits for each of this point but I can squash if required 👼 

/cc @thaJeztah @cpuguy83 @dnephin @icecrime

2016-12-12 00:28 UTC, AkihiroSuda commented on pkg/testutil/tempfile/tempfile.go
> +var globalTestID string
why global?

2016-12-12 07:52 UTC, vdemeester commented on pkg/testutil/tempfile/tempfile.go
> +var globalTestID string
@AkihiroSuda yeah I just moved the code. I was wondering the same thing :sweat_smile:

2016-12-16 20:22 UTC, dnephin approved these changes
LGTM

Nice change!

2016-12-20 23:38 UTC, tiborvass requested changes

2016-12-20 23:38 UTC, tiborvass commented on container/container_windows.go
> +	return ReplaceOrAppendEnvValues(linkedEnv, container.Config.Env)
this change should not be in this commit.

2016-12-21 21:25 UTC, vdemeester commented on container/container_windows.go
> +	return ReplaceOrAppendEnvValues(linkedEnv, container.Config.Env)
oh :scream_cat:

2016-12-21 21:43 UTC, vdemeester commented on container/container_windows.go
> +	return ReplaceOrAppendEnvValues(linkedEnv, container.Config.Env)
Should be in the right commit :angel: :stuck_out_tongue:

2016-12-22 14:20 UTC, thaJeztah approved these changes
LGTM, much cleaner!

2016-12-22 14:20 UTC, thaJeztah commented on distribution/registry_unit_test.go
> +// TestDirectory creates a new temporary directory and returns its path.
nit: s/TestDirectory/testDirectory/

2016-12-22 14:21 UTC, merged