Fix incorrect words and formats in image
moby/moby pull request #29345
Opened 2016-12-13 06:03 UTC by yuexiao-wang

**- What I did**
1. Fix incorrect words such as "Invalid" and "Exected"
2. Error information should begin with lower-case 
3. Supplement some information

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

2016-12-13 11:44 UTC, allencloud commented on image/fs_test.go
> +	// skipping use of digest pkg because its is used by the implementation
its -> it ?

2016-12-13 11:54 UTC, yuexiao-wang commented on image/fs_test.go
> +	// skipping use of digest pkg because its is used by the implementation
Sorry,  It will be applied to this PR.
Thanks a lot.

2016-12-14 00:56 UTC, yuexiao-wang commented
@thaJeztah PTAL
Combine #29351 into this PR.
Thanks

2016-12-15 01:44 UTC, yuexiao-wang commented
@thaJeztah @vdemeester PTAL

2016-12-15 08:26 UTC, vdemeester requested changes

2016-12-15 08:26 UTC, vdemeester commented on image/fs_test.go
> +		t.Fatal("expected to get failed after data modification.")
Pretty sure the initial message is better (we expect the `get` method to fail)

2016-12-15 08:26 UTC, vdemeester commented on image/fs_test.go
> +		t.Fatal("expecting error from invalid filesystem data.")
s/expecting/expected

2016-12-15 09:14 UTC, yuexiao-wang commented
@vdemeester PTAL
Done
Thanks

2016-12-15 11:40 UTC, thaJeztah commented on image/fs_test.go
> +	testWalk(t, fs)
I'm not sure this is correct; it's testing a _walker_ (that "walks")? In any case, I'm not sure we gain much by renaming these

2016-12-15 11:54 UTC, yuexiao-wang commented on image/fs_test.go
> +	testWalk(t, fs)
@thaJeztah PTAL
OK and reverted them.

2016-12-15 12:18 UTC, thaJeztah requested changes

2016-12-15 12:18 UTC, thaJeztah commented on image/image.go
>  	// Parent id of the image
Looking at this again, I think I know why these comments were inconsistent. I think the original intent of these was to write;

```
ID - a unique 64 character identifier of the image
Comment - user added comment
```

Which doesn't follow GoDoc conventions. _However_, now that _some_ follow those conventions, and some don't, we should be careful;

```
Parent id of the image
```

could now be interpreted as

```
Parent - ID of the image
```

Which isn't correct. I suggest (but further suggestions welcome);

```
Parent is the ID of the parent image
Comment is the commit message that was set when committing the image
Created is the timestamp at which the image was created
DockerVersion specifies the version of Docker that was used to build the image
Author is the name of the author that was specified when committing the image
```

2016-12-15 12:18 UTC, thaJeztah commented on image/tarexport/tarexport.go
> +// NewTarExporter returns new Exporter in image for tar packages
not sure we need "in image" 

```
NewTarExporter returns a new Exporter for saving images as tar packages
```

@vdemeester does that look correct? ^

2016-12-15 13:11 UTC, vdemeester commented on image/tarexport/tarexport.go
> +// NewTarExporter returns new Exporter in image for tar packages
I would say yes :angel:

2016-12-16 02:00 UTC, yuexiao-wang commented
@thaJeztah @vdemeester PTAL
thanks

2016-12-16 15:37 UTC, thaJeztah commented on image/image.go
> +	// Comment is custom message set by user when creating the image.
can use the same here as above;

```
Comment is the commit message that was set when committing the image
```

2016-12-16 15:39 UTC, thaJeztah commented on image/image.go
> +	// Created is timestamp when image was created
```
Created is the timestamp at which the image was created
```

2016-12-16 15:40 UTC, thaJeztah requested changes
Some issues remaining, see my comments inline

2016-12-16 15:40 UTC, thaJeztah commented on image/image.go
> +	// Parent is the id of the image
You missed "parent" here;

```
Parent is the ID of the parent image
```

2016-12-19 06:42 UTC, yuexiao-wang commented
@thaJeztah PTAL
Thanks!

2016-12-19 08:46 UTC, yuexiao-wang commented on image/image.go
> +	// Author is the name of the author that was specified when building the image
@thaJeztah 
It uses "building the image" here , right?

2016-12-19 10:33 UTC, thaJeztah commented on image/image.go
> +	// Author is the name of the author that was specified when building the image
Should probably be `committing` as well here, given that this value is set by the `--author` flag on `docker commit` https://docs.docker.com/engine/reference/commandline/commit/

2016-12-20 01:53 UTC, yuexiao-wang commented
@thaJeztah PTAL
It has been done.
Thanks

2016-12-20 17:17 UTC, thaJeztah approved these changes
LGTM

2016-12-20 17:17 UTC, thaJeztah commented
@vdemeester PTAL

2016-12-21 20:50 UTC, vdemeester approved these changes
LGTM :frog:

2016-12-21 20:50 UTC, merged