[plugins] return err when failing remove
moby/moby pull request #29372
Opened 2016-12-13 22:19 UTC by tophj-ibm

Fixes a case where removing the plugin from disk would
fail silently. Also moves pluginStore remove after we
remove from disk, so 'docker plugin ls'  isn't
empty in case it errors out.

Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>

ping @anusha-ragunathan @tiborvass

2016-12-13 22:20 UTC, vdemeester commented
/cc @vieux @anusha-ragunathan @tiborvass

2016-12-13 22:21 UTC, tophj-ibm commented
I've been trying to write a test case for this, but I can't figure out how to get RemoveAll to fail when run as root. Even the go stdlib RemoveAll test fails in this case.

2016-12-13 23:35 UTC, tiborvass commented
Seems reasonable. LGTM

2016-12-13 23:50 UTC, thaJeztah commented on plugin/backend_linux.go
> +		return fmt.Errorf("unable to remove %q from plugin remove: %v", pluginDir, err)
was discussing with @tiborvass; should this use `errors.Wrap()`?

2016-12-14 17:28 UTC, thaJeztah commented on plugin/backend_linux.go
> +		return fmt.Errorf("unable to remove %q from plugin remove: %v", pluginDir, err)
It's provided through this package; https://github.com/pkg/errors#adding-context-to-an-error

2016-12-14 17:31 UTC, tophj-ibm commented on plugin/backend_linux.go
> +		return fmt.Errorf("unable to remove %q from plugin remove: %v", pluginDir, err)
thanks, I did find and read that 😄  PR should be up to date now.

2016-12-14 17:43 UTC, cpuguy83 requested changes

2016-12-14 17:43 UTC, cpuguy83 commented on plugin/backend_linux.go
> +		return errors.Wrap(err, "failed to remove plugin directory")
Probably need to handle this like in container rm where it's something like
```go
defer func() {
    if err == nil || config.ForceRemove {
        pm.pluginStore.Remove(p)
        pm.pluginEventLogger(id, name, "remove")
    }
}()

2016-12-14 19:19 UTC, tophj-ibm commented on plugin/backend_linux.go
> +		return errors.Wrap(err, "failed to remove plugin directory")
question: If we are force removing and RemoveAll fails, shouldn't it keep the plugin in the store so you can see that it is still there / that remove failed (besides the err)? If it's not in the store, doesn't that means the only way to remove it is by manually removing it from disk?

2016-12-14 19:22 UTC, cpuguy83 commented on plugin/backend_linux.go
> +		return errors.Wrap(err, "failed to remove plugin directory")
I think if someone is specifying force remove then we should remove it from the store no matter what.
We could report a warning still.

This is what we do for containers and volumes.

2016-12-14 19:57 UTC, tophj-ibm commented on plugin/backend_linux.go
> +		return errors.Wrap(err, "failed to remove plugin directory")
Okay, should be updated. It will throw an error on that case anyway.

2016-12-14 19:59 UTC, cpuguy83 commented on plugin/backend_linux.go
> +		if err == nil || config.ForceRemove {
you'll need to name the error return for this to work, or change `if err :=` to `if err = `. and define error above.

2016-12-15 01:25 UTC, vieux commented
ping @cpuguy83

2016-12-15 01:27 UTC, cpuguy83 approved these changes
LGTM

2016-12-15 08:17 UTC, vdemeester approved these changes
LGTM 🐻

2016-12-15 08:18 UTC, merged