We need to fix labels if the user requests on volumes
moby/moby pull request #29428
Opened 2016-12-14 22:23 UTC by rhatdan

Currently local volumes and other volumes that support SELinux do
not get labeled correctly.  This patch will allow a user to specify
:Z or :z when  mounting a volume and have it fix the label of the newly
created volume.

Signed-off-by: Dan Walsh <dwalsh@redhat.com>

2016-12-14 22:24 UTC, rhatdan commented
Fixes this bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1401260

2016-12-14 22:24 UTC, rhatdan commented
I did testing on docker-1.12 branch, I have not gotten 1.14 to work yet.

2016-12-15 08:42 UTC, vdemeester commented
/cc @cpuguy83 @crosbymichael

2016-12-15 15:55 UTC, runcom commented
LGTM (the bugzilla isn't mentioning that this issue happends with `--selinux-enabled`, btw, I can reproduce it and this patch fixes it).

2016-12-15 16:04 UTC, cpuguy83 commented
Not sure I follow that issue... but isn't this the same as https://github.com/docker/docker/blob/master/volume/volume.go#L155-L159

I guess the relabel just needs to be moved up before the `if m.Volume != nil`

2016-12-15 16:08 UTC, rhatdan commented
I think you would need it in both cases.  Since the second case the source directory is being created and needs to be labeled.

2016-12-15 16:11 UTC, rhatdan commented
The Relabel has to happen after this code also.
```
if bind.Driver == volume.DefaultDriverName {
				setBindModeIfNull(bind)
}
```
Since this says if "local" volume and bind.Mode is Null, then set it to "z"

2016-12-15 16:16 UTC, cpuguy83 commented
This `Setup()` function is called when the container is started, which seems like a good place, we just aren't setting it for volumes, only binds.

2016-12-15 16:49 UTC, rhatdan commented
@cpuguy83 Do you like this one better?  Should I relabel before or after the mount call?

2016-12-15 20:28 UTC, cpuguy83 commented
How about a defer at the top of the function... we'll have to name the returns so we can check if err is nil in the defer, but since there's no happy case where we don't want to relabel, I think it's safer.

2016-12-15 21:05 UTC, rhatdan commented
@cpuguy83 Kind of ugly, is this what  you had in mind?  Any cleaner way to do this?

2016-12-15 21:06 UTC, cpuguy83 requested changes

2016-12-15 21:06 UTC, cpuguy83 commented on volume/volume.go
> +		err  error
declar this in the return instead of here.

2016-12-15 21:06 UTC, cpuguy83 commented on volume/volume.go
> +	defer func() (string, error) {
no need to declare a return here

2017-01-10 15:54 UTC, rhatdan commented
@cpuguy83 PTAL

2017-01-10 15:56 UTC, cpuguy83 approved these changes
LGTM

2017-01-26 19:47 UTC, LK4D4 commented
Code is kinda weird, but I'm going to merge it anyway.

2017-01-26 19:47 UTC, LK4D4 approved these changes
LGTM

2017-01-26 19:47 UTC, merged