Add Fuxi Volume Plugin to the docs
moby/moby pull request #29468
Opened 2016-12-16 02:07 UTC by hongbin

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Hongbin Lu <hongbin034@gmail.com>

2016-12-16 15:53 UTC, thaJeztah requested changes

2016-12-16 15:53 UTC, thaJeztah commented on docs/extend/legacy_plugins.md
> +[Fuxi Volume Plugin](https://github.com/openstack/fuxi)                             | A volume plugin that is developed as part of the OpenStack Kuryr project and implements the Docker volume plugin
Can you move the plugin "up", so that the list is in alphabetical order?

2016-12-19 15:05 UTC, hongbin commented
@thaJeztah , thanks for the review. I have updated the pull request to address your comments.

2016-12-19 17:22 UTC, thaJeztah approved these changes
LGTM, thanks!

/cc @vdemeester

2016-12-21 20:47 UTC, vdemeester approved these changes
LGTM :frog:

2016-12-21 20:49 UTC, merged