Refactor and extract TestRequire functionality
moby/moby pull request #29483
Opened 2016-12-16 14:18 UTC by vdemeester

This will help when extracting suites in their own package. Ideas is :

```go
func (s *MySuite) TestMyTest(c *check.C) {
    requirement.Is(c, SameDaemon, ArchitectureIs("amd64"), someLocalCheck)
    // […]
}
```

I really wish `go-check` would use `Skip(...interface{})` instead of `Skip(string)`, as it would make this mechanism work for both `go-check` and `testing` packages.

/cc @icecrime @thaJeztah @dnephin @cpuguy83 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2016-12-16 14:30 UTC, thaJeztah commented
SGTM

2016-12-16 16:38 UTC, icecrime commented on integration-cli/requirement/requirement.go
> +			s.Skip(message)
If that's the only place where the message is used, then _maybe_ we should consider a nuclear option that would avoid complicating the syntax for all the callers of requirement functions. We could:

- Have requirements functions be `func () bool`, in such way that we can continue writing `if SameHostDaemon() {`.
- Use some reflect magic here to provide a message, as in `s.Skip(fmt.Sprintf("unmatched requirement %s", runtime.FuncForPC(<some_reflect_magic>).Name())`.

2016-12-19 22:12 UTC, dnephin approved these changes
LGTM

2016-12-20 21:19 UTC, tiborvass commented
@vdemeester needs a rebase

2016-12-21 00:14 UTC, thaJeztah commented
@vdemeester is rebasing :house: -> 🏡

2016-12-21 21:17 UTC, vdemeester commented
🏡  and rebased

2016-12-21 21:20 UTC, cpuguy83 requested changes

2016-12-21 21:20 UTC, cpuguy83 commented on integration-cli/requirements_unix_test.go
> +func overlayFSSupported() bool {
Should just be `overlayFSSupported` and remove the `overlaySupported`

2016-12-21 21:38 UTC, vdemeester commented on integration-cli/requirements_unix_test.go
> +func overlayFSSupported() bool {
@cpuguy83 oh thanks… I messed up the *conflict* merging here…

2016-12-21 21:40 UTC, vdemeester commented
@cpuguy83 done :angel:

2016-12-21 21:42 UTC, cpuguy83 approved these changes

2016-12-22 09:24 UTC, merged