Improve error output for `docker stats ...`
moby/moby pull request #29491
Opened 2016-12-16 20:23 UTC by yongtang

While looking into `docker stats <c1> <c2> ...` I noticed that the error output is quite long, especially if there are multiple errors:

```sh
ubuntu@ubuntu:~/docker$ docker stats nofound
: Error response from daemon: No such container: nofound
ubuntu@ubuntu:~/docker$ docker stats nofound foo bar
: Error response from daemon: No such container: nofound, : Error response from daemon: No such container: foo, : Error response from daemon: No such container: bar
```

There are several issues,
1. There is an extra `: ` at the beginning. That is because if container is not found, the name will not be available from the daemon.
2. Multiple errors are concatenated with `, ` which will be quite long.

This fix:
1. Only prient out the error from daemon.
2. Multiple errors are printed out line by line.

Below is the new output:
```sh
ubuntu@ubuntu:~/docker$ docker stats nofound
Error response from daemon: No such container: nofound
ubuntu@ubuntu:~/docker$ docker stats nofound foo bar
Error response from daemon: No such container: nofound
Error response from daemon: No such container: foo
Error response from daemon: No such container: bar
```

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-12-18 00:13 UTC, thaJeztah requested changes

2016-12-18 00:13 UTC, thaJeztah commented on cli/command/container/stats.go
> +				errs = append(errs, fmt.Sprintf("%v", cErr))
Perhaps simplify to

```go
if err := c.GetError(); err != nil {
	errs = append(errs, err.Error())
}
```

2016-12-18 00:17 UTC, thaJeztah commented
One suggestion, but looks good otherwise; tested this, and definitely looks better :smile:

2016-12-18 00:28 UTC, yongtang commented
Thanks @thaJeztah. The PR has been updated. 😅

2016-12-18 00:32 UTC, thaJeztah commented on cli/command/container/stats.go
>  			cErr := c.GetError()
oh, any reason you didn't put this in the `if` initialization? I think `cErr` is only used inside the `if`, so can be scoped to that (see my example)

2016-12-18 01:46 UTC, thaJeztah commented on cli/command/container/stats.go
>  			cErr := c.GetError()
No problem! Just started doubting myself if I overlooked something, and you may have had a special reason not to change it haha 👍

2016-12-18 01:46 UTC, thaJeztah approved these changes
LGTM

2016-12-21 18:19 UTC, cpuguy83 approved these changes
This is kinda gross, but I guess since this is being directly displayed on stdout it's ok.

LGTM

2016-12-21 18:19 UTC, merged