links are unavailable
moby/moby pull request #29540
Opened 2016-12-19 12:44 UTC by tim-zju

Signed-off-by: tim-zju <21651152@zju.edu.cn>

**- What I did**
delete links which are unavailable in docs->api->version-history.md
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-19 13:59 UTC, thaJeztah requested changes

2016-12-19 13:59 UTC, thaJeztah commented on docs/api/version-history.md
> -[Docker Engine API v1.25](v1.25.md) documentation
I think this will become https://docs.docker.com/engine/api/v1.25/ once 1.13 is released (same for the v1.26 above)

2016-12-21 09:09 UTC, AkihiroSuda requested changes
Please squash commits

2016-12-21 10:50 UTC, thaJeztah commented on docs/api/version-history.md
> +[Docker Engine API v1.26](v1.26.md) documentation
Can you change this to https://docs.docker.com/engine/api/v1.26/, and the v1.25 link to  https://docs.docker.com/engine/api/v1.26/ ?

The documentation for docker 1.13 and 1.14 is not published yet, so the links will not be there yet, but once docker they're up, those should be the URL's. See https://github.com/docker/docker.github.io/tree/vnext-engine/engine/api/v1.25

2017-01-12 17:27 UTC, vdemeester commented
ping @tim-zju

2017-01-17 00:42 UTC, thaJeztah commented
closing, because there was no response, but let us know if you still want to work on this

2017-01-17 00:42 UTC, closed without merging