several function names fixed in devmapper.go
moby/moby pull request #29577
Opened 2016-12-20 07:25 UTC by lixiaobing10051267

several function names fixed in devmapper.go.

2016-12-20 14:32 UTC, thaJeztah requested changes

2016-12-20 14:32 UTC, thaJeztah commented on pkg/devicemapper/devmapper.go
> +		return fmt.Errorf("devicemapper: Error running deviceCreate (createSnapDeviceRaw) %s", err)
Should be with a capital `C`

2016-12-21 01:11 UTC, thaJeztah requested changes
can you squash your commits?

2016-12-21 01:23 UTC, lixiaobing10051267 commented
yeah, has been squashed.

2016-12-21 12:22 UTC, thaJeztah approved these changes
LGTM

2016-12-21 13:23 UTC, vdemeester approved these changes
LGTM 🐸

2016-12-21 17:21 UTC, merged