Inappropriate punctuation modified
moby/moby pull request #29584
Opened 2016-12-20 09:21 UTC by EnergyLiYN

Signed-off-by: yanan Lee <energylyn@zju.edu.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-20 14:27 UTC, thaJeztah requested changes
Not sure we should change all of these

2016-12-20 14:27 UTC, thaJeztah commented on api/swagger.yaml
> +        This endpoint returns a live stream of a container's resource usage statistics.
These don't have to be changed, see http://practicaltypography.com/straight-and-curly-quotes.html

2016-12-20 14:27 UTC, thaJeztah commented on CHANGELOG.md
> +* The new ONBUILD instruction adds to your image a `trigger` instruction to be executed at a later time, when the image is used as the base for another build
This should not be changed, because `trigger` is not a command or literal string printed by docker here

2016-12-20 14:27 UTC, thaJeztah commented on api/swagger.yaml
> +          description: "If `1`, `true`, or `True` then it will be an error if unpacking the given content would cause an existing directory to be replaced with a non-directory and vice versa."
Have you tried if this renders correctly if you `make swagger-docs`, and view the generated documentation?

2016-12-20 14:46 UTC, EnergyLiYN commented on api/swagger.yaml
> +          description: "If `1`, `true`, or `True` then it will be an error if unpacking the given content would cause an existing directory to be replaced with a non-directory and vice versa."
![image](https://cloud.githubusercontent.com/assets/19368056/21354359/b650a6bc-c704-11e6-8d1a-d8dcda64c737.png)
I think there should be corresponding with this.

2017-01-10 03:12 UTC, stevvooe commented
Was this for a school assignment?

2017-01-13 09:57 UTC, closed without merging