some grammatical errors
moby/moby pull request #29590
Opened 2016-12-20 13:07 UTC by wxb0521

Signed-off-by: Xinbo Weng <xihuanbo_0521@zju.edu.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-20 14:15 UTC, thaJeztah requested changes
Thanks; found one issue, and /cc'd @aaronlehmann for the change in the image-spec

2016-12-20 14:15 UTC, thaJeztah commented on experimental/docker-stacks-and-bundles.md
> +`services` in the bundle is the services that comprise the app. They
this change doesn't look correct

2016-12-20 14:15 UTC, thaJeztah commented on image/spec/v1.1.md
> +        must comply with standard DNS rules, but may not contain
/cc @aaronlehmann

2016-12-20 14:36 UTC, wxb0521 commented on experimental/docker-stacks-and-bundles.md
> +`services` in the bundle is the services that comprise the app. They
I think `services`  is a field name , like a proper noun. So it should be considered singular.

2016-12-20 14:41 UTC, thaJeztah commented on experimental/docker-stacks-and-bundles.md
> +`services` in the bundle is the services that comprise the app. They
I understand, but the sentence is hard to read this way. Consider changing to 

"services in the bundle is a list of service that comprise the app"

"in the bundle"  may not be needed, as the introduction above is already mentioning this is about the bundle file.

2016-12-21 00:49 UTC, wxb0521 commented on experimental/docker-stacks-and-bundles.md
> +`services` in the bundle is the services that comprise the app. They
Thank you! I understand your meaning. And `are` is correct.

2016-12-21 01:05 UTC, thaJeztah commented on image/spec/v1.1.md
> +        must comply with standard DNS rules, but may not contain
My preference would go to "comply with" as well, but wanted to check with @aaronlehmann, the devil may be in the detail with specs

2016-12-21 01:12 UTC, aaronlehmann commented on image/spec/v1.1.md
> +        must comply with standard DNS rules, but may not contain
Either one is fine.

2017-01-12 17:26 UTC, vdemeester commented
ping @wxb0521 could you take care of @thaJeztah comment ? 👼

2017-01-24 01:54 UTC, AkihiroSuda commented
ping @wxb0521

2017-01-31 21:57 UTC, LK4D4 commented
@thaJeztah mind to carry this?

2017-02-01 03:35 UTC, thaJeztah commented
carried in https://github.com/docker/docker/pull/30620

2017-02-01 03:35 UTC, closed without merging