Clarify what docker diff shows
moby/moby pull request #29603
Opened 2016-12-20 19:51 UTC by mstanleyjones

**- What I did**

Added info about the baseline that the `docker diff` command is using for comparison.
This is due to a request at https://github.com/docker/docker.github.io/issues/736.

I went ahead and changed the usage instructions in Cobra to match what I changed in the Markdown.

2016-12-20 20:15 UTC, thaJeztah commented on man/docker-diff.1.md
> +    $ docker diff 1fdfd1f54c1b
forgot to un-indent this one

2016-12-20 20:18 UTC, thaJeztah requested changes
Found one nit, and a question, but looks good otherwise

2016-12-20 20:18 UTC, thaJeztah commented on man/docker-diff.1.md
> +the full or shortened container ID or the container name set using
Should we mention the A/D/C meaning in this file as well?

2016-12-20 21:16 UTC, mstanleyjones commented
Addressed the feedback, tried to unify the contents of the man page and command-line reference to be more similar.

2016-12-20 21:40 UTC, thaJeztah commented on docs/reference/commandline/diff.md
> +# EXAMPLES
oh, this needs to be in sentence-case, and a H2 for the online docs (all-caps is just for formatting in the man pages)

2016-12-20 21:41 UTC, thaJeztah commented on docs/reference/commandline/diff.md
> +**docker run --name** option.
For the online docs, this should be in back tics instead :blush:

2016-12-20 21:42 UTC, thaJeztah requested changes
Sorry, looks like I caused some extra work ☺️

2016-12-21 01:03 UTC, mstanleyjones commented
Addressed @thaJeztah feedback.

2016-12-21 01:09 UTC, thaJeztah commented on docs/reference/commandline/diff.md
> +## diff
Weren't these generated from the metadata now?
Guess we need to do a full pass to remove the H1's everywhere

2016-12-21 01:09 UTC, thaJeztah approved these changes
LGTM

2016-12-22 14:14 UTC, vdemeester approved these changes
LGTM 🐮

2016-12-22 14:15 UTC, merged