followup to incorporate review comments per previous reviews on PR#29561
moby/moby pull request #29615
Opened 2016-12-21 01:50 UTC by londoncalling

### What I did

Incorporated review comments

### Description for the changelog

Glossary updates for Docker for Mac and Windows, copy-on-write, and union filesystem

2016-12-21 02:00 UTC, londoncalling commented
@thaJeztah @mstanleyjones these are the changes that didn't make it in before PR #29561 got merged, but now I am getting conflicts that don't show up when I fetch and rebase. @mstanleyjones let's look at this together tomorrow.

2016-12-21 02:55 UTC, allencloud commented
Conflict occurs, rebase need, I am afraid @londoncalling  😄

2016-12-21 23:35 UTC, londoncalling commented
@thaJeztah @mstanleyjones @allencloud this has more changes per review comments, and merge conflicts are now resolved. If it looks ok to you guys, please merge for me. Thanks!

2016-12-21 23:54 UTC, mdlinville approved these changes
LGTM

2016-12-22 12:32 UTC, thaJeztah requested changes
Thanks @londoncalling! found some minor issues, but LGTM otherwise

2016-12-22 12:32 UTC, thaJeztah commented on docs/reference/glossary.md
> +container-specific changes on a writable in-memory layer which is deleted when
remove "in-memory" here, because the writable layer is also written to disk

2016-12-22 12:32 UTC, thaJeztah commented on docs/reference/glossary.md
> -supersedes [Docker Toolbox](#toolbox) as state-of-the-art Docker for macOS.
Incomplete sentence; Looks like something went wrong here with the rebase, or the trailing `Docker for Mac` must be removed

2016-12-22 12:32 UTC, thaJeztah commented on docs/reference/glossary.md
> +Examples implementations of union file systems are
s/Examples/Example/

2016-12-22 19:55 UTC, londoncalling commented
@thaJeztah @mstanleyjones thanks for the reviews! 

Please have a look, and merge if you think all comments are addressed properly and it looks ok.

2016-12-22 20:25 UTC, thaJeztah commented
@londoncalling changes look good now, can you squash your commits?

2016-12-22 20:32 UTC, londoncalling commented
@thaJeztah how's that?

2016-12-22 20:50 UTC, thaJeztah approved these changes
yup, all good 👍 LGTM

Ho! Ho! here we go

2016-12-22 20:50 UTC, merged