modify builder.md and run.md of /doc/reference/
moby/moby pull request #29618
Opened 2016-12-21 02:23 UTC by CandiceGuo

**- What I did**
I have modified several English grammar mistakes in two files. They are  /doc/reference/builder.md and /doc/reference/run.md. 
**- How I did it**
Errors always occur on the third person singular.
**- How to verify it**
I found them and corrected them.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-21 02:23 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:CandiceGuo/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-21 02:44 UTC, allencloud commented on docs/reference/builder.md
> +process does is to send the entire context (recursively) to the daemon.  In most
I think this part is reasonable. `to` is not necessary.

2016-12-21 07:20 UTC, CandiceGuo commented
How to solve the problem of dco-signed?

2016-12-21 07:56 UTC, CandiceGuo commented
I  fixed my key issues and forced pushed. But it seems the dco/no tag not remove. How can I do ?

2016-12-21 23:31 UTC, thaJeztah requested changes
Your fork was probably out of date when rebasing, and because of that, some unrelated commits ended up in your branch. I also see that you opened your pull request from your "master" branch; it's best to create a separate "feature" branch for each pull request so that you can work on them without interfering with changes to master. (see https://docs.docker.com/opensource/workflow/find-an-issue/#/sync-your-fork-and-create-a-new-branch)

To fix this;

If your "upstream" (docker) remote is called "upstream", this should do it;

```
git fetch upstream; git fetch origin; git rebase upstream/master;
```

after that, _force_ push to your own fork;

```
git push -f origin
```

More information can also be found in our contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

2016-12-23 08:38 UTC, allencloud commented on builder/tarsum.go
> +	if err != nil {
I think it is not necessary to make such kind of change.

2016-12-23 11:34 UTC, thaJeztah requested changes
@CandiceGuo thanks for contributing, but unfortunately these changes are not correct (see my review inline).

Also, I see there are still some "foreign" commits in your pull request that shouldn't be in there.

I recommend reading the contributors guide (see my earlier comment for links) to get familiar with the workflow.

I'll close this pull request, but welcome seeing future contributions from your hand!

2016-12-23 11:34 UTC, thaJeztah commented on docs/reference/builder.md
> +    Sending build context to Docker daemons 2.048 kB
Sorry, this is not correct, `daemon` is singular (there's only one daemon this is being sent to)

2016-12-23 11:34 UTC, thaJeztah commented on docs/reference/builder.md
> +were loaded with `docker load`. If you wish to use build cache of a specific
this is not correct either; "the whole chain of images" is also singular (the _chain_ (of images) was loaded with `docker load`)

2016-12-23 11:34 UTC, closed without merging