misusing a and an
moby/moby pull request #29627
Opened 2016-12-21 06:43 UTC by tim-zju

Signed-off-by: tim-zju <21651152@zju.edu.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-21 07:25 UTC, AkihiroSuda requested changes

2016-12-21 07:25 UTC, AkihiroSuda commented on docs/api/v1.19.md
> - - When the client API version is newer than the daemon's, these calls return an HTTP
"an aitch tee tee pee" is correct

2016-12-21 08:11 UTC, allencloud commented on docs/api/v1.19.md
> - - When the client API version is newer than the daemon's, these calls return an HTTP
I am 👎  on this part as well.

2016-12-21 09:11 UTC, AkihiroSuda requested changes

2016-12-21 09:11 UTC, AkihiroSuda commented on docs/extend/plugin_api.md
> -To ease plugins development, we're providing an `sdk` for each kind of plugins
"an ess dee kay" is correct

2016-12-21 23:17 UTC, thaJeztah commented on docs/reference/builder.md
> +
Be careful with your editor settings; it looks like it's stripping whitespace, which can quickly lead to too many unrelated changes and (in some case) trailing whitespace is added on purpose.

In this case I think it's ok to remove, but try to configure your editor to not automatically strip it (or make sure to revert those changes before committing)

2017-01-10 03:05 UTC, stevvooe commented
I don't see any corrections that are correct. Closing.

Thanks for the PR!

2017-01-10 03:05 UTC, closed without merging