Optimized the english expression of this document
moby/moby pull request #29630
Opened 2016-12-21 08:55 UTC by dongziming

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-21 08:55 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:dongziming/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354519400
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-21 09:00 UTC, AkihiroSuda requested changes
A bunch of unrelated commits seems squashed to this PR..

2016-12-21 09:08 UTC, AkihiroSuda commented
Also, please consider squashing https://github.com/docker/docker/pull/29629

2016-12-28 16:48 UTC, cpuguy83 commented
Looks like there's still a bunch of unrelated items in this PR.
I'm going to go ahead and close.

Feel free to open a new one fixing the grammar and what have you.

2016-12-28 16:48 UTC, closed without merging