Clean up client binary dependencies
moby/moby pull request #29666
Opened 2016-12-22 21:54 UTC by tonistiigi

This removes following packages from client binary

```
"github.com/docker/docker/api/server/httputils",
"github.com/docker/docker/api/types/backend",
"github.com/docker/docker/builder",
"github.com/docker/docker/daemon/graphdriver",
"github.com/docker/docker/distribution",
"github.com/docker/docker/distribution/metadata",
"github.com/docker/docker/distribution/xfer",
"github.com/docker/docker/image",
"github.com/docker/docker/image/v1",
"github.com/docker/docker/layer",
"github.com/docker/docker/oci",
"github.com/docker/docker/pkg/chrootarchive",
"github.com/docker/docker/pkg/mount",
"github.com/docker/docker/pkg/plugingetter",
"github.com/docker/docker/pkg/plugins",
"github.com/docker/docker/pkg/plugins/transport",
"github.com/docker/docker/pkg/reexec",
"github.com/docker/docker/plugin/v2",
"github.com/docker/docker/vendor/github.com/docker/distribution/manifest",
"github.com/docker/docker/vendor/github.com/docker/distribution/manifest/manifestlist",
"github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema1",
"github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema2",
"github.com/docker/docker/vendor/github.com/golang/protobuf/proto",
"github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/configs",
"github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/devices",
"github.com/docker/docker/vendor/github.com/opencontainers/runtime-spec/specs-go",
"github.com/docker/docker/vendor/github.com/vbatts/tar-split/archive/tar",
"github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/asm",
"github.com/docker/docker/vendor/github.com/vbatts/tar-split/tar/storage",
"github.com/docker/docker/vendor/golang.org/x/net/http2",
"github.com/docker/docker/vendor/golang.org/x/net/http2/hpack",
"github.com/docker/docker/vendor/golang.org/x/net/internal/timeseries",
"github.com/docker/docker/vendor/golang.org/x/net/trace",
"github.com/docker/docker/vendor/google.golang.org/grpc",
"github.com/docker/docker/vendor/google.golang.org/grpc/codes",
"github.com/docker/docker/vendor/google.golang.org/grpc/credentials",
"github.com/docker/docker/vendor/google.golang.org/grpc/grpclog",
"github.com/docker/docker/vendor/google.golang.org/grpc/internal",
"github.com/docker/docker/vendor/google.golang.org/grpc/metadata",
"github.com/docker/docker/vendor/google.golang.org/grpc/naming",
"github.com/docker/docker/vendor/google.golang.org/grpc/peer",
"github.com/docker/docker/vendor/google.golang.org/grpc/transport",
"hash/crc64",
"html",
"html/template",
```

cc @dmcgowan

2016-12-22 22:32 UTC, thaJeztah commented
build fails @tonistiigi 

    22:00:36 FAIL	github.com/docker/docker/builder/clientutils [build failed]

2016-12-22 22:50 UTC, tonistiigi commented
@thaJeztah Fixed. So I just copied these 3 helper functions https://github.com/docker/docker/blob/d25186a625ca94ec1d4a814dd8745fd3ca335caa/builder/utils_test.go#L19-L61 to the other pkg as well. They did not look clean enough to make them public and move to separate `builder/testutil` pkg. If we can figure out a clean public `testutil` interface that everyone agrees on I could convert all of these tests to that. Or I could just rewrite them without the utility functions, but I don't think it needs to happen in this pr.

2016-12-22 23:44 UTC, dmcgowan commented
LGTM

2016-12-23 03:25 UTC, tonistiigi commented
CI failures not related

2016-12-23 08:04 UTC, vdemeester requested changes
@tonistiigi package `builder/clientutils` should really be `builder/client`, _utils_doesn't add anything :angel:

2016-12-23 21:45 UTC, tonistiigi commented
@vdemeester Well, these methods have even less to do with client than with utils. They really are just helper functions for walking/archiving directories, doing git clone and pulling a tarball. I'm bit confused even why we do it in client side and why we have a duplicate implementation for daemon but that's for another PR. If you look at https://github.com/docker/docker/pull/29666/files#diff-d95d1cd5af5a6266a043dad2ec7db72eR19 I replace client because it would be confusing to read otherwise. Happy to rename but don't think "client" is a correct name here.

2016-12-23 22:22 UTC, thaJeztah commented
>  doing git clone and pulling a tarball. I'm bit confused even why we do it in client side

I think this has to do with `docker build github.com/foo/bar`, which performs a git-checkout on the client, and sends that as build context for building an image

2016-12-24 16:17 UTC, vdemeester requested changes
Hum you're right, `client` as package name is worse. Looking a bit more the code, it seems those `clientutils`/`buildutils` method are only used from `cli` package, let's move them there then.

2016-12-24 16:17 UTC, vdemeester commented on cli/command/image/build.go
> +		buildCtx, relDockerfile, err = buildutils.GetContextFromReader(dockerCli.In(), options.dockerfileName)
@tonistiigi if it's only used in `cli` code let's put the function there then (`cli/commands/images/build` or `cli/build` for example).

2016-12-27 16:51 UTC, tonistiigi commented on cli/command/image/build.go
> +		buildCtx, relDockerfile, err = buildutils.GetContextFromReader(dockerCli.In(), options.dockerfileName)
@vdemeester PTAL

2016-12-27 16:59 UTC, vdemeester approved these changes
LGTM 🐸

2016-12-27 20:00 UTC, cpuguy83 approved these changes
LGTM

2016-12-27 20:01 UTC, merged