Fix image's `CMD` after `WORKDIR` in Dockerfile
moby/moby pull request #29679
Opened 2016-12-23 19:30 UTC by yongtang

This fix tries to fix #29667 where image's `CMD` is modified after `WORKDIR` in Dockerfile.

The value of `b.runConfig.Cmd` was modified in the processing
of `WORKDIR`, in order to fix 28902. However, the same
`b.runConfig.Cmd` is passed to `commit()`.

This fix restored the `b.runConfig.Cmd` before `commit()`
the image for `WORKDIR`.

A test has been added.

This fix fixes #29667.

This fix is related to #28902, #28909, #28514.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2016-12-23 19:44 UTC, yongtang commented
/cc @thaJeztah @tiborvass @tonistiigi @jhowardmsft

2016-12-23 20:27 UTC, thaJeztah commented
Thanks @yongtang! I think @tonistiigi and @tiborvass were discussing some options; one of which was to only start a container for Workdir on _Windows_, but don't do that on Linux, so perhaps they can have a look 👍

2016-12-27 03:09 UTC, tonistiigi commented
Didn't test this yet so maybe I'm missing something but shouldn't it be cleaner to just pass copy of config to `ContainerCreate()`?

Like @thaJeztah mentioned I was concerned if this change of the meaning/performance of `WORKDIR` instruction(#28514) got adequate review and would like to get more opinions about it. But that shouldn't block this fix.

2016-12-28 14:55 UTC, cpuguy83 requested changes
Looks good, but seems like tests could just be unit tests.

2016-12-28 18:04 UTC, tonistiigi commented
LGTM

2016-12-28 21:29 UTC, yongtang commented
Thanks @cpuguy83 for the review. I take a look and it seems that it is not very easy to come up with a unit test for that.

In the original implementation before this PR, `b.runConfig.Cmd` was changed and eventually restored back before return from `workdir()`. So from outside of `func workdir()` the `b.runConfig.Cmd` value is expected even before this PR.

The issue is that inside the `func workdir()`, the `b.runConfig.Cmd` value was modified before `commit()` statement. Even though `b.runConfig.Cmd` has been restored after the `commit()` statement, it still causes the generated docker image (at the commit step) to have modified `b.runConfig.Cmd` value.

I am thinking to test the correct behavior, we have to check the value of `b.runConfig.Cmd` for the `commit()` step. (We can not set `b.disableCommit = true` to skip it)
But `commit()` actually invokes the `daemon.Commit()`, which is quite similar as an integration test.

2016-12-29 01:26 UTC, cpuguy83 commented
Oh, seems so. Thanks for looking into it. We do some weird things sometimes, I guess.

2016-12-29 01:26 UTC, cpuguy83 approved these changes
LGTM

2016-12-29 01:27 UTC, merged

2017-01-02 18:11 UTC, vdemeester commented
https://github.com/docker/docker/pull/29679 was cherry-picked, should this one cherry-picked too ?
/cc @vieux @thaJeztah

2017-01-03 11:10 UTC, justincormack commented
@vdemeester yes I think it should be

2017-01-03 11:12 UTC, justincormack commented
Marked for cherry pick as users are reporting issues eg see https://github.com/docker/for-mac/issues/1085