Minor cleanups in cli/command/container
moby/moby pull request #29687
Opened 2016-12-25 00:12 UTC by thaJeztah

Was playing around with [Gogland](https://www.jetbrains.com/go/), so thought; "lets do some cleanup" :smile: 🎄 

This change does some minor cleanups in the cli/command/container package;

- sort imports
- replace `fmt.Fprintf()` with `fmt.Fprintln()` if no formatting is used
- replace `fmt.Errorf()` with `errors.New()` if no formatting is used
- remove some redundant `else`'s

2016-12-25 00:13 UTC, thaJeztah commented on cli/command/container/rm.go
> +		container = strings.Trim(container, "/")
this is the only "functional" change; I considered a container name containing only slashes to be "empty", but happy to change this back :smile:

2016-12-25 00:14 UTC, thaJeztah commented on cli/command/container/run.go
> +				return errHijack
This seemed more logical to me / slightly more readable

2016-12-25 00:14 UTC, thaJeztah commented
/cc @vdemeester

2016-12-25 09:51 UTC, vdemeester requested changes
Build is failing though

```
00:49:21 # github.com/docker/docker/cli/command/container
00:49:21 cli/command/container/run.go:77: undefined: errors in errors.New
00:49:21 cli/command/container/run.go:78: undefined: errors in errors.New
00:49:21 cli/command/container/unpause.go:46: undefined: errors in errors.New
```

And a few comments 😝

2016-12-25 09:51 UTC, vdemeester commented on cli/command/container/create.go
> +	fmt.Fprintln(dockerCli.Out(), response.ID)
😍

2016-12-25 09:51 UTC, vdemeester commented on cli/command/container/create.go
> +		return fmt.Errorf("failed to remove the CID file '%s': %s \n", cid.path, err)
At some point, we should use `github.com/pkg/errors` (`errors.Wrapf`) for those 👼

2016-12-25 10:06 UTC, thaJeztah commented on cli/command/container/create.go
> +		return fmt.Errorf("failed to remove the CID file '%s': %s \n", cid.path, err)
Yes, I actually considered that, but wasn't sure if it would change the format; I'll dig into that at some point :+1:

2016-12-25 10:07 UTC, vdemeester commented on cli/command/container/create.go
> +		return fmt.Errorf("failed to remove the CID file '%s': %s \n", cid.path, err)
@thaJeztah yeah, can definitely be in a follow-up PR :angel:

2016-12-25 10:10 UTC, thaJeztah commented
Let me look at the build failure when I get back; must've missed an import

2016-12-27 09:30 UTC, vdemeester approved these changes
LGTM 🐸

2016-12-29 08:31 UTC, merged