fix some typos
moby/moby pull request #29696
Opened 2016-12-26 04:53 UTC by zhenghenghuo

Signed-off-by: zhenghenghuo <zhenghenghuo@zju.edu.cn>

**- What I did**
fix some typos

**- How I did it**
"an" should be used before some words such as "STS" and "HTTP", and I change these "a" to "a"

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2016-12-26 05:04 UTC, AkihiroSuda requested changes
Please do not modify vendored files

2016-12-26 05:15 UTC, zhenghenghuo commented
but I don't know which kind of files are vendored files?

2016-12-26 05:27 UTC, AkihiroSuda commented
The files under the `vendor` directory.

These files are synced with other git repositories, using [vndr](https://github.com/LK4D4/vndr).
Please also refer to `vendor.conf`: https://github.com/docker/docker/blob/master/vendor.conf.

2016-12-26 05:33 UTC, zhenghenghuo commented
Thanks, and I remove those changes in vendored files.

2016-12-26 05:48 UTC, AkihiroSuda approved these changes
LGTM, but just note that some people pronounce SSH as /ssh/, SHA as /shaw/ :smile: 

http://www.linuxquestions.org/questions/general-10/how-do-you-pronounce-ssh-637508/
https://en.wikipedia.org/wiki/Talk:SHA-1/Archive_1

2016-12-26 05:54 UTC, zhenghenghuo commented
Thanks.

2016-12-27 11:19 UTC, thaJeztah requested changes
left a comment about the `SHA256`; can you change those back? Otherwise looks good

2016-12-27 11:19 UTC, thaJeztah commented on docs/reference/commandline/pull.md
> +Docker uses a content-addressable image store, and the image ID is an SHA256
agree with @AkihiroSuda I think this should be `a SHA256`

2016-12-27 11:19 UTC, thaJeztah commented on image/spec/v1.1.md
> +        representation. This is an SHA256 digest over the tar archive used to
same here

2016-12-27 11:19 UTC, thaJeztah commented on image/spec/v1.2.md
> +        representation. This is an SHA256 digest over the tar archive used to
and here

2016-12-27 12:03 UTC, thaJeztah approved these changes
LGTM, thanks!

2016-12-27 12:05 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "branch-two" git@github.com:zhenghenghuo/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353351592
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-27 12:11 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "branch-two" git@github.com:zhenghenghuo/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354153512
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-27 12:17 UTC, thaJeztah commented
Looks like your last push added a merge commit; can you rebase again?

2016-12-27 12:55 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "branch-two" git@github.com:zhenghenghuo/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353928232
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-27 12:58 UTC, thaJeztah commented
If you need help squashing your commits; the contributors guide has a section on rebasing/squashing; https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

2016-12-28 01:38 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "branch-two" git@github.com:zhenghenghuo/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354388184
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2016-12-28 07:05 UTC, merged