update URL of plugins_graphdriver.md in experimental/README.md
moby/moby pull request #29740
Opened 2016-12-28 02:03 UTC by lixiaobing10051267

update URL of plugins_graphdriver.md in experimental/README.md

2016-12-28 02:04 UTC, lixiaobing10051267 commented
oh, the commit message should be updated.

2016-12-28 08:15 UTC, thaJeztah requested changes

2016-12-28 08:15 UTC, thaJeztah commented on experimental/README.md
> + * [External graphdriver plugins](https://github.com/docker/docker/blob/master/docs/extend/plugins_graphdriver.md)
This should be a relative URL (`../docs/extend/plugins_graphdriver.md`), so that it links to the document in the same branch (not "master")

2016-12-29 01:42 UTC, lixiaobing10051267 commented
ok, has been updated to "../docs/extend/plugins_graphdriver.md"

2016-12-29 10:34 UTC, thaJeztah approved these changes
LGTM

2016-12-29 10:34 UTC, merged