[test-integration] Add a registry package with registry v1/v2 code
moby/moby pull request #29799
Opened 2016-12-30 18:40 UTC by vdemeester

This extract what was in registry_test.go and registry_mock_test.go. This also move `RegistryHosting` requirement to `registry.Hosting` 🦁.

Hopefully, my comments are ok 👼

/cc @thaJeztah @icecrime @dnephin @cpuguy83 @tiborvass @AkihiroSuda @aaronlehmann @dmcgowan 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2016-12-31 14:22 UTC, thaJeztah requested changes
found one leftover comment, but LGTM otherwise

2016-12-31 14:22 UTC, thaJeztah commented on integration-cli/docker_cli_pull_local_test.go
> +	//registryV2Path := filepath.Join(s.reg.dir, "docker", "registry", "v2")
leftover comment?

2016-12-31 14:23 UTC, vdemeester commented on integration-cli/docker_cli_pull_local_test.go
> +	//registryV2Path := filepath.Join(s.reg.dir, "docker", "registry", "v2")
Yes 😅

2017-01-02 10:38 UTC, AkihiroSuda commented on integration-cli/registry/requirement.go
> +// Hosting returns wether the host can host a registry (v2) or not
nit: wether -> whether

2017-01-02 10:38 UTC, AkihiroSuda commented on integration-cli/registry/registry_mock.go
> +// Mock represent a registry mock
nit: represent -> represents

2017-01-02 10:39 UTC, AkihiroSuda commented on integration-cli/registry/registry_mock.go
> +// RegisterHandler register the specified handler for the registry mock
nit: register -> registers

2017-01-02 10:40 UTC, AkihiroSuda approved these changes
LGTM

(typos are trivial)

2017-01-02 14:37 UTC, thaJeztah approved these changes
LGTM

2017-01-02 14:37 UTC, merged