Update reference document for secret and stack
moby/moby pull request #29791
Opened 2016-12-30 07:41 UTC by yuexiao-wang

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**- What I did**
Update the index for secret and stack in reference document

2017-01-01 15:22 UTC, RuairiSpain commented
Hi,

There are two markdown files related to deploy, "docker stack deploy" and the alias "docker deploy".  In deploy.md, apart from saying "docker deploy" is an alias for "docker stack deploy" the rest of the document is identical.  Maybe deploy.md could be shortened and just link to the stack_deploy.md file?

docker/docs/reference/commandline/deploy.md
docker/docs/reference/commandline/stack_deploy.md

One question, in the long run will "docker deploy" alias be depreciated in the API now that there is a set of stack commands?

2017-01-02 10:31 UTC, thaJeztah commented
> One question, in the long run will "docker deploy" alias be depreciated in the API now that there is a set of stack commands?

The "top level" `docker deploy` command is still marked "experimental", so only available if the `--experimental` flag is set on the daemon. No decision was made yet, but it's possible indeed that this command won't leave "experimental", and only the `docker stack deploy` command stays.

2017-01-03 06:45 UTC, yuexiao-wang commented
@thaJeztah 
Is there any suggestion for this PR?

2017-01-03 09:02 UTC, thaJeztah requested changes
Left one suggestion, but LGTM otherwise

2017-01-03 09:02 UTC, thaJeztah commented on docs/reference/commandline/stack_deploy.md
> +* [deploy](deploy.md)
I think we can just remove `deploy` here, because it's an alias for `stack deploy` (which is the page we're currently on)

2017-01-03 09:12 UTC, yuexiao-wang commented
@thaJeztah 
It has been done.

2017-01-03 09:52 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-01-03 09:54 UTC, vdemeester approved these changes
LGTM 🐸

2017-01-03 09:54 UTC, merged