Small cleanups on integration cli
moby/moby pull request #29831
Opened 2017-01-02 22:47 UTC by vdemeester

- Join a few tests in one when it makes sense (reduce the number of container run and thus the overall time of the suites)
- Remove some duplication on several tests
- Remove some unused methods

/cc @thaJeztah @icecrime @AkihiroSuda @dnephin @cpuguy83 @tiborvass 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2017-01-03 18:26 UTC, dnephin commented on integration-cli/trust_server_test.go
> +	return result.Combined()
:heart:

2017-01-03 18:26 UTC, dnephin commented on integration-cli/docker_experimental_network_test.go
> +	// ensure Kernel version is >= v3.9 for macvlan support
Minor: this comment could be updated

2017-01-03 18:26 UTC, dnephin commented on integration-cli/docker_cli_service_health_test.go
> -func (s *DockerSwarmSuite) TestServiceHealthUpdate(c *check.C) {
What's the story with this test?

2017-01-03 18:31 UTC, vdemeester commented on integration-cli/docker_cli_service_health_test.go
> -func (s *DockerSwarmSuite) TestServiceHealthUpdate(c *check.C) {
No idea, but the diff with the previous one is just an empty line so…
ping @runshenzhu

2017-01-03 18:36 UTC, dnephin commented on integration-cli/docker_cli_service_health_test.go
> -func (s *DockerSwarmSuite) TestServiceHealthUpdate(c *check.C) {
Ahh, I see. It's a duplicate.

I suspect it should be testing something else, but the line wasn't updated after the test was copied.

2017-01-03 18:54 UTC, thaJeztah requested changes
left some questions / suggestions

2017-01-03 18:54 UTC, thaJeztah commented on integration-cli/docker_cli_logs_test.go
> +func testLogsContainerPagezie(c *check.C, testLen int) {
`Pagezie`? `PageSize`?

2017-01-03 18:54 UTC, thaJeztah commented on integration-cli/docker_cli_run_test.go
>  	testRequires(c, DaemonIsLinux)
Actually; https://github.com/docker/docker/pull/27842

2017-01-03 18:54 UTC, thaJeztah commented on integration-cli/docker_cli_run_test.go
>  	testRequires(c, DaemonIsLinux)
Same here, possibly https://github.com/docker/docker/pull/27842

2017-01-03 18:54 UTC, thaJeztah commented on integration-cli/docker_cli_run_test.go
>  	testRequires(c, DaemonIsLinux)
Although `cgroups` probably doesn't make a lot of sense for Windows 😄

2017-01-03 18:54 UTC, thaJeztah commented on integration-cli/docker_cli_run_test.go
> +	out, _ := dockerCmd(c, "run", "--cpu-percent=80", "--cpu-count=1", "--cpu-shares=1000", "--name", "test", "busybox", "echo", "testing")
Can these actually be combined? https://github.com/docker/docker/blob/9fab262690a1e9c465687b3dc22f84b053c5624f/daemon/daemon_windows.go#L89-L128

2017-01-03 19:40 UTC, aaronlehmann commented on integration-cli/docker_cli_logs_test.go
> +func testLogsContainerPagezie(c *check.C, testLen int) {
`Pagination`?

2017-01-04 07:37 UTC, runshenzhu commented on integration-cli/docker_cli_service_health_test.go
> -func (s *DockerSwarmSuite) TestServiceHealthUpdate(c *check.C) {
@vdemeester it seems that I made a mistake when writing it. Very sorry about it.

2017-01-04 08:47 UTC, vdemeester commented on integration-cli/docker_cli_service_health_test.go
> -func (s *DockerSwarmSuite) TestServiceHealthUpdate(c *check.C) {
@runshenzhu no problem 😉

2017-01-04 08:50 UTC, vdemeester commented on integration-cli/docker_cli_run_test.go
> +	out, _ := dockerCmd(c, "run", "--cpu-percent=80", "--cpu-count=1", "--cpu-shares=1000", "--name", "test", "busybox", "echo", "testing")
arf, I am sad 😓

2017-01-09 10:29 UTC, thaJeztah approved these changes
LGTM

2017-01-14 21:43 UTC, cpuguy83 approved these changes
LGTM

2017-01-14 21:43 UTC, merged