[WIP] 1.13.0 rc5 cherrpicks
moby/moby pull request #29866
Opened 2017-01-03 23:17 UTC by vieux

Add a GetAll function that returns only managed plugins supported by V2 #29665
Fix inspect object by invalid reference #29681
fix swagger description for `DELETE /plugin/{name}` #29707
update experimental/README.md #28160
Add missing "--default-runtime" flag in manpage #29500
Remove bash completion for `docker node ps --all|-a` #29509
Remove `--all|-a` from `docker node ps` reference #29510
Remove bash completion for deprecated `docker daemon` #29551
Add 'volume prune' to the volume commands index #29682
Add bash completion for `plugin install --alias` #29690
Update 'ID' field for 'docker plugin ls' #29701
Fix usage of boltdb in volume restore #29664
commit: do not change container labels on commit #29550

2017-01-04 02:14 UTC, vieux commented
ping @docker/core-engine-maintainers

2017-01-04 02:28 UTC, coolljt0725 commented
@vieux  add https://github.com/docker/docker/pull/29441 and https://github.com/docker/docker/pull/29721 ?

2017-01-04 10:19 UTC, vieux commented
@coolljt0725  #29721  doesn't cherry-pick cleanly, can you open a PR against 1.13.x with the same changes ?

2017-01-04 11:49 UTC, vdemeester commented
Removed #29313 and fixed compilation/test problems in the respective commits 👼

2017-01-04 17:12 UTC, mstanleyjones commented on docs/reference/commandline/dockerd.md
> +	"default-runtime": "runc",
@johndmulhausen do you need to add anything to the dockerd YAML file you made for 1.13 related to this?

2017-01-04 17:13 UTC, mstanleyjones commented on docs/reference/commandline/events.md
> +    2016-07-25T17:30:14.825557616Z plugin pull ec7b87f2ce84330fe076e666f17dfc049d2d7ae0b8190763de94e1f2d105993f (name=tiborvass/sample-volume-plugin:latest)
Remember for 1.13 the docs no longer consume these Markdown files directly but consume YAML files (which read the cobra specifications)  to create the CLI reference.

2017-01-04 17:18 UTC, mdlinville requested changes

2017-01-04 17:18 UTC, mstanleyjones commented on docs/reference/commandline/secret_create.md
> +$ cat secret.json | docker secret create -f - secret.json
Why would you do it this way?? Just `docker secret create -f secret.json secret.json

Also these examples are made more confusing when you call the secret the same as the file name used to create it. So maybe: `docker secret create -f secret.json my_secret`

2017-01-04 17:18 UTC, mstanleyjones commented on docs/reference/commandline/secret_create.md
> +$ docker secret create --file secret.in secret.json
I actually think the file name should be `secret.json` and the secret name should be something else.

2017-01-04 17:18 UTC, mstanleyjones commented on docs/reference/commandline/secret_create.md
> +$ cat secret.json | docker secret create secret.json -f - --label env=dev --label rev=20161102
Again, don't cat the file if you have the `-f` flag available.

2017-01-04 19:01 UTC, tiborvass commented
LGTM

2017-01-04 19:02 UTC, LK4D4 approved these changes
LGTM

2017-01-04 19:04 UTC, merged

2017-01-04 19:04 UTC, tiborvass commented
@mstanleyjones thanks for your input, those will have to be addressed in master first.

2017-01-04 19:57 UTC, mstanleyjones commented
Understood and it was already done in #29889. Thanks!

2017-01-05 20:49 UTC, johndmulhausen commented on docs/reference/commandline/dockerd.md
> +	"default-runtime": "runc",
Most likely; it is [here](https://github.com/docker/docker.github.io/tree/vnext-engine/_data/dockerd-cli) and should probably live over here in docker/docker and get imported via Dockerfile or somesuch

2017-01-05 20:53 UTC, johndmulhausen commented on docs/reference/commandline/dockerd.md
> +	"default-runtime": "runc",
Filed issue https://github.com/docker/docker.github.io/issues/1038