Windows: Enable TestBuildWorkdirImageCmd
moby/moby pull request #29899
Opened 2017-01-04 23:36 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Enables a test introduced in https://github.com/docker/docker/pull/29679 (cherry-picked to 1.13 RC5) on Windows.

@yongtang FYI.

2017-01-05 04:30 UTC, yongtang commented
Thanks @jhowardmsft. The failed test `TestSwarmAlternateLockUnlock` seems to be unrelated.

There was another mentioning of the same flaky test in https://github.com/docker/docker/pull/29441#issuecomment-267916528

```
00:33:15 ----------------------------------------------------------------------
00:33:15 FAIL: docker_cli_swarm_test.go:1300: DockerSwarmSuite.TestSwarmAlternateLockUnlock
00:33:15 
00:33:15 [df3296ab022c4] waiting for daemon to start
00:33:15 [df3296ab022c4] daemon started
00:33:15 
00:33:15 [df3296ab022c4] exiting daemon
00:33:15 [df3296ab022c4] waiting for daemon to start
00:33:15 [df3296ab022c4] daemon started
00:33:15 
00:33:15 docker_cli_swarm_test.go:1323:
00:33:15     c.Assert(err, checker.IsNil, check.Commentf("out: %v", string(out)))
00:33:15 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420a880c0), Stderr:[]uint8(nil)} ("exit status 1")
00:33:15 ... out: Error response from daemon: swarm component could not be started: can't initialize raft node: failed to open WAL: fileutil: file already locked
00:33:15 
00:33:15 
00:33:15 [df3296ab022c4] exiting daemon
00:33:44 
00:33:44 ----------------------------------------------------------------------
```

2017-01-05 08:44 UTC, vdemeester approved these changes
LGTM 🐸

2017-01-05 10:41 UTC, thaJeztah requested changes

2017-01-05 10:41 UTC, thaJeztah commented on integration-cli/docker_cli_build_test.go
> +	// The Windows busybox image has a blank `cmd`
hm, two questions;

- is there a reason the `busybox` image on Windows does not have a default `cmd`? Seems rather inconsistent
- by checking for `null`, is this still properly validating that setting a `WORKDIR` does not overwrite the original `CMD`?

Should we use a different image that originally _had_ a `CMD` instead? (perhaps the `hello-world` image works?)

2017-01-05 17:08 UTC, jhowardmsft commented on integration-cli/docker_cli_build_test.go
> +	// The Windows busybox image has a blank `cmd`
Completely orthogonal.... the issue is that the cmd is overwritten, not what the default value is to start with. If you revert 29679, you can see that the test is valid as CMD is being overwritten incorrectly by the WORKDIR statement as shown below:

```
----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:7318: DockerSuite.TestBuildWorkdirImageCmd

docker_cli_build_test.go:7334:
    c.Assert(strings.TrimSpace(out), checker.Equals, lookingFor)
... obtained string = "[\"cmd\",\"/S\",\"/C\",\"#(nop) WORKDIR C:\\\\foo\\\\bar\"]"
... expected string = "null"

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (2.29s)
FAIL
exit status 1
FAIL    github.com/docker/docker/integration-cli        2.492s
```

2017-01-06 16:15 UTC, thaJeztah commented on integration-cli/docker_cli_build_test.go
> +	// The Windows busybox image has a blank `cmd`
Oh, you're right, it wasn't reset, it was changed, my fault.

(was just curious about the `busybox` image :D)

2017-01-06 16:15 UTC, thaJeztah approved these changes
LGTM

2017-01-06 16:15 UTC, merged