docs/api: document the /logs endpoint wire format
moby/moby pull request #29897
Opened 2017-01-04 22:28 UTC by ahmetalpbalkan

This was not documented anywhere. So I'm adding a piece of explanation about the `/logs` endpoint response format. I am not sure if this is covered under any API guarantee (or documenting it makes it as such).

2017-01-05 08:43 UTC, vdemeester requested changes
Thanks @ahmetalpbalkan 👼
I think the `swagger.yaml` should also be updated as it's what generates the docs for newer API version.

/cc @thaJeztah

2017-01-05 17:39 UTC, ahmetalpbalkan commented
@vdemeester will it generate the v1.25 or does v1.24 come from swagger, too? For instance the "Example request/response" sections in the current documentation are not present in api/swagger.yml.

2017-01-10 02:59 UTC, stevvooe commented
@ahmetalpbalkan There is some other tricky stuff about attributes and timestamps. I had to reverse engineer this in https://github.com/docker/swarmkit/blob/master/agent/exec/container/controller.go#L497.

2017-01-10 03:02 UTC, stevvooe commented
@ahmetalpbalkan Also, checkout the oneliner decode...

2017-01-10 16:51 UTC, thaJeztah commented
> will it generate the v1.25 or does v1.24 come from swagger, too? 

Only the 1.25 docs (and up) will come from swagger

> For instance the "Example request/response" sections in the current documentation are not present in api/swagger.yml.

Yes, I was looking at that.

ping @dnephin @bfirsh could you have a look? I tried to add examples (e.g. set some query parameters in the swagger.yml), but couldn't make those show up in the generated docs

2017-01-10 20:58 UTC, ahmetalpbalkan commented
@stevvooe off topic: doesn't this cause a bug if the arch running the program is little endian?

    size := header & ^(uint64(0xFF)<<(7<<3))

2017-01-10 22:09 UTC, stevvooe commented
@ahmetalpbalkan The endian conversion happens at https://github.com/docker/swarmkit/blob/master/agent/exec/container/controller.go#L489. This works because we use shifts, which are endian independent, to locate the MSB. I think there may be a missing mask to uint32.

I don't have a bigendian machine to test on, so I may be wrong.

2017-01-11 11:03 UTC, bfirsh commented
Yep - swagger.yaml is where this lives now, and I made an attempt at improving the documentation for the binary format while moving the docs. See: https://github.com/docker/docker/blob/24e9ac15759cc23caf90383b5ea6de79af4363a0/api/swagger.yaml#L3759

For documenting requests/responses, there are response examples for pretty much all endpoints, and example parameters can be specified with the `example` key on each parameter. Unfortunately there isn't a good way of providing a complete example request, but we could build an extension for ReDoc if we wanted that.

2017-01-11 11:12 UTC, thaJeztah commented
@bfirsh Yes, I tried to add query parameters to an example (e.g. https://github.com/docker/docker/blob/24e9ac15759cc23caf90383b5ea6de79af4363a0/api/swagger.yaml#L2474-L2477), but adding `size: true` does not make `?size=true` / `?size=1` show up in the example request.

I _would_ expect that to be the case (as it provides useful information as to what parameters are / should be used, and what format they take)

2017-01-11 18:34 UTC, ahmetalpbalkan commented
Looks like @bfirsh's documentation is sufficient (although it's not on /logs but /attach), I'll go ahead and close this. Perhaps a note can be added on /logs to refer to /attach for the wire format.

2017-01-11 18:34 UTC, closed without merging