CONTRIBUTING: add tips for succesful changes
moby/moby pull request #30041
Opened 2017-01-11 00:04 UTC by stevvooe

Expand the contributing doc to include tips for successful PRs and
guidance on commit messages. This should help contributers to have
better position PRs that are more likely to be merged.

Signed-off-by: Stephen J Day <stephen.day@docker.com>

2017-01-17 17:11 UTC, thaJeztah requested changes
thanks @stevvooe, this is a welcome addition. I left some comments / suggestions

2017-01-17 17:11 UTC, thaJeztah commented on CONTRIBUTING.md
> +We ask that before contributing, please make the effort to coordinate with the
you can skip `We ask that`

```Markdown
Before contributing large or high impact changes, make the effort to coordinate with the
maintainers of the project before submitting a pull request. This prevents you from doing
extra work that may or may not be merged.
```

2017-01-17 17:11 UTC, thaJeztah commented on CONTRIBUTING.md
> +frivelous, say so.
s/frivelous/frivolous/

2017-01-17 17:11 UTC, thaJeztah commented on CONTRIBUTING.md
> +are accomplished through communication of the design goals and subsqeuent
s/subsqueuent/subsequent/

2017-01-17 17:11 UTC, thaJeztah commented on CONTRIBUTING.md
> +
Should we mention reasons for having the _commit_ message good? i.e. explain the PR's description on GitHub **is not** sufficient, as it's not preserved in Git history.

Likewise, when referring to a related change in your commit message, refer (not only to) the related pull-request, but to the _commit_ that made the change.

2017-01-17 21:12 UTC, stevvooe commented on CONTRIBUTING.md
> +
I don't think we need to get too specific here. Let's see if we can't first get better commit messages.

2017-01-17 21:16 UTC, stevvooe commented
@thaJeztah Updated.

2017-01-17 22:15 UTC, thaJeztah approved these changes
LGTM, thanks!!

2017-01-17 22:15 UTC, thaJeztah commented
ping @vdemeester for review/merge

2017-01-17 22:16 UTC, thaJeztah commented on CONTRIBUTING.md
> +
Definitely 👍

2017-01-18 08:59 UTC, vdemeester approved these changes
LGTM 🦁 😍

2017-01-18 09:00 UTC, merged