fix typo in pkg/archive/archive_test.go
moby/moby pull request #30165
Opened 2017-01-14 14:16 UTC by xulike666

Signed-off-by: Aaron.L.Xu <likexu@harmonycloud.cn>

**- What I did**

[Newbie Task : 6/36]

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-01-14 14:26 UTC, thaJeztah commented
@xulike666 would it be possible to combine your fixes to a single PR?

2017-01-14 14:44 UTC, xulike666 commented
@thaJeztah , thanks for your suggestion.  My subjective willingness is to combine those boring  bothersome typo fixes for sure but my superiors who are so care about the number of commits for docker community which is 36 in my case. Apologize for next 30 typo-fix pr and from a different perspective，I'm try to sketch the whole project structure for my No.37 worthwhile contribution.

2017-01-14 15:48 UTC, AkihiroSuda approved these changes
LGTM

2017-01-14 15:49 UTC, runcom commented
LGTM

2017-01-14 15:54 UTC, AkihiroSuda commented
But please squash next 30 planned typo fixes? 😅

2017-01-14 16:19 UTC, xulike666 commented
Well gentlemen, I have already hack a fix-typo-pr-bot for this kind of daily PRs and won't put the next 'episode' out in this LGTM.

2017-01-14 16:42 UTC, thaJeztah commented
@xulike666 "number of commits" should not be a metric. Although we appreciate your contributions, also keep in mind that each PR will at least result in 6 machines (three on the PR, three or more on "master") running CI for an hour each

2017-01-14 16:58 UTC, xulike666 commented
@thaJeztah, nice guider !  As a freshman, I'd like to squash my typo-related contributions into one pr ASAP and apologize for wasting computing resources.

2017-01-14 17:04 UTC, thaJeztah commented
> I'd like to squash my typo-related contributions into one pr 

That'd be appreciated

> apologize for wasting computing resources

Well, they're there to be running, but could delay other PR's from getting merged. Overall "measuring performance" just by looking at number of commits is _not_ the way (not your fault, but something for your superiors to rethink); Contributing is _more_ than just generating commits; looking into bugs, trying to reproduce those, or assisting others are great way to contribute, just less easy to "measure", but not less appreciated.

2017-01-17 03:43 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "fix-typo-6/36" git@github.com:xulike666/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354747896
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-01-17 03:57 UTC, xulike666 commented
@AkihiroSuda, sorry for the delay in this pr and I rebase and push all my typo errors  I found  in these days .

2017-01-17 04:18 UTC, AkihiroSuda requested changes
Please omit unrelated commits

2017-01-17 09:28 UTC, allencloud commented on pkg/term/term_windows.go
> +// StdStreams returns the standard streams (stdin, stdout, stderr).
I also found that in file `pkg/term/term.go#L34` there is a same typo.
Could you please combine that in this single PR?

2017-01-17 09:30 UTC, allencloud commented on integration-cli/docker_api_exec_test.go
> +	testRequires(c, DaemonIsLinux) // Uses pause/unpause but bits may be salvageable to Windows to Windows CI
also found in `pkg/archive/copy_unix_test.go#L3`

2017-01-17 09:34 UTC, AkihiroSuda commented
And please sign your commit

2017-01-19 07:31 UTC, allencloud commented
That is great. Thanks for your work. While I think it would be better if you could help to squash the 3 commits into a single one. @xulike666

2017-01-19 08:12 UTC, AkihiroSuda approved these changes
LGTM if green

2017-01-19 16:21 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-01-19 16:21 UTC, merged