fix flag descriptions for content-trust
moby/moby pull request #30211
Opened 2017-01-17 14:49 UTC by thaJeztah

Commit ed13c3abfb242905ec012e8255dc6f26dcf122f6 (https://github.com/docker/docker/pull/14546) added flags for Docker Content Trust. Depending on the `verify` boolean, the message is "Skip image verification", or "Skip image signing". "Signing" is intended for `docker push` / `docker plugin push`.

During the migration to Cobra, this boolean got flipped for `docker push` (9640e3a4514f96a890310757a09fd77a3c70e931 https://github.com/docker/docker/pull/23256), causing `docker push` to show the incorrect flag description.

This patch changes the flags to use the correct description for `docker push`, and `docker plugin push`.

/cc @vdemeester @dmcgowan PTAL

2017-01-17 15:28 UTC, vdemeester approved these changes
ohhh 😅 
LGTM 🐻

2017-01-17 19:47 UTC, dmcgowan commented
LGTM

test failing on trust related commands but message is about timeout and panic, going to try a rebuild

2017-01-18 16:39 UTC, cpuguy83 commented
And we see why boolean arguments are not good here 😉 
Can we change these calls to `AddTrustSigningFlags` and `AddTrustVerificationFlags` that can handle these differences in the packages public API?

2017-01-18 16:50 UTC, thaJeztah commented
@cpuguy83 yeah, I actually was looking at some alternative approaches, also for the `--disable-content-trust (default true)`, which is awkward from a UX perspective. I decided to open this quick fix first, and look at further improvements later, but if you think it's best to include it in this PR, I'll update.

2017-01-18 17:43 UTC, cpuguy83 commented
@thaJeztah If the intention is to have a quick fix for 1.13.1 then this is fine, else I think we should fix.

2017-01-22 22:31 UTC, thaJeztah commented
@cpuguy83 @vdemeester updated; added an `AddTrustSigningFlags()` function and dropped the boolean

2017-01-23 08:58 UTC, vdemeester approved these changes
LGTM 🐸

2017-01-23 13:48 UTC, cpuguy83 requested changes

2017-01-23 13:48 UTC, cpuguy83 commented on cli/command/container/create.go
> +	command.AddTrustedFlags(flags)
Can we change this to `AddTrustVerificationFlags`?

2017-01-23 13:50 UTC, thaJeztah commented on cli/command/container/create.go
> +	command.AddTrustedFlags(flags)
sure, let me change :smile:

2017-01-23 13:53 UTC, thaJeztah commented on cli/command/container/create.go
> +	command.AddTrustedFlags(flags)
done! Enjoying Gogland quite a bit for that 👍

2017-01-23 13:58 UTC, cpuguy83 approved these changes
LGTM

2017-01-23 22:52 UTC, merged