fix a typo error
moby/moby pull request #30218
Opened 2017-01-17 16:30 UTC by kevinetc123

Signed-off-by: kaiwentan <kaiwentan@harmonycloud.cn>

**- What I did**
fix a typo mistake. formater -> formatter
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-01-17 16:37 UTC, allencloud commented on cli/command/formatter/disk_usage.go
> +// DiskUsageContext contains disk usage specific information required by the formatter, encapsulate a Context struct.
also found in https://github.com/docker/docker/blob/master/cli/command/formatter/image.go#L23,
could you update that as well?

2017-01-18 11:22 UTC, kevinetc123 commented on cli/command/formatter/disk_usage.go
> +// DiskUsageContext contains disk usage specific information required by the formatter, encapsulate a Context struct.
Sorry It's my negligence. I will correct all the 'formater'.

2017-01-18 11:49 UTC, allencloud commented on cli/command/formatter/disk_usage.go
> +// DiskUsageContext contains disk usage specific information required by the formatter, encapsulate a Context struct.
Thanks for your contribution. I saw you fixed that place as well. 
Maybe still something for us to do. Could you squash the two commits in this PR into a single one?

2017-01-18 14:32 UTC, thaJeztah requested changes
changes LGTM, but can you squash your commits, as @allencloud asked?

2017-01-19 03:20 UTC, kevinetc123 commented
ok

2017-01-19 05:29 UTC, allencloud commented
Oh, that is much better now. Thanks a lot @kevinetc123

2017-01-19 05:33 UTC, AkihiroSuda approved these changes
LGTM

2017-01-19 05:34 UTC, merged