fix some ineffectual assignments (and minor fixes)
moby/moby pull request #30227
Opened 2017-01-18 02:19 UTC by thaJeztah

To make [goreportcard](https://goreportcard.com/report/github.com/docker/docker) a bit happier

Also found that

- `TestCpToErrDstParentNotExists()` was partially broken, because a `runDockerCp()` was inadvertently removed in f26a31e80cfcc77daba0872ddb14bf03f4398311
- `TestDaemonRestartSaveContainerExitCode()` didn't verify the actual _Error_ message, so added that to the test.
- `TestVolumeCLICreateOptionConflict()` only checked for an error to occur, but didn't validate if the error was due to conflicting options.

**- How to verify it**

Wait for Janky to (hopefully) become 💚

2017-01-18 02:19 UTC, thaJeztah commented
/cc @vdemeester :smile:

2017-01-18 02:20 UTC, stevvooe commented on integration-cli/docker_cli_build_unix_test.go
> -	stdoutBuild, err := buildCmd.StdoutPipe()
Should this not be checked?

2017-01-18 02:20 UTC, stevvooe commented on integration-cli/docker_cli_pull_local_test.go
> +	outImageCmd, _, _ := dockerCmdWithError("images", repo)
Check error here?

2017-01-18 02:21 UTC, stevvooe commented on pkg/ioutils/buffer_test.go
> +	_, err = buf.Write(bytes.Repeat([]byte{1}, 64))
`n` should be checked here to have the partial write before `errBufferFull`, allowing the caller to recover the amount written.

2017-01-18 02:22 UTC, stevvooe commented
@thaJeztah I wonder if there are cases where we should remove the error return from some of these util functions and just fail the test if they experience an error. That might be a much bigger PR.

2017-01-18 02:25 UTC, thaJeztah commented
@stevvooe I think @vdemeester is working on some of those (create utility functions that automatically fail the test). Let me check your comments; I mainly remove unused variables, but I can add a check for some that are important.

Lot's of tests need a cleanup (and a better description what they're testing, as it's not always clear without checking git log)

2017-01-18 09:14 UTC, vdemeester requested changes
Two comments, otherwise 👍

2017-01-18 09:14 UTC, vdemeester commented on integration-cli/docker_cli_pull_local_test.go
> +	outImageCmd, _, _ := dockerCmdWithError("images", repo)
Hum we could even use `dockerCmd(c, "images", repo)` here so no need to check errors 👼

2017-01-18 09:14 UTC, vdemeester commented on integration-cli/docker_cli_run_test.go
> +	out, _, _ = dockerCmdWithStdoutStderr(c, "run", "--dns=127.0.0.1", "--dns-search=.", "--dns-opt=ndots:3", "busybox", "cat", "/etc/resolv.conf")
Here too, I think `dockerCmd` would be better here (I don't think the test should care about stdout vs stderr).

2017-01-18 14:51 UTC, thaJeztah commented on integration-cli/docker_cli_run_test.go
> +		c.Fatalf("expected 'nameserver 1.1.1.1 options ndots:3', but says: %q", actual)
changed to `1.1.1.1` to prevent the "local DNS" warning 😇

2017-01-18 19:40 UTC, tophj-ibm commented on integration-cli/docker_cli_external_volume_driver_unix_test.go
> +	c.Assert(out, checker.Equals, "Conflicting options: either specify --name or provide positional arg, not both")
fyi janky is complaining because you need a newline at the end of the comparison string.

2017-01-18 20:56 UTC, thaJeztah commented on integration-cli/docker_cli_external_volume_driver_unix_test.go
> +	c.Assert(out, checker.Equals, "Conflicting options: either specify --name or provide positional arg, not both")
oh! thx, must've overlooked that failure :blush:

2017-01-19 11:00 UTC, thaJeztah commented
Restarting the build, but looks like there may be some flakyness; i.e., `docker`
did not detect that the container failed to be created). On experimental,
CI failed (running on ubuntu-1404 (aufs) (i-01705da2e6f18987e))'

- https://jenkins.dockerproject.org/job/Docker-PRs-experimental/29784/
- https://jenkins.dockerproject.org/job/Docker-PRs-experimental/29784/console

The logs of the `"error-values"` container show;

```
{"log":"exec toto failed: No such file or directory\n","stream":"stderr","time":"2017-01-19T00:44:30.539268469Z"}
```

But looks like docker did not get that error;

```
00:44:30 ----------------------------------------------------------------------
00:44:30 FAIL: docker_cli_daemon_test.go:2564: DockerDaemonSuite.TestDaemonRestartSaveContainerExitCode
00:44:30 
00:44:30 [d6c4aa715e5f0] waiting for daemon to start
00:44:30 [d6c4aa715e5f0] daemon started
00:44:30 
00:44:30 docker_cli_daemon_test.go:2581:
00:44:30     c.Assert(errMsg1, checker.Contains, "executable file not found")
00:44:30 ... obtained string = ""
00:44:30 ... substring string = "executable file not found"
00:44:30 
00:44:30 [d6c4aa715e5f0] exiting daemon
00:44:33 
```

<details>
<summary>Relevant logs from the integration-ci daemon</summary>

```
time="2017-01-19T00:44:30.094864500Z" level=debug msg="Calling POST /v1.26/containers/create?name=error-values" 
time="2017-01-19T00:44:30.095172313Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"toto\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"busybox\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}" 
time="2017-01-19T00:44:30.096795091Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231-init" 
time="2017-01-19T00:44:30.096834517Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/06baf30096b1c05b7f51e3a6cbd2f12185fb8c3d46e70b1105ec05bf98335471, /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231-init)" 
time="2017-01-19T00:44:30.096848449Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/06baf30096b1c05b7f51e3a6cbd2f12185fb8c3d46e70b1105ec05bf98335471 /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231-init)" 
time="2017-01-19T00:44:30.162061653Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231" 
time="2017-01-19T00:44:30.162104009Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231-init, /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231)" 
time="2017-01-19T00:44:30.162124520Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231-init /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231)" 
time="2017-01-19T00:44:30.344739387Z" level=debug msg="container mounted via layerStore: /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231" 
time="2017-01-19T00:44:30.350601536Z" level=debug msg="Calling POST /v1.26/containers/911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108/attach?stderr=1&stdout=1&stream=1" 
time="2017-01-19T00:44:30.350753868Z" level=debug msg="attach: stdout: begin" 
time="2017-01-19T00:44:30.350795645Z" level=debug msg="attach: stderr: begin" 
time="2017-01-19T00:44:30.351116360Z" level=debug msg="Calling GET /v1.26/events?filters=%7B%22container%22%3A%7B%22911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D" 
time="2017-01-19T00:44:30.351643285Z" level=debug msg="Calling POST /v1.26/containers/911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108/start" 
time="2017-01-19T00:44:30.352061577Z" level=debug msg="container mounted via layerStore: /go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/d6c4aa715e5f0/root/vfs/dir/c615e23eeadb4ab1ce8fbf63c3a9ce8942182bad8be82ddae0512df3bd271231" 
time="2017-01-19T00:44:30.352323496Z" level=debug msg="Assigning addresses for endpoint error-values's interface on network bridge" 
time="2017-01-19T00:44:30.352346210Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])" 
time="2017-01-19T00:44:30.354889911Z" level=debug msg="Assigning addresses for endpoint error-values's interface on network bridge" 
time="2017-01-19T00:44:30.365863177Z" level=debug msg="Programming external connectivity on endpoint error-values (f36a5f77a49df8ee8ceecb2664240eb4feb6d555469e29d0f9df84efce041453)" 
time="2017-01-19T00:44:30.470606259Z" level=debug msg="sandbox set key processing took 37.527657ms for container 911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108" 
time="2017-01-19T00:44:30.539864517Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc4212240e0)}" 
time="2017-01-19T00:44:30.553910970Z" level=debug msg="libcontainerd: event unhandled: type:\"start-container\" id:\"911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108\" timestamp:<seconds:1484786670 nanos:538836799 > " 
time="2017-01-19T00:44:30.579045198Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"911b0d18c478b9016d97f373e3f51442b6e9564f0357b1403f56754d0d8c9108\", Status:0x7f, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc421224360)}" 
time="2017-01-19T00:44:30.579222125Z" l [...]

2017-01-20 01:44 UTC, thaJeztah commented
ping @mlaventure could you have a look at this failing test? It looks like it always fails on experimental, but not on janky. I can find the test to pass, but the change in the test may have exposed an actual issue (see my previous comment)

2017-01-20 19:41 UTC, tonistiigi commented
This PR changes it so the error message is also checked but the error message is different between janky/experimental because experimental uses `--init`. One hacky way to fix it would be https://github.com/docker/docker/pull/26061#discussion-diff-77089604 . Could probably work around it in test if we don't think this is important enough. In case of the init script the errors is in stdout of the container.

2017-01-24 08:51 UTC, thaJeztah commented
> In case of the init script the errors is in stdout of the container.

@tonistiigi that sounds odd; isn't that actually a _bug_ ? Is it expected behavior that `stderr` output is moved to `stdout` if `--init` is used?

2017-01-24 09:19 UTC, thaJeztah commented
Ok, so behavior differences between `docker run`, and `docker run` with `--init` is;

```bash
$ docker run --name without-init busybox toto 2> stderr.txt 1> stdout.txt

$ cat stdout.txt
# (empty)

$ cat stderr.txt
# docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"toto\": executable file not found in $PATH".

$ docker inspect --format '{{.State.Error}}' without-init
# oci runtime error: container_linux.go:247: starting container process caused "exec: \"toto\": executable file not found in $PATH"

```

Now, using with `--init`;

```bash
$ docker run --name with-init --init busybox toto 2> stderr.txt 1> stdout.txt

$ cat stdout.txt
# (empty)

$ cat stderr.txt
# exec toto failed: No such file or directory

$ docker inspect --format '{{.State.Error}}' with-init
# (empty)

```

If we want to make the `--init` transparent to the user, I wonder if we can change that

2017-01-24 09:22 UTC, thaJeztah commented
Right, I see this was discussed here as well; https://github.com/docker/docker/pull/26061#r78054578

> If we run the tests with this feature enabled these two will fail because they check that the cmd passed does not exist and it will always exist because we prepend our init.

> It will still exit with a 127 but not at start time. I tried looking through the history to see why these these were added but I couldn't find anything.

> We went over this same discussion in the runc change for 1.11 and I said that if we were to ever solve the zombie problem this is not going to work. We get the same outcome, the containers fails with 127 exit status but it does not return the error on start.

2017-01-24 10:17 UTC, thaJeztah commented on integration-cli/docker_cli_daemon_test.go
> +	out, err := s.d.Cmd("run", "--name", containerName, "--init=false", "busybox", "toto")
I disabled `--init` on this test so that it passes on "experimental", also added a description "why"

2017-01-24 10:36 UTC, vdemeester approved these changes
LGTM 🐸

2017-01-25 00:47 UTC, thaJeztah commented
ping @stevvooe ptal 👍

2017-01-25 01:46 UTC, stevvooe commented
LGTM

2017-01-25 01:49 UTC, merged