Fix incorrect `Scope` in `network ls/inspect` with duplicate network names
moby/moby pull request #30250
Opened 2017-01-18 15:59 UTC by yongtang

**- What I did**

This fix tries to address the issue raised in comment https://github.com/docker/docker/issues/30242#issuecomment-273468307 where the `Scope` field always changed to `swarm` in the ouput of `docker network ls/inspect` when duplicate network name exists.

The reason for the issue was that `buildNetworkResource()` use network name
(which may not be unique) to check for the scope.

**- How I did it**

This fix fixes the issue by always use network ID in `buildNetworkResource()`.

**- How to verify it**

A test has been added. The test fails before the fix and passes after the fix.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

![j3iz7jp](https://cloud.githubusercontent.com/assets/6932348/22071405/e9f69a0c-dd53-11e6-94f7-aa89ab7ca160.jpg)

This fix fixes #30242.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-01-18 16:04 UTC, allencloud commented
I am a super fan of you, @yongtang 
😆 ❤️

2017-01-18 16:44 UTC, aboch commented
Looks good to me

2017-01-19 06:35 UTC, chanwit commented
thank you @yongtang, you're awesome!
non-maintainer LGTM, both codes and the test case.

ping @thaJeztah I think you know who should review this PR :-)

2017-01-19 17:46 UTC, thaJeztah requested changes
one nit/suggestion for the tests, but LGTM otherwise

2017-01-19 19:48 UTC, yongtang commented on integration-cli/docker_api_swarm_test.go
> +	out1, err := d.Cmd("network", "inspect", "--format", "{{.Scope}}", n1.ID)
Thanks @thaJeztah for the review. The PR has been updated with API used. Please take a look.

2017-01-19 21:01 UTC, thaJeztah approved these changes
LGTM (if green), thanks!

2017-01-26 16:38 UTC, allencloud commented
It is great to see all greens. 😄 
ping @thaJeztah

2017-01-26 18:11 UTC, merged