Add `shorten` function for Go templates
moby/moby pull request #30484
Opened 2017-01-26 21:10 UTC by yongtang

This fix is part of the discussion in #28199 about using `shorten` to replace `--no-trunc`.

As part of the fix, a new function `shorten` has been added for Go templates so that it is possible to use
```
docker stack services --format "{{.ID | shorten}}: {{.Mode}} {{.Replicas}}"
```
to show short ID.

A unit test has been added.

This fix is related to #28199.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-01-27 15:25 UTC, vdemeester reviewed
Design LGTM 🐮
/cc @thaJeztah @dnephin @cpuguy83 @tiborvass @AkihiroSuda @runcom @icecrime

2017-01-27 16:44 UTC, dnephin commented
LGTM

2017-01-27 16:50 UTC, dnephin reviewed
The tests could use the assertion helpers. I think it makes them a lot easier to read when they are shorter.

The error messages are also consistent that way, and include things like "Expected no error, but got: ..."

2017-01-27 16:50 UTC, dnephin commented on pkg/templates/templates_test.go
> +	}
```go
assert.NilError(t, err)
```

2017-01-27 16:50 UTC, dnephin commented on pkg/templates/templates_test.go
> +	}
```go
assert.NilError(t, tm.Execute(&b, "tupx5xzf6hvsrhnruz5cr8gwp"))
```

2017-01-27 16:50 UTC, dnephin commented on pkg/templates/templates_test.go
> +	}
```go
assert.Equal(t, b.String(), "tupx5xzf6hvs")
```

2017-01-27 16:52 UTC, cpuguy83 requested changes

2017-01-27 16:52 UTC, cpuguy83 commented on pkg/templates/templates.go
> +	"shorten": stringid.TruncateID,
Since this works on any string, I think it should take an integer argument to shorten to a certain length

2017-01-27 16:53 UTC, cpuguy83 commented on pkg/templates/templates.go
> +	"shorten": stringid.TruncateID,
That is not to say that `TruncateID` should take an argument ;)

2017-01-27 16:53 UTC, vdemeester commented on pkg/templates/templates.go
> +	"shorten": stringid.TruncateID,
Oh good point 👍

2017-01-27 21:21 UTC, yongtang commented
Thanks @dnephin the PR has been updated with unit tests using assertion helpers. Other tests in `pkg/templates/templates_test.go` has also been updated to use it. (not necessarily related to `shorten` but the change is small enough).

2017-01-27 21:22 UTC, yongtang commented
Thanks @cpuguy83 @vdemeester for the comment. Now `shorten` takes the int for the max length of the truncation. Please take a look.

2017-01-27 21:25 UTC, cpuguy83 approved these changes
LGTM

2017-01-27 21:54 UTC, dnephin approved these changes
LGTM

2017-01-27 22:16 UTC, stevvooe commented
The correct word your looking for is `truncate`.

2017-01-28 01:41 UTC, thaJeztah commented
I agree that `truncate` would be better; it's also consistent with the current `--no-trunc` flag, so easier to explain that they relate.

Moving it back to design for a bit

2017-01-28 01:46 UTC, yongtang commented
We currently have 
```
	"json":
	"split"
	"join"
	"title"
	"lower"
	"upper"
	"pad"
```
I am thinking maybe we could consider `trunc`?
It seems `truncate` is a litter long compared with other functions. Though either is fine for me.

2017-01-30 19:05 UTC, tiborvass commented
👍 for `truncate`.

2017-01-30 21:36 UTC, yongtang commented
Thanks all for the review. The PR has been updated with `truncate`. The title and description of the PR has also been updated. Please take a look.

2017-01-31 20:55 UTC, LK4D4 approved these changes
LGTM

2017-01-31 20:55 UTC, LK4D4 commented
@cpuguy83 @dnephin @thaJeztah @vdemeester feel free to merge.

2017-01-31 20:56 UTC, vdemeester approved these changes
LGTM 🎉

2017-01-31 20:56 UTC, merged