Add markdown for man page of `docker plugin ls`
moby/moby pull request #30645
Opened 2017-02-01 19:31 UTC by yongtang

This fix adds markdown for man page of `docker plugin ls`,
based on the feedback https://github.com/docker/docker/pull/28627#issuecomment-276731752

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

/cc @thaJeztah

2017-02-01 23:14 UTC, thaJeztah requested changes
Thanks! left some comments

2017-02-01 23:14 UTC, thaJeztah commented on man/src/plugin/ls.md
> +# Display all plugins
can you make this a H2 (`##`)? Same for the others below

2017-02-01 23:14 UTC, thaJeztah commented on man/src/plugin/ls.md
> +    # docker plugin ls
lets use an unprivileged prompt (`$`) here like we do for the online docs (we should probably update other man-pages as well) - also for the other examples below

2017-02-02 02:40 UTC, yongtang commented on man/src/plugin/ls.md
> +# Display all plugins
Thanks @thaJeztah the PR has been updated.

2017-02-02 02:41 UTC, yongtang commented on man/src/plugin/ls.md
> +    # docker plugin ls
@thaJeztah Done. Also another PR has been #30660 created to cover other markdown files. Please take a look.

2017-02-02 07:14 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-02-02 09:42 UTC, vdemeester approved these changes
LGTM 🐸

2017-02-02 09:42 UTC, merged