docker deploy stack command
moby/moby pull request #30664
Opened 2017-02-02 06:01 UTC by huangyanxiong01

Signed-off-by: huangyanxiong <huangyanxiong2013@gmail.com>

**- What I did**
specify a name for the docker deploy stack command
**- How I did it**
Replace `docker deploy vossibility-stack` with `docker deploy --bundle-file vossibilitystack.dab vossibility` in experimental/docker-stacks-and-bundles.md
**- How to verify it**
:eyes:
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-02-02 06:14 UTC, AkihiroSuda requested changes

2017-02-02 06:14 UTC, AkihiroSuda commented on experimental/docker-stacks-and-bundles.md
> +```s
typo?

2017-02-02 06:17 UTC, AkihiroSuda commented
Also, please consider carrying https://github.com/docker/docker/pull/30016 with https://github.com/docker/docker/pull/30016#pullrequestreview-15862225 ?

(cc @lixiaobing10051267 )

2017-02-03 05:21 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:huangyanxiong01/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354218472
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-02-03 07:52 UTC, huangyanxiong01 commented on experimental/docker-stacks-and-bundles.md
> +```s
sorry,I have already updated

2017-02-04 02:13 UTC, thaJeztah requested changes
Let a comment, also, please squash your commits

2017-02-04 02:13 UTC, thaJeztah commented on experimental/docker-stacks-and-bundles.md
> +# docker deploy --bundle-file vossibilitystack.dab vossibility
The `--bundle-file` doesn't match the output below, which says:

```
Loading bundle from vossibility-stack.dab
```

Also, the _name_ given (see the output below) is `vossibility-stack`, not `vossibility`


So this should be:

```bash
$ docker deploy --bundle-file vossibility-stack.dab vossibility-stack
```

2017-02-07 14:16 UTC, vdemeester commented
Carrying into #30789

2017-02-07 14:16 UTC, closed without merging

2017-02-10 14:33 UTC, huangyanxiong01 commented on experimental/docker-stacks-and-bundles.md
> +# docker deploy --bundle-file vossibilitystack.dab vossibility
Thank you for correcting