Allow `--format` to use different delim in `table` format
moby/moby pull request #30733
Opened 2017-02-04 04:28 UTC by yongtang

**- What I did**

This fix is an attempt to address https://github.com/docker/docker/pull/28213#issuecomment-273840405

Currently when specify table format with table `--format "table {{.ID}}..."`, the delimiter in the header section of the table is always `"\t"`. That is actually different from the content of the table as the delimiter could be anything (or even contatenated with `.`, for example):
```
$ docker service ps web --format 'table {{.Name}}.{{.ID}}' --no-trunc

NAME                ID
web.1.inyhxhvjcijl0hdbu8lgrwwh7
 \_ web.1.p9m4kx2srjqmfms4igam0uqlb
```

**- How I did it**

This fix is an attampt to address the skewness of the table when delimiter is not `"\t"`.

The basic idea is that, when header consists of `table` key, the header section will be redendered the same way as content section. A map mapping each placeholder name to the HEADER entry name is used for the context of the header.

**- How to verify it**

Unit tests have been updated and added to cover the changes.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

This fix is related to #28313.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-02-04 22:04 UTC, yongtang commented
/cc @thaJeztah

2017-02-06 10:32 UTC, vdemeester requested changes

2017-02-06 10:32 UTC, vdemeester commented on cli/command/formatter/disk_usage_test.go
> +	//"encoding/json"
Comments ? 👼

2017-02-06 10:32 UTC, vdemeester commented on cli/command/formatter/image.go
> +	imageCtx := imageContext{}
I think those are not required as you use `newImageContext` just after 👼

2017-02-06 10:32 UTC, vdemeester commented on cli/command/formatter/volume.go
> +func (c volumeHeaderContext) Label(name string) string {
Thinking outloud 🤔 but I think these are duplicated a lot, we might be able to do some "refactoring" 👼

2017-02-07 04:00 UTC, yongtang commented on cli/command/formatter/disk_usage_test.go
> +	//"encoding/json"
My bad. Thanks. The PR has been updated.

2017-02-07 04:00 UTC, yongtang commented on cli/command/formatter/image.go
> +	imageCtx := imageContext{}
@vdemeester My bad again. Thanks for pointing out. Updated.

2017-02-07 04:04 UTC, yongtang commented on cli/command/formatter/volume.go
> +func (c volumeHeaderContext) Label(name string) string {
@vdemeester I think it might be possible to refactoring. Though it looks tricky. Let me think about it any maybe we could do it in a follow up PR?

2017-02-07 08:04 UTC, vdemeester commented on cli/command/formatter/volume.go
> +func (c volumeHeaderContext) Label(name string) string {
@yongtang yeah, definitely in a follow-up 👼

2017-02-20 18:28 UTC, mlaventure approved these changes
LGTM

ping @vdemeester

2017-02-20 18:38 UTC, vdemeester approved these changes
LGTM 🐸

2017-03-03 19:25 UTC, merged

2017-03-03 21:02 UTC, dnephin commented
I think this is causing tests to fail on master:

```
20:54:19 cli/command/formatter/task.go:71: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:79: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:84: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:101: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:106: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:111: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:119: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
20:54:19 cli/command/formatter/task.go:132: c.AddHeader undefined (type *taskContext has no field or method AddHeader)
```

2017-03-03 21:09 UTC, yongtang commented
The error is likely caused by overlapping merge from different PRs. Let me take a look and fix it.

2017-03-03 21:15 UTC, dnephin commented
sounds right. I have most of the fix, but I'm seeing the header as `<no value>`

2017-03-03 21:17 UTC, mlaventure commented
@yongtang https://github.com/docker/docker/pull/28213 did indeed

2017-03-03 21:21 UTC, dnephin commented
https://gist.github.com/dnephin/4f35a12f131f70f1d5bf04b1bd8b6cb8 seems to be most of it, but one test is failing because of whitespace. I'm not sure if the test needs to be fixed, or the code.

2017-03-03 21:28 UTC, yongtang commented
Created #31533 for the fix.

2017-03-03 21:31 UTC, yongtang commented
@dnephin Ah yes the test needs to be changed. The original test uses delim `" "` (whitespace). Under the old way of header process, that will caused the content to be rendered with delim `" "` (whitespace) and the header to be rendered with `\t` (tab). 

This PR (#30733) actually fixes the issue so the header/content delim should be consistent now.

2017-03-03 21:31 UTC, yongtang commented
Thanks @dnephin @mlaventure and sorry for the inconvenience caused.