Cli fixups
moby/moby pull request #30804
Opened 2017-02-07 23:49 UTC by mstanleyjones

Two smaller commits address https://github.com/docker/docker.github.io/issues/1451 and remove an unused GIF from `docs/reference/commandline/`.

The big commit standardizes formatting of CLI reference commands:
    
- Command name should be a H1
- Only Description, Examples, and Related Commands should be H2
- Changed 'Related information' heading to 'Related commands' since 99% it is only linking commands
- Added some examples where relevant

These changes will enable us to automate use of the CLI reference files in generated YAML output.

![Cute alligators](http://www.photographyblogger.net/wp-content/uploads/2013/07/6262865399_9280cc301a_z.jpg)

cc/ @FrenchBen

2017-02-08 01:57 UTC, AkihiroSuda commented on docs/reference/commandline/attach.md
> +```bash
I wonder `console` is preferred over `bash` for better rendering, but it can be other PR.

2017-02-08 06:30 UTC, thaJeztah commented on docs/reference/commandline/attach.md
> +```bash
Highlighting will probably improve once we can do https://github.com/docker/docker.github.io/pull/1021, unfortunately that's currently blocked by changes upstream

2017-02-08 07:21 UTC, thaJeztah requested changes
thanks! left some comments

2017-02-08 07:21 UTC, thaJeztah commented on docs/reference/commandline/rm.md
> +### Remove a container and its links
Actually, this only removes the "link" (if it's a legacy link on the default bridge network; the same may not apply when using `--link` on a custom network)

2017-02-08 07:21 UTC, thaJeztah commented on docs/reference/commandline/rm.md
> +### Force-remove a running container
For a follow up; we may want to express the dangers of using `-f`, as it not only forces removal of a container is still running, but also can result in layers being left behind if they fail to be removed

2017-02-08 07:21 UTC, thaJeztah commented on docs/reference/commandline/wait.md
> +> the container is still running.
Can you check this to be sure (per our discussion)

2017-02-08 21:18 UTC, mstanleyjones commented on docs/reference/commandline/attach.md
> +```bash
Either `bash` is a synonym for `console` or the other way around. They are equivalent. We have pretty much standardized on `bash` over time.

2017-02-08 21:20 UTC, mstanleyjones commented on docs/reference/commandline/dockerd.md
> +```none
Correct. It screws up the formatting in the whole rest of the file. :(

2017-02-08 21:24 UTC, mstanleyjones commented
Addressed feedback so far, except for follow-up issues.

2017-02-08 23:29 UTC, thaJeztah approved these changes
LGTM, but needs a rebase

2017-02-09 00:58 UTC, mstanleyjones commented
Rebase complete, @thaJeztah

2017-02-09 01:07 UTC, thaJeztah commented
Let's go!

2017-02-09 01:07 UTC, merged