Add `PORTS` field for `docker service ls` (`ingress`)
moby/moby pull request #30813
Opened 2017-02-08 06:55 UTC by yongtang

This fix is related to https://github.com/docker/docker/issues/30232#issuecomment-276525426 where `docker service ls` does not show `PORTS` information like `docker service ps`.

This fix adds `PORTS` fields for services that publish ports in ingress mode.

Additional unit tests cases have been updated.

This fix is related to #30232.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-02-08 15:40 UTC, yongtang commented
The ports published in `host` mode is not shown in this PR. I am thinking it might make sense to have it in `PORTS` column as well. Though not sure what is the best way to represent it (and distinguish itself from `ingress` mode).

The ingress port is in `*:8002->80/tcp` format.

2017-02-08 17:13 UTC, yongtang commented
Also, not sure if the `PORT` columns should be based on `service.Spec.EndpointSpec.Ports`, or `service.Endpoint.Ports`.

2017-03-27 19:46 UTC, vdemeester commented
ping @thaJeztah @mavenugo @icecrime

2017-03-27 19:47 UTC, vdemeester approved these changes
LGTM 🐮

2017-03-30 13:29 UTC, thaJeztah requested changes
changes LGTM, can you add the new placeholder to the CLI docs; https://github.com/docker/docker/blob/master/docs/reference/commandline/service_ls.md#formatting ?

2017-04-04 01:41 UTC, yongtang commented
@vdemeester @thaJeztah Thanks for the review. The doc has been updated.

2017-04-04 10:30 UTC, vdemeester approved these changes
LGTM 🦁

2017-04-04 12:35 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-04-04 15:04 UTC, merged