fix typo for dockerd.8.md
moby/moby pull request #30997
Opened 2017-02-14 09:09 UTC by lixiaobing10051267

fix typo.

2017-02-14 09:48 UTC, vdemeester approved these changes
LGTM 🐸
/cc @AkihiroSuda @runcom @thaJeztah

2017-02-14 09:53 UTC, thaJeztah commented on man/dockerd.8.md
> +resize support, dynamically changing thin-pool features, automatic thin
Are you sure it's a typo? I think `thinp` is the actual name here (for thin provisioning) https://fedoraproject.org/wiki/Features/ThinProvisioning

/cc @rhvgoyal

2017-02-15 01:30 UTC, AkihiroSuda requested changes
As @thaJeztah said this does not seem typo

2017-02-15 01:47 UTC, lixiaobing10051267 commented
ok

2017-02-15 01:47 UTC, closed without merging