Flags for specifying bind mount consistency
moby/moby pull request #31047
Opened 2017-02-15 16:00 UTC by yallop

This PR introduces a small change to the Docker client CLI as part of a larger project to address some longstanding file sharing performance on Docker for Mac ([[1]][fs-performance-forums], [[2]][fs-performance-issues]).

The poor performance of bind mounts in Docker for Mac for some applications arises from [osxfs][osxfs] ensuring perfectly consistent views of bind mounts between container and host: reads, writes and events from within a container are propagated synchronously to the host, and vice versa.

Perfect consistency is the right default, but for some workloads where it's unnecessary it puts a low ceiling on performance.  To improve performance for such workloads, we plan to allow the user to relax consistency guarantees for individual bind-mounted directories.

The full details of the proposal are available [here][proposal].  This patch includes one small piece of the work, namely additional bind options `cached`, `delegated`, `consistent`, for selecting consistency modes.  Although the immediate aim is improving `osxfs` performance, these options are not macOS-specific; they give a general view of consistency that applies to many systems, both for bind mounts and volume plugins.  For example,
 * essentially the same consistency taxonomy is used by Infinit
 * the same approach may be used in future to improve performance on Windows
 * on systems that directly expose the host file system to a container, such as Linux, ignoring the options is an acceptable implementation of all three modes.  (Even on Linux a container runtime could in principle take advantage of the relaxed semantics associated with `delegated` and `cached`.)

[osxfs]: https://docs.docker.com/docker-for-mac/osxfs/
[fs-performance-forums]: https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076
[fs-performance-issues]: https://github.com/docker/for-mac/issues/77
[proposal]: https://gist.github.com/yallop/d4af9dd1bb33ae61d48adf86692cdf9e

2017-02-16 02:11 UTC, AkihiroSuda commented
Can we add these flags to `--mount` (`opts/mount.go`) as well?

2017-02-16 16:53 UTC, yallop commented
@AkihiroSuda: a1649ef

2017-02-16 20:51 UTC, dnephin commented
Design LGTM

2017-02-16 20:55 UTC, dnephin commented on api/types/mount/mount.go
> +	State    State  `json:",omitempty"`
I wonder if `State` is the right term here.

Would something like `Consistency` work?

2017-02-16 21:46 UTC, yallop commented on api/types/mount/mount.go
> +	State    State  `json:",omitempty"`
Yes, `State` is a bit general.  `Consistency` sounds good.

2017-02-17 01:29 UTC, cpuguy83 commented
While I definitely appreciate the goal of making osxfs faster (directly affects me!) this does not seem right.
This is adding an API only change and nothing in Docker would even be using it.

Additionally it seems like we're pushing osxfs performance issues to the user to deal with.
Suddenly we'll see compose files everywhere with `cached` or `delegated` added to them just so performance doesn't suck on OSX.

2017-02-17 08:07 UTC, yallop commented
> Additionally it seems like we're pushing osxfs performance issues to the user to deal with.

Improving performance on Docker for Mac is an immediate goal of this introducing this feature now, but there's nothing specific to osxfs in the design.

We're allowing the user to describe the consistency requirements of the mount, because that's information that only the user has, and because Docker can make use of that information to improve performance.

The interface currently has no way to enable caching because it's been designed with the Linux implementation in mind.  If we want Docker to perform well on other systems then we need to adapt the interface so that it's less Linux-specific. 

> Suddenly we'll see compose files everywhere with cached or delegated added to them just so performance doesn't suck on OSX.

We can certainly hope that people start to use the feature.   If we see `cached` or `delegated` in compose files it's because those are the consistency levels required by the application.

2017-02-20 16:03 UTC, yallop commented
@dnephin, did the [label](https://github.com/docker/docker/pull/31047#event-965701465) (`rebuild/experimental`) trigger an experimental rebuild?  I'm not sure whether the test failure represents a genuine problem.

2017-02-20 16:13 UTC, justincormack commented
I just retriggered the experimental rebuild, we were having some issues, I don't think it was triggered as the label was not automatically removed.

2017-02-22 11:32 UTC, yallop commented
There's not a lot of activity on this issue, perhaps because it's not clear to the casual reader how critical this patch is to the success of Docker on macOS.

Here's an account [posted on Reddit yesterday](https://www.reddit.com/r/docker/comments/5v8fc7/docker_for_mac_vs_dockertoolbox/de0a209/) of how one company gave up on Docker:

> This is our primary blocker for not using docker in our infrastructure right now. [...]
> Docker is basically a no go at our company because of this issue. (Entire office uses MBP's)
> There are some workarounds using rsync or something but it just seems like too much complexity.
> I actually ended up spending a ton of time dockerizing our stack only to run into this brick wall. It was devistating.

This PR allows us to address the company's major concern.  And this is far from an isolated case; it would be easy to give many more such examples.

2017-02-22 14:53 UTC, cpuguy83 commented
@yallop I get it, I really do... but again this is not doing anything but changing the API. Docker is not consuming it any way. Major red flag here.

Why not at least provide a switch to change the default behavior in d4mac preferences? This could be done either globally or per share.
If there's still an issue after such an option is available it can be addressed accordingly.

2017-02-23 18:38 UTC, nathanleclaire commented
I applaud the general effort to improve shared folder performance in Docker for Mac but I share @cpuguy83's concerns that this is adding something to the Docker API which does not get used by the Docker daemon at all.

Why would this not be added as a configurable setting in Docker for Mac? It seems to be very Docker for Mac specific. The Docker daemon is designed to run on Linux and Windows, but this adds a parameter which will be ignored by both.

2017-02-23 18:44 UTC, dsheets commented
@nathanleclaire while Docker for Mac is the first use case for these semantics, they are applicable to Infinit, Docker for Windows, volume plugins, and potentially Docker on Linux with a future extension point (`delegated` can effectively disable disk flushes during container run-time).

2017-02-23 22:08 UTC, dnephin commented on api/types/mount/mount.go
> +	State    State  `json:",omitempty"`
bump now  that this PR is in code review

2017-02-23 22:13 UTC, cpuguy83 commented on api/types/mount/mount.go
> +	StateConsistent State = "consistent"
`full`, or `synchronous`

2017-02-23 22:13 UTC, cpuguy83 commented on api/types/mount/mount.go
> +	StateConsistent State = "consistent"
Change `State` here to `Consistency`

2017-02-23 22:27 UTC, cpuguy83 commented on api/types/mount/mount.go
> +type State string
Change `State` here to `Consistency`

2017-02-23 22:28 UTC, cpuguy83 commented on api/types/mount/mount.go
> +type State string
Or `ConsistencyLevel` ?

2017-02-23 22:34 UTC, cpuguy83 commented
Just for the record, I was wooed and am ok with this change.

2017-02-24 14:37 UTC, dsheets commented
@cpuguy83 we're open to changing the name of the field and the names of the modes. We initially selected `state` and [`consistent`,`cached`,`delegated`,`default`] by evaluating three criteria:

1. `-v` comprehensibility
2. `--mount` comprehensibility
3. verbalization

The cases considered look like:

`-v /a:/a:consistent` pronounced "the mount is consistent"
`-v /a:/a:cached` pronounced "the mount is cached"
`-v /a:/a:delegated` pronounced "the mount is delegated"
`--mount type=bind,src=/a,dst=/a,state=consistent` pronounced "the mount's state is consistent"
`--mount type=bind,src=/a,dst=/a,state=default` pronounced "the mount's state is default"
`--mount type=bind,src=/a,dst=/a,state=cached` pronounced "the mount's state is cached"
`--mount type=bind,src=/a,dst=/a,state=delegated` pronounced "the mount's state is delegated"

I think you are proposing to change `consistent` to `synchronous` or `full` and `state` to `consistency`? I understand that `state` seems somewhat ambiguous about whether it is referring to the state of the mount concept or the underlying file system. I think it is unlikely to collide with future changes that do not interact with this specification as `state` is too general for any Docker mount concept and only makes sense in reference to the state of the file system itself.

I don't think `full` will work due to the case `-v /a:/a:full` which is not explanatory.

`-v /a:/a:synchronous` makes more sense but is longer, contains non-phonetic letters, and describes the implementation rather than the user's obervable experience. We are fine with naming the mode this if these trade-offs are considered and deemed acceptable. `sync` wouldn't have as many of these downsides but still describes implementation rather than behavior.

Renaming `state` to `consistency` would result in:

`--mount type=bind,src=/a,dst=/a,consistency=consistent` pronounced "the mount's consistency is consistent"
`--mount type=bind,src=/a,dst=/a,consistency=default` pronounced "the mount's consistency is default"
`--mount type=bind,src=/a,dst=/a,consistency=cached` pronounced "the mount's consistency is cached"
`--mount type=bind,src=/a,dst=/a,consistency=delegated` pronounced "the mount's consistency is delegated"

`consistency` is significantly longer than `state`, though arguably more descriptive. I don't think the verbalizations read as smoothly as `state` but they are still understandable.

We also believe that the terms used should be the same between `-v` and `--mount` and any future uses. In discussion with Ian Campbell, he suggested that `state` is ambiguous with some existing flags like `ro` which was undesirable. I know that the design of `ro` and `rw` are themselves in question as they are anonymous booleans. I think it could make sense to unify them with the `state` field to produce arguments like

`--mount type=bind,src=/a,dst=/a,state=cached+ro` pronounced "the mount's state is cached and read-only"

Ultimately, this all comes down to various comprehensibility and ease-of-use trade-offs in the design space. We think that the current names are the best of those we considered during design (e.g. `state` was initially `semantics`!) but we're happy to explore other options in a framework that takes the whole UX into account.

What issues do you foresee with the current set of names?

2017-02-24 16:18 UTC, dnephin commented
I think `state` is too generic. `consistency` makes the setting more clear.

2017-02-24 16:20 UTC, dnephin commented on api/types/mount/mount.go
> +	StateConsistent State = "consistent"
`synchronous` seem to refer more to the mechanism used to accomplish the consistency.

Where as `consistent` refers to the desired "state".

I prefer `consistent` here.

2017-02-27 15:30 UTC, dnephin approved these changes
LGTM

2017-02-27 17:07 UTC, cpuguy83 requested changes

2017-03-01 14:14 UTC, yallop commented on volume/volume_unix.go
> +	"consistent": true,
@cpuguy83.  Good idea. See e02de44.

2017-03-01 14:30 UTC, cpuguy83 commented
```
14:29:39 These files are not properly gofmt'd:
14:29:39  - api/types/mount/mount.go
14:29:39 
14:29:39 Please reformat the above files using "gofmt -s -w" and commit the result.
```

Also needs a squash.

2017-03-01 17:59 UTC, yallop commented
Fixed and squashed into three coherent commits.  Let me know if you'd prefer it further squashed into one, @cpuguy83.

2017-03-01 18:03 UTC, cpuguy83 commented
One commit should be good for this change, thanks!

2017-03-01 20:41 UTC, cpuguy83 approved these changes
LGTM

ping @thaJeztah what if any docs do we need for this?

2017-03-08 00:46 UTC, thaJeztah commented
For docs, this probably needs changes to;

- the swagger.yaml (https://github.com/docker/docker/blob/master/api/swagger.yaml)
- an entry to the API changes https://github.com/docker/docker/blob/master/docs/api/version-history.md#v127-api-changes
- the reference docs for run, create https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md, https://github.com/docker/docker/blob/master/docs/reference/commandline/create.md (there's a list of options for `-v` for the flag description, but I think it's not published on docs.docker.com, so we may need a different section for describing those, similar to what we have on `service create` 😞 )
- the `service create` docs mention mount options; https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#bind-propagation
- the `docker run` man page https://github.com/docker/docker/blob/master/man/docker-run.1.md
- the `docker create` man page options section; https://github.com/docker/docker/blob/master/man/src/container/create.md#options


So, yes, we may want to start thinking of having a central section for these options, because it's repeated in a lot of places 😓

2017-03-10 22:49 UTC, yallop commented
I've opened a separate in-progress PR for documentation, following @justincormack's suggestion, so as not to delay the merge here: #31749.

2017-03-11 10:42 UTC, justincormack commented
As the freeze for 17.04 is Monday, splitting doesn't help much, as we need
docs if we are going to ship it.


On 10 Mar 2017 22:49, "yallop" <notifications@github.com> wrote:

> I've opened a separate in-progress PR for documentation, following
> @justincormack <https://github.com/justincormack>'s suggestion, so as not
> to delay the merge here: #31749
> <https://github.com/docker/docker/pull/31749>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/31047#issuecomment-285806610>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAdcPMfTP7GAYz-ixeWoyaXfcAquGKu1ks5rkdOHgaJpZM4MB5U4>
> .
>

2017-03-11 16:47 UTC, yallop commented
I've pushed docs to #31749.

2017-03-13 10:36 UTC, thaJeztah commented
Thanks for doing the docs PR; let's go ahead and merge this

2017-03-13 10:36 UTC, merged

2017-03-17 16:56 UTC, mstanleyjones commented
This seems to be missing CLI docs. @thaJeztah PTAL

2017-03-17 17:01 UTC, thaJeztah commented
@mstanleyjones see https://github.com/docker/docker/issues/31749

2017-03-17 17:19 UTC, mstanleyjones commented
Wow! Thanks.

2017-06-08 14:44 UTC, zikphil commented
Just wanted to thank the Moby team for integrating those changes. 👍

2017-07-07 20:43 UTC, stevvooe commented on api/types/mount/mount.go
> +	Consistency Consistency `json:",omitempty"`
Any reason this didn't land on `BindOptions`? This seems to only apply to bind mounts.