Windows: Wait for OOBE to prevent crashing during host update
moby/moby pull request #31054
Opened 2017-02-15 18:25 UTC by darrenstahlmsft

Signed-off-by: Darren Stahl <darst@microsoft.com>

**- What I did**

Prevent a Daemon crash during host update.

**- How I did it**

Some services Docker depends on are not active during a host update. This PR holds daemon initialization until after a host update is completed.

It also notifies the Windows Service Control Manager that the service has started as soon as the API is active to prevent service start timeouts waiting for OOBE or daemon initialization.

**- How to verify it**

Install Docker service on a machine that receives manual OS updates, such as a Windows Insider machine. After an update is installed, the daemon was not running, with an SCM log stating that it terminated unexpectedly. With this update, the daemon will be running.

**- Description for the changelog**

Prevent crash during Windows host update.

/cc @jhowardmsft @jstarks

2017-02-15 19:08 UTC, jhowardmsft commented on daemon/daemon_windows.go
> +func waitOOBEComplete() error {
Wondering if these two OOBE functions should be in pkg\system?

2017-02-15 19:08 UTC, jhowardmsft commented
LGTM with one minor comment.

2017-02-15 19:14 UTC, jhowardmsft commented
@johnstep FYI

2017-02-15 19:35 UTC, johnstep requested changes

2017-02-15 19:35 UTC, johnstep commented on daemon/daemon_windows.go
> +func isOOBEComplete() (OOBEComplete bool, err error) {
Looks like `isOOBEComplete` is unused.

2017-02-15 19:35 UTC, johnstep commented on cmd/dockerd/daemon_windows.go
> +	// start the service now to prevent timeouts waiting for daemon to started
Nit: `s/started/start`

2017-02-15 22:01 UTC, darrenstahlmsft commented on daemon/daemon_windows.go
> +func waitOOBEComplete() error {
I think pkg/system is generally for platform agnostic versions of things. Not to say I would be against moving it makes sense there though.

2017-02-15 22:03 UTC, darrenstahlmsft commented on daemon/daemon_windows.go
> +func isOOBEComplete() (OOBEComplete bool, err error) {
Ah, yep, removed.

2017-02-15 22:03 UTC, darrenstahlmsft commented on cmd/dockerd/daemon_windows.go
> +	// start the service now to prevent timeouts waiting for daemon to started
Fixed.

2017-02-16 05:44 UTC, johnstep approved these changes
LGTM

2017-02-16 16:18 UTC, cpuguy83 approved these changes
LGTM

2017-02-16 16:18 UTC, merged

2017-03-27 22:40 UTC, darrenstahlmsft commented
@thaJeztah If #32152 is merged, the changelog from this PR is no longer needed.