Typo fixed and this time I provide my cSpell.json
moby/moby pull request #31088
Opened 2017-02-16 16:12 UTC by xulike666

Signed-off-by: Aaron.L.Xu <likexu@harmonycloud.cn>

**- What I did**

I was very annoyed by those kind of typo mistakes and maybe this file (https://github.com/xulike666/vscode-spell-checker-helper/blob/master/docker/spellcheck.txt) could help our developers.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-02-16 16:23 UTC, vdemeester approved these changes
LGTM 🐸

2017-02-16 16:23 UTC, cpuguy83 commented on cli/command/image/build.go
> +// non terminal scenarios to depresses verbose messages
suppress?

2017-02-16 16:23 UTC, vdemeester commented on cli/command/image/build.go
> +// non terminal scenarios to depresses verbose messages
ah lol :joy:

2017-02-16 16:24 UTC, cpuguy83 requested changes

2017-02-16 16:24 UTC, cpuguy83 commented on man/dockerd.8.md
> +resize support, dynamically changing thin-pool features, automatic thin
`thinp` is correct

2017-02-17 01:03 UTC, cpuguy83 approved these changes
LGTM

2017-02-17 03:04 UTC, merged