typo fixes: make man more reliable
moby/moby pull request #31083
Opened 2017-02-16 12:13 UTC by liker12134

Signed-off-by: Aaron.L.Xu <likexu@harmonycloud.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-02-16 12:32 UTC, vdemeester approved these changes
LGTM 🐸

2017-02-16 12:32 UTC, vdemeester commented on man/src/container/commit.md
> -      -a="A D Ministrator" 98bd7fc99854 fedora/fedora_httpd:20
This one might be intentional ?

2017-02-17 01:14 UTC, cpuguy83 commented
Can you squash and provide an accurate commit message?

Thanks!

2017-02-17 06:53 UTC, AkihiroSuda commented
@liker12134 
Just a confirmation: are you @xulike666 ?

(I think it is OK to use multiple GitHub accounts, but just confused)

2017-02-17 06:58 UTC, xulike666 commented
@AkihiroSuda, sorry for the confusion and it‘s my personal private account. 😄

2017-02-17 17:33 UTC, justincormack approved these changes

2017-02-17 18:01 UTC, cpuguy83 requested changes
Still needs a commit message update.
Thanks!

2017-03-03 13:05 UTC, AkihiroSuda commented
ping @xulike666 (@liker12134)

2017-03-03 14:12 UTC, thaJeztah approved these changes
looks like the commit message is ok now

LGTM

2017-03-03 14:13 UTC, merged