Update storage driver options link
moby/moby pull request #31103
Opened 2017-02-16 22:24 UTC by tonistiigi

Old link redirects but loses the anchor.

@thaJeztah 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

2017-02-16 23:51 UTC, thaJeztah requested changes

2017-02-16 23:51 UTC, thaJeztah commented on daemon/graphdriver/devmapper/deviceset.go
> +			logrus.Error("devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For mor
can you change the anchor and remove the extra slash (`/#/storage-driver-options` -> `/#storage-driver-options`) ? The extra slash is added by some JavaScript library, but is not the _actual_ anchor

2017-02-16 23:51 UTC, thaJeztah commented on daemon/graphdriver/devmapper/deviceset.go
> +			logrus.Error("devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a more recent version of libdevmapper or select a different storage driver. For mo
Same here

2017-02-17 02:33 UTC, tonistiigi commented
@thaJeztah PTAL

2017-02-17 02:44 UTC, thaJeztah approved these changes
LGTM

2017-02-17 02:45 UTC, thaJeztah commented
ping @vdemeester

2017-02-17 08:45 UTC, vdemeester approved these changes
LGTM 🐸

2017-02-17 08:45 UTC, merged