Improve the description of "docker -v" & "docker version"
moby/moby pull request #31180
Opened 2017-02-20 09:16 UTC by YuPengZTE

Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

**- What I did**
1. Delete "and quit" of "docker -v"
2. Distinguish the description between "docker -v" and “docker version”
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
Before:
docker version
![image](https://cloud.githubusercontent.com/assets/20062886/23118538/774012b2-f78f-11e6-8db3-654d8aac43e1.png)
docker -v
![image](https://cloud.githubusercontent.com/assets/20062886/23118570/982f5bcc-f78f-11e6-80f0-33df819c401e.png)
![image](https://cloud.githubusercontent.com/assets/20062886/23118596/b24e4c8e-f78f-11e6-96c4-696e94db4837.png)

2017-02-20 09:34 UTC, AkihiroSuda requested changes

2017-02-20 09:34 UTC, AkihiroSuda commented on cmd/docker/docker.go
> +	flags.BoolVarP(&opts.Version, "version", "v", false, "Show version information")
This is incorrect. It actually quits.

2017-02-20 11:01 UTC, YuPengZTE commented on cmd/docker/docker.go
> +	flags.BoolVarP(&opts.Version, "version", "v", false, "Show version information")
@AkihiroSuda ,yes, many "show xxx" commands actually quit, but not add  "and quit", except “docker -v”.

2017-02-20 11:12 UTC, thaJeztah commented on cli/command/system/version.go
> +		Short: "Show the summary information of client and server",
I'm not convinced that "summary information" is any clearer

2017-02-21 01:53 UTC, AkihiroSuda commented on cmd/docker/docker.go
> +	flags.BoolVarP(&opts.Version, "version", "v", false, "Show version information")
No, `--version` is different from other flags such as `--config`, `--debug`, and `--tls`.
They does not quit.

2017-02-21 01:54 UTC, AkihiroSuda commented on cmd/docker/docker.go
> +	flags.BoolVarP(&opts.Version, "version", "v", false, "Show version information")
I found `docker --version SOME_SUBCOMMAND` executes the subcommand rather than just prints version and quits, but this behavior should be bug.

2017-02-21 02:37 UTC, YuPengZTE commented on cmd/docker/docker.go
> +	flags.BoolVarP(&opts.Version, "version", "v", false, "Show version information")
Thanks @AkihiroSuda , I will have a closer look at the code.

2017-02-23 09:23 UTC, closed without merging