validate extraHosts in daemon side
moby/moby pull request #31384
Opened 2017-02-27 13:26 UTC by allencloud

Signed-off-by: allencloud <allen.sun@daocloud.io>

fixes https://github.com/docker/docker/issues/31378

**- What I did**
1. add validation for extraHosts in daemon side when creating a container;
2  add validation for extraHosts in buildSandboxOptions to prevent the remaining container with run extraHost from being started again 

I think the extraHost has already covered in UNIT test of https://github.com/docker/docker/blob/master/opts/hosts_test.go#L151-L164 , then no integration test added.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-02-27 13:44 UTC, thaJeztah submitted a review, later dismissed
~~LGTM~~ see below

2017-02-27 13:46 UTC, thaJeztah commented
Windows is failing;
```
13:34:47 # github.com/docker/docker/daemon
13:34:47 ..\..\daemon\container.go:260: multiple-value opts.ValidateExtraHost() in single-value context
```

2017-02-27 13:48 UTC, thaJeztah requested changes

2017-02-27 13:48 UTC, thaJeztah commented on daemon/container.go
> +		if err := opts.ValidateExtraHost(extraHost); err != nil {
Should probably be

```go
if _, err := ......
```

2017-02-28 01:28 UTC, AkihiroSuda commented on daemon/container_operations.go
> +		if len(parts) != 2 {
why not use `opts.ValidateExtraHost` here?

2017-02-28 02:34 UTC, allencloud commented on daemon/container.go
> +		if err := opts.ValidateExtraHost(extraHost); err != nil {
Oh, this validation still returns the original input string, sorry for my mistake. Updated.

2017-02-28 02:42 UTC, allencloud commented on daemon/container_operations.go
> +		if len(parts) != 2 {
Yeah, `opts.ValidateExtraHost` also validates whether the IP is valid, not only bad format.

2017-02-28 17:09 UTC, allencloud commented
Yeah, I think it is flaky test. PTAL @thaJeztah

2017-02-28 17:26 UTC, thaJeztah approved these changes
LGTM

2017-02-28 17:27 UTC, vdemeester approved these changes
LGTM 🐸

2017-02-28 17:28 UTC, merged