exported add. cli compose loader parsing methods
moby/moby pull request #31443
Opened 2017-03-01 09:01 UTC by james-nesbitt

Signed-off-by: James Nesbitt <james.nesbitt@wunderkraut.com>

Relates to https://github.com/docker/docker/issues/31440

**- What I did**

I exported some of the loadX methods found in the cli/compose/loader system, to make it possible for others to reuse the core functionality to parse services/networks etc from custom yml config.
This is meant to allow re-using of the core code for parsing compose config, regardless of where it is used.

The changes are all internal to the docker/cli/compose/loader package, and no external impact should be felt.

THIS INTRODUCES THE RISK OF MAINTENANCE OF NEWLY EXPORTED FUNCTIONS
(people are going to expect them to be reliable - but technically they may start to use Load() anyway)

**- How I did it**

The following functions in cli/compose/loader/loader.go where affected:

```
loadServices()
loadService()
loadNetworks()
loadVolumes()
loadSecrets()
```

1. I exported the functions (turned loadX into LoadX) and added a doc line to each
2. Then I updated all calls of those functions

**- How to verify it**

This should produce no external changes, but allows use of the loader as a library.

**- Description for the changelog**

exported more cli/compose/load marshalling functions for re-use

2017-03-01 10:14 UTC, james-nesbitt commented
```
09:18:59 cli/compose/loader/loader.go:307:1: comment on exported function LoadServices should be of the form "LoadServices ..."
09:18:59 cli/compose/loader/loader.go:322:1: comment on exported function LoadService should be of the form "LoadService ..."
09:18:59 cli/compose/loader/loader.go:410:1: comment on exported function LoadNetworks should be of the form "LoadNetworks ..."
09:18:59 cli/compose/loader/loader.go:426:1: comment on exported function LoadVolumes should be of the form "LoadVolumes ..."
09:18:59 cli/compose/loader/loader.go:442:1: comment on exported function LoadSecrets should be of the form "LoadSecrets ..."
```

pushed a commit to fix poor exported func documentation.

2017-03-01 12:38 UTC, james-nesbitt commented
I realize now that direct use of the loaders would bypass the schema validator in Load():

```
	if err := schema.Validate(configDict, schema.Version(configDict)); err != nil {
		return nil, err
	}
```

2017-03-01 22:38 UTC, dnephin approved these changes
LGTM

2017-03-02 07:47 UTC, james-nesbitt commented
@dnephin you are not concerned about the schema validation issue?

2017-03-02 15:07 UTC, dnephin commented
I don't think it will be an issue for `docker/docker`

2017-03-03 08:49 UTC, james-nesbitt commented
@thaJeztah I will have to follow the lead on that question.

What do you think is appropriate?

```
// LoadServices produces a ServiceConfig map from a compose file Dict.  Does not validate the Dict schema
```

2017-03-06 12:00 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "export-more-compose-methods" git@github.com:james-nesbitt/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354215320
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-06 12:11 UTC, james-nesbitt commented
made some doc changes:

for example:
```
 // LoadServices produces a ServiceConfig map from a compose file Dict
 +// the servicesDict is not validated if directly used. Use Load() to enable validation
```

2017-03-06 13:20 UTC, thaJeztah requested changes
changes LGTM, but can you squash your commits, so that there's only a single commit in this PR?

If needed, you can find some information on how to do so in our contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently

2017-03-07 10:10 UTC, james-nesbitt commented
@thaJeztah will do that now

2017-03-07 10:28 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "export-more-compose-methods" git@github.com:james-nesbitt/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353967408
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-07 10:46 UTC, james-nesbitt commented
ok, I royally messed that up, I will try again

2017-03-07 13:17 UTC, thaJeztah approved these changes
LGTM

2017-03-07 15:34 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "export-more-compose-methods" git@github.com:james-nesbitt/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354560008
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-08 10:23 UTC, james-nesbitt commented
No sure how these changes would break the powerpc build.  Seems like a jenkins/build failure to me?

2017-03-08 14:11 UTC, thaJeztah commented
> No sure how these changes would break the powerpc build. Seems like a jenkins/build failure to me?

Yes, I think they're still setting up the PowerPC and Z builds. Feel free to ignore them for now

2017-03-08 14:12 UTC, thaJeztah commented
All other builds are green, so I'll go ahead and merge, thanks for contributing!

2017-03-08 14:12 UTC, merged