Add format to secret ls
moby/moby pull request #31552
Opened 2017-03-05 11:14 UTC by ripcurld0

**- What I did**
 Add the format option to the docker-secret-ls command
related to #30431

**- How I did it**
* Add the format option to the cli/command/secret/ls.go
* Create cli/command/formatter/secret.go
* Add unit tests

**- How to verify it**
 TESTDIRS='cli/command/formatter/' TESTFLAGS='-test.run ^TestSecret*' hack/make.sh test-unit

**- Description for the changelog**
Add format to secret ls

2017-03-06 01:20 UTC, AkihiroSuda commented on cli/command/formatter/secret.go
> +type secretContext struct {
MarshalJSON is needed (please refer to similar code in the package)

2017-03-06 01:21 UTC, AkihiroSuda requested changes
Also, please add docs?

2017-03-06 07:06 UTC, ripcurld0 commented
@AkihiroSuda thanks a lot. I will fix that :smiley_cat:

2017-03-06 08:46 UTC, vdemeester reviewed
design LGTM for me 👼

2017-03-06 10:51 UTC, ripcurld0 commented on cli/command/formatter/secret.go
> +type secretContext struct {
:+1:

2017-03-06 11:50 UTC, thaJeztah commented on cli/command/secret/ls.go
> +	flags.StringVarP(&opts.format, "format", "", "", "Pretty-print containers using a Go template")
s/containers/secrets/ :smile:

2017-03-06 11:57 UTC, ripcurld0 commented on cli/command/secret/ls.go
> +	flags.StringVarP(&opts.format, "format", "", "", "Pretty-print containers using a Go template")
:scream:

2017-03-06 15:06 UTC, ripcurld0 commented
Added documentation + fixed comments

2017-03-08 13:32 UTC, thaJeztah requested changes
Thanks @ripcurld0, overall looking good, but I think some things are missing (see my comments inline) ☺️

2017-03-08 13:32 UTC, thaJeztah commented on cli/command/secret/ls.go
> +	if len(format) == 0 {
Can you add support for setting a default format in the client configuration file? (like https://github.com/docker/docker/blob/b1debf1374ca7be7e7b4d4fcd41eceaf8b7cf153/cli/command/stack/ps.go#L66-L73)

2017-03-08 13:32 UTC, thaJeztah commented on cli/command/secret/ls.go
> +	if len(format) == 0 {
And add an example to the CLI docs here; https://github.com/docker/docker/blob/master/docs/reference/commandline/cli.md#configuration-files

2017-03-08 13:33 UTC, thaJeztah commented
I think we should also have `.Labels` and `.Label` (similar to the [option on `docker ps`](https://github.com/docker/docker/blob/master/docs/reference/commandline/ps.md#formatting)), given that secrets can have labels, and a `--filter` option is added in https://github.com/docker/docker/pull/30810

2017-03-13 11:39 UTC, thaJeztah requested changes
Thanks! I think we're almost there; code LGTM, left some comments for the docs

2017-03-13 11:39 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +
Can you add an example as well in the sample JSON below? (https://github.com/docker/docker/pull/31552/files#diff-578706828b816c40dd41b66896ab92c5R214)

2017-03-13 11:39 UTC, thaJeztah commented on docs/reference/commandline/secret_ls.md
> +| `.Labels`    | All labels assigned to the secret |
Looks like you forgot to add the `.Label` option here

2017-03-13 11:39 UTC, thaJeztah commented
ping @AkihiroSuda ptal

2017-03-13 11:49 UTC, AkihiroSuda commented on cli/command/formatter/secret.go
> +)
Typo: Updatedd -> Updated

2017-03-13 17:05 UTC, ripcurld0 commented on docs/reference/commandline/cli.md
> +
What JSON? 🐈

2017-03-13 17:09 UTC, thaJeztah commented on docs/reference/commandline/cli.md
> +
Oh there's a sample `config.json` configuration file; would be good to have an example `secretFormat` in there;

<img width="978" alt="screen shot 2017-03-13 at 18 07 45" src="https://cloud.githubusercontent.com/assets/1804568/23866136/2c300bb2-0818-11e7-8628-320000b5072f.png">

2017-03-13 17:20 UTC, ripcurld0 commented on docs/reference/commandline/cli.md
> +
Got it! 👍

2017-03-20 19:13 UTC, MHBauer commented
Concept, code, docs looks good to me. @AkihiroSuda, @thaJeztah anything else?

2017-03-20 19:18 UTC, thaJeztah approved these changes
oh, I missed it was updated 😃 

LGTM

2017-03-20 19:20 UTC, thaJeztah commented
I think @AkihiroSuda's comments are addressed, so let me go ahead 👍

2017-03-20 19:20 UTC, merged

2017-03-20 19:21 UTC, thaJeztah commented
/cc @albers @sdurrheimer for completion scripts :heart:

2017-03-20 19:40 UTC, ripcurld0 commented
🙌 🕺