Remove redundant Mounts when start docker daemon
moby/moby pull request #31570
Opened 2017-03-06 11:42 UTC by keloyang

Signed-off-by: yangshukui <yangshukui@huawei.com>

If you have one or more container running in your host and restart docker daemon when docker save is in progress, then  you use docker save again, the docker save operation will not be successful again.

**Why**
1. with container ruuning, docker daemon will not invoke Cleanup in the graphdriver when daemon exit.
2. docker daemon exit with exception when docker save operation is running,the procedure of saving will have mount/umount operation , if docker daemon exit with exception, it maybe has something not umount.

**- How I did it**
when restart docker daemon, remove the redundant mounts which are not used by docker container.

**- How to verify it**
before the pr,
```
docker run -d ubuntu:15.04 sleep 100000
docker save ubuntu:15.04>test.tar         #(kill docker daemon at the same time and restart it)
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker save rnd-dockerhub.huawei.com/official/ubuntu:15.04>test.tar
Error response from daemon: open /var/lib/docker/devicemapper/mnt/b49e7f17506fc456afc1936ddadc570ff9861f86af5c157b10b07057b7a31535/rootfs/bin/bash: no such file or directory
docker save rnd-dockerhub.huawei.com/official/ubuntu:15.04>test.tar
Error response from daemon: open /var/lib/docker/devicemapper/mnt/b49e7f17506fc456afc1936ddadc570ff9861f86af5c157b10b07057b7a31535/rootfs/bin/bash: no such file or directory
 ......
```

2017-03-06 14:07 UTC, thaJeztah commented on daemon/daemon.go
> +		path := fields[4]
This requires a check if there's 4 fields, otherwise this will panic

2017-03-06 14:08 UTC, thaJeztah commented
ping @cpuguy83 ptal

2017-03-08 08:47 UTC, coolljt0725 commented
ping @cpuguy83  @vdemeester

2017-03-10 01:58 UTC, keloyang commented
Can I remove "if len(fields) < 5 {",  “/proc/self/mountinfo” is a os interface which need forward compatibility, so I think there is no need to judge the length.
ping @thaJeztah WDYT ?

2017-03-15 07:36 UTC, keloyang commented
ping @cpuguy83 @vdemeester

2017-03-15 09:20 UTC, vdemeester commented
@keloyang unit test failures 

```
08:04:52 # github.com/docker/docker/distribution/xfer
08:04:52 distribution/xfer/download_test.go:270: cannot use layerStore (type *mockLayerStore) as type layer.Store in argument to NewLayerDownloadManager:
08:04:52 	*mockLayerStore does not implement layer.Store (missing DriverPut method)
08:04:52 distribution/xfer/download_test.go:331: cannot use mockLayerStore literal (type *mockLayerStore) as type layer.Store in argument to NewLayerDownloadManager:
08:04:52 	*mockLayerStore does not implement layer.Store (missing DriverPut method)
```

2017-03-16 04:25 UTC, AkihiroSuda requested changes

2017-03-16 04:25 UTC, AkihiroSuda commented on daemon/daemon.go
> +func (daemon *Daemon) removeRedundantMounts(containers map[string]*container.Container) error {
this should be moved to `daemon_linux.go`

2017-03-16 10:16 UTC, thaJeztah commented
ping @AkihiroSuda @cpuguy83 PR was updated, PTAL

2017-03-17 20:32 UTC, cpuguy83 requested changes
Seems like instead of this the layerstore should have a cleanup function that is run on daemon startup.
Ideally a `kill -9` should never lead to an inconsistent state after startup.

2017-03-17 20:32 UTC, cpuguy83 commented on layer/layer_store.go
> +func (ls *layerStore) DriverPut(id string) error {
I don't think we should be adding this to the interface

2017-03-18 02:23 UTC, keloyang commented on layer/layer_store.go
> +func (ls *layerStore) DriverPut(id string) error {
>layerstore should have a cleanup function that is run on daemon startup.
Thanks for your review.
how can we get a method to  exclude the correct mounts which are used by the running containers?

2017-03-23 20:56 UTC, cpuguy83 commented on layer/layer_store.go
> +func (ls *layerStore) DriverPut(id string) error {
> Seems like instead of this the layerstore should have a cleanup function that is run on daemon startup.

2017-06-23 01:09 UTC, closed without merging