Dry run test
moby/moby pull request #31596
Opened 2017-03-07 07:53 UTC by rootsongjc

Wrong entrypoint in docker plugin example 

``/go/bin/`` directory not exist, change the entrypoint to ``/docker-volume-sshfs``

2017-03-07 07:53 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "dry-run-test" git@github.com:rootsongjc/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842355073576
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-07 07:57 UTC, AkihiroSuda requested changes

2017-03-07 07:57 UTC, AkihiroSuda commented on docs/extend/index.md
> +	"entrypoint": ["/docker-volume-sshfs"],
I'm not sure this PR was opened by mistake or real pull request, but if this is a real PR, 

- Please update L168 as well
- Please remove TEST.md and update the description

2017-03-07 08:02 UTC, rootsongjc commented on docs/extend/index.md
> +	"entrypoint": ["/docker-volume-sshfs"],
OK, I have fixed it.

2017-03-07 08:13 UTC, AkihiroSuda commented on docs/extend/index.md
> +	"entrypoint": ["/docker-volume-sshfs"],
Please squash commits?

2017-03-07 08:13 UTC, AkihiroSuda commented on docs/extend/index.md
> +	"entrypoint": ["/docker-volume-sshfs"],
and please sign the commit

2017-03-07 09:09 UTC, rootsongjc commented on docs/extend/index.md
> +	"entrypoint": ["/docker-volume-sshfs"],
How about now?

2017-03-07 09:20 UTC, AkihiroSuda approved these changes
LGTM
cc @vieux

2017-03-20 22:38 UTC, thaJeztah approved these changes
LGTM

2017-03-20 22:38 UTC, merged