[WIP][test-integration] Introduce a `cli` package for test-integration
moby/moby pull request #31608
Opened 2017-03-07 13:43 UTC by vdemeester

This is an attempt to extract `dockerCmd*`, `inspect*` and `build*` code from `docker_utils_test.go` to package(s) (here `cli` and `cli/build`). The idea is to make what's done for `buildImage` but for any `docker` command and make it so that a test suite that wants to target a daemon use the same command as the default one (with just a *modifier*).

Some code examples 🐻.

```go
// dockerCmd functions
out := cli.DockerCmd(c, "ps", "-q").Combined() // equilvalent to `dockerCmd("ps", "-q")`
cli.Docker(cli.Cmd("ps", "-q"), cli.On(s.d)) // ~equivalent to `d.Cmd("ps", "-q")`
cli.Docker(cli.Cmd("ps", "-q"), cli.WithTimeout(5 * time.Second)).Assert(c, icmd.Success)
// Showing chaining asserts and using result
out := cli.Docker(cli.Cmd("ps", "-q")).Assert(c, icmd.Success).Combined()

// build* functions
cli.BuildCmd("imageName", build.WithDockerfile(…))
cli.BuildCmd("imageName", build.WithoutCache, withBuildContext(…))
// Or the common / hard way for specific stuff
cli.Docker(cli.Build("imageName"), build.WithDockerfile(…), cli.WithFlag("-q"))

// inspect* functions
id := cli.InspectCmd(c, "id", cli.Format(".Id")).Combined()
// Or the common / hard way for specific stuff ?
cli.Docker(cli.Inspect("id"), cli.Format(".Id")).Combined()
```

It also comes with a small change in `pkg/testutil/cmd` package to be able to chain multiple `Assert` and thus use `Result` after asserts if needed 🐯. 

It's a wip because I want to get some feedback on that 👼 and because I didn't migrate all function (will be in follow-up PRs anyway because it would be too much to review in one pass) and didn't mark old function as deprecated either. Not sure about the name either 😅. It might not pass validation too at first because I didn't comment all exported function 😝 

/cc @thaJeztah @aaronlehmann @dnephin @icecrime @cpuguy83 @vieux 

🦁

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2017-03-07 13:49 UTC, thaJeztah commented
```
13:44:24 These files are not properly gofmt'd:
13:44:24  - integration-cli/check_test.go
13:44:24  - integration-cli/docker_api_containers_test.go
13:44:24  - integration-cli/docker_cli_events_test.go
13:44:24  - integration-cli/docker_cli_events_unix_test.go
13:44:24  - integration-cli/docker_cli_images_test.go
13:44:24  - integration-cli/docker_cli_ps_test.go
13:44:24  - integration-cli/docker_cli_volume_test.go
```

2017-03-07 18:05 UTC, aaronlehmann commented
> cli.Docker(cli.Cmd("ps", "-q"), cli.On(s.d)) // ~equivalent to `d.Cmd("ps", "-q")`

How about `cli.Daemon` instead of `cli.On`?

> // Showing chaining asserts and using result
> out := cli.Docker(cli.Cmd("ps", "-q")).Assert(c, icmd.Success).Combined()

I like the other stuff but this chaining feels strange to me. We end up with a lot going on in one line, and it's strange for `Assert` to return something that can deliver output. I feel like it would be better to avoid this kind of chaining.

2017-03-08 11:06 UTC, vdemeester commented
> How about `cli.Daemon` instead of `cli.On`?

❤️ 

> I like the other stuff but this chaining feels strange to me. We end up with a lot going on in one line, and it's strange for `Assert` to return something that can deliver output. I feel like it would be better to avoid this kind of chaining.

Yeah, it's kind of a side effect to being able to make sure the command did ok *and* return some info about it.

2017-03-10 15:23 UTC, dnephin reviewed
Design LGTM

2017-03-21 09:25 UTC, vdemeester commented
Fixed build errors, I'll do follow-up to this in order to keep PR "reviewable" 👼

2017-03-21 10:21 UTC, thaJeztah requested changes
left some thoughts / comments 😅

2017-03-21 10:21 UTC, thaJeztah commented on integration-cli/docker_api_images_test.go
> +	buildImageSuccessfully(c, "saveandload", build.WithDockerfile("FROM busybox\nENV FOO bar"))
Will these functions (`buildImage...`) be moved and become exported? It feels a bit odd that (e.g.) `build.WithDockerfile` is exported, but only consumed by an _unexported_ function 😅

2017-03-21 10:21 UTC, thaJeztah commented on integration-cli/cli/build/build.go
> +// WithDockerfile specify a dockerfile string to be used as Dockerfile for build operations
If we have a type (see below), the description could become a bit clearer; `WithDockerfile creates / returns a CmdOperator to set the Dockerfile for a build operation` (or something like that)

2017-03-21 10:21 UTC, thaJeztah commented on integration-cli/docker_cli_health_test.go
> +		"--format=timeout={{.Config.Healthcheck.Timeout}} "+"interval={{.Config.Healthcheck.Interval}} "+"retries={{.Config.Healthcheck.Retries}} "+"test={{.Config.Healthcheck.Test}}", name)
These concatenations (`+`) are not needed now?

2017-03-21 10:21 UTC, thaJeztah commented on integration-cli/cli/build/build.go
> +// WithDockerfile specify a dockerfile string to be used as Dockerfile for build operations
Will this package only have "operators", or also other functionality? If just operators, wondering if it should be named different, but again, thinking out loud

2017-03-21 10:24 UTC, vdemeester commented on integration-cli/cli/build/build.go
> +// WithDockerfile specify a dockerfile string to be used as Dockerfile for build operations
@thaJeztah for now it's just operators but could be more 👼 (I want to move the `fakeContext` thingies here too)

2017-03-21 10:25 UTC, vdemeester commented on integration-cli/docker_api_images_test.go
> +	buildImageSuccessfully(c, "saveandload", build.WithDockerfile("FROM busybox\nENV FOO bar"))
Yeah, `buildImageSuccessfully` becomes `BuildCmd(…)`. I just did not renamed then yet (because the PR would be really huge!)

2017-03-21 10:26 UTC, vdemeester commented on integration-cli/docker_cli_health_test.go
> +		"--format=timeout={{.Config.Healthcheck.Timeout}} "+"interval={{.Config.Healthcheck.Interval}} "+"retries={{.Config.Healthcheck.Retries}} "+"test={{.Config.Healthcheck.Test}}", name)
Didn't see that (thanks to Goglnad) but yeah 😂

2017-03-23 17:29 UTC, thaJeztah approved these changes
LGTM

2017-03-23 19:53 UTC, dnephin approved these changes
LGTM

2017-03-24 04:04 UTC, merged