Improvement of TestCopier
moby/moby pull request #31675
Opened 2017-03-09 02:51 UTC by yummypeng

Since `Copier.Run()` won't return any error, it would be confusing to
users if an error is returned when `Decode` in `TestCopier()` but it
actually comes from `Copier.Run()`. So it's better to check if an
error occurred during the process of `Copier.Run()` before `Decode`.

Signed-off-by: Yuanhong Peng <pengyuanhong@huawei.com>

2017-03-09 03:37 UTC, AkihiroSuda requested changes

2017-03-09 03:37 UTC, AkihiroSuda commented on daemon/logger/copier.go
> +	err error
seems racy

2017-03-09 07:11 UTC, yummypeng commented on daemon/logger/copier.go
> +	err error
Thank you for code review. :stuck_out_tongue_winking_eye: 
I changed it to be a map to avoid race. PTAL @AkihiroSuda

2017-03-09 07:32 UTC, AkihiroSuda commented on daemon/logger/copier.go
> +	err error
we still need a mutex

2017-03-09 12:23 UTC, yummypeng commented on daemon/logger/copier.go
> +	err error
Sorry for misunderstanding what you meant. I add a mutex now.

2017-03-09 13:57 UTC, cpuguy83 commented
I don't think we should take this.
Errors here are not able to be propagated anywhere other than logging them.

As far as the tests go, these errors are not related to the copier itself and out of the control of the package, so it seems a little weird account for them in the tests.

2017-03-10 03:42 UTC, yummypeng commented
Oh, I see..Close it !

2017-03-10 03:42 UTC, closed without merging