TestDuplicateMountpointsForVolumesFromAndMounts: remove unintentional dependency for /tmp/data
moby/moby pull request #31687
Opened 2017-03-09 09:35 UTC by AkihiroSuda

/tmp/data needs to be created before running this test (by some other test)

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2017-03-09 14:00 UTC, cpuguy83 requested changes

2017-03-09 14:00 UTC, cpuguy83 commented on integration-cli/docker_cli_volume_test.go
> +	err := os.MkdirAll("/tmp/data", 0755)
Need to set a test requirement for`SameHostDaemon` with this

2017-03-10 02:04 UTC, AkihiroSuda commented on integration-cli/docker_cli_volume_test.go
> +	err := os.MkdirAll("/tmp/data", 0755)
done

2017-03-10 02:14 UTC, cpuguy83 approved these changes
LGTM

2017-03-15 10:30 UTC, AkihiroSuda commented
@vdemeester PTAL?

2017-03-15 13:15 UTC, vdemeester approved these changes
LGTM 🐸

2017-03-15 13:15 UTC, merged