Log payload only [logentries]
moby/moby pull request #31727
Opened 2017-03-10 09:35 UTC by sascha-andres

If you want to use the advanced query in logentries
logging in json is very useful. If you do not need
the advanced information with
--log-opt logentries-line-only=true just logs the payload

Created issue for enhancement: #31726

2017-03-10 09:35 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "31726-le-lion-only" git@github.com:sascha-andres/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-10 13:57 UTC, cpuguy83 commented
It may be helpful to have this available to all drivers.
Particularly if people are already using structured logging.

2017-03-10 14:24 UTC, thaJeztah commented
That sounds similar to https://github.com/docker/docker/issues/24898, https://github.com/docker/docker/issues/17020 ?

2017-03-10 14:38 UTC, sascha-andres commented
#24652 implements this for splunk when a logging option with value raw is set. It seems that similar requirements pop up for different logging drivers. Basically, wrapping into a serialized go map makes it harder for our devs to analyse logs generated by apache or php within the containers. Therefore I came up with this and have not found something like this for logentries

2017-05-30 21:37 UTC, kevin-bockman commented
I am using Logentries as well and am running into this same problem. This PR seemed to have stalled. Can this be merged?

2017-06-08 20:52 UTC, LK4D4 commented
For move this forward I propose to just use generic `line-only` name(without logentries part), but implement only for logentries.
@sascha-andres @vdemeester @cpuguy83

2017-06-09 04:48 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "31726-le-lion-only" git@github.com:sascha-andres/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354335024
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-06-09 04:52 UTC, sascha-andres commented
@LK4D4 Adjusted from logentries-line-only to line-only

2017-06-22 02:02 UTC, cpuguy83 commented
Design OK.

2017-06-22 02:02 UTC, cpuguy83 requested changes

2017-06-22 02:02 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +	if "" == info.Config[lineonly] {
```
if _, exists := info.Config[lineOnly]; exists {
  // do strconv
}
```

There is no need to explicitly set false.
I think we should error out if nothing is set, which will happen with `ParseBool`

2017-06-22 02:02 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +			return nil, err
Please use `errors.Wrap` to provide context to the error.

2017-06-30 12:26 UTC, sascha-andres reviewed
@cpuguy83 Changed implementation

2017-07-03 20:13 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
We can't `PutMessage` until all the values are copied.
I think in this case we just need to copy `msg.TimeStamp`

2017-07-11 18:52 UTC, LK4D4 commented
@sascha-andres would you mind to fix comments? Thanks!

2017-07-12 11:58 UTC, sascha-andres commented
@LK4D4 I will take a look and report back.

2017-07-27 06:11 UTC, sascha-andres commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
Just to be sure about this. The original source code looks like this:

```
data := map[string]string{
    "container_id":   f.containerID,
    "container_name": f.containerName,
    "source":         msg.Source,
    "log":            string(msg.Line),
}
for k, v := range f.extra {
    data[k] = v
}
ts := msg.Timestamp // ts used for Printf later, I used msg.Timestamp directly
logger.PutMessage(msg)
```
You are proposing adding the timestamp to data in addition to the one included in msg?

2017-07-28 15:38 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
That seems like it would work since we aren't actually modifying the timestamp itself at any point.

2017-07-28 15:39 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
Sorry, let me clarify, the current code is doing a `PutMessage`, as such you can't use `msg.Timestamp` reliably below in the `Println`

You will have to `ts := msg.Timestamp // ts used for Printf later, I used msg.Timestamp directly` and use `ts`.

2017-07-28 15:40 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
Likewise here you can't `PutMessage` and then use `msg.Line`.

2017-07-29 10:47 UTC, sascha-andres commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
Thanks for your explanation. Changed the code to reflect my new understanding

2017-07-29 10:47 UTC, sascha-andres commented on daemon/logger/logentries/logentries.go
> +		logger.PutMessage(msg)
Thanks for your explanation. Changed the code to reflect my new understanding

2017-08-04 12:34 UTC, thaJeztah commented
@sascha-andres looks like this needs a rebase due to the `github.com/Sirupsen/logrus` -> `github.com/sirupsen/logrus` rename; can you also squash your commits?

2017-08-04 12:41 UTC, sascha-andres commented
@thaJeztah Will squash and rebase

2017-08-05 14:14 UTC, cpuguy83 commented on daemon/logger/logentries/logentries.go
> +		return nil, errors.Wrap(err, "error parsing lineonly option")
nit `line-only`

2017-08-05 14:15 UTC, cpuguy83 approved these changes
LGTM

2017-08-22 12:59 UTC, vdemeester approved these changes
LGTM 🐮

2017-08-22 12:59 UTC, merged