Windows: Balk on --privileged
moby/moby pull request #31740
Opened 2017-03-10 17:43 UTC by jhowardmsft

Signed-off-by: John Howard (VM) <jhoward@ntdev.microsoft.com>

Throws an error if privileged mode is attempted on Windows where the platform does not support it. Fixes https://github.com/docker/docker/issues/31059 @thaJeztah

2017-03-10 18:42 UTC, cpuguy83 commented on runconfig/hostconfig_windows.go
> +		return fmt.Errorf("invalid --privileged: Windows does not support this feature")
"privileged mode is not supported on Windows"

2017-03-10 19:12 UTC, jhowardmsft commented on runconfig/hostconfig_windows.go
> +		return fmt.Errorf("invalid --privileged: Windows does not support this feature")
Consistency https://github.com/docker/docker/blob/master/runconfig/hostconfig_windows.go#L67 
😇

2017-03-10 20:46 UTC, thaJeztah commented on runconfig/hostconfig_windows.go
> +		return fmt.Errorf("invalid --privileged: Windows does not support this feature")
That's ok for now; agreed on consistency. Given that the API can be used separate from the docker-cli, we should probably update them all at some point.

@jhowardmsft perhaps you can review https://github.com/docker/docker/pull/30788 as well, which handles these things on the client?

2017-03-10 20:52 UTC, thaJeztah requested changes
one nit, but looks good otherwise

2017-03-10 20:52 UTC, thaJeztah commented on runconfig/hostconfig_windows.go
> +func ValidatePrivileged(hc *container.HostConfig) error {
Looks like this function doesn't have to be exported (I realize some of the others probably don't have to be exported as well)

2017-03-10 20:52 UTC, thaJeztah commented
Thanks!

2017-03-11 02:21 UTC, jhowardmsft commented
@thaJeztah Updated to not export, along with the other relevant functions.

2017-03-11 11:09 UTC, thaJeztah commented
oh it's failing;

```
02:47:59 runconfig/hostconfig_windows_test.go:11: TestvalidatePrivileged has malformed name: first letter after 'Test' must not be lowercase

2017-03-13 15:56 UTC, jhowardmsft commented
Casing fixed.

2017-03-13 15:59 UTC, thaJeztah approved these changes
LGTM

2017-03-13 20:35 UTC, justincormack approved these changes

2017-03-13 20:35 UTC, merged