Fix stringer in Result (pkg\testutil\cmd)
moby/moby pull request #31752
Opened 2017-03-10 23:23 UTC by jhowardmsft

Signed-off-by: John Howard (VM) <jhoward@ntdev.microsoft.com>

@vdemeester Fixes the error output [and aligns (I'm just like that 😇)]. The `%s` for error should have been a `%v`.

Before:

```
00:14:51.046 Command: d:\CI\CI-0b8f46bb6\binary\docker.exe ps -f status=paused -q -a
00:14:51.046 ExitCode: 0, Error: %!s(<nil>)
00:14:51.046 Stdout: 
00:14:51.046 Stderr: 
```

After:

```
Command:  e:\go\src\github.com\docker\docker\bundles\docker.exe ps -f status=paused -q -a
ExitCode: 0
Error:    <nil>
Stdout:
Stderr:
```

2017-03-11 03:00 UTC, AkihiroSuda commented on pkg/testutil/cmd/command.go
> +	fmt.Println("**** Assert failed")
fmt.Println -> t.Logf

2017-03-11 03:00 UTC, AkihiroSuda commented on pkg/testutil/cmd/command.go
> +		t.Fatalf("at %s:%d\n%s", filepath.Base(file), line, err.Error())
\n unneeded

2017-03-12 10:07 UTC, vdemeester requested changes

2017-03-12 10:07 UTC, vdemeester commented on pkg/testutil/cmd/command.go
> +	fmt.Println("**** Assert failed")
@AkihiroSuda Definitely 😻

2017-03-13 03:48 UTC, AkihiroSuda commented on pkg/testutil/cmd/command.go
> +	fmt.Println("**** Assert failed")
rather, we can just remove this

2017-03-13 15:39 UTC, jhowardmsft commented
@AkihiroSuda @vdemeester haha - that was part of my debugging, shouldn't have been there. Removed and force pushed.

2017-03-13 15:45 UTC, vdemeester approved these changes
LGTM 🐯

2017-03-13 16:46 UTC, AkihiroSuda approved these changes
LGTM if green

2017-03-13 17:44 UTC, aaronlehmann commented
LGTM

2017-03-13 19:33 UTC, thaJeztah commented
all green

2017-03-13 19:33 UTC, merged