Fix zsh-completion for containers in status 'created'
moby/moby pull request #31891
Opened 2017-03-16 16:35 UTC by ngaro

This patch makes sure that containers in the created-stated are
counted as stopped containers. Otherwise if you create a container,
don't run it and type: "docker rm ", followed by pressing tab in zsh, it won't show up.

Signed-off-by: Nikolas Garofil <nikolas.garofil@uantwerpen.be>

2017-03-17 08:44 UTC, albers commented
ping @sdurrheimer

2017-03-17 09:17 UTC, vdemeester approved these changes
LGTM 🐯

2017-03-17 09:53 UTC, sdurrheimer requested changes

2017-03-17 09:53 UTC, sdurrheimer commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Exit* ]] || [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Created* ]] ; then
```
if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = (Exit*|Created*) ]]; then
```

2017-03-17 09:53 UTC, sdurrheimer commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Exit* ]] || [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Created* ]] ; then
same here

2017-03-17 13:40 UTC, ngaro commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Exit* ]] || [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Created* ]] ; then
Although they do exactly the same thing, your code is a cleaner than mine, so I agree it's probably best to take your version.
Should I create a new pull request with your code or are you guys going to handle the rest ?

2017-03-17 13:43 UTC, vdemeester commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Exit* ]] || [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Created* ]] ; then
@ngaro you can update your code and `ammend` the commit 😉

2017-03-17 17:19 UTC, ngaro commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Exit* ]] || [[ ${line[${begin[STATUS]},${end[STATUS]}]} = Created* ]] ; then
I tried this, meanwhile fearing github would explode killing everyone in the neighbourhood, but when I look at https://github.com/docker/docker/pull/31891/files it seems that it worked...

2017-03-17 20:54 UTC, thaJeztah requested changes
Left some tiny nitpicks, otherwise LGTM

@sdurrheimer LGTY?

2017-03-17 20:54 UTC, thaJeztah commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = (Exit*|Created*) ]] ; then
I'm gonna be very nit-picky, but can you remove the extra space before the semicolon, to keep a consistent coding style in this file? 😅

2017-03-17 20:54 UTC, thaJeztah commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = (Exit*|Created*) ]] ; then
same here


(ducks)

2017-03-18 01:17 UTC, ngaro commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = (Exit*|Created*) ]] ; then
done...

2017-03-18 01:17 UTC, ngaro commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = (Exit*|Created*) ]] ; then
... and done

2017-03-18 02:09 UTC, thaJeztah commented on contrib/completion/zsh/_docker
> +            if [[ ${line[${begin[STATUS]},${end[STATUS]}]} = (Exit*|Created*) ]] ; then
❤️ thanks!

2017-03-18 02:09 UTC, thaJeztah approved these changes
LGTM!

2017-03-18 02:09 UTC, merged