specify max size for secret in doc
moby/moby pull request #31911
Opened 2017-03-17 06:53 UTC by allencloud

Signed-off-by: allencloud <allen.sun@daocloud.io>

I think we should explain the max size for secret in docs, since it has been specified in https://github.com/docker/swarmkit/blob/master/manager/controlapi/secret.go#L21

**- What I did**
1. specify max size for secret in doc

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-03-17 07:35 UTC, thaJeztah commented on docs/reference/commandline/secret_create.md
> +command on a manager node. The content of secret must be less than 500 KB.
I'm not sure it should be part of the first paragraph; I think having some paragraphs after this that describe what secrets are could work though. Perhaps we should either _copy_  (a shortened version of) the "about secrets" section; https://docs.docker.com/engine/swarm/secrets/#about-secrets 

At least we need to add a link to the page (https://docs.docker.com/engine/swarm/secrets/) somewhere in this reference doc

2017-03-27 05:27 UTC, allencloud commented on docs/reference/commandline/secret_create.md
> +command on a manager node. The content of secret must be less than 500 KB.
I can feel some kind of improper adding this in the first paragraph. How about the updated format? @thaJeztah

2017-03-27 16:42 UTC, thaJeztah requested changes

2017-03-27 16:42 UTC, thaJeztah commented on docs/reference/commandline/secret_create.md
> +command on a manager node. We can get details about created secret from [here](https://docs.docker.com/engine/swarm/secrets/#about-secrets).
I was thinking something like this, would that work for you?

```Markdown
Creates a secret using standard input or from a file for the secret content. You must run this
command on a manager node.

For detailed information about using secrets, refer to [manage sensitive data with Docker secrets](https://docs.docker.com/engine/swarm/secrets/).
```

Perhaps the same should be added to the other "secret" pages in the command-line reference.

2017-03-28 02:12 UTC, allencloud commented on docs/reference/commandline/secret_create.md
> +command on a manager node. We can get details about created secret from [here](https://docs.docker.com/engine/swarm/secrets/#about-secrets).
Yeah, I think that is reasonable. Tried to update that. PTAL

2017-03-28 08:17 UTC, vdemeester approved these changes
LGTM 🐸

2017-03-28 10:59 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-03-28 10:59 UTC, merged