Windows: graph cleanup '-removing'
moby/moby pull request #31928
Opened 2017-03-17 22:01 UTC by jhowardmsft

Signed-off-by: John Howard (VM) <jhoward@ntdev.microsoft.com>

@darrenstahlmsft PTAL. Adds code to the graphdriver cleanup to delete any left-over `-removing` directories. These might remain on disk if a previous daemon instance was killed without a chance to cleanup.

2017-03-17 22:17 UTC, darrenstahlmsft commented
Not a maintainer, but LGTM 👍

2017-03-20 12:25 UTC, thaJeztah reviewed
left two nits/questions, but LGTM otherwise

2017-03-20 12:25 UTC, thaJeztah commented on daemon/graphdriver/windows/windows.go
> +				logrus.Infof("Cleaned up %s", item.Name())
Wondering if this is "info" or "debug" information. Looking for other cleanup actions, those seem to use `Debug`;
https://github.com/docker/docker/blob/7c62f58b27f98140ff3d39de166bf2e107e84a65/plugin/blobstore.go#L69
https://github.com/docker/docker/blob/f67d4b897adc9048269d1b91435b6dcbf69e36d1/libcontainerd/container_windows.go#L61

Open to input what would be best 👍

2017-03-20 12:25 UTC, thaJeztah commented on daemon/graphdriver/windows/windows.go
> +	// Note we don't return an error on cleanup failure, but do log a warning.
This comment is a bit odd, because the first error below actually doesn't log anything 😅

2017-03-20 12:35 UTC, vdemeester requested changes

2017-03-20 12:35 UTC, vdemeester commented on daemon/graphdriver/windows/windows.go
> +		return nil
If we want to return `nil` here, let's at least log the error.

2017-03-20 12:35 UTC, vdemeester commented on daemon/graphdriver/windows/windows.go
> +		if item.IsDir() && strings.HasSuffix(item.Name(), "-removing") {
```go
if !item.IsDir() || !strings.HasSuffix(item.Name(), "-removing") {
    continue
}
// […]
```

2017-03-20 16:12 UTC, jhowardmsft commented on daemon/graphdriver/windows/windows.go
> +	// Note we don't return an error on cleanup failure, but do log a warning.
That's fair - moved it lower down and clarified.

2017-03-20 16:12 UTC, jhowardmsft commented on daemon/graphdriver/windows/windows.go
> +				logrus.Infof("Cleaned up %s", item.Name())
I think these logs are correct here. Will make sense with the updated comment. It's not debugging information.

2017-03-20 16:14 UTC, jhowardmsft commented on daemon/graphdriver/windows/windows.go
> +		return nil
Updated. This one is highly unlikely to fail, so returning the error

2017-03-20 16:14 UTC, jhowardmsft commented on daemon/graphdriver/windows/windows.go
> +		if item.IsDir() && strings.HasSuffix(item.Name(), "-removing") {
Why? IMHO the current way is more understandable.... 😇

2017-03-20 16:15 UTC, vdemeester commented on daemon/graphdriver/windows/windows.go
> +		if item.IsDir() && strings.HasSuffix(item.Name(), "-removing") {
I have OCD on complexity and *nested if*, that's all 😅.

2017-03-20 19:02 UTC, thaJeztah commented on daemon/graphdriver/windows/windows.go
> +				logrus.Infof("Cleaned up %s", item.Name())
Thanks for looking; I'm ok with keeping it as info then 👍

2017-03-20 19:03 UTC, thaJeztah approved these changes
LGTM

2017-03-21 08:43 UTC, vdemeester approved these changes
LGTM 🐻

2017-03-21 08:43 UTC, merged