Update system df docs to call out performance implications
moby/moby pull request #31973
Opened 2017-03-21 16:12 UTC by wsong

Signed-off-by: Wayne Song <wsong@docker.com>

2017-03-21 16:38 UTC, thaJeztah requested changes
one minor nit, but LGTM otherwise, thanks!

2017-03-21 16:38 UTC, thaJeztah commented on docs/reference/commandline/system_df.md
> +The system df command can be very resource-intensive. It traverses the
can you add backticks around `system df` ?

2017-03-21 16:40 UTC, wsong commented on docs/reference/commandline/system_df.md
> +The system df command can be very resource-intensive. It traverses the
Done.

2017-03-21 19:42 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-03-21 19:42 UTC, thaJeztah commented
ping @mlaventure @vdemeester PTAL

2017-03-22 02:00 UTC, mlaventure requested changes

2017-03-22 02:00 UTC, mlaventure commented on docs/reference/commandline/system_df.md
> +filesystem of every container and every volume in the system. You should be
`every image, container, and volume`

2017-03-22 02:00 UTC, mlaventure commented on docs/reference/commandline/system_df.md
> +in systems where some containers or volumes have very large filesystems with
`where some images, containers, or volumes`

2017-03-22 08:49 UTC, wsong commented
Addressed comments.

2017-03-22 12:46 UTC, vdemeester approved these changes
LGTM 🐯

2017-03-22 12:46 UTC, merged