Add note regarding Windows VOLUME limitations
moby/moby pull request #31980
Opened 2017-03-21 19:36 UTC by JohnMaguire

**- What I did**

I added a note regarding some limitations of Docker volumes on Windows to the builder documentation under the `VOLUME` header.

**- How I did it**

With the uncontested, greatest editor of all time, vim.

**- How to verify it**

N/A

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

![](https://i.imgur.com/QtRul5x.png)

2017-03-21 19:36 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "doc-update" git@github.com:JohnMaguire/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-21 19:39 UTC, JohnMaguire commented on docs/reference/builder.md
> +
I ripped this text off of here: https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volume--v---read-only

Original read:

> The following examples will fail when using Windows-based containers, as the destination of a volume or bind-mount inside the container must be one of: a non-existing or empty directory; or a drive other than C:. Further, the source of a bind mount must be a local directory, not a file.

2017-03-22 13:12 UTC, thaJeztah requested changes
Thanks for working on this! I left some comments, could you make those changes and amend your commit?

Also ping @jhowardmsft @johnstep for review

2017-03-22 13:12 UTC, thaJeztah commented on docs/reference/builder.md
> +> bind-mount inside the container must be one of: a non-existing or empty
Can you remove `or bind-mount` here? Bind mounts are not used in Dockerfiles

2017-03-22 13:12 UTC, thaJeztah commented on docs/reference/builder.md
> +> directory; or a drive other than C:. Further, the source of a bind mount must
Same here; can you remove "Further, the source of a bind mount must be a local directory, not a file." ?

2017-03-22 18:46 UTC, JohnMaguire commented
@thaJeztah Thanks for the comments, updated!

2017-03-22 18:50 UTC, thaJeztah approved these changes
perfect! LGTM

2017-03-22 18:52 UTC, jhowardmsft commented
Text is good. Just questioning whether it's really a `warning`. Should it not be a `note`?

2017-03-22 18:54 UTC, thaJeztah commented
"note" works for me

2017-03-22 18:58 UTC, JohnMaguire commented
👍  Updated.

2017-03-22 19:00 UTC, jhowardmsft commented
LGTM. Thanks @JohnMaguire. 👍

2017-03-22 19:01 UTC, merged