update: include a note regarding the image
moby/moby pull request #32005
Opened 2017-03-22 15:56 UTC by MickelSierra85

Update the description of `docker save` such that it will include `docker pull`.

2017-03-22 15:58 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-1" git@github.com:MickelSierra85/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-23 01:22 UTC, AkihiroSuda commented
If we want to add this note, we need to update the corresponding `--help` code as well

2017-03-26 10:28 UTC, vdemeester requested changes
ping @MickelSierra85 : You need to sign-off your commit, and I do agree with @AkihiroSuda on updating `--help` code too 👼 

/cc @thaJeztah

2017-03-28 11:55 UTC, thaJeztah commented
I'm closing this PR because it's missing a sign-off, and it's only a minor enhancement

2017-03-28 11:55 UTC, closed without merging