Update stackoverflow question count
moby/moby pull request #32055
Opened 2017-03-23 21:23 UTC by FabianLauer

There's ~27k questions by now, not just 7k  :wink:

2017-03-24 12:35 UTC, cpuguy83 commented on CONTRIBUTING.md
> +      Stack Overflow has over 27000 Docker questions listed. We regularly
How about just `thousands`?

2017-03-24 12:49 UTC, cpuguy83 commented on CONTRIBUTING.md
> +      Stack Overflow has over 27 thousand Docker questions listed. We regularly
I meant changing form such a specific number like 27k, to simply "Stack Overflow has thousands of Docker questions listed."

2017-03-24 12:52 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "so-counters" git@github.com:FabianLauer/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354515584
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-24 12:54 UTC, FabianLauer commented on CONTRIBUTING.md
> +      Stack Overflow has over 27 thousand Docker questions listed. We regularly
Oh, sure

2017-03-24 15:47 UTC, AkihiroSuda approved these changes
LGTM

2017-03-24 16:03 UTC, thaJeztah requested changes

2017-03-24 16:03 UTC, thaJeztah commented on CONTRIBUTING.md
> +      Stack Overflow has over thousands of Docker questions listed. We regularly
"over thousands" needs to be "thousands" 😊

2017-03-24 16:10 UTC, FabianLauer commented on CONTRIBUTING.md
> +      Stack Overflow has over thousands of Docker questions listed. We regularly
Oh gawd, I'm so sorry 🙈 
I owe you one guys.

2017-03-24 16:11 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "so-counters" git@github.com:FabianLauer/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354215552
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-28 11:09 UTC, thaJeztah commented
Thanks @FabianLauer. Can you squash your commits, so that there's a single commit in this PR? You can find some instructions here; https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently, but let us know if you need help 👍

2017-04-08 17:54 UTC, tonistiigi commented
ping @FabianLauer

2017-04-09 21:04 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-04-09 21:05 UTC, merged