update 3 old docs about secret in docs/reference/commandline/
moby/moby pull request #32075
Opened 2017-03-24 08:51 UTC by uhayate

When I browse the document about `docker secret`, I found that some of these three documents out of date, they are:
docs/reference/commandline/secret_create.md,
docs/reference/commandline/secret_inspect.md,
docs/reference/commandline/secret_ls.md.

In the latest version, `docker secret ls`, `docker secret create`, `docker secret inspect` prints out the results at the console have changed, but the old document did not synchronize these changes.

Signed-off-by: uhayate <uhayate.gong@daocloud.io>

2017-03-24 10:05 UTC, thaJeztah requested changes
thanks!! some small nits, but looks good otherwise :+1:

/cc @vdemeester

2017-03-24 10:05 UTC, thaJeztah commented on docs/reference/commandline/secret_create.md
> -
same here (blank line)

2017-03-24 10:05 UTC, thaJeztah commented on docs/reference/commandline/secret_create.md
> -
same here (blank line)

2017-03-24 10:12 UTC, vdemeester approved these changes
LGTM 🐯

2017-03-24 10:15 UTC, uhayate commented on docs/reference/commandline/secret_create.md
> -
OK. You are right.

2017-03-24 10:17 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "update_old_docs" git@github.com:uhayate/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354408888
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-03-24 10:29 UTC, thaJeztah commented
Oh, looks like this needs to be squashed, one commit is missing a sign off; let me know if you need help

2017-03-26 02:31 UTC, allencloud commented
Squashed now. PTAL @thaJeztah

2017-03-26 10:41 UTC, thaJeztah approved these changes
LGTM, thank you so much!

2017-03-26 10:41 UTC, merged