Bump up nproc in TestExecUlimits
moby/moby pull request #32076
Opened 2017-03-24 11:24 UTC by tmp6154

Bump up nproc from 21 to 121, because in some environments, such as
inside Virtuozzo Containers, number of processes is higher and testcase
fails.

Signed-off-by: Vitaly Ostrosablin <vostrosablin@virtuozzo.com>

2017-03-24 12:27 UTC, cpuguy83 commented
Maybe `nofile` is a better test here.

2017-04-01 18:54 UTC, vdemeester requested changes
I do agree with @cpuguy83, using `nofile` here would be better.

2017-04-03 07:49 UTC, tmp6154 commented
Here's testcase changed to set nofile instead of nproc.

2017-04-03 12:29 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:tmp6154/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354404248
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-03 13:11 UTC, cpuguy83 approved these changes
LGTM

2017-04-03 13:15 UTC, vdemeester reviewed
@tmp6154 could you squash the commits ? (the merge commit shouldn't be there I think 👼)

2017-04-03 13:44 UTC, tmp6154 commented
Done

2017-04-03 13:45 UTC, vdemeester approved these changes
LGTM 🦁

2017-04-03 20:30 UTC, vdemeester commented
Powerpc failure is unrelated and a known flakey test, let's merge 👼

2017-04-03 20:30 UTC, merged