Fix Healthcheck API doc
moby/moby pull request #32107
Opened 2017-03-25 12:46 UTC by mkumatag

Fixes : #32089

2017-03-26 10:47 UTC, vdemeester commented
SGTM but ping @talex5 to be sure 👼

2017-03-26 10:49 UTC, thaJeztah requested changes

2017-03-26 10:49 UTC, thaJeztah commented on api/types/container/config.go
> +	// ["CMD-SHELL", command] : run command with system's default shell
This is GoDoc, not JSON, so these probably should not be changed

2017-03-26 12:47 UTC, mkumatag commented on api/types/container/config.go
> +	// ["CMD-SHELL", command] : run command with system's default shell
@thaJeztah roll-backed the changes on this file, PTAL at latest commit.

2017-03-26 17:59 UTC, vdemeester approved these changes
LGTM 🐸

2017-03-27 16:44 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-03-27 16:45 UTC, thaJeztah commented
failing CI is not related

2017-03-27 16:45 UTC, merged

2017-03-27 17:29 UTC, mkumatag commented
Thanks @thaJeztah