Add details for inspect command usage
moby/moby pull request #32112
Opened 2017-03-26 10:24 UTC by vdemeester

Carrying #31738

---

Updated documentation on docker inspect sub-command.

/cc @thaJeztah @mstanleyjones 

🦁

Signed-off-by: Eric G. Noriega <egnoriega@users.noreply.github.com>
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2017-03-27 02:20 UTC, allencloud commented on docs/reference/commandline/inspect.md
> +to the request.  In addition inspect can target any construct type, which may further
I think that we have a double white spaces here in `request.  In addition`. Could us remove one? 😄

2017-03-27 02:50 UTC, allencloud commented
I found that secret was not a inspect type, and should we add that? (currently docker/master does not support `docker inspect secret_name`)

2017-03-27 07:43 UTC, vdemeester commented on docs/reference/commandline/inspect.md
> +to the request.  In addition inspect can target any construct type, which may further
😂

2017-03-27 07:44 UTC, vdemeester commented
oohh intersting 😅 (cc @icecrime :trollface:) @allencloud I'll take a look 👼

2017-03-28 09:02 UTC, thaJeztah requested changes
left a suggestion, but let me know what you think 👍

2017-03-28 09:02 UTC, thaJeztah commented on docs/reference/commandline/inspect.md
> +## Request a custom response format (--format)
can you add a blank line after this heading?

2017-03-28 09:02 UTC, thaJeztah commented on docs/reference/commandline/inspect.md
> +It has always been possible for a container to be assigned the same name as an image.
Would this work (as there's more possibilities than just "images" and "containers" to have the same name);

    The `docker inspect` command matches any type of object by either ID or name.
    In some cases multiple type of objects (for example, a container and a volume)
    exist with the same name, making the result ambigious.

    To restrict `docker inspect` to a specific type of object, use the `--type`
    option.

    The following example inspects a _volume_ named "myvolume"

    ```bash
    $ docker inspect --type=volume myvolume
    ```

2017-03-28 09:38 UTC, thaJeztah approved these changes
LGTM

2017-03-28 10:43 UTC, boaz0 approved these changes
LGTM 2

2017-03-28 10:49 UTC, merged