Adopt text/template in node inspect
moby/moby pull request #32116
Opened 2017-03-26 17:24 UTC by mkumatag

**- What I did**
Changed the node inspect code to use text/template instead of using Sprintf. This was actually one of the TODO task in that file - https://github.com/docker/docker/blob/master/cli/command/node/inspect.go#L81

2017-03-26 17:33 UTC, vdemeester requested changes
I think the idea was more to mimic what we did for the other inspect command, like on `service inspect` https://github.com/docker/docker/blob/master/cli/command/service/inspect.go#L11 — reusing and completing the `cli/formatter` package 👼

2017-03-26 18:12 UTC, mkumatag commented
@vdemeester make sense, spent some more time to understand `service inspect`. I could relate what I've submitted part of this PR. Let me refactor my code to align to `cli/formatter` package.

2017-03-28 15:04 UTC, mkumatag commented
@vdemeester refactored the code using `cli/formatter`, PTAL at latest commit.

2017-03-28 18:09 UTC, cpuguy83 commented
```
11:16:16 --- FAIL: TestNodeInspectErrors (0.00s)
11:16:16 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
11:16:16 	panic: runtime error: invalid memory address or nil pointer dereference
11:16:16 [signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x483a39]
11:16:16 
11:16:16 goroutine 13 [running]:
11:16:16 panic(0x7ccb40, 0xc4200100a0)
11:16:16 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
11:16:16 testing.tRunner.func1(0xc42007ad80)
11:16:16 	/usr/local/go/src/testing/testing.go:579 +0x25d
11:16:16 panic(0x7ccb40, 0xc4200100a0)
11:16:16 	/usr/local/go/src/runtime/panic.go:458 +0x243
11:16:16 github.com/docker/docker/cli/command/node.runInspect(0xc353c0, 0xc42007af00, 0xc4202e7aa0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4202e7aa0, 0x1)
```

2017-03-29 18:30 UTC, mkumatag commented
@vdemeester all jobs got passed except windowsRS1 one, not sure whats wrong with it.!

2017-04-07 17:40 UTC, mkumatag commented
@vdemeester ping

2017-04-10 08:24 UTC, vdemeester reviewed
design LGTM
/cc @thaJeztah @dnephin @AkihiroSuda @cpuguy83

2017-04-10 08:24 UTC, vdemeester commented on cli/command/formatter/node.go
> +	//	"github.com/docker/distribution/reference"
Should remove the commented import/code 👼

2017-04-10 08:42 UTC, GordonTheTurtle commented
Looks like we would not be able to merge this PR because of merge conflicts. Please rebase, fix conflicts, and force push to your branch.

2017-04-10 12:18 UTC, mkumatag commented on cli/command/formatter/node.go
> +	//	"github.com/docker/distribution/reference"
@vdemeester fixed your comment and rebased the branch, PTAL into latest commit

2017-04-10 12:44 UTC, vdemeester approved these changes
LGTM (design & code) 🐻

2017-04-10 18:55 UTC, dnephin approved these changes
LGTM

2017-04-10 21:02 UTC, merged