Add support for `--type=secret` in `docker inspect`
moby/moby pull request #32124
Opened 2017-03-27 08:00 UTC by vdemeester

Taking into account @allencloud, add support for `docker inspect --type=secret` because, why not 👼.

/cc @icecrime :trollface: @thaJeztah @cpuguy83 @AkihiroSuda @dnephin @tiborvass 

🦁

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2017-03-27 08:28 UTC, thaJeztah commented
design LGTM

2017-03-27 08:36 UTC, thaJeztah requested changes

2017-03-27 08:36 UTC, thaJeztah commented on cli/command/system/inspect.go
> +			objectInspector: inspectSecret(ctx, dockerCli),
isSwarmObject: true,

2017-03-27 08:37 UTC, vdemeester commented on cli/command/system/inspect.go
> +			objectInspector: inspectSecret(ctx, dockerCli),
@thaJeztah nice I missed that one 👼

2017-03-27 08:41 UTC, allencloud commented
That is great. Thanks a lot. @vdemeester 
Eh... Please do not forget to update inspect.md under command docs directory. 😄

2017-03-27 08:42 UTC, vdemeester commented
>  Eh... Please do not forget to update inspect.md under command docs directory. 😄

Right, I was waiting for it to pass `design` phase but.. it's already the case 😛

2017-03-27 16:27 UTC, ehazlett commented
design lgtm

2017-03-28 08:50 UTC, vdemeester commented
@thaJeztah completions scripts updated (cc @sdurrheimer @albers)

2017-03-28 09:30 UTC, thaJeztah approved these changes
code LGTM, but needs updates to the documentation as mentioned above :smile:

2017-03-28 09:39 UTC, thaJeztah commented
docs is being taken care of in https://github.com/docker/docker/pull/32112

2017-03-28 18:23 UTC, albers commented
Bash completion tested locally, perfect!

2017-03-30 13:01 UTC, ehazlett commented
LGTM

2017-03-30 13:05 UTC, thaJeztah commented
pssst @ehazlett; looks like it can be moved to `status/4-merge` 😇

2017-03-30 15:01 UTC, merged

2017-03-30 18:56 UTC, sdurrheimer commented on contrib/completion/zsh/_docker
> +                    elif [[ ${words[(r)--type=service]} == --type=secrets ]]; then
Sorry for looking at this too late, should be `elif [[ ${words[(r)--type=secrets]}` not `elif [[ ${words[(r)--type=service]}`

2017-03-30 19:06 UTC, vdemeester commented on contrib/completion/zsh/_docker
> +                    elif [[ ${words[(r)--type=service]} == --type=secrets ]]; then
oh shit, my bad I missed one 😱 I'll fix 👼

2017-03-30 19:07 UTC, thaJeztah commented on contrib/completion/zsh/_docker
> +                    elif [[ ${words[(r)--type=service]} == --type=secrets ]]; then
Oh, thanks of the catch; can you open a pull request to fix that, or want someone else to do that?