Clean `docker run -e` reference docs
moby/moby pull request #32180
Opened 2017-03-28 17:23 UTC by joaofnfernandes

Simplified the docs on how to set environment variables in a
container. Makes it clear that you have three options, and how
to use them.

Relates to docker/docker.github.io#2355

Signed-off-by: Joao Fernandes <joao.fernandes@docker.com>

2017-03-30 18:25 UTC, mdlinville requested changes
Just a few suggestions. It might be good to also visit the Dockerfile reference and make sure its info about environment variables is consistent.

Have you tested how environment variables work on Windows containers? It might be good to show an example of them in action and how they manifest within the container.

2017-03-30 18:25 UTC, mstanleyjones commented on docs/reference/commandline/run.md
> +You can also use variables that you've exported to your local environment:
I would caveat here that this is depending on your local environment and that it's less predictable than specifying the vars on the  command line or in the Dockerfile.

2017-03-30 18:25 UTC, mstanleyjones commented on docs/reference/commandline/run.md
> +If no `=` is provided and that variable is not exported in your local
Are you sure it won't be set to an empty value?

2017-03-30 18:25 UTC, mstanleyjones commented on docs/reference/commandline/run.md
> +The `-e`, `--env`, and `--env-file` flags allow you to set simple (non-array)
I like a more active sentence like:

Use the `-e`, `--env`, and `--env-file` flags to set simple (non-array) environment variables within the container.

2017-03-31 18:44 UTC, joaofnfernandes commented on docs/reference/commandline/run.md
> +If no `=` is provided and that variable is not exported in your local
Yup, it won't be set

```
docker run -e VAR1 ubuntu env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=e5c77d8efe0a
HOME=/root
```

2017-03-31 18:44 UTC, joaofnfernandes commented on docs/reference/commandline/run.md
> +You can also use variables that you've exported to your local environment:
I included a small caveat after the snippet. I agree that you should make the declaration of variables as explicit as possible, and I bet most uses for setting variables from the environment where for situations that are now covered by secrets.

2017-04-03 13:42 UTC, vdemeester approved these changes
LGTM 🐸

2017-04-11 22:13 UTC, joaofnfernandes commented
@mstanleyjones I've added another caveat explaining that `docker run --env` allows you to define new environment variables, or overwrite the ones that are defined in the Dockerfile for the image you're using.

I think the Dockerfile reference is OK for now. Since the `ENV` keyword in the Dockerfile works at buildtime and `docker run --env` works at runtime, I think most people will intuitively expect the be current behavior of `docker build` and `docker run`, so I don't think we need to add more disclaimers.

I don't have a Windows machine to test with, but I think the behavior of the builder and runner should be exactly the same. You'll only have to update the samples to run the equivalent of `env` in windows, to print the environment variables that are set in the container.

Does this satisfy all your requirements to approve this PR?

2017-04-11 23:14 UTC, mdlinville approved these changes
LGTM. We should go back through these at some point and make it so that people don't have to already know what `cat` and `grep` do. It might be worthwhile to make the statement, then explain what the example is doing, then show the example.

2017-04-12 01:00 UTC, joaofnfernandes commented
Agree, and also add the equivalent snippets for windows.

2017-04-12 07:34 UTC, merged

2017-05-01 21:00 UTC, rneu31 commented
Is there an example of --env working on Windows at all? Seems Windows was brushed over here. If I run a `docker run -it some-image:1.0 -e somevar=hello cmd` and then an `echo %somevar%` the var doesn't seem to be set.