cli: add `--mount` to `docker run`
moby/moby pull request #32251
Opened 2017-03-31 06:58 UTC by AkihiroSuda

**- What I did**

Revert #28838
Update #28527

Plese refer to https://github.com/docker/docker/issues/28527#issuecomment-290502425 for the discussion so far.

This PR adds `--mount` to `docker run`.

The syntax of `docker run --mount` is identical to `docker service create --mount`.

Some notes:
* `--volume-driver` is ignored for `--mounts`. A warning will be printed on the client side when specified.
* `--mount` still only supports "CSV" form. i.e. `--mount type=volume,src=foo,dst=/bar` works but `--mount foo:/bar` does NOT work.
* user can mix up `--mount` and `-v` simultaneously.

**- How I did it**

Revert #28838 + warning about "--volume-driver is ignored for --mount volumes"

**- How to verify it**

```console
$ docker run --rm --mount type=bind,src=/host-foo,dst=/foo --mount type=bind,src=/host-bar,dst=/bar -v /host-baz:/baz  busybox ls /foo /bar /baz
/bar:
..
/baz:
..
/foo:
..
```

```console
$ docker run --volume-driver foo --mount type=volume,dst=/foo -it --rm busybox
WARN[0000] `--volume-driver` is ignored for volumes specified via `--mount`. Use `--mount type=volume,volume-driver
...
```
**- Description for the changelog**

cli: add `--mount` to `docker run`

**- A picture of a cute animal (not mandatory but encouraged)**
![penguins](https://camo.githubusercontent.com/41c4d406625a188d7070c012da18e4b3641dc4d3/687474703a2f2f6e61747572616c686973746f72792e73692e6564752f65786869626974732f6e6174757265732d626573742d323031322f696d616765732f3138546f6d564d796572735f50656e6775696e732e6a7067)

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

2017-03-31 18:53 UTC, dnephin approved these changes
LGTM

2017-03-31 19:55 UTC, stevvooe approved these changes

2017-03-31 19:55 UTC, stevvooe commented
LGTM

2017-03-31 20:19 UTC, cpuguy83 commented
Moving to code review.

2017-04-01 01:25 UTC, aaronlehmann commented on integration-cli/docker_cli_run_test.go
> +					"--volume", fmt.Sprintf("%s:/foo", mnt1),
`mnt1 + ":/foo"` instead of Sprintf?

2017-04-01 01:25 UTC, aaronlehmann commented on integration-cli/docker_cli_run_test.go
> +					"--volume", fmt.Sprintf("%s:/foo", mnt1),
`mnt1 + ":/foo"` instead of Sprintf?

2017-04-01 01:26 UTC, aaronlehmann commented
LGTM

2017-04-01 09:31 UTC, vdemeester approved these changes
LGTM 🐸

2017-04-04 07:27 UTC, AkihiroSuda commented on integration-cli/docker_cli_run_test.go
> +					"--volume", fmt.Sprintf("%s:/foo", mnt1),
done

2017-04-04 07:27 UTC, AkihiroSuda commented on integration-cli/docker_cli_run_test.go
> +					"--volume", fmt.Sprintf("%s:/foo", mnt1),
done

2017-04-04 08:32 UTC, thaJeztah requested changes
one nit, LGTM otherwise 😅 

(sorry, forgot to _submit_ my review)

2017-04-05 04:52 UTC, AkihiroSuda commented
@thaJeztah done
cc @icecrime @mstanleyjones

2017-04-05 07:57 UTC, thaJeztah approved these changes
LGTM, thanks!!!

2017-04-05 20:34 UTC, merged