Ensure health probe is stopped when a container is removed
moby/moby pull request #32274
Opened 2017-03-31 16:39 UTC by mlaventure

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

-- 

**- What I did**

Fixes #30107 by preventing an health check to keep on running after a container has been removed

**- How I did it**

Added a call to `updateHealtMonitor` in the rm code path to ensure that the health check probe gets stopped in the case where the exit events was received beforehand and the container hadn't been restarted yet.

**- How to verify it**

Given it's a race, it has to be manually testing unfortunately. Instructions provided by @esbite were used (https://gist.github.com/esbite/d0c639e72435b4721d44445b0972dff8)

**- Description for the changelog**

Ensure health probe is stopped when a container is removed

**- A picture of a cute animal (not mandatory but encouraged)**

Not Today :scream_cat:

2017-04-01 18:44 UTC, vdemeester approved these changes
LGTM 🦁

2017-04-03 13:33 UTC, cpuguy83 requested changes

2017-04-03 13:33 UTC, cpuguy83 commented on daemon/delete.go
> +	daemon.updateHealthMonitor(container)
This needs to be called with a lock.

2017-04-03 13:33 UTC, cpuguy83 commented on daemon/delete.go
> +	daemon.updateHealthMonitor(container)
Also should be called after `containerStop()`?

2017-04-03 15:21 UTC, mlaventure commented on daemon/delete.go
> +	daemon.updateHealthMonitor(container)
Just realized that `containerStop()` already stop the health check.

Going to go through the flow again, there's definitely a race there, but I'm thinking it's more in the `StateChanged()` daemon callback now.

2017-04-03 17:03 UTC, mlaventure commented
@vdemeester @cpuguy83 changed the fixed (and updated the PR description) PTAL

2017-04-03 17:07 UTC, tonistiigi approved these changes
LGTM

2017-04-03 17:22 UTC, cpuguy83 approved these changes
LGTM

2017-04-04 14:14 UTC, vdemeester commented
powerpc failure known flaky, let's merge this 👼

2017-04-04 14:14 UTC, merged