Add docs for multi-stage builds
moby/moby pull request #32362
Opened 2017-04-04 20:58 UTC by tonistiigi

cc @thaJeztah 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

2017-04-04 21:31 UTC, AkihiroSuda commented on docs/reference/builder.md
>  - `FROM` must be the first non-comment instruction in the `Dockerfile`.
This line seems outdated. Now we can have ARG.

2017-04-04 21:32 UTC, tonistiigi commented on docs/reference/builder.md
>  - `FROM` must be the first non-comment instruction in the `Dockerfile`.
not yet: https://github.com/docker/docker/pull/31352

2017-04-06 02:03 UTC, vieux commented
SGTM ping @mstanleyjones

2017-04-08 00:08 UTC, vieux commented
ping @thaJeztah

2017-04-08 17:08 UTC, thaJeztah requested changes
some minor nits, but LGTM otherwise

2017-04-08 17:08 UTC, thaJeztah commented on docs/reference/builder.md
> +builder assumes a `latest` by default. The builder returns an error if it
nit: perhaps be explicit;

`latest` _tag_ 

(as it's not latest "digest")

2017-04-08 17:08 UTC, thaJeztah commented on docs/reference/builder.md
> +    FROM <image>:<tag> [AS <name>]
this was already like this, but given that tag is optional, should this be?;

   FROM <image>[:<tag>] [AS <name>]

2017-04-08 17:08 UTC, thaJeztah commented on docs/reference/builder.md
> +    FROM <image>@<digest> [AS <name>]
same here for digest

2017-04-08 17:08 UTC, thaJeztah commented on docs/reference/builder.md
> +Optionally `COPY` accepts a flag `--from=[name|index]` that can be used to set
`--from=<name|index>` (name or index is required when using `--from`)

2017-04-08 17:08 UTC, thaJeztah commented on docs/reference/builder.md
> +the source location to a previous build stage(created with `FROM .. AS <name>`
- add a space before `(`
- "created with _the_ ..." (or remove "command" on the next line)

2017-04-10 03:41 UTC, tonistiigi commented
@thaJeztah Updated. PTAL

2017-04-10 12:24 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-04-10 12:26 UTC, vdemeester approved these changes
LGTM 🐸

2017-04-10 12:26 UTC, merged