docker/registry: Make CertsDir configurable.
moby/moby pull request #32376
Opened 2017-04-05 10:27 UTC by vosst

On linux hosts, it would be helpful if certificates for
accessing a remote registry could be configured at runtime
for specific setups. One example are snaps and third-parties
who want to work with their own registries.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-04-05 10:27 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "make-certs-dir-configurable" git@github.com:vosst/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-05 20:21 UTC, vosst commented
I tried to track down the test failure on Windows, but failed to reproduce the Jenkins setup. Do you have instructions available for debugging test failures?

2017-04-06 03:32 UTC, cpuguy83 requested changes

2017-04-06 03:32 UTC, cpuguy83 commented on registry/config_unix.go
> +	dir := os.Getenv("DOCKER_REGISTRY_CERTS_DIR")
Definitely no.
Daemon flag would be much better.

2017-04-07 09:05 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "make-certs-dir-configurable" git@github.com:vosst/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354043568
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-07 09:15 UTC, vosst commented on registry/config_unix.go
> +	dir := os.Getenv("DOCKER_REGISTRY_CERTS_DIR")
Thanks, applied your review. Let me know if the name of the flag works, or if you would prefer something less clunky.

2017-05-16 23:00 UTC, thaJeztah commented
ping @cyli @diogomonica PTAL as well

2017-06-20 17:29 UTC, cpuguy83 commented
@vosst Thanks for the update. It looks like you have the flag but it's not wired up to anything currently.

2017-06-27 04:20 UTC, thaJeztah commented
ping @vosst are you still working on this?

2017-07-17 18:17 UTC, ehazlett commented
ping @vosst

2017-09-22 23:00 UTC, thaJeztah commented
closing because there was no activity for a long time

2017-09-22 23:00 UTC, closed without merging