Update README.md
moby/moby pull request #32451
Opened 2017-04-08 05:41 UTC by saharjs

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-04-08 05:41 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-1" git@github.com:saharjs/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-08 05:41 UTC, saharjs commented
Hi
Required by the one of the assignments of my technical writing course I am supposed to edit other people's writing. I think the minor changes that I have proposed would increase the readability of your README file.
Thank you

2017-04-09 04:52 UTC, AkihiroSuda requested changes
Unfortunately, this PR seems rather decreasing readability (e.g. what is "due to blow"?)

2017-04-09 13:40 UTC, vdemeester commented
I do agree with @AkihiroSuda, it doesn't make it more readable and need to be signed-off.
Thanks for the contribution, but I'll close 👼

2017-04-09 13:40 UTC, closed without merging