service privileges: API docs & completion
moby/moby pull request #32483
Opened 2017-04-10 18:57 UTC by aluzzardi

Follow up for #32339

Added Swagger Docs, updated the API changelog and shell completion.

/cc @thaJeztah

2017-04-10 20:54 UTC, mstanleyjones commented
I think you also need to update the command-line reference files, right?

2017-04-10 21:08 UTC, thaJeztah commented
Yes, this needs an update to the CLI docs as well; although plans are to remove the `USAGE` output there, we probably could use a simple example of it's usage

2017-04-11 13:33 UTC, thaJeztah commented
Added a commit for the CLI reference

/cc @friism @johnstep if the description is correct

2017-04-11 16:17 UTC, mdlinville reviewed
Just one question...

2017-04-11 16:17 UTC, mstanleyjones commented on docs/reference/commandline/service_create.md
> +This option is only supported on a daemon running on Windows. The `--credential-spec` must be in the format
Does this mean running Windows containers, or running Linux containers on a Windows host machine?

2017-04-11 16:19 UTC, thaJeztah commented on docs/reference/commandline/service_create.md
> +This option is only supported on a daemon running on Windows. The `--credential-spec` must be in the format
Hm, yes, it's Windows containers; should I change to "only supported for Native Windows containers"?

2017-04-11 16:49 UTC, friism commented on docs/reference/commandline/service_create.md
> +This option is only supported on a daemon running on Windows. The `--credential-spec` must be in the format
Yeah that, or `supported on a daemon running natively on Windows`

2017-04-13 21:48 UTC, aaronlehmann commented
@aluzzardi: Need a rebase

2017-04-13 21:51 UTC, aluzzardi commented
Rebased

2017-04-13 21:55 UTC, aaronlehmann commented on docs/reference/commandline/service_create.md
> +This option is only supported on a daemon running on Windows. The `--credential-spec` must be in the format
Let's remove the reference to the daemon. As I understand it, this applies to the containers being run, not the daemon that the client is communicating with to set up the service.

2017-04-15 05:34 UTC, thaJeztah commented on docs/reference/commandline/service_create.md
> +This option is only used for services using Windows containers. The
@aaronlehmann @mstanleyjones does this work?

2017-04-16 18:57 UTC, aaronlehmann commented on docs/reference/commandline/service_create.md
> +This option is only used for services using Windows containers. The
SGTM

2017-04-16 18:59 UTC, aaronlehmann commented on docs/reference/commandline/service_create.md
> +daemon host in the `C:\programfiles\docker\credentialspecs\` directory. When
Let's make clear whether the path after `file://` should be a full path or a relative path within `C:\programfiles\docker\credentialspecs\`.

As a side note, it's potentially confusing if `file://` is meant to be used with a relative path here.

2017-04-17 01:29 UTC, thaJeztah commented on docs/reference/commandline/service_create.md
> +daemon host in the `C:\programfiles\docker\credentialspecs\` directory. When
Yes, I was a bit confused by this as well https://github.com/docker/docker/pull/32339#discussion_r110453491

@friism could you help a bit here?

2017-04-17 01:30 UTC, thaJeztah commented on docs/reference/commandline/service_create.md
> +daemon host in the `C:\programfiles\docker\credentialspecs\` directory. When
also; does it accept a filename only or also a sub directory?

2017-04-17 15:56 UTC, friism commented on docs/reference/commandline/service_create.md
> +daemon host in the `C:\programfiles\docker\credentialspecs\` directory. When
It's a relative path from the `C:\programfiles\docker\credentialspecs` folder. Using an absolute path errors correctly:

    time="2017-04-17T08:48:45.126507000-07:00" level=error msg="fatal task error" error="starting container failed: invalid credential spec - file:// path cannot be absolute" module="node/agent/taskmanager" node.id=y6t3hh97zaqh3wkxnrnkg6plw service.id=l5bz9jvh9qxccxdladbg7uec2 task.id=0s3vbr0luxotquovs2ul3fosr

Subdirs can be used, eg. I just tested `C:\ProgramData\docker\credentialspecs\subdir` and it works great.

@aluzzardi let me know if you want to work on the wording or whether you want to do it.

2017-05-12 09:37 UTC, thaJeztah commented
ping @aluzzardi can you address the review comments?

2017-06-08 21:09 UTC, LK4D4 commented
@thaJeztah maybe you could carry it?

2017-07-06 16:33 UTC, LK4D4 commented
ping @thaJeztah

2017-07-11 14:33 UTC, thaJeztah commented
Carrying API side in https://github.com/moby/moby/issues/34002 - will close this one when I opened a PR for the CLI docs

2017-07-11 18:53 UTC, LK4D4 commented
@thaJeztah assigned to you

2017-07-14 00:40 UTC, johnstep requested changes

2017-07-14 00:40 UTC, johnstep commented on docs/reference/commandline/service_create.md
> +daemon host in the `C:\programfiles\docker\credentialspecs\` directory. When
Actually it is `$env:ProgramData`, not `$env:ProgramFiles` (PowerShell environment variable syntax), so the default is `$env:ProgramData\Docker\CredentialSpecs` which is usually `C:\ProgramData\Docker\CredentialSpecs`.

Is there a better way to phrase this to say it's `CredentialSpecs` under the Docker data root directory, which defaults to `$env:ProgramData\Docker` where `$env:ProgramData` is usually `C:\ProgramData`?

2017-07-14 00:40 UTC, johnstep commented on api/swagger.yaml
> +                    description: "Load credential spec from this registry key"
Technically it is a registry _value_ within the CredentialSpecs registry key, so I would change this to 'registry value'. Comparing to a file system, a key is roughly equivalent to a directory, and a value, a file.

2017-07-14 00:40 UTC, johnstep commented on docs/reference/commandline/service_create.md
> +`--credential-spec` must be in the format `file://spec.txt` or
To be clear on the expected file format, maybe change this to `file://spec.json`.

2017-07-14 00:40 UTC, johnstep commented on docs/reference/commandline/service_create.md
> +using the `registry://keyname` format, the credential spec is read from
`registry://valuename`

2017-07-14 00:40 UTC, johnstep commented on docs/reference/commandline/service_create.md
> +`registry://keyname`.
`registry://valuename`

2017-07-15 00:04 UTC, thaJeztah commented on docs/reference/commandline/service_create.md
> +`--credential-spec` must be in the format `file://spec.txt` or
@johnstep I was already working on the API changes in https://github.com/moby/moby/pull/34002; PTAL there

2017-07-18 11:10 UTC, thaJeztah commented
https://github.com/docker/cli/pull/338 and https://github.com/moby/moby/pull/34002 were merged, so closing this one

2017-07-18 11:10 UTC, closed without merging