Update docs of `label` filter for `docker system prune`
moby/moby pull request #32481
Opened 2017-04-10 18:43 UTC by yongtang

This fix updates docs of `label` filter for `docker system prune`.

This fix is related to #30740 and #29999, and specifically to
comment https://github.com/docker/docker/pull/30740#issuecomment-293012957.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-04-10 18:44 UTC, yongtang commented
/cc @mlaventure @thaJeztah @vdemeester

2017-04-11 09:10 UTC, vdemeester requested changes

2017-04-11 09:10 UTC, vdemeester commented on docs/reference/commandline/container_prune.md
> +The `label` filter accpets two formats. One is the `label=...` (`label=<key>` or `label=<key>=<value>`),
s/accpets/accepts/ :angel:

2017-04-11 09:10 UTC, vdemeester commented on docs/reference/commandline/image_prune.md
> +The `label` filter accpets two formats. One is the `label=...` (`label=<key>` or `label=<key>=<value>`),
s/accpets/accepts/ :angel:

2017-04-11 09:10 UTC, vdemeester commented on docs/reference/commandline/network_prune.md
> +The `label` filter accpets two formats. One is the `label=...` (`label=<key>` or `label=<key>=<value>`),
s/accpets/accepts/ :angel:

2017-04-11 09:10 UTC, vdemeester commented on docs/reference/commandline/system_prune.md
> +The `label` filter accpets two formats. One is the `label=...` (`label=<key>` or `label=<key>=<value>`),
s/accpets/accepts/ :angel:

2017-04-11 09:10 UTC, vdemeester commented on docs/reference/commandline/volume_prune.md
> +The `label` filter accpets two formats. One is the `label=...` (`label=<key>` or `label=<key>=<value>`),
s/accpets/accepts/ :angel:

2017-04-11 15:33 UTC, yongtang commented on docs/reference/commandline/container_prune.md
> +The `label` filter accpets two formats. One is the `label=...` (`label=<key>` or `label=<key>=<value>`),
Thanks @vdemeester. Was in a rush and didn't check carefully.

2017-04-11 15:33 UTC, yongtang commented
Thanks @vdemeester. The PR has been updated.

2017-04-11 16:11 UTC, thaJeztah approved these changes
LGTM

2017-04-11 16:11 UTC, thaJeztah commented on docs/reference/commandline/container_prune.md
> +containers without the specified labels.
This may need a bit of rewrite, but let's get this merged, we can make it "nicer" afterwards

2017-04-11 16:12 UTC, vdemeester approved these changes
LGTM 🦁

2017-04-11 18:46 UTC, vdemeester commented
@yongtang arf already need a rebase 😱

2017-04-11 19:10 UTC, yongtang commented
@vdemeester @thaJeztah Rebased and updated the PR. Thanks.

2017-04-12 13:37 UTC, merged