17.05.0 rc1 changelog, bump version to 17.06-dev, API to 1.30
moby/moby pull request #32498
Opened 2017-04-10 23:21 UTC by thaJeztah

ping @vieux @tiborvass

2017-04-11 01:35 UTC, cpuguy83 commented on CHANGELOG.md
> +### Swarm Mode
https://github.com/docker/docker/pull/31144 ?

2017-04-11 01:46 UTC, tonistiigi commented on CHANGELOG.md
> ++ Add multi-stage build support [#31257](https://github.com/docker/docker/pull/31257)
Link to #32063 (or both)

2017-04-11 01:49 UTC, vieux commented on CHANGELOG.md
> +### Swarm Mode
added

2017-04-11 01:50 UTC, vieux commented on CHANGELOG.md
> ++ Add multi-stage build support [#31257](https://github.com/docker/docker/pull/31257)
added

2017-04-11 03:30 UTC, tiborvass requested changes

2017-04-11 03:30 UTC, tiborvass commented on CHANGELOG.md
> +- Add `--api-enable-cors` to deprecated features. This flag was marked deprecated in Docker 1.6 but not listed in deprecated features [#32352](https://github.com/docker/docker/pull/32352)
@vieux would prefer saying `Deprecate X` instead of `Add X to deprecated features.`

2017-04-11 04:05 UTC, vieux commented on CHANGELOG.md
> +- Add `--api-enable-cors` to deprecated features. This flag was marked deprecated in Docker 1.6 but not listed in deprecated features [#32352](https://github.com/docker/docker/pull/32352)
ok

2017-04-11 06:18 UTC, thaJeztah commented on CHANGELOG.md
> +### Swarm Mode
ah, we forgot to add impact kageks in that one

2017-04-11 09:16 UTC, albers commented on CHANGELOG.md
> +### Swarm Mode
kageks :grin:

2017-04-11 09:30 UTC, thaJeztah commented on CHANGELOG.md
> +### Swarm Mode
LOL, typing on a phone isn't my strong point

2017-04-11 10:33 UTC, thaJeztah commented
We need to add https://github.com/docker/docker/pull/32516 as well, if merged

2017-04-11 11:37 UTC, thaJeztah commented on CHANGELOG.md
> +- Add `--api-enable-cors` to deprecated features. This flag was marked deprecated in Docker 1.6 but not listed in deprecated features [#32352](https://github.com/docker/docker/pull/32352)
@tiborvass updated

2017-04-11 11:37 UTC, thaJeztah commented on CHANGELOG.md
> +* `docker service inspect` now shows default values for fields that are not specified by the user [#32284](https://github.com/docker/docker/pull/32284)
Added these two (https://github.com/docker/docker/pull/32284)

2017-04-11 11:38 UTC, thaJeztah commented on docs/api/version-history.md
> +* `GET /services/(id)` now accepts an `insertDefaults` query-parameter to merge default values into the service inspect output.
Relates to https://github.com/docker/docker/pull/32284

2017-04-11 13:02 UTC, thaJeztah commented
Also need to add https://github.com/docker/docker/pull/32505 (if merged)

2017-04-11 14:49 UTC, thaJeztah commented on CHANGELOG.md
> +- Fix files being written to `/var/lib/docker` if a different data-root is set [#32505](https://github.com/docker/docker/pull/32505)
Added these two for https://github.com/docker/docker/pull/32505 ptal @mavenugo

2017-04-11 16:17 UTC, thaJeztah commented on CHANGELOG.md
> +- Remove Ubuntu 12.04 (Precise Pangolin) as supported platform. Ubuntu 12.04 is EOL, and no longer receives updates [#32520](https://github.com/docker/docker/pull/32520)
Added https://github.com/docker/docker/pull/32520

2017-04-11 18:16 UTC, merged

2017-06-09 12:00 UTC, thaJeztah commented
Cherry-picked through https://github.com/moby/moby/pull/33606