Fine control of libdevmapper logging
moby/moby pull request #32541
Opened 2017-04-11 22:03 UTC by jwhonce

I added a storage-opt command line option to allow libdevmapper logging to be configured when starting the daemon rather than at compile time to better facilitate debugging.  The default level is still Fatal.

Note: dm.log_level must be greater than or equal to Docker's log-level

Chang log:
  Added dm.log_level to allow runtime configuration of libdevmapper logging.

Signed-off-by: Jhon Honce <jhonce@redhat.com>

2017-04-11 22:06 UTC, jwhonce commented
@cpuguy83 When debugging devicemapper issues from customers I found I wanted to see more detail from libdevmapper.  This PR allows me to do so without rebuilding docker.

2017-04-11 22:18 UTC, thaJeztah commented
Would it make sense to do this automatically if the daemon is put in debug mode?

2017-04-12 17:06 UTC, jwhonce commented
@thaJeztah I thought about doing just that, but the amount of output could have an effect on  debugging other areas of the daemon. So I limited the scope.

2017-04-12 20:54 UTC, cpuguy83 commented on daemon/graphdriver/devmapper/deviceset.go
> +		case "dm.log_level":
I'd prefer to not expose this to users. Passing through the logrus logging level seems the easiest way to set this.

2017-04-13 17:59 UTC, jwhonce commented
@cpuguy83 @thaJeztah Patch updated to be driven by logrus's log level

2017-06-09 01:34 UTC, cpuguy83 requested changes
Sorry about the long wait time for a review here, just a minor change and I think we'll be good to move forward.

2017-06-09 01:34 UTC, cpuguy83 commented on pkg/devicemapper/log.go
> +	logrus.Infof,
There shouldn't be a need to pull in logrus into this package.
Instead we can do the conversion in the devicmapper graphdriver package to devmapper levels defined in this package.

2017-06-27 16:00 UTC, cyphar commented
I'm going to cherry-pick and modify-as-necessary this into #33845. @jwhonce if you're still looking at this patch please feel free to review it as well.

2017-07-04 12:19 UTC, cpuguy83 commented
Thanks @cyphar

2017-07-04 12:19 UTC, closed without merging