Switch to using opencontainers/selinux for selinux bindings
moby/moby pull request #32687
Opened 2017-04-18 13:27 UTC by runcom

Carry of https://github.com/docker/docker/pull/32011, hopefully tests are green here.

@cpuguy83 @thaJeztah @vdemeester @rhatdan PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

2017-04-24 09:43 UTC, runcom commented
Ping anyone, why aren't tests running for this PR?

2017-04-24 11:16 UTC, TomSweeneyRedHat commented on vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
> +// Filecon returns the SELinux label for this path or returns an error.
Filecon to FileLabel in this comment.

2017-04-24 12:18 UTC, runcom commented on vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
> +// Filecon returns the SELinux label for this path or returns an error.
Nice catch, could you open a PR to fix this in opencontainers/selinux?

2017-04-24 12:50 UTC, cpuguy83 requested changes
I don't think we should make any changes until we have a strongly-typed object for handing off selinux context from the daemon.

For instance in swarm we use this: https://github.com/moby/moby/blob/091b5e68ea735bf4e8ece708bbc8c413a32eab73/api/types/swarm/container.go#L25

2017-04-24 12:50 UTC, cpuguy83 commented on vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
> -		"label=role:" + con["role"],
This change seems like it's going to break stuff.
Why the change?

Definitely breaking https://github.com/moby/moby/blob/master/daemon/cluster/executor/container/container.go#L624

2017-04-24 12:52 UTC, runcom commented on vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
> -		"label=role:" + con["role"],
@cpuguy83 selinux hasn't any notion of `label=` prefixed labels. The label is just the label, not `label=label` <- this is something docker did afacit, nothing related to selinux /cc @rhatdan

2017-04-24 12:54 UTC, runcom commented
> I don't think we should make any changes until we have a strongly-typed object for handing off selinux context from the daemon.

I don't understand....this change is super-transparent and what you're saying can be postponed for sure, in the mean time we'll switch to OCI/selinux since there's no libcontainer/selinux anymore. If something happen to be incorrect we'll fix OCI/selinux directly that way...

2017-04-24 13:07 UTC, rhatdan commented on vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
> -		"label=role:" + con["role"],
label should not be in any SELinux specific section. this should be in the label section but not in the selinux specific section.

2017-04-24 13:13 UTC, cpuguy83 commented
Ok I see you've got this label conversion happening in Docker now. That's fine.
I'll open an issue to discuss a strong type that we can convert to to make sure this kind of stuff is checked at compile time.

Will need to do some manual testing on this just to make sure we're not breaking anything (seems ok, but just want to be sure).

2017-04-26 20:13 UTC, cpuguy83 approved these changes
LGTM

2017-04-26 22:19 UTC, runcom commented
everything green :green_heart:

2017-04-29 17:05 UTC, vdemeester approved these changes
LGTM 👍

2017-04-29 17:05 UTC, merged