Update attach.md
moby/moby pull request #32701
Opened 2017-04-18 23:02 UTC by gschaetz

issue #1456 https://github.com/docker/docker.github.io/issues/1456

2017-04-18 23:02 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:gschaetz/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-19 16:07 UTC, gschaetz commented
This fixes a doc issue at https://github.com/docker/docker.github.io/issues/2005

2017-04-20 17:17 UTC, mdlinville requested changes

2017-04-20 17:17 UTC, mstanleyjones commented on docs/reference/commandline/attach.md
> +> The attach command will display the output of the ENTRYPOINT/CMD process.  This
Please mark this up a bit by putting technical words like "attach" and "ENTRYPOINT/CMD" in back-ticks.

Only a single space between sentences.

Other than that, this is great!

2017-04-24 02:39 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:gschaetz/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354432024
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-24 02:41 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:gschaetz/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353888072
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-24 02:53 UTC, gschaetz commented
@mstanleyjones can you see If I got this right now.

2017-04-24 15:30 UTC, mstanleyjones commented on docs/reference/commandline/build.md
> +> **Note:**
This change is unrelated to `docker attach` and should probably be submitted in a separate PR. I think this time we can let it go, but in future, please try to keep your PRs to one issue at a time, for ease of review and for if the change ever needs to be reverted.

2017-04-24 15:30 UTC, mstanleyjones commented
@vdemeester PTAL

2017-04-26 16:47 UTC, mdlinville approved these changes

2017-04-26 17:19 UTC, thaJeztah requested changes
changes look good to me, but can you squash your commits, so that there's a single commit in this PR? You can find some instructions in our contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently

2017-04-26 18:14 UTC, mstanleyjones commented
@gschaetz we would like to close this one out, can you please address the feedback? :)

2017-04-27 21:38 UTC, gschaetz commented
@mstanleyjones I will get it done tonight 
Sent from my iPhone.

> On Apr 26, 2017, at 11:48 AM, Misty Stanley-Jones <notifications@github.com> wrote:
> 
> @mstanleyjones

2017-04-30 16:52 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:gschaetz/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842361080304
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-05-02 09:31 UTC, vdemeester requested changes
LGTM 👼 but @gschaetz you need to squash the 5 commits into one 🙏

2017-05-02 10:43 UTC, gschaetz commented
> @vdemeester I'll try to squash them again. 
> 

Sent from my iPhone.

> On May 2, 2017, at 4:31 AM, Vincent Demeester <notifications@github.com> wrote:
> 
> @vdemeester requested changes on this pull request.
> 
> LGTM 👼 but @gschaetz you need to squash the 5 commits into one 🙏
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-05-02 14:30 UTC, gschaetz commented
@vdemeester  I tried to rebase and squash but the old ones still show up.  Any tips you can give me or instructions?

2017-05-02 14:41 UTC, vdemeester commented
@gschaetz sure 😉 

```
$ git rebase --interactive HEAD~5
# keep one and mark the other as squash in the editor that popped up
# update commit message if it's messed up and save it
$ git status 
# to make sure you have one commit and the remote has 5
$ git push --force-with-lease origin master
```

*Note for later: it's safer to open a PR from a separate branch as master (allows you to keep updating master without messing current PR 👼 )*

2017-05-02 23:16 UTC, gschaetz commented
Ugh @vdemeester that is pulling in other commits.  Not just mine.

> On May 2, 2017, at 5:43 AM, Gary Schaetz <gschaetz@gmail.com> wrote:
> 
>> vdemeester
>>

2017-05-03 01:12 UTC, thaJeztah approved these changes
@gschaetz I rebased/squashed and pushed to your branch to update the PR

LGTM

2017-05-03 01:12 UTC, merged