Adding more on -m and --memory
moby/moby pull request #32724
Opened 2017-04-19 22:09 UTC by PatrickLang

**- Description for the changelog**
Doc change only

Resolves https://github.com/docker/docker.github.io/issues/2936 clarifying what `-m` and `--memory` do on Windows as well as a Linux sample.

**- A picture of a cute animal (not mandatory but encouraged)**
![Susie-b](http://i.imgur.com/6sI1LSi.jpg)

2017-04-19 22:09 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patricklang-win-memory" git@github.com:PatrickLang/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353741296
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-24 18:00 UTC, PatrickLang commented
@jhowardmsft @mstanleyjones any feedback?

2017-04-24 18:46 UTC, lowenna requested changes
Could you also squash your commits?

2017-04-24 18:46 UTC, jhowardmsft commented on docs/reference/commandline/run.md
> +- with `hyperv` isolation, Windows will report the limit as the total system memory
Do you mean the utility VM? `total system memory` implies of the host system to me

2017-04-24 18:46 UTC, jhowardmsft commented on docs/reference/commandline/run.md
> +- With `process` isolation, Windows will report the full memory of the system, not the limit to applications running inside the container
of the `host` system?

2017-04-25 17:12 UTC, mstanleyjones commented
@PatrickLang please come back and address the feedback. :)

2017-04-25 21:17 UTC, PatrickLang commented on docs/reference/commandline/run.md
> +- With `process` isolation, Windows will report the full memory of the system, not the limit to applications running inside the container
Fixed

2017-04-25 21:17 UTC, PatrickLang commented on docs/reference/commandline/run.md
> +- with `hyperv` isolation, Windows will report the limit as the total system memory
Fixed

2017-04-25 21:46 UTC, PatrickLang commented
Squash done too

2017-04-25 21:57 UTC, lowenna approved these changes

2017-04-25 21:57 UTC, jhowardmsft commented
LGTM (not a docs maintainer)

Ping @thaJeztah

2017-04-25 22:47 UTC, mdlinville approved these changes

2017-04-25 22:48 UTC, mstanleyjones commented
@thaJeztah needs to be cherry-picked to master and 17.05.x, I added the label.

2017-04-26 13:30 UTC, vdemeester approved these changes
LGTM 🐮

2017-04-26 13:30 UTC, merged