Proposal: Add --until flag for docker logs
moby/moby pull request #32767
Opened 2017-04-21 15:12 UTC by jamiehannaford

**- What I did**

This PR contains a design proposal for introducing an `--until` flag for the `docker logs` command. All info (use cases and potential implementations) are listed in the MD file.

**- How I did it**

N/A

**- How to verify it**

N/A

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

![](http://i.imgur.com/e6hTzsm.gif)

2017-04-21 15:12 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "until_logging_prop" git@github.com:jamiehannaford/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-25 01:43 UTC, AkihiroSuda requested changes
Please use github issue for proposals

2017-04-25 09:09 UTC, jamiehannaford commented
@AkihiroSuda I followed [the advanced contribution docs](https://docs.docker.com/opensource/workflow/advanced-contributing/#design-proposal) for new features which states:

> - Create a new Markdown file in the area you wish to change.
> - Name the file descriptively, for example redesign-daemon-proposal.md.
> - Write a proposal for your change into the file.
> - Submit your proposal in a pull request to docker/docker.

If I really need to do this through an issue, these docs need to be changed.

2017-04-25 09:12 UTC, closed without merging

2017-04-25 09:28 UTC, AkihiroSuda commented
cc @thaJeztah @stevvooe for contribution docs (seems added in 2015 via https://github.com/moby/moby/pull/11209, but IIUC we are not using PR for design proposals recently)