Fixes #10824. Adjusted docker stats memory output
moby/moby pull request #32777
Opened 2017-04-22 11:29 UTC by Sergeant007

Signed-off-by: Sergey Tryuber <Sergeant007@users.noreply.github.com>

### **- What I did**
"docker stats" CLI command now outputs memory usage without page cache. Fixes #10824.

### **- How I did it**
Followed to the solution suggested by @crosbymichael in #10824 - "just subtract the cache from the usage value before displaying it to the user". 

### **- How to verify it**
#10824 contains the debug steps to prove that "docker stats" used to include page cache in its output. This PR corrects the behavior. 

Experiment (Docker version 17.06.0-dev, build 1eec7b5). The steps are done inside [development container](https://docs.docker.com/opensource/project/set-up-dev-env/#task-2-start-a-development-container), you would need to open several terminals to the development container.

_Step 0. [build the binaries](https://docs.docker.com/opensource/project/set-up-dev-env/#task-2-start-a-development-container) and then start docker daemon listening on tcp_
```bash
// start with tcp since curl in development container cannot work with file sockets
$dockerd -D -H tcp://0.0.0.0:2375
```

_Step 1. start a container with bash_
```bash
docker -H localhost:2375 run --name mem_stats_test --interactive --tty ubuntu:14.04 /bin/bash
```

_Step 2. open a new terminal window and ensure that memory consumption in stats is low_
```bash
$ docker -H localhost:2375 stats mem_stats_test --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
mem_stats_test      0.00%               1.699MiB / 15.58GiB   0.01%               648B / 0B           0B / 0B             1
$
$curl http://localhost:2375/containers/mem_stats_test/stats?stream=false | python -m json.tool
...
    "memory_stats": {
        "limit": 16724922368,
        "max_usage": 2629632,
        "stats": {
            "active_anon": 507904,
            "active_file": 0,
            "cache": 20480,                  <-- CACHE
            "dirty": 0,
            "hierarchical_memory_limit": 9223372036854771712,
            "inactive_anon": 4096,
            "inactive_file": 0,
            "mapped_file": 0,
            "pgfault": 1377,
            "pgmajfault": 0,
            "pgpgin": 754,
            "pgpgout": 629,
            "rss": 491520,
            "rss_huge": 0,
            "total_active_anon": 507904,
            "total_active_file": 0,
            "total_cache": 20480,
            "total_dirty": 0,
            "total_inactive_anon": 4096,
            "total_inactive_file": 0,
            "total_mapped_file": 0,
            "total_pgfault": 1377,
            "total_pgmajfault": 0,
            "total_pgpgin": 754,
            "total_pgpgout": 629,
            "total_rss": 491520,
            "total_rss_huge": 0,
            "total_unevictable": 0,
            "total_writeback": 0,
            "unevictable": 0,
            "writeback": 0
        },
        "usage": 1802240                     <-- OVERALL USAGE
    },
...
```

_Step 3. Let is work for several hours to ensure that memory doesn't grow significanly (or believe me ans skip this step)_

_Step 4. Do some heavy file operations that grow page cache (in docker container console from Step 1)_
```bash
# # Once following operation is finished, page cache will grow, but no additional "real" memory consumption is added
# dd if=/dev/urandom of=/tmp/1GB.bin bs=64M count=16 iflag=fullblock
16+0 records in
16+0 records out
1073741824 bytes (1.1 GB) copied, 10.9137 s, 98.4 MB/s
```

_Step 5. Check docker stats again to see that **there is no page cache included in the output**_
```bash
$ # reported memoty DID NOT grew up (significantly)!!!
$ docker -H localhost:2375 stats mem_stats_test --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
mem_stats_test      0.00%               4.039MiB / 15.58GiB   0.03%               648B / 0B           0B / 0B             1
$curl http://localhost:2375/containers/mem_stats_test/stats?stream=false | python -m json.tool
...
"memory_stats": {
        "limit": 16724922368,
        "max_usage": 1145520128,
        "stats": {
            "active_anon": 520192,
            "active_file": 0,
            "cache": 1073766400,                          <-- OUR PAGE CACHE
            "dirty": 0,
            "hierarchical_memory_limit": 9223372036854771712,
            "inactive_anon": 0,
            "inactive_file": 1073741824,
            "mapped_file": 0,
            "pgfault": 2050,
            "pgmajfault": 0,
            "pgpgin": 263492,
            "pgpgout": 1221,
            "rss": 495616,
            "rss_huge": 0,
            "total_active_anon": 520192,
            "total_active_file": 0,
            "total_cache": 1073766400,
            "total_dirty": 0,
            "total_inactive_anon": 0,
            "total_inactive_file": 1073741824,
            "total_mapped_file": 0,
            "total_pgfault": 2050,
            "total_pgmajfault": 0,
            "total_pgpgin": 263492,
            "total_pgpgout": 1221,
            "total_rss": 495616,
            "total_rss_huge": 0,
            "total_unevictable": 0,
            "total_writeback": 0,
            "unevictable": 0,
            "writeback": 0
        },
        "usage": 1078001664                                  <-- THIS INCLUDES PAGE CACHE !!!!
...
```
_Step 6. Conclusion_
**With this PR docker stats outputs reasonable amount of used memory (no page cache included)**

### **- Description for the changelog**
"docker stats" command outputs memory usage with no page cache memory included.

### **- A picture of a cute animal (not mandatory but encouraged)**
My cat Tom.
![tom](https://cloud.githubusercontent.com/assets/6276040/25304000/3de373e6-276f-11e7-886f-a5e5240b5f64.jpg)

2017-04-26 05:25 UTC, boaz0 requested changes
unit-tests are missing.

2017-04-27 17:47 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "10824-dockerstats-misleading-mem" git@github.com:Sergeant007/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354520728
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-27 18:29 UTC, Sergeant007 commented
@ripcurld0, @vdemeester 
Added unit tests. Please, review.

2017-04-27 23:34 UTC, thaJeztah requested changes
left some suggestions :)

2017-04-27 23:34 UTC, thaJeztah commented on cli/command/container/stats_helpers.go
> +//there is no reason do display memory that includes page cache
Perhaps use GoDoc convention here;

```
// calculateMemUsageUnixNoCache calculates the amount of memory excluding page cache
```

or something like that :smile:

2017-04-28 04:48 UTC, Sergeant007 commented
Hi @thaJeztah 
Thanks for good suggestions, I've corrected all of them. Please review.  
I wasn't able to find any "godoc documentation convention" - only blog posts. So I did my best there. Please, advise if necessary.

2017-04-28 05:11 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-04-30 03:23 UTC, boaz0 approved these changes
👍

2017-05-10 15:53 UTC, Sergeant007 commented
Hi @stevvooe,
I see that you was assigned to merge the pull request, but now there are merge conflict. Will you be able to resolve them by yourself?

2017-05-11 01:27 UTC, AkihiroSuda commented
Please resolve by yourself

2017-05-11 01:28 UTC, AkihiroSuda commented
Also, now this needs to be moved to https://github.com/docker/cli

2017-05-13 03:03 UTC, Sergeant007 commented
Hi @AkihiroSuda 

> Please resolve by yourself
> Also, now this needs to be moved to https://github.com/docker/cli

This does not "needs to be moved", this is throwing away current and making a brand new pull request and large chunk of "paper work", just because you, guys, are not friendly to 3rd party contributions (or slow, or whatever else - please, find and fire).

Unfortunately I'll have time to do the adjustment only in next several weeks.

2017-05-13 23:16 UTC, AkihiroSuda commented
CL is now Docker, Inc.'s product and not under the scope of Moby project. (https://github.com/moby/moby/pull/32694)

I carried this PR to https://github.com/docker/cli/pull/80

> you, guys, are not friendly to 3rd party contributions (or slow, or whatever else - please, find and fire).

Even I'm one of 3rd party contributors, not an employee of Docker, Inc. 😕

2017-05-15 08:58 UTC, thaJeztah commented
@Sergeant007 please try to keep your [comments respectful](https://github.com/moby/moby/blob/v17.03.0-ce/CONTRIBUTING.md#docker-community-guidelines)? We realise there's extra work needed during the transition to a separate Moby project and Docker product, which we're right in the middle of. We _do_ try to review and merge PR's as quickly as possible, but rebases and merge-conflicts cannot be avoided in a fast moving repository, but are happy to help where needed.

2017-05-18 04:20 UTC, AkihiroSuda commented
merged https://github.com/docker/cli/pull/80, closing

2017-05-18 04:20 UTC, closed without merging