Update kill.md
moby/moby pull request #32803
Opened 2017-04-25 03:39 UTC by scjane

Related to docker/docker.github.io/issues/1054. 
Add information describing that a container can be killed by its ID or name using this command.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-04-25 03:39 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-5" git@github.com:scjane/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-25 12:13 UTC, duglin commented
@scjane please sign your commit
LGTM once signed

2017-04-25 21:30 UTC, thaJeztah requested changes
spotted a typo, but looks good after that is addressed, and the commit is signed-off

2017-04-25 21:30 UTC, thaJeztah commented on docs/reference/commandline/kill.md
> +You can kill a container using the conatiner's ID or name. The main process inside the container will be sent `SIGKILL`, or any
s/conatiner's/container's/

2017-04-26 02:56 UTC, scjane commented
@thaJeztah Sorry for producing a typo. I've fixed it.

2017-04-26 12:38 UTC, vdemeester commented
@scjane can you squash and sign your commit ? 👼

2017-04-26 17:21 UTC, mdlinville approved these changes
LGTM after squash and sign.

2017-04-26 20:17 UTC, johndmulhausen commented
@scjane Run these instructions and then they can merge this. These instructions sign the commit, they don't change the contents or anything. Takes just a few seconds. :)

```
$ git clone -b "patch-5" git@github.com:scjane/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
```

2017-05-09 21:41 UTC, mlaventure approved these changes
LGTM

2017-05-09 21:42 UTC, mlaventure commented
@scjane could you sign and squash the PR?

2017-05-10 09:04 UTC, scjane commented
@mlaventure Sorry, I failed to amend the commit because my SourceTree client went wrong. I tried to fix it but nothing took effect.

2017-05-11 14:59 UTC, mlaventure commented
@scjane What's the issue? maybe we can help?

2017-06-29 08:04 UTC, AkihiroSuda commented
ping @scjane

2017-06-29 08:21 UTC, thaJeztah commented
Carried in https://github.com/docker/cli/pull/264

2017-06-29 08:21 UTC, closed without merging