Clarify --env-file usage with names without values
moby/moby pull request #32888
Opened 2017-04-27 09:15 UTC by denis-soundcloud

This extends the documentation for `run --env-file` to also mention the possibility of specifying env var names without values (e.g. `USER`), which will let `docker run` take the value of the env var from the host environment.

This is supported and documented for `-e/--env`, but it also works for `--env-file`, which isn’t documented.

2017-04-27 09:15 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "clarify-env-file-without-value" git@github.com:denis-soundcloud/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-04-27 16:19 UTC, mdlinville approved these changes

2017-04-27 22:07 UTC, thaJeztah requested changes
changes LGTM, but can you squash the commits so that there's a single commit in this PR? You can find some instructions on doing so in the contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently

2017-04-28 07:04 UTC, denis-soundcloud commented
@thaJeztah Done!

2017-04-28 23:03 UTC, thaJeztah approved these changes
perfect, thanks!

LGTM

2017-04-28 23:03 UTC, merged