fix some typos for plugin
moby/moby pull request #32908
Opened 2017-04-28 02:16 UTC by yuexiao-wang

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**- What I did**
fix some typos for plugin

2017-04-28 02:43 UTC, AkihiroSuda requested changes

2017-04-28 02:43 UTC, AkihiroSuda commented on docs/reference/commandline/plugin_create.md
> -
Empty lines are added consistently across all the files in the `commandline` directory

2017-04-28 06:33 UTC, yuexiao-wang commented on docs/reference/commandline/plugin_create.md
> -
It is inconsistent with docker commands output.  Why added empty lines?

2017-04-28 06:38 UTC, AkihiroSuda commented on docs/reference/commandline/plugin_create.md
> -
so that input can be distinguished from the output, I guess

2017-04-28 06:49 UTC, yuexiao-wang commented on docs/reference/commandline/plugin_create.md
> -
Well.  I will recover these empty lines

2017-04-28 07:02 UTC, yuexiao-wang commented
@AkihiroSuda  
It is updated and PTAL

2017-04-28 07:07 UTC, AkihiroSuda approved these changes
LGTM

2017-04-29 02:09 UTC, thaJeztah approved these changes
LGTM

2017-04-29 02:09 UTC, merged