daemon/info: don't sort authorization plugins as order matters
moby/moby pull request #32937
Opened 2017-04-30 16:35 UTC by dsheets

#30474 started sorting authorization plugins in `/info` responses but AuthZ plugins exist in a chain that composes potentially mutating requests and responses. This simply reverts the sorting of AuthZ plugins so that the `/info` API endpoint returns the internal ordering used for AuthZ composition.

Volume driver plugins are not affected because they are just a set.

**- What I did**

Removed the sorting of AuthZ plugins reported on the `/info` endpoint.

**- How I did it**

Returned the implementation to its state before #30474 with respect to AuthZ plugins.

**- How to verify it**

AuthZ plugins are now reported via `/info` in the order they are used.

**- Description for the changelog**

This probably doesn't need a mention? Unless you think it is a bugfix worth mentioning?

**- A picture of a cute animal (not mandatory but encouraged)**

<img src="https://userscontent2.emaze.com/images/07526565-6061-4434-89ee-5973d18971a9/d746e06bec5611061409ee31d3899649.jpeg">

2017-05-01 20:28 UTC, cpuguy83 approved these changes
LGTM

2017-05-01 21:14 UTC, aaronlehmann commented
LGTM

2017-05-01 21:56 UTC, thaJeztah requested changes
changes LGTM, but can you squash your commits?

2017-05-02 08:40 UTC, dsheets commented
Squashed.

2017-05-02 08:45 UTC, vdemeester approved these changes
LGTM 🦁

2017-05-02 12:11 UTC, merged