Adding csv format parameters to network option in service create/update
moby/moby pull request #32975
Opened 2017-05-02 21:44 UTC by abhinandanpb

**- What I did**
Added capability to service create/update  to accept network option in csv format and add test case to verify the same.

**- How I did it**
Changed --network , --network-add options to accept csv format key/value by create a new network option type. 

**- How to verify it**
docker service create --name web --network name=docknet,alias=web1,alias=web2 nginx
docker service create --name web --network docknet nginx
docker service update web --network-add name=docknet,alias=web1
docker service update web --network-rm docknet

**- A picture of a cute animal (not mandatory but encouraged)**

![polar-bear](https://cloud.githubusercontent.com/assets/784144/25640747/acccb80c-2f45-11e7-8dc5-188ee564964e.jpg)

2017-05-04 23:06 UTC, mavenugo commented
ping @thaJeztah

2017-05-04 23:11 UTC, thaJeztah commented
Thanks! Should we have the same format added to `docker container create/run` to keep parity?

2017-05-04 23:12 UTC, thaJeztah commented
Also this relates to https://github.com/moby/moby/issues/31964 (although not all of the options are implemented yet)

2017-05-04 23:31 UTC, thaJeztah commented
Hm, is this by design, or overlooked?

```bash
docker network create -d overlay docknet

docker service create \
  --name web \
  --network name=docknet,alias=web1,alias=web2 \
  --network name=docknet,alias=web3,alias=web4 \
  nginx:alpine
```

2017-05-04 23:36 UTC, thaJeztah commented
Hm, looks like that's already possible in 17.05 (attach twice to the same network), gonna check 17.03/17.04

2017-05-04 23:39 UTC, abhinandanpb commented
@thaJeztah : you beat me to it. Yes its possible in the current code as well. I can add a sanity check as well.
As Far as  #31964 I am in the process of extending the network options to have driver options as well. So the plan is to support network name , alias, driver specific option for the network.

2017-05-04 23:39 UTC, mavenugo commented
@thaJeztah we should get this for `docker run` as well... but we can address it using another PR as these are fairly independent and also there is more work involved for `docker run` to support multiple networks.

And yes, this is related to #31964 the only 2 networks options that we support today for `docker service` are network `name` and `alias`. As we support other options, we can start to add to this CSV format.

2017-05-05 01:30 UTC, thaJeztah requested changes
design LGTM - the validation for duplicate networks can be separate from this, but is probably something that needs to be fixed.

moving to code review (left some initial comments)

2017-05-05 01:30 UTC, thaJeztah commented on opts/network.go
> +			return fmt.Errorf("invalid field key %s", key)
I think we should make the error messages consistent with what we have for `--mount`, e.g. https://github.com/moby/moby/blob/49376cddab7d2ea28fd08fbbb75522656a72ed09/opts/mount.go#L129

2017-05-05 01:30 UTC, thaJeztah commented on opts/network.go
> +			return fmt.Errorf("invalid field %s", field)
Same here for consistent error messages https://github.com/moby/moby/blob/49376cddab7d2ea28fd08fbbb75522656a72ed09/opts/mount.go#L82

2017-05-05 01:30 UTC, thaJeztah commented on opts/network.go
> +	n.networkAttachments = append(n.networkAttachments, netAttach)
Should we validate here if `netAttach.name` (or `ID`?) is set?

2017-05-08 13:44 UTC, abhinandanpb commented on opts/network.go
> +			return fmt.Errorf("invalid field %s", field)
@thaJeztah I was. following the error message https://github.com/moby/moby/blob/master/opts/port.go#L43

2017-05-08 13:44 UTC, abhinandanpb commented on opts/network.go
> +			return fmt.Errorf("invalid field key %s", key)
same as above

2017-05-08 13:45 UTC, abhinandanpb commented on opts/network.go
> +	n.networkAttachments = append(n.networkAttachments, netAttach)
both work. So shouldn't be a problem

2017-05-08 13:46 UTC, abhinandanpb commented
@thaJeztah thanks for taking a quick look. I will split this pr in docker/cli and here to continue the discussion further.

2017-05-11 16:43 UTC, abhinandanpb commented
closing this in favor of #33130

2017-05-11 16:43 UTC, closed without merging