fix inconsistent state string with containerd
moby/moby pull request #33075
Opened 2017-05-08 04:02 UTC by x1022as

should be `stopped` according to containerd:
  https://github.com/containerd/containerd/blob/v0.2.x/runtime/runtime.go#L104

Signed-off-by: Deng Guangxing <dengguangxing@huawei.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-05-08 04:40 UTC, AkihiroSuda commented
cc @mlaventure @crosbymichael

2017-05-08 14:23 UTC, mlaventure requested changes

2017-05-08 14:23 UTC, mlaventure commented on libcontainerd/client_linux.go
> +	if err != nil || cont.Status == "stopped" {
good catch!

Could you use "github.com/containerd/containerd/runtime".Stopped instead though?

2017-05-09 11:36 UTC, x1022as commented on libcontainerd/client_linux.go
> +	if err != nil || cont.Status == "stopped" {
@mlaventure ,Thanks, I have tried to update vendor with hack/vendor.sh, but failed because of network problems. feel free to take this pr over  :)

2017-05-09 14:42 UTC, cpuguy83 commented on libcontainerd/client_linux.go
> +	if err != nil || cont.Status == "stopped" {
Pushing an update momentarily.

2017-05-09 14:51 UTC, mlaventure commented on libcontainerd/client_linux.go
> +	if err != nil || cont.Status == "stopped" {
@cpuguy83 oups, I think I did override yours :sweat_smile:

2017-05-09 15:02 UTC, cpuguy83 commented on libcontainerd/client_linux.go
> +	if err != nil || cont.Status == "stopped" {
Let's fix vendors first: https://github.com/moby/moby/pull/33111 so this commit is focused on just the containerd revendor.

2017-05-15 14:23 UTC, thaJeztah commented
ping @mlaventure looks like the vendoring needs another update 😅

2017-05-15 21:15 UTC, mlaventure approved these changes

2017-05-15 23:02 UTC, thaJeztah commented
ping @crosbymichael @cpuguy83 PTAL

2017-05-16 23:43 UTC, cpuguy83 approved these changes
LGTM

2017-05-17 13:27 UTC, merged