Update make.ps1 to respect client repo
moby/moby pull request #33123
Opened 2017-05-09 20:12 UTC by johnstep

Signed-off-by: John Stephens <johnstep@docker.com>

This is important for merging #32571 because it requires building the client from a fork.

2017-05-09 20:18 UTC, thaJeztah commented
ping @friism @jhowardmsft

2017-05-09 20:22 UTC, aaronlehmann commented
LGTM

2017-05-09 20:28 UTC, jhowardmsft commented
Hmmm. I'm not sure where this addition came from - I don't think I was pinged on it, and it needs some revision. Havent had time to look at the history.

1. I'm not keen on it cloning to ..  What if run on a dev machine and it clobbers an existing repo? To be safe, it should clone to a directory under %TEMP%.

2. It has no fail-safe for git failing and not popd as for the other pushd already in the file.

2017-05-09 21:04 UTC, tiborvass commented
LGTM

2017-05-09 21:42 UTC, lowenna requested changes
As per comment, should clone to %temp% to avoid clobbering.

2017-05-10 00:15 UTC, tiborvass commented
@jhowardmsft I agree with you, let's fix it in another PR. This PR is about allowing to specify a fork of the docker/cli repo.

2017-05-10 00:21 UTC, tiborvass approved these changes

2017-05-10 02:03 UTC, merged

2017-05-10 02:07 UTC, jhowardmsft commented
K. Could you file an issue so it doesn't get forgotten please?

2017-05-10 07:59 UTC, johnstep commented
I opened #33131 to build to a temporary directory.