Build client on Windows in a temporary directory
moby/moby pull request #33131
Opened 2017-05-10 07:29 UTC by johnstep

Signed-off-by: John Stephens <johnstep@docker.com>

2017-05-10 16:58 UTC, jhowardmsft commented
Sooooo much better. I think it could do with a couple of tweaks to not be so verbose (using `--quiet`) and catch any git errors. Something like this:

```PowerShell
            # Temporarily override GOPATH, then clone, checkout, and build.
            $saveGOPATH = $env:GOPATH
            Try {
                $env:GOPATH = $tempLocation
                $dockerCliRoot = "$env:GOPATH\src\$($dockerCliRepo.Split("/", 3)[2])"
                Write-Host "INFO: Cloning client repository from $dockerCliRepo..."
                git clone --quiet $dockerCliRepo $dockerCliRoot
                if ($LASTEXITCODE -ne 0) { Throw "Failed to clone client repository" }
                Write-Host "INFO: Checking out client commit $dockerCliCommit..."
                git -C $dockerCliRoot -c advice.detachedHead=false checkout --quiet $dockerCliCommit
                if ($LASTEXITCODE -ne 0) { Throw "Failed to checkout client commit $dockerCliCommit" }
                Write-Host "INFO: Building client..."
                go build -o "$root\bundles\docker.exe" "github.com/docker/cli/cmd/docker"
                if ($LASTEXITCODE -ne 0) { Throw "Failed to compile client" }
            }
            Catch [Exception] {
                Throw $_
            }
            Finally {
                # Always restore GOPATH and remove the temporary directory.
                $env:GOPATH = $saveGOPATH
                Remove-Item -Force -Recurse $tempLocation
            }
```

2017-05-10 16:58 UTC, jhowardmsft commented on hack/make.ps1
> +                git clone $dockerCliRepo $dockerCliRoot
Errors here need to be captured too.

2017-05-10 17:02 UTC, lowenna requested changes
See larger comment, but looks pretty good. Just a few nits need addressing.

2017-05-10 17:02 UTC, jhowardmsft commented on hack/make.ps1
> +                git -C $dockerCliRoot -c advice.detachedHead=false checkout $dockerCliCommit
Same here

2017-05-10 18:50 UTC, lowenna reviewed
LGTM 😸

2017-05-10 18:50 UTC, lowenna approved these changes

2017-05-15 13:21 UTC, thaJeztah approved these changes
LGTM

2017-05-15 13:22 UTC, merged