Fix Markdown problem in ps ref
moby/moby pull request #33140
Opened 2017-05-10 16:21 UTC by mstanleyjones

The `|` symbol is being interpreted as a table delimiter where it shouldn't. Also standardize some formatting. Originally reported in https://github.com/docker/docker.github.io/issues/3219 and a temporary docs fix is at https://github.com/docker/docker.github.io/pull/3221

![water bear](http://www.jimgworld.com/beta/wbear1.jpg)

2017-05-10 17:24 UTC, thaJeztah requested changes

2017-05-10 17:24 UTC, thaJeztah commented on docs/reference/commandline/ps.md
> +* id (`container's id`)
Given that the `container's id` is not a literal value, should we swap the formatting for these?

```Markdown
* `id` (container's id)
* `label` (`label=<key>` or `label=<key>=<value>`)
* `name` (container's name)
```

(and so on)

2017-05-10 17:49 UTC, mstanleyjones commented on docs/reference/commandline/ps.md
> +* id (`container's id`)
I thought about it. I think it's good to have it formatted somehow. Maybe italics?

2017-05-10 19:16 UTC, thaJeztah commented on docs/reference/commandline/ps.md
> +* id (`container's id`)
With the list getting quite lengthy; should we start thinking of a table?

2017-06-20 20:41 UTC, cpuguy83 approved these changes
LGTM

2017-06-20 22:50 UTC, thaJeztah commented
This has to be in the docker/cli repository now; @mstanleyjones can you reopen there?

2017-06-20 22:50 UTC, closed without merging