docs: add docs for build —target
moby/moby pull request #33185
Opened 2017-05-13 00:14 UTC by tonistiigi

fixes https://github.com/moby/moby/issues/33143

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

2017-05-13 00:24 UTC, dnephin approved these changes
LGTM

2017-05-15 11:34 UTC, thaJeztah requested changes
left some comments.

This also needs to be added to the man-page; https://github.com/moby/moby/blob/master/man/docker-build.1.md

2017-05-15 11:34 UTC, thaJeztah commented on docs/reference/commandline/build.md
> +speficy an intermediate build stage by name as a final stage for the resulting
s/speficy/specify/

2017-05-15 11:34 UTC, thaJeztah commented on docs/reference/commandline/build.md
> +    $ docker build -t mybuildimage --target build-env .
Can you put this in fences with a `bash` language-hint?

    ```bash
    $ docker build -t mybuildimage --target build-env .
    ```

2017-05-15 16:59 UTC, tonistiigi commented
@thaJeztah PTAL

2017-05-15 20:14 UTC, thaJeztah approved these changes
LGTM

2017-05-15 20:14 UTC, merged