Add a error check in postHijacked to avoid docker exec command blocking.
moby/moby pull request #33262
Opened 2017-05-18 02:07 UTC by keloyang

When user execute docker exec command(client.ContainerExecAttach), docker daemon maybe have err return because
of ExecExists check, and then the hijack stream will not be close, it can lead to docker exec command block.

Signed-off-by: yangshukui <yangshukui@huawei.com>

**- What I did**
Add a error check in postHijacked to avoid docker exec command blocking.

**- How to verify it**

with the follown steps， the problem can be reproduced easyly.
1. start a testone container
```
docker run -d --name testone ubuntu bash -c 'for (( i = 1; i <= 200000; i++ )) do echo -n "$i";sleep 1;done'
```
2. run pause.sh
```
#!/bin/bash
while true; do
        docker pause testone
        docker unpause testone
done
```
3. run exec.sh
```
#!/bin/bash
while true; do
        echo "exec ${i}th times"
        docker exec -ti testone bash  -c "sleep 0.5 ;exit"
        ((i++))
done
```
just wait a minute, you will see the blocking.

you can also modify daemon'code to help reproduce like this:
```
--- a/api/server/router/container/exec.go
+++ b/api/server/router/container/exec.go
@@ -77,7 +77,7 @@ func (s *containerRouter) postContainerExecStart(ctx context.Context, w http.Res
        if err := json.NewDecoder(r.Body).Decode(execStartCheck); err != nil {
                return err
        }
-
+       time.Sleep(2 * time.Second)
        if exists, err := s.backend.ExecExists(execName); !exists {
                return err
        }
```
then run " docker unpause testone; sleep 2;docker pause testone" in a shell, and run " docker exec -ti testone bash  -c "sleep 0.5 ;exit"" in another shell immediately.

2017-05-19 05:42 UTC, keloyang commented
ping @dnephin

2017-05-19 08:19 UTC, coolljt0725 commented
ping @vdemeester  @thaJeztah

2017-05-19 13:53 UTC, cpuguy83 approved these changes
LGTM

2017-05-19 13:53 UTC, cpuguy83 commented on client/hijack.go
> +	if resp != nil {
This nil check looks like it's not needed.

2017-05-19 13:58 UTC, thaJeztah requested changes

2017-05-19 13:58 UTC, thaJeztah commented on client/hijack.go
> +	if resp != nil {
Yes, I think it's cleaner without @keloyang can you remove it?

2017-05-19 14:05 UTC, dnephin commented on client/hijack.go
> +	}
What do you think about something like this:

```go

defer ensureReaderClosed(resp)

switch resp.StatusCode {
case http.StatusOK, http.StatusSwitchingProtocols:
    rwc, br := clientconn.Hijack()
    return types.HijackedResponse{Conn: rwc, Reader: br}, nil
}

body, err := ioutil.ReadAll(resp.Body)
...
return types.HijackedResponse{}, fmt.Errorf("...")
```

I think you want the response closed called in both cases?

2017-05-20 01:50 UTC, keloyang commented on client/hijack.go
> +	if resp != nil {
It's true that I need remove it , thank you.

2017-05-20 02:16 UTC, keloyang commented on client/hijack.go
> +	}
@dnephin ，thanks for your review and advice. 
I just want the response close called when resp.StatusCode != http.StatusOK(or http.StatusSwitchingProtocols)， If  resp.StatusCode is http.StatusSwitchingProtocols, do we must close the resp ? I'm not sure.

2017-05-25 01:05 UTC, keloyang commented
ping @thaJeztah

2017-06-05 00:55 UTC, keloyang commented
ping @thaJeztah @dnephin @aaronlehmann

2017-06-07 11:56 UTC, thaJeztah requested changes
left one suggestion, but LGTM otherwise

ping @dnephin PTAL as well

2017-06-07 11:56 UTC, thaJeztah commented on client/hijack.go
> +	if resp != nil {
I think the previous comment https://github.com/moby/moby/pull/33262#discussion_r117484500 meant to say that we don't have to check `resp` if `err != nil`; we can still return early here, to reduce complexity, e.g.;

```go
resp, err := clientconn.Do(req)
if err != nil {
	return types.HijackedResponse{}, err
}

defer resp.Body.Close()

switch resp.StatusCode {
case http.StatusOK, http.StatusSwitchingProtocols:
	rwc, br := clientconn.Hijack()
	return types.HijackedResponse{Conn: rwc, Reader: br}, err
}
body, err := ioutil.ReadAll(resp.Body)
if err != nil {
	return types.HijackedResponse{}, err
}
return types.HijackedResponse{}, fmt.Errorf("Error response from daemon: %s", bytes.TrimSpace(body))
```

2017-06-08 06:11 UTC, coolljt0725 commented
@keloyang  squash your commits

2017-06-08 07:32 UTC, keloyang commented
@coolljt0725 , I apologize and update the pr. Thank you.

2017-06-08 19:27 UTC, dnephin approved these changes
LGTM

2017-06-08 19:42 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-06-09 01:20 UTC, merged

2017-06-12 18:32 UTC, tonistiigi commented on client/hijack.go
> +	case http.StatusOK, http.StatusSwitchingProtocols:
@keloyang Why is `StatusOK` allowed here?

2017-06-13 03:01 UTC, keloyang commented
```
func (s *containerRouter) postContainersAttach(ctx context.Context, w http.ResponseWriter, r *http.Request, vars map[string]string) error {
        err := httputils.ParseForm(r)
        if err != nil {
                return err
        }
        containerName := vars["name"]

        _, upgrade := r.Header["Upgrade"]
        detachKeys := r.FormValue("detachKeys")

        hijacker, ok := w.(http.Hijacker)
        if !ok {
                return fmt.Errorf("error attaching to container %s, hijack connection missing", containerName)
        }

        setupStreams := func() (io.ReadCloser, io.Writer, io.Writer, error) {
                conn, _, err := hijacker.Hijack()
                if err != nil {
                        return nil, nil, nil, err
                }

                // set raw mode
                conn.Write([]byte{})

                if upgrade {
                        fmt.Fprintf(conn, "HTTP/1.1 101 UPGRADED\r\nContent-Type: application/vnd.docker.raw-stream\r\nConnection: Upgrade\r\nUpgrade: tcp\r\n\r\n")
                } else {
                        fmt.Fprintf(conn, "HTTP/1.1 200 OK\r\nContent-Type: application/vnd.docker.raw-stream\r\n\r\n")
                }
...
```

2017-06-13 16:43 UTC, tonistiigi commented
@keloyang But this function always sends the `upgrade` header so it should not reach the second condition.

2017-06-14 01:33 UTC, keloyang commented
@tonistiigi thanks. I have found that out, if we don't  allowe StatusOK  in postHijack，we should remove 'fmt.Fprintf(conn, "HTTP/1.1 200 OK\r\nContent-Type: application/vnd.docker.raw-stream\r\n\r\n")' from docker daemon, WDYT ?
and ping @dnephin @thaJeztah

2017-06-14 01:38 UTC, tonistiigi commented
It may be backward compatibility with older clients(didn't confirm), but shouldn't be a problem for the client pkg as we didn't support new clients with old daemon until very recently.

2017-06-14 01:54 UTC, keloyang commented
Do we have any problems to allow  StatusOK in postHijack ?