fix typos using misspell
moby/moby pull request #33312
Opened 2017-05-20 05:32 UTC by aspala

This PR is part of a campaign to fix a lot of typos on github!
You can see the progress on https://github.com/fixTypos/fix_typos/

https://github.com/client9/misspell

**-what I did:**
fixed typos within comments

**-how-to-verify**
see changes : D

**-description for the changelog**
Fixed typos

**-picture of cute animal**
![img_0095](https://cloud.githubusercontent.com/assets/2420034/26273320/4f5b3c38-3d2e-11e7-977d-64f5aa96b089.JPG)

2017-05-20 20:18 UTC, albers commented
LGTM - Thanks!

2017-05-22 13:04 UTC, thaJeztah commented on Dockerfile.windows
> +# The number of build steps below are explicitly minimized to improve performance.
🇬🇧 :smile:

2017-05-22 13:07 UTC, thaJeztah requested changes
Found one change that wasn't correct

2017-05-22 13:07 UTC, thaJeztah commented on pkg/namesgenerator/names-generator.go
> +		// Johanna Mestorf - German prehistoric archeologist and first female museum director in Germany - https://en.wikipedia.org/wiki/Johanna_Mestorf
I think the original was good here

2017-06-20 20:18 UTC, cpuguy83 commented
Ping.
Can you fix the one issue and then remove the docs changes? Docs are now in github.com/docker/cli.
Let us know, or we can carry. Thanks!

2017-06-21 06:53 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "fix_typos" git@github.com:fixTypos/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354073648
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-06-21 07:13 UTC, closed without merging