Stop referring CLI flags in error messages if API client is unknown
moby/moby pull request #33320
Opened 2017-05-21 18:02 UTC by sbko

Made error messages more generic. 

Fixes #33138

2017-05-21 18:19 UTC, sbko commented
For some reason make unit-test didn't catch what windowsRS1 catched. I'll push a fix to tests

2017-05-22 00:57 UTC, fntlnz commented
I would change also [api/server/router/experimental.go:14](https://github.com/moby/moby/blob/242060302a71279b7f1e9fd5031401f0aa8376ab/api/server/router/experimental.go#L14) considering the fact that also daemon options are not only be passed as parameters.

2017-05-22 01:16 UTC, sbko commented
@fntlnz thanks! I checked only fmt.Errorf(...). I'll search for errors.New(...) as well.

2017-05-22 13:19 UTC, cpuguy83 requested changes

2017-05-22 13:19 UTC, cpuguy83 commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support SecurityOpt to build")
"does not support setting security options on build"

2017-05-22 13:19 UTC, cpuguy83 commented on runconfig/hostconfig_unix.go
> +		return fmt.Errorf("invalid QoS settings: %s does not support configuration of IO maximum bandwidth", runtime.GOOS)
"does not support configuration of maximum bandwidth"

2017-05-22 13:19 UTC, cpuguy83 commented on runconfig/hostconfig_unix.go
> +		return fmt.Errorf("invalid QoS settings: %s does not support configuration of IO maximum IOps", runtime.GOOS)
"does not support configuration of maximum IOPs"

2017-05-22 13:22 UTC, thaJeztah commented
Thanks for working on this!

2017-05-22 14:43 UTC, fntlnz requested changes

2017-05-22 14:43 UTC, fntlnz commented on runconfig/hostconfig_windows.go
> +		return fmt.Errorf("container network stack unsupported for hyperv isolation")
I would write: Using the network stack of another  container is not supported while using Hyper-V Containers

2017-05-22 14:43 UTC, fntlnz commented on api/server/router/build/build_routes.go
> +		return nil, fmt.Errorf("the daemon on this platform does not support SecurityOpt to build")
I would start with a capital letter

2017-05-22 14:43 UTC, fntlnz commented on runconfig/hostconfig_unix.go
> +		return fmt.Errorf("invalid QoS settings: %s does not support configuration of IO maximum IOps", runtime.GOOS)
capital letter here

2017-05-22 14:43 UTC, fntlnz commented on runconfig/hostconfig_unix.go
> +		return fmt.Errorf("invalid QoS settings: %s does not support configuration of IO maximum bandwidth", runtime.GOOS)
capital letter here

2017-05-22 14:43 UTC, fntlnz commented on runconfig/hostconfig.go
> +			return fmt.Errorf("invalid network mode: invalid container format container:<name|id>")
capital letter here

2017-05-22 14:43 UTC, fntlnz commented on runconfig/hostconfig_windows.go
> +		return fmt.Errorf("container network stack unsupported for hyperv isolation")
And also use a capital letter to start the phrase

2017-05-23 01:42 UTC, sbko commented
@fntlnz @cpuguy83 I made changes per your request. Looks like powerpc jenkins job died. Is there a way to retrigger it?

2017-05-23 05:18 UTC, fntlnz commented
@sbko - re-triggered :innocent:

2017-05-23 10:16 UTC, sbko commented
@fntlnz thanks! It passed as well :)

2017-05-23 10:25 UTC, fntlnz approved these changes

2017-05-23 10:26 UTC, fntlnz commented
LGTM

2017-05-24 15:00 UTC, sbko commented
@cpuguy83 I'm not sure if I need to ping you after tests are done or not. but here I am pinging you :)

2017-05-25 14:58 UTC, cpuguy83 approved these changes
LGTM

2017-05-25 17:48 UTC, vdemeester approved these changes
LGTM 👼

2017-05-25 17:48 UTC, merged