Clarify nat/bridge default on Windows and add section on transparent
moby/moby pull request #33357
Opened 2017-05-23 17:55 UTC by PatrickLang

Fixes https://github.com/docker/docker.github.io/issues/3357 

**- Description for the changelog**
Doc update clarifying defaults and showing some common networking options on Windows

Signed-off-by: Patrick Lang <plang@microsoft.com>

2017-05-23 17:56 UTC, PatrickLang commented
@Kallie-b @jmesser81 want to add any more?

2017-05-24 19:22 UTC, PatrickLang commented
Well "host" also lets things like the DNS resolver and /etc/hosts from the host apply to the container. 

What do you think about this?

Linux "bridge" <-> Windows "nat"
Linux "macvlan" <-> Windows "transparent"

Based on this [post](https://blog.docker.com/2016/12/understanding-docker-networking-drivers-use-cases/) _The bridge driver creates a private network internal to the host so containers on this network can communicate. External access is granted by exposing ports to containers. Docker secures the network by managing rules that block connectivity between different Docker networks._ which to me describes what Windows does with the nat driver.

Transparent just attaches it to a vswitch giving it layer 2 switching which sounds like macvlan in that article: _The macvlan driver uses the concept of a parent interface. This interface can be a host interface such as eth0, a sub-interface, or even a bonded host adaptor which bundles Ethernet interfaces into a single logical interface. A gateway address from the external network is required during MACVLAN network configuration, as a MACVLAN network is a L2 segment from the container to the network gateway._

2017-05-24 21:59 UTC, mstanleyjones commented
Why are you not basing this on `master`?

2017-05-24 22:47 UTC, PatrickLang commented
Sure, will move it.

2017-05-30 11:16 UTC, thaJeztah requested changes
Let some comments; can you update the PR, and change its base to be against master?

2017-05-30 11:16 UTC, thaJeztah commented on docs/reference/commandline/network_create.md
> +The `transparent` network on Windows is very similar to the Linux `bridge` driver.
Can you add a blank line between the heading and the body-text? (I think some Markdown renderers don't like it if it's missing)

2017-05-30 11:16 UTC, thaJeztah commented on docs/reference/commandline/network_create.md
> +`--driver` option, the command automatically creates a `bridge` network for you on Linux, or `nat` on Windows.
Can you wrap this to 80-chars?

    `--driver` option, the command automatically creates a `bridge` network for you
    on Linux, or `nat` on Windows.

2017-05-30 11:16 UTC, thaJeztah commented on docs/reference/commandline/network_create.md
> +| `com.docker.network.windowsshim.interface`      | Existing network adapter name to bind to the transparent network |
nit: can you align the table here?

```Markdown
| Option                                          | Description                                                      |
|-------------------------------------------------|------------------------------------------------------------------|
| `com.docker.network.windowsshim.interface`      | Existing network adapter name to bind to the transparent network |
```

2017-05-30 11:16 UTC, thaJeztah commented on docs/reference/commandline/network_create.md
> +a transparent network. This example will use DHCP to obtain container IPs.
Trying to avoid future tense;

```Markdown
The following example uses DHCP to obtain container IPs:
```

2017-06-13 21:12 UTC, PatrickLang commented
I'm addressing feedback in new PR #33659 . Thanks!

2017-06-13 21:12 UTC, closed without merging