matching events using ID and name
moby/moby pull request #33377
Opened 2017-05-24 15:31 UTC by yastij

** What I did** event matching done by filtering with id and name see #33371

Signed-off-by: Yassine TIJANI <yasstij11@gmail.com>

2017-05-24 18:18 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "33371-matchevent-filtering" git@github.com:yastij/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354361376
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-05-25 13:12 UTC, yastij commented
seems that health_test are failing (flaky tests ?) : 
```
18:41:21 --- FAIL: TestHealthStates (4.00s)
18:41:21 	health_test.go:90: time limit exceeded, didn't get expected error
18:41:21 FAIL
18:41:21 coverage: 8.1% of statements
18:41:21 FAIL	github.com/docker/docker/daemon/cluster/executor/container	4.017s
```
i think that it's a timeout problem @thaJeztah

2017-06-13 09:12 UTC, thaJeztah commented
Oh, so sorry for the delay; I restarted CI to see if it is green now

Also ping @stevvooe, for who `TODO` was there :smile:

2017-06-13 09:17 UTC, yastij commented
@thaJeztah it's not a blocker so it's okay 😄

2017-06-13 18:39 UTC, stevvooe commented
@yastij So, if it was this easy, I wouldn't have just put a TODO there. ;)

Make sure that the value for `container.id()` is the correct value. There are cases where it is not available quite yet, due to races during creation. Once that problem is solved this is trivial. Granted, things may have changed since that TODO was in place, so this may not be quite as challenging.

2017-06-14 06:03 UTC, yastij commented
@stevvooe - indeed, will correct it tomorrow, thanks for the info. ;)

2017-06-14 17:36 UTC, stevvooe commented
@yastij Actually, the method used here isn't returning the container's id, at all. If we look at https://github.com/moby/moby/blob/master/daemon/cluster/executor/container/container.go#L92, it is returning the container id for a network attachment. 

This is very unfortunate, but I'm glad we found it! I've filed #33679. You are welcome to address that but you don't have to.

Luckily, I think you can resolve it by getting the id after the creation step: https://github.com/moby/moby/blob/master/daemon/cluster/executor/container/adapter.go#L217. The error handling in https://github.com/moby/moby/blob/master/daemon/cluster/executor/container/controller.go#L152 handles the case where the container is already created (such as resolving after restart), so you will have to register it in that case, as well.

2017-06-14 19:08 UTC, yastij commented
@stevvooe - i'll patch this one first, and then get to #33679, many thanks for the help.

2017-06-14 21:07 UTC, yastij commented
i'll patch this one first, and then get to #33679, many thanks for the help.

EDIT : @stevvooe - maybe we have to change the create function so that it returns a ` <- chan, err` using ctx, in order to perform id access

2017-06-14 21:20 UTC, stevvooe commented
> EDIT : @stevvooe - maybe we have to change the create function so that it returns a <- chan, err, in order to notify for id access.

I'd not sure that is necessary, but it will have to protected by a mutex. The create call should end with an id, but we need to have this only get used when needed.

(And you can see why this was a TODO. :P, Thank you so much for tackling this!)

2017-06-14 21:43 UTC, yastij commented
@stevvooe - indeed, this one is a bit racy (this worths the TODO hehe :P)

so to summarize : 

We should have a mutex that acquires lock before creation then release it, and id access locking until creation.

but isn't it the same if we used channels to sync ?

2017-06-15 20:56 UTC, stevvooe commented
Yes, the access needs to be synchronized. You could use channels, but I'm not sure that would be easier here, and you definitely don't need to change the method signature to create to achieve that. I might have something like this:

```go
func (c *containerConfig) setID(id string) {
  select {
  case <-c.idset:
    log.L.Warn("container id set twice")
  default:
    c.setIDOnce.Do(func() {
      c.containerID = id
      close(c.idset)
    })
  }
 }

func (c *containerConfig) id() string {
  // include code for attachment type...
  <-c.idset
  return c.containerID
}
```

This will allow the id to be set only once. Calling `id()` will block until it is set.

The risk in something like this is the creation of a deadlock when the identifier is never set, so we need to ensure (through careful inspection) that it is only called after the container is created or has been resolved. It may also need something to handle cancellation/closure.

2017-06-16 00:42 UTC, yastij commented
@stevvooe  - LGTM, we'll go with locks. I will patch this tomorrow.

P.S : if you need to cut some issues from your backlog hit me up. Would like to help :P

2017-06-16 20:55 UTC, stevvooe commented
@yastij Sounds good.

As far as cutting issues, TODOs are good to hunt down. Mostly, I'm working on containerd right now, but try to help out reviewing and shepherding fixes like this.

Thanks for being responsive and helping to hunt down the right solution here!

2017-06-16 21:00 UTC, yastij commented
@stevvooe - my pleasure, will ping you for review.

2017-06-27 04:25 UTC, thaJeztah commented
ping @yastij have you had time to work on the proposed changes?

2017-06-27 07:47 UTC, yastij commented
@thaJeztah - sorry for the delay, i hadn't the time to work on this one. but i'm on it right now.

2017-06-27 09:53 UTC, yastij commented
mutex and channels didn't seem natural to me, so I went with a reverse-Waitgroup (wait() on match event, and decrement the count only after creation), this LGTY @stevvooe ?

2017-06-28 00:47 UTC, stevvooe commented on daemon/cluster/executor/container/controller.go
> +	// see https://github.com/moby/moby/pull/33377 for more information
Its not good to reference issues. You should explain what the code does in line.

2017-06-28 00:47 UTC, stevvooe commented on daemon/cluster/executor/container/controller.go
> +	r.idset.Wait()
What if `Prepare` is never called? This can happen when an engine is restarted -- the controller will skip the prepare stage.

2017-06-28 02:49 UTC, thaJeztah commented
Looks like there's an issue;

```
13:35:40 daemon/cluster/executor/container/controller.go:58: literal copies lock value from idset: sync.WaitGroup contains sync.noCopy
13:35:40 exit status 1
```

2017-06-29 12:32 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> +	// see https://github.com/moby/moby/pull/33377 for more information
yup, you're right.

2017-06-29 12:41 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> +	r.idset.Wait()
stated it on my last comment. one solution is to access state of the container inside the `matchevent`. but that would require us passing `ctx` to the`matchevent` no ?

2017-06-29 13:19 UTC, yastij commented
@thaJeztah - thanks, just fixed this one.

2017-06-30 08:00 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> +	// see https://github.com/moby/moby/pull/33377 for more information
yup, you're right.

2017-07-06 10:09 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> +	r.idset.Wait()
@stevvooe - this solution LGTY ?

2017-07-06 20:31 UTC, stevvooe commented on daemon/cluster/executor/container/controller.go
> +	r.idset.Wait()
The problem with this approach is that it does not encapsulate this requirement for the caller of `adaptor.container.id()`. If it gets used elsewhere, they also need to wait on `idset`.

2017-07-06 20:49 UTC, stevvooe commented
@yastij I'm starting to wonder if the fix here is merely to remove the TODO. Matching on container name has proven effective and the current solutions seem to add more complexity than necessary. Unless we have seen a real bug because of this, I am afraid we may introduce a deadlock with this fix.

I'm sorry we went through a few revisions.

2017-07-06 20:54 UTC, yastij commented
Yes you may be right. But the container name is unique only on the node where he exists. Using swarm-mode names might collide ? If so we should clearly state it somewhere.

No apologies at least we explored it !

2017-07-06 21:45 UTC, stevvooe commented
@yastij The container id is a triple of service name, task slot and task id. The task id is very collision proof, with 128-bits of entropy. `nostalgic_hypatia.1.33xmdmc6v8cvq9zs8ut8nba5y` is an example, so this shouldn't be an issue. We chose collision resistant names to avoid having to solve these problems.

> No apologies, at least we explored it !

Sign of a true dev! :hamster: 

I guess, just remove the TODO?

2017-07-06 21:51 UTC, yastij commented
🤓

Will remove the TODO by tomorrow !

2017-07-07 19:10 UTC, stevvooe commented on daemon/cluster/executor/container/controller.go
> -
Don't delete this whitespace.

2017-07-07 19:35 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> -
It's done by go fmt, but i can add it

2017-07-07 20:12 UTC, stevvooe commented on daemon/cluster/executor/container/controller.go
> -
Fair enough. I guess we can leave it alone if `gofmt` removed the line.

2017-07-07 20:12 UTC, stevvooe commented
LGTM

2017-07-07 20:56 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> -
Too late added it while squashing 

P.S: this CI hates me 😁

2017-07-07 21:20 UTC, thaJeztah requested changes
Thanks for going through these iterations 👍 

I left one comment to fix; ideally I'd love to see the whitespace changes being removed as well, but that's less of an issue

Reason we try to avoid those is that it may complicate cherry-picking, or introduce merge conflicts in other pull requests, so we try to keep diffs as small as possible.

2017-07-07 21:20 UTC, thaJeztah commented on daemon/cluster/executor/container/controller.go
> +	"os"
Can you put these back at the top? Convention in this repo is to group imports in "standard library" imports and external imports

2017-07-07 21:24 UTC, yastij commented on daemon/cluster/executor/container/controller.go
> +	"os"
@thaJeztah - sure

2017-07-07 21:35 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-07-07 21:35 UTC, yastij commented
@thaJeztah - minimized the diffs, and squashed commits.

@stevvooe - if a bug appears on the eventmatching re-open this PR and ping me.

Thanks !

2017-07-07 21:36 UTC, thaJeztah commented
oh, it's your first time contribution 👍 🎉 ... almost merged, hope CI is nice to you this time (it should)

2017-07-07 21:38 UTC, yastij commented
@thaJeztah - hopefully not the last one :smile:

2017-07-10 14:11 UTC, merged