Don't resolve image by contacting registry for docker stack deploy tests
moby/moby pull request #33386
Opened 2017-05-25 00:07 UTC by nishanttotla

This PR turns off digest pinning for `docker stack deploy` integration-cli tests.

It should be merged as soon as the CLI changes of https://github.com/docker/cli/pull/121 are merged and included.

We did a similar thing for `docker service create` and `update` in https://github.com/moby/moby/pull/33274

NOTE: CI will fail right now, because the flag that's being added depends on https://github.com/docker/cli/pull/121

2017-06-13 21:43 UTC, nishanttotla commented
Also updated tests that were failing because they didn't account for the default `latest` digest added to service images.

2017-06-14 23:19 UTC, nishanttotla commented
Ping @aaronlehmann @vdemeester @tiborvass this PR is ready now. I'm not sure if it's okay to update the CLI commit hash, but the tests should be updated (note that these fixes were already part of the cherry picks into RC2 and RC3 for 17.06).

2017-06-14 23:42 UTC, aaronlehmann commented
LGTM

2017-06-15 17:52 UTC, thaJeztah requested changes
I'd like to have consensus on our approach  for bumping the CLI first; I'll see if we can discuss this ASAP

2017-06-15 17:55 UTC, nishanttotla commented
@thaJeztah sounds good. I updated CLI here to make sure tests pass.

2017-06-16 17:43 UTC, tiborvass commented on hack/dockerfile/binaries-commits
> +DOCKERCLI_COMMIT=4d980880f30eddec01dbe4328e0cd656a52b502b
i'm not sure about this :S

2017-06-16 17:48 UTC, nishanttotla commented on hack/dockerfile/binaries-commits
> +DOCKERCLI_COMMIT=4d980880f30eddec01dbe4328e0cd656a52b502b
@tiborvass that makes two of us.

2017-06-16 17:49 UTC, tiborvass requested changes
I suggest changing the scripts to install docker cli by downloading the released 17.06 static binary. Probably in a separate PR to not conflate the two problems.

2017-06-16 17:53 UTC, aaronlehmann commented
Let's not block this PR because we want to make changes to how the CLI is installed. Without these changes to the tests, the tests won't run correctly with the released 17.06 binary anyway.

2017-06-20 23:26 UTC, aaronlehmann commented
Has a decision been made about this one?

2017-07-11 16:53 UTC, dnephin commented
I agree we should open a PR to pin the client at the 17.06 release version.

These tests should be deleted, not updated. They're only testing the cli, so they are not providing any value in this repo. They won't catch any regressions to the cli because they are not run as part of cli changes.

2017-08-18 01:03 UTC, closed without merging