Added support for Generic Resources
moby/moby pull request #33440
Opened 2017-05-31 02:03 UTC by RenaudWasTaken

Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>
Hi !

This implements support for Generic Resources in moby (after implementing it in swarmkit).
More details can be found on the issue [here](https://github.com/moby/moby/issues/33439) and the [design doc](https://github.com/docker/swarmkit/blob/master/design/generic_resources.md)

Thanks,

2017-05-31 08:46 UTC, aaronlehmann reviewed
The design seems right to me. I agree with configuring the available resources on the node itself instead of on a manager, because that leaves open the future possibility of automatically detecting devices such as GPUs. It also fits the existing model where the node self-reports memory and CPU resources.

In the future we could potentially also add generic resource information to `NodeSpec`, so certain resources could be declared with `node update` on a manager. This could coexist with individual nodes self-reporting any resources they know about. The `NodeSpec` model might make sense for "abstract" resources (as opposed to real hardware resources). However, I think the self-reporting approach in this PR is the right place to start.

I think the main questions around this will center around UX. I'm not an expert in that area so I'll let others review this part and provide suggestions.

2017-05-31 08:46 UTC, aaronlehmann commented on daemon/cluster/convert/service.go
> +func GenericResourcesToSwarmkit(genericRes []*types.GenericResource) []*swarmapi.GenericResource {
nit: `GenericResourcesToGRPC`

2017-05-31 08:46 UTC, aaronlehmann commented on daemon/cluster/convert/service.go
> +func GenericResourcesFromSwarmkit(genericRes []*swarmapi.GenericResource) []*types.GenericResource {
nit: `GenericResourcesFromGRPC`

2017-05-31 08:46 UTC, aaronlehmann commented on api/types/swarm/task.go
> +	Discrete *GenericDiscrete
Both of these fields should have `json:",omitempty"`

2017-06-01 00:31 UTC, RenaudWasTaken commented
@aaronlehmann I've addressed your issues, fixed vendors (I think) and compilation.
Should I also update api/swagger.yaml ?

2017-06-01 05:46 UTC, aaronlehmann commented
> @aaronlehmann I've addressed your issues, fixed vendors (I think) and compilation.
> Should I also update api/swagger.yaml ?
> 
Yes, please.

2017-06-01 23:59 UTC, RenaudWasTaken commented
@aaronlehmann I've create a `ResourceObject` object to encapsulate `NanoCPUs` and `MemoryBytes` which were hardcoded in every structures.

I'm not really sure about the choice of name but because there already exists a `Resources` object I don't have any other suggestions. Do you have some idea ?

Thanks!

2017-06-06 18:35 UTC, RenaudWasTaken commented
@aaronlehmann @stevvooe @ehazlett @tonistiigi PTAL :)
Thanks!

2017-06-12 20:51 UTC, tiborvass commented
I wonder how this impacts https://github.com/moby/moby/pull/33575 by @cpuguy83

2017-06-12 21:04 UTC, RenaudWasTaken commented
@tiborvass I gave the PR a quick look and it seems to me that it wouldn't impact it :)
Though I think that the current model would let your plugin request Generic resources which I think is something that seems reasonable ?

2017-06-12 22:00 UTC, cpuguy83 commented
Agreed I don't think there is any impact.

2017-06-13 12:29 UTC, tophj-ibm commented on vendor.conf
> +github.com/docker/swarmkit 85019dae9bacf2b68b81f092c34e755e2ee76b02
Hey @RenaudWasTaken 👋 

You should be able to rebase and drop the swarmkit re-vendor now that a newer version is in moby via https://github.com/moby/moby/pull/33642.

2017-06-13 16:00 UTC, RenaudWasTaken commented on vendor.conf
> +github.com/docker/swarmkit 85019dae9bacf2b68b81f092c34e755e2ee76b02
Thanks !

2017-06-13 20:57 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "genericresource" git@github.com:RenaudWasTaken/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842353767704
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-06-19 19:43 UTC, RenaudWasTaken commented
This PR seems to be in limbo :)
Is there any ETA or process to follow @aaronlehmann @stevvooe @ehazlett @tonistiigi @aluzzardi  ?

Thanks!

2017-06-20 22:12 UTC, cpuguy83 requested changes

2017-06-20 22:12 UTC, cpuguy83 commented on api/types/swarm/task.go
> +	Str      *GenericString   `json:",omitempty"`
What does `Str` mean? I assume "string" as in "GenericString", but it's not very descriptive.

2017-06-20 22:12 UTC, cpuguy83 commented on api/types/swarm/task.go
> +	Kind  string `json:",omitempty"`
What consumes these "kind" fields? Some extra docs would be helpful here.

2017-06-20 22:18 UTC, RenaudWasTaken commented on api/types/swarm/task.go
> +	Kind  string `json:",omitempty"`
Hi !

Kind is used to describe the Kind of the resource (e.g: GPU, FPGA, ...)
It is then used when creating a service ($ docker service create --name nginx --image nginx:latest --generic-resources "GPU=2")


You can find the design doc here: https://github.com/docker/swarmkit/blob/master/design/generic_resources.md

2017-06-20 22:19 UTC, RenaudWasTaken commented on api/types/swarm/task.go
> +	Str      *GenericString   `json:",omitempty"`
Yep Str means string.
A resource can either be described by an int (SSD=3) or through a String (GPU=UUID-1)

This is described in more details in the design doc: https://github.com/docker/swarmkit/blob/master/design/generic_resources.md#use-cases

2017-06-20 22:20 UTC, RenaudWasTaken commented on api/types/swarm/task.go
> +	Str      *GenericString   `json:",omitempty"`
Do you have a more descriptive name in mind ?

2017-06-20 22:41 UTC, cpuguy83 commented on api/types/swarm/task.go
> +	Kind  string `json:",omitempty"`
So this is completely opaque and dependent on how the resource is defined by the engine administrator.
Can we add some doc around that?

2017-06-20 22:57 UTC, cpuguy83 commented on api/types/swarm/task.go
> +	Str      *GenericString   `json:",omitempty"`
That's a great question...


Maybe `NamedResourceSpec`
And likewise `DiscreteResourceSpec`.

Although I must admit I don't know what the idea is behind the naming of `Discrete`

2017-06-20 22:58 UTC, cpuguy83 commented on api/types/swarm/task.go
> +type GenericString struct {
In following with the above suggesting, `NamedGenericResource`

2017-06-20 22:58 UTC, cpuguy83 commented on api/types/swarm/task.go
> +type GenericDiscrete struct {
`DiscreteGenericResource`

2017-06-20 23:03 UTC, cpuguy83 commented on daemon/cluster/executor/container/container.go
> +		Env:          env,
How do the devices make it into the container?

2017-06-20 23:14 UTC, RenaudWasTaken commented on daemon/cluster/executor/container/container.go
> +		Env:          env,
Isolation, or resource allocation (for example gpu devices) is a totally different scope :)
This PR is about resource accounting at the scheduler level and giving users the knobs.

The problem of GPUs in containers is not an easy one and right now we are solving it with a library that can be called at the runc level: https://github.com/NVIDIA/libnvidia-container

2017-06-20 23:18 UTC, cpuguy83 commented on daemon/cluster/executor/container/container.go
> +		Env:          env,
Ah, ok. Does it make sense to expose this to the container then?

2017-06-20 23:34 UTC, RenaudWasTaken commented on daemon/cluster/executor/container/container.go
> +		Env:          env,
Well even if it's not the scope of this PR to isolate or allocate the resource, you still want at some point the container to know what resources it was assigned.

Right now we are doing this through environment variables and this allows to send the information to the runtime level.

2017-06-21 23:48 UTC, RenaudWasTaken commented
@cpuguy83 I've addressed your comments :)

2017-06-27 06:09 UTC, RenaudWasTaken commented
Rebased against master seems like this broke the WindowsRS1 jenkins :(
@cpuguy83 do you have any more comments or does this seem good to you ?

@stevvooe @ehazlett @tonistiigi can you take a look :) ?

2017-06-30 19:08 UTC, stevvooe commented on api/swagger.yaml
> +        NamedResourceSpec:
This looks very different from what is in swarmkit. https://github.com/docker/swarmkit/blob/d4a01ccd09df3e554d9efc670869fd130ed0154e/api/types.proto#L38

2017-06-30 19:10 UTC, stevvooe commented on api/types/swarm/task.go
> +	AssignedGenericResources []*GenericResource  `json:",omitempty"`
This field name is extremely awkward. Can there every be unassigned resources? These resources belong to the task and are assumed to be assigned.

2017-06-30 19:10 UTC, stevvooe commented on api/types/swarm/task.go
> +	AssignedGenericResources []*GenericResource  `json:",omitempty"`
Also, why a pointer type?

2017-06-30 19:11 UTC, stevvooe commented on api/types/swarm/task.go
> +	GenericResources []*GenericResource `json:",omitempty"`
No pointer type here.

2017-06-30 19:11 UTC, cpuguy83 commented on api/swagger.yaml
> +        NamedResourceSpec:
Sorry, this was my suggestion just reading through the API changes in this PR.

2017-06-30 19:12 UTC, stevvooe commented
So, let's make sure the names match in swarmkit. Either backport these object names to swarmkit or change these to match swarmkit. It makes it extremely hard to understand what is equivalent when they have different names.

2017-06-30 19:14 UTC, RenaudWasTaken commented on api/types/swarm/task.go
> +	AssignedGenericResources []*GenericResource  `json:",omitempty"`
No you can't have unassigned resources that case do you think `GenericResources` is enough ?

It should not be a pointer type will change that

2017-06-30 19:15 UTC, RenaudWasTaken commented on api/types/swarm/task.go
> +	GenericResources []*GenericResource `json:",omitempty"`
will change that

2017-06-30 19:15 UTC, RenaudWasTaken commented
I'll do a PR to swarmkit I think the naming @cpuguy83 proposed was better

2017-06-30 19:20 UTC, stevvooe commented on api/types/swarm/task.go
> +	AssignedGenericResources []*GenericResource  `json:",omitempty"`
`Resources` might even be okay. We'd have to flow some of this back to swarmkit (these names are a little clearer).

@aaronlehmann Thoughts? I know this has already been through a large review cycle.

2017-06-30 19:21 UTC, stevvooe commented
@RenaudWasTaken I agree! Thank you!

2017-06-30 21:17 UTC, RenaudWasTaken commented
@stevvooe once the PR gets accepted in swarmkit should I do a seperate PR to update moby dependencies or should I update the deps in this PR ?

2017-06-30 21:29 UTC, stevvooe commented
@RenaudWasTaken Whatever is easiest for you!

2017-07-16 00:45 UTC, RenaudWasTaken commented
@stevvooe Rebased against master with the latests swarmkit revendoring

2017-07-16 19:19 UTC, cpuguy83 commented
This looks pretty good to me.

The only concern I have is allowing the engine to define the resources (via the info endpoint as it does in in this PR) vs doing it at the node level.
By "concern" here, I mean I'm not sure which is the right approach, not necessarily that I think there's something wrong with it.

2017-07-16 22:09 UTC, RenaudWasTaken commented
> The only concern I have is allowing the engine to define the resources (via the info endpoint as it does in in this PR) vs doing it at the node level.

@cpuguy83 what do you mean by doing at the node level ?

2017-07-18 03:32 UTC, cpuguy83 commented
@RenaudWasTaken Sorry, for "node" level I mean on the swarm node object rather than the engine itself.

2017-07-18 04:49 UTC, RenaudWasTaken commented
@cpuguy83 we discussed that with @aaronlehmann before so I'll be quoting him :)

> The current behavior for the existing resources (NanoCPUs and MemoryBytes) is that they get filled in by Describe (see agent/exec/dockerapi/executor.go for the dockerapi executor implementation). I think we should follow this with generic resources, so that they are consistent with the existing resources, and because it's an easy way to address the hotplug case (Describe is called periodically, and the node is updated dynamically based on the result).
 
and:

> But once this is all integrated in Docker, I think the source of truth should be the SystemInfo call, not information passed through Node.

2017-07-20 19:25 UTC, RenaudWasTaken commented
@cpuguy83 @stevvooe is there anything in this PR that needs to be changed ?

2017-07-24 23:25 UTC, stevvooe commented
LGTM

2017-07-25 00:42 UTC, aaronlehmann commented on daemon/cluster/convert/service.go
> +		} else {
I think this should be `else if res.NamedResourceSpec != nil`. These will be provided by users, and we can't assume that one of the two is non-nil.

2017-07-25 00:50 UTC, RenaudWasTaken commented on daemon/cluster/convert/service.go
> +		} else {
Fixed

2017-07-25 01:01 UTC, aaronlehmann commented
LGTM

2017-07-25 17:48 UTC, RenaudWasTaken commented
CI is now green :)

2017-07-25 19:32 UTC, cpuguy83 approved these changes
LGTM

2017-07-25 19:32 UTC, merged

2017-08-03 22:21 UTC, RenaudWasTaken commented
@aaronlehmann @cpuguy83 what is the process to integrate in the CLI ?
It seems they don't rebase very often should I open an issue ?

2017-08-05 14:30 UTC, cpuguy83 commented
@RenaudWasTaken Rebasing is done as needed. If you have changes that need to go into the CLI that require a bump of moby/moby, you can revendor in 1 commit and make your changes in a 2nd commit.