remove VERSION file
moby/moby pull request #33455
Opened 2017-05-31 18:09 UTC by vieux

removing the `VERSION` file since it doesn't make sense in the Moby context.
Docker CE version and branch management is now done in https://github.com/docker/docker-ce

See https://github.com/docker/docker-ce/blob/master/VERSION and https://github.com/docker/docker-ce/tree/17.06

I decided to go to an hardcoded "dev" version for now.

/cc @tianon @tiborvass @mlaventure @andrewhsu @thaJeztah

2017-05-31 18:14 UTC, thaJeztah commented
LOL, was actually thinking of doing this today; can you also remove https://github.com/moby/moby/blob/master/poule.yml#L38-L42 ?

2017-05-31 18:17 UTC, vieux commented
@thaJeztah PTAL

2017-05-31 18:17 UTC, vdemeester approved these changes
LGTM 👼

2017-05-31 18:20 UTC, thaJeztah requested changes

2017-05-31 18:20 UTC, thaJeztah commented on poule.yml
> -      - type:       version-label
while people still report docker issues, I think we should keep the `version-label`

2017-05-31 18:25 UTC, vieux commented on poule.yml
> -      - type:       version-label
oh I see

2017-05-31 18:26 UTC, vieux commented on poule.yml
> -      - type:       version-label
in the near future, ppl should probably not report issues in moby/moby, but I'll add back for now

2017-05-31 19:01 UTC, thaJeztah approved these changes
LGTM (if green)

next step; we need to decide how to handle API versioning

2017-05-31 19:02 UTC, thaJeztah commented
Windows is failing - halp @johnstep

2017-05-31 21:18 UTC, jhowardmsft commented
Was talking to @vieux on Slack to help, but I'm not sure I like the direction this is heading. Can we not have a moby version? And have docker do what-ever it needs to do to build with a docker version?

2017-05-31 21:24 UTC, vieux commented
I think we're confusing to things, docker != moby therefore the docker version and moby version are different.

The moby version can be found here https://github.com/moby/tool/blob/master/cmd/moby/main.go#L16 (soon to me moved back to moby/moby)

The docker version can be found here https://github.com/docker/docker-ce/blob/master/VERSION

2017-06-01 00:15 UTC, AkihiroSuda commented
CI seems failing

```
23:28:46 =================================== FAILURES ===================================
23:28:46 _________________________ InformationTest.test_version _________________________
23:28:46 /docker-py/tests/integration/api_client_test.py:19: in test_version
23:28:46     self.assertEqual(len(res['Version'].split('.')), 3)
23:28:46 E   AssertionError: 1 != 3
23:28:46 ======== 1 failed, 205 passed, 31 skipped, 2 xfailed in 281.74 seconds =========
```

2017-06-02 01:32 UTC, johnstep commented on hack/make.ps1
> +    if (-not (Test-Path ".\Dockerfile.windows")) { Throw "VERSION file not found. Is this running from the root of a docker repository?" }
Update the message to reference Docker.windows instead of VERSION.

2017-06-02 15:45 UTC, thaJeztah commented
We could leave a VERSION file and put, idk `0.1-dev` in it

2017-06-06 00:49 UTC, vieux commented
@thaJeztah how about just "dev" I don't want to put a number since we have no plans to update it.

2017-06-09 21:27 UTC, thaJeztah commented
@vieux my train of thought was that having 0.01-dev or 0.1-dev would potentially cause less issues with tools/code that's parsing a version string

2017-06-15 19:07 UTC, vieux commented
@moby/moby-maintainers wdyt ? I'm still reluctant to use 0.1

2017-06-15 21:00 UTC, tiborvass commented
I'm in favor for removing

2017-06-15 21:26 UTC, mlaventure commented
![](http://s2.quickmeme.com/img/79/79e78f03d7ef7ea7d55a4cecb10822003e2a94fe8ad0bd6b2cfdfd6592d5d2a2.jpg)

2017-06-15 22:14 UTC, stevvooe commented
Why don't we just remove the version file and use git tags?

2017-06-16 18:07 UTC, mlaventure commented
@vieux I don't think that'd be an issue as those parsing tool are use against docker binaries. Moby not having releases, it shouldn't matter.

2017-06-29 09:00 UTC, AkihiroSuda commented
What's the current status?

2017-06-30 15:22 UTC, vieux commented
@mlaventure @stevvooe keep the file allows for an easy override from the docker-ce and docker-ee packaging.

2017-06-30 15:28 UTC, mlaventure commented
@vieux the version string can be generated by the packing (using the repo own VERSION file), I think versioning should be left to the packaging.

As long as the engine Makefile allows for the ldflags to be augmented so we can override the value found in the `version.go` file, it shouldn't be an issue.

2017-06-30 15:29 UTC, mlaventure commented
@andrewhsu WDYT ^^

2017-07-01 05:59 UTC, andrewhsu commented
The docker/docker-ce repo is overriding the `VERSION` file for building packages for release: https://github.com/docker/docker-ce/pull/80/files

So, as long as there is some way for a user of the moby/moby repo to override the version string output of `docker --version`, I think any change would be acceptable.

2017-07-13 04:44 UTC, AkihiroSuda commented
Note: There is a plan to start the version from 2.0
https://forums.mobyproject.org/t/topic-find-a-good-and-non-confusing-home-for-the-remaining-monolith/37/54

2017-07-22 23:12 UTC, mavenugo commented
I heard few other 👍 to @thaJeztah's [comment](https://github.com/moby/moby/pull/33455#issuecomment-305826110)  to change the VERSION to `0.1-dev`.
cc @mlaventure @tiborvass @cpuguy83 @dnephin can you pls confirm with your suggestion ?

2017-07-26 15:12 UTC, dnephin commented
As I see it there are two topics being discussed here:
1. What is the moby version?
2. How do we document the version?


**What is the moby version?**

I think the version should be 0.1. We've made the statement that this is a new effort, so we should start the versioning from the beginning again. I think v0.1 best reflects the changes that should be coming to this repo. We're talking about completely changing the architecture, splitting out major pieces, etc. 

** How do we document the version**

+1 to the suggestion from @tiborvass , @stevvooe, and @mlaventure to remove the file. I think we can use git tags and pass the version with ldflags

2017-07-26 15:19 UTC, cpuguy83 commented
I agree with removing. Consumers can even use a build flag to set the version if they want something compiled in.

2017-07-26 22:34 UTC, tiborvass commented
@cpuguy83 @dnephin if there are any unknown issues with CIs expecting some version in master, maybe something like `0-dev` or `0.0-dev`. Ideally the default could just be `dev`.

2017-08-01 16:11 UTC, mlaventure commented
@tiborvass CI can always be updated :)

I think it'll be a case of updating `hack/make.sh` and `hack/make.ps1` when they define the `VERSION` variable by reading out the content of the `VERSION` file

2017-08-17 17:55 UTC, dnephin commented
Anything blocking this? Can we proceed with this change?

2017-09-24 11:45 UTC, AkihiroSuda commented
ping @vieux @cpuguy83 @tiborvass @andrewhsu @dnephin

2017-09-26 18:51 UTC, stevvooe commented
Wait, why aren't we removing the file?

We should be using tags for versioning. Let's remove the file and fix up the problems as they come.

2017-11-02 01:32 UTC, AkihiroSuda commented
closing per new pr
 https://github.com/moby/moby/issues/35368

2017-11-02 01:32 UTC, closed without merging