Split pkg/idtools
moby/moby pull request #33482
Opened 2017-06-02 00:30 UTC by vieux

See #32989

Split `"github.com/docker/docker/pkg/idtools` between `github.com/docker/docker/pkg/fsutils1 and `github.com/docker/docker/pkg/system`

2017-06-02 02:57 UTC, dnephin commented
This is going to conflict heavily with #33362. I hope we can merge that first. It's a more involved change. Sorry I should have put that into the tracking issue.

2017-06-02 19:05 UTC, vieux commented
@dnephin ok no worries

2017-06-13 11:07 UTC, thaJeztah commented
ping @vieux - https://github.com/moby/moby/pull/33362 was merged, so this needs an, erm, rebase or rewrite

2017-06-16 01:31 UTC, vieux commented
@dnephin rebased.

2017-06-16 09:35 UTC, thaJeztah approved these changes
LGTM

spotted one typo

2017-06-16 09:35 UTC, thaJeztah commented on pkg/system/utils_unix.go
> +// ResolveBinary resolves a binary path (synlinks and such).
s/synlinks/symlinks/

2017-06-16 19:00 UTC, dnephin requested changes

2017-06-16 19:00 UTC, dnephin commented on pkg/system/utils_unix.go
> +func ExecCmd(cmd, args string) ([]byte, error) {
I don't think we should export this two line helper.

I believe with the suggested split up  this won't need to be exported anymore, as the only consumers will be in `pkg/system/user`

2017-06-16 19:00 UTC, dnephin commented on pkg/fsutils/usergroupadd_linux.go
> +package fsutils
This is the part of the package that I thought would move to `pkg/system`. It doesn't have much to do with files.

This file could move to `pkg/system/user/usergroupadd_linux.go`

2017-06-16 19:00 UTC, dnephin commented on pkg/fsutils/usergroupadd_unsupported.go
> +package fsutils
This file could move to `pkg/system/user/....go`

2017-06-16 19:00 UTC, dnephin commented on pkg/fsutils/idtools_unix.go
> +package fsutils
This file needs to be split up.

`LookupX()` would go to `pkg/system/user/usergroupadd_linux.go`

The file stiff can stay in fsutil

2017-06-16 19:00 UTC, dnephin commented on pkg/fsutils/idtools.go
> +package fsutils
I think some of this file needs to be split up.

All the Mkdir... would be fsutils, but the ID stuff probably makes more sense in system/user/

The file stiff can stay in fsutil

2017-06-16 19:00 UTC, dnephin commented on pkg/system/utils_unix.go
> +func ResolveBinary(binname string) (string, error) {
I believe with the suggested split up  this won't need to be exported anymore, as the only consumers will be in `pkg/system/user`

2017-06-16 23:34 UTC, vieux commented on pkg/system/utils_unix.go
> +func ExecCmd(cmd, args string) ([]byte, error) {
@dnephin so you would move the whole `utils_unix.go` to `pkg/system/user` ?

2017-06-16 23:41 UTC, dnephin commented on pkg/system/utils_unix.go
> +func ExecCmd(cmd, args string) ([]byte, error) {
The file is only these 2 functions, right? so yes I think it would all move to `pkg/system/user`.

2017-06-24 06:55 UTC, thaJeztah commented
ping @vieux this needs a rebase

2017-06-30 15:21 UTC, vieux commented
@thaJeztah yup, @dnephin will carry the PR, assigning to him.

2017-07-20 17:45 UTC, thaJeztah commented
ping @dnephin ^^

2017-07-20 18:25 UTC, dnephin commented
This seems fairly low priority given the new path for the engine. I'm going to close this PR for now. It's still on my list.

2017-07-20 18:25 UTC, closed without merging