Update API docs on image creation
moby/moby pull request #33499
Opened 2017-06-02 19:56 UTC by davidxia

When pulling images, the Docker daemon returns 401
for unauthorized pulls instead of 404.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-06-02 19:56 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-3" git@github.com:davidxia/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-06-03 01:41 UTC, thaJeztah requested changes

2017-06-03 01:41 UTC, thaJeztah commented on api/swagger.yaml
>          404:
This should be `401`?

2017-06-03 01:53 UTC, thaJeztah commented
Actually, is this correct?

Non-existing image:

```bash
$ curl -v -X POST -H 'Content-Type: application/json' 'http://localhost/v1.30/images/create?fromImage=thajeztah/ldkaadslkjdaslkdjasladksjads&tag=latest'

* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST /v1.30/images/create?fromImage=thajeztah/ldkaadslkjdaslkdjasladksjads&tag=latest HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 404 Not Found
< Api-Version: 1.30
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
* Server Docker/17.06.0-dev (linux) is not blacklisted
< Server: Docker/17.06.0-dev (linux)
< Date: Sat, 03 Jun 2017 01:51:29 GMT
< Content-Length: 108
<
{"message":"repository thajeztah/ldkaadslkjdaslkdjasladksjads not found: does not exist or no pull access"}
* Connection #0 to host localhost left intact
```

Private image:

```bash
$ curl -v -X POST -H 'Content-Type: application/json' 'http://localhost/v1.30/images/create?fromImage=thajeztah/private-test-image&tag=latest'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST /v1.30/images/create?fromImage=thajeztah/private-test-image&tag=latest HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 404 Not Found
< Api-Version: 1.30
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
* Server Docker/17.06.0-dev (linux) is not blacklisted
< Server: Docker/17.06.0-dev (linux)
< Date: Sat, 03 Jun 2017 01:52:20 GMT
< Content-Length: 98
<
{"message":"repository thajeztah/private-test-image not found: does not exist or no pull access"}
* Connection #0 to host localhost left intact
```

2017-06-03 14:40 UTC, davidxia commented
Oops sorry. You're right the 401 I saw was coming from the docker registry.

2017-06-03 14:40 UTC, closed without merging