Stop using deprecated SockRequest
moby/moby pull request #33534
Opened 2017-06-06 02:19 UTC by sbko

Signed-off-by: Stanislav Bondarenko <stanislav.bondarenko@gmail.com>

per #31410 

Use `client/` package instead of `request `deprecated functions (`SockRequest`, `SockRequestRaw`). If not viable to use `client/` replace with new `Do`, `Post`, `Get`, ...

**- Description for the changelog**
Use `client/` package in tests instead of deprecated functions SockRequest and SockRequestRaw.

2017-06-06 02:20 UTC, sbko commented
@vdemeester

2017-06-06 07:36 UTC, aaronlehmann commented
There are `gofmt` issues with a few files.

2017-06-06 11:08 UTC, sbko commented
@aaronlehmann should be fixed now

2017-06-06 12:48 UTC, sbko commented
looks like windowsRS1 run out of space.

not sure what to do with:
FAIL: docker_cli_run_test.go:4189: DockerSuite.TestRunStoppedLoggingDriverNoLeak
.... leaked goroutines: expected less than or equal to 1560, got: 1690" ....
using `/client` increased number of goroutines?

2017-06-09 00:04 UTC, thaJeztah commented
Looks like a couple of tests are failing

2017-06-09 00:26 UTC, sbko commented on integration-cli/docker_utils_test.go
>  func getGoroutineNumber() (int, error) {
failing tests are counting  leaked goroutines. I'm not sure what caused that. I changed getGoroutineNumber to use client.Info instead of SockRequest

2017-06-09 00:26 UTC, sbko commented on integration-cli/docker_utils_test.go
>  func getGoroutineNumber() (int, error) {
@thaJeztah

2017-06-09 00:32 UTC, sbko commented
@thaJeztah failing tests are counting leaked goroutines. I'm not sure what caused that, the only change around those tests is that getGoroutineNumber() now uses client.Info() instead of SockRequest call to "/info"

https://github.com/moby/moby/pull/33534/files/971817824022fadaa6e46ffa6853c789e8878254#diff-eb56f180020ddc0ad74fde7b5b8b55fbR404

2017-06-09 01:16 UTC, cpuguy83 commented
@sbko Seems like there is something wrong with the client usage.
800+ goroutines is insanely high.
Maybe we aren't closing out connections somewhere?
At least between the two calls to get the goroutines it's increased.

2017-06-09 01:26 UTC, sbko commented
@cpuguy83 looks like it. I just reverted change to getGoroutineNumber() and tests passed. I tried requests.Get("/info") instead of SockRequests("GET", "/info,..) and it passes tests as well. I will take a look at client library.

2017-06-09 02:42 UTC, sbko commented
Looks like it's client itself. `defer cli.Close()` solves the leak.

2017-06-09 20:39 UTC, sbko commented
@thaJeztah tests are passing now

2017-06-15 03:28 UTC, sbko commented
any changes to api? 

`value *errors.errorString = &errors.errorString{s:"\"secret create\" requires API version 1.25, but the Docker daemon API version is "} ("\"secret create\" requires API version 1.25, but the Docker daemon API version is ")`

2017-06-15 13:23 UTC, thaJeztah commented
I think I know what's happening; version negotiation is currently in the _cli_, not in the API-client, hence it doesn't know what version of the daemon it's talking to.

There's a pull request to update that; https://github.com/moby/moby/pull/32779

2017-06-15 13:24 UTC, thaJeztah commented
But, hm.. if no version was found, it should probably assume "latest" and have the API server return the appropriate error if needed. This is the code that generates the error; https://github.com/moby/moby/blob/69c35dad8e7ec21de32d42b9dd606d3416ae1566/client/errors.go#L228-L235

2017-06-16 01:37 UTC, sbko commented
@thaJeztah do we need to open an issue for that?

2017-06-27 04:23 UTC, thaJeztah commented
@sbko I see that https://github.com/moby/moby/pull/32779 was merged, perhaps it resolves the issue we're seeing here; this does need a rebase though; can you try rebasing, and see if the issue is resolved?

2017-06-27 10:24 UTC, sbko commented
@thaJeztah sure. Thanks!

2017-06-27 16:07 UTC, sbko commented
@thaJeztah I rebased on top of master but it's still failing with same issue.

2017-06-30 05:07 UTC, thaJeztah commented on integration-cli/daemon/daemon.go
> +	cli, err := client.NewClient(d.Sock(), "", httpClient, nil)
The problem is that the client is not initialised with a version, causing the version check to produce an error. There's a couple of solutions;

1. Initialize the client with the default version supported by this client;

```patch
diff --git a/integration-cli/daemon/daemon.go b/integration-cli/daemon/daemon.go
index 6c14136..d4da3d3 100644
--- a/integration-cli/daemon/daemon.go
+++ b/integration-cli/daemon/daemon.go
@@ -14,6 +14,7 @@ import (
        "strings"
        "time"

+       "github.com/docker/docker/api"
        "github.com/docker/docker/api/types/events"
        "github.com/docker/docker/client"
        "github.com/docker/docker/integration-cli/checker"
@@ -761,7 +762,7 @@ func (d *Daemon) ReloadConfig() error {
 // NewClient creates new client based on daemon's socket path
 func (d *Daemon) NewClient() (*client.Client, error) {
        var httpClient *http.Client
-       cli, err := client.NewClient(d.Sock(), "", httpClient, nil)
+       cli, err := client.NewClient(d.Sock(), api.DefaultVersion, httpClient, nil)
        if err != nil {
                return nil, err
        }
```

2. Update the version-check to assume "latest supported version" if no version is set

```patch
diff --git a/client/errors.go b/client/errors.go
index e0effaf..b8905df 100644
--- a/client/errors.go
+++ b/client/errors.go
@@ -3,6 +3,7 @@ package client
 import (
        "fmt"

+       "github.com/docker/docker/api"
        "github.com/docker/docker/api/types/versions"
        "github.com/pkg/errors"
 )
@@ -228,7 +229,11 @@ func IsErrPluginPermissionDenied(err error) bool {
 // NewVersionError returns an error if the APIVersion required
 // if less than the current supported version
 func (cli *Client) NewVersionError(APIrequired, feature string) error {
-       if versions.LessThan(cli.version, APIrequired) {
+       version := cli.version
+       if version == "" {
+               version = api.DefaultVersion
+       }
+       if versions.LessThan(version, APIrequired) {
                return fmt.Errorf("%q requires API version %s, but the Docker daemon API version is %s", feature, APIrequired, cli.version)
        }
        return nil
```

3. Allow version-negotiation if the version that's set for the client is empty

```patch
diff --git a/client/client.go b/client/client.go
index 222aa50..62a3db3 100644
--- a/client/client.go
+++ b/client/client.go
@@ -260,8 +260,13 @@ func (cli *Client) NegotiateAPIVersionPing(p types.Ping) {
                p.APIVersion = "1.24"
        }

-       // if server version is lower than the current cli, downgrade
-       if versions.LessThan(p.APIVersion, cli.ClientVersion()) {
+       // if the client is not initialized with a version, start with the latest supported version
+       if cli.version == "" {
+               cli.version = api.DefaultVersion
+       }
+
+       // if server version is lower than the maximum version supported by the Client, downgrade
+       if versions.LessThan(p.APIVersion, api.DefaultVersion) {
                cli.version = p.APIVersion
        }
 }
```

(3. also would require doing version negotiation after the client is initialised)

I'll open pull requests to discuss 2. and 3., but doing 1. would resolve the test failures

2017-06-30 21:30 UTC, sbko commented on integration-cli/daemon/daemon.go
> +	cli, err := client.NewClient(d.Sock(), "", httpClient, nil)
Done! Added 1.

2017-06-30 21:32 UTC, thaJeztah commented on integration-cli/daemon/daemon.go
> +	cli, err := client.NewClient(d.Sock(), "", httpClient, nil)
Fingers crossed! :smile:

2017-07-01 00:18 UTC, sbko commented
**janky**: 23:48:51 Error response from daemon: No such container: docker-pr44035

2017-07-01 01:09 UTC, thaJeztah commented
restarted

2017-07-01 14:04 UTC, sbko commented
@thaJeztah looks like **janky** is stuck

2017-07-01 21:34 UTC, thaJeztah commented
ugh, restarting again 😞

2017-07-03 15:00 UTC, vdemeester requested changes
Few question, otherwise looks good 👼

2017-07-03 15:00 UTC, vdemeester commented on integration-cli/daemon/daemon_swarm.go
> +	res, dt, err := request.DoOnHost(d.Sock(), "/info", request.Method("GET"))
Why not using `cli.Info` here ? 👼

2017-07-03 15:00 UTC, vdemeester commented on integration-cli/docker_api_info_test.go
> +	res, body, err := request.Get("/v1.20/info")
Same here with a specified version ?

2017-07-03 15:13 UTC, sbko commented on integration-cli/docker_api_info_test.go
> +	res, body, err := request.Get("/v1.20/info")
`ExecutionDriver` isn't in `types.Info` struct so we can't check if it exists if we will use `cli.Info`

https://github.com/sbko/moby/blob/29276d647f5c4e0a1e9fafd62923872292d01fe2/integration-cli/docker_api_info_test.go#L82

2017-07-03 15:19 UTC, vdemeester commented on integration-cli/docker_api_info_test.go
> +	res, body, err := request.Get("/v1.20/info")
oh, I see 👼 🙃

2017-07-03 23:26 UTC, sbko commented on integration-cli/daemon/daemon_swarm.go
> +	res, dt, err := request.DoOnHost(d.Sock(), "/info", request.Method("GET"))
hmm, not sure :) I changed it to use `cli.Info`

2017-07-04 14:57 UTC, dnephin commented on integration-cli/daemon/daemon.go
> +	var httpClient *http.Client
I think this should use `request.NewHTTPClient(d.sock())` for `httpClient`.

2017-07-06 21:50 UTC, sbko commented on integration-cli/daemon/daemon.go
> +	var httpClient *http.Client
@dnephin just so I understand what is the reason for this? if we specify to use d.Sock() in client.NewClient anyway(line 765). I tried it and it works but I don't see a difference

2017-07-07 14:39 UTC, dnephin commented on integration-cli/daemon/daemon.go
> +	var httpClient *http.Client
`NewHTTPClient()` sets up the transport to be more similar to what we have in the client.

We also might add more to that method, and we shouldn't have two ways to create an httpClient in tests.

2017-07-07 17:54 UTC, sbko commented
Do I need to keep rebasing it or wait for reviews?

2017-07-07 23:30 UTC, thaJeztah commented
I wasn't sure if you updated with @dnephin's comment https://github.com/moby/moby/pull/33534#discussion_r126163046

2017-07-07 23:31 UTC, thaJeztah commented
also ping @vdemeester PTAL

2017-07-08 03:01 UTC, sbko commented on integration-cli/daemon/daemon.go
> +	var httpClient *http.Client
I made the change

2017-07-08 03:02 UTC, sbko commented
@thaJeztah  I made the change :)

2017-07-12 16:29 UTC, sbko commented on integration-cli/daemon/daemon_swarm.go
> +	res, dt, err := request.DoOnHost(d.Sock(), "/info", request.Method("GET"))
@vdemeester PTAL :)

2017-07-31 17:12 UTC, sbko commented
@vdemeester do I keep rebasing or wait for reviews?

2017-07-31 19:35 UTC, sbko commented
@vdemeester PTAL. do I need to keep rebasing or wait for reviews first?

2017-08-01 09:06 UTC, vdemeester approved these changes
SGTM 🐸
@sbko You can rebase 😉

2017-08-01 17:18 UTC, sbko commented
@vdemeester done! :)

2017-08-09 19:12 UTC, sbko commented
@thaJeztah what should be my next step? just wait?

2017-08-14 14:19 UTC, thaJeztah approved these changes
LGTM (sorry for the delay)

ping @dnephin can you have another look as well?

I see it needs a minor rebase

2017-08-14 16:10 UTC, dnephin reviewed
This PR is quite large. I did another quick scan, and it generally seems fine, but I didn't really look at every change.

In the future doing multiple smaller PRs will make it much easier to review, and should reduce the time it takes to get it merged.

Couple minor comments, but nothing blocking a merge.

2017-08-15 11:26 UTC, sbko commented on integration-cli/daemon/daemon.go
> +	if err != nil {
done

2017-08-15 11:26 UTC, sbko commented on integration-cli/daemon/daemon_swarm.go
> +	cli, err := d.NewClient()
ok

2017-08-15 19:21 UTC, thaJeztah commented
I think there was an issue with Docker Hub search causing these failures; restarting CI

2017-08-15 20:08 UTC, sbko commented
@thaJeztah looks like still failing:
`19:46:48 FAIL: docker_api_containers_test.go:1584: DockerSuite.TestContainerAPIDeleteWithEmptyName
19:46:48 
19:46:48 docker_api_containers_test.go:1590:
19:46:48     c.Assert(err.Error(), checker.Contains, "No container name or ID supplied")
19:46:48 ... obtained string = "Error response from daemon: page not found"
19:46:48 ... substring string = "No container name or ID supplied"`

`20:02:21 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
20:02:21 
20:02:21 docker_cli_search_test.go:72:
20:02:21     c.Assert(outSearchCmdOfficialSlice, checker.HasLen, 3) // 1 header, 1 line, 1 carriage return
20:02:21 ... obtained []string = []string{"NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED", ""}
20:02:21 ... n int = 3`

2017-08-16 14:35 UTC, thaJeztah commented
@sbko yes, I chatted with the Hub team yesterday, and the cause was that the search index was out of date, causing the `busybox` image (which is used in that test) not being returned in the first X search results.

They triggered a re-index, and it should now (really) be fixed; triggering once more 😅

2017-08-22 14:43 UTC, vdemeester commented
arf @sbko needs rebasing 😓 
/cc @dnephin can you help ? 👼

2017-08-22 14:49 UTC, sbko commented
@vdemeester I was busy last week. I will probably rebase tonight or tomorrow.

2017-08-23 10:24 UTC, sbko commented
@vdemeester @dnephin rebased

2017-08-23 14:33 UTC, dnephin requested changes
This might be easier to get in (faster reveiws and fewer rebases) if it were split into smaller chunks. +/- 300 lines is significantly easier to review than +/-1500.

2017-08-23 14:33 UTC, dnephin commented on integration-cli/docker_api_create_test.go
> +func (s *DockerSuite) TestAPICreateWithNotExistImage(c *check.C) {
This looks like a bad merge. These tests were removed in #34000

2017-08-23 14:33 UTC, dnephin commented on integration-cli/environment/clean.go
> +func getAllPlugins(c *client.Client) (types.PluginsListResponse, error) {
I think this should be using `client.APIClient` (the interface), same is true in other places.

2017-08-23 14:33 UTC, dnephin commented on integration-cli/environment/clean.go
> +	}
`require.NoError(t, err)`

2017-08-23 14:33 UTC, dnephin commented on integration-cli/daemon/daemon.go
> +	if err != nil {
I still see the if here

2017-08-23 20:52 UTC, sbko commented on integration-cli/docker_api_create_test.go
> +func (s *DockerSuite) TestAPICreateWithNotExistImage(c *check.C) {
Done

2017-08-23 20:53 UTC, sbko commented on integration-cli/environment/clean.go
> +func getAllPlugins(c *client.Client) (types.PluginsListResponse, error) {
Done

2017-08-23 21:13 UTC, sbko commented
made changes per @dnephin review and rebased again :)
@dnephin my next pull request will be smaller ;)

2017-08-24 15:29 UTC, dnephin approved these changes

2017-08-24 15:30 UTC, merged