Moby Dev Report 2017 06 05
moby/moby pull request #33547
Opened 2017-06-06 17:55 UTC by vieux

ping @tonistiigi @tiborvass @thaJeztah

2017-06-06 18:18 UTC, AkihiroSuda reviewed
6-5 seems a dupe of 5-29

2017-06-06 18:18 UTC, AkihiroSuda commented on reports/2017-06-05.md
> +Ee are discussing the future of this meeting [here](https://forums.mobyproject.org/t/of-standups-future), we will possibily move the meeting
s/Ee/We

2017-06-06 18:22 UTC, AkihiroSuda commented on reports/2017-06-05.md
> +The LinuxKit dev report can be found [here](https://github.com/linuxkit/linuxkit/blob/master/reports/2017-06-03.md_
Extra underscore

2017-06-06 18:29 UTC, thaJeztah requested changes
Left some comments, but LGTM otherwise

2017-06-06 18:29 UTC, thaJeztah commented on reports/2017-06-05.md
> +Ee are discussing the future of this meeting [here](https://forums.mobyproject.org/t/of-standups-future), we will possibily move the meeting
s/Ee/We/

2017-06-06 18:29 UTC, thaJeztah commented on reports/builder/2017-06-05.md
> +### `v17.06` release
This is not related to moby? Or should be "discovered downstream in Docker 17.06"

2017-06-07 01:54 UTC, tiborvass commented
LGTM

2017-06-07 01:55 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "report-2017-06-05" git@github.com:vieux/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354480304
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-06-07 01:56 UTC, merged