Mention that USER directive also allows to specify the user group
moby/moby pull request #33573
Opened 2017-06-07 17:06 UTC by php-coder

When `USER 1000` is specified in the `Dockerfile`, the resulted image will be run with an UID=1000 and GID=0 (root):
```sh
$ docker build -t test-uid .
Sending build context to Docker daemon 13.82 kB
Step 1/2 : FROM centos:latest
 ---> 3bee3060bfc8
Step 2/2 : USER 1000
 ---> Running in 18b73f17a670
 ---> eef2fb2ad150
Removing intermediate container 18b73f17a670
Successfully built eef2fb2ad150
$ docker run --rm -it test-uid id
uid=1000 gid=0(root) groups=0(root)
```

Such behavior is unexpected (and also insecure) and it's possible to set a GID explicitly by using `USER uid:gid` syntax:
```sh
$ docker build -t test-uid .
Sending build context to Docker daemon 13.82 kB
Step 1/2 : FROM centos:latest
 ---> 3bee3060bfc8
Step 2/2 : USER 1000:1000
 ---> Running in b8c31413f969
 ---> dc0154009df7
Removing intermediate container b8c31413f969
Successfully built dc0154009df7
$ docker run --rm -it test-uid id
uid=1000 gid=1000 groups=1000
```

But this syntax is undocumented and many developers (including me until today) don't know about it.

**- What I did**
I've updated documentation to reflect the current state.

**- Description for the changelog**
Document that the `USER` directive also allows to specify the user group

**- A picture of a cute animal (not mandatory but encouraged)**
🐈 

Thanks to @dmage and @legionus for opening my eyes on that.
CC @mfojtik

2017-06-13 13:07 UTC, thaJeztah requested changes
Thanks @php-coder - I left some comments

2017-06-13 13:07 UTC, thaJeztah commented on docs/reference/builder.md
> +> instructions) will be running with the `root` group.
Perhaps we should be more explicit, something like;

```markdown
> **Warning**:
> IF `USER` is used without specifying a `group` or `GID`, the group is 
> reset, and the default group (`0` - `root`) is used.
```

Steps to check this behavior;

```bash
$ docker build -<<EOF
FROM busybox
RUN id
USER 123:456
RUN id
USER 789
RUN id
EOF
```

Which will show;

```
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM busybox
 ---> 00f017a8c2a6
Step 2/6 : RUN id
 ---> Running in 1e541467e8a4
uid=0(root) gid=0(root) groups=10(wheel)
 ---> f683b31c30a0
Removing intermediate container 1e541467e8a4
Step 3/6 : USER 123:456
 ---> Running in 20124639421b
 ---> ebcd2f31886f
Removing intermediate container 20124639421b
Step 4/6 : RUN id
 ---> Running in 36079bff5338
uid=123 gid=456
 ---> fa3b4d02cd7f
Removing intermediate container 36079bff5338
Step 5/6 : USER 789
 ---> Running in f54165b19c52
 ---> c4209b5a44fb
Removing intermediate container f54165b19c52
Step 6/6 : RUN id
 ---> Running in 30ae2b70c550
uid=789 gid=0(root)
 ---> b39cfbb318c3
Removing intermediate container 30ae2b70c550
Successfully built b39cfbb318c3
```

So;

- by default, both `uid` and `gid` are `0` (`root`)
- if both `uid` and `gid` are provided, `uid:gid` is used
- if only `uid` is provided, `gid` is reset to the default (`0` - `root`)


This is different than, e.g. `sudo -u`, which preserves the current `gid`;

```bash
$ sudo -u \#123 id
uid=123 gid=20(staff) groups=20(staff),4294967295(nogroup)
```

2017-06-13 13:07 UTC, thaJeztah commented on docs/reference/builder.md
> +> instructions) will be running with the `root` group.
Wondering actually, if that was by design, or a "bug" (i.e.; should `gid` be reset if not specified)

2017-06-14 13:42 UTC, php-coder commented on docs/reference/builder.md
> +    USER daemon[:wheel]
Done.

2017-06-14 13:44 UTC, php-coder commented on docs/reference/builder.md
> +> instructions) will be running with the `root` group.
> if only uid is provided, gid is reset to the default (0 - root)

It turns out that it happens not always but only in the case when user with provided uid doesn't have a primary group (4th field in the `/etc/passwd`/ file).

I've updated message. PTAL.

2017-06-14 13:52 UTC, php-coder commented
Because the documentation have been moved to another repository, I'm closing this PR and will open a new one.

2017-06-14 13:52 UTC, closed without merging