Increased test Coverage of pkg/chrootarchive
moby/moby pull request #33657
Opened 2017-06-13 13:53 UTC by raja-sami-10p

Signed-off-by: Raja Sami <raja.sami@tenpearls.com>

**- What I did**
Increased unit test coverage of pkg/chrootarchive

**- How to verify it**
```sh
make test-unit
```

**- A picture of a cute animal (not mandatory but encouraged)**
:bird:

2017-06-13 17:56 UTC, vieux commented
LGTM

2017-06-13 20:11 UTC, thaJeztah requested changes
Left some questions

2017-06-13 20:11 UTC, thaJeztah commented on pkg/chrootarchive/archive_test.go
> +	err = UntarUncompressed(nil, destination, &archive.TarOptions{ExcludePatterns: []string{"testuncompresss"}})
Although it doesn't really _hurt_, all the exclusion patterns seem to be covered already by other tests (the only different between `UntarUncompressed` and `Untar` is this bit https://github.com/moby/moby/blob/93fbdb69acf9248283a91a1c5c6ea24711c26eda/pkg/chrootarchive/archive.go#L60-L67, of which only the error-case seems to be not covered.

2017-06-13 20:11 UTC, thaJeztah commented on pkg/chrootarchive/archive_test.go
> +	stream, err = archive.Tar(destination, archive.Uncompressed)
What is being tested here? `archive.Tar()`, `archive.DecompressStream()` are all part of [`pkg/archive`](https://github.com/moby/moby/blob/93fbdb69acf9248283a91a1c5c6ea24711c26eda/pkg/archive/archive.go)?

2017-06-13 20:11 UTC, thaJeztah commented on pkg/chrootarchive/archive_test.go
> +	stream, err = archive.Tar(destination, archive.Uncompressed)
Same here; I don't see what's being tested here. Actually, this looks like an exact copy of what's in `TestUnTarUncompressed` above

2017-06-16 13:35 UTC, cpuguy83 commented
I don't think this test is valid, and surprised that it didn't break the rest of the test suite.
If we want to test this function it needs to be done via re-exec, and will be pretty hard to test.

2017-06-19 10:58 UTC, raja-sami-10p commented
@cpuguy83, can you please help me understand how this test should have broken the rest of the test suites?

2017-06-19 11:47 UTC, cpuguy83 commented
@raja-sami-10p Because the function being tested is creating a new mount namespace, and then doing a pivot_root to an empty directory.

2017-06-21 22:45 UTC, aaronlehmann commented
Since it sounds like this test is invalid, should we close the PR?

2017-06-21 22:48 UTC, cpuguy83 commented
Yes, let's close this one.

Thanks all!

2017-06-21 22:48 UTC, closed without merging