Increase the Coverage of pkg/streamformatter
moby/moby pull request #33653
Opened 2017-06-13 10:43 UTC by raja-sami-10p

Signed-off-by: Raja Sami <raja.sami@tenpearls.com>

**- What I did**
Increase test coverage of pkg/streamformatter

**- How to verify it**
```sh
make test-unit
```

**- A picture of a cute animal (not mandatory but encouraged)**
:panda_face:

2017-06-16 13:43 UTC, cpuguy83 requested changes
Just a minor nit, but LGTM

2017-06-16 13:43 UTC, cpuguy83 commented on pkg/streamformatter/streamformatter_test.go
> +	// The jsonProgress will always be in the format of:
Nit:
Either `The progress will...` 
Or just `jsonProgress will...`

2017-06-16 16:45 UTC, aaronlehmann commented on pkg/streamformatter/streamformatter_test.go
> +	assert.Equal(t, fmt.Sprintf("{\"status\":\"a1\",\"id\":\"ID\"}%s", streamNewline), string(res))
Can you please use the `+` operator to merge the strings instead of `Sprintf`?

2017-06-16 16:45 UTC, aaronlehmann commented on pkg/streamformatter/streamformatter_test.go
> +	assert.Equal(t, fmt.Sprintf("{\"status\":\"Downloading\",\"progressDetail\":{},\"id\":\"id\"}%s", streamNewline), b.String())
Can you please use the `+` operator to merge the strings instead of `Sprintf`?

2017-06-16 16:45 UTC, aaronlehmann commented on pkg/streamformatter/streamformatter_test.go
> +	assert.Equal(t, fmt.Sprintf(`{"aux":{"Data":"Additional data"}}%s`, streamNewline), b.String())
Can you please use the `+` operator to merge the strings instead of `Sprintf`?

2017-06-19 11:06 UTC, raja-sami-10p commented on pkg/streamformatter/streamformatter_test.go
> +	// The jsonProgress will always be in the format of:
Okay

2017-06-19 11:06 UTC, raja-sami-10p commented on pkg/streamformatter/streamformatter_test.go
> +	assert.Equal(t, fmt.Sprintf("{\"status\":\"a1\",\"id\":\"ID\"}%s", streamNewline), string(res))
Done

2017-06-19 20:56 UTC, vieux commented
ping @aaronlehmann @cpuguy83

2017-06-19 20:57 UTC, vieux commented
LGTM

2017-06-19 21:28 UTC, aaronlehmann commented on pkg/streamformatter/streamformatter_test.go
> +	assert.Equal(t, "{\"status\":\"a1\",\"id\":\"ID\"}"+streamNewline, string(res))
Can you please use backticks here for readability?

2017-06-19 21:28 UTC, aaronlehmann commented on pkg/streamformatter/streamformatter_test.go
> +func TestNewJSONProgressOutput(t *testing.T) {
This function is named `TestNewJSONProgressOutput`, but it isn't really testing `NewJSONProgressOutput`. `NewJSONProgressOutput` just returns a struct. IMHO it's testing `WriteProgress`.

2017-06-22 07:27 UTC, raja-sami-10p commented on pkg/streamformatter/streamformatter_test.go
> +	assert.Equal(t, "{\"status\":\"a1\",\"id\":\"ID\"}"+streamNewline, string(res))
Sure

2017-06-22 07:28 UTC, raja-sami-10p commented on pkg/streamformatter/streamformatter_test.go
> +func TestNewJSONProgressOutput(t *testing.T) {
I've tweaked the test a little bit.

2017-06-22 16:35 UTC, aaronlehmann commented
LGTM

2017-06-22 17:58 UTC, cpuguy83 approved these changes
LGTM pending windows CI.

2017-06-23 00:42 UTC, thaJeztah commented
```
21:33:29 ----------------------------------------------------------------------
21:33:29 FAIL: check_test.go:97: DockerSuite.TearDownTest
21:33:29 
21:33:29 check_test.go:98:
21:33:29     testEnv.Clean(c, dockerBinary)
21:33:29 environment/clean.go:63:
21:33:29     t.Fatalf("error removing containers %v : %v (%s)", containers, result.Error, result.Combined())
21:33:29 ... Error: error removing containers [07d52da96817] : exit status 1 (Error response from daemon: removal of container 07d52da96817 is already in progress
21:33:29 )
21:33:29 
21:33:29 
21:33:29 ----------------------------------------------------------------------
21:33:29 PANIC: docker_cli_restart_test.go:296: DockerSuite.TestRestartAutoRemoveContainer
21:33:29 
21:33:29 ... Panic: Fixture has panicked (see related PANIC)
```

2017-06-23 01:51 UTC, thaJeztah commented
argh, funky node?

```
00:44:31 fatal: unable to access 'https://github.com/docker/cli/': Couldn't resolve host 'github.com'
00:44:31 
00:44:31 ERROR: make.ps1 failed:
00:44:31 Failed to clone client repository https://github.com/docker/cli
```

2017-06-23 02:52 UTC, merged