Increase test Coverage of pkg/templates
moby/moby pull request #33674
Opened 2017-06-14 11:55 UTC by raja-sami-10p

Signed-off-by: Raja Sami <raja.sami@tenpearls.com>

**- What I did**
Increase unit test coverage of pkg/templates

**- How to verify it**
```sh
make test-unit
```

**- A picture of a cute animal (not mandatory but encouraged)**
:horse:

2017-06-20 21:35 UTC, cpuguy83 requested changes

2017-06-20 21:35 UTC, cpuguy83 commented on pkg/templates/templates_test.go
> +		t.Run("Empty Source Test with template: "+testCase.template, func(t *testing.T) {
Can we either convert the test above this to use the `t.Run` pattern or continue to use the already established pattern in this test?

2017-06-22 07:44 UTC, raja-sami-10p commented on pkg/templates/templates_test.go
> +		t.Run("Empty Source Test with template: "+testCase.template, func(t *testing.T) {
I've changed it to t.Run pattern.

2017-06-22 13:05 UTC, cpuguy83 approved these changes
LGTM

2017-06-24 07:00 UTC, thaJeztah commented
windows failing on https://github.com/moby/moby/issues/33805, which is a known flaky test

2017-06-24 07:01 UTC, thaJeztah approved these changes
LGTM

2017-06-24 08:04 UTC, merged