fd leak and error hanlding
moby/moby pull request #33713
Opened 2017-06-16 04:02 UTC by x1022as

Signed-off-by: Deng Guangxing <dengguangxing@huawei.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-06-16 12:51 UTC, cpuguy83 requested changes

2017-06-16 12:51 UTC, cpuguy83 commented on pkg/discovery/generator.go
> +	re, err := regexp.Compile(`\[(.+):(.+)\]`)
I feel like this should be run at package init.

2017-06-19 04:13 UTC, x1022as commented on pkg/discovery/generator.go
> +	re, err := regexp.Compile(`\[(.+):(.+)\]`)
@cpuguy83  Can you explain explicitly? I'm afraid I did't get your point of package init :(

2017-06-19 11:57 UTC, cpuguy83 commented on pkg/discovery/generator.go
> +	re, err := regexp.Compile(`\[(.+):(.+)\]`)
@x1022as Because this is effectively a package level constant.

2017-06-20 21:57 UTC, cpuguy83 approved these changes
LGTM

2017-06-21 22:48 UTC, aaronlehmann commented on daemon/logger/jsonfilelog/multireader/multireader.go
>  				rdr.Seek(0, os.SEEK_SET)
Does this one need an error check as well?

2017-06-22 01:05 UTC, x1022as commented on daemon/logger/jsonfilelog/multireader/multireader.go
>  				rdr.Seek(0, os.SEEK_SET)
I think errors should be ignored and continue the for loop, so maybe  no need to check here.

2017-06-23 07:35 UTC, x1022as commented
janky failed seems not related.  will push again to re-run it.

2017-06-29 07:05 UTC, thaJeztah commented
ping @aaronlehmann PTAL

2017-06-29 20:31 UTC, aaronlehmann commented on daemon/logger/jsonfilelog/multireader/multireader.go
> +		if _, err := r.Seek(tmpOffset+offset, os.SEEK_SET); err != nil {
Rather than calling `Seek` recursively here, which seems to do a lot of redundant work, couldn't we just set `r.pos` directly?

2017-07-04 13:48 UTC, vieux commented on daemon/logger/jsonfilelog/multireader/multireader.go
> +		if _, err := r.Seek(tmpOffset+offset, os.SEEK_SET); err != nil {
ping @x1022as

2017-07-05 06:07 UTC, thaJeztah commented on daemon/logger/jsonfilelog/multireader/multireader.go
> +		if _, err := r.Seek(tmpOffset+offset, os.SEEK_SET); err != nil {
@aaronlehmann @vieux if this is an important fix, and we want it to be in 17.07, perhaps we should carry to make sure it gets merged in time

2017-07-06 16:55 UTC, aaronlehmann commented
This LGTM as-is, however I suggested a simplification for the existing code. The simplification could happen in a separate PR.

2017-07-06 23:47 UTC, merged