Fix mem leak in libcontainerd/queue/append
moby/moby pull request #33764
Opened 2017-06-21 08:39 UTC by keloyang

For every container,  queue' append interface add a element to q.fns,and it will never be remove.
this pr will  fix it ,and with the follown code ,we can see the approach.
```
package main

import (
	"fmt"
	"os/exec"
	"time"
	"runtime/debug"
	"crypto/rand"
)

//copy code from libcontainerd/queue_unix.go
typedef queue{
	...
}

func (q *queue) append(id string, f func()) {
    ...
}

func randID(n int) string{
    b := make([]byte, n)
    if _, err := rand.Read(b); err != nil {
        return "369027c8aaa7b671214abfda8a3ac34b434f27c0bb33d35c4c25b9468bc1fc43"
    }
    return fmt.Sprintf("%x", b)
}

func main(){
	const (
		NUM = 1000000
	)
	var (
	
		q queue
		count = 0	
	)
	for i:= 0; i< NUM; i++{
		q.Append(randID(32), func(){
			count++
		})
	}
	for done:= false; done != false; {
		select {
			case <-time.After(time.Millisecond):
				if count == NUM{
					done = true
			}
		}
	}
	debug.FreeOSMemory()
	
	argv := []string{"-c", "smem|grep queue",}
	c := exec.Command("/bin/bash", argv...)
	d, _ := c.Output()
	fmt.Println(string(d)) 	
}
```
### Before this pr,
![1](https://user-images.githubusercontent.com/11223367/27374877-f4d5e5b6-569f-11e7-9d74-3a418e4f4a1d.JPG)

### After this pr,
![2](https://user-images.githubusercontent.com/11223367/27374896-0120dd30-56a0-11e7-995c-584ab4f47b0a.JPG)

Signed-off-by: yangshukui <yangshukui@huawei.com>

2017-06-21 20:34 UTC, aaronlehmann commented
This seems reasonable, but I'm wondering if a simpler solution would be to add something like this to the end of the goroutine:

```
q.Lock()
if q.fns[id] == done {
        delete(q.fns, done)
}
q.Unlock()
```

Since the goroutines wait for each other and run in sequential order, this `delete` should be reached if and only if nothing else has been waiting for the particular goroutine to finish.

2017-06-22 03:51 UTC, keloyang commented
Thanks for  your review, I think your  code is better and it  will work also.

2017-06-22 03:57 UTC, cpuguy83 approved these changes
LGTM

2017-06-22 04:03 UTC, thaJeztah commented on libcontainerd/queue_unix_test.go
> +		if serialization != 1 {
Perhaps good to use testify for these (like in https://github.com/moby/moby/blob/16380b3ee68c0da2fda036d7980129241957220c/pkg/promise/promise_test.go#L7-L13)

2017-06-22 05:56 UTC, keloyang commented on libcontainerd/queue_unix_test.go
> +		if serialization != 1 {
@thaJeztah thanks  for your advice , the code has been changed.

2017-06-22 07:39 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-06-22 07:44 UTC, thaJeztah requested changes

2017-06-22 07:44 UTC, thaJeztah commented on libcontainerd/queue_unix_test.go
> +package libcontainerd
Oops; build on Windows is failing;

```
06:03:49 # github.com/docker/docker/libcontainerd
06:03:49 libcontainerd\queue_unix_test.go:12: undefined: queue
```

This file also needs the same build tags as `queue_unix.go`;

```go
// +build linux solaris
```

2017-06-22 08:33 UTC, keloyang commented on libcontainerd/queue_unix_test.go
> +package libcontainerd
@thaJeztah Sorry, I made a mistake, I think queue_unix.go has no build tag,so queue_unix_test.go don't need it also. Updated , thank you.

2017-06-22 09:09 UTC, thaJeztah approved these changes
thanks!

LGTM (if green 😅 )

2017-06-22 17:57 UTC, thaJeztah commented
All green now! merging

thanks @keloyang !

2017-06-22 17:57 UTC, merged