LCOW: Fix nits from 33241
moby/moby pull request #33826
Opened 2017-06-26 16:13 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Fixes most of the feedback 'nits' comments from @johnstep in #33241

2017-06-26 18:41 UTC, johnstep approved these changes
LGTM

2017-06-27 01:53 UTC, johnstep commented on api/server/backend/build/tag.go
> +		if system.LCOWSupported() {
What about the other instances of this redundant (`platform == "windows"`) check?

2017-06-27 03:47 UTC, thaJeztah requested changes
left one nit, but looks good otherwise

2017-06-27 03:47 UTC, thaJeztah commented on builder/dockerfile/parser/parser.go
> +	directive.setPlatformToken(DefaultPlatformToken)
I noticed `DefaultPlatformToken` is only used in this file; can you un-export it?

2017-06-27 04:33 UTC, jhowardmsft commented on builder/dockerfile/parser/parser.go
> +	directive.setPlatformToken(DefaultPlatformToken)
Yup, fixed. Push coming shortly.

2017-06-27 04:53 UTC, jhowardmsft commented on api/server/backend/build/tag.go
> +		if system.LCOWSupported() {
As mentioned on slack, it's a little moot as I'm actively working to remove all these markers anyway. But done. Push imminent.

2017-06-27 04:53 UTC, jhowardmsft commented
Comments addressed.

2017-06-27 05:58 UTC, thaJeztah approved these changes
LGTM

ping @johnstep PTAL

2017-06-27 06:10 UTC, johnstep approved these changes
LGTM

2017-06-27 07:32 UTC, vdemeester approved these changes
LGTM 👼

2017-06-27 14:23 UTC, cpuguy83 commented
Failures look legit.

2017-06-27 14:37 UTC, jhowardmsft commented
@cpuguy83 yup, they do. Investigating

2017-06-27 19:00 UTC, jhowardmsft commented
I see it. Should be fixed in latest push.

2017-06-28 03:24 UTC, jhowardmsft commented
Experimental failure (just locked up and about to timeout) is unrelated. Restarting for the 3rd time.

2017-06-28 05:54 UTC, jhowardmsft commented
Green 💚 . Finally. (All sorts of CI infrastructure issues on multiple contexts the past few days)

2017-06-28 05:56 UTC, merged