Fix log readers can block writes indefinitely
moby/moby pull request #33897
Opened 2017-06-30 17:22 UTC by cpuguy83

Before this patch, a log reader is able to block all log writes
indefinitely (and other operations) by simply opening the log stream and
not consuming all the messages.

The reason for this is we protect the read stream from corruption by
ensuring there are no new writes while the log stream is consumed (and
caught up with the live entries).

We can get around this issue because log files are append only, so we
can limit reads to only the section of the file that was written to when
the log stream was first requested.

Now logs are only blocked until all files are opened, rather than
streamed to the client.

2017-06-30 22:10 UTC, mlaventure requested changes

2017-06-30 22:10 UTC, mlaventure commented on daemon/logger/jsonfilelog/read.go
> +	latestChunk, err := newSectionReader(latestFile)
you need to seek to this value on line 108, otherwise we may miss some data.

2017-06-30 22:42 UTC, cpuguy83 commented on daemon/logger/jsonfilelog/read.go
> +	latestChunk, err := newSectionReader(latestFile)
We are seeking in "newSectionReader"

2017-07-01 20:20 UTC, mlaventure commented on daemon/logger/jsonfilelog/read.go
> +	latestChunk, err := newSectionReader(latestFile)
It is initially yes, but then the lock is released on line 84, and if we were asked to tail and follow, then on line 108, we do another `SEEK_END`, shouldn't that one be a `SEEK_SET` to `latestChunk`?

2017-07-03 19:52 UTC, cpuguy83 commented on daemon/logger/jsonfilelog/read.go
> +	latestChunk, err := newSectionReader(latestFile)
Ok, I fixed this. You're right, I left an extra seek in there.

2017-07-04 01:37 UTC, thaJeztah commented
ping @mlaventure @tonistiigi PTAL

2017-07-04 06:43 UTC, mlaventure approved these changes
LGTM

2017-07-04 13:42 UTC, vieux commented
LGTM ping @tonistiigi

2017-07-05 17:57 UTC, tonistiigi reviewed
Not too familiar with this code but apart from one typo SGTM

2017-07-05 17:57 UTC, tonistiigi commented on daemon/logger/jsonfilelog/jsonfilelog.go
> +		errors.Wrap(err, "error writing log entry")
return

2017-07-05 22:30 UTC, thaJeztah commented
```
18:07:25 INFO: Base image for tests is microsoft/windowsservercore
18:07:25 INFO: Loading windowsservercore .tar from disk into the daemon under test. This may take some time...
18:08:48 re-exec error: exit status 1: output: BackupWrite \\?\D:\CI\CI-bf11b0b0d\daemon\windowsfilter\39a6fda2dfcc44cdb21c59f8d90690bc5798b5b6db5e6c050ae82f80890d27c2\Files\Windows\IME\IMETC\DICTS\IMTCT.IMD: There is not enough space on the disk.
18:08:48 
18:08:48 
```

2017-07-06 01:21 UTC, thaJeztah commented
All green! Merging

2017-07-06 01:21 UTC, merged