return prune data when context canceled
moby/moby pull request #33979
Opened 2017-07-06 08:54 UTC by allencloud

Signed-off-by: allencloud <allen.sun@daocloud.io>

This PR takes into user's cancel request when prune data into consideration. When context is canceled, docker daemon still returns the data which is already pruned. 

Prune Object includes: container, network, image, volume, and build cache.

**- What I did**
1. make engine return prune data even if context is canceled.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-07-06 09:24 UTC, mlaventure requested changes

2017-07-06 09:24 UTC, mlaventure commented on daemon/prune.go
> +			return nil, nil
This one can stay as before as nothing was altered yet.

2017-07-06 09:53 UTC, allencloud commented on daemon/prune.go
> +			return nil, nil
Oh, thanks. Updated now.

2017-07-06 12:26 UTC, mlaventure approved these changes
LGTM

2017-07-06 16:22 UTC, cpuguy83 requested changes

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +	if err == errPruneCancelled {
Do we need this new error?
Why not `if err == context.Cancelled`?

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +	errPruneCancelled = fmt.Errorf("a prune operation is cancelled")
I don't think think we need to add this new error here, but in any case the wording is a bit funky.
Maybe `the prune operation was cancelled`

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +			return errPruneCancelled
I don't think it's right to return a cancelled error here since cancellation is just one reason why the context would be done.

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +	if err == errPruneCancelled {
This could also check `context.DeadlineExceeded`

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +			// when the context is cancelled, only return the report struct as presently
This sentence doesn't look complete.

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +			// when the context is cancelled, only return the report struct as presently
This sentence doesn't look complete.

2017-07-06 16:22 UTC, cpuguy83 commented on daemon/prune.go
> +		// when the context is cancelled, only return the report struct as presently
This sentence doesn't look complete.

2017-07-07 02:51 UTC, allencloud commented on daemon/prune.go
> +	if err == errPruneCancelled {
Thanks for your feedback. @cpuguy83 
Currently I have updated the PR and only checked `err == context.Cancelled`. And if we also check context.DeadlineExceeded, what should we return, a report with nil, or a report with error?

2017-07-07 20:58 UTC, cpuguy83 requested changes

2017-07-07 20:58 UTC, cpuguy83 commented on builder/fscache/fscache.go
> +			logrus.Warnf("Cache prune operation cancelled, pruned size: %d", size)
Can be a debug

2017-07-07 20:58 UTC, cpuguy83 commented on builder/fscache/fscache.go
> +			logrus.Warnf("Cache prune operation cancelled, pruned size: %d", size)
I see others are warnings as well...

2017-07-07 20:58 UTC, cpuguy83 commented on daemon/prune.go
> +		// when the context is cancelled, return current report struct and nil
This is obvious from the return line, I don't think we need the comment explaining

2017-07-07 20:58 UTC, cpuguy83 commented on daemon/prune.go
> +			// when the context is cancelled, return current report struct and nil
This is obvious from the return line, I don't think we need the comment explaining

2017-07-09 01:24 UTC, allencloud commented
Thanks for your review again. @cpuguy83 
I have updated that, PTAL.

2017-07-10 00:40 UTC, thaJeztah requested changes
Left some questions / comments, thanks!

2017-07-10 00:40 UTC, thaJeztah commented on daemon/prune.go
>  	return rep, err
this is now returning a different error than before, because the `err = daemon.traverseLocalVolumes()` is now moved inside the `if ...`

2017-07-10 00:40 UTC, thaJeztah commented on daemon/prune.go
> +		return rep, nil
related to my comment two lines below; this doesn't return if `err == nil`,  correct?

2017-07-10 00:40 UTC, thaJeztah commented on daemon/prune.go
> +			// when the context is cancelled, return true to stop the networks traverse
nit; "when" should probably be "if"

would it be enough to just mention "return true to stop network traverse"? or is "context cancelled" a special case?

2017-07-10 00:40 UTC, thaJeztah commented on daemon/prune.go
> +		logrus.Debugf("NetworksPrune operation cancelled: %#v", *rep)
I see @cpuguy83 suggested "debug"; just wondering if changing from "warn" in the current code to "debug" is too big a change, and if "info" would be a better fit.

Not a show stopper, just thinking aloud

2017-07-10 02:08 UTC, allencloud commented on daemon/prune.go
> +		return rep, nil
What you mentioned is right, I have updated this, Thanks a lot.

2017-07-10 07:09 UTC, mlaventure commented on daemon/prune.go
> +		logrus.Debugf("NetworksPrune operation cancelled: %#v", *rep)
I think debug is fine. Not sure if that message being in the log by default has any benefits

2017-07-10 21:09 UTC, thaJeztah commented
hm, flaky? https://jenkins.dockerproject.org/job/Docker-PRs/44175/console

```
03:33:45 ----------------------------------------------------------------------
03:33:45 FAIL: docker_cli_swarm_test.go:1146: DockerSwarmSuite.TestSwarmLockUnlockCluster
03:33:45 
03:33:45 [d6209096216f9] waiting for daemon to start
03:33:45 [d6209096216f9] daemon started
03:33:45 
03:33:45 [df75e109fdee3] waiting for daemon to start
03:33:45 [df75e109fdee3] daemon started
03:33:45 
03:33:45 [ded4392fb23e8] waiting for daemon to start
03:33:45 [ded4392fb23e8] daemon started
03:33:45 
03:33:45 [df75e109fdee3] exiting daemon
03:33:45 [df75e109fdee3] waiting for daemon to start
03:33:45 [df75e109fdee3] daemon started
03:33:45 
03:33:45 [df75e109fdee3] exiting daemon
03:33:45 [d6209096216f9] exiting daemon
03:33:45 [d6209096216f9] waiting for daemon to start
03:33:45 [d6209096216f9] daemon started
03:33:45 
03:33:45 [ded4392fb23e8] exiting daemon
03:33:45 [ded4392fb23e8] waiting for daemon to start
03:33:45 [ded4392fb23e8] daemon started
03:33:45 
03:33:45 [df75e109fdee3] waiting for daemon to start
03:33:45 [df75e109fdee3] daemon started
03:33:45 
03:33:45 docker_cli_swarm_test.go:1192:
03:33:45     // d2 is now set to lock
03:33:45     checkSwarmUnlockedToLocked(c, d2)
03:33:45 docker_utils_test.go:471:
03:33:45     c.Assert(v, checker, args...)
03:33:45 ... obtained bool = false
03:33:45 ... expected bool = true
03:33:45 
03:33:45 [d6209096216f9] exiting daemon
03:33:45 [df75e109fdee3] exiting daemon
03:33:45 [ded4392fb23e8] exiting daemon
03:34:06 
```

2017-07-11 01:09 UTC, allencloud commented
Great to see all green. ☀️ 😄

2017-07-11 01:14 UTC, thaJeztah approved these changes
LGTM

@cpuguy83 PTAL

2017-07-11 01:17 UTC, cpuguy83 approved these changes
LGTM

2017-07-11 01:17 UTC, merged