Return an empty stats if "container not found"
moby/moby pull request #34004
Opened 2017-07-07 08:06 UTC by yummypeng

If we get "container not found" error from containerd, it's possibly
because that this container has already been stopped. It will be ok to
ignore this error and just return an empty stats.

**Steps to reproduce:**
```
# docker run -tid --name tmp --restart=always ubuntu true && docker stats --no-stream
48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c

(hangs...)

^C
#
```

It's a duplicate of #27772 which has already been closed by https://github.com/moby/moby/pull/28026, but https://github.com/moby/moby/pull/28026 is not a complete fix because if `docker stats --no-stream` comes faster after `docker run`, the container is still running when the code hits https://github.com/moby/moby/blob/master/daemon/stats.go#L35. Then I can see a lot of error logs from daemon:
```
time="2017-07-07T14:54:41.210577988+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:42.210686973+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:43.210721305+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:44.210637074+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:45.210742374+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:46.210928003+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:47.210899239+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:48.210914277+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:49.210748399+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:50.210818936+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
time="2017-07-07T14:54:51.210596037+08:00" level=error msg="collecting stats for 48d3344f404a2b4a28538af857dedab5bca7f3939667f51509c61dd9f150bf5c: rpc error: code = Unknown desc = containerd: container not found"
```
This pr will ignore this error and just return an empty stats. So that client will not hang forever.

Signed-off-by: Yuanhong Peng <pengyuanhong@huawei.com>

2017-07-07 08:23 UTC, yummypeng commented
![images](https://user-images.githubusercontent.com/20569488/27949524-90e8c9b8-6330-11e7-936a-517eac6183e1.jpg)

2017-07-07 08:28 UTC, yummypeng commented
Oops, I close this pr by mistake and CI stopped @thaJeztah

2017-07-07 22:12 UTC, thaJeztah commented
Looks like CI started again, and is green now 👍

2017-07-07 22:32 UTC, thaJeztah requested changes
Left some suggestions :)

2017-07-07 22:32 UTC, thaJeztah commented on daemon/stats/collector.go
> +				if _, ok := err.(notRunningErr); !ok && !strings.Contains(err.Error(), "container not found") {
Could we make the `container not found` error a typed error (like we do for `notRunningErr`)?

2017-07-07 22:32 UTC, thaJeztah commented on daemon/stats/collector.go
> +				if _, ok := err.(notRunningErr); !ok && !strings.Contains(err.Error(), "container not found") {
Not introduced in this PR, but while looking at this code:
The double negative is a bit confusing here as well; would this be more readable (assuming a typed error for `container not found` was implemented;?

```go
for _, pair := range pairs {
	stats, err := s.supervisor.GetContainerStats(pair.container)

	switch err.(type) {
	case nil:
		// FIXME: move to containerd on Linux (not Windows)
		stats.CPUStats.SystemUsage = systemUsage
		stats.CPUStats.OnlineCPUs = onlineCPUs

		pair.publisher.Publish(*stats)

	case notRunningErr, notFoundErr:
		// publish empty stats containing only name and ID if not running or not found
		pair.publisher.Publish(types.StatsJSON{
			Name: pair.container.Name,
			ID:   pair.container.ID,
		})

	default:
		logrus.Errorf("collecting stats for %s: %v", pair.container.ID, err)
	}
}
```

2017-07-10 02:09 UTC, yummypeng commented on daemon/stats/collector.go
> +				if _, ok := err.(notRunningErr); !ok && !strings.Contains(err.Error(), "container not found") {
@thaJeztah Thanks for your suggestion :heart: I have updated the codes.

2017-07-10 02:53 UTC, thaJeztah requested changes
left one more comment

also /cc @cpuguy83 for review

2017-07-10 02:53 UTC, thaJeztah commented on daemon/daemon_unix.go
> +		if strings.Contains(err.Error(), "container not found") {
I guess this also needs to be done in the `_windows` version; https://github.com/moby/moby/blob/9d87e6e0fb799d6ef3bb9a97bc523f8d343b5fb3/daemon/daemon_windows.go#L525-L529

2017-07-10 03:04 UTC, yummypeng commented on daemon/daemon_unix.go
> +		if strings.Contains(err.Error(), "container not found") {
Updated :wink:  @thaJeztah

2017-07-10 04:14 UTC, thaJeztah requested changes

2017-07-10 04:14 UTC, thaJeztah commented on daemon/stats/collector.go
> +}
Hm, looking at this again; this interface is not specific enough, as both `daemon. errNotRunning`, and `daemon. errNotFound` satisfy this interface; see https://play.golang.org/p/HtkBu1_QuM. If you make it more specific, it works though; https://play.golang.org/p/S7DzAuRITj

2017-07-10 06:20 UTC, yummypeng commented on daemon/stats/collector.go
> +}
@thaJeztah Tons of thanks for finding this :heart:

2017-07-10 08:35 UTC, yummypeng commented
janky failed but it seems not related to my PR:
```
07:41:22 ----------------------------------------------------------------------
07:41:22 FAIL: docker_cli_swarm_test.go:1146: DockerSwarmSuite.TestSwarmLockUnlockCluster
07:41:22 
07:41:22 [d4ec576a08906] waiting for daemon to start
07:41:22 [d4ec576a08906] daemon started
07:41:22 
07:41:22 [dacb4fc0da4ef] waiting for daemon to start
07:41:22 [dacb4fc0da4ef] daemon started
07:41:22 
07:41:22 [d0e91bd982f1a] waiting for daemon to start
07:41:22 [d0e91bd982f1a] daemon started
07:41:22 
07:41:22 [dacb4fc0da4ef] exiting daemon
07:41:22 [dacb4fc0da4ef] waiting for daemon to start
07:41:22 [dacb4fc0da4ef] daemon started
07:41:22 
07:41:22 [dacb4fc0da4ef] exiting daemon
07:41:22 [d4ec576a08906] exiting daemon
07:41:22 [d4ec576a08906] waiting for daemon to start
07:41:22 [d4ec576a08906] daemon started
07:41:22 
07:41:22 [d0e91bd982f1a] exiting daemon
07:41:22 [d0e91bd982f1a] waiting for daemon to start
07:41:22 [d0e91bd982f1a] daemon started
07:41:22 
07:41:22 [dacb4fc0da4ef] waiting for daemon to start
07:41:22 [dacb4fc0da4ef] daemon started
07:41:22 
07:41:22 docker_cli_swarm_test.go:1192:
07:41:22     // d2 is now set to lock
07:41:22     checkSwarmUnlockedToLocked(c, d2)
07:41:22 docker_utils_test.go:471:
07:41:22     c.Assert(v, checker, args...)
07:41:22 ... obtained bool = false
07:41:22 ... expected bool = true
07:41:22 
07:41:22 [d4ec576a08906] exiting daemon
07:41:22 [dacb4fc0da4ef] exiting daemon
07:41:22 [d0e91bd982f1a] exiting daemon
07:41:35 
07:41:35 ----------------------------------------------------------------------
```

2017-07-11 02:34 UTC, yummypeng commented
ping @thaJeztah @cpuguy83

2017-07-11 03:03 UTC, thaJeztah commented on daemon/stats/collector.go
> +}
@yummypeng you're welcome! I almost missed it as well ☺️

2017-07-11 03:04 UTC, thaJeztah approved these changes
LGTM

2017-07-11 10:05 UTC, vieux commented
LGTM ping @tiborvass

2017-07-11 10:05 UTC, vieux commented
ping @kolyshkin

2017-07-12 03:10 UTC, tiborvass commented
LGTM

2017-07-12 03:10 UTC, merged