Allow stopping of paused container
moby/moby pull request #34027
Opened 2017-07-09 13:41 UTC by cpuguy83

When a container is paused, signals are sent once the container has been
unpaused.
Instead of forcing the user to unpause a container before they can ever
send a signal, allow the user to send the signals, and in the case of a
stop signal, automatically unpause the container afterwards.

This is much safer than unpausing the container first then sending a
signal (what a user is currently forced to do), as the container may be
paused for very good reasons and should not be unpaused except for
stopping.
Note that not even SIGKILL is possible while a process is paused,
but it is killed the instant it is unpaused.

Closes #15853
Closes #28366

2017-07-09 19:14 UTC, boaz0 approved these changes
👍

2017-07-09 20:26 UTC, thaJeztah commented
ping @coolljt0725 - guess you want to have a look

2017-07-10 06:43 UTC, coolljt0725 commented
I like this,  :+1: LGTM

2017-07-10 13:57 UTC, vieux commented on integration-cli/docker_cli_pause_test.go
> +func (s *DockerSuite) TestStopPausedContainr(c *check.C) {
missing `e`

2017-07-10 13:58 UTC, vieux commented
SGTM

2017-07-10 13:59 UTC, cpuguy83 commented on integration-cli/docker_cli_pause_test.go
> +func (s *DockerSuite) TestStopPausedContainr(c *check.C) {
It's web 2.0

2017-07-10 14:00 UTC, cpuguy83 commented on integration-cli/docker_cli_pause_test.go
> +func (s *DockerSuite) TestStopPausedContainr(c *check.C) {
Fixed

2017-07-11 06:35 UTC, thaJeztah commented
powerpc failing on https://github.com/moby/moby/issues/34051

2017-07-12 06:19 UTC, thaJeztah requested changes
Gee, that `kill.go` file is really difficult to follow, there's a lot of weird logic in there.

Looking at this, I wonder why we have all the conditions to determine if we want or don't want to unpause the container.

Can't we simply modify `daemon.kill()` to:

```go
func (daemon *Daemon) kill(c *containerpkg.Container, sig int) error {
	if err := daemon.containerd.Signal(c.ID, sig); err != nil {
		return err
	}
	if c.Paused {
		// above kill signal will be sent once resume is finished
		if err := daemon.containerd.Resume(c.ID); err != nil {
			logrus.Warn("Cannot unpause container %s: %s", c.ID, err)
		}
	}
	return nil
}
```

Basically; if we want to send a signal to the container, we unpause (un-freeze) it afterwards, otherwise the signal never reaches the process.

Are there any conditions we can think of where that is _not_ the desired behaviour?

2017-07-12 06:19 UTC, thaJeztah commented on daemon/kill.go
> +	if unpause {
Looks like we try to resume the container, even if the `daemon.kill()` above returned `"container not found"` or `"no such process"`

2017-07-12 14:27 UTC, cpuguy83 commented on daemon/kill.go
> +		unpause = container.Paused
No, unpause is only needed for kill signals.
In the case where the daemon is not shutting down, it's already going to be set. But we also need to make sure that when the daemon is shutting down that we set it.

2017-07-12 14:30 UTC, cpuguy83 commented on daemon/kill.go
> +		unpause = container.Paused
But, I guess it should already be set in both cases since it should be a stop sig on shutdown.

2017-07-12 14:40 UTC, cpuguy83 commented on daemon/kill.go
>  	if !daemon.IsShuttingDown() {
Removed else.

2017-07-12 14:40 UTC, cpuguy83 commented on daemon/kill.go
> +	if unpause {
Fixed

2017-07-12 16:39 UTC, cpuguy83 commented
@thaJeztah I think we only want to unpause if it's a stop-type signal. signal.

2017-07-13 02:13 UTC, thaJeztah approved these changes
LGTM

2017-07-13 02:14 UTC, thaJeztah commented
ping @coolljt0725 @vieux PTAL

2017-07-13 02:16 UTC, coolljt0725 commented
LGTM

2017-07-13 02:16 UTC, merged