Add builder dev report for 2017-07-10
moby/moby pull request #34089
Opened 2017-07-12 23:56 UTC by tonistiigi

@vieux @thaJeztah 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

2017-07-13 01:25 UTC, AkihiroSuda commented on reports/builder/2017-07-10.md
> +Running build jobs now has support for graceful canceling and clear error reporting in case some build steps fail or are canceled. Bugs that may have left state dir in an inconsistent state of server
fixes -> fixed

2017-07-13 01:25 UTC, AkihiroSuda commented on reports/builder/2017-07-10.md
> +Separate source implementation for git repositories is currently in review. Using this source for accessing source code in git repositories has many performance and caching advantages. All the build
in review -> merged

2017-07-13 02:19 UTC, thaJeztah requested changes
minor nits, but LGTM

2017-07-13 02:19 UTC, thaJeztah commented on reports/builder/2017-07-10.md
> +The build definition solver was updated to detect the identical parts of the graph sent by different clients and synchronize their processing. This is important when multiple targets of the same proj
s/on the same time/at the same time/

2017-07-13 02:19 UTC, thaJeztah commented on reports/builder/2017-07-10.md
> +No updates for this week. Metadata commands need to be updated but it probably easier to do it after https://github.com/moby/moby/pull/33492 has been merged.
s/but it probably easier/but it is probably easier/

2017-07-13 02:59 UTC, tonistiigi commented on reports/builder/2017-07-10.md
> +Separate source implementation for git repositories is currently in review. Using this source for accessing source code in git repositories has many performance and caching advantages. All the build
I wrote this on Monday. Sorry for posting late.

2017-07-13 03:09 UTC, thaJeztah approved these changes
LGTM

ping @vieux

2017-07-13 14:34 UTC, cpuguy83 requested changes

2017-07-13 14:34 UTC, cpuguy83 commented on reports/builder/2017-07-10.md
> +The PR is in code review and waiting for feedback. Hopefully ready to me merged this week.
"be merged"

2017-07-14 03:20 UTC, tonistiigi commented on reports/builder/2017-07-10.md
> +The PR is in code review and waiting for feedback. Hopefully ready to me merged this week.
updated

2017-07-14 06:25 UTC, thaJeztah commented
I see @cpuguy83's comment was addressed; I'll merge

2017-07-14 06:25 UTC, merged