Exit if there are unnecessary keys in the config file
moby/moby pull request #34093
Opened 2017-07-13 13:45 UTC by ripcurld0

**- What I did**

I would like to have a consistent behavior when loading the configuration file.
When I have a key in daemon.json that is not an option and is empty, I rather the daemon to exit with an error message than continue running without knowing that something is ignored or useless in the configuration file. It is also another way to make sure there are no typos. For example, "default-ulimit" instead of "default-ulimits".

**- How I did it**

* Change `configValueSet` to return `unnecessaryKeys` keys alongside with `configSet`
* Check that `unnecessaryKeys` is empty otherwise return error specifying the bad keys

**- How to verify it**

```
$ TESTDIRS='daemon/config' hack/make.sh test-unit
```

2017-07-13 13:45 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "daemon_json" git@github.com:ripcurld0/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-07-20 13:10 UTC, thaJeztah commented
I'm a bit hesitant to completely _fail_ if unknown keys are found. My thought behind this is that people may have a system in place to provision hosts, possibly targeting different versions  of docker.

I _would_ agree to start with printing warnings ("Ignoring unknown option xyz") and possibly in future change this to an error.

_However_ (without having deep-dived into the code) I have a feeling we're reinventing the wheel; I think we're looking at properly validating the `daemon.json`; the format is currently "badly" documented (just the example JSON in https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file), which could use some improvement overall.

Would it be an idea to define a JSON schema for the configuration file, and use that for validating? Possibly we can use the schema itself to generate documentation as well (which would be a win-win)

WDYT?

Also /cc @dnephin @vdemeester perhaps you have thoughts on the JSON-schema (with the experience you have on the compose schema; https://github.com/docker/cli/tree/master/cli/compose/schema/data)

(Orthogonal to this, but there's a lot of improvements to be made to the daemon configuration, I have a TODO on my list to write down a list of things we should work on)

2017-07-20 13:20 UTC, ripcurld0 commented
@thaJeztah sounds awesome!
This commit was meant to make the daemon configuration validation more verbose.
If there is a schema it makes the job easier and will produce human-readable errors and warnings.

2017-07-20 18:06 UTC, thaJeztah commented
Discussing this in the maintainers meeting, and we're ok with this as a stop-gap solution; if you change it to a warning instead of erring, and quiting

2017-08-01 08:58 UTC, vdemeester reviewed
Design LGTM 👼

2017-08-02 09:33 UTC, thaJeztah requested changes

2017-08-02 09:33 UTC, thaJeztah commented on daemon/config/config.go
> +			logrus.Warnf("The following configuration keys are unnecessary: %s", strings.Join(unnecessaryKeys, ","))
Wondering how much value this adds. Having empty options in the configuration file may actually be a deliberate choice; similar to having "commented out" options in an ini-file. If these options are not changing the daemon's behaviour, I think it's fine to skip them without warning.

I _do_ think options that are _unknown_ should output a warning (thinking of the "typo" situation), but as commented earlier, I'd prefer to have a json-schema (or similar) approach for this.

I'm -1 on this change (sorry! 😅 )

2017-08-02 14:04 UTC, ripcurld0 commented
👍  closing this because it doesn't have any added value.

2017-08-02 14:04 UTC, closed without merging