Fix tar prefix header
moby/moby pull request #34106
Opened 2017-07-14 02:11 UTC by tonistiigi

One possible fix for #34092 , especially for the releases that can't wait for golang update.

@dmcgowan @stevvooe @thaJeztah @tiborvass @andrewhsu

2017-07-14 02:12 UTC, tonistiigi commented
We can also discuss better fixes than reverting but these should probably happen in upstream first.

2017-07-14 04:39 UTC, thaJeztah commented
@tonistiigi could you add your description in https://github.com/moby/moby/issues/34092#issuecomment-315231720 as commit message? (probably to the "test" commit, but could be both)

2017-07-14 04:41 UTC, thaJeztah requested changes
Fix and code itself LGTM, but left some comments

2017-07-14 04:41 UTC, thaJeztah commented on pkg/archive/archive_test.go
> +func TestPrefixHeaderReadable(t *testing.T) {
Can you add a short description of what we're testing for here?

2017-07-14 04:41 UTC, thaJeztah commented on Dockerfile
> +# IMPORTANT: When updating this please note that stdlib archive/tar pkg is vendored
This Note should be added to all the Dockerfiles

2017-07-14 04:44 UTC, thaJeztah commented
@tonistiigi guess this one also fixes https://github.com/moby/moby/issues/33958 ?

2017-07-14 04:50 UTC, tonistiigi commented
> guess this one also fixes #33958 ?

@thaJeztah yes

2017-07-14 17:24 UTC, tonistiigi commented
@thaJeztah Updated

2017-07-14 17:27 UTC, thaJeztah approved these changes
LGTM

2017-07-14 17:37 UTC, dmcgowan commented
LGTM

Let's figure out a better way to handle this vendoring in a follow up. I don't think it is a big issue to create a repo with just `archive/tar` from the golang fork, as long as that repo is only updated from the golang fork and not maintained as a package fork.

2017-07-14 17:37 UTC, dmcgowan approved these changes

2017-07-17 07:40 UTC, vdemeester approved these changes
LGTM 🐯

2017-07-17 07:40 UTC, merged