set plugin v1 active timeout
moby/moby pull request #34177
Opened 2017-07-19 07:00 UTC by BSWANG

Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>

**- What I did**
Fix #33871  , Dockerd can not restart when use containerize v1 plugins.
**- How I did it**
Set plugin check http client timeout.
**- How to verify it**
Restart the docker daemon with v1 plugin.
**- Description for the changelog**

In the `pkg/plugins/plugins.go activateWithLock` . Use the timeout http client with 30 seconds.

**- A picture of a cute animal (not mandatory but encouraged)**

![image](https://user-images.githubusercontent.com/3598874/28354570-f8048c20-6c92-11e7-9019-d33ca11717e0.png)

2017-07-19 20:26 UTC, cpuguy83 requested changes

2017-07-19 20:26 UTC, cpuguy83 commented on pkg/plugins/plugins.go
> +	c, err := NewClientWithTimeout(p.Addr, p.TLSConfig, 30*time.Second)
I don't think we can just set a 30s timeout here.
Many requests may take more than 30s (e.g. provisioning block storage for a volume).

This client gets cached and used for other requests, IIRC.

2017-07-20 07:14 UTC, BSWANG commented
@cpuguy83 Look like the client will be use for following API requests. Should I just set the timeout on `Activity` API request?

2017-12-15 02:15 UTC, BSWANG commented
Maybe fixed by #35265

2017-12-15 02:15 UTC, closed without merging