Update volume_ls.md
moby/moby pull request #34225
Opened 2017-07-23 16:29 UTC by hernandanielg

Fixed `Network` to `Volume`

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-07-23 16:29 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-2" git@github.com:hernandanielg/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-07-23 16:42 UTC, hernandanielg commented
Done and thanks :)

2017-07-24 06:15 UTC, ripcurld0 commented on docs/reference/commandline/volume_ls.md
>  `.Label`      | Value of a specific label for this volume. For example `{{.Label "project.version"}}`
I think it has `.Label` any more. In addition, the doc is missing the `Links` and the `Size` placeholders.

2017-07-24 06:16 UTC, ripcurld0 commented
@thaJeztah @dnephin shouldn't this PR be moved to https://github.com/docker/cli?

2017-07-24 08:17 UTC, thaJeztah requested changes
Thanks @hernandanielg - I left some comments 👍 

As @ripcurld0 mentioned, the _current_ version of these docs has moved to the docker/cli repository; https://github.com/docker/cli/blob/master/docs/reference/commandline/volume_ls.md

This PR targets the 17.03.x branch (so will only affect the 17.03 archive of the docs). Given that docker 17.03 is still supported, I think it's good to update this; would you be interested in opening a similar pull request to the docker/cli repository?

2017-07-24 08:17 UTC, thaJeztah commented on docs/reference/commandline/volume_ls.md
>  `.Label`      | Value of a specific label for this volume. For example `{{.Label "project.version"}}`
It does have `.Label` still;

```bash
$ docker volume create --label project.version=one-two foobar
$ docker volume create --label project.version=three-four foobar2

$ docker volume ls --format 'table {{.Name}}\t{{.Label "project.version"}}'

VOLUME NAME         VERSION
foobar              one-two
foobar2             three-four
```

w.r.t. the `Links` and `Size` - these values are only propagated by the "prune" command; I'm actually looking at deprecating those fields for `volume ls`, and using a dedicated API type for the prune action

2017-07-24 08:17 UTC, thaJeztah commented on docs/reference/commandline/volume_ls.md
> +`.Mountpoint` | Whether the volume is internal or not.
This description is a bit odd; Perhaps "The mount point of the volume on the host" ?

2017-07-24 09:21 UTC, hernandanielg commented
Ok sure I will create a new PR on docker/cli. I came here using link on Edit on the documentation, so I think that needs to be fixed too. Maybe we can close this PR.

2017-07-24 09:21 UTC, closed without merging