add check for local volume option
moby/moby pull request #34233
Opened 2017-07-24 08:20 UTC by moypray

**- What I did**

Add check for creating local volume

Fix issue:
```
root@localhost:~# docker volume create -d local --name test -o type=tmpfs
test
root@localhost:~# docker run -tid -v test:/tmp ubuntu
docker: Error response from daemon: missing device in volume options.
See 'docker run --help'.
root@localhost:~#
```

I think it should fail at creating it.
```
root@localhost:~# docker volume create -d local --name test2 -o type=tmpfs
Error response from daemon: create test2: option device must be specified
root@localhost:~#
```

**- How I did it**

add check flag when creating local volume

**- How to verify it**

docker volume create -d local --name test -o type=tmpfs
It should fail to create local volume when provide wrong options.

**- Description for the changelog**

Signed-off-by: Wentao Zhang <zhangwentao234@huawei.com>

**- A picture of a cute animal (not mandatory but encouraged)**

2017-07-24 16:29 UTC, thaJeztah commented
@moypray there's a test failing;

```
08:45:34 ----------------------------------------------------------------------
08:45:34 FAIL: docker_api_containers_test.go:1549: DockerSuite.TestContainersAPICreateMountsValidation
08:45:34 
08:45:34 case 0
08:45:34 case 1
08:45:34 case 2
08:45:34 case 3
08:45:34 case 4
08:45:34 case 5
08:45:34 case 6
08:45:34 case 7
08:45:34 case 8
08:45:34 case 9
08:45:34 docker_api_containers_test.go:1735:
08:45:34     c.Assert(status, checker.Equals, x.status, check.Commentf("%s\n%v", string(b), cases[i].config))
08:45:34 ... obtained int = 500
08:45:34 ... expected int = 201
08:45:34 ... {"message":"create hello3: option device must be specified"}
08:45:34 
08:45:34 {busybox {[{volume hello3 /foo false  <nil> 0xc4200c4540 <nil>}]}}
08:45:34 
```

2017-07-25 01:53 UTC, moypray commented
@thaJeztah updated, thanks, wait for CI.

BTW, I supposed that we support `tmpfs | nfs` for local driver, and the `device` and `type` options are both mandatory for them.

Correct me if something is wrong.

2017-07-25 14:57 UTC, dsheets commented
I don't think a device is necessary for bind mounts.

2017-07-26 01:14 UTC, moypray commented
@dsheets yes, for bind mount, it is not necessary

But I wonder if we use bind mount in local volume? And the `device` option is checked here：
https://github.com/moby/moby/blob/master/volume/local/local_unix.go#L75

So I supposed that local volume just supports `nfs | tmpfs | local directory` as I said. But I am not sure.
`device` and `type` are both mandatory for `nfs` and `tmpfs`.

2017-07-26 01:15 UTC, moypray commented
ping @thaJeztah  @cpuguy83

2017-07-26 10:05 UTC, dsheets commented
@moypray I was confused and thinking of the `type=` key which is unnecessary for bind mounts. `device=` is, of course, how you specify the source of the bind mount. Sorry!

With that said, use of local volume bind mounts should definitely be considered when changing `local` but requiring `device=` is fine for them.

The only file system that I know of that doesn't require a device is `proc` but a dummy can be provided. As you point out, at mount time `device` is already checked for all `local` volumes.

2017-07-27 01:12 UTC, moypray commented
@dsheets That's fine, I think we can just set `device` as mandatory key. I will rework my PR.

2017-07-27 01:13 UTC, moypray commented
BTW, how could we use bind mount in local volume driver??

2017-07-27 08:44 UTC, dsheets commented
`docker volume create -o o=bind -o device=/etc my_etc_volume`

2017-07-27 08:47 UTC, moypray commented
@dsheets Got it, thanks.

2017-10-26 18:23 UTC, thaJeztah commented on volume/local/local_unix.go
> +		"device": {},
Discussing with @cpuguy83 and we should add `type` to this list as well; can you add that?

2017-10-26 18:26 UTC, thaJeztah commented
Generally looks good, but needs a rebase, and a check for `type`; could you update the PR @moypray ?

2017-10-26 18:27 UTC, cpuguy83 requested changes

2017-10-26 18:27 UTC, cpuguy83 commented on volume/local/local.go
> +				return validationError{fmt.Errorf("option %s must be specified", mKey)}
Can we use `errors.Errorf`? This passes the error with the stack trace for debugging purposes.

Maybe we can re-word this, something like "missing required option %s".

2017-10-26 18:27 UTC, cpuguy83 commented on volume/local/local_unix.go
> +		"device": {},
This needs to add "type".

2018-01-17 16:37 UTC, cpuguy83 commented
Any news @moypray ?

2018-01-18 01:47 UTC, moypray commented
@cpuguy83 
sorry, I do not work on docker for some time. Would some one to cherry this PR ?

2018-04-06 09:13 UTC, vdemeester reviewed
SGTM :angel: 
cc @thaJeztah @cpuguy83 I rebased it against master and took care of your comments :angel: :wink:

2018-04-06 16:36 UTC, cpuguy83 commented
```
09:24:32 volume/local/local.go:375:12:warning: invalid composite literal type validationError (gosimple)
09:24:32 volume/local/local.go:375:12:warning: invalid composite literal type validationError (interfacer)
09:24:32 volume/local/local.go:375:12:warning: invalid composite literal type validationError (unconvert)
```

2018-05-15 08:55 UTC, vdemeester commented
re-rebased :sweat_smile:

2018-05-15 10:28 UTC, thaJeztah approved these changes
LGTM

2018-05-15 10:28 UTC, thaJeztah commented
ping @cpuguy83 PTAL

2018-05-15 13:52 UTC, cpuguy83 commented
```
09:52:39 FAIL: docker_api_containers_test.go:1662: DockerSuite.TestContainersAPICreateMountsValidation
09:52:39 
09:52:39 case 0
09:52:39 case 1
09:52:39 case 2
09:52:39 case 3
09:52:39 case 4
09:52:39 case 5
09:52:39 case 6
09:52:39 case 7
09:52:39 case 8
09:52:39 case 9
09:52:39 docker_api_containers_test.go:1878:
09:52:39     c.Assert(err.Error(), checker.Contains, x.msg, check.Commentf("%v", cases[i].config))
09:52:39 ... obtained string = "Error response from daemon: create hello3: missing required option device"
09:52:39 ... substring string = "device must be specified"
09:52:39 ... {   false false false map[] false false false [] [] <nil> false busybox map[]  [] false  [] map[]  <nil> []}
09:52:39 
09:52:40 
09:52:40 ----------------------------------------------------------------------
```

2018-12-21 18:42 UTC, olljanat commented
Derek add label: rebuild/*

2018-12-22 01:19 UTC, thaJeztah commented
Rebased, fixed the failing test, added a missing test-case for "type", and made some small tweaks

@cpuguy83 @vdemeester PTAL

2018-12-24 16:29 UTC, merged