Improve debug message
moby/moby pull request #34232
Opened 2017-07-24 07:50 UTC by blag

Signed-off-by: Drew Hubl <drew.hubl@gmail.com>

**- What I did**

Added filesystem information to debug log when rootdir filesystem != zfs.

**- How I did it**

Modified the format string of the call to `logrus.Debugf` to include filesystem information and added the type of filesystem that was found.

**- How to verify it**

There is no change in logic, just in the log message. Verification not really necessary.

**- Description for the changelog**

Improved logging to ease troubleshooting.

**- A picture of a cute animal (not mandatory but encouraged)**

Please accept this bribe of two baby elephant pics (shamelessly stolen from [/r/babyelephants](https://www.reddit.com/r/babyelephants/)) to merge this change.

![Baby elephant on ledge](https://i.redd.it/zhmqox26ahwy.jpg)
![Elephant faceplant](https://i.imgur.com/62vLHRF.jpg)

2017-07-24 16:56 UTC, thaJeztah requested changes

2017-07-24 16:56 UTC, thaJeztah commented on daemon/graphdriver/zfs/zfs_linux.go
> +		logrus.Debugf("[zfs] no zfs dataset found for rootdir '%s', found '%s' filesystem", rootdir, buf.Type)
`buf.Type` is an `int64`, so probably isn't very useful to print; perhaps this should use a similar approach as is used by the other drivers? https://github.com/moby/moby/blob/90fbe6a7373da81b36d1427e0c2764c0b583f421/daemon/graphdriver/aufs/aufs.go#L91-L103

2017-07-31 08:13 UTC, thaJeztah commented
ping @blag ^^

2017-08-02 06:56 UTC, blag commented
@thaJeztah ACK. I like your suggested changes, but I'm not sure I'm going to have time to redo this until next week. Please ping me next week if I don't get to it.

2017-08-02 10:23 UTC, thaJeztah commented
Sure! Thanks in advance!

2017-09-26 04:56 UTC, AkihiroSuda commented
ping @blag

2017-10-10 08:13 UTC, AkihiroSuda commented
pingping @blag

2017-10-10 09:21 UTC, blag commented
@AkihiroSuda Sorry I've been MIA - I started a new job. I'll try to get this done this weekend.

2018-01-16 22:01 UTC, cpuguy83 commented
Carrying this in #36033

2018-01-16 22:01 UTC, closed without merging