Use ID rather than Name to identify a container when sharing namespace
moby/moby pull request #34352
Opened 2017-08-01 12:35 UTC by ChenMin46

Fix: https://github.com/moby/moby/issues/34307

Signed-off-by: Chen Min chenmin46@huawei.com

**- What I did**
Convert from the connected container name to its ID when we create the container.

**- How I did it**
Modify PidMode、Ipcmode and NetworkMode of hostConfig in /daemon/daemon_unix.go

**- How to verify it**
I wrote a test case,which names "TestAdaptSharedNamespaceContainer".

**- Description for the changelog**

 daemon/daemon_unix.go                     | 31 +++++++++++++++++++++++++++++++
 integration-cli/docker_cli_create_test.go | 13 +++++++++++++
 2 files changed, 44 insertions(+)

**- A picture of a cute animal (not mandatory but encouraged)**
：）

2017-08-01 12:35 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "fix_rename_shared_namespace" git@github.com:ChenMin46/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-08-01 12:54 UTC, AkihiroSuda requested changes
The test result is unchecked.
Also, please add an API test instead of CLI one

2017-08-01 13:26 UTC, ripcurld0 commented on daemon/daemon_unix.go
> +// When a container shares its namespace by container name,
Can you change the comment to `adaptSharedNamespaceContainer replaces a container name with its container ID when ...` or something similar.

2017-08-01 13:27 UTC, ripcurld0 commented on daemon/daemon_unix.go
> +		c, err := daemon.GetContainer(hostConfig.PidMode.Container())
Maybe there is a way to call `daemon.GetContainer` once and avoid all these verbose code lines

2017-08-01 13:28 UTC, boaz0 requested changes
All in all LGTM minus the comment.

2017-08-02 04:08 UTC, yummypeng commented on daemon/daemon_unix.go
> +		c, err := daemon.GetContainer(hostConfig.PidMode.Container())
@ripcurld0 I dont think there is a way to call `daemon.GetContainer` once since we may want to share different namespaces with different containers.

2017-08-02 04:22 UTC, yummypeng commented on integration-cli/docker_cli_create_test.go
> +}
This file is for `docker create` tests. Maybe you should put this testcase in another place.

2017-08-02 14:39 UTC, ChenMin46 commented
I have a doubt, when we create a container named AA but not start it, after another container BB created and BB shares AA's namespaces, we delete container AA, and then recreate a container named AA. Finally
，we start container BB. It comes out an error, the container ID（former AA） is not exists.

This case also confused users.

So, I wonder which logic is better, name or ID ?

2017-08-03 13:46 UTC, ChenMin46 commented
ping @AkihiroSuda 

I add an api test suite to check the results , PTAL. :)

2017-08-03 13:50 UTC, ChenMin46 commented
ping @ripcurld0 

The comments are updated, and some codes  are simplified. PTAL :^)

2017-08-04 00:54 UTC, ChenMin46 commented
The Jenkins control platform checks failed, I have no idea what caused this error.
 ping @ripcurld0 @AkihiroSuda 
```
00:44:09 + docker stop docker-pr-power5093
00:44:09 Error response from daemon: No such container: docker-pr-power5093
```

2017-08-07 06:36 UTC, ChenMin46 commented
All checks have passed , PTAL ,looking forward to your replies, ping @ripcurld0  @AkihiroSuda .  
![image](https://user-images.githubusercontent.com/29109944/29014830-b00afd38-7b7d-11e7-92e9-e5fdb9ac23bd.png)

2017-08-08 07:46 UTC, boaz0 approved these changes
LGTM 👍

2017-08-14 09:20 UTC, ChenMin46 commented
PTAL   ：）   
ping @AkihiroSuda

2017-08-15 03:58 UTC, AkihiroSuda commented
Which function requires this to be ID string?

2017-08-15 04:17 UTC, ChenMin46 commented
When I rename a container which namespace is shared by another container B ,then we restart the container B,it will come out an error .see https://github.com/moby/moby/issues/34307

I try to use ID to keep the connection between the namespace shared and sharing containers.
ping @AkihiroSuda

2017-08-15 04:20 UTC, AkihiroSuda commented on daemon/daemon_unix.go
> +// when a container shares its namespace by container name.
Please add a comment so as to clarify that this conversion is needed for supporting rename operation

2017-08-15 04:20 UTC, AkihiroSuda commented on integration-cli/docker_api_containers_test.go
> +func (s *DockerSuite) TestContainerShareNamespaceByName(c *check.C) {
This needs to be an API test with rename operation

2017-08-16 00:58 UTC, mlaventure commented
ping @ChenMin46

2017-08-18 07:49 UTC, ChenMin46 commented
ping @mlaventure sorry for the late response. I have fixed the conflicts and update the api testsuit.PTAL
:>)

2017-08-18 08:01 UTC, AkihiroSuda approved these changes
LGTM

2017-08-22 13:31 UTC, vdemeester reviewed
SGTM 👼
/cc @dnephin @mlaventure @vieux

2017-08-22 14:32 UTC, mlaventure approved these changes
one nit

LGTM

2017-08-22 14:32 UTC, mlaventure commented on daemon/daemon_unix.go
> +// sharing connection when renaming the container which namespaces be shared.
nit: `it shared`?

2017-08-22 18:06 UTC, dnephin reviewed
This should really be tested with a unit test. Unfortunately `Daemon` is heavily overloaded and makes this difficult.

I'd like to suggest a change which should make it easier to unit test. Instead of making `adaptSharedNamespaceContainer()` a method on `Daemon` (which already has way too many methods) make it a function that accepts an interface

```go
type containerGetter interface {
    func GetContainer(string) container.Container
}
```

That way you can easily provide a fake which returns the values you care about, and test the function behaviour (modifying hostConfig) without all the overhead of the existing integration tests.

2017-08-22 18:06 UTC, dnephin requested changes
Sorry, meant to comment as "Request changes" so doing that now

2017-08-23 06:13 UTC, ChenMin46 commented on integration-cli/docker_api_containers_test.go
> +	dockerCmd(c, "run", "--name=share", "--ipc", "container:"+name, "--pid", "container:"+name, "--net", "container:"+name, "busybox")
@dnephin I have modified `adaptSharedNamespaceContainer()` to accept a `containerGetter` interface as you suggested, here is the demo:
```go
diff --git a/daemon/daemon_unix.go b/daemon/daemon_unix.go
index b3eaa2f68..8bed31da3 100644
--- a/daemon/daemon_unix.go
+++ b/daemon/daemon_unix.go
@@ -64,6 +64,10 @@ const (
        cgroupSystemdDriver = "systemd"
 )

+type containerGetter interface {
+       GetContainer(string) (*container.Container, error)
+}
+
 func getMemoryResources(config containertypes.Resources) *specs.LinuxMemory {
        memory := specs.LinuxMemory{}

@@ -285,7 +289,7 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
                hostConfig.IpcMode = containertypes.IpcMode(m)
        }

-       daemon.adaptSharedNamespaceContainer(hostConfig)
+       adaptSharedNamespaceContainer(daemon, hostConfig)

        var err error
        opts, err := daemon.generateSecurityOpt(hostConfig)
@@ -304,7 +308,7 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
 // adaptSharedNamespaceContainer replaces a container name with its container ID when
 // a container shares its namespace by container name,so as to keep the namespace
 // sharing connection when renaming the container which namespaces be shared.
-func (daemon *Daemon) adaptSharedNamespaceContainer(hostConfig *containertypes.HostConfig) error {
+func adaptSharedNamespaceContainer(daemon containerGetter, hostConfig *containertypes.HostConfig) error {
        containerPrefix := "container:"
        if hostConfig.PidMode.IsContainer() {
                pidContainer := hostConfig.PidMode.Container()
```

> That way you can easily provide a fake which returns the values you care about

But what do you mean by `a fake`? If I understood correctly, you meant I should define a `fakedaemon`  and implement `GetContainer()` ( I think it's complicated to implement this method ), then use that `fakedaemon` to test func `adaptSharedNamespaceContainer`? Could you please give me more infomation?

I noticed a unittest named `TestAdjustCPUShares`, I think I can write a similar one without any change of `adaptSharedNamespaceContainer()` if it's acceptable.

2017-08-23 14:40 UTC, dnephin commented on integration-cli/docker_api_containers_test.go
> +	dockerCmd(c, "run", "--name=share", "--ipc", "container:"+name, "--pid", "container:"+name, "--net", "container:"+name, "busybox")
diff looks good.

Yes, a fake `containerGetter` really (not the whole daemon). It shouldn't be hard to implement, it's something like this:

```go

type fakeContainerGetter struct {
    containers map[string]*container.Container
}

func (f *fakeContainerGetter) GetContainer(cid string) (*container.Container, error) {
    container, ok := f.containers[cid]
    if !ok {
         return nil, errors.New("container not found")
    }
    return container, nil
}
```

A test like `TestAdjustCPUShares` would also be ok.

2017-08-25 00:29 UTC, ChenMin46 commented
![image](https://user-images.githubusercontent.com/29109944/29694502-3529bab4-896f-11e7-9ac7-beb90da0ada0.png)
ping @dnephin All the checks are passed except an irrelevant case. PTAL .：）

2017-08-25 16:36 UTC, dnephin approved these changes
LGTM

2017-08-25 16:39 UTC, merged