Added support for swarm service isolation mode
moby/moby pull request #34424
Opened 2017-08-07 14:33 UTC by simonferquel

**- What I did**
Added isolation field on swarm service creation / updates to enable setting hyperv/process isolation per service on Windows
**- How I did it**
Updated swarmkit (PR with isolation in containerspec), added the field in swarm.ContainerSpec and in convert logic, use it in the executor
**- How to verify it**
Missing a test for now (incoming)
**- Description for the changelog**
Isolation mode (default, process, hyperv) can be set on swarm services to bypass host node defaults

2017-08-07 14:49 UTC, friism commented
Fixes https://github.com/moby/moby/issues/31616

2017-08-07 21:24 UTC, thaJeztah commented
@simonferquel looks like you vendored using an older version of `vndr`; can you update to the current version, and run `vndr` again?

```
14:45:45 The result of vndr differs
14:45:45 
14:45:45 ?? vendor/github.com/docker/distribution/vendor.conf
14:45:45 ?? vendor/github.com/docker/libnetwork/vendor.conf
14:45:45 ?? vendor/github.com/docker/swarmkit/vendor.conf
14:45:45 ?? vendor/github.com/moby/buildkit/vendor.conf
14:45:45 ?? vendor/github.com/opencontainers/runc/vendor.conf
14:45:45 
14:45:45 Please vendor your package with github.com/LK4D4/vndr.
14:45:45 
```

Also, this needs an update of the swagger.yml, and the API version history; https://github.com/moby/moby/blob/master/docs/api/version-history.md

2017-08-08 12:51 UTC, simonferquel commented
Swarm test suite is not executed on Windows. Can't write a usefull test on it. I'll just make a test putting an explicit "default" isolation mode, and will inspect service and container to check if it is not empty.

2017-08-08 13:17 UTC, thaJeztah commented on api/swagger.yaml
> +          Isolation:
Shouldn't this go into the `TaskTemplate.ContainerSpec`?

2017-08-08 13:24 UTC, thaJeztah requested changes
left some notes

2017-08-08 13:24 UTC, thaJeztah commented on api/swagger.yaml
> +            type: "string"
Perhaps add an enum - what is the behaviour if `""` is passed? Is that the same as `default`?

```
            enum:
              - "default"
              - "process"
              - "hyperv"
```

2017-08-08 13:24 UTC, thaJeztah commented on api/swagger.yaml
> +            description: "Isolation mode of the containers running the service (default, process, hyperv..."
Perhaps the same terminology as is used on `docker run`, and add a note that it's only used for Windows containers;

```
description: |
  Container isolation technology to use for the container.

  <p><br /></p>

  > **Note**: Container isolation is only used for Windows containers.
  > This field is ignored for Linux containers.
```

(the `<p><br /></p>` is a bit hacky, but I haven't found another way to add spacing yet :smile:)

2017-08-08 13:38 UTC, simonferquel commented on api/swagger.yaml
> +            type: "string"
"" or null have the same behavior as default (except service inspect will report with an explicit "default" value for isolation).
I am not completely certain about making it an enum btw, as underlying executor (hcs for windows) might introduce new isolation mode. I'll check on container/create messages and harmonize that.

2017-08-08 13:47 UTC, simonferquel commented
@thaJeztah fixed the doc (used the same exact description and enum as on HostConfig)
We'll need to wait for https://github.com/docker/swarmkit/pull/2342 to be merged, update once again the vendoring before merging this one

2017-08-08 14:19 UTC, thaJeztah commented
@simonferquel you forgot this one; https://github.com/moby/moby/pull/34424/commits/967fe0cbceb68a6c25a0ac51a5b368bea29f3a1a#r131908016 😇

2017-08-08 14:32 UTC, simonferquel commented on api/swagger.yaml
> +          Isolation:
It is the case :)

2017-08-08 15:24 UTC, thaJeztah commented on api/swagger.yaml
> +          Isolation:
oh boy, you're right; It looked as if it was at the wrong indentation level, but you're right. Sorry, my mistake ha!

2017-08-17 14:55 UTC, thaJeztah commented
@simonferquel this needs a rebase

2017-08-22 06:04 UTC, coolljt0725 commented
ping @simonferquel needs refactor

2017-09-06 12:50 UTC, simonferquel commented
@thaJeztah, could you please update your review ?

2017-09-20 13:30 UTC, thaJeztah requested changes
left some comments 😅

2017-09-20 13:30 UTC, thaJeztah commented on docs/api/version-history.md
> +* `POST /services/create` and `POST /services/(id)/update` now accept an `Isolation` field on container spec
This should now be in v1.33 as v1.32 has shipped in a release; I opened https://github.com/moby/moby/pull/34908 to bump the API version

2017-09-20 13:30 UTC, thaJeztah commented on integration-cli/daemon/daemon.go
> +func (d *Daemon) InspectContainer(ctx context.Context, id string) (*container.Config, *container.HostConfig, error) {
These tests now probably have to be moved to the `/integration` suite, not `/integration-cli/`; https://github.com/moby/moby/blob/master/integration/service/create_test.go

2017-10-05 04:00 UTC, PatrickLang commented
Can we revive this? With Windows Server version 1709 around the corner, it will be needed to run containers using the Windows Server 2016 base images. Windows versions have breaking kernel changes between them but `--isolation=hyperv` works around that by using the right kernel allowing a newer node to run older containers.

2017-10-05 05:59 UTC, thaJeztah commented
@PatrickLang this is waiting for https://github.com/docker/swarmkit/pull/2342 in SwarmKit upstream

2017-10-05 06:08 UTC, thaJeztah commented
It also involves an API change so cannot be backported without introducing a lot of problems

2017-10-12 09:03 UTC, simonferquel commented
Since the PR Swarmkit side has been merged, I rebased and refreshed this PR.
However, Isolation field on swarm side has moved from a free form string to an enum, with an explicit "Default" value, so I can't use the fact that I could have both <empty>  and "default" valid strings to make a Linux integration kit.

What I want to do then, is to introduce more unit testing, that would hopefully cover all aspects of the PR

2017-10-12 10:07 UTC, simonferquel commented
Done (made a bit of cleanup for reusing Isolation type instead of a free string, and added tests to make sure conversions and executors take the change into account)

2017-10-20 13:45 UTC, simonferquel commented
I just rebased it to see if the plugin tests still fail. Overwise I think the needs/vendoring flag can be removed (the pr now references swarmkit master)

2017-10-24 08:45 UTC, simonferquel commented
Hmm swarmkit vendoring update seem to have broken `DockerSwarmSuite.TestSwarmVolumePlugin` somehow. Not sure why, but I could use some help here...

2017-10-24 10:30 UTC, simonferquel commented
Ok, found the reason of the test regression: error details are reported in a separate task status field now. Updated the test, amended my commit, waiting for test results.

2017-10-24 14:31 UTC, simonferquel commented
@thaJeztah could you update your review ? Want to make sure I did update the right swagger stuff.

2017-10-30 13:41 UTC, thaJeztah approved these changes
LGTM, but needs a minor rebase

2017-10-30 13:42 UTC, thaJeztah commented
ping @cpuguy83 @dnephin PTAL

2017-11-01 18:13 UTC, vieux commented
LGTM ping @cpuguy83 @dnephin

2017-11-01 20:40 UTC, cpuguy83 approved these changes
LGTM

2017-11-01 20:41 UTC, merged