fixing returned error code for network creation from 500 to 409
moby/moby pull request #34484
Opened 2017-08-11 09:42 UTC by yastij

Signed-off-by: Yassine TIJANI <yasstij11@gmail.com>

**- What I did** fixed status code from 500 to 409 see #34459 ping @ripcurld0 @thaJeztah 

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-08-11 10:30 UTC, ripcurld0 commented
This closes #34459

2017-08-11 10:35 UTC, ripcurld0 commented on api/server/router/network/network_routes.go
> +				return httputils.WriteJSON(w, http.StatusConflict, libnetwork.NetworkNameError(create.Name))
I think the last argument in `httputils.WriteJSON` should be `libnetwork.NetworkNameError(create.Name).Error()`.
However I might be wrong.

2017-08-11 10:36 UTC, yastij commented on api/server/router/network/network_routes.go
> +				return httputils.WriteJSON(w, http.StatusConflict, libnetwork.NetworkNameError(create.Name))
Typo

2017-08-11 10:39 UTC, boaz0 requested changes
I think it will be lovely if there are integration tests to this change.

2017-08-11 11:11 UTC, yastij commented on api/server/router/network/network_routes.go
> +				return httputils.WriteJSON(w, http.StatusConflict, libnetwork.NetworkNameError(create.Name))
Fixed

2017-08-11 11:13 UTC, yastij commented
@ripcurld0 - integration tests should be added in `server_test.go` ?

2017-08-11 11:58 UTC, ripcurld0 commented
More likely to [integration-cli/docker_api_network_test.go](https://github.com/moby/moby/blob/master/integration-cli/docker_api_network_test.go#L46-L71).

2017-08-11 12:09 UTC, yastij commented
thanks for the hint.

2017-08-11 12:35 UTC, yastij commented
@ripcurld0 - we should just [https://github.com/moby/moby/blob/master/integration-cli/docker_api_network_test.go#L315](this) to check precisely against conflict code I think.

2017-08-11 12:58 UTC, ripcurld0 commented
@yastij if some tests fail because of this, then we will have to change it but my guess is it's fine and no need to be changed. 🥇

2017-08-11 13:04 UTC, yastij commented
@ripcurld0 this assertion already checks against duplicate network, do you prefer to have another that checks specifically for the conflict status ?

2017-08-12 07:12 UTC, tossmilestone commented
I think `api/server/router/network/network_routes.go:212` should also be changed:
```golang
 	if nws, err := n.cluster.GetNetworksByName(create.Name); err == nil && len(nws) > 0 {
 		return libnetwork.NetworkNameError(create.Name)
 	}
```
WDYT@yastij @ripcurld0

2017-08-12 17:58 UTC, ripcurld0 commented
@tossmilestone yes that's right. @yastij  we have to update that line too.

2017-08-12 18:05 UTC, yastij commented
Sure, taking care of it by tomorrow !

2017-08-25 19:23 UTC, cpuguy83 commented
Please return an error using the new errdefs packag: https://godoc.org/github.com/moby/moby/api/errdefs

2017-09-29 15:01 UTC, thaJeztah commented
This one is carried by @tossmilestone  in https://github.com/moby/moby/pull/35030

2017-09-29 15:01 UTC, closed without merging