Various fixes and improvements to the API docs / Swagger specs
moby/moby pull request #34485
Opened 2017-08-11 14:21 UTC by thaJeztah

This builds on top of https://github.com/moby/moby/pull/34478, so needs a rebase after that is merged.

**- What I did**

Fixed various issues in the API documentation / Swagger:

- Added more per-field example values, so that the examples can more easily be reused. When providing a full example _response_, the type/schema of the endpoint is fully ignored by the generated documentation. Because of this, the documentation may _look_ correct (API response looks correct), but the actual definition is incorrect. It also causes a lot of duplication (same example responses used for multiple endpoints).
- Updated / added descriptions for some fields.
- Fixed various incorrect types (e.g. `uint64` instead of `int`);
  - `ObjectVersion.Index` is an `uint64` https://github.com/moby/moby/blob/0fd90c4d5d8ab739d6f999a36d9c4096e89c8059/api/types/swarm/common.go#L5-L15
  - `ClusterInfo` is nullable in the `/info` output (see https://github.com/moby/moby/blob/ff4f700f74450018f36d014f3cde0ff1b9c17fb3/api/types/swarm/swarm.go#L203)
  - `CAConfig.ForceRotate` was missing a type, therefore treated as an `object` in Swagger: https://github.com/moby/moby/blob/ff4f700f74450018f36d014f3cde0ff1b9c17fb3/api/types/swarm/swarm.go#L121
  - `Raft.SnapshotInterval`, `Raft.KeepOldSnapshots`, and `Raft.LogEntriesForSlowFollowers` are an `uint64` not an `int64`
  - Various fields in `swarm.Info` are nullable; added `x-nullable`

- Fix TLSInfo documenting the wrong type, and being at the wrong nesting level;
  - `TLSInfo` is part of `Node.Description`, but was documented as a
direct child of `Node`
  - `Node.TLSInfo` incorrectly was using the `SwarmSpec` type,
instead of `TLSInfo`

- Add definitions for `Node.Status` and `Node.ManagerStatus`, which only present in the response example, but not documented
- Extracted `Platform`, `EngineDescription`, `NodeDescription` to a definition, instead of being defined as part of an API endpoint (allowing them to be re-used).
- Create a definition for the `/info` response (`SystemInfo`); This endpoint was badly documented, missing various fields, and incorrectly describing others. Also removing the response example in favor of per-field examples, as this prevents an incorrectly formatted response from masking omissions in the actual type.

**- How I did it**

Editing, reading the Go structs that are used for the response, and writing/updating the Swagger specs based on that.

**- How to verify it**

run `make swagger-docs` and visit http://localhost:9000 in your browser

**- Description for the changelog**

    Various fixes and improvements to the API documentation /  Swagger specification.

**- A picture of a cute animal (not mandatory but encouraged)**

2017-08-11 14:22 UTC, thaJeztah commented
Ping @vdemeester @dnephin @mstanleyjones PTAL 😅

2017-08-11 14:26 UTC, thaJeztah commented
I kept commits separate, so it may be easier to review per commit, to verify the changes; the first commit is https://github.com/moby/moby/pull/34478 so can either be ignored here, or we can close the other one :smile:

2017-08-11 17:24 UTC, mdlinville requested changes
A few suggestions and comments. This was big, but I tried to review everything.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +      PortBinding represents a binding between a Host IP address and a Host
Why is Host capitalized within the sentence?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          Date/time at which the node was added to the swarm in
It's date and time, right? Not date or time? (throughout)

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          agent.
What's the "agent"?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +      ClusterInfo represents info about the cluster for outputting in "info"
Ugh I wish this had not been called ClusterInfo. We don't refer to them as clusters but as swarms.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          Date/time at which the swarm cluster was initialised in
At least you can s/swarm cluster/swarm in all these descriptions.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +              `/etc/hosts` file. The format of extra hosts on swarmkit is
Maybe make this less Linux-specific?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +      It rovides the current status of the node, as seen by the manager.
s/rovides/provides

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          reachable. As configured through `--advertise-addr`.
s/As configured through/To configure, use the `--advertise-addr` flag

(or something like that)

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          Storage driver-specific information, provided as "label" / "value" pairs.
Maybe "Information specific to the storage driver"

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          for outputing as part of `docker info` on the command line.
"outputing" is not a word. Maybe "formatted in a way consistent with the output of `docker info`...." or something like that.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +        default: "/var/lib/docker"
So the default default is Linux? ;)

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          > by the Swarm standalone API, and is empty (`null`) in other setups.
Ehhhh.... this is interesting. Do we need to say that this doesn't include built-in swarm mode?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          - [" swarm-master", "192.168.99.101:2376"]
Don't we say manager?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.
Is this Linux-specific?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          When connecting to a standalone Swarm API, this field returns the
You don't connect to an API, right?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          List of [OCI compliant](https://github.com/opencontainers/runtime-spec)
Will people know what OCI is?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          Indicates if "live restore" is enabled.
Why is this quoted?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          The supported values are platform specific.
platform-specific.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          If no isolation value is specified on daemon start, on Windows client,
The actual values should be monospaced and this could probably use some rewording in general.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          Path to the docker-init binary.
mono space

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          If only the binary name, not a full path is configured, the daemon
Reword. Something like "If the path is omitted, the daemon searches the `PATH` variable for the binary and uses the first result."

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          List of security features that are enabled on the daemon, such as
Is this Linux-specific?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          > registry. However, because its use creates security vulnerabilities
This paragraph is weird. You start by talking about registries in the plural and then switch to singular (it). Might need some rewording.

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          List of registries URLs that act as a mirror for the official
registry URLs

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +      IndexInfo contains information about a registry
Missing period

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          - "https://hub-mirror.corp.example.com:5000/"
Does this work, having three different examples? Did you mean to include a `|`?

2017-08-11 17:24 UTC, mstanleyjones commented on api/swagger.yaml
> +          If only the binary name is configured, the daemon looks for a binary
Same rewording request as above.

2017-08-11 19:05 UTC, thaJeztah commented on api/swagger.yaml
> +          Date/time at which the node was added to the swarm in
Yes it is, actually didn't realize it's ambiguous, ha! Ill update

2017-08-14 23:27 UTC, thaJeztah commented on api/swagger.yaml
> +          - [" swarm-master", "192.168.99.101:2376"]
Ah, yes; I had to quickly setup a legacy swarm cluster to check the responses, and copied the responses from the quickstart, which appears to use `"master"` for the manager node :smile:; https://docs.docker.com/swarm/install-w-machine/#launch-the-swarm-manager. I'll update the example output

2017-08-14 23:30 UTC, thaJeztah commented on api/swagger.yaml
> +          [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.
I don't think it's Linux specific https://github.com/golang/go/blob/f9cf8e5ab11c7ea3f1b9fde302c0a325df020b1a/src/net/http/transport.go#L250-L300

2017-08-14 23:34 UTC, thaJeztah commented on api/swagger.yaml
> +          List of security features that are enabled on the daemon, such as
Windows currently doesn't have security options, so this list would be empty; I can add a note about that

2017-08-15 00:42 UTC, thaJeztah commented on api/swagger.yaml
> +        default: "/var/lib/docker"
Let me remove the default; the default is different for each platform, and the swagger spec won't allow me expressing that

2017-08-15 00:57 UTC, thaJeztah commented on api/swagger.yaml
> +          - "https://hub-mirror.corp.example.com:5000/"
No this is correct; you can configure multiple mirrors for Docker Hub

2017-08-15 10:44 UTC, thaJeztah commented
@mstanleyjones updated, PTAL

2017-08-15 16:59 UTC, thaJeztah commented
Looks like there was an issue with Docker Hub search. Reminds me we need to rewrite that test to not rely on Hub;

```
10:16:12 ----------------------------------------------------------------------
10:16:12 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
10:16:12 
10:16:12 docker_cli_search_test.go:72:
10:16:12     c.Assert(outSearchCmdOfficialSlice, checker.HasLen, 3) // 1 header, 1 line, 1 carriage return
10:16:12 ... obtained []string = []string{"NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED", ""}
10:16:12 ... n int = 3
10:16:12 
```

2017-08-15 21:55 UTC, mdlinville approved these changes

2017-08-15 21:55 UTC, mstanleyjones commented
Approved even though it looks like there might be a few things still pending.

2017-08-16 12:28 UTC, thaJeztah commented
Failure on `z` is not related; https://jenkins.dockerproject.org/job/Docker-PRs-s390x/5080/console

```
09:24:32 --- FAIL: TestFrequency (0.21s)
09:24:32 	splunk_test.go:891: Unexpected number of requests 7
09:24:32 time="2017-08-16T09:24:19Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:19Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:19Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:19Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"0\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.655946\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"1\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.655974\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"0\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.718288\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"1\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.718302\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="splunk: failed to send event - 500 Internal Server Error - " 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"2\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.718303\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"3\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.718616\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 time="2017-08-16T09:24:20Z" level=error msg="Failed to send a message '{\"event\":{\"line\":\"4\",\"source\":\"stdout\",\"tag\":\"containeriid\"},\"time\":\"1502875460.718619\",\"host\":\"9e7b271ec137\"}'" 
09:24:32 FAIL
```

All others are green; author LGTM

2017-08-16 12:29 UTC, merged