Add Init API field documentation to swagger
moby/moby pull request #34655
Opened 2017-08-28 20:33 UTC by nmeyerhans

The API documentation is missing a description of the "Init" HostConfig setting. This change corrects that omission. The text of the Init description is copied from the `docker run --help` output's description of the `--init` flag.

Tested with `make swagger-docs`

2017-09-12 07:28 UTC, vdemeester approved these changes
LGTM 🐮

2017-09-12 10:03 UTC, thaJeztah requested changes
Thanks @nmeyerhans! I left some comments; no real show-stoppers, but let me know what you think 👍

2017-09-12 10:03 UTC, thaJeztah commented on api/swagger.yaml
> +        type: "boolean"
Thanks for spotting this!

Looking at the code:

https://github.com/moby/moby/blob/bb6fc72cd2bd0f194940c7710d8ed8cf3fb99d21/api/types/container/host_config.go#L383-L384

We may want to add that

- the default (as configured on the daemon) is used if this field is omitted / null
- that the field is nullable ([`x-nullable: true`](https://github.com/moby/moby/blob/28362f11d73b5b72ff9d7eba27cf9f817ec86ef8/api/swagger.yaml#L934))
- perhaps mention something like "this field is omitted if empty" (or "this field is omitted if not set")

2017-09-12 21:45 UTC, mstanleyjones commented
Will this need to be backported? If so, how far?

2017-09-13 10:08 UTC, thaJeztah commented
> Will this need to be backported? If so, how far?

Yes, we can look at back porting this. Perhaps we should also consider _copying_ the swagger.yaml with each version change (`swagger-v1.30.yaml`, `swagger-v1.29.yaml`) to make this easier (also for the docs).

2018-01-10 20:41 UTC, cpuguy83 commented
paging @nmeyerhans

2018-01-19 23:12 UTC, vdemeester commented
@mistyhacks @nmeyerhans @thaJeztah rebased and took @thaJeztah into account 😉

2018-01-23 19:03 UTC, mdlinville approved these changes

2018-01-23 19:04 UTC, cpuguy83 approved these changes
LGTM

@thaJeztah LGTY?

2018-01-24 08:38 UTC, thaJeztah approved these changes
LGTM

we should also add this to the API version history (don't think it's listed there)

2018-01-24 08:39 UTC, thaJeztah commented
oh, actually; looks like the script needs to be run again;

```
23:17:35  M api/types/container/container_wait.go
23:17:35 
23:17:35 Please update api/swagger.yaml with any api changes, then 
23:17:35 run `hack/generate-swagger-api.sh`.
```

ping @vdemeester

2018-01-25 18:16 UTC, yongtang commented
All test passed 👍 merging.

2018-01-25 18:16 UTC, merged

2018-01-25 18:46 UTC, yongtang commented
Sorry my bad. Didn't see comment from @thaJeztah about updating API version history.

Created a follow up PR #36116 for that.