add an exception case
moby/moby pull request #34689
Opened 2017-08-31 04:34 UTC by chchliang

Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>

Add an exception case in this testcase.

2017-08-31 06:12 UTC, chchliang commented
@GordonTheTurtle

there is no association with changes here.

04:39:00 --- FAIL: TestStateTimeoutWait (0.20s)
04:39:00 	state_test.go:137: Stop callback doesn't fire in 200 milliseconds
04:39:00 FAIL
04:39:00 coverage: 28.0% of statements
04:39:00 FAIL	github.com/docker/docker/container	0.225s

2017-08-31 06:37 UTC, AkihiroSuda requested changes

2017-08-31 06:37 UTC, AkihiroSuda commented on opts/env_test.go
> +		"=a":                  fmt.Sprintf("invalid environment variable: %s", "=a"),
It is really weird to let `valids` map contain invalid values.
Let's use structs.

2017-08-31 06:55 UTC, chchliang commented
func ValidateEnv(val string) (string, error) {
	arr := strings.Split(val, "=")
	if arr[0] == "" {
		return "", errors.Errorf("invalid environment variable: %s", val) //here never reach in this testcase
	}
	if len(arr) > 1 {
		return val, nil
	}
	if !doesEnvExist(val) {
		return val, nil
	}
	return fmt.Sprintf("%s=%s", val, os.Getenv(val)), nil
}

In this method `ValidateEnv`,i see this test case never reach the exception branch,so i add some  invalid values to map.

2017-08-31 07:00 UTC, chchliang commented
Ok,i use struct replace map, thanks.
@AkihiroSuda

2017-08-31 10:31 UTC, AkihiroSuda requested changes

2017-08-31 10:31 UTC, AkihiroSuda commented on opts/env_test.go
> +	valids := []struct {
testCases := []struct{
  value string
  expected string
  err error
}

2017-09-01 02:12 UTC, AkihiroSuda commented on opts/env_test.go
> +			expected: fmt.Sprintf("invalid environment variable: %s", "=a"),
When `err` is nil, `expected` should be empty

2017-09-01 04:08 UTC, AkihiroSuda commented on opts/env_test.go
>  		}
if err != r.err { t.Fatalf("Expected err ...", ...) }

2017-09-01 07:30 UTC, AkihiroSuda commented on opts/env_test.go
>  		}
Make sure it fails when `err == nil && r.err != nil`

2017-09-01 08:57 UTC, AkihiroSuda approved these changes
LGTM if green

2017-09-01 16:50 UTC, tonistiigi commented
LGTM

2017-09-01 17:53 UTC, yongtang approved these changes
LGTM

2017-09-01 17:53 UTC, merged