change variable
moby/moby pull request #34727
Opened 2017-09-04 18:54 UTC by Anfar234

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-09-04 18:54 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-1" git@github.com:Anfar234/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-09-05 00:24 UTC, AkihiroSuda requested changes
We don't need this change

2017-09-05 01:10 UTC, duglin commented
why did you want to make this change?

2017-09-05 07:36 UTC, vdemeester commented
Agreeing with @AkihiroSuda @duglin we don't need that change, closing. Thanks for the contribution though 👼

2017-09-05 07:36 UTC, closed without merging