should use time.Since instead of time.Now().Sub
moby/moby pull request #34738
Opened 2017-09-06 08:56 UTC by wgliang

**- What I did**
use time.Since instead of time.Now().Sub
**- How I did it**
use time.Since instead of time.Now().Sub
**- How to verify it**
NONE
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-09-06 08:56 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "optimization1" git@github.com:wgliang/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-09-06 09:05 UTC, AkihiroSuda approved these changes
LGTM

2017-09-06 09:58 UTC, AkihiroSuda commented on integration-cli/docker_api_containers_test.go
> +	case waiters := <-waitresC:
No, "waitres" (wait result) is correct

2017-09-06 09:59 UTC, AkihiroSuda requested changes
Also, please update the title of the PR

2017-09-06 10:03 UTC, wgliang commented on integration-cli/docker_api_containers_test.go
> +	case waiters := <-waitresC:
Get！

2017-09-06 10:05 UTC, wgliang commented
I've updated it.

2017-09-06 12:21 UTC, boaz0 approved these changes
LGTM! GJ

2017-09-06 14:40 UTC, dnephin approved these changes
LGTM

2017-09-06 14:42 UTC, AkihiroSuda approved these changes
LGTM

2017-09-06 16:21 UTC, ripcurld0 commented
@wgliang can you update the commit title to be the same as the title of the PR?

Thanks.

2017-09-07 01:46 UTC, wgliang commented
@ripcurld0 Ok,I've updated it.

2017-09-07 04:16 UTC, lowenna approved these changes
LGTM

2017-09-07 16:45 UTC, merged