Update names-generator.go
moby/moby pull request #35250
Opened 2017-10-19 14:38 UTC by joppich

added cédric villani and laika kudryavka to names list.

![laika_ soviet_dog](https://user-images.githubusercontent.com/12008491/31776495-fe93c064-b4eb-11e7-9883-72b0d42fa2a1.jpg)

2017-10-19 14:40 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-1" git@github.com:joppich/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-10-25 19:03 UTC, cpuguy83 commented
It seems a little off to include a dog here... Can you find a human woman to replace the dog?
Can you also be sure to include a wikipedia link?

2017-10-25 21:26 UTC, thaJeztah requested changes

2017-10-25 21:26 UTC, thaJeztah commented on pkg/namesgenerator/names-generator.go
> +		// Cédric Villani - French mathematician, won Fields Medal, Fermat Prize and Poincaré Price for his work in differential geometry and statistical mechanics
Can you add a link with more information as well (e.g. to wikipedia, as is used for other names?)

2017-10-27 09:37 UTC, thaJeztah requested changes
Thank you for updating! Can you:

- Squash your commits, so that there's only a single commit in this PR
- Update the commit message to match the changes?
- Update your sign-off to [include your real name, not your GitHub handle](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work) 😅 

LGTM after that's done 👍

2017-10-30 17:17 UTC, thaJeztah commented
oh, looks like you have to `gofmt` the file;

```
12:13:01 pkg/namesgenerator/names-generator.go:1::warning: file is not goimported (goimports)
12:13:01 pkg/namesgenerator/names-generator.go:1::warning: file is not gofmted with -s (gofmt)
12:13:02 Build step 'Execute shell' marked build as failure
```

2017-11-08 05:08 UTC, AkihiroSuda commented
CI green

@thaJeztah LGTY?

2017-11-08 09:13 UTC, thaJeztah approved these changes
LGTM, thanks!

2017-11-09 14:20 UTC, yongtang approved these changes
LGTM, thanks!

2017-11-09 14:21 UTC, merged