rmLink: fix parsing name with /
moby/moby pull request #35270
Opened 2017-10-23 07:25 UTC by keloyang

Run a container with "--link container:somethingA/somethingB", then rm the link, we will see a err like this,
```
Error response from daemon: Cannot get parent **for name ***
```

### How to reproduce
```
# runc two containers
docker run -d -ti --name aaa busybox sleep 10000000   
docker run -d -ti --name bbb --link aaa:linka/hello busybox sleep 1000000

[root@localhost ~]# docker ps  --no-trunc 
CONTAINER ID                                                       IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
d4065c5608f24a6ff9e7633d5aca27771a05b40cfee79036b8179848f5993308   busybox             "ash"               2 seconds ago       Up Less than a second                       bbb
f996150fa7597d4bb142626e058259435728ebfb1889710e6d679eb72ed52c79   busybox             "ash"               10 seconds ago      Up 7 seconds                                aaa,bbb/linka/hello
[root@localhost ~]# docker rm -l bbb/linka/hello
Error response from daemon: Cannot get parent linka for name /bbb/linka/hello
```

### Why
With "--link container:somethingA/somethingB", docker should parse "parent"( parent, n := path.Split(name)) to "/container", not "/container/somethingA".

### After this pr
```
[root@localhost ~]# docker ps --no-trunc 
CONTAINER ID                                                       IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
74376ac54f93a114f7f835061a1d5b15d13f01c41b8cc51043133944b20aed0c   busybox             "ash"               4 seconds ago        Up 2 seconds                            bbb
6ab1881806a0ac4e293b0cc049d0bc5f6f6b0f646099c6cb747589d2103c7479   busybox             "ash"               11 seconds ago       Up 9 seconds                            aaa,bbb/linka/hello
[root@localhost ~]# docker rm -l bbb/linka/hello
bbb/linka/hello
[root@localhost ~]# docker ps --no-trunc        
CONTAINER ID                                                       IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
74376ac54f93a114f7f835061a1d5b15d13f01c41b8cc51043133944b20aed0c   busybox             "ash"               15 seconds ago       Up 13 seconds                           bbb
6ab1881806a0ac4e293b0cc049d0bc5f6f6b0f646099c6cb747589d2103c7479   busybox             "ash"               22 seconds ago       Up 20 seconds                           aaa
```
Signed-off-by: yangshukui <yangshukui@huawei.com>

2017-10-23 13:29 UTC, cpuguy83 requested changes
Can we factor this out and make a test for it?

2017-10-23 13:29 UTC, cpuguy83 commented on daemon/delete.go
> +	sep := string(os.PathSeparator)
This should always be `/` rather than `os.Pathseparator`

2017-10-25 01:04 UTC, keloyang commented
ping @cpuguy83 @LK4D4 @dnephin @tonistiigi

2017-10-26 15:30 UTC, thaJeztah commented
Is linking with a slash in the link-name actually meant to be supported? As far as I'm aware it's only meant to be used as `--link <name or id>:alias` https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#communication-across-links

2017-10-26 18:51 UTC, cpuguy83 commented
So this is a bit strange.
It looks like the issue is that `--link` is allowing you to create an alias which is effectively a container name (since the system lets you address aliases this way) but yet the alias does not get the same validation as container names.

The correct thing to do would be to validate aliases the same way we validate container names, however we could end up breaking a lot of people at this point.

2017-10-27 02:57 UTC, keloyang commented
```
--link <name or id>:alias
```
@thaJeztah The  case is alias has a  slash, e.g. name:aliaspart1/aliaspart2, and the doc don't limit the alias.

@cpuguy83 Take "--link containername:aliaspart1/aliaspart2" for example, in the original code, using path.Split,  name does not get the same validation as container names,  it get "/containername/aliaspart1", its' wrong , and the correct name is "/containername". I think this pr  validate name:aliases the same way as validate container name and it will fix the issue that alias has a slash. but I don't know why it breaking a lot of people, it don't break any original interface. PTAL, thank you very much.

2017-10-27 02:57 UTC, keloyang commented
```
--link <name or id>:alias
```
@thaJeztah The  case is alias has a  slash, e.g. name:aliaspart1/aliaspart2, and the doc don't limit the alias.

@cpuguy83 Take "--link containername:aliaspart1/aliaspart2" for example, in the original code, using path.Split,  name does not get the same validation as container names,  it get "/containername/aliaspart1", its' wrong , and the correct name is "/containername". I think this pr  validate name:aliases the same way as validate container name and it will fix the issue that alias has a slash. but I don't know why it breaking a lot of people, it don't break any original interface. PTAL, thank you very much.

2017-10-27 13:38 UTC, cpuguy83 commented
@keloyang I'm saying that using an alias with a `/` in it should not be allowed. These aliases are treated just like names throughout the codebase so should have the same restrictions as full container names.

2017-10-28 08:38 UTC, keloyang commented
@cpuguy83 I add a  restriction for alias that  alias don't contain a slash.

2017-10-30 14:39 UTC, thaJeztah commented
I had to think twice as well, as this was a bit confusing; so the behaviour is basically;

```
--link <container>:<alias>
```

Doing so may create an _internal_ name for the link that's named `/container/alias`, but it's not allowed  to _create_ an alias with that name (because the `alias` is also used as hostname for the link; i.e., inside the container I can `curl <alias>`.

2017-10-30 14:40 UTC, thaJeztah commented on daemon/daemon.go
> +	aliasChecker := alias
Aliases should probably follow the same rules as container names, and I think we'd already have a function for that to validate those

2017-11-01 01:02 UTC, keloyang commented
ping @thaJeztah @cpuguy83

2018-11-27 00:37 UTC, cpuguy83 commented
I'm not sure if this new validation is worth the cost of breaking people... it looks like it even broke a test in this repo.

2021-01-05 07:24 UTC, closed without merging