Permit a broader range of errors from mirror endpoints when determining whether to fall back
moby/moby pull request #35376
Opened 2017-11-02 01:44 UTC by KingEmet

This change has 2 primary effects:
* Allow for continueOnError to disambiguate mirror -> other endpoint fallbacks from V2 -> V1 fallbacks.
* Begin allowing for a wider range of failures from mirror endpoints to result in fallbacks

The goal is to allow for higher pull availability.

Signed-off-by: Jake Sanders <jsand@google.com>

![what kind of fruit is this](https://i.redd.it/45qkgqs53avz.jpg)

2017-11-03 03:07 UTC, aaronlehmann reviewed
Seems fine to me. I wonder if 404s on blobs should fall back to the canonical repo as well.

2017-11-03 04:24 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:KingEmet/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354636672
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-11-03 04:31 UTC, KingEmet commented
agreed, added that check for all docker/distribution/registry/api/errcode.Errors from mirror endpoints

2017-11-07 00:47 UTC, KingEmet commented
Ping (looks like signing the commit killed the janky test)

2017-11-07 14:16 UTC, vdemeester approved these changes
LGTM 🐮

2017-11-07 22:27 UTC, KingEmet commented
commits squashed

2017-11-09 00:24 UTC, thaJeztah approved these changes
LGTM

2017-11-09 19:52 UTC, stevvooe commented
LGTM on design

As far as I understand this change, it just lets us continue on what were previously terminal errors when interacting with a known mirror.

2017-11-09 19:53 UTC, stevvooe commented on distribution/errors_test.go
> +func TestContinueOnError(t *testing.T) {
While I am not sure if we have a better way of testing this, this kind of unit is just testing the implementation detail of the package. This kind of test makes it harder or impossible to refactor in the future.

Is there another way we could setup this test?

If this is the only way, it should at least be a table-based test.

2017-11-09 19:54 UTC, stevvooe requested changes
Please address the issues with the unit test.

2017-11-10 21:49 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:KingEmet/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354101072
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-11-10 22:07 UTC, thaJeztah commented
Looks like something went wrong during rebasing

2017-12-01 03:56 UTC, KingEmet commented
Sorry about that, should be good now.

2017-12-04 21:45 UTC, stevvooe approved these changes

2017-12-04 21:49 UTC, thaJeztah commented
Thanks! Moving to "merge"; I'll restart Janky, which failed due to some Jenkins issue

2017-12-04 21:53 UTC, thaJeztah commented
Don't merge yet; was discussing with @stevvooe, and he preferred @dmcgowan to have a quick peek as well 👍

2017-12-04 21:58 UTC, dmcgowan commented
LGTM

2017-12-05 00:46 UTC, KingEmet commented
Fixed golint errors...

2017-12-05 00:48 UTC, KingEmet commented
Janky is still being... janky...

2017-12-05 01:55 UTC, thaJeztah commented
Looks like there's some issues with Jenkins indeed; lots of PR's fail directly 😞

2017-12-05 02:49 UTC, KingEmet commented
I'm guessing the TestEventsOOMDisableTrue failure is a flake? Doesn't seem related

2017-12-05 02:54 UTC, thaJeztah commented
Should not be related no, but not sure I've seen that one fail recently (last mention if it was optimising that test https://github.com/moby/moby/pull/19619)

https://jenkins.dockerproject.org/job/Docker-PRs-s390x/7127/console

```
01:19:04 PASS: docker_cli_events_unix_test.go:51: DockerSuite.TestEventsOOMDisableFalse	0.451s
01:19:05 
01:19:05 ----------------------------------------------------------------------
01:19:05 FAIL: docker_cli_events_unix_test.go:81: DockerSuite.TestEventsOOMDisableTrue
01:19:05 
01:19:05 docker_cli_events_unix_test.go:125:
01:19:05     c.Assert(strings.TrimSpace(status), checker.Equals, "running", check.Commentf("container should be still running"))
01:19:05 ... obtained string = "exited"
01:19:05 ... expected string = "running"
01:19:05 ... container should be still running
01:19:05 
```

ping @tophj-ibm ^^

2017-12-05 03:01 UTC, KingEmet commented
kk, was passing and hope that the golint fix didn't KO it ¯\_(ツ)_/¯

2017-12-06 09:22 UTC, thaJeztah commented
All green now 🎉

2017-12-06 09:23 UTC, merged