Replace 'precpu' with 'percpu' in API docs.
moby/moby pull request #35410
Opened 2017-11-05 17:45 UTC by soulshake

**- What I did**

Replace `precpu` with `percpu` in `docs/api/*.md`.

**- How to verify it**

Compare output of:

- `curl "localhost:4243/containers/$CID/stats?stream=false" | jq .cpu_stats.cpu_usage.precpu_usage`
- `curl "localhost:4243/containers/$CID/stats?stream=false" | jq .cpu_stats.cpu_usage.precpu_usage`

**- Description for the changelog**

Docs should refer to `percpu_stats`, not `precpu_stats`.

**- A picture of a cute animal (not mandatory but encouraged)**

![image](https://user-images.githubusercontent.com/1585815/32417398-0e309dec-c20e-11e7-857d-a577c20091f2.png)

2017-11-05 17:45 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "soulshake-precpu-to-percpu-api-docs" git@github.com:soulshake/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2017-11-05 18:03 UTC, thaJeztah commented on docs/api/version-history.md
> +* `GET /containers/(id or name)/stats` now includes an `online_cpus` field in both `percpu_stats` and `cpu_stats`. If this field is `nil` then for compatibility with older daemons the length of the c
I know this confused me a couple of times as well, but I think `precpu_..` is correct; https://github.com/moby/moby/blob/2c6a1e1878975550cd2e7a98494773903e39eaf7/api/types/stats.go#L168

2017-11-05 18:16 UTC, soulshake commented
@thaJeztah Whoops, you are totally right.

Please accept a humble offering in the form of this updated PR if you think anyone might be as bad as me at reading in the future :)

Otherwise feel free to close this. <3

2017-11-05 23:07 UTC, boaz0 approved these changes
LGTM 🏆

2017-11-14 15:03 UTC, justincormack commented
@soulshake please can you amend and sign off your commit again?

2017-11-14 15:13 UTC, thaJeztah requested changes
oh, whoops, forgot about this one (marked it as "read" by opening on my phone 😞): can you; also make the same changes to the Swagger file (which is used to render the current version of the API documentation)? https://github.com/moby/moby/blob/master/api/swagger.yaml#L5069-L5071

> Please accept a humble offering in the form of this updated PR if you think anyone might be as bad as me at reading in the future :)

Haha, no apologies needed, at all: it's definitely a confusing choice of words for this property (but accepting to have a drink next time I'll see you 😇)

2017-11-14 15:13 UTC, thaJeztah commented on docs/api/v1.19.md
> +The `precpu_stats` is the cpu statistic of **pre**vious read, which is used for calculating the cpu usage percent. It is not the exact copy of the `cpu_stats` field.
nit-picky; perhaps we should emphasize the whole word;

```Markdown
The `precpu_stats` is the cpu statistic of *previous* read, which is used for calculating the cpu usage percent. It is not the exact copy of the `cpu_stats` field.
```

2017-11-21 01:09 UTC, stevvooe commented
@soulshake Could you address @thaJeztah's comments? ;) thanks!

2018-02-16 15:48 UTC, vdemeester commented
@soulshake @thaJeztah rebased and took care of the comments 👼 😉

2018-02-16 17:59 UTC, soulshake commented
Oh jeez, thank you @vdemeester @thaJeztah and sorry for the inattention on my part </3

2018-05-15 12:08 UTC, thaJeztah approved these changes
lol, rebased again 😊 

LGTM

2018-05-17 12:54 UTC, thaJeztah commented
lol - let me update (again)

```
19:00:11 api/swagger.yaml
19:00:11   5099:76   error    trailing spaces  (trailing-spaces)
```

2018-05-18 15:26 UTC, merged