Restore hack/make/test-unit for "make test"
moby/moby pull request #35547
Opened 2017-11-20 10:59 UTC by thaJeztah

fixes https://github.com/moby/moby/issues/35540

Commit https://github.com/moby/moby/pull/34911/commits/dbf580be57a4bb854d7ce20d313e3a22ea337be5 (https://github.com/moby/moby/pull/34911) removed
this helper script because it's no longer used in CI.

However, the `make test` target in the Makefile still called this helper, resulting it to fail.

ping @dnephin @vdemeester PTAL

2017-11-20 16:00 UTC, dnephin requested changes
How about this change instead?

```diff
diff --git a/Makefile b/Makefile
index db7056f..3298815 100644
--- a/Makefile
+++ b/Makefile
@@ -158,8 +158,8 @@ run: build ## run the docker daemon in a container
 shell: build ## start a shell inside the build env
 	$(DOCKER_RUN_DOCKER) bash
 
-test: build ## run the unit, integration and docker-py tests
-	$(DOCKER_RUN_DOCKER) hack/make.sh dynbinary cross test-unit test-integration test-docker-py
+test: build test-unit ## run the unit, integration and docker-py tests
+	$(DOCKER_RUN_DOCKER) hack/make.sh dynbinary cross test-integration test-docker-py
 
 test-docker-py: build ## run the docker-py tests
 	$(DOCKER_RUN_DOCKER) hack/make.sh dynbinary test-docker-py
```

2017-11-20 18:10 UTC, thaJeztah commented
Ah, yes, I thought about that; wasn't sure if we wanted to keep the order of execution (build first, then unit-tests). I'm okay updating to that 👍

2017-11-20 18:13 UTC, thaJeztah commented
updated 👍

2017-11-20 18:18 UTC, dnephin approved these changes
LGTM

2017-11-21 09:49 UTC, vdemeester approved these changes
LGTM 🐯

2017-11-21 09:49 UTC, merged