image: decrease the size of image imported
moby/moby pull request #35572
Opened 2017-11-22 10:59 UTC by arm64b

The commit '0a13f827a10d3bf61744d9b3f7165c5885a39c5d' introduces an
import test for CVE-2017-14992, it uses a 8GB image to make sure we
don't revert CVE-2017-14992, but unfortunately this test can't finish
in 5 mins on AArch64, so the consequent panic of this test will terminate
all the integration tests followed.

This PR decrease the size from 8GB to 6GB on AArch64 to mitigate the
preformance relevant issue, thus we can continue all other tests on
AArch64.

Signed-off-by: Dennis Chen <dennis.chen@arm.com>

**- What I did**
Fix the panic of 'TestImportExtremelyLargeImageWorks' case
**- How I did it**
Make the image can be finished within 5 mins by decreasing the size from 8GB to 6GB
**- How to verify it**
`make test-integration` and the `TestImportExtremelyLargeImageWorks` passed and continue the following tests.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2017-11-22 17:11 UTC, thaJeztah commented
Wonder if 6GB would be enough to test this on all platforms

2017-11-23 06:08 UTC, arm64b commented
> Wonder if 6GB would be enough to test this on all platforms

I've tested it on the 3 mainstream AArch64 server platforms: Cavium ThunderX, Qualcomm Centriq2400 and Huawei D05, all those can pass this tests. Of course, given the range of AArch64 is so huge, I test it with less performance power processor A53, it also can pass this. So I think 6GB should be OK for almost all the AArch64 platforms.  Relevant: #35075

2017-11-23 10:02 UTC, thaJeztah commented
Oh! I actually meant: wondering if (instead of changing the size just for Aarch64), to just change the size; if the test is still valid with the smaller size (on any arch), we could just do that :smile:

I know the size was tweaked a bit to make it work (see https://github.com/moby/moby/pull/35424#issuecomment-342564288), so perhaps smaller would still be ok (/cc @cyphar)

2017-11-23 10:29 UTC, cyphar commented
The size needs to be big enough to trigger an OOM or memory over-commitment, which depends on teh system the test is running.

2017-11-23 10:51 UTC, arm64b commented
> The size needs to be big enough to trigger an OOM or memory over-commitment, which depends on the system the test is running.

So the what I am curious is how to figure out the size is big enough to trigger an OOM or over-commitment, I take a look at #35424, seems you are tweaking the size from 20G to 8G, is there some implicit approach to finalize the size.  On AArch64, I am pretty sure if the size is 8G, the 3 server platforms can't complete the test (it takes about 5~6 mins), so I isolate the AArch64 from this test and give it a 6GB size which can make us pass this test and continue  :-). Any suggestions?
(/cc @thaJeztah )

2017-11-23 11:00 UTC, arm64b commented
BTW, the system memory in Huawei D05 and Cavium ThunderX is 128G, Qualcomm Centriq2400 is 96G 😄

2017-11-23 13:05 UTC, cyphar commented
If you want to test it locally, you could try running just that test with different values and with the fix #35424 removed. The key part of the value is it must be large enough for the test to fail if the fix is removed. Otherwise the test isn't testing anything.

2017-11-23 16:26 UTC, thaJeztah commented
Hm, so this is tricky indeed, because it depends on the host. Was thinking of setting the size based on available memory, but creating a `128G+` load just for this test may be a bit too much 😂.

2017-11-23 17:11 UTC, dnephin commented
I would say just skip the test on any platform where it is slow by adding a `t.Skip()`.

2017-11-24 07:16 UTC, arm64b commented
I sadly find that I am in a dilemma condition: I do trigger the issue with a very very large image when removing the fix #35424, but absolutely the test will time out if I use that size😂. So I think @dnephin 's suggestion is reasonable, we can skip this test on AArch64 but keep others intact. Forcing the update ...

2017-11-27 06:36 UTC, arm64b commented
hmm, all the checks passed. 
/cc @thaJeztah @dnephin  @cyphar @yongtang , hello guys, I am pushed by my colleagues who are working on the Moby CI on AArch64 for the CI pipeline has been broken now 😄 , so would you please give me a hand to see if it's ready to go or changes needed?

2017-11-27 14:26 UTC, dnephin approved these changes
LGTM

2017-11-27 14:26 UTC, dnephin commented on integration/image/import_test.go
> +	}
I would move this to the first line of the function.

2017-11-27 18:31 UTC, vdemeester requested changes
LGTM with @dnephin's comment taken into account 👼

2017-11-28 01:51 UTC, arm64b commented
Thanks @dnephin and @vdemeester ! The latest update has pushed...👼

2017-11-28 12:51 UTC, vdemeester approved these changes
LGTM 🐮

2017-11-28 12:51 UTC, merged