35012 limit build io
moby/moby pull request #35682
Opened 2017-12-02 23:19 UTC by bealerj2260

Closes #35012 

**- What we did**
Added the six options to limit read/write speeds to a device that are present in docker run to docker build. There will need to be cli changes to use this feature. We have already completed that work and will open a PR against the cli repo once this gets merged (or earlier if maintainers would prefer that). 

**- How I did it**
Added the additional parameters to the build options, and host config. 

**- How to verify it**
This has been difficult to verify as limiting the block devices is not easily observable for some reason, but you can see that the limits are applied to the build container by checking the cgroup in your docker system files `/sys/fs/cgroup/blkio/docker/<container_long_id>/blkio.throttle.<command-name>`.

**- Description for the changelog**
Add device throttle options to docker build

2017-12-06 00:32 UTC, kolyshkin requested changes

2017-12-06 00:32 UTC, kolyshkin commented on api/types/client.go
> +	BlkioWriteIOpsDevice string
Perhaps drop the `Device` suffix, as it looks redundant and doesn't add any more clarity.

2017-12-06 00:32 UTC, kolyshkin commented on builder/dockerfile/internals.go
> +	if strings.HasSuffix(configuration[1], "kb") {
This is basically repeating the functionality of [docker/go-units](https://github.com/docker/go-units), which is used by other similar places. Please use it here, too.

2017-12-14 01:15 UTC, bealerj2260 commented
@kolyshkin Sorry for the delay! I've renamed those fields and made use of the library that you mentioned.

2018-12-22 14:35 UTC, olljanat commented
Derek add label: status/failing-ci

2019-07-16 16:03 UTC, thaJeztah commented
Looks like this went stale, and we're not sure if this is something to add or too much bells and whistles, so I'll close this one for now. Feel free to continue the conversation if there's strong reasons for adding this functionality

2019-07-16 16:03 UTC, closed without merging