Update CRIU version in the shell Dockerfile
moby/moby pull request #35695
Opened 2017-12-04 19:30 UTC by boucher

CRIU needs a newer version to work with the updates pulled in by containerd 1.0

Signed-off-by: Ross Boucher <rboucher@gmail.com>

2017-12-04 20:53 UTC, thaJeztah approved these changes
LGTM

ping @kolyshkin PTAL

2017-12-04 22:24 UTC, kolyshkin commented
@boucher can you please also
* remove `-v` option from tar invocation;
* remove `apt-get install libnet-dev` (and the preceding comment) and add `libnet-dev` to the list at the beginning of the file (where all the other criu deps are living anyway)

2017-12-04 22:25 UTC, kolyshkin requested changes
@boucher can you please also
* remove `-v` option from tar invocation;
* remove `apt-get install libnet-dev` (and the preceding comment) and add `libnet-dev` to the list at the beginning of the file (where all the other criu deps are living anyway)

2017-12-04 22:26 UTC, kolyshkin requested changes

2017-12-04 22:26 UTC, kolyshkin commented on Dockerfile
> -
remove this hunk

2017-12-04 22:46 UTC, boucher commented
Done

2017-12-04 23:32 UTC, kolyshkin commented
LGTMThank you, Ross!

2017-12-04 23:37 UTC, kolyshkin commented
@boucher I am very sorry, totally forgot it that we moved github repo to https://github.com/checkpoint-restore/criu/; can you please change the download URL accordingly?

2017-12-04 23:42 UTC, kolyshkin commented
This might also fix https://github.com/moby/moby/issues/35235

2017-12-05 21:40 UTC, kolyshkin approved these changes
LGTM

2017-12-05 21:48 UTC, yongtang approved these changes
LGTM

2017-12-05 21:49 UTC, merged