devmapper: Log fstype and mount options during mount error
moby/moby pull request #35732
Opened 2017-12-07 16:10 UTC by rhvgoyal

Right now we only log source and destination (and demsg) if mount operation
fails. fstype and mount options are available easily. It probably is a good
idea to log these as well. Especially sometimes failures can happen due to
mount options.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

2017-12-07 16:17 UTC, rhvgoyal commented
I have heard some reports of error saying mount failed and only error message seems to be "invalid argument". I am also curious to know what mount options were used for mount calls. That's why enhancing the error message to output more debug information.

2017-12-07 16:18 UTC, rhvgoyal commented
https://github.com/openshift/origin/issues/17330

2017-12-07 18:50 UTC, runcom commented
:+1:

2017-12-07 22:14 UTC, thaJeztah commented
Note that this will be less of a problem with https://github.com/moby/moby/pull/35514 merged (but could still be useful for existing installs). Also see https://github.com/moby/moby/pull/35527, which may be of interest as well :innocent:

2017-12-07 22:16 UTC, thaJeztah commented
Nevermind, I was sleeping, this is devicemapper (got my head thinking due to interpreting `fstype` as `d_type` / `fs_type=1`)

2017-12-07 22:20 UTC, thaJeztah commented
Are there specific filesystems that cause issues? If so, are there filesystems that should be excluded, similar to https://github.com/moby/moby/blob/0a4e793a3da9ba6d20bccfb83f7c48e20a76d895/daemon/graphdriver/overlay/overlay.go#L140-L144 ?

2017-12-07 22:21 UTC, thaJeztah approved these changes
LGTM

2017-12-07 22:21 UTC, thaJeztah commented
/cc @kolyshkin

2017-12-08 13:24 UTC, rhvgoyal commented
@thaJeztah By the time we hit this error, we are only dealing with supported filesystems only. IOW, this error we will not hit for unsupported filesystems.

2017-12-08 21:56 UTC, kolyshkin requested changes

2017-12-08 21:56 UTC, kolyshkin commented on daemon/graphdriver/devmapper/deviceset.go
> +		return fmt.Errorf("Error mounting '%s' on '%s'. fstype=%s options=%s: %s\n%v", info.DevName(), fsMountPoint, devices.BaseDeviceFilesystem, options, err, string(dmesg.Dmesg(256)))
The punctuation looks strange. Perhaps change it to
```go
return fmt.Errorf("Error mounting '%s' on '%s' (fstype='%s' options='%s'): %s\n%v", info.DevName(), fsMountPoint, devices.BaseDeviceFilesystem, options, err, string(dmesg.Dmesg(256)))
```

2017-12-08 21:56 UTC, kolyshkin commented on daemon/graphdriver/devmapper/deviceset.go
> +		return fmt.Errorf("devmapper: Error mounting '%s' on '%s'. fstype=%s options=%s: %s\n%v", info.DevName(), path, fstype, options, err, string(dmesg.Dmesg(256)))
ditto

2017-12-11 18:28 UTC, rhvgoyal commented
@kolyshkin Took care of your comments. PTAL.

2017-12-11 20:28 UTC, kolyshkin approved these changes
LGTM

2017-12-11 22:37 UTC, vieux approved these changes
LGTM

2017-12-11 22:37 UTC, merged