Add storage options to build options
moby/moby pull request #35780
Opened 2017-12-13 00:54 UTC by johnstep

Signed-off-by: John Stephens <johnstep@docker.com>

This addresses builder support in the daemon needed for https://github.com/moby/moby/issues/34947, allowing storage options to be passed to the graph driver. Per that issue, the default Windows read-write layer size of 20 GB is too small in some cases. This allows it to be set per build instead of requiring global configuration.

2017-12-13 01:39 UTC, heaths commented on client/image_build.go
> +	storageOptJSON, err := json.Marshal(options.StorageOpt)
May want to add serialization tests to prevent regressions. I know some other options have them.

2017-12-13 01:41 UTC, thaJeztah commented
I know this came up in another PR, but should we limit this to just the `size` option, and not other options for now?

2018-01-03 22:00 UTC, jhowardmsft commented
@thaJeztah Yes, it has. We need this for a number of reasons, including for LCOW. Particularly though now due to some of the reexec issues some people are running into building large layers (where I'm going to bump the default size anyway after speaking to @johnstep offline).

2018-01-04 17:59 UTC, thaJeztah commented
Ah! yes, was discussing that option with @johnstep as well (on slack); shall we close this one in favour of https://github.com/moby/moby/pull/35925 ?

2018-01-04 21:32 UTC, heaths commented
Currently 127GB is plenty for what we need (Visual Studio Build Tools 2017), but it may not always be. While it's a great improvement and, by default, people won't need to change it, if more is needed do we then bump it again? IMO, allowing for storage options passed to `build` as to `run` (even if only a subset as you proposed above) is more flexible.

2018-01-05 00:36 UTC, darrenstahlmsft commented
+1 on being configurable beyond just expanding to 127GB. Also, https://github.com/moby/moby/pull/35925 is also only for changing the size of the RW layer created by RUN commands, not the size of layers created by COPY/ADD. I have a WIP branch that could build on top of this change to allow for large COPY/ADD step layers.

2018-01-20 01:19 UTC, PatrickLang commented
Is this also settable in the daemon config json?

2018-01-20 01:27 UTC, darrenstahlmsft commented
Prior to #35925, daemon config json/cmdline was the only way to change this. After #35925, it is not currently settable via daemon config json, as the 127GB set in the builder overwrites the daemon default.

This PR (plus a followup that I have) would still have it default to 127GB, but passing `storage-opt` to the build would overwrite that if present.

2018-01-20 01:42 UTC, heaths commented
I know that containers are laid out on disk via the filter driver, but is there any sort of max configured for them like VHDs? If so, I would prefer whatever was passed to the command line since its the most specific. If not, +1 on the idea to use the highest specified in either the daemon config or the command line.

2018-02-28 23:26 UTC, lowenna approved these changes
LGTM

2018-03-01 00:20 UTC, thaJeztah requested changes
I’d like more input from others regarding if we should limit options to “size” here

2018-03-08 20:09 UTC, thaJeztah commented
Discussing in the maintainers meeting, and looks like for Windows the issue is resolved by raising the default size, and for LCOW no issues have been raised that the size was too limited, so I'm in favour of closing

2018-03-08 20:09 UTC, closed without merging

2018-03-09 18:17 UTC, heaths commented
The new default - 127GB - is not large enough for some customers looking to install Visual Studio 2017 in a container. We are working to make Build Tools support more workloads, but in the meantime to containerize build via Visual Studio and fetch/build their sources, 127GB may not be enough.

The primary support is already in the support for running the intermediate containers. All this is really plumbing through an additional option. It should be low-risk, but provide customers with better options than having to reconfigure daemons they might not be able to control like in hosted solutions.

2018-03-09 21:55 UTC, darrenstahlmsft commented
I agree that this is necessary for certain workloads. At the very least, the size option should be configurable from the API imo.

2018-11-30 11:06 UTC, IvanBoyko commented
Which Docker for Windows versions got this change?

We use Docker **17.06.2-ee-17** on Windows Server 2016 and 1803.
It's the latest version in 17.06 branch.
And we still have only 20 Gb given to RUN instructions on `docker build`:
(see the line closer to the end - "21,268,504,576 bytes free")

```
PS > type .\Dockerfile
FROM microsoft/windowsservercore:ltsc2016
RUN cmd /c dir C:

PS > docker build --no-cache .
Sending build context to Docker daemon  17.92kB
Step 1/2 : FROM microsoft/windowsservercore:ltsc2016
 ---> 64d9bc839037
Step 2/2 : RUN cmd /c dir C:
 ---> Running in 35dc3262923d
 Volume in drive C has no label.
 Volume Serial Number is D0BA-FC3E

 Directory of C:\

11/22/2016  11:45 PM             1,894 License.txt
10/27/2018  12:08 AM    <DIR>          PerfLogs
11/30/2018  12:04 PM    <DIR>          Program Files
07/16/2016  02:18 PM    <DIR>          Program Files (x86)
11/30/2018  12:04 PM    <DIR>          Users
11/30/2018  12:04 PM    <DIR>          Windows
               1 File(s)          1,894 bytes
               5 Dir(s)  21,268,504,576 bytes free
 ---> 6241dc95b4e8
Removing intermediate container 35dc3262923d
Successfully built 6241dc95b4e8
```

We install Visual Studio Build Tools 2017 and sometimes it fails.
In logs we see errors:
> 2018-11-29T07:35:46 : Error : Visual Studio needs at least 25.63 GB of disk space. You might want to free up space on C:\ or change your target drive.