Disable service on release network
moby/moby pull request #35960
Opened 2018-01-08 22:39 UTC by abhi

This PR contains a fix for moby/moby#30321. There was a moby/moby#31142
PR intending to fix the issue by adding a delay between disabling the
service in the cluster and the shutdown of the tasks. However
disabling the service was not deleting the service info in the cluster.
Added a fix to delete service info from cluster and verified using siege
to ensure there is zero downtime on rolling update of a service.In order
to support it and ensure consitency of enabling and disable service knob
from the daemon, we need to ensure we disable service when we release
the network from the container. This helps in making the enable and
disable service less racy. The corresponding part of libnetwork fix is
part of docker/libnetwork#1824

Signed-off-by: abhi <abhi@docker.com>

**- What I did**
In order to ensure enable and disable a service on an sandbox less racy , explictly disable service on the sandbox during a container exit event on the network side. This entry point is the releaseNetwork action which triggers the tearing of the network resource for a container.
**- How I did it**
Added DisableService action on releaseNetwork
**- How to verify it**
This is particularly important during rolling update of a service and when the tasks in a swarm service goes down. Verified using siege and performing zero downtime rolling update.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-01-08 22:39 UTC, abhi commented
@fcrisciani

2018-01-16 10:23 UTC, thaJeztah commented
ping @abhi can you rebase this PR? Also looks like you added a file that shouldn't be there (I noticed theres a stack dump in there);

<img width="1006" alt="screen shot 2018-01-16 at 11 19 26" src="https://user-images.githubusercontent.com/1804568/34983985-9abbea26-faaf-11e7-98f6-e2c4692be46a.png">

2018-01-17 15:06 UTC, thaJeztah commented
Looks like you updated the PR; note that GitHub doesn't send out notifications when you update, so its best to comment or "ping" someone after you did so 😄

2018-01-17 15:40 UTC, abhi commented
@thaJeztah the guy I need to ping sits next to me :D Will do next time. 
@fcrisciani PTAL

2018-01-17 16:06 UTC, cpuguy83 requested changes

2018-01-17 16:06 UTC, cpuguy83 commented on daemon/container_operations.go
> +		logrus.Errorf("Error disabling service for sandbox id  %s container %s: %v", sid, container.ID, err)
Nit: `logrus.WithField("container", container.ID).WithError(err).WithField("sandbox", sid).Error("Error removing service from sandbox")`

2018-01-17 16:21 UTC, thaJeztah commented on daemon/container_operations.go
> +		logrus.Errorf("Error disabling service for sandbox id  %s container %s: %v", sid, container.ID, err)
Or `.WithFields()`;

```go
log.WithFields(log.Fields{"container": container.ID, "sandbox": sid}).WithError(err).Error("Error removing service from sandbox")
```

2018-01-17 17:55 UTC, fcrisciani commented
LGTM after the log change 👍

2018-01-17 22:21 UTC, abhi commented
@thaJeztah @cpuguy83 done.

2018-01-17 22:44 UTC, thaJeztah approved these changes
LGTM

2018-01-18 16:19 UTC, cpuguy83 approved these changes
LGTM

I'm not sure I like the ambiguity of the "service" term, but it is what it is.

2018-01-18 16:19 UTC, merged