Fix issue with plugin scanner going to deep
moby/moby pull request #36119
Opened 2018-01-26 01:50 UTC by cpuguy83

The plugin spec says that plugins can live in one of:

- /var/run/docker/plugins/<name>.sock
- /var/run/docker/plugins/<name>/<name>.sock
- /etc/docker/plugins/<name>.[json,spec]
- /etc/docker/plugins/<name>/<name>.<json,spec>
- /usr/lib/docker/plugins/<name>.<json,spec>
- /usr/lib/docker/plugins/<name>/<name>.<json,spec>

However, the plugin scanner which is used by the volume list API was
doing `filepath.Walk`, which will walk the entire tree for each of the
supported paths.
This means that even v2 plugins in
`/var/run/docker/plugins/<id>/<name>.sock` were being detected as a v1
plugin.
When the v1 plugin loader tried to load such a plugin it would log an
error that it couldn't find it because it doesn't match one of the
supported patterns... e.g. when in a subdir, the subdir name must match
the plugin name for the socket.

There is no behavior change as the error is only on the `Scan()` call,
which is passing names to the plugin registry when someone calls the
volume list API.

Fixes #35992

2018-01-26 02:22 UTC, thaJeztah commented
CI is failing;

```
01:53:41 pkg/plugins/discovery_unix_test.go:157::error: possible formatting directive in Fatal call (vet)
01:53:41 Build step 'Execute shell' marked build as failure
```

2018-01-26 02:24 UTC, thaJeztah requested changes

2018-01-26 02:24 UTC, thaJeztah commented on pkg/plugins/discovery_unix_test.go
> +		t.Fatal("expected plugin named `not-a-plugin`, got: %s", names[0])
`s/t.Fatal/t.Fatalf/`

2018-01-26 13:41 UTC, cpuguy83 commented
Fixed

2018-01-30 06:05 UTC, thaJeztah commented on pkg/plugins/discovery.go
> +			names = append(names, plugin)
Perhaps put these lines inside the `switch ext {` above?

2018-01-30 06:06 UTC, thaJeztah requested changes
one nit, but otherwise looks good


ping @anusha-ragunathan @tiborvass PTAL

2018-02-01 19:32 UTC, anusha-ragunathan commented on pkg/plugins/discovery.go
> +	return nil, errors.Wrapf(ErrNotFound, "could not find plugin %s in v1 plugin registry", name)
can you add the plugin name to the pluginv2 error msg as well? https://github.com/moby/moby/blob/6d4d3c52ae7c3f910bfc7552a2a673a8338e5b9f/plugin/backend_linux.go#L527

2018-02-01 19:49 UTC, anusha-ragunathan commented
Other than the nit, the rest LGTM

2018-02-02 23:14 UTC, thaJeztah approved these changes
LGTM

2018-02-03 04:18 UTC, anusha-ragunathan commented
LGTM

2018-02-03 04:19 UTC, merged