Add names to right in names-generator
moby/moby pull request #36381
Opened 2018-02-22 16:03 UTC by lonewarrior556

Signed-off-by: Konrad <lonewarrior556@yahoo.com>
**- What I did**
Added a few names seriosu and a few fun names to name-generator to slightly increase variation.

**- How I did it**
Following current convention

**- How to verify it**
see below

**- Description for the changelog**
Add a few names to names-generator to slightly increase variation.

![image](https://user-images.githubusercontent.com/4774405/36545253-caf49c82-17e8-11e8-884b-9b05b7913c7f.png)

2018-03-09 00:54 UTC, coolljt0725 commented
ping @thaJeztah

2018-03-09 14:09 UTC, thaJeztah requested changes
Thank you for contributing; I left some comments inline, but we also try to have an equal representation of female and male people in the list; could you update the PR, addressing my comments, and adding some women to keep it balanced?

2018-03-09 14:09 UTC, thaJeztah commented on pkg/namesgenerator/names-generator.go
> +		"farnsworth",
Same for farnsworth :smile:

2018-03-09 14:09 UTC, thaJeztah commented on pkg/namesgenerator/names-generator.go
> +		"munroe",
Big fan, but not sure it fits the general theme 😅

2018-03-09 15:24 UTC, lonewarrior556 commented
:) I can add distinguished females, however is it possible if at least one of the trio (`brannigan`, `farnsworth`, `Munroe`) made it? (`farnsworth` would be my choice) The sole reason they were added was because I saw `Emmett Brown` is in there!

2018-03-09 16:55 UTC, thaJeztah commented
:smile: I know it's tempting; there's two jokes in the file; "Emmet Brown" (as you found), and of course [the Woz](https://github.com/moby/moby/blob/4f0d95fa6ee7f865597c03b9e63702cdcb0f7067/pkg/namesgenerator/names-generator.go#L635-L639); not sure if we should add more, or keep it to "it's funny once".

Perhaps there's something to say for both of those being male (so should we add [Doctor Amy Wong](https://en.wikipedia.org/wiki/Amy_Wong)?)

2018-10-04 03:29 UTC, AkihiroSuda commented
ping @lonewarrior556

also please sign your commit with your full name

2018-11-26 23:53 UTC, cpuguy83 commented
I'm going to close this due to inactivity.
Please let me know if you are still interested in submitting these and we can re-open.

Thanks! 🙇

2018-11-26 23:53 UTC, closed without merging