[WIP] Update docker-py
moby/moby pull request #36384
Opened 2018-02-22 23:04 UTC by yongtang

This fix update docker-py so that containers from the tests run
could be cleaned up during teardown.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-02-23 21:06 UTC, yongtang commented
This PR depends on https://github.com/docker/docker-py/pull/1922

2018-02-23 21:33 UTC, thaJeztah requested changes

2018-02-23 21:33 UTC, thaJeztah commented on Dockerfile
> +RUN git clone https://github.com/yongtang/docker-py.git /docker-py \
^^ commenting just so that we don't forget to change it before merging

2018-02-23 21:36 UTC, thaJeztah commented
https://github.com/docker/docker-py/pull/1922 was merged 👍

2018-02-23 22:27 UTC, yongtang commented
Thanks @thaJeztah. The PR has been updated.

2018-02-23 22:33 UTC, thaJeztah approved these changes
LGTM (if green)

2018-02-24 14:05 UTC, thaJeztah commented
ping @vdemeester @cpuguy83 it's green 🤗

2018-02-25 10:52 UTC, boaz0 approved these changes
LGTM :+1:

2018-02-25 11:42 UTC, vdemeester approved these changes
LGTM 🦌

2018-02-25 11:42 UTC, merged