Whitelist statx syscall
moby/moby pull request #36417
Opened 2018-02-26 20:32 UTC by NobodyOnSE

Signed-off-by: NobodyOnSE <ich@sektor.selfip.com>

Edited via github's webeditor, so the signoff was done manually, I hope that is enough.

**- What I did**
Added statx to whitelist of allowed syscalls.

**- How I did it**
Added it in the default.json for seccomp.

**- How to verify it**
Try to use it and don't get an EPERM anymore on non-privileged containers.

**- Description for the changelog**
Whitelist statx syscall

**- A picture of a cute animal (not mandatory but encouraged)**

![Hedgehog with christmas hat](http://i.imgur.com/7KJzx.jpg)

2018-02-27 10:13 UTC, AkihiroSuda requested changes
This is autogenerated file.

Please edit `seccomp_dewfault.go` and run `go generate`

2018-02-27 14:53 UTC, NobodyOnSE commented
@AkihiroSuda I hope that worked. I am no go programmer. I am not used to having an autogenerated file in version control.

2018-02-28 10:55 UTC, thaJeztah commented
ping @justincormack @n4ss PTAL

2018-02-28 14:07 UTC, xantares approved these changes

2018-02-28 14:58 UTC, justincormack approved these changes

2018-02-28 15:01 UTC, justincormack commented
Thats fine but note that you will need to install libseccomp-2.3.3 on the host for this to work, as I think that is the first version with `statx` support.

2018-02-28 17:13 UTC, thaJeztah commented
> Thats fine but note that you will need to install libseccomp-2.3.3 on the host for this to work, as I think that is the first version with statx support.

What would be the effect when running on an older libseccomp? will it just ignore this configuration, and continue working as currently?

2018-02-28 19:28 UTC, n4ss commented
LGTM!

2018-03-05 19:05 UTC, NobodyOnSE commented
@thaJeztah I tried to emulate this case by whitelisting the fake syscall `nonsense` and got no error message. The container started as intended. Furthermore, the seccomp filter still seems to work as I got EPERM on a non whitelisted syscall.

2018-03-05 19:09 UTC, thaJeztah commented
>  I tried to emulate this case by whitelisting the fake syscall nonsense and got no error message. The container started as intended. Furthermore, the seccomp filter still seems to work as I got EPERM on a non whitelisted syscall.

Thanks! 

Changes LGTM; could you squash your commits, so that there's a single commit in this PR? While doing so, perhaps you could update the commit message to also mention that this requires newer versions of libseccomp, and will be ignored by older ones

2018-03-06 07:48 UTC, NobodyOnSE commented
> could you squash your commits, 

done 

> update the commit message to also mention that this requires newer versions of libseccomp, and will be ignored by older ones

done

2018-03-06 08:14 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-03-06 12:49 UTC, NobodyOnSE commented
@thaJeztah Is there an ETA or a planned release for this PR?

2018-03-06 13:33 UTC, merged

2018-03-06 13:35 UTC, thaJeztah commented
@NobodyOnSE it was opened after code-freeze for Docker 18.03, so currently it will be included in the release after that (18.04)

2018-03-06 13:37 UTC, thaJeztah commented
If you want to try a version with this patch, nightly builds should be available soon in the "nightly" channel (e.g. nightly builds for Ubuntu 16.04 https://download.docker.com/linux/ubuntu/dists/xenial/pool/nightly/amd64/)