Migrate api options tests in integration-cli to api tests
moby/moby pull request #36431
Opened 2018-02-27 19:49 UTC by yongtang

This fix migrates api options tests in integration-cli to api tests.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-02-27 19:55 UTC, dnephin reviewed
I think all of these can be unit tests

2018-02-27 19:55 UTC, dnephin commented on integration/system/options_test.go
> +	assert.Equal(t, resp.StatusCode, http.StatusOK)
Should be a unit test of the api router

2018-02-27 19:55 UTC, dnephin commented on integration/system/options_test.go
> +	// and here none of the headers below are in the response?
This test doesn't look to be useful anymore. It's been disabled for so long now I think we can aprobably remove it as the original intent is probably lost.

2018-02-27 19:55 UTC, dnephin commented on integration/system/options_test.go
> +	expected := fmt.Sprintf("client version %s is too old. Minimum supported API version is %s, please upgrade your client to a newer version", version, api.MinVersion)
I think this should be a unit test.

`integration` tests should be for features/behaviour. We can easily test this error case without running a full daemon.

2018-02-27 19:55 UTC, dnephin commented on integration/system/options_test.go
> +	assert.Equal(t, strings.TrimSpace(r.Message), "Config cannot be empty in order to create a container")
Not sure what this is supposed to be testing. Is it testing the container create API? It could be a unit test of the API router.

2018-02-27 19:55 UTC, dnephin commented on integration/system/options_test.go
> +	assert.Equal(t, strings.TrimSpace(string(b)), "Config cannot be empty in order to create a container")
can be a unit test.

2018-02-27 19:55 UTC, dnephin commented on integration/system/options_test.go
> +	resp, body, err := req.Get("/notfound", req.JSON)
can be a unit test of the API router.

2018-02-28 08:13 UTC, vdemeester requested changes
Agreeing with @dnephin, those tests should be unit tests :angel:

2018-05-11 19:42 UTC, yongtang commented
@cpuguy83 Let me close this one for now.

2018-05-11 19:42 UTC, closed without merging