Migrate docker rm tests to api tests
moby/moby pull request #36474
Opened 2018-03-02 22:55 UTC by yongtang

This fix migrates docker rm test in integration-cli
to api tests.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-03-03 16:25 UTC, AkihiroSuda commented on integration/container/remove_test.go
> +func buildImageWithDockerfile(t *testing.T, ctx context.Context, client client.APIClient, tag string, dockerfile string) string { // nolint: golint
Maybe we can expose this function to other packages, but not needed right now

2018-03-03 16:25 UTC, AkihiroSuda approved these changes

2018-03-05 17:36 UTC, dnephin requested changes

2018-03-05 17:36 UTC, dnephin commented on integration/container/remove_test.go
> +	imageID1 := buildImageWithDockerfile(t, ctx, client, img, dockerfile1)
I think we should avoid using `build` in tests outside of the image suite.

1. It's going to be slower to build something that to `load`
2. It means that multiple test suites require build. If we want to provide build as a separate service this unnecessary coupling is going to make it a lot more work.

Can we setup this image structure using `image load` api?  If not,  we should make this a unit test.

2018-03-05 19:16 UTC, yongtang commented
@dnephin The PR has been updated to use commit for a small image change (vs. Dockerfile) instead. Please take a look.

2018-03-05 20:19 UTC, dnephin reviewed
Thanks for making this change.

Looking at the test in more detail now, it seems like it is testing "image remove" not container remove. Is that right?

Should this move to `integration/image/remove_test.go` ?

2018-03-05 20:37 UTC, yongtang commented
@dnephin Thanks. Yes it might be more relevant to images. The PR has been updated. Please take a look.

2018-03-05 20:40 UTC, dnephin approved these changes
LGTM

2018-03-06 01:15 UTC, merged