Unify arch-specific Dockerfiles into multi-arch one
moby/moby pull request #36546
Opened 2018-03-09 07:17 UTC by arm64b

Now we have several Dockerfiles for all the available platforms, the contents in those files are almost the same, naturally one solution is to consolidate all those Dockerfiles into only one, which will ease the effort of the code maintenance, for example, we have multi files need to be updated if we want to bump the version of `runc`.    

**- What I did**
Remove the redundancy of the Dockerfile 
**- How I did it**
Consolidate the different arch-specific Dockerfiles into only one.
**- How to verify it**
`make binary` and `make test-integration`
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-03-09 07:26 UTC, arm64b commented
@vdemeester @thaJeztah @cpuguy83 @tonistiigi

2018-03-09 08:24 UTC, thaJeztah commented
oooooh :heart_eyes: nice!

ping @tianon @seemethere @andrewhsu as well :-)

2018-03-09 08:41 UTC, vdemeester commented
Updating the powerpc and z to "handle" that PR to make sure it works :angel: (without making other PRs fail)

```bash
# powerpc
test -f Dockerfile.ppc64le && \
docker build --rm --force-rm --build-arg APT_MIRROR=cdn-fastly.deb.debian.org -t docker-powerpc:$GITCOMMIT -f Dockerfile.ppc64le . || \
docker build --rm --force-rm --build-arg APT_MIRROR=cdn-fastly.deb.debian.org -t docker-powerpc:$GITCOMMIT -f Dockerfile .
# z
test -f Dockerfile.s390x && \
docker build --rm --force-rm --build-arg APT_MIRROR=cdn-fastly.deb.debian.org -t docker-s390x:$GITCOMMIT -f Dockerfile.s390x . || \
docker build --rm --force-rm --build-arg APT_MIRROR=cdn-fastly.deb.debian.org -t docker-s390x:$GITCOMMIT -f Dockerfile .
```

2018-03-09 09:05 UTC, arm64b commented
Thanks @vdemeester and @thaJeztah for the quick response, especially the command line for `powerpc` and `z` nodes is extremely helpful and magic 👼

2018-03-09 19:06 UTC, dnephin approved these changes
LGTM

2018-03-09 21:21 UTC, kolyshkin requested changes
CRIU for other platforms, also s/Malti-arch/Multiarch/

2018-03-09 21:34 UTC, seemethere commented
Going to try and see if this will work with our build/release pipeline for Docker CE.

2018-03-09 22:40 UTC, seemethere approved these changes
LGTM

2018-03-12 02:09 UTC, arm64b commented on Dockerfile
> +	mkdir -p /opt/criu; \
The typo has been fixed. For the CRIU stuff, thanks for the suggestion 👍 , so I'll submit a separate PR to enable CRIU on ARM, PPC64 and S390x platforms. This PR just focuses on the build pipeline.

2018-03-12 08:42 UTC, thaJeztah approved these changes
LGTM

> I'll submit a separate PR to enable CRIU on ARM, PPC64 and S390x platforms after this PR merged. This PR just focuses on the build pipeline.

Agreed, let's keep that change separate from this one (thanks @kolyshkin for providing the info 👍)

2018-03-12 08:47 UTC, vdemeester approved these changes
LGTM :tiger:

2018-03-12 11:36 UTC, merged