Don't make container mount unbindable
moby/moby pull request #36768
Opened 2018-04-02 20:24 UTC by crosbymichael

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Reverts the unbindable change in #35830 so that secrets/configs can be propagated.

2018-04-03 00:07 UTC, cpuguy83 requested changes
Looks like we need to change or remove the `ContainerShmNoLeak` test.

2018-04-03 18:25 UTC, crosbymichael commented
@cpuguy83 what should we change about it?

2018-04-03 20:00 UTC, cpuguy83 commented
I think the only real way to test it is to make sure the shm mount for the 1st container is unmounted from the 2nd container when the 1st container is stopped.
Just trying to remove the 1st container with the 2nd one running isn't really enough since lazy unmount+rm works just fine since the `rm` also becomes lazy in that case.

2018-04-04 15:32 UTC, crosbymichael commented
Should we make the shm mount unbindable?

2018-04-04 15:47 UTC, cpuguy83 commented
It would have to be in a separate dir, because we can't make the mount itself unbindable.

2018-04-11 00:08 UTC, cpuguy83 approved these changes
LGTM

2018-04-11 01:47 UTC, kolyshkin commented
LGTM

2018-04-11 01:55 UTC, thaJeztah approved these changes
LGTM

2018-04-11 07:54 UTC, merged