Standardize artefact path for all build stages
moby/moby pull request #36858
Opened 2018-04-13 19:21 UTC by j-haj

Closes #36414 

**- What I did**
Updated the output path for all build artefacts to `/build/` in the Dockerfile

**- How I did it**
Changed the old output paths to `/build/`

**- How to verify it**
Easily verified by viewing the updated Dockerfile or the `/build/` directory of the intermediate builds

**- Description for the changelog**
Standarizes output path for artefacts of intermediate builds to `/build/`

2018-04-13 22:38 UTC, thaJeztah requested changes
Thanks! I left some comments 👍

2018-04-13 22:38 UTC, thaJeztah commented on Dockerfile
> +		go build -buildmode=pie -o /build github.com/docker/distribution/cmd/registry \
This should be `-o /build/registry-v2`

2018-04-13 22:38 UTC, thaJeztah commented on Dockerfile
> +			go build -buildmode=pie -o /build github.com/docker/distribution/cmd/registry; \
This should be `-o /build/registry-v2-schema1`

2018-04-13 22:38 UTC, thaJeztah commented on Dockerfile
> +	&& go build -o /build github.com/go-swagger/go-swagger/cmd/swagger \
This should be `-o /build/swagger`

2018-04-13 22:38 UTC, thaJeztah commented on Dockerfile
> +RUN PREFIX=/build/$INSTALL_BINARY_NAME ./install.sh $INSTALL_BINARY_NAME
This should be `/build/` (without `$INSTALL_BINARY_NAME`) because it's the target-directory

2018-04-13 22:38 UTC, thaJeztah commented on Dockerfile
> +RUN PREFIX=/build/$INSTALL_BINARY_NAME ./install.sh $INSTALL_BINARY_NAME
Same here (and others below)

2018-04-17 13:04 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "36414-standardize_build_paths" git@github.com:j-haj/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842360409832
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-04-17 17:14 UTC, j-haj commented
It appears two tests are failing:

* `DockerSwarmSuite.TestAPIServiceUpdatePort`
* `DockerSwarmSuite.TestSwarmPublishDuplicatePorts`

On the surface these don't seem like they should be related to the changes made to the Dockerfile. I'll poke around in `docker_cli_swar_test.go` to see if anything stands out.

2018-04-17 17:22 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-04-18 08:41 UTC, vdemeester approved these changes
LGTM :tiger:

2018-04-18 10:58 UTC, cpuguy83 approved these changes
LGTM

2018-04-18 10:58 UTC, merged