Add myself to poule to get 2w/old PRs
moby/moby pull request #36866
Opened 2018-04-16 09:51 UTC by fntlnz

2018-04-16 11:05 UTC, vdemeester approved these changes
LGTM :tiger:

2018-04-16 16:30 UTC, thaJeztah requested changes
one nit, but LGTM otherwise 🤗

2018-04-16 16:30 UTC, thaJeztah commented on .DEREK.yml
> +  - fntlnz
Can you keep the lists alphabetical? 🤗

2018-04-16 16:30 UTC, thaJeztah commented on poule.yml
> +                "fntlnz",
Same for this one :smile:

2018-04-17 01:32 UTC, thaJeztah approved these changes
LGTM

2018-04-17 01:32 UTC, thaJeztah commented
Merging, as this file isn't tested in CI :smile:

2018-04-17 01:32 UTC, merged