[test/integration-cli] small cleanups of FIXME(s)
moby/moby pull request #36875
Opened 2018-04-17 10:05 UTC by vdemeester

- Add a Cleanup function that cleans exec root and swarm files directly in `internal/test/daemon`
- Remove `daemon.BuildImageWithOut` and use cli helpers function instead

2018-04-17 17:59 UTC, thaJeztah requested changes
left some nits, but looks good otherwise

2018-04-17 17:59 UTC, thaJeztah commented on internal/test/daemon/daemon.go
> +	walDir := filepath.Join(d.Root, "swarm/raft/wal")
Perhaps move this to a function as well (similar to `cleanupExecRoot()`)

2018-04-17 17:59 UTC, thaJeztah commented on internal/test/daemon/daemon.go
>  	cleanupExecRoot(t, d.execRoot)
Looks like `cleanupExecRoot()` is now basically only cleaning up netns; perhaps we should rename it

2018-04-20 00:14 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-04-20 00:31 UTC, cpuguy83 approved these changes
LGTM

2018-04-20 00:31 UTC, merged