Update hcsshim to v0.6.10
moby/moby pull request #36985
Opened 2018-05-02 17:19 UTC by darrenstahlmsft

**- What I did**

Update hcsshim to v0.6.10 which includes security fixes to address [CVE-2018-8115](https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/CVE-2018-8115)

**- Description for the changelog**

Security: Change to address [CVE-2018-8115](https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/CVE-2018-8115)

(Addition by @jhowardmsft): Replaces #36938 which vendored v0.6.9. Hence also: Fixes https://github.com/docker/for-win/issues/1947. Fixes https://github.com/moby/moby/issues/36919 where files are in certain circumstances omitted from layers on commit during a build step on Windows. See https://github.com/Microsoft/hcsshim/pull/165 for more detail.

@carlfischer1 Both fixes should probably should be backported.

2018-05-02 19:31 UTC, darrenstahlmsft commented
This change only affects code that compiles on Windows so the other CI failures can be ignored. I'll restart them anyway, but they shouldn't matter.

This is also been tested by Docker Inc and Microsoft internally.

2018-05-03 02:16 UTC, lowenna approved these changes
LGTM. @johnstep PTAL

2018-05-03 05:18 UTC, thaJeztah requested changes
The previous PR (https://github.com/moby/moby/issues/36938) did not have a test case, will that be included as part of this one?

2018-05-03 05:41 UTC, jhowardmsft commented
@thaJeztah TL;DR No. 

This is already in EE. Others are free to add test cases if they have time. Resources are limited. This fixes a CVE plus a reported bug, both of which have been verified by both MS and Docker Inc independently. If there needs to be a follow-up PR for tests, that should not block this PR.

2018-05-03 06:11 UTC, jhowardmsft commented
@carlfischer1 FYI

2018-05-03 17:52 UTC, johnstep approved these changes
LGTM

I found and fixed a separate bug (see https://github.com/Microsoft/hcsshim/pull/169) and also wrote an integration test that covers that issue, plus checks that `$Recycle.Bin` is not committed, and that files are not missing. After this PR is merged, I will vendor hcsshim v0.6.11 into my [test branch](https://github.com/johnstep/moby-moby/commits/add-windows-recycle-bin-test) and open a moby PR.

2018-05-03 20:17 UTC, thaJeztah approved these changes
lgtm

2018-05-03 20:18 UTC, merged

2018-05-07 18:25 UTC, mback2k commented
Could we please also get a new preview version (like` 17.10.0-ee-preview-3`) with these bugfixes? I have to spent hours of building docker images locally and uploading them to my Windows Server 1709. Waiting for more than 1 hour between each test run due to slow build and upload time locally is very annoying. It would be very appreciated.

2018-06-28 07:43 UTC, mback2k commented
@thaJeztah Could you please tell us if the new release of "18.03.1-ee-1 (2018-06-27)" includes hcsshim v0.6.11 or at least v0.6.10?

2018-06-28 08:09 UTC, thaJeztah commented
@mback2k yes; all current versions of Docker (EE, CE) have the fix in place