Avoid unique name usage in TestDockerNetworkConnectAlias
moby/moby pull request #37044
Opened 2018-05-11 20:06 UTC by yongtang

In `TestDockerNetworkConnectAlias` the network and container names used are unique which are not preferred. This fix address the issue by appending `t.Name()` so that names are randomized.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-05-13 20:15 UTC, thaJeztah approved these changes
LGTM

2018-05-14 08:35 UTC, vdemeester requested changes
I don't think we even need to set names for those tests right ? We are testing the aliases, so we could use id for all the operation and check that the `ng2` container has the correct alias for the specified network.. So we just need a unique network name :angel:

2018-05-14 20:52 UTC, yongtang commented
Thanks @vdemeester The PR has been updated. Please take a look.

2018-05-15 07:38 UTC, vdemeester approved these changes
LGTM :lion:

2018-05-15 09:46 UTC, merged