Adds a few more names to the name generator.
moby/moby pull request #37157
Opened 2018-05-26 07:24 UTC by debayande

**- What I did**
_Added a few more names to the name generator_

**- How I did it**
_I added the names to `pkg/namesgenerator/names-generator.go`_

**- How to verify it**
_Please check `pkg/namesgenerator/names-generator.go`_

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-05-26 08:27 UTC, AkihiroSuda commented on pkg/namesgenerator/names-generator.go
> +		"youyou",
Her family name is Tu

2018-05-26 13:53 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		"youyou",
Oops! Will fix right away.

2018-06-28 04:13 UTC, AkihiroSuda commented
Please rebase?

2018-06-29 15:32 UTC, AkihiroSuda commented
@thaJeztah PTAL?

2018-06-30 20:53 UTC, thaJeztah requested changes

2018-07-01 13:28 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		"burnell",
That would conflict with `bell` from Alexander Graham Bell's surname.

Despite her divorce, Dame Jocelyn chooses to keep that surname. For example, she is the patron of the [Burnell House](https://en.wikipedia.org/wiki/Cambridge_House_Grammar_School#The_House_System) in the Cambridge House Grammar School. Also [a book](https://www.amazon.co.uk/Dark-Matter-Poems-Maurice-Riordan/dp/190308010X) co-edited by her as recently as in 2008 (she divorced Martin Burnell in 1993), retains _Burnell_ in her name. So, I think `burnell` should be fine.

2018-07-01 13:31 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		"burnell",
That would conflict with _bell_ from Alexander Graham Bell's surname.

Despite her divorce, Dame Jocelyn chooses to keep that surname. For example, she is the patron of the [Burnell House](https://en.wikipedia.org/wiki/Cambridge_House_Grammar_School#The_House_System) in the Cambridge House Grammar School. Also [a book](https://www.amazon.co.uk/Dark-Matter-Poems-Maurice-Riordan/dp/190308010X) co-edited by her as recently as in 2008 (she divorced Martin Burnell in 1993), retains Burnell in her name. So, I think _burnell_ should be fine.

2018-07-01 13:31 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		// Susan Jocelyn Bell Burnell - Northern Irish astrophysicist who discovered radio pulsars and was the first to analyse them. https://en.wikipedia.org/wiki/Jocelyn_Bell_Burnell
Done!

2018-07-01 13:31 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		// Mary Lucy Cartwright - British mathematician who was one of the first to study what is now known as chaos theory. Also known for Cartwright's theorem which finds applications in signal processin
Done!

2018-07-01 13:40 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		"berners",
Actually, we have: cf. [al-Battānī](https://github.com/debayande/moby/blob/fc09683d601f7374bf5ded4767603eb289ca7466/pkg/namesgenerator/names-generator.go#L108), [Joliot-Curie](https://github.com/debayande/moby/blob/fc09683d601f7374bf5ded4767603eb289ca7466/pkg/namesgenerator/names-generator.go#L422), [Payne-Gaposchkin](https://github.com/debayande/moby/blob/fc09683d601f7374bf5ded4767603eb289ca7466/pkg/namesgenerator/names-generator.go#L590), [Levi-Montalcini](https://github.com/debayande/moby/blob/fc09683d601f7374bf5ded4767603eb289ca7466/pkg/namesgenerator/names-generator.go#L620), [Barré-Sinoussi](https://github.com/debayande/moby/blob/fc09683d601f7374bf5ded4767603eb289ca7466/pkg/namesgenerator/names-generator.go#L662), [Nüsslein-Volhard](https://github.com/debayande/moby/blob/fc09683d601f7374bf5ded4767603eb289ca7466/pkg/namesgenerator/names-generator.go#L719).

In each of these cases, the committer has chosen to go either with the first or the second of the two dashed surnames. I've chosen to go with the first.

2018-07-01 13:56 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		"onnes",
Replaced by [Ralph C. Merkle](https://github.com/debayande/moby/blob/02a7afa7ac6a99527765b0e7ce77f4268f6b9e01/pkg/namesgenerator/names-generator.go#L536).

2018-07-01 13:59 UTC, debayande commented
@thaJeztah I've made the changes you requested. Please take a look. Thanks!

2018-07-02 10:23 UTC, thaJeztah commented on pkg/namesgenerator/names-generator.go
> +		"berners",
Hm, looks like we're not really consistent there, or the committer may have misinterpreted double names as maiden names. For al-Battānī, I see that `al-` is more of a "prefix" (so possibly that's commonly excluded / not part of the last name). For Joliot-Curie,  Payne-Gaposchkin, Barré-Sinoussi, and Nüsslein-Volhard, I see their maiden-names were used, but "Levi-Montalcini" may be incorrect

2018-07-02 11:53 UTC, debayande commented on pkg/namesgenerator/names-generator.go
> +		"berners",
Replaced by [Horst Feistel](https://en.wikipedia.org/wiki/Horst_Feistel).

2018-07-02 12:51 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-07-03 01:14 UTC, debayande commented
☝️ Just squashed two commits into one; no new deltas have been introduced.

2018-07-03 12:17 UTC, vdemeester approved these changes
LGTM :tiger:

2018-07-05 19:06 UTC, merged

2018-07-05 19:06 UTC, thaJeztah commented
Merged! Thanks for contributing @debayande !!