Initial support for OCI multi-platform image
moby/moby pull request #37346
Opened 2018-06-26 08:24 UTC by arm64b

Add the OCI spec compatible image support in client side.

Signed-off-by: Dennis Chen <dennis.chen@arm.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-06-26 09:08 UTC, arm64b commented
/cc @thaJeztah @johnstep, @dmcgowan @tianon, and @tonistiigi 😃

2018-06-26 09:20 UTC, arm64b commented
Will check the ci-failing tomorrow

2018-06-26 09:23 UTC, thaJeztah commented
Thanks!

2018-06-26 17:50 UTC, kolyshkin requested changes

2018-06-26 17:50 UTC, kolyshkin commented on api/server/router/build/build_routes.go
> +		if len(strings.TrimSpace(apiPlatform)) != 0 {
Where is this (`strings.TrimSpace()`) coming from? It seems you are relaxing the spec here, allowing for non-empty strings containing some whitespace characters. Previous implementation (`system.ParsePlatform()`) did not do any special treatment of white space.

2018-06-26 17:50 UTC, kolyshkin commented on api/server/router/image/image_routes.go
> +		if len(strings.TrimSpace(apiPlatform)) != 0 {
ditto

2018-06-26 17:50 UTC, kolyshkin commented on image/tarexport/load.go
> +	// TODO(@arm64b): Leave this sanity check to the containerd code in the future
From the code it appears it's not longer a TODO item, so maybe just remove the comments about checking altogether?

2018-06-26 18:11 UTC, kolyshkin commented
CI failures are caused by
```
02:06:53 # github.com/docker/docker/client
02:06:53 client/image_build.go:33:22: invalid operation: options.Platform != "" (mismatched types v1.Platform and string)
02:06:53 client/image_build.go:37:32: cannot use options.Platform (type v1.Platform) as type string in argument to query.Set
02:06:53 client/image_build.go:133:22: invalid operation: options.Platform != "" (mismatched types v1.Platform and string)
02:06:53 client/image_build.go:134:48: cannot use options.Platform (type v1.Platform) as type string in argument to strings.ToLower
```

2018-06-27 01:51 UTC, arm64b commented
Hello @kolyshkin , thanks for the comments! I think we can close this PR since we have a replacement of PR #37350 by @tonistiigi 👍

2018-06-27 01:51 UTC, closed without merging