Add Omar Khayyam to the names generator
moby/moby pull request #37384
Opened 2018-07-03 18:14 UTC by omidkrad

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-07-03 18:14 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-2" git@github.com:omidkrad/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-07-03 19:12 UTC, cpuguy83 commented
> Please, for any amazing man that you add to the list, consider adding an equally amazing woman to it, and vice versa.

2018-07-04 17:23 UTC, thaJeztah requested changes
thank you for contributing! Could you add a woman as well? https://github.com/moby/moby/pull/37384#issuecomment-402263958

2018-09-19 17:28 UTC, thaJeztah commented
Let's close this one for now, as it went stale, and needs a rebase as well

2018-09-19 17:28 UTC, closed without merging