Bump swarmkit to include task reaper fixes and more metrics.
moby/moby pull request #37399
Opened 2018-07-05 20:53 UTC by cyli

This includes the following behavior-modifying PRs:

- https://github.com/docker/swarmkit/pull/2673
- https://github.com/docker/swarmkit/pull/2669
- https://github.com/docker/swarmkit/pull/2675
- https://github.com/docker/swarmkit/pull/2664

Signed-off-by: Ying Li <ying.li@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-07-05 21:52 UTC, thaJeztah requested changes

2018-07-05 21:52 UTC, thaJeztah commented on vendor/archive/tar/LICENSE
> -Copyright (c) 2009 The Go Authors. All rights reserved.
Ah, hm, looks like something still went wrong; that's an issue with the latest version of vndr, which removes everything before vendoring.

The `archive/tar` vendor should not be removed

2018-07-05 21:57 UTC, cyli commented
@thaJeztah Oh ok, weird, the vendor CI seemed to pass.  Will do.

2018-07-05 22:41 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-07-06 01:27 UTC, yongtang approved these changes
LGTM one all  💚

2018-07-06 07:30 UTC, merged