[WIP] api: add a GPU resource type
moby/moby pull request #37434
Opened 2018-07-10 22:14 UTC by flx42

CLI discussion: https://github.com/docker/cli/issues/1200

First draft of what the API might look like. I don't believe we need something more complex than that.

Discussion points
* Since in the CLI discussion we agreed to namespace GPUs per vendor, naturally the entrypoint for the API is a map to access all the GPUs and options for a single vendor. We could have a single slice of GPUs and a single option map, but it feel awkward if a vendor needs to skip devices/options that it doesn't own.
* Naming is hard, so `Resources` (plural) is all the GPUs from all vendor. `Resource` is all the GPUs from a **single** vendor. Thoughts?
* Let's not support per-GPU options for now, but we can add that to the `GPU` struct later without breaking existing code.
* In the CLI discussion we discussed a shortcut to select all GPUs: `--gpus nvidia`. However at this point it's not possible to get the actual list of GPU ids. We have two options: a) if `gpu.Resource.GPUs` is empty, then select all GPUs OR b) if `gpu.Resource.GPUs[0].ID == "*"` then select all GPUs.

2018-07-11 14:21 UTC, crosbymichael commented on api/types/gpu/gpu.go
> +// TODO: is this confusing? Should one resource struct correspond to one GPU only?
Yes, it is pretty confusing ;)

2018-07-11 15:59 UTC, cpuguy83 commented
There's already some work (in swarmkit) around "GenericResources".
I wonder if that can, or should, be brought over into the runtime side for this.

https://godoc.org/github.com/docker/docker/api/types/swarm#GenericResource

It's a bit more abstract because it's designed to be pretty loose as resources are defined by admins for a given node and the scheduler matches the resources defined on the node with resources defined in the service.... so maybe not necessarily the best fit.

2018-07-11 16:16 UTC, flx42 commented
Yes, the `GenericResource` support was added in swarmkit by my colleague @RenaudWasTaken. As you said this existing API seems to be a better fit for scheduling/matching purposes, and we'll lose the per-vendor separation that I think is useful for API users; but on the other hand this type might be reused for other purposes in the future too.

But those are not major problems, we could work with the existing `GenericResource` type, if we also attach option to each resource.

2018-07-11 16:29 UTC, flx42 commented
So the fundamental question here is:
* Do we want a `GPU` resource type? Or do we want a more generic API similar to Swarm?

I'm fine either ways.

2018-07-11 16:30 UTC, cpuguy83 commented
I think a GPU type works fine and is much simpler to deal with.

2018-07-12 19:06 UTC, flx42 commented
Updated my PR, we now have the following:
```
package container

type Resources struct {
        GPUsByVendor map[gpu.Vendor]*gpu.Resources
        [...]
}
```

```
package gpu

type Vendor string

type Resources struct {
        GPUs    []GPU
        Options map[string]string
}

type GPU struct {
        ID string
}
```

I don't think we need more than that today. If we agree on the API, I can start to flesh out the next step: integration in `dockerd` by transforming these GPU resources into OCI annotations, then calling into the new containerd API.

2018-07-12 22:29 UTC, cpuguy83 requested changes
I'm not really sure what makes sense from the GPU side of things, but I'd like to make sure the API does not limit how we can use this later on (or to what the proposed docker CLI solution can handle).

Would make make sense to have the API be `GPUs []gpu.Resource` where a `gpu.Resource` is:

```go
package gpu

type Resource {
    Type string // e.g. 'nvidia'
    ID string // GPU UUID... whatever the vendor defines
    Options map[string]string
}
```

Also this may not require it's own package since there's not really much to it.

Anyway as I said I'm not sure what makes sense from the vendor perspective here but this seems like it makes the API a bit more extensible and the complexity of it can be handled by the client.

2018-07-12 22:29 UTC, cpuguy83 commented on api/types/container/host_config.go
> +	GPUsByVendor map[gpu.Vendor]*gpu.Resources `json:"GpusByVendor,omitempty"` // List of GPUs to map inside the container.
This limits the API quite a bit.
What do you think about using a slice here and then we can validate as needed in code.

2018-07-12 23:36 UTC, cpuguy83 commented
@flx42 Thanks for the feedback! So when you say "all" of the GPU's, does that mean literally all GPU's on the system or all the selected GPUs?

Do we know anyone from AMD that would be able to provide input here as well?

2018-07-12 23:44 UTC, flx42 commented
> So when you say "all" of the GPU's, does that mean literally all GPU's on the system or all the selected GPUs?

All the **selected** GPUs for the `nvidia` vendor. Or in other words, this option applies at the container level.

Maybe @kad can chime in on the Intel side for OpenCL, maybe they could have a similar option for selecting/modifying the OpenCL ICD.

2018-07-16 16:48 UTC, cpuguy83 commented
@flx42 It seems like your structs work well (but still would prefer a slice over a map in hostconfig, and leave it up to the implementation to validate). Perhaps we can change `Resource` to `GPUSet`?

2018-07-17 23:08 UTC, flx42 commented
Well the existing `Resources` struct is embedded in `HostConfig`:
https://github.com/moby/moby/blob/master/api/types/container/host_config.go#L398-L399

I think it makes sense to consider a GPU as a `resource` since that's where CPU, char/block devices, memory are.

2018-07-17 23:09 UTC, flx42 commented
The `Resources` struct in https://github.com/moby/moby/pull/37434#issuecomment-405755707 is the existing one, in case it was not clear, sorry :)

2018-07-17 23:09 UTC, cpuguy83 commented
Ah I see, yeah that's perfect.

2018-07-18 01:46 UTC, flx42 commented
Assuming we are OK with this design, I will go ahead with the corresponding implementation in the CLI (`--gpus) and in dockerd (for calling into the containerd features).

2018-12-22 07:44 UTC, olljanat commented
Derek add label: rebuild/janky

2018-12-22 16:40 UTC, olljanat commented
@yongtang looks that this one passes tests. PTAL

2018-12-22 16:57 UTC, yongtang commented
/cc @cpuguy83

2019-01-12 03:08 UTC, RenaudWasTaken commented
Hello!

I'll be taking over @flx42's PRs.

@cpuguy83 do you have any problems left with the current API? If not can we go ahead and merge this?
Thanks!

2019-01-15 22:14 UTC, cpuguy83 commented
Mainly concerned about other GPU vendors chiming in, but no one has in all this time... moving to code review.

2019-03-19 18:32 UTC, closed without merging