Migrate some ipc container test from integration-cli to integration
moby/moby pull request #37541
Opened 2018-07-27 08:05 UTC by yongtang

This fix migrates some ipc container tests from integration-cli to integration test.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-07-27 08:16 UTC, vdemeester approved these changes
LGTM :tiger:

2018-07-31 09:19 UTC, thaJeztah requested changes
thanks! some minor comments / suggestions

2018-07-31 09:19 UTC, thaJeztah commented on integration/container/ipcmode_test.go
> +// TestAPIIpcModePrivateAndContainer checks that a container created with
Whoops, looks like you forgot to copy the second line of this test's

2018-07-31 09:19 UTC, thaJeztah commented on integration/container/ipcmode_test.go
> +	defer setupTest(t)()
Should this function have `t.Helper()`?

2018-07-31 09:19 UTC, thaJeztah commented on integration/container/ipcmode_test.go
> +	testIpcContainer(t, "shareable", true)
(just a suggestion); we could combine these two tests and use subtests (one with `shareable` one with `private`)

2018-08-02 04:41 UTC, yongtang commented
@thaJeztah Thanks. The PR has been updated. Please take a look.

2018-08-02 13:51 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-08-02 13:51 UTC, merged