buildkit: enable net modes and bridge
moby/moby pull request #37620
Opened 2018-08-09 21:43 UTC by tonistiigi

Changes the default network used by buildkit to libnetwork bridge and enables `--network=host` and `--network=none`. Frontends have the capability to set networking modes per-command.

depends on https://github.com/moby/buildkit/pull/560

@fcrisciani @abhi

2018-08-10 03:05 UTC, tonistiigi commented on builder/builder-next/builder.go
> +	llbsolver.AllowNetworkHostUnstable = true
This is a temporary variable that needs to be set globally because buildkit by default forbids host network entitlement on daemon level.

2018-08-10 05:30 UTC, abhi approved these changes
LGTM.  I will give the patch a try for better understanding.

2018-08-10 15:50 UTC, tonistiigi commented
Forgot to add `--add-host` support as well. Added a commit.

2018-08-17 17:14 UTC, thaJeztah commented
This test is failing on all CI, so may be related;

```
09:46:47 --- FAIL: TestContainerStartOnDaemonRestart (2.33s)
09:46:47 	daemon.go:289: [d887a474afedf] waiting for daemon to start
09:46:47 	daemon.go:321: [d887a474afedf] daemon started
09:46:47 	daemon.go:289: [d887a474afedf] waiting for daemon to start
09:46:47 	daemon.go:321: [d887a474afedf] daemon started
09:46:47 	daemon_linux_test.go:65: assertion failed: error is not nil: Error response from daemon: mkdir /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/5f3a5f580ed0f8999f27b9a7d9f33f251ec812ced9d0998744f104995c20464d: file exists: already exists: failed to start test container
09:46:47 	daemon.go:279: [d887a474afedf] exiting daemon
```

2018-08-17 17:16 UTC, thaJeztah requested changes

2018-08-17 17:16 UTC, thaJeztah commented on vendor.conf
> +github.com/moby/buildkit 95e0348f571a0e500a9b6911992c92f877b44ff1 git://github.com/tonistiigi/buildkit.git
https://github.com/moby/buildkit/pull/560 was merged; so this can likely be "un-forked"

2018-08-20 21:49 UTC, thaJeztah approved these changes
LGTM

2018-08-20 21:52 UTC, abhi approved these changes

2018-08-20 21:55 UTC, tiborvass approved these changes
LGTM

2018-08-20 21:56 UTC, merged