Add dev tooling for image based dockerd
moby/moby pull request #37729
Opened 2018-08-28 21:34 UTC by dhiltgen

**- What I did**

This adds a new makefile target to build the docker
daemon as an image that can be loaded by the new docker
CLI tooling leveraging containerd.

**- How I did it**

**- How to verify it**

```
make image
```
then copy the `moby_engine_0.0.0-dev.tar` to your test environment then
```
ctr --namespace docker image import --oci-name docker.io/moby/engine moby_engine_0.0.0-dev.tar
docker engine update --registry-prefix docker.io/moby --engine-image engine --version 0.0.0-dev
```

Note: this depends on https://github.com/docker/cli/pull/1317 to work properly with the latest packaging.

**- Description for the changelog**

NA - not user visible, just for developer use.

**- A picture of a cute animal (not mandatory but encouraged)**

2018-09-18 02:08 UTC, AkihiroSuda commented on Dockerfile.engine
> +RUN . /binaries-commits && \
why not use  hack/dockerfile/install/proxy.installer

2018-09-18 02:09 UTC, AkihiroSuda commented on Makefile
> +CONTAINERD_SOCK:=/var/run/containerd/containerd.sock
nit: /var/run -> /run

2018-09-18 02:09 UTC, AkihiroSuda commented on Makefile
> +GO_VERSION:=1.10.3
1.11 now?

2018-09-18 02:10 UTC, AkihiroSuda commented on Makefile
> +	@echo "ctr --namespace docker image import --oci-name docker.io/moby/engine $<"
FYI: This is going to be changed: https://github.com/containerd/containerd/pull/2633

cc @dmcgowan

2018-09-18 14:56 UTC, thaJeztah requested changes
Thanks! Left some comments inline.

I think we should evaluate what Dockerfiles and Makefile targets we have, and see if we can combine some things to prevent

a) duplicated effort (not my main concern) 
b) things getting out of sync, possibly silently introducing regressions

2018-09-18 14:56 UTC, thaJeztah commented on Makefile
> +	docker build -t $(DOCKER_HUB_ORG)/$(ENGINE_IMAGE):$(IMAGE_VERSION) \
Wondering; should the local image actually have the "docker hub org" prefixed? Generally we recommend to not use a different naming for locally built images than for the actual image name on Hub (e.g. use `local/myimage` or just `myimage` for the locally built image, then push to `myhub-org/myimage` when pusing)

2018-12-21 17:43 UTC, olljanat commented
@dhiltgen plz check comments above

2018-12-22 07:30 UTC, olljanat commented
Derek add label: status/failing-ci

2019-07-15 13:54 UTC, thaJeztah commented
Looks like this went stale; I'll close this one, but let me know if you want to work on this again @dhiltgen and I can reopen before you push

2019-07-15 13:54 UTC, closed without merging