fix typos
moby/moby pull request #37741
Opened 2018-08-31 15:40 UTC by mooncak

**- What I did**
fix typos in experimental.go and buildargs.go

**- How I did it**
remove duplicate words

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-08-31 15:40 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "fix_typos" git@github.com:mooncak/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-08-31 16:21 UTC, tonistiigi approved these changes

2018-08-31 21:13 UTC, AkihiroSuda requested changes
Please sign the commit with your real name

2018-09-01 13:28 UTC, mooncak commented
@AkihiroSuda Hi，already signed my real name.

2018-09-14 08:48 UTC, thaJeztah approved these changes
LGTM

2018-09-14 09:53 UTC, merged