Fix typo
moby/moby pull request #37981
Opened 2018-10-05 18:46 UTC by 16yuki0702

I think It's a little typo.

2018-10-05 18:46 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "fix_typo" git@github.com:16yuki0702/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-10-05 20:54 UTC, AkihiroSuda requested changes
Please sign the commit with your real full name

2018-10-06 01:32 UTC, 16yuki0702 commented
@AkihiroSuda I'm sorry. I re-signed the commit with my full name.

2018-10-06 02:03 UTC, AkihiroSuda approved these changes

2018-10-08 12:05 UTC, yongtang approved these changes
LGTM

2018-10-08 18:03 UTC, merged