Only add CONTAINER_PARTIAL_MESSAGE if not the last partial
moby/moby pull request #38046
Opened 2018-10-16 05:04 UTC by nonspecialist

Addresses #38045

**- What I did**

Adjust the journald logging driver so that, when writing message partials to journald, all but the last partial are annotated with `CONTAINER_PARTIAL_MESSAGE=true`

**- How I did it**

Transferred the relevant logic from the json-file driver

**- How to verify it**

Cause a container using the journald log driver to emit a long message (>16k), and verify that the `docker logs` output is terminated by `\r\n` instead of just `\r` 

**- Description for the changelog**

Fix journald log driver to correctly mark message partials (ensures end-of-line isn't truncated from long events)

**- A picture of a cute animal (not mandatory but encouraged)**

![capybara](https://user-images.githubusercontent.com/984924/46993836-35d33d00-d15d-11e8-9b33-5693a1126030.jpg)

2018-10-16 05:04 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "master" git@github.com:nonspecialist/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-10-16 18:00 UTC, thaJeztah requested changes
change SGTM, but can you sign-off your commit? (see the comment from @GordonTheTurtle - our bot, for some instructions 🤗)

2018-10-16 18:01 UTC, thaJeztah commented
ping @anusha-ragunathan @cpuguy83 PTAL

2018-10-16 20:54 UTC, nonspecialist commented
Signoff added @thaJeztah

2018-10-17 14:54 UTC, thaJeztah commented
Thanks!

2018-10-17 15:04 UTC, anusha-ragunathan approved these changes
LGTM

2018-10-17 17:35 UTC, cpuguy83 approved these changes
LGTM

2018-10-17 17:36 UTC, merged