Update roadmap to reflect reality.
moby/moby pull request #38097
Opened 2018-10-29 00:07 UTC by cpuguy83

The roadmap is one of the most important ways that a new contributor may
get started on the codebase, as such it is important for it to reflect
the real effort that is currently happening.

This update just brings it up to date. There may be some other efforts
going on and I would encourage people to update the roadmap accordingly
as a separate effort.

2018-10-29 08:00 UTC, vdemeester approved these changes
SGTM :angel:

2018-10-29 17:16 UTC, thaJeztah requested changes

2018-10-29 17:16 UTC, thaJeztah commented on ROADMAP.md
> +Over time we have accumulated a lot of functionaility in the container runtime
s/functionaility/functionality/

2018-10-29 17:16 UTC, thaJeztah commented on ROADMAP.md
> +pieces are now duplicated work now available in other, lower level components
`now` is in this sentence twice; could remove one of them

2018-10-29 17:16 UTC, thaJeztah commented on ROADMAP.md
> +Moby currnetly only utilizes containerd for basic rutime state management, e.g. starting
s/currnetly/currently/

s/rutime/runtime/

2018-10-29 17:16 UTC, thaJeztah commented on ROADMAP.md
> +extensibility while also keeping builds portable, a cheif tenent of Moby's builder.
s/cheif/chief/ (unless you were referring to [this urban dictionary use of that word](https://www.urbandictionary.com/define.php?term=Cheif) :joy:)

2018-10-29 17:16 UTC, thaJeztah commented on ROADMAP.md
> +in their own way without being blocked by Moby maintainers, or even write a
Perhaps something like "a custom syntax" (it doesn't have to be a Dockerfile (like) syntax)

2018-10-29 17:16 UTC, thaJeztah commented
Thanks for starting the work on this! I left some nits, and we'll definitely need more follow-ups, but it's a good start 👍

2018-10-29 18:42 UTC, thaJeztah commented
As came up in the maintainers meeting, I think the big elephant in the room is also the API; how do we want to evolve the API? Split it to a separate repo (keep the definition/specs separate from implementation)? Head more towards a GRPC API, and keep the RESTful API as an optional compatibility layer?

We can keep that for a follow-up, but it's something we should discuss

2018-10-30 16:48 UTC, iaoiui requested changes

2018-10-30 16:59 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "roadmap.md" git@github.com:cpuguy83/docker.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354131192
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-11-02 21:04 UTC, cpuguy83 commented on ROADMAP.md
> +See (buildpacks on buildkit)[https://github.com/tonistiigi/buildkit-pack] as an
Can you write what you'd like to see here and I'll update?

2018-11-02 21:12 UTC, cpuguy83 commented
@AkihiroSuda Added.

2018-11-02 21:34 UTC, thaJeztah commented
ping @moby/moby-maintainers PTAL if things are missing that you'd like to have added

2018-11-08 04:16 UTC, AkihiroSuda approved these changes

2018-11-08 08:50 UTC, vdemeester approved these changes
LGTM :tiger:

2018-11-08 19:29 UTC, cpuguy83 commented on ROADMAP.md
> +See (buildpacks on buildkit)[https://github.com/tonistiigi/buildkit-pack] as an
@tonistiigi WDYT?

2018-11-08 19:58 UTC, tonistiigi commented on ROADMAP.md
> +See (buildpacks on buildkit)[https://github.com/tonistiigi/buildkit-pack] as an
New features for builder and Dockerfile should be implemented first in BuildKit backend using an external Dockerfile implementation from the container images. This allows everyone to test and evaluate the feature without upgrading their daemon. New features should go to experimental channel first and can be part of the `docker/dockerfile:experimental` image. From there they graduate to `docker/dockerfile:latest` and binary releases. The Dockerfile frontend source code is temporarily located at https://github.com/moby/buildkit/tree/master/frontend/dockerfile with separate new features defined with go build tags.

2018-11-11 05:57 UTC, AkihiroSuda commented
Mergeable?

2018-11-15 17:02 UTC, cpuguy83 commented on ROADMAP.md
> +See (buildpacks on buildkit)[https://github.com/tonistiigi/buildkit-pack] as an
Done

2018-11-16 17:18 UTC, thaJeztah approved these changes
Left some minor suggestions and fixes, but LGTM after those are addressed

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +See (buildpacks on buildkit)[https://github.com/tonistiigi/buildkit-pack] as an
The markdown for the link is flipped should be;

```suggestion
See [buildpacks on buildkit](https://github.com/tonistiigi/buildkit-pack) as an
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +- #38043
Looks like GItHub won't render this as a link; can you make it a link? Perhaps add the title of the issue as well;

```suggestion
- [#38043](https://github.com/moby/moby/issues/38043) Proposal: containerd image integration
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +- #32925
Same for this one;

```suggestion
- [#32925](https://github.com/moby/moby/issues/32925) discussion: builder future: buildki
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +- #37375
```suggestion
- [#37375](https://github.com/moby/moby/issues/37375) Proposal: allow running `dockerd` as an unprivileged user (aka rootless mode)
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +- #32866
```suggestion
- [#32866](https://github.com/moby/moby/issues/32866) Replace integration-cli suite with API test suite
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +example this extensibility.
```suggestion
example of this extensibility.
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +New features for the builder and Dockerfile should be implemented first in
```suggestion
New features for the builder and Dockerfile should be implemented first in the
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +their daemon. New features should go to experimental channel first and can be
```suggestion
their daemon. New features should go to the experimental channel first, and can be
```

2018-11-16 17:18 UTC, thaJeztah commented on ROADMAP.md
> +support running the daemon as a nomral, unprivileged user without requiring suid
```suggestion
support running the daemon as a nomral, unprivileged user without requiring `suid`
```

2018-11-22 05:40 UTC, AkihiroSuda commented
@cpuguy83 could you address @thaJeztah 's comments?

2018-11-26 18:46 UTC, cpuguy83 commented
Updated.

2018-12-17 23:02 UTC, olljanat commented
> As came up in the maintainers meeting, I think the big elephant in the room is also the API; how do we want to evolve the API? Split it to a separate repo (keep the definition/specs separate from implementation)?

Based on my experience so far I think that it would be good idea to move at least ```github.com/docker/docker/api/types``` to own repository. Now some changes like this one https://github.com/moby/moby/issues/25885#issuecomment-447657852 needs quite boring PR loop between repositories.

> We can keep that for a follow-up, but it's something we should discuss

Should we create separate issue for that discussion?

2018-12-18 21:42 UTC, cpuguy83 commented
I don't think it belongs in the roadmap, for sure.

2018-12-19 21:19 UTC, olljanat commented
Derek add label: rebuild/janky

2018-12-19 22:18 UTC, thaJeztah commented
There's this issue as well, so we can use that for discussing; https://github.com/moby/moby/issues/32873

2018-12-19 22:19 UTC, thaJeztah approved these changes
whoops, see I didn't LGTM since you updated 😊 😅

2018-12-19 22:20 UTC, thaJeztah commented
Let's merge this; I see there's enough LGTM's, and we can update in follow-ups if desired 👍

2018-12-19 22:20 UTC, merged