builder-next: print warning/error for unsupported ImageBuildOptions
moby/moby pull request #38248
Opened 2018-11-22 08:30 UTC by AkihiroSuda

* Prohibit Squash
* Print warning for other unsupported options

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

@tonistiigi @tiborvass

2018-11-22 08:32 UTC, AkihiroSuda commented
@tonistiigi 

Question: can we implement a new executor with `builder.ExecBackend` instead of the current runcexecutor, so that we can easily implement these runtime options?

2018-11-22 21:24 UTC, thaJeztah requested changes
Thanks! Left some thoughts / suggestions

2019-03-19 03:19 UTC, AkihiroSuda commented on builder/builder-next/builder.go
> +		// return error rather than print a warning, as squash is often used for hiding secrets
ping @tonistiigi

2019-03-19 03:36 UTC, tonistiigi commented on builder/builder-next/builder.go
> +		// return error rather than print a warning, as squash is often used for hiding secrets
Why doesn't squash work? For other options, I don't think we should error on most of them. Maybe only `SecurityOpt` that we probably just don't want anymore. If the removal options are set there is no issue for the user cause buildkit is already guaranteed to not leak containers or partial images. For the cgroup values I think they are optional and warn is ok.

2019-03-19 10:25 UTC, AkihiroSuda commented on builder/builder-next/builder.go
> +		// return error rather than print a warning, as squash is often used for hiding secrets
> Why doesn't squash work? 

seems a bug in `daemon/image/images.go:SquashImage()`?

2019-03-19 10:39 UTC, AkihiroSuda commented on builder/builder-next/builder.go
> +		// return error rather than print a warning, as squash is often used for hiding secrets
Looks like squash itself is working but the resulting image in the store is not tagged with the squashed image ID

2019-03-19 10:50 UTC, AkihiroSuda commented on builder/builder-next/builder.go
> +		// return error rather than print a warning, as squash is often used for hiding secrets
https://github.com/moby/moby/pull/38902

2019-03-19 11:26 UTC, AkihiroSuda commented
As `--squash` turned out to be supported (but broken until https://github.com/moby/moby/pull/38902 gets merged), there is no longer reason to return `error`.

For warning messages, probably they should be implemented on CLI side.

2019-03-19 11:26 UTC, closed without merging