Use errors.Wrap() in daemon/config
moby/moby pull request #38267
Opened 2018-11-24 13:49 UTC by thaJeztah

just a small change; using `errors.Wrap()` preserves the original error

2018-11-24 13:50 UTC, thaJeztah commented
Hm, looks like Hub has some issues;

```
13:50:04 Step 1/93 : FROM golang:1.11.2 AS base
13:50:05 error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
13:50:05 Build step 'Execute shell' marked build as failure
```

2018-11-26 22:02 UTC, cpuguy83 approved these changes
LGTM

2018-11-30 00:05 UTC, yongtang approved these changes
LGTM

2018-11-30 00:06 UTC, yongtang requested changes
Actually, I think one test needs to be adjusted.

2018-11-30 00:28 UTC, thaJeztah commented
Updated the test; thanks!

2018-12-02 12:31 UTC, thaJeztah commented
@yongtang PTAL 🤗

2018-12-03 08:37 UTC, vdemeester approved these changes
LGTM :frog:

2018-12-03 16:30 UTC, yongtang approved these changes
LGTM, Thanks!

2018-12-03 16:30 UTC, merged