Fix volume CreatedAt being altered on initialization
moby/moby pull request #38276
Opened 2018-11-26 15:33 UTC by thaJeztah

fixes https://github.com/moby/moby/issues/38274

The CreatedAt date was determined from the volume's `_data` directory (`/var/lib/docker/volumes/<volumename>/_data`). However, when initializing a volume, this directory is updated, causing the date to change.

Instead of using the `_data` directory, use its parent directory, which is not updated afterwards, and should reflect the time that the volume was created.

**- Description for the changelog**

2018-11-27 00:56 UTC, cpuguy83 requested changes
While the dir is fine to use, I don't like that we are making that assumption in the `localVolume` implementation.

2018-11-27 01:04 UTC, thaJeztah commented
Can you explain? Isn't this path also constructed by the localVolume driver?

2018-11-28 23:36 UTC, cpuguy83 commented
@thaJeztah This is set in the driver implementation, not the volume implementation.
So `localVolume` just has a path that was passed to it from the driver, it doesn't know about the parent.

2018-12-19 15:00 UTC, olljanat commented
Derek add label: rebuild/*

2019-04-18 21:18 UTC, rbjorklin commented
Just stumbled my way over here after encountering #38274, has there been any out-of-band progress on this issue?

2019-07-07 11:26 UTC, collinbarrett commented
Would love to see this merged. Just gave me a scare on a prod server when I `inspect`ed my volumes and saw that they had been created in the last 24 hours when they should have been long-lived persisting my application state.

2023-01-03 17:38 UTC, closed without merging