Removed read only bind of /proc/asound
moby/moby pull request #38299
Opened 2018-11-30 00:48 UTC by jaswdr

**- What I did**
Fixes #38285 

**- How I did it**
Removed read only bind for /proc/asound

**- How to verify it**
Start some video or audio like Youtube or Spotify

```bash
$ docker run --rm ubuntu:latest bash -c "sleep 7; cat /proc/asound/card*/pcm*p/sub*/status | grep state | cut -d ' ' -f2 | grep RUNNING || echo 'not running'"
```
This need to print 'not running'

**- Description for the changelog**
Removed read only bind for /proc/asound

**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://user-images.githubusercontent.com/6409113/49261334-d8ebc780-f428-11e8-819d-44bac9aff83d.png)

2018-11-30 02:07 UTC, thaJeztah commented
ping @justincormack @crosbymichael PTAL

2018-11-30 05:11 UTC, AkihiroSuda commented
No need to mask the path?

2018-11-30 09:32 UTC, cyphar commented
Yes, you will want to mask it -- removing it from the read-only list allows the container to write to it (making the container have more access than before)>

2018-11-30 09:44 UTC, jaswdr commented
@cyphar @AkihiroSuda thanks for the tip, I'll change this

2018-11-30 10:51 UTC, thaJeztah requested changes
Can you use the description from https://github.com/moby/moby/issues/38285 as commit message? I think it's useful information to have in git

2018-11-30 10:54 UTC, thaJeztah commented
Also may want to update the first line of the commit message to mention we're now masking the path (instead of making it readonly)

2018-11-30 11:15 UTC, jaswdr commented
@thaJeztah everything done :+1:

2018-11-30 11:43 UTC, thaJeztah commented
Oh, I meant to have the description in the commit message as well (not only on GitHub); that way, the description is preserved in git history

2018-11-30 12:05 UTC, jaswdr commented
@thaJeztah I think now is good :smile:

2018-11-30 12:49 UTC, thaJeztah commented
Perfect, thanks!

2018-11-30 13:40 UTC, thaJeztah commented
Opened pull requests in containerd to make the same change there; https://github.com/containerd/containerd/pull/2846 (and backports for the release branches)

2018-11-30 13:54 UTC, sw-pschmied commented
Thanks :+1:

2018-11-30 14:12 UTC, thaJeztah commented
Actually, there may be a test that needs updating; https://github.com/moby/moby/blob/3c5eac362884bb60f9c7778966559d04b44cfb6a/integration-cli/docker_cli_run_test.go#L2841-L2848

I think it will still pass, because it's masked (thus writing to `/proc/asound/version` will fail because it doesn't exist). Wondering if that's the correct check though and if it should try _reading_ something there (as well?)

For reference; that test was added in https://github.com/moby/moby/commit/d87da59c79eabb794087f731d3ad51ea98f7a3cc, part of https://github.com/moby/moby/pull/13073 (it may have been cherry-picked from another PR though)

@crosbymichael ^^ looks like you wrote that test originally

2018-11-30 16:37 UTC, justincormack approved these changes

2018-11-30 18:40 UTC, cpuguy83 approved these changes
LGTM

2018-11-30 18:41 UTC, cpuguy83 commented
@thaJeztah Will leave to you to merge since you have a "request change" on it still.

2018-11-30 23:08 UTC, thaJeztah approved these changes
LGTM

We can have a look at improving these tests separately

2018-11-30 23:09 UTC, thaJeztah commented
PowerPC failure is unrelated, and a known flaky test;

```
13:48:59 FAIL: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
```

2018-11-30 23:09 UTC, merged

2018-11-30 23:10 UTC, thaJeztah commented
Thanks for contributing @jaswdr, and congrats on your first PR merged 👍 🎉

2018-12-02 23:38 UTC, jaswdr commented
@thaJeztah thanks a lot, I'll keep going trying to help :+1:

2019-01-15 10:56 UTC, pvizeli commented
That is bad, now only privileged add-ons can play music :(

2019-01-15 11:00 UTC, AkihiroSuda commented
https://github.com/docker/cli/pull/1347 will give you flexibility to allow access to /proc/asound without passing `--privileged`