Fix mistake in docs/contributing/test.md running specific unit test #38096
moby/moby pull request #38294
Opened 2018-11-29 13:24 UTC by jaswdr

**- What I did**
Fixes #38096

**- How I did it**
Updating the docs with more specific path when running specific unit tests

**- How to verify it**
Running the code bellow.

```sh
$ TESTDIRS='github.com/docker/docker/opts' TESTFLAGS='-test.run $^TestValidateIPAddress$' make test-unit
```

**- Description for the changelog**
Corrected running specific unit tests script in docs

**- A picture of a cute animal (not mandatory but encouraged)**

![image](https://user-images.githubusercontent.com/6409113/49224742-597adb80-f3c9-11e8-9b23-760de3837161.png)

2018-11-29 13:30 UTC, AkihiroSuda approved these changes

2018-12-08 18:08 UTC, thaJeztah requested changes

2018-12-08 18:08 UTC, thaJeztah commented on docs/contributing/test.md
> +$ TESTDIRS='github.com/docker/docker/opts' TESTFLAGS='-test.run $^TestValidateIPAddress$' make test-unit
Shouldn't this be updated on line 151 instead?

2018-12-09 19:13 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "issue-38096" git@github.com:jaswdr/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354132952
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2018-12-10 12:45 UTC, thaJeztah requested changes
left a comment; also could you squash your commits, so that there's only a single commit in this PR?

2018-12-10 12:45 UTC, thaJeztah commented on docs/contributing/test.md
> +$ TESTDIRS='github.com/docker/docker/opts' TESTFLAGS='-test.run $^TestValidateIPAddress$' make test-unit
This section talks about the `TESTDIRS` environment variable, so I guess this should be;

```suggestion
$ TESTDIRS='github.com/docker/docker/opts' make test-unit
```

2018-12-10 13:02 UTC, jaswdr commented
@thaJeztah I think now is ok

2018-12-11 11:55 UTC, thaJeztah approved these changes
LGTM

thank you so much!

2018-12-11 11:55 UTC, merged