[WIP] Attach: use epoll to check for client close
moby/moby pull request #38300
Opened 2018-11-30 05:23 UTC by xu001186

This prevents leaks on attach where there is no data to read from the
stdio streams of the container, and as such the `io.Copy` just blocks.

Signed-off-by: Brian Goff <cpuguy83@gmail.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2018-12-01 01:13 UTC, cpuguy83 requested changes

2018-12-01 01:13 UTC, cpuguy83 commented on api/server/router/container/container_routes.go
> +		func() {
Hmm, the context from the request should be closed when the connection closes. Is this sufficient?

2018-12-01 01:13 UTC, cpuguy83 commented on api/server/router/container/container_routes.go
> +		func() {
Oh maybe not because of hijack...

2019-07-14 11:55 UTC, thaJeztah commented
ping @xu001186 were you still working on this?

2019-10-03 18:50 UTC, closed without merging