Support adding any log info field to extra attrs
moby/moby pull request #38312
Opened 2018-12-03 19:10 UTC by cpuguy83

Adds a new generic log-opt "loginfo" which takes a comma separated list
of field names fromt he log info struct.

This is somewhat supported by way of log tags, however log tags mean
different things for different drivers and is not always desirable (e.g.
fluentd uses log tags for routing).

This allows populating the "extras" map with any field from the log info
struct.

Note I chose to make sure that the fields used by log tag templates are
the same field names used for extras. This could be extended further to
support some actual templating (via some new log-opt key).

 ---

This is essentially carrying #27859 with a simpler implementation and that doesn't add any new fields for users to have to figure out since it is the same field names as used in templates for log tags.

Closes #27859

2018-12-23 22:56 UTC, dnephin approved these changes
LGTM

2018-12-23 22:56 UTC, dnephin commented on daemon/logger/loginfo_test.go
> +			desc: "all thing things",
"all the things" ?

2018-12-24 19:11 UTC, thaJeztah requested changes
Thanks!

I gave this a spin, but I think the non-string types are a bit troublesome here (`Config`, `ContainerArgs`, `ContainerCreated`, `ContainerEnv`, `ContainerLabels`). Here's what I tried:

Create a container with some labels and env-vars, and set all available options for `loginfo`;

```bash
docker run -dit \
	--log-opt loginfo=Config,ContainerID,ContainerName,ContainerEntrypoint,ContainerArgs,ContainerImageID,ContainerImageName,ContainerCreated,ContainerEnv,ContainerLabels,LogPath,DaemonName \
	--name mycontainer \
	--env FOO=bar,BAR=qux \
	--label labe1=value1,label2=value2 \
	busybox echo "hello docker"
```

View the logs;


```bash
docker logs --details mycontainer
Config=%3Cmap%5Bstring%5Dstring+Value%3E,ContainerArgs=%3C%5B%5Dstring+Value%3E,ContainerCreated=%3Ctime.Time+Value%3E,ContainerEntrypoint=echo,ContainerEnv=%3C%5B%5Dstring+Value%3E,ContainerID=c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27,ContainerImageID=sha256%3A59788edf1f3e78cd0ebe6ce1446e9d10788225db3dedcfd1a59f764bad2b2690,ContainerImageName=busybox,ContainerLabels=%3Cmap%5Bstring%5Dstring+Value%3E,ContainerName=%2Fmycontainer,DaemonName=docker,LogPath=%2Fvar%2Flib%2Fdocker%2Fcontainers%2Fc4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27%2Fc4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27-json.log hello docker
```

First of all, the output is URL-encoded (which makes it not very readable)

URL-decoding the output makes it a bit more readable;

```
Config=<map[string]string Value>,ContainerArgs=<[]string Value>,ContainerCreated=<time.Time Value>,ContainerEntrypoint=echo,ContainerEnv=<[]string Value>,ContainerID=c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27,ContainerImageID=sha256:59788edf1f3e78cd0ebe6ce1446e9d10788225db3dedcfd1a59f764bad2b2690,ContainerImageName=busybox,ContainerLabels=<map[string]string Value>,ContainerName=/mycontainer,DaemonName=docker,LogPath=/var/lib/docker/containers/c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27/c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27-json.log
```

However, there's  various fields that are not very useful currently;

```
Config=<map[string]string Value>,
ContainerArgs=<[]string Value>,
ContainerCreated=<time.Time Value>,
ContainerEntrypoint=echo,
ContainerEnv=<[]string Value>,
ContainerID=c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27,
ContainerImageID=sha256:59788edf1f3e78cd0ebe6ce1446e9d10788225db3dedcfd1a59f764bad2b2690,
ContainerImageName=busybox,
ContainerLabels=<map[string]string Value>,
ContainerName=/mycontainer,
DaemonName=docker,
LogPath=/var/lib/docker/containers/c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27/c4544e29327d56ca0d56d3187e52b55078808e2777b6b20e545814ffef445f27-json.log
```

I also wonder if we should;

- Exclude `labels` and `env` here, given that they already have their own option (`--log-opt labels=one,two,three` - same for `env`)
- Either use a go-template for this, or possibly exclude `Config`
- `LogPath` seems a bit "meta"

2018-12-24 19:11 UTC, thaJeztah commented on daemon/logger/factory.go
> +	logInfoKey:        true,
This should be added to the API history (mention of the new option); https://github.com/moby/moby/blob/master/docs/api/version-history.md

2019-01-05 00:51 UTC, cpuguy83 commented
Perhaps we should just support templates here?

2019-02-21 19:25 UTC, cpuguy83 commented on daemon/logger/loginfo_test.go
> +			desc: "all thing things",
lol

2019-10-03 18:35 UTC, cpuguy83 commented
This didn't get any reviews and perhaps a slightly different approach should be taken (e.g. templates).

2019-10-03 18:35 UTC, closed without merging