image/spec/v1.1.md formatting error (fixes #38337)
moby/moby pull request #38338
Opened 2018-12-10 09:23 UTC by Bevisy

**- What I did**
delete unnecessary line 422 - "\</dd\>"
**- How I did it**
for formatting
**- How to verify it**
just view it
**- Description for the changelog**
delete unnecessary line 422 - "\</dd\>"

Signed-off-by: Bevisy Zhang <binbin36520@gmail.com>

2018-12-10 12:36 UTC, thaJeztah requested changes
Thanks for contributing! I don't think this is the correct fix, but I left a comment with an alternative. Could you update your PR to use that alternative instead?

2018-12-10 12:36 UTC, thaJeztah commented on image/spec/v1.1.md
> -    </dd>
This `</dd>` should not be removed; the actual fix is to remove the blank lines at line 408 and 410 instead. Similar to what was done in https://github.com/moby/moby/pull/37051

```patch
diff --git a/image/spec/v1.1.md b/image/spec/v1.1.md
index de74d91a19..8d0ec892da 100644
--- a/image/spec/v1.1.md
+++ b/image/spec/v1.1.md
@@ -405,9 +405,7 @@ whitespace. It has been added to this example for clarity.
             filesystem).
           </li>
         </ul>
-
 Here is an example history section:
-
 <pre>"history": [
   {
     "created": "2015-10-31T22:22:54.690851953Z",
```

2018-12-10 16:13 UTC, thaJeztah requested changes
thanks! changes look good, but can you squash your commits?

Let me know if you need help doing so

2018-12-12 02:49 UTC, Bevisy commented
@thaJeztah Thanks for your patience.I've already changed it .

2018-12-12 12:57 UTC, thaJeztah approved these changes
LGTM, thanks!

2018-12-12 12:57 UTC, merged