Add config for reaction and topissues bots
moby/moby pull request #38443
Opened 2018-12-27 21:23 UTC by olljanat

**- What I did**
Added configurations for 
- [Reaction Comments](https://probot.github.io/apps/reaction/) bot which deletes reaction comments, such as +1, and encourages the use of GitHub reactions.
- [Top Issues](https://probot.github.io/apps/topissues/) bot which labels issues with the most 👍 reactions

NOTE: this PR only adds configurations for these bots. Someone with admin rights must enable them after this one is merged.

Related to #35490

**- How to verify it**
These bots are enabled to playground repository https://github.com/olljanat/moby-bot-lab/

**- A picture of a cute animal (not mandatory but encouraged)**
![bg robot-chameleon-1920x1200](https://user-images.githubusercontent.com/6213926/50494820-3d04aa00-0a2e-11e9-94df-bb627572ea93.jpg)

2019-01-03 10:13 UTC, vdemeester approved these changes
LGTM :angel: :stuck_out_tongue_closed_eyes:

2019-01-03 17:39 UTC, thaJeztah requested changes
Thanks @olljanat ! I left some thoughts inline.

One thing that was great about the old bot is that it would collect the upvotes, so the voter's "+1" didn't get lost, but I guess that's not a big issue. Wondering if the the person and other participants get an e-mail notification if the bot updates their comment; did you try if that's the case? (Thinking what's best there; 👍 that the "spammer" gets a notification, but 👎 that it actually amplifies their "spam" to everyone on the thread 🤔

2019-01-03 17:39 UTC, thaJeztah commented on .github/reaction.yml
> +  :wave: @{comment-author}, did you mean to use
I think we should tweak the message a bit (_"did you mean to use"_ may sound a bit so/so (and I know people can get offended easily)).

Here's the text we used when we had "leeroy" running; https://github.com/docker/leeroy/blob/2fe5a91ab1f8a99baf64284abaae924687ed5570/github/issue.go#L13-L24

And/or we could link to the ["reporting other issues"](https://github.com/moby/moby/blob/7b3966245de27b753c6acfe0347833811ed9eed8/CONTRIBUTING.md#reporting-other-issues) paragraph (we may want to tweak that one a bit as well)

2019-01-03 17:39 UTC, thaJeztah commented on .github/topissuebot.yml
> +numberOfIssuesToLabel: 50
Do we want this many? That's two pages on GitHub 🤔 - here's the current list of most :+1:'d issues; https://github.com/moby/moby/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

2019-01-03 17:39 UTC, thaJeztah commented on .github/topissuebot.yml
> +labelName: ":thumbsup: Top Issue!"
Thinking of some better label for this (to fit a bit more in our current label scheme) `top-voted` ?

2019-05-05 14:47 UTC, olljanat commented
Looks that link
https://github.com/moby/moby/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
actually tells what I wanted to see so closing this now.

2019-05-05 14:47 UTC, closed without merging