Add Git auto signoff hook
moby/moby pull request #38505
Opened 2019-01-07 08:58 UTC by glensc

**- What I did**

1. add example hook. [git/templates/hooks--prepare-commit-msg.sample](https://github.com/git/git/blob/v2.20.1/templates/hooks--prepare-commit-msg.sample)
2. enabled needed section
3. updated contributing odc

**- How I did it**

with ❤️ 

**- How to verify it**

1. checkout this branch
2. invoke the mentioned command
3. make some commit
4. `git show` that commit

**- Description for the changelog**

Add example Git hook to make all commits include `Signed-Off-By` lines.

2019-01-07 12:40 UTC, thaJeztah requested changes
Thanks! 😍 

I left some comments below; also, I haven't used git hooks much myself, so let me ask @tianon @albers to have a look (as they're much more capable ba(sh) scripters than I am 🤗

2019-01-07 12:40 UTC, thaJeztah commented on CONTRIBUTING.md
> +```
nit: if you add a `bash` type-hint, GitHub will apply code-highlighting to the example below;

```suggestion
```bash
```

2019-01-07 12:40 UTC, thaJeztah commented on hack/git/hooks/prepare-commit-msg
> +#!/bin/sh
We generally use the `hack` directory for scripts that are actually used in CI and/or called from the `Makefile`.

Thinking that the `contrib/` directory would be a better place to put this 🤔

2019-01-07 15:55 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "git-autosign-hook" git@github.com:glensc/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354510312
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2019-01-07 15:59 UTC, glensc commented
uh. the @GordonTheTurtle needs updating (or policies), as I accepted the proposed change via GitHub UI which resulted this commit 89800dd:

```
commit 89800ddc398d4c848cdad75f2abd8433fea899a7 (HEAD -> git-autosign-hook, origin/git-autosign-hook)
Author: Sebastiaan van Stijn <thaJeztah@users.noreply.github.com>
Date:   Mon Jan 7 17:55:02 2019 +0200

    add syntax type hint

    Co-Authored-By: glensc <glen@pld-linux.org>
```

yet bot complained about this: https://github.com/moby/moby/pull/38505#issuecomment-451981343

Such scenario is not addressed (in contributing.md as well). I should probably just squash for the problem to go away this time.

2019-01-07 17:03 UTC, thaJeztah commented
> I accepted the proposed change via GitHub UI which resulted this commit 89800dd:

Hm.. interesting. Perhaps something I can post as feedback on that feature (as in: perhaps they can provide an option to make it DCO sign-off that commit 🤔 )

> yet bot complained about this: #38505 (comment)
> Such scenario is not addressed (in contributing.md as well). I should probably just squash for the
> problem to go away this time.

I think the bot is correct (as in; there's a commit in the PR that's missing a `signed-off-by`), so with the interactive rebase, and `commit -s --amend --no-edit`, each commit gets a `signed-off-by` added

But yes, there's no need to keep those suggested changes as separate commits

2019-01-07 17:11 UTC, tianon commented
I feel like we discussed adding something like this once but it was ultimately rejected due to something with lawyers and encouraging contributors to be explicit about their Sign-off of contributed code; does that sound familiar @thaJeztah? Might've been before you joined our merry band that we discussed it. 😅

2019-01-07 17:53 UTC, cpuguy83 commented
@tianon Not sure, but I have similar concerns. Sign-offs should be explicit.

2019-01-07 18:01 UTC, thaJeztah commented
>  does that sound familiar @thaJeztah? Might've been before you joined our merry band that we discussed it.

hm.. not sure I recall that discussion, so could definitely be before I got involved (or I just forgot about it 😅 ).

> I have similar concerns. Sign-offs should be explicit.

I can see the point; OTOH, it's not something we install by default (and people could already be using this, or have `git commit -s` configured as an alias for `git commit`). 🤷‍♂️

2019-01-07 20:34 UTC, tianon commented
> I can see the point; OTOH, it's not something we install by default (and people could already be using this, or have `git commit -s` configured as an alias for `git commit`). :man_shrugging:

Right (I've done so myself for years now), but the difference is that setting up their environment that way is still a pretty explicit choice that they've made for themselves.  Providing this (arguably fairly simple) script _for_ them could be argued to be a recommendation that they do so, if I recall the previous discussion properly.

2019-01-08 09:59 UTC, albers commented
The situation reminds me to _.gitignore_ files:
Instead of trying to maintain a complete list of all IDE specific files which will end up in identical files for most git projects, we switched to encouraging users to set up a global gitignore file: https://github.com/moby/moby/blob/master/.gitignore#L2-L3

Similarly, it would be helpful for users if every project shipped the same example hook file. But I think this does not make sense and is out of scope for a given project.

I think referencing an external file and description is better.

2019-01-22 13:43 UTC, thaJeztah commented
> I think referencing an external file and description is better.

Perhaps a blogpost that describes how to sign-off (manually and/or automatically with a hook) would work; then the choice to take the automatic approach is left with the user, and both options can be described?


Looking at the discussion above, and the concerns being raised, I'll have to close this PR (sorry!)

Feel free to continue the conversation though, and thanks so much for taking the time to open this PR 🤗

2019-01-22 13:43 UTC, closed without merging