Bumping Swarmkit's version
moby/moby pull request #38525
Opened 2019-01-10 00:36 UTC by wk8

Mainly for the sake of testing the new "soft delete" capabilities of
Swarmkit, see more at
https://github.com/docker/swarmkit/pull/2778

Signed-off-by: Jean Rouge <jer329@cornell.edu>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2019-01-10 07:15 UTC, olljanat commented
@wk8 Janky failure:
```
02:50:56 ============================= test session starts ==============================
02:50:56 platform linux2 -- Python 2.7.13, pytest-2.9.1, py-1.7.0, pluggy-0.3.1
02:50:56 rootdir: /docker-py, inifile: pytest.ini
02:50:56 plugins: cov-2.1.0
02:50:57 collected 338 items
02:50:57 
02:51:23 ../../../../../docker-py/tests/integration/api_build_test.py ....s..s........
02:51:24 ../../../../../docker-py/tests/integration/api_client_test.py .......
02:51:25 ../../../../../docker-py/tests/integration/api_config_test.py .....
02:52:49 ../../../../../docker-py/tests/integration/api_container_test.py ....x....x.......x............................................................
02:52:59 ../../../../../docker-py/tests/integration/api_exec_test.py .............
02:53:06 ../../../../../docker-py/tests/integration/api_healthcheck_test.py ....
02:53:17 ../../../../../docker-py/tests/integration/api_image_test.py ...s........s....
02:53:52 ../../../../../docker-py/tests/integration/api_network_test.py ...........................
02:54:15 ../../../../../docker-py/tests/integration/api_plugin_test.py ...........
02:54:16 ../../../../../docker-py/tests/integration/api_secret_test.py .....
02:54:35 ../../../../../docker-py/tests/integration/api_service_test.py ............................FF.......F.FF.............
02:55:07 ../../../../../docker-py/tests/integration/api_swarm_test.py ..s...x......
02:55:22 ../../../../../docker-py/tests/integration/api_volume_test.py .........
02:55:22 ../../../../../docker-py/tests/integration/client_test.py ....
02:55:23 ../../../../../docker-py/tests/integration/errors_test.py .
02:56:11 ../../../../../docker-py/tests/integration/models_containers_test.py ..............................
02:56:27 ../../../../../docker-py/tests/integration/models_images_test.py .............
02:56:28 ../../../../../docker-py/tests/integration/models_networks_test.py ....
02:56:34 ../../../../../docker-py/tests/integration/models_nodes_test.py .
02:56:35 ../../../../../docker-py/tests/integration/models_resources_test.py .
02:56:37 ../../../../../docker-py/tests/integration/models_services_test.py ......F.......X.
02:56:38 ../../../../../docker-py/tests/integration/models_swarm_test.py .
02:56:38 ../../../../../docker-py/tests/integration/models_volumes_test.py ..
02:56:42 ../../../../../docker-py/tests/integration/regression_test.py ......
02:56:42 
02:56:42  generated xml file: /go/src/github.com/docker/docker/bundles/test-docker-py/results.xml 
02:56:42 =========================== short test summary info ============================
02:56:42 XFAIL ../../../../../docker-py/tests/integration/api_container_test.py::CreateContainerTest::test_create_with_cpu_rt_options
02:56:42   CONFIG_RT_GROUP_SCHED isn't enabled
02:56:42 XFAIL ../../../../../docker-py/tests/integration/api_container_test.py::CreateContainerTest::test_create_with_init_path
02:56:42   init-path removed in 17.05.0
02:56:42 XFAIL ../../../../../docker-py/tests/integration/api_container_test.py::CreateContainerTest::test_create_with_storage_opt
02:56:42   Not supported on most drivers
02:56:42 XFAIL ../../../../../docker-py/tests/integration/api_swarm_test.py::SwarmTest::test_init_swarm_with_log_driver
02:56:42   This doesn't seem to be taken into account by the engine
02:56:42 SKIP [1] tests/integration/api_image_test.py:289: Doesn't work inside a container - FIXME
02:56:42 SKIP [1] /docker-py/tests/integration/api_swarm_test.py:31: Test stalls the engine on 1.12.0
02:56:42 SKIP [3] /docker-py/tests/helpers.py:69: Feature requires Docker Engine experimental mode
02:56:42 =================================== FAILURES ===================================
02:56:42 _____________ ServiceTest.test_create_service_with_unicode_config ______________
02:56:42 /docker-py/tests/integration/api_service_test.py:642: in test_create_service_with_unicode_config
02:56:42     config_id = self.client.create_config(config_name, config_data)
02:56:42 /docker-py/docker/utils/decorators.py:34: in wrapper
02:56:42     return f(self, *args, **kwargs)
02:56:42 /docker-py/docker/api/config.py:35: in create_config
02:56:42     self._post_json(url, data=body), True
02:56:42 /docker-py/docker/api/client.py:229: in _result
02:56:42     self._raise_for_status(response)
02:56:42 /docker-py/docker/api/client.py:225: in _raise_for_status
02:56:42     raise create_api_error_from_http_exception(e)
02:56:42 /docker-py/docker/errors.py:31: in create_api_error_from_http_exception
02:56:42     raise cls(e, response=response, explanation=explanation)
02:56:42 E   APIError: 409 Client Error: Conflict ("rpc error: code = AlreadyExists desc = config favorite_touhou already exists")
02:56:42 _____________ ServiceTest.test_create_service_with_unicode_secret ______________
02:56:42 /docker-py/tests/integration/api_service_test.py:590: in test_create_service_with_unicode_secret
02:56:42     secret_id = self.client.create_secret(secret_name, secret_data)
02:56:42 /docker-py/docker/utils/decorators.py:34: in wrapper
02:56:42     return f(self, *args, **kwargs)
02:56:42 /docker-py/docker/api/secret.py:46: in create_secret
02:56:42     self._post_json(url, data=body), True
02:56:42 /docker-py/docker/api/client.py:229: in _result
02:56:42     self._raise_for_status(response)
02:56:42 /docker-py/docker/api/client.py:225: in _raise_for_status
02:56:42     raise create_api_error_from_http_exception(e)
02:56:42 /docker-py/docker/errors.py:31: in create_api_error_from_http_exception
02:56:42     raise cls(e, response=response, explanation=explanation)
02:56:42 E   APIError: 409 Client Error: Conflict ("rpc error: code = AlreadyExists desc = secret favorite_touhou already exists")
02:56:42 ________________________ ServiceTest.test_list_services ________________________
02:56:42 /docker-py/tests/integration/api_service_test.py:76: in test_list_services
02:56:42     assert len(test_services) == 0
02:56:42 E   AssertionError: assert 9 == 0
02:56:42 E    +  where 9 = len([{'CreatedAt': '2019-01-10T02:54:17.610899445Z', 'Endpoint': {'Spec': {}}, 'ID': 'obpnh07dag0cwi8z2yu3phd68', 'Pending...10T02:54:23.874616888Z', 'Endpoint': {'Spec': {}}, 'ID': 'x1i3jvdrgrei9h1yj9i9l2bk7', 'PendingDelete': True, ...}, ...])
02:56:42 ____________________ ServiceTest.test_remove_service_by_id _____________________
02:56:42 /docker-py/tests/integration/api_service_test.py:118: in test_remove_service_by_id
02:56:42     assert len(test_services) == 0
02:56:42 E   AssertionError: assert 4 == 0
02:56:42 E    +  where 4 = len([{'CreatedAt': '2019-01-10T02:54:17.610899445Z', 'Endpoint': {'Spec': {}}, 'ID': 'obpnh07dag0cwi8z2yu3phd68', 'Pending...9-01-10T02:54:24.061397702Z', 'Endpoint': {'Spec': {}}, 'ID': 'fet1grsijuqh9q06mo4t7t8w7', 'PendingDelete': True, ...}])
02:56:42 ___________________ ServiceTest.test_remove_service_by_name ____________________
02:56:42 /docker-py/tests/integration/api_service_test.py:124: in test_remove_service_by_name
02:56:42     assert len(test_services) == 0
02:56:42 E   AssertionError: assert 5 == 0
02:56:42 E    +  where 5 = len([{'CreatedAt': '2019-01-10T02:54:24.142811361Z', 'Endpoint': {'Spec': {}}, 'ID': '0p7bqsqb23lezynqqaquroex0', 'Pending...9-01-10T02:54:24.061397702Z', 'Endpoint': {'Spec': {}}, 'ID': 'fet1grsijuqh9q06mo4t7t8w7', 'PendingDelete': True, ...}])
02:56:42 _________________________ ServiceTest.test_list_remove _________________________
02:56:42 /docker-py/tests/integration/models_services_test.py:80: in test_list_remove
02:56:42     assert service not in client.services.list()
02:56:42 E   AssertionError: assert <Service: bke7s3fwnr> not in [<Service: bke7s3fwnr>, <Service: de3pe7myoh>, <Service: df7yub3t6n>, <Service: ozisoi19iv>, <Service: u4fwx2vhug>, <Service: uwsemomnq7>, ...]
02:56:42 E    +  where [<Service: bke7s3fwnr>, <Service: de3pe7myoh>, <Service: df7yub3t6n>, <Service: ozisoi19iv>, <Service: u4fwx2vhug>, <Service: uwsemomnq7>, ...] = <bound method ServiceCollection.list of <docker.model [...]

2019-01-10 07:16 UTC, olljanat commented
Derek add label: rebuild/powerpc

2019-01-10 07:20 UTC, cpuguy83 commented
Yeah, this seems like a breaking change from swarmkit.

2019-01-11 18:30 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "wk8/bump_swarmkit" git@github.com:wk8/moby.git somewhere
$ cd somewhere
$ git rebase -i HEAD~842354192848
editor opens
change each 'pick' to 'edit'
save the file and quit
$ git commit --amend -s --no-edit
$ git rebase --continue # and repeat the amend for each commit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2019-01-13 03:13 UTC, wk8 commented
Note to reviewers: the build failure should be fixed once https://github.com/docker/docker-py/pull/2228 is merged. Thanks!

2019-01-13 03:13 UTC, wk8 commented on internal/test/daemon/config.go
> -	}
Note for all of these: `d.NewClientT(t)` already does the exact same thing.

2019-01-13 04:17 UTC, cpuguy83 commented
Sorry no, changing docker-py is not a valid fix for a breaking API change.

2019-01-13 04:19 UTC, cpuguy83 commented
These tests exist to pinpoint issues like this, just changing the test is not how to deal with this.

This is a breaking change in swarmkit. It should be addressed there, and if not then we need to change the implementation here such that these changes are not breaking existing users.

2019-01-13 04:49 UTC, wk8 commented
@cpuguy83 : yes, this is absolutely a breaking change in Swarmkit, that has been deemed the lesser of two evils after ample discussion within the Swarmkit team and outside of it.

Since it is indeed a breaking change, and changes a behavior that tests both in this repo and in docker-py rely upon, it seems logical to me to adapt the tests to test the new desired behavior?

2019-01-13 04:59 UTC, olljanat commented
@wk8 remember that Moby API must be backward compatible so you cannot change behavior for API versions < 1.40

2019-01-15 20:12 UTC, cpuguy83 commented
Glossing over the actual bug being solved... I'll assume this had due diligence applied in how to solve the problem... why can't async delete be opt-in?

If swarmkit is not going to handle this, then we need to handle it in moby. We simply cannot have such a breaking change.

Basically:
```
Create("foo")
Delete("foo")
Create("foo")
```

Should just work. If `Delete` returns then "foo" must be available immediately again.

2019-01-15 20:17 UTC, cpuguy83 commented
btw, when I say "opt-in", I mean the delete internally would still be async (marked for removal) but the API would either only return when it is actually freed or if async=true it can return as soon as it has been marked.

2019-01-15 20:47 UTC, wk8 commented
@cpuguy83 : sorry, I certainly didn't mean to gloss over the actual problem, apologies if it came across that way.

The actual problem being solved is that currently nothing prevents you from creating a service, with a network attached to it, and then deleting the service and the network even if the service's containers have not shut down yet. This means the containers can't perform their cleanup properly if they need to use the network to do so; and can also lead to interesting failures if a network and/or a service with the same name are re-created before the old ones are gone.

The same applies to any service-level resource down the road.

Note that it's only a breaking change precisely if you do anything that assumes (and _needs_ to assume) that a service gets instantaneously deleted, which is conceptually wrong, and will lead to errors if that's really an assumption you need.

I understand your concern, though; how would you feel about, depending on the client's version:
* if < 1.40, then we only return from the API call after the delete has occurred
* otherwise, we return instantly, as we used to, but the actual removal happens asynchronously

That would ensure we don't break older clients, while still also returning fast in the 99% use case, when people don't try re-creating a service or a service-level resource right away.

2019-01-15 21:28 UTC, thaJeztah requested changes
See my comment inline; about adding a separate field for this.

I also agree with @cpuguy83  - we can't change this behavior and make it the default; doing so will be breaking any consumer of the API out there; this behavior should be opt-in, and enabled through a new option in the API request (to be added in API v1.40 and up).

2019-01-15 21:34 UTC, cpuguy83 commented on api/types/swarm/service.go
> +	PendingDelete bool          `json:",omitempty"`
K8s uses `DeletionTimestap`, though it is a little different, basically the timestamp is the time when the object should no longer be visible:

> The resource is expected to be deleted (no longer visible
    // from resource lists, and not reachable by name) after the time in this field, once the
    // finalizers list is empty.

2019-02-21 19:26 UTC, thaJeztah commented
Closing for now

2019-02-21 19:26 UTC, closed without merging