Replace waitAndAssert in config_test.go with poll.WaitOn
moby/moby pull request #38547
Opened 2019-01-12 22:40 UTC by yongtang

This fix replaces waitAndAssert in config_test.go with poll.WaitOn
so that the testing is consistent with all other tests in integration.

Also, config_test.go uses to wait and sleep for 2 * (1 minutes) to get the task
info. This fix combined those two sleep and wait for 1 mins. Think 1 min
is enough for config test.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2019-01-12 23:54 UTC, thaJeztah commented
oh! in case you were thinking on moving the `SwarmLockUnlock` tests to `integration/`. I had this written for the NodeStatus; https://github.com/moby/moby/compare/master...thaJeztah:poll_node 😅

2019-01-13 16:18 UTC, olljanat commented
Derek add label: rebuild/*

2019-01-14 01:35 UTC, thaJeztah requested changes
Left some ideas; actually part of that code written while reviewing earlier today, so I pushed it as a branch; https://github.com/moby/moby/pull/38558 😅

2019-01-14 01:35 UTC, thaJeztah commented on integration/config/config_test.go
> +	poll.WaitOn(t, getServiceTask, swarm.ServicePoll, poll.WithTimeout(1*time.Minute))
I wonder if we should split this into two steps;

- check if the service reconciled (check if the desired number of tasks is running); that may be more generic / reusable
- once that's the case, do the `inspect` on its task

2019-01-15 04:06 UTC, yongtang commented
Thanks @thaJeztah for the review. I have updated the PR and used the changes you made to `swarm.GetRunningTasks`. Please take a look

2019-01-15 14:15 UTC, thaJeztah approved these changes
LGTM, thanks!

2019-01-15 14:27 UTC, vdemeester approved these changes
LGTM :tiger:

2019-01-15 14:27 UTC, merged