Use a regex to match labels
moby/moby pull request #38586
Opened 2019-01-16 22:15 UTC by robin-thoni

**- What I did**
I added an option to the log drivers to include as attributes the labels that match a regex. (Similar to #27561).

Documentation update in available in docker/docker.github.io#
**- How I did it**
I added the `--labels-regex` option to the logging drivers.
I added code to scan and match container labels against the regex supplied in the above option. I add these matching variables to the 'extra' map in the log driver.
**- How to verify it**
I updated `gelf_test.go`, `jsonfilelog_test.go` and `syslog_test.go` to test the new option.
**- Description for the changelog**
Allow the log drivers to pick up labels that match a supplied regular expression.

**- A picture of a cute animal (not mandatory but encouraged)**
![20190101_202730_](https://user-images.githubusercontent.com/9640353/51281750-3f2da900-19db-11e9-9a30-6ba1da5a02c5.jpg)

2019-01-16 22:15 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "labels-regex" git@github.com:robin-thoni/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2019-01-19 14:03 UTC, olljanat commented
Derek add label: rebuild/experimental

2019-01-25 12:12 UTC, robin-thoni commented
I feel like I'm not responsible for this windowsRS1 fail, am I?

2019-01-25 12:45 UTC, olljanat commented
@robin-thoni that is known flaky test which is waiting for #38595 
Let's try once more.

2019-02-02 15:15 UTC, cpuguy83 requested changes
LGTM, but needs a test.
Also seems like you might be missing support in the "local" driver.

Come to think of it, I believe we have a thing for global options which get filtered out when they are passed to the log drivers option validator.

2019-03-02 17:00 UTC, robin-thoni commented
Sorry for long delay.

> LGTM, but needs a test.

There's a test in `daemon/logger/jsonfilelog/jsonfilelog_test.go` and minor checks in `daemon/logger/syslog/syslog_test.go` and `daemon/logger/gelf/gelf_test.go` (the same kind as in the original pull request for `env-regex`).

> Also seems like you might be missing support in the "local" driver.

Not sure this kind of thing is supported in "local". At least, it does not have any particular behavior for `env-regex`.

> Come to think of it, I believe we have a thing for global options which get filtered out when they are passed to the log drivers option validator.

Not sure what you're referring to. I made equivalent changes to what was made by @cpuguy83 in #27565.

Thanks!

2019-03-14 15:21 UTC, robin-thoni commented
ping :)

2019-03-21 21:05 UTC, kolyshkin approved these changes
LGTM

2019-04-09 22:01 UTC, fntlnz approved these changes
SGTM :angel:

2019-04-24 18:38 UTC, robin-thoni commented
Are we ready to merge then?

2019-04-26 01:26 UTC, fntlnz commented
cc/ @cpuguy83  This one is waiting another review from you

2019-04-26 22:15 UTC, cpuguy83 approved these changes
LGTM

2019-04-29 19:25 UTC, merged