Print a warning if config has an unknown argument
moby/moby pull request #38607
Opened 2019-01-21 20:02 UTC by sh7dm

Fixes #32530

**- What I did**
Print a warning if config has an unknown argument.

**- How I did it**
Add an additional check

**- How to verify it**
Check it with config like in #32530

**- Description for the changelog**

Print a warning if config has an unknown argument

**- A picture of a cute animal (not mandatory but encouraged)**
![default](https://user-images.githubusercontent.com/19504461/51496359-8ac3c680-1dd0-11e9-90b9-b36b3de200e5.png)

2019-01-22 18:32 UTC, olljanat commented
@sh7dm first of all. I can see that this is your first PR to Moby, so let me say welcome :+1: 

Then I can tell that CI fails to:
`
20:12:00 daemon/config/config.go:406:20: type CommonConfig is not an expression
`
so that one need to be fixed and you should also add unit test which reproduces #32530
Look: https://github.com/moby/moby/blob/master/TESTING.md#writing-tests-for-bug-fixes

2019-01-22 19:22 UTC, sh7dm commented
@olljanat how can I make a test for console warning? Help me please, I'm Go beginner. Thanks in advance

2019-01-22 19:47 UTC, olljanat commented
@sh7dm I guess that #38138 will provide some options to this.

2019-01-22 19:50 UTC, sh7dm commented
@olljanat How can I expect console warning in unit test?

2019-01-22 20:02 UTC, olljanat commented
Ahaa. It is just warning which does not change any behavior? I think that unit tests would be overkill then (I'm not maintainer so some of them will give official instruction).

How ever CI fails now to:
`
19:35:04 daemon/config/config.go:421:71:warning: unnecessary conversion (unconvert)
`
so plz fix that and also rebase these to one commit.

2019-02-01 21:15 UTC, thaJeztah requested changes
The example from https://github.com/moby/moby/issues/32530 does indeed ignore the invalid fields;

```bash
echo '{ "jjj": {}, "default-ulimit": {} }' > /etc/docker/daemon.json 
dockerd
# no error
```
Diging a bit further, this looks to be only the case if the unknown option is an empty `{}`:

This gets ignored:

```bash
echo '{"unknown-option":{} }' > /etc/docker/daemon.json 
dockerd
# no error
```

Any other value, such as `null`, `""`, `[]` all produce an error:


```bash
echo '{"unknown-option":null }' > /etc/docker/daemon.json 
dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: unknown-option

echo '{"unknown-option":"" }' > /etc/docker/daemon.json 
dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: unknown-option

echo '{"unknown-option":[] }' > /etc/docker/daemon.json 
dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: unknown-option
```

Interestingly, setting a nested value prints an error on the _nested_ value, not on the `unknown-option` field:

```bash
echo '{"unknown-option":{"nested":"option"} }' > /etc/docker/daemon.json
dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: nested
```

Even if the nested field is an empty struct `{}`;

```bash
echo '{"unknown-option":{"nested":{}}}' > /etc/docker/daemon.json
dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: nested
```


I did a bit of digging as to what may be causing this, and this looks to be an issue with the  `configValuesSet()` function.

That function "flattens" options where needed (putting nested configuration options at the top-level). However, if an option is a map, and that map is _empty_, it's ignored (not added to the `flatten` map).
This PR https://github.com/moby/moby/pull/34093 was adding warnings for _valid_ options that were set, but empty (which we decided was not desirable https://github.com/moby/moby/pull/34093#issuecomment-316698133), but it was actually dealing with the same area.


I have a fix, but it's not fully fledged-out yet (there's some weird handling of "possibly known options" that I need to look into)

2019-02-05 01:07 UTC, MHBauer commented
@sh7dm has suggestions for next steps.

2019-05-01 08:44 UTC, justrich commented
Dupe of #36911 ?

2025-07-20 16:50 UTC, closed without merging