Write stackdumps to file
moby/moby pull request #39011
Opened 2019-04-06 04:32 UTC by jhowardmsft

Signed-off-by: John Howard <jhoward@microsoft.com>

Part of a diagnostics gathering effort for when things go wrong. Already have identical PRs for the containerd shim runtime (merged already), and containerd. This completes the circle and writes the stacks to a file in temp so that it can be gathered for later analysis. 

(https://github.com/Microsoft/hcsshim/pull/554 is tracking the gathering of all these logs).

2019-04-06 10:49 UTC, thaJeztah requested changes

2019-04-06 10:49 UTC, thaJeztah commented on pkg/signal/trap.go
> +	if dir == "" {
Instead of this, couldn't we just pass a `dir` when calling this function?

2019-04-09 17:50 UTC, cpuguy83 commented
I'm not sure I understand this since we are already writing it to a file.
Additionally there is an API to fetch the stacks as well.

2019-04-11 01:28 UTC, jhowardmsft commented
Closing this. I reworked the log gatherer script to accomodate what the daemon already does. @cpuguy83  re

> Additionally there is an API to fetch the stacks as well.

There is? When did that get introduced?

2019-04-11 01:28 UTC, closed without merging

2019-04-11 01:56 UTC, cpuguy83 commented
There's always been one, but it was hidden behind the debug mode, this is now always added, probably for a few versions of Docker.