Fix DOCKER_CROSS being overwritten
moby/moby pull request #39069
Opened 2019-04-13 18:54 UTC by thaJeztah

Not exactly sure why, but this line;

   build: DOCKER_CROSS ?= false

Always overwrote `DOCKER_CROSS` when running `make cross`. Perhaps because it is set in `cross: DOCKER_CROSS := true`, and in a different scope? May also be dependent on the version of `make` in use.

2019-04-13 18:55 UTC, thaJeztah commented
ping @cpuguy83 @tianon PTAL

2019-04-14 02:16 UTC, tianon commented
Bizarre! Seems sane to me 👍

2019-04-14 09:00 UTC, thaJeztah commented
definitely bizarre; I'll try creating a minimal re producer Makefile to figure out if it's something version-specific, or perhaps I don't understand variable scope in Makefiles

2019-04-14 09:12 UTC, thaJeztah commented
was wondering if there's a Makefile linter; apparently there's one; it's even written in Go (:tada:), and inspired by a tweet from @meatballhat 🤗 https://github.com/mrtazz/checkmake

might give that a try as well

2019-04-14 19:02 UTC, thaJeztah commented
This is a minimal reproducer;

```make
cross: DOCKER_CROSS := true-cross
cross: build
        echo this is cross, and DOCKER_CROSS is $(DOCKER_CROSS)

ifdef DOCKER_CROSSPLATFORMS
build: DOCKER_CROSS := true-build
else
build: DOCKER_CROSS ?= false-build
endif

build:
        echo this is build, and DOCKER_CROSS is $(DOCKER_CROSS)
```

Running `make cross` with that produces:

```bash
make cross
echo this is build, and DOCKER_CROSS is false-build
this is build, and DOCKER_CROSS is false-build
echo this is cross, and DOCKER_CROSS is true-cross
this is cross, and DOCKER_CROSS is true-cross
```

Adding this at the top:

```
DOCKER_CROSS := false-default
```

So;

```make
DOCKER_CROSS := false-default

cross: DOCKER_CROSS := true-cross
cross: build
        echo this is cross, and DOCKER_CROSS is $(DOCKER_CROSS)

ifdef DOCKER_CROSSPLATFORMS
build: DOCKER_CROSS := true-build
else
build: DOCKER_CROSS ?= false-build
endif

build:
        echo this is build, and DOCKER_CROSS is $(DOCKER_CROSS)
```

And running again:

```bash
make cross
echo this is build, and DOCKER_CROSS is true-cross
this is build, and DOCKER_CROSS is true-cross
echo this is cross, and DOCKER_CROSS is true-cross
this is cross, and DOCKER_CROSS is true-cross
```

So, looks like variables are locally scoped, _unless_ a global variable exists. This is on macOS, so perhaps it's a different variant of make than on Linux (at least it's an ancient one)

```bash
make --version

GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

Hm.. actually looks like the same is on Linux. Using the original Makefile;

```
docker run -it --rm -v (pwd):/test -w /test debian:stretch sh -c 'apt-get update && apt-get -y install make && make cross'

...

echo this is build, and DOCKER_CROSS is false-build
this is build, and DOCKER_CROSS is false-build
echo this is cross, and DOCKER_CROSS is true-cross
this is cross, and DOCKER_CROSS is true-cross
```

2019-04-14 19:12 UTC, thaJeztah commented
LOL that linter was not super-entertaining (other than some typos);

```
checkmake Makefile
                                                                    
        RULE                   DESCRIPTION             LINE NUMBER  
                                                                    
  phonydeclared       Target "default" should be               125  
                      declared PHONY.                               
  timestampexpanded   Variable "PHONY" possibly        2            
                      contains and timestamp and                    
                      should be simply exapnded.          
```

"exapnded" 🤔 

At least it has a `pizza` target:

```
 make pizza


🍕 🍕 🍕 🍕 🍕 🍕   make.pizza 🍕 🍕 🍕 🍕 🍕 🍕 

https://twitter.com/mrb_bk/status/760636493710983168
```

2019-04-15 16:15 UTC, cpuguy83 commented
Hmmm, I know I tested both true and false cases... oh well.

2019-04-15 16:17 UTC, cpuguy83 requested changes

2019-04-15 16:17 UTC, cpuguy83 commented on Makefile
> +DOCKER_CROSS := false
```suggestion
DOCKER_CROSS ?= false
```

2019-04-15 16:37 UTC, thaJeztah commented on Makefile
> +DOCKER_CROSS := false
Ah, yes, makes sense; let me update

2019-04-15 16:38 UTC, thaJeztah commented on Makefile
> +DOCKER_CROSS := false
Updated 👍

2019-04-15 16:45 UTC, cpuguy83 approved these changes
LGTM

2019-04-15 18:14 UTC, thaJeztah commented
@tianon LGTY?

2019-04-15 22:18 UTC, tianon commented
LGTM

2019-04-15 23:01 UTC, merged