Fluentd: add fluentd-async, fluentd-request-ack, and deprecate fluentd-async-connect
moby/moby pull request #39086
Opened 2019-04-16 11:01 UTC by thaJeztah

Follow up to https://github.com/moby/moby/pull/39074

- Some minor refactoring; the driver now not only validates if options are supported, but also if their value can be parsed (producing an error earlier, instead of when instantiating a driver)
- Add `fluentd-async` option, deprecate `fluentd-async-connect`. This ia a rename of the old option. The old option remains functional, but when used will log a deprecation warning in fluentd.  If both the new, and old option is set, a "conflicting options" error is produced. This change is not versioned, and affects all API versions.
- Add `fluentd-request-ack` option. This adds a new `fluentd-request-ack` logging option for the Fluentd logging driver. If enabled, the server will respond with an acknowledgement. This option improves the reliability of the message transmission. This change is not versioned, and affects all API versions.

2019-04-16 11:06 UTC, thaJeztah commented
Ping @tagomoris @cpuguy83 PTAL

@tagomoris I noticed two more options that are in the driver, but not exposed through the docker API;

- https://github.com/fluent/fluent-logger-golang/commit/70eca0b368756d0ac825f27e3a68432dc52ef817 (https://github.com/fluent/fluent-logger-golang/pull/56); New configuration directive `MaxRetryWait`. Looking at that option, it would likely only make sense as a `daemon` option; not sure if it's worth adding though (as we already have `fluentd-retry-wait` and that option would only limit/restrict its maximum value
- https://github.com/fluent/fluent-logger-golang/pull/27 Add JSON marshaler (Add `MarshalAsJSON` option and marshal as forward protocol adopted JSON). Looks like that option was around already, but also not exposed through the Docker API; is that problem still current? (i.e., are there still cases where `msgpack` cannot be used?). If that's really addressing a corner-case, perhaps we should not add that option (but open to input).

2019-04-17 01:05 UTC, tagomoris approved these changes
Basically LGTM. I commented on a point for usability.

2019-04-17 01:05 UTC, tagomoris commented on daemon/logger/fluentd/fluentd.go
> +		return config, errors.Errorf("conflicting options: cannot specify both '%s' and '%s", asyncKey, asyncConnectKey)
This error msg doesn't show the pair of keys now conflicting (just shows values of these keys). It should show conflicting keys and these values for users.

2019-04-17 01:05 UTC, tagomoris commented on daemon/logger/fluentd/fluentd.go
> +		return config, errors.Errorf("conflicting options: cannot specify both '%s' and '%s", asyncKey, asyncConnectKey)
It's best if it can show that the one is now deprecated and the other is recommended.

2019-07-14 20:38 UTC, thaJeztah commented
ping @kolyshkin @cpuguy83 PTAL

2019-12-31 16:34 UTC, thaJeztah commented
rebased ping @kolyshkin @cpuguy83 @tiborvass PTAL

2019-12-31 17:48 UTC, cpuguy83 requested changes

2019-12-31 17:48 UTC, cpuguy83 commented on daemon/logger/fluentd/fluentd.go
>  		return nil, err
This would typically need to be an `errdefs.InvalidParameter` error, I think.

2020-01-02 11:23 UTC, thaJeztah commented
@cpuguy83 updated; PTAL

2020-01-02 18:03 UTC, cpuguy83 approved these changes
LGTM

2020-01-09 17:05 UTC, thaJeztah commented
ping @tonistiigi @AkihiroSuda @vdemeester ptal 🤗

2020-02-11 01:14 UTC, thaJeztah commented
ping @tonistiigi @AkihiroSuda @tiborvass PTAL

2020-02-11 06:16 UTC, AkihiroSuda approved these changes

2020-02-11 06:16 UTC, merged