Dockerfile.e2e: copy test sources
moby/moby pull request #39150
Opened 2019-04-27 05:36 UTC by kolyshkin

(this is a quick followup to #39116)

Package "gotest.tools/assert" uses source introspection to
print more info in case of assertion failure. When source code
is not available, it prints an error instead.

In other words, before this commit:

> --- SKIP: TestCgroupDriverSystemdMemoryLimit (0.00s)
>     cgroupdriver_systemd_test.go:32: failed to parse source file: /go/src/github.com/docker/docker/integration/system/cgroupdriver_systemd_test.go: open /go/src/github.com/docker/docker/integration/system/cgroupdriver_systemd_test.go: no such file or directory
>     cgroupdriver_systemd_test.go:32:

and after:

> --- SKIP: TestCgroupDriverSystemdMemoryLimit (0.09s)
>    cgroupdriver_systemd_test.go:32: !hasSystemd()

This increases the resulting image size by about 2 MB
on my system (from 758 to 760 MB).

2019-04-27 05:37 UTC, kolyshkin commented on Dockerfile.e2e
> +RUN mkdir -p /build/${PWD} && find integration integration-cli -name \*_test.go -exec cp --parents '{}' /build${PWD} \;
I'm using $PWD here as it points to /go/src/github.com/docker/docker and this is where binaries expect the files to be in. This is also why the last COPY statement (below) has destination as /

2019-04-27 21:12 UTC, thaJeztah requested changes
Left some comments, but otherwise looks good 🤗

2019-05-01 20:24 UTC, kolyshkin commented on Dockerfile.e2e
>  ARG DOCKER_GITCOMMIT
DONE

2019-05-01 20:25 UTC, kolyshkin commented
@seemethere PTAL (second patch)

2019-05-01 20:29 UTC, seemethere approved these changes

2019-05-01 22:05 UTC, thaJeztah commented on Dockerfile.e2e
> +ARG DOCKER_GITCOMMIT=${DOCKER_GITCOMMIT:-undefined}
This should do the job;

```suggestion
ARG DOCKER_GITCOMMIT=undefined
```

2019-05-02 21:58 UTC, kolyshkin commented on Dockerfile.e2e
> +ARG DOCKER_GITCOMMIT=${DOCKER_GITCOMMIT:-undefined}
Right; fixed

2019-05-02 22:29 UTC, thaJeztah approved these changes
LGTM, thanks!

2019-05-02 22:32 UTC, seemethere approved these changes

2019-05-03 02:07 UTC, merged