Change socket location to /run/docker.sock
moby/moby pull request #39275
Opened 2019-05-28 11:35 UTC by wiktor-k

This change resolves systemd warning:

```
/usr/lib/systemd/system/docker.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/docker.sock → /run/docker.sock; please update the unit file accordingly.
```

**- What I did**
Update the location of docker socket to use `/run` directory

**- How I did it**
By editing the file :)

**- How to verify it**
I used the changed file locally and it worked.

**- Description for the changelog**

Change location of docker socket to `/run/docker.sock`

**- A picture of a cute animal (not mandatory but encouraged)**

![cat](https://user-images.githubusercontent.com/1718963/58475107-60529300-814d-11e9-9a93-651902b1f570.jpg)

2019-05-28 11:35 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "move-var-run-to-run" git@github.com:wiktor-k/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2019-05-28 11:45 UTC, AkihiroSuda requested changes
Why not just ignore the warning?

If we want to migrate to the modern path scheme, we would need to update the daemon and the CLI as well, but it is highly likely to break compatibility.

2019-05-28 11:57 UTC, wiktor-k commented
I try not to ignore warnings as this builds "warning blindness" but I understand your reasoning. [`/run` was introduced over 8 years ago](https://lwn.net/Articles/436012/).

Do you suggest closing this PR until this is discussed further?

2019-05-28 12:12 UTC, AkihiroSuda commented
Yes,  I suggest closing PR, but maybe you can instead add a comment like this:
```
[Socket]
# If /var/run is implemented as a symlink to /run, you may specify ListenStream=/run/docker.sock instead.
ListenStream=/var/run/docker.sock
```

Note that there is no guarantee that `/var/run` is implemented as a symlink to `/run`, according to LSB 3.0:  http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html

2019-05-28 12:25 UTC, wiktor-k commented
> maybe you can instead add a comment like this:

Okay, I think this still would be useful.

> Note that there is no guarantee that /var/run is implemented as a symlink to /run

:thinking: as far as I'm reading "It is valid to implement /var/run as a symlink to /run." I think they mean that /var/run can be implemented as symlink or in any other reasonable manner (hardlink? bind-mount?) not that they would point to two different places...

But my previous change would violate other rule that's also on that page:

> Programs should not access both /var/run and /run directly, except to access /var/run/utmp.

That is accessing both /var/run and /run (as you mentioned in other places, like CLI or daemon).

Thanks for helping with this PR, I really appreciate it!

2019-05-28 12:31 UTC, AkihiroSuda commented
cc @andrewhsu @tianon

2019-05-28 14:32 UTC, tianon commented
Are there common systemd-using systems that don't have the `/var/run -> /run` symlink in practice?

2019-05-28 14:47 UTC, AkihiroSuda commented
No AFAIK

2019-05-28 20:34 UTC, wiktor-k commented
> Are there common systemd-using systems that don't have the `/var/run -> /run` symlink in practice?

That'd have to be an uncanny distro in my opinion. Systemd was released on 2010 and `/run` introduced in 2011 by the same author so I guess it's natural that the distro would follow the same path when adopting systemd.

2019-05-28 21:16 UTC, tianon commented
Yeah, makes sense (and matches what I would expect) -- IMO this should probably go the other way in that case (default to `/run`, optionally with a comment explaining how to "fix" it for non-symlinking distros).

2019-05-28 21:25 UTC, wiktor-k commented
Okay, sounds reasonable. Adjusted the socket location and reversed comment's text. See if this looks better.

2019-05-28 22:04 UTC, tianon approved these changes
:+1: :heart:

2019-05-29 02:33 UTC, AkihiroSuda approved these changes

2019-05-29 14:09 UTC, yongtang approved these changes
LGTM

2019-05-29 16:39 UTC, merged

2019-06-04 11:08 UTC, thaJeztah commented
Note that this systemd unit file is not used in the deb/rpm packages; the packages  use the unit file from https://github.com/docker/docker-ce-packaging/blob/master/systemd/docker.service

Also wondering; if we want to change the actual path; there's many locations in the codebase that look for `/var/run/docker.sock` (perhaps there's SELinux profiles that need to be updated). Note that containerd also still uses `/var/run/...`

2019-06-07 13:54 UTC, wiktor-k commented
@thaJeztah, what action would you suggest? I don't mind filing more PRs against these projects but if there is no consensus that it's a good idea then the work would be wasted...

2019-06-11 13:03 UTC, alcohol commented
Running Archlinux, and having installed `docker 1:18.09.6-1`, the `docker.sock` file is now created by the daemon in `/run` (which is not a symlink to / from `/var/run`), but the client is still trying to connect to `/var/run/docker.sock` :-(

2019-06-12 09:46 UTC, thaJeztah commented
@alcohol if that's a default setup of Archlinux, might be good to report that with the Archlinux maintainers. It will be a concern though if there's more systems in the wild that are missing the symlink.

@wiktor-k perhaps you could open an issue to track this, on which we can have a discussion on what changes would have to be made? Also thinking (e.g.) having a fallback in the Docker CLI to try both locations (first attempt `/run/docker.sock`, and fallback to `/var/run/docker.sock`). There are thousands of examples on the internet for using `/var/run/docker.sock` so we should make sure that those never break.

2019-06-12 09:53 UTC, alcohol commented
I do not think it is default. Was just my vps that was setup incorrectly. Most of my other Archlinux machines have the symlink.

2019-06-12 10:48 UTC, wiktor-k commented
> if that's a default setup of Archlinux, might be good to report that with the Archlinux maintainers. It will be a concern though if there's more systems in the wild that are missing the symlink.

Just as @alcohol says it was probably a bug on one system. I'm using Arch as well and have correct symlinks in place. (Actually the warnings I saw that pushed me to open this PR was on Arch).

> perhaps you could open an issue to track this, on which we can have a discussion on what changes would have to be made? Also thinking (e.g.) having a fallback in the Docker CLI to try both locations (first attempt /run/docker.sock, and fallback to /var/run/docker.sock). There are thousands of examples on the internet for using /var/run/docker.sock so we should make sure that those never break.

Good idea, which repo should I use? moby? or docker-ce-packaging?

2019-06-12 10:56 UTC, thaJeztah commented
> Good idea, which repo should I use? moby? or docker-ce-packaging?

This repository would be fine; I expect changes will be needed in multiple repositories though (packaging, cli, as well as in this repository to change the default paths that are used, possibly SELinux profiles that need updating)