fix: fix lack of copyUIDGID in swagger.yaml
moby/moby pull request #39279
Opened 2019-05-29 08:38 UTC by ZYecho

Signed-off-by: zhangyue <zy675793960@yeah.net>

**- What I did**
original fix at [#28923](https://github.com/moby/moby/pull/28923), but lack of bringing change to swagger.

**- How I did it**
add copyUIDGID param to swagger.yaml

**- How to verify it**
No need
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2019-05-29 12:35 UTC, olljanat commented
@ZYecho CI build fails to
```
11:50:25 api/swagger.yaml
11:50:25   [2m623   error    syntax error: expected <block end>, but found '<block mapping start>'
```
because that yaml is not valid.

Also use your real name on sign off message.

2019-05-30 01:20 UTC, ZYecho commented
> @ZYecho CI build fails to
> 
> ```
> 11:50:25 api/swagger.yaml
> 11:50:25   �[2m623   error    syntax error: expected <block end>, but found '<block mapping start>'
> ```
> 
> because that yaml is not valid.
> 
> Also use your real name on sign off message.

done.

2019-05-30 08:45 UTC, olljanat commented
Derek add label: rebuild/windowsRS1

2019-06-04 11:11 UTC, thaJeztah commented
Could you also add a note to the API history file? I see the original PR was merged for Docker 17.06, so the change should be included under the API v1.30 changes; https://github.com/moby/moby/blob/master/docs/api/version-history.md#v130-api-changes

2019-06-04 11:16 UTC, thaJeztah requested changes

2019-06-04 11:16 UTC, thaJeztah commented on api/swagger.yaml
> +          description: "If “1”, “true”, or “True” then it will copy UID/GID maps to the dest file"
I see this is documented like this on other places as well, but perhaps we should just document `1` and `true`. 

Strictly speaking, any non-empty value should work; https://github.com/moby/moby/blob/4f0d95fa6ee7f865597c03b9e63702cdcb0f7067/api/server/httputils/form.go#L9-L13

But I don't think we should officially support all of that (so officially support just `1` and `true`)

2019-06-05 01:58 UTC, ZYecho commented
@thaJeztah PTAL

2019-06-05 11:12 UTC, thaJeztah approved these changes
LGTM, thanks!

2019-06-05 11:13 UTC, merged