Handle blocked I/O of exec'd processes
moby/moby pull request #39383
Opened 2019-06-20 20:24 UTC by crosbymichael

This is the second part to
https://github.com/containerd/containerd/pull/3361 and will help process
delete not block forever when the process exists but the I/O was
inherited by a subprocess that lives on.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

2019-06-21 09:49 UTC, thaJeztah commented
addresses https://github.com/containerd/containerd/issues/3286 docker exec hang if earlier docker exec left a zombie process


@crosbymichael does this also relate to;

- https://github.com/moby/moby/issues/38978 Zombie reaping not occurring as expected
- https://github.com/moby/moby/issues/38978 docker cannot terminate a container when processes linger after TERM


Should we have a test-case for this? (not sure if it's easy to test)

2019-06-21 09:52 UTC, thaJeztah requested changes

2019-06-21 09:52 UTC, thaJeztah commented on container/stream/streams.go
> +func (c *Config) Wait(ctx context.Context) {
Oh; linting failure;

```
20:37:38 container/stream/streams.go:151:1:warning: exported method Config.Wait should have comment or be unexported (golint)
20:37:41 Build step 'Execute shell' marked build as failure
```

2019-06-21 09:53 UTC, thaJeztah commented
Haven't seen this one before; https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25656/console

```
21:06:29 FAIL: docker_cli_exec_test.go:538: DockerSuite.TestExecWindowsOpenHandles
21:06:29
21:06:29 assertion failed: 2 (int) != 1 (int)
```


I'll kick CI for RS1 to see if it was just flaky

2019-06-21 16:01 UTC, crosbymichael commented
I read through that test and its depending on the "bad" functionality, forking off the sleeps into the background and the actually cmd.exe is exiting. I think it's safe for this test to be removed with this change as well as the test is horribly racy and depending on how many seconds the sleeps wait until they exit, its bad!

2019-07-03 13:17 UTC, thaJeztah approved these changes
SGTM

@kolyshkin @dmcgowan PTAL

2019-07-05 17:49 UTC, cpuguy83 approved these changes
LGTM

2019-07-05 17:51 UTC, cpuguy83 commented
I/O waiters seems like a good candidate for metrics as well.

2019-07-05 17:51 UTC, merged