Add (hidden) flags to set containerd namespaces
moby/moby pull request #39500
Opened 2019-07-11 23:52 UTC by cpuguy83

This allows our tests, which all share a containerd instance, to be a
bit more isolated by setting the containerd namespaces to the generated
daemon ID's rather than the default namespaces.

This came about because I found in some cases we had test daemons
failing to start (really very slow to start) because it was (seemingly)
processing events from other tests.

2019-07-12 00:02 UTC, thaJeztah commented
related previous PR (which did this through the API) https://github.com/moby/moby/pull/36914

Is the namespace length still a concern? Or don't we reach the maximum length here? https://github.com/moby/moby/pull/36914#issuecomment-383067597

2019-07-12 00:02 UTC, cpuguy83 commented
Length can still be problematic if you make too long of a name. I ran these locally and it was fine at least.

2019-07-12 00:05 UTC, thaJeztah requested changes
found a typo, but SGTM

2019-07-12 00:05 UTC, thaJeztah commented on cmd/dockerd/config_unix.go
> +	flags.StringVar(&conf.ContainerdPluginNamespace, "containerd-plugins-namespace", containerd.PluginNamespace, "Containerd namespce to use for plugins")
typo: `namespce`

2019-07-12 00:09 UTC, cpuguy83 commented
Ah I need to deal with Windows issues (validation check doesn't make sense on Windows which doesn't use containerd right now).

But going to let linux tests run through first.

2019-07-12 00:12 UTC, thaJeztah commented
yes, let's see if it all works 🤞

2019-07-12 00:14 UTC, thaJeztah commented
this looks weird (converting it to a http url?)

```
02:11:22     daemon.go:336: [d4259ba841705] error pinging daemon on start: Get http://%2Ftmp%2Fdocker-integration%2Fd4259ba841705.sock/_ping: dial unix /tmp/docker-integration/d4259ba841705.sock: connect: no such file or directory

2019-07-12 00:30 UTC, cpuguy83 commented
Failure was because the plugin client was talking to the wrong namespace, fixed.

2019-07-12 04:59 UTC, cpuguy83 commented
Clean run on the first shot...

2019-07-12 05:18 UTC, cpuguy83 commented
Apparently I can't make gordon rebuild successful tests anymore.

2019-07-12 13:11 UTC, thaJeztah approved these changes
LGTM

Two questions;

- do we want to make this visible at some point?
- do we need separate configuration for plugins and containers, or could plugins take the same ns plus a suffix (e.g. `<containerd-namespace> + "p"`)?

2019-07-12 15:25 UTC, thaJeztah commented
all green now

2019-07-12 16:19 UTC, cpuguy83 commented
> do we want to make this visible at some point?

🤷‍♂ 
Seems footgun-ish right now, particularly before containerd is fully integrated.

> do we need separate configuration for plugins and containers, or could plugins take the same ns plus a suffix (e.g. <containerd-namespace> + "p")?

I don't see why not, actually makes it a bit simpler to implement I think.
I originally implemented this as a prefix which gets pre-pended to the hardcoded namespaces and then used the test daemon's ID as the prefix... this led to path length issues so I changed to have the prefix just be an auto-incremented counter, but namespaces have validation that prevent an integer from being the first character.
Ultimately is kinda nice to have full control rather than a prefix for suffix.

2019-07-12 17:24 UTC, thaJeztah commented
> Ultimately is kinda nice to have full control rather than a prefix for suffix.

Ok, that's fair; I was thinking if it was too much bells and whistles, but given that it's not a "public" UX yet, we can still change if we change our minds.

2019-07-12 17:33 UTC, tiborvass approved these changes
Fine for me

2019-07-12 17:35 UTC, crosbymichael commented
LGTM

2019-07-12 17:35 UTC, merged

2019-07-24 12:45 UTC, Rid commented
Is there any way to set this flag as a user? Even if it's not in the public UX?

2019-07-24 18:27 UTC, thaJeztah commented
@Rid Yes, this PR adds the `--containerd-namespace` and `--containerd-plugins-namespace` flags on `docker`. Is there a specific use-case you have in mind to change the namespace? It's added here for a very specific use-case (CI is running multiple instances of dockerd on the same machine to test specific situations)

2019-07-25 08:14 UTC, Rid commented
@thaJeztah we're running a public docker cloud, where each user is assigned a docker daemon and we'd like as much separation between users as possible for security reasons.

2019-07-26 21:16 UTC, cpuguy83 commented
@Rid It's not really the intention to provide secure isolation with this. We just needed a mechanism to do this for tests and these flags are not guaranteed to be supported going forward.

2019-07-31 08:53 UTC, Rid commented
@cpuguy83 is it something that you'd consider supporting, given that it's useful in the use case where you're running multiple daemons per machine?

2019-07-31 17:36 UTC, cpuguy83 commented
@Rid It's definitely something I'd like to do, but I'm not sure these flags are the right place for that, and definitely not until after we have moved to totally using containerd.