Fix TestSwarmClusterRotateUnlockKey
moby/moby pull request #39616
Opened 2019-07-26 18:08 UTC by dperny

TestSwarmClusterRotateUnlockKey had been identified as a flaky test. It turns out that the test code was wrong: where we should have been checking the string output of a command, we were instead checking the value of the error. This means that the error case we were expecting was not being matched, and the test was failing when it should have just retried.

2019-07-26 18:11 UTC, thaJeztah approved these changes
heh 😂 that was the issue all this time? LGTM

2019-07-26 18:19 UTC, tiborvass approved these changes

2019-07-26 18:56 UTC, tonistiigi commented
>  that was the issue all this time

@thaJeztah No, this retry for allowing this error (that shouldn't really be allowed to happen) was added last week

@dperny There's an identical check in TestSwarmRotateUnlockKey

2019-07-26 19:13 UTC, thaJeztah commented
Ah, I see; added in https://github.com/moby/moby/commit/52e0dfef9090fa3c6003115a2c82238b189ebe42 https://github.com/moby/moby/pull/39531

2019-07-26 20:30 UTC, andrewhsu approved these changes
LGTM

2019-07-26 20:33 UTC, andrewhsu commented
@dperny this PR looks good to go, but could you also check the other retry logic added in #39531. 

Also, could we log the retry attempts in the test? If we're expecting retry to be a thing that a user would expect to experience, would be good to see if retry was tried.

2019-07-26 20:36 UTC, thaJeztah commented
Is it worth logging the first 5 attempts if we know converging takes some time? (it already logs a failure if 5 attempts failed)

2019-07-26 20:44 UTC, tonistiigi requested changes
https://github.com/moby/moby/pull/39616#issuecomment-515563370

2019-07-26 20:52 UTC, dperny commented
Fixed the other test in the same way.

2019-07-26 20:56 UTC, tonistiigi approved these changes

2019-07-26 23:09 UTC, merged

2019-09-09 20:19 UTC, thaJeztah commented
Looks like this test is still flaky https://github.com/moby/moby/pull/39883#issuecomment-529648586