Fix regression in handling of NotFound err during startup
moby/moby pull request #39703
Opened 2019-08-08 23:54 UTC by ddebroy

**- What I did**
Address a regression during daemon startup introduced in https://github.com/moby/moby/pull/38931.

**- How I did it**
Added (back) proper handling of NotFound err

**- How to verify it**
Start a container in Windows like: 
```
docker run -d --restart always --name testcontainer --network nat -p 8080:80 mcr.microsoft.com/windows/servercore:ltsc2019 ping -t 127.0.0.1
```
and Restart-Computer.
After reboot, make sure container comes back up properly and is not a zombie.

**- Description for the changelog**
Fix regression in reboot of Windows daemon

**- A picture of a cute animal (not mandatory but encouraged)**

2019-08-08 23:59 UTC, thaJeztah requested changes
change looks good but linting is failing;

```
23:55:13 Congratulations!  All commits are properly signed with the DCO!
23:56:27 daemon/daemon.go:1::warning: file is not gofmted with -s (gofmt)
23:56:27 daemon/daemon.go:1::warning: file is not goimported (goimports)
```

2019-08-08 23:59 UTC, thaJeztah commented on daemon/daemon.go
> +				if err != nil  && !errdefs.IsNotFound(err) {
```suggestion
				if err != nil && !errdefs.IsNotFound(err) {
```

2019-08-09 00:00 UTC, thaJeztah approved these changes
LGTM

2019-08-09 00:10 UTC, thaJeztah commented
backport: https://github.com/docker/engine/pull/317

2019-08-09 00:30 UTC, kolyshkin approved these changes
LGTM

2019-08-09 07:54 UTC, StefanScherer approved these changes
LGTM
retested with the NAV container example on Windows 10 with Docker Desktop.

2019-08-09 12:42 UTC, thaJeztah commented
all green 💚 - merging

2019-08-09 12:42 UTC, merged