fix docker rmi stucking
moby/moby pull request #39749
Opened 2019-08-15 02:35 UTC by yanghaichao12

- What I did
  figure out https://github.com/moby/moby/issues/39739
- How I did it
 swapping code https://github.com/moby/moby/blob/fade624f1696a46071b812606f4ddb0c6d2e4d16/daemon/images/image_delete.go#L372

- How to verify it

- Description for the changelog

- A picture of a cute animal (not mandatory but encouraged)

2019-08-15 02:35 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "dev190815" git@github.com:yanghaichao12/moby.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2019-08-15 02:41 UTC, yanghaichao12 commented
/area images

2019-08-15 02:43 UTC, yanghaichao12 commented
/area images

2019-08-15 02:45 UTC, yanghaichao12 commented
Derek add label: area/images

2019-08-15 09:47 UTC, yanghaichao12 commented
/retest

2019-08-15 09:58 UTC, yanghaichao12 commented
retest

2019-08-15 10:00 UTC, yanghaichao12 commented
retest

2019-08-15 10:02 UTC, yanghaichao12 commented
retest this please

2019-08-16 03:21 UTC, yanghaichao12 commented
retest this please

2019-08-17 01:25 UTC, yanghaichao12 commented
/retest

2019-08-17 16:23 UTC, thaJeztah requested changes
Thank you; I left a comment below.

Could you also change your DCO sign-off to [use your real name](https://github.com/moby/moby/blob/0aa167d0dfd2bc1296cd3e8bfde7765f795bd561/CONTRIBUTING.md#sign-your-work), not your GitHub handle (`yanghaichao12`)? 


```
Signed-off-by: yanghaichao12 ....
```

2019-08-17 16:23 UTC, thaJeztah commented on .gitignore
> +.idea/
Can you remove this change? It is not related to the fix, and we don't add editor-specific ignores here (see https://github.com/moby/moby/blob/d4306e4b331b49f086b9bec22421879c3e58072d/.gitignore#L1-L3)

2019-08-19 01:45 UTC, yanghaichao12 commented
@thaJeztah hi, i have change DCO and remove the content in .gitignore added by me

2019-08-19 08:56 UTC, thaJeztah commented
Hm; perhaps something went wrong with the DCO sign-off; I still see this in the commit message 😅 ;

```
Signed-off-by: yanghaichao12 <yang.haichao@zte.com.cn>
```

2019-08-19 09:31 UTC, yanghaichao12 commented
@thaJeztah hi， how about for now？
```shell
Signed-off-by: yanghaichao <yang.haichao@zte.com.cn>
```

2019-08-19 09:58 UTC, thaJeztah commented
It's one word, or `Yang Haichao`  ?

Oh! 🙈 Looks like your local copy was out of date, and you pulled in an extra commit in the rebase. Can you rebase once more? (make sure your fork is up-to-date, and the extra commit should disappear)

2019-08-19 10:26 UTC, yanghaichao12 commented
in fact, Yang is my last name.....,  i have modified  it

2019-08-19 10:39 UTC, thaJeztah approved these changes
LGTM

Thank you! sorry for all the hassle with the sign-off 🤗

2019-08-19 11:26 UTC, yanghaichao12 commented
thank you too :-)

2019-08-20 00:52 UTC, yanghaichao12 commented
retest this please

2019-08-20 06:37 UTC, yanghaichao12 commented
/retest

2019-08-20 17:01 UTC, thaJeztah commented
Windows RS1 failure is unrelated

@yongtang ptal 🤗

2019-08-20 17:08 UTC, yongtang approved these changes
LGTM, Thanks for the fix!

2019-08-20 17:09 UTC, merged

2019-08-21 00:03 UTC, yanghaichao12 commented
@thaJeztah @yongtang   Thank you！