daemon: Use short libnetwork ID in exec-root
moby/moby pull request #39822
Opened 2019-08-29 08:28 UTC by Rid

Signed-off-by: Grant Millar <rid@cylo.io>

**- What I did**
Use short controller ID in libnetwork-setkey in order to avoid https://github.com/moby/moby/issues/39608 where using a custom exec-root which contains > 27 chars before the controller ID causes the daemon to fail starting with:

```
failed to start daemon: Error initializing network controller: error obtaining controller instance: listen unix /cylostore/sdj/9598/var/run/docker/libnetwork/b2757cb82eadaaea94aab22529663e38c3bf799369f5b578fe8a5bb4bcefe0f0.sock: bind: invalid argument
```

This happens due to hitting the UNIX_PATH_MAX limit (which is 108, ours is 115 in the example above). The patch gives us 79 chars to play with vs 27.

**- How I did it**
Truncate the libnetwork controller ID, and submitted patches on libnetwork to accept the new format in https://github.com/docker/libnetwork/pull/2443

**- How to verify it**
```
root@58a4fa1735b4:/go/src/github.com/docker/docker# ls -la /var/run/docker/libnetwork/
total 8
drw------- 2 root root 4096 Aug 29 08:19 .
drwx------ 6 root root 4096 Aug 29 08:19 ..
srw------- 1 root root    0 Aug 29 08:19 ce6597205a18.sock
```

**- Description for the changelog**

Use short libnetwork ID in exec-root

**- A picture of a cute animal (not mandatory but encouraged)**
![Funny-Unusual-Weird-Animal-Pictures-1](https://user-images.githubusercontent.com/3407496/63923748-fe047980-ca3e-11e9-92c1-4680cf9f9169.jpg)

2019-09-30 14:02 UTC, Rid commented
@AkihiroSuda the libnetwork part was merged, is there anything else which needs to be done here?

2019-09-30 14:21 UTC, AkihiroSuda commented
Please update vendor.conf and run vndr

2019-09-30 15:48 UTC, Rid commented
@AkihiroSuda done PTAL 👍

2019-09-30 15:59 UTC, AkihiroSuda commented
needs rebase

2019-09-30 16:34 UTC, Rid commented
@AkihiroSuda rebased

2019-10-14 08:25 UTC, Rid commented
@AkihiroSuda sorry was on vacation, I've now rebased and squashed commits.

2019-10-14 08:40 UTC, AkihiroSuda requested changes

2019-10-14 08:40 UTC, AkihiroSuda commented on hack/dockerfile/install/proxy.installer
> +LIBNETWORK_COMMIT=0025177e3dabbe0de151be0957dcaff149d43536
Please preserve the original format

2019-10-14 08:53 UTC, Rid commented on hack/dockerfile/install/proxy.installer
> +LIBNETWORK_COMMIT=0025177e3dabbe0de151be0957dcaff149d43536
@AkihiroSuda fixed.

2019-10-14 11:18 UTC, AkihiroSuda approved these changes

2019-10-14 23:17 UTC, tonistiigi approved these changes
cc @arkodg

2019-10-14 23:47 UTC, arkodg approved these changes

2019-10-15 16:54 UTC, merged