integration-cli: Fix `SA1019: httputil.ClientConn is deprecated`
moby/moby pull request #40074
Opened 2019-10-11 12:23 UTC by yedamao

Rewrite sockRequestHijack to requestHijack which use writable Response.Body
```
// As of Go 1.12, the Body will also implement io.Writer
// on a successful "101 Switching Protocols" response,
// as used by WebSockets and HTTP/2's "h2c" mode.
Body io.ReadCloser
```

TestPostContainersAttach and TestExecResizeImmediatelyAfterExecStart
replace all sockRequestHijack to requestHijack.

Signed-off-by: HuanHuan Ye <logindaveye@gmail.com>

fixes #39927

**- What I did**
Fix `SA1019: httputil.ClientConn is deprecated`

**- How I did it**
Rewrite sockRequestHijack to requestHijack which use writable Response.Body
https://github.com/golang/go/issues/28030#issuecomment-427223449

**- How to verify it**
Maybe in CI golangci-lint

**- Description for the changelog**

integration-cli: Fix `SA1019: httputil.ClientConn is deprecated`

**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://user-images.githubusercontent.com/8220938/66651119-d3742600-ec64-11e9-9e20-92327809da59.png)

2019-10-14 01:14 UTC, thaJeztah commented
Thanks! Looks like CI is failing on a linting issue;

```
integration-cli/docker_api_attach_test.go:301:2: unreachable: unreachable code (govet)
	return
	^
```

2019-10-14 07:58 UTC, yedamao commented
@thaJeztah  PTAL. Thanks.

2019-10-17 18:41 UTC, andrewhsu commented
@yedamao needs a rebase to address conflicts

2019-10-18 05:25 UTC, yedamao commented
@andrewhsu thanks.  rebased and fixed tconflicts

2019-10-18 18:27 UTC, cpuguy83 requested changes

2019-10-19 03:46 UTC, yedamao commented on integration-cli/docker_api_attach_test.go
> +	if os.Getenv("DOCKER_TLS_VERIFY") != "" {
This come from testutil/request pkg newRequest method, I want to reuse it here later.
https://github.com/moby/moby/blob/a8b04b17fd37ed797e34bea6534d307929c6337b/testutil/request/request.go#L113-L137

The old code use ```httputil.ClientConn``` as client to do request, request not need set ```req.URL.Scheme``` and ```req.URL.Host```, but ```http.Client``` need request to set them.

2019-10-22 02:58 UTC, yedamao commented on integration-cli/docker_api_attach_test.go
> +	if os.Getenv("DOCKER_TLS_VERIFY") != "" {
remove certs testing.

2019-10-22 02:59 UTC, yedamao commented
@cpuguy83 PTAL

2019-11-05 19:40 UTC, cpuguy83 approved these changes
LGTM

2019-12-18 18:30 UTC, AkihiroSuda approved these changes

2019-12-18 18:30 UTC, merged