Bump hcsshim to 6c7177eae8be632af2e15e44b62d69ab18389ddb
moby/moby pull request #40128
Opened 2019-10-24 03:03 UTC by vikramhh

Among other things, this is required to pull in
https://github.com/microsoft/hcsshim/pull/718 which should
take care of multiple issues reported to us.

Signed-off-by: Vikram bir Singh <vikrambir.singh@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2019-10-24 07:32 UTC, thaJeztah commented
```

vendor/github.com/Microsoft/hcsshim/internal/schema2/properties.go:13:2: cannot find package "github.com/containerd/cgroups/stats/v1" in any of:
 	/go/src/github.com/docker/docker/vendor/github.com/containerd/cgroups/stats/v1 (vendor tree)
 	/usr/local/go/src/github.com/containerd/cgroups/stats/v1 (from $GOROOT)
 	/go/src/github.com/containerd/cgroups/stats/v1 (from $GOPATH)

```


Looks like this needs a more recent version of the containerd/cgroups package to get https://github.com/containerd/cgroups/blob/master/stats/v1/, which was added in https://github.com/containerd/cgroups/pull/100

2019-10-24 07:48 UTC, thaJeztah commented
To other reviewers: please consider merging https://github.com/moby/moby/pull/39100 first; I've been rebasing that one for over 6 months now

2019-10-29 20:17 UTC, vikramhh commented
@thaJeztah @tiborvass - https://github.com/moby/moby/pull/40128 is in now. How can I trigger all checks to run on this change so that we could see if there are any build breaks? I recall @andrewhsu telling me that I need a member of maintainers group to do that.

2019-10-30 10:11 UTC, thaJeztah commented
@vikramhh strange; CI should trigger as usual, because you didn't make changes to the Jenkinsfile. Could you try a rebase/force push to see if Jenkins starts?

Note that our current CI doesn't run tests with Hyper-V isolation, but I have a "WIP" test branch that adds Windows 1903 and hyper-v isolation to Jenkins; https://github.com/moby/moby/pull/39846

I'll rebase that PR on top of this one to see if we can confirm the issue is resolved

2019-10-30 10:33 UTC, thaJeztah commented
oh; your branch has a merge-conflict; you need to rebase and re-run `vndr github.com/Microsoft/hcsshim`

2019-10-30 10:50 UTC, thaJeztah commented
@vikramhh I did a quick rebase and re-vendor

2019-10-30 11:55 UTC, thaJeztah commented
oh, I need to fix-up vendoring;

```
[2019-10-30T11:18:11.665Z]  D vendor/github.com/containerd/cgroups/stats/v1/doc.go
[2019-10-30T11:18:11.665Z]  D vendor/github.com/containerd/cgroups/stats/v1/metrics.pb.go
[2019-10-30T11:18:11.665Z]  D vendor/github.com/containerd/cgroups/stats/v1/metrics.proto
```

2019-10-30 12:15 UTC, thaJeztah commented
opened https://github.com/moby/moby/pull/40154 to update containerd/cgroups, and based this on top of that one

2019-10-31 00:18 UTC, thaJeztah commented
Seeing a lot of these failures on both RS1 and RS5;

```

[2019-10-30T14:22:37.513Z]     --- FAIL: TestDockerSuite/TestEventsContainerEventsAttrSort (3.17s)
[2019-10-30T14:22:37.513Z]         cli.go:29: assertion failed: 
[2019-10-30T14:22:37.513Z]             Command:  d:\CI\PR-39846\32\binary\docker.exe run --rm --name container-events-test busybox true
[2019-10-30T14:22:37.513Z]             ExitCode: 125
[2019-10-30T14:22:37.513Z]             Error:    exit status 125
[2019-10-30T14:22:37.513Z]             Stdout:   
[2019-10-30T14:22:37.513Z]             Stderr:   d:\CI\PR-39846\32\binary\docker.exe: Error response from daemon: process 1176 in container 01ef1c1ff2fddc4f76fdeb147bf724ce80a00bf46f90b4e3edf51531cf818426 encountered an error during hcsshim::Process::StdioLegacy: failure in a Windows system call: Element not found. (0x490).
[2019-10-30T14:22:37.513Z]             
[2019-10-30T14:22:37.513Z]             
[2019-10-30T14:22:37.513Z]             Failures:
[2019-10-30T14:22:37.513Z]             ExitCode was 125 expected 0
[2019-10-30T14:22:37.513Z]             Expected no error

```


```

[2019-10-30T13:57:29.000Z]     --- FAIL: TestDockerSuite/TestRunWorkingDirectory (4.12s)
[2019-10-30T13:57:29.000Z]         cli.go:29: assertion failed: 
[2019-10-30T13:57:29.000Z]             Command:  d:\CI\PR-40128\11\binary\docker.exe run --workdir C:/Windows busybox pwd
[2019-10-30T13:57:29.000Z]             ExitCode: 125
[2019-10-30T13:57:29.000Z]             Error:    exit status 125
[2019-10-30T13:57:29.000Z]             Stdout:   
[2019-10-30T13:57:29.000Z]             Stderr:   d:\CI\PR-40128\11\binary\docker.exe: Error response from daemon: process 4760 in container 0860bbbb4a73487c39416f46ecd6600b62e88d6627d89dd0fa6f19f1b0c261bb encountered an error during hcsshim::Process::StdioLegacy: failure in a Windows system call: Element not found. (0x490).
[2019-10-30T13:57:29.000Z]             
[2019-10-30T13:57:29.000Z]             
[2019-10-30T13:57:29.000Z]             Failures:
[2019-10-30T13:57:29.000Z]             ExitCode was 125 expected 0
[2019-10-30T13:57:29.000Z]             Expected no error
```

2019-10-31 00:56 UTC, vikramhh commented
0x490 is ERROR_NOT_FOUND [https://golang.org/pkg/syscall/?GOOS=windows] - this is very likely coming from `makeOpenFiles` in `internal/hcs/utils.go`

@kevpar - could you please take a look.

2019-10-31 01:20 UTC, thaJeztah commented
> 0x490 is ERROR_NOT_FOUND [https://golang.org/pkg/syscall/?GOOS=windows] - this is very likely coming from makeOpenFiles in internal/hcs/utils.go

Ok, so https://github.com/moby/moby/blob/1bd184a4c291e4f60629e2cc279216f8f40495f3/integration-cli/docker_cli_run_test.go#L137-L157 starts a container with `--workdir=C:\Windows`. On Linux, specifying a non-existing directory as `workdir`, will create the working directory if it's not there. So it _could_ be that something in the code is first trying to change to the directory, and then falling back to creating? 

(I assume `C:\Windows` is in the image, but adding just in case)

2019-11-08 02:02 UTC, ebalders commented
Any ETA on when this will be merged in?

2019-11-08 05:47 UTC, thaJeztah commented
@ebalders there's a regression in this hcsshim version, which is currently blocking this from being merged

2019-11-08 22:00 UTC, kevpar commented
I am taking a look at this.

2019-11-08 23:17 UTC, kevpar commented
@thaJeztah I'm not familiar with the moby Jenkins CI. Is there a command I can run to repro the CI tests locally?

2019-11-08 23:58 UTC, thaJeztah commented
@kevpar there probably is; you should be able to take the environment variables and commands that are in the Jenkinsfile (but admittedly, I'm not on Windows, and have never tried to do so.

Be aware that on Windows, the tests cannot run docker-in-docker, so may modify things on the host, so might be good to run them in a test-machine https://github.com/moby/moby/blob/master/Jenkinsfile#L949-L1006

@vikramhh may be able to help more with that

2019-11-09 00:00 UTC, thaJeztah commented
@kevpar are you on the community Slack (or on our internal Slack?) if not; perhaps you could inform if you could be added there; we do have a shared channel with Microsoft, which is sometimes handy for quick discussions

2019-11-10 14:31 UTC, vikramhh commented
@kevpar - I tried to get a local repro but quickly ran into another issue, also in hcsshim. You may want to take a look at that first. With a docker daemon that has these hcsshim changes, I find the following:


C:\gopath\src\github.com\docker\docker>`docker run --rm mcr.microsoft.com/windows/servercore:ltsc2019 true`
`docker: Error response from daemon: container 8cc37c049d7328d9fff3433632b6c86dc495bfb4d60856e59e90d227c451f26a encountered an error during hcsshim::System::CreateProcessNoStdio: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"true","WorkingDirectory":"C:\\","CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.`

Here is the output from docker daemon when run with the --debug flag:

`C:\gopath\bin\temp>dockerd.exe --debug
time="2019-11-10T14:26:36.709443200Z" level=info msg="Starting up"
time="2019-11-10T14:26:36.763447000Z" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"
time="2019-11-10T14:26:36.769450800Z" level=debug msg="Stackdump - waiting signal at Global\\stackdump-3152"
time="2019-11-10T14:26:36.769450800Z" level=info msg="Windows default isolation mode: process"
time="2019-11-10T14:26:36.770449000Z" level=debug msg="Using default logging driver json-file"
time="2019-11-10T14:26:36.770449000Z" level=debug msg="[graphdriver] trying provided driver: windowsfilter"
time="2019-11-10T14:26:36.770449000Z" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\windowsfilter"
time="2019-11-10T14:26:36.771445100Z" level=debug msg="Initialized graph driver windowsfilter"
time="2019-11-10T14:26:36.772446500Z" level=debug msg="Ignoring invalid digest sha256:0cb0663b573dc14c66c6b47467c561505d071367af6679f7d9f227fdf49d3296-f60566d6410fd8f33c0c2eba255f3b617a41313b717b8a952e3283d78471825e-removing"
time="2019-11-10T14:26:36.772446500Z" level=debug msg="Ignoring invalid digest sha256:0ef10fc62e511966e788c54679fd02b678111498d4ba6636c36fe22a26945c17-d79f3123c512dd497633cc535e23e348578667a2a89f2c93ee42a40751881bcf-removing"
time="2019-11-10T14:26:36.772446500Z" level=debug msg="Ignoring invalid digest sha256:1466f4ec2fa7179a675f5a2825120b84205a9ed9d4c42c4423968af446984f68-66249a70b7386d5f49bf89a60e3c6ce638cb4c64baf8026c4dcff814aff467e6-removing"
time="2019-11-10T14:26:36.773426800Z" level=debug msg="Ignoring invalid digest sha256:1b7551572c0ea8c98ce839d0b86abccc042557424d60b8f15e0e0df3220c66e7-83022ab77b3f29e5f7972246928c19cc2dc1b4bd32b60348a5a0bb8cdadd22f6-removing"
time="2019-11-10T14:26:36.773426800Z" level=debug msg="Ignoring invalid digest sha256:1ef81f9116b15701fea5e9b3015bd6faf2d2df1603b2e0f32663c951eb955e1e-cfe8a5f0d7d35bf6989d73edcc97fb11567a08224d8c3402f6f036a75ed9865d-removing"
time="2019-11-10T14:26:36.773426800Z" level=debug msg="Ignoring invalid digest sha256:20084a9e7acab64346da00da0818fea913d41dad33d5ab92ef277e3d0e5538b3-c99a2a86de0c37cecc5bec8ad95011701c001c3cc337ea5366bdc44d07323205-removing"
time="2019-11-10T14:26:36.773426800Z" level=debug msg="Ignoring invalid digest sha256:3028621079f8d318ca75325393150abb71e99cda6ec445b95698e5d266df79e7-f26a09b9679213138561f13ac314de7124d96827104886f68b1582fed00871d0-removing"
time="2019-11-10T14:26:36.773426800Z" level=debug msg="Ignoring invalid digest sha256:36ab587e4c9d5b92c8198a6d07d00a811e20f4b0601cd9f67e34e9e2316d1e94-a65d7cdc2e8c3f9881aafc1a947c46b709d3ad83108e27ea961413b063f5034d-removing"
time="2019-11-10T14:26:36.774446500Z" level=debug msg="Ignoring invalid digest sha256:385936468bb70caab17147fc7449c69fa580614d8016a6f48682bb272115987e-e5a5cdc560f7cda5743798c8f84539575d28bcc4eeb00c176375e2afe9870275-removing"
time="2019-11-10T14:26:36.774446500Z" level=debug msg="Ignoring invalid digest sha256:4ea904bbc0396d31e8fbf4fa2ce901a7fbc71567abff568e0153137cf2261f0a-8866bec9c70e892b5cfda518fdded0eb6fee4a16366df2fdbd5cdf0bc9dbfe66-removing"
time="2019-11-10T14:26:36.774446500Z" level=debug msg="Ignoring invalid digest sha256:4eba9880006fa41db021b2a1f16d3011c20382f77ac9e5ffd0fff5c78bdfad31-34cf421f842ddef128debdcb982a0f0af731065c73dde4c85bac25dcbef62dfa-removing"
time="2019-11-10T14:26:36.775438600Z" level=debug msg="Ignoring invalid digest sha256:51d8067a414204b03088d19f5b4f976623cea23fb5af9d3aba67d443a99d85e4-e1548021bd70941094614da3031756cbe602451328ff7f94e60581c3d2219bce-removing"
time="2019-11-10T14:26:36.775438600Z" level=debug msg="Ignoring invalid digest sha256:6f18435cf9dd3a896912fbaae501bb1d151e5c868d749ad4b132c11a02ef7bff-5f3e7de0c64619854d3e3c1b576dda42a5052c97ed62497c5998775aef43702a-removing"
time="2019-11-10T14:26:36.776412300Z" level=debug msg="Ignoring invalid digest sha256:77b6e71e4e50eaf1507de2054e9af5f63a73ee26b387be026ef8f5b199ef9a14-ffe56fad1011e2525979101e9cfe2badde6818bab2ef3ed519d6373088b8a11e-removing"
time="2019-11-10T14:26:36.776412300Z" level=debug msg="Ignoring invalid digest sha256:7975d87f65d733194993b8dbc57fec7138642074d2fef30946abaebc8359591b-ced3043d2bcd65cdb48aa0521731b11a249baddd106d6e09d18072fa795cfa9b-removing"
time="2019-11-10T14:26:36.776412300Z" level=debug msg="Ignoring invalid digest sha256:7e40b62e0f6d8d7d59ecf994e071f3198c7b06f1f8f9f76a6917d71f6f889bb2-c141ca36240e335af35250a807e37796d1b2f762ea9eef14990855a068f1a162-removing"
time="2019-11-10T14:26:36.777449200Z" level=debug msg="Ignoring invalid digest sha256:8451f5327c9dc993d37563a26a0ff3136ab6e221ff52b67573f221d1adfcd679-440dd214ed0f2d2cd823fa7348729c8af334b95b87dd6983d3706d8ca0911912-removing"
time="2019-11-10T14:26:36.777449200Z" level=debug msg="Ignoring invalid digest sha256:87d27531abafaf75e5c94e318af68044eb1f04210e336cded44b55129db678f5-a32c3642cac8c1bb5f558992f57db2853bf0f4a7e138e9cf17548a8e63966209-removing"
time="2019-11-10T14:26:36.778448600Z" level=debug msg="Ignoring invalid digest sha256:8cb4ac14ccdc0c431e8f982b863e98a691bd725265b9e540e80f768e1c84b9b0-f76d133c347f523767a620b630f2498fb90bce966b93c15365e73eb30bcdc13f-removing"
time="2019-11-10T14:26:36.779448600Z" level=debug msg="Ignoring invalid digest sha256:ab7432f3f9fb935efbbbb4777929f08f18c483e82ea187dd91a7458ec683dc85-2ab7fb0e0532736b972a17175ad32f706083d7718b5bd07980aa4bf63c84cced-removing"
time="2019-11-10T14:26:36.779448600Z" level=debug msg="Ignoring invalid digest sha256:b4b2843ac12109c6e5d084e589586433086883e7df86ce03d4430e27b1b8baba-9f047110cf7102d64f219cd5964035c15db3a8b9e2c92c16abe3a1d1e53849b9-removing"
time="2019-11-10T14:26:36.780448600Z" level=debug msg="Ignoring invalid digest sha256:ba420aeb30723506ef1aff5db6b81f12a65f05976b60e473a4fa65ae47eb8e17-4f3c276f42cd60e3279a0b2aade8d814e8c63f8be2f3f274795b74369aa8be23-removing"
time="2019-11-10T14:26:36.783448100Z" level=debug msg="Ignoring invalid digest sha256:c06439d0575849cee99502d14fc17564eeea1540319be44082f19f8b270cab57-1fb34f9591bd10f40d205dc8ccb85974f1ea258d47e8f3de33253ac0327e580c-removing"
time="2019-11-10T14:26:36.783448100Z" level=debug msg="Ignoring invalid digest sha256:cd004f09c238e8b02ef56a2d31e62b152620360628707ed24b2e007f26d1a240-9cbb6f1a5f9d646e1822ec4de2251a7ea2d612710bfa6991fe407a832935345f-removing"
time="2019-11-10T14:26:36.784396400Z" level=debug msg="Ignoring invalid digest sha256:cfa9069b7b0e6f373f23f2bb37b322be88341bda706b5d6f070f21369b6845ae-9bcad79d920ffe6d03c0e5dfdcedda6b1de2236f8f6f55bd8230ebb14435a7c6-removing"
time="2019-11-10T14:26:36.784396400Z" level=debug msg="Ignoring invalid digest sha256:d10492009737c4496b96afa569e9d5af52db2211ee46c5c65c03f03ae7dc4d1e-5904b94aff4c7a9d016c89f839c8b9e482bfc230eb87979747dca149c5f39365-removing"
time="2019-11-10T14:26:36.785401200Z" level=debug msg="Ignoring invalid digest sha256:dee9ca9bfcb1d2ab24a77801904011668972393240b2622a9249dbed0d8688bf-0a843d84759d083861e49a531db01965ea4a311ae7818efb52497cc64d170f34-removing"
time="2019-11-10T14:26:36.785401200Z" level=debug msg="Ignoring invalid digest sha256:e8ea8559c77de95338e4f81cb2d735220f35b137365ed130485844cd71c4e144-540a24eb7e069c5b6441b77c2fc6f1123aa52b72a2f414e59d8183fee230e4d4-removing"
time="2019- [...]

2019-11-12 03:03 UTC, vikramhh commented
The above issue was a false positive and we were able to move on and get a repro of the original issue [0x490]. Issue was reproed with tracing enabled - @kevpar is taking a look.

2019-11-12 20:21 UTC, kevpar commented
@thaJeztah I'm on the Docker Community Slack. Is there a specific channel I should make sure I'm on?

@vikramhh It looks like the "Element not found" error can occur when running a container that exits immediately. There is a race condition that can cause Docker to still try to query for things like the stdio handles after the container has already exited and been cleaned up. I need to investigate further to determine what has changed to cause this.

2019-11-12 22:30 UTC, thaJeztah commented
I can add you both to the maintainers channel, which would give a more "quiet" channel to discuss if needed

2019-11-15 22:15 UTC, vikramhh commented
Changed the title to reflect the fact that we had to bump hcsshim to take in https://github.com/microsoft/hcsshim/pull/737

2019-11-15 23:21 UTC, thaJeztah commented
Looks like you may have to run `vndr` again;

```
[2019-11-15T22:42:52.013Z] The result of vndr differs
[2019-11-15T22:42:52.013Z] 
[2019-11-15T22:42:52.013Z]  D vendor/github.com/containerd/cgroups/stats/v1/metrics.pb.txt
[2019-11-15T22:42:52.013Z]  M vendor/github.com/containerd/cgroups/stats/v1/metrics.proto
[2019-11-15T22:42:52.013Z] 
[2019-11-15T22:42:52.013Z] Please vendor your package with github.com/LK4D4/vndr.
[2019-11-15T22:42:52.013Z] 
[2019-11-15T22:42:52.013Z] diff --git a/vendor/github.com/containerd/cgroups/stats/v1/metrics.proto b/ve
[2019-11-15T22:42:52.013Z] ndor/github.com/containerd/cgroups/stats/v1/metrics.proto
[2019-11-15T22:42:52.013Z] index e821e8407..ba6be851d 100644
[2019-11-15T22:42:52.013Z] --- a/vendor/github.com/containerd/cgroups/stats/v1/metrics.proto
[2019-11-15T22:42:52.013Z] +++ b/vendor/github.com/containerd/cgroups/stats/v1/metrics.proto
[2019-11-15T22:42:52.013Z] @@ -135,6 +135,7 @@ message NetworkStat {
[2019-11-15T22:42:52.013Z]  	uint64 tx_errors = 8;
[2019-11-15T22:42:52.013Z]  	uint64 tx_dropped = 9;
[2019-11-15T22:42:52.013Z]  }
[2019-11-15T22:42:52.013Z] +
[2019-11-15T22:42:52.013Z]  // CgroupStats exports per-cgroup statistics.
[2019-11-15T22:42:52.013Z]  message CgroupStats {
[2019-11-15T22:42:52.013Z]  	// number of tasks sleeping
```

2019-11-16 06:25 UTC, vikramhh commented
@thaJeztah - would you recommend running RS1 tests as well for this?

2019-11-16 18:23 UTC, thaJeztah commented
restarted CI with RS1 enabled as well

2019-11-18 01:07 UTC, vikramhh commented
@thaJeztah - the RS1 failures seem to be known flaky tests mentioned in https://github.com/moby/moby/pull/39885 - does this look good to go otherwise?

2019-11-18 05:29 UTC, thaJeztah commented
Yes, if it's ready for review, feel free to move it out of draft

2019-11-21 19:01 UTC, thaJeztah approved these changes
LGTM

2019-11-22 17:16 UTC, vikramhh commented
@kolyshkin - Looks like I need two reviewers for getting a merge done. Could you please take a look.

2019-11-22 21:06 UTC, kolyshkin commented
I am seeing the following failure on Windows RS1

> [2019-11-22T18:31:50.937Z]     --- FAIL: TestDockerSuite/TestRunAttachFailedNoLeak (4.19s)

> [2019-11-22T18:31:50.937Z]         docker_cli_run_test.go:3948: assertion failed: expression is false: strings.Contains(out, "port is already allocated") || strings.Contains(out, "were not connected because a duplicate name exists") || strings.Contains(out, "The specified port already exists") || strings.Contains(out, "HNS failed with error : Failed to create endpoint") || strings.Contains(out, "HNS failed with error : The object already exists"): Output: d:\CI\PR-40128\20\binary\docker.exe: Error response from daemon: failed to create endpoint fail on network nat: hns failed with error : The object already exists.

and it looks like it's relevant.

@vikramhh I suggest you fix this test case to do case-insensitive comparison instead (just lowercase `out` before doing comparisons, and make sure all comprarison strings are also lowercased).

2019-11-22 21:09 UTC, kolyshkin commented
> just lowercase out before doing comparisons, and make sure all comprarison strings are also lowercased

i.e. something like
```diff
diff --git a/integration-cli/docker_cli_run_test.go b/integration-cli/docker_cli_run_test.go
index af9044a92c..4271aba72e 100644
--- a/integration-cli/docker_cli_run_test.go
+++ b/integration-cli/docker_cli_run_test.go
@@ -3945,11 +3945,11 @@ func (s *DockerSuite) TestRunAttachFailedNoLeak(c *testing.T) {
        assert.Assert(c, err != nil, "Command should have failed but succeeded with: %s\nContainer 'test' [%+v]: %s\nContainer 'fail' [%+v]: %s", out, err1, out1, err2, out2)
        // check for windows error as well
        // TODO Windows Post TP5. Fix the error message string
-       assert.Assert(c, strings.Contains(out, "port is already allocated") ||
+       assert.Assert(c, strings.Contains(strings.ToLower(out), "port is already allocated") ||
                strings.Contains(out, "were not connected because a duplicate name exists") ||
-               strings.Contains(out, "The specified port already exists") ||
-               strings.Contains(out, "HNS failed with error : Failed to create endpoint") ||
-               strings.Contains(out, "HNS failed with error : The object already exists"), fmt.Sprintf("Output: %s", out))
+               strings.Contains(out, "the specified port already exists") ||
+               strings.Contains(out, "hns failed with error : failed to create endpoint") ||
+               strings.Contains(out, "hns failed with error : the object already exists"), fmt.Sprintf("Output: %s", out))
        dockerCmd(c, "rm", "-f", "test")
 
        // NGoroutines is not updated right away, so we need to wait before failing
```

2019-11-24 13:18 UTC, vikramhh commented
@kolyshkin - Thanks for the review. I have fixed `TestRunAttachFailedNoLeak` per your suggestion and verified that it passes RS1 checks. Ready to merge unless you have any other comments.

2019-11-25 11:15 UTC, kolyshkin approved these changes
LGTM

2019-11-25 11:18 UTC, kolyshkin commented on integration-cli/docker_cli_run_test.go
> +	assert.Assert(c, strings.Contains(strings.ToLower(out), "port is already allocated") ||
I would suggest to do
```go
out = strings.ToLower(out)
```
instead. Otherwise, this code is doing it five times :-\

2019-11-25 11:19 UTC, kolyshkin commented on integration-cli/docker_cli_run_test.go
> +	assert.Assert(c, strings.Contains(strings.ToLower(out), "port is already allocated") ||
Also, test change would be better as a separate commit (preceding the one updating the vendor)

2019-11-25 11:19 UTC, kolyshkin requested changes
Please see comments above

2019-11-25 13:10 UTC, thaJeztah commented
@vikramhh I see you updated the tests, but could you move that change to a separate commit, as requested by @kolyshkin ?

2019-11-25 13:45 UTC, vikramhh commented
@thaJeztah - how do I "split" a commit? Just remove the test related files and force push it?

2019-11-25 17:40 UTC, closed without merging

2019-11-30 04:20 UTC, ebalders commented
I see this has been merged, any idea when it will be integrated into a Docker release?

2019-11-30 05:11 UTC, kolyshkin commented
@ebalders this one was not merged; #40250 was. In there you will be able to see links to backports to 19.03 branch and monitor it