Don't re-create volumes (fixes #40047)
moby/moby pull request #40267
Opened 2019-11-28 17:52 UTC by sh7dm

**- What I did**
Fixed #40047
**- How I did it**
Added a check so if volume is already created `Create` method just returns it.
**- How to verify it**
Run a new `TestServiceCreateLogs` unit test
**- Description for the changelog**
Don't re-create volumes (#40047) 
**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://user-images.githubusercontent.com/19504461/69825595-dcbf4f00-1220-11ea-980f-5e8f9fb32d6a.png)

2019-12-19 19:24 UTC, thaJeztah commented
Discussing in the maintainers meeting with @cpuguy83, and he mentioned that this could potentially be racy (the driver returning that the volume exists, but it may no longer exist the moment the volume is used by the container). Perhaps only a small risk, but something we should take into account

2019-12-19 19:27 UTC, thaJeztah commented on volume/service/service.go
> +	v, err := s.vs.Create(ctx, name, driverName, options...)
Perhaps instead we should make this return wether or not it created the volume, and send the right event based on that?

2019-12-19 19:28 UTC, cpuguy83 requested changes

2019-12-19 19:28 UTC, cpuguy83 commented on volume/service/service.go
> +	oldV, err := s.Get(ctx, name, opts.WithGetDriver(driverName))
This is breaking some things, namely it is getting the volume without passing through any references.

In terms of not getting multiple creates, this is also somewhat racey.
Instead we could return from s.vs.Create if the volume was actually created or not.

2022-02-04 17:21 UTC, thaJeztah commented
Looks like this still needed some work, and the `create` event always being emitted should be fixed by https://github.com/moby/moby/pull/42028, so let me go ahead and  close this for now.

Thanks @sh7dm !

2022-02-04 17:21 UTC, closed without merging