update vendor golang.org/x/sys
moby/moby pull request #40274
Opened 2019-11-29 10:09 UTC by XiaodongLoong

execute "docker run -it {image name} /bin/sh" no response on mip64el platform;
EpollEvent struct define lack a field named PadFd;
add the field "PadFd";
execcute docker run -it {image} /bin/sh for test after rebuilded.

2019-11-29 10:13 UTC, AkihiroSuda requested changes
Please sign with real name, then LGTM

2019-11-29 12:39 UTC, thaJeztah commented
Looks like `vndr` also has to be run again to get the updated files;

```
[2019-11-29T10:37:43.517Z] The result of vndr differs
[2019-11-29T10:37:43.517Z] 
[2019-11-29T10:37:43.517Z]  M vendor/golang.org/x/sys/cpu/cpu_mips64x.go
[2019-11-29T10:37:43.517Z]  M vendor/golang.org/x/sys/cpu/cpu_mipsx.go
[2019-11-29T10:37:43.518Z]  M vendor/golang.org/x/sys/cpu/cpu_other_arm64.go
....
```

2019-12-02 02:12 UTC, XiaodongLoong commented
@AkihiroSuda 
Nice to meet you. I am a Chinese people and family name is first named "Liu".  My real name is Liu Xiaodong(刘 小东). So the sign is OK.
Thanks!

2019-12-02 02:21 UTC, XiaodongLoong commented
@thaJeztah How to run the "vndr" tool again, Can I excute the operation?

2019-12-02 03:07 UTC, AkihiroSuda commented
"Signed-off-by: root" isn't correct

2019-12-02 06:01 UTC, closed without merging