update runc to rc10
moby/moby pull request #40404
Opened 2020-01-24 07:28 UTC by AkihiroSuda

2020-01-24 11:29 UTC, thaJeztah commented
Could you

- update the commit message to say `v1.0.0-rc10` instead of just `rc10` ?
- should the `binary` and `vendor` changes be in separate commits? (so that we can cherry-pick separate if needed)

Also  the commit message for the binary update should probably contain some details about the changes, as this update of runc includes https://github.com/opencontainers/runc/pull/2207, which fixes: CVE-2019-19921 (as reported in https://github.com/opencontainers/runc/issues/2197)

Given, I don't think the CVE affects docker, but it might still be useful to have

Are there other notable changes? This is the full diff upstream; https://github.com/opencontainers/runc/compare/v1.0.0-rc9...v1.0.0-rc10


Finally; should we wait for https://github.com/containerd/containerd/pull/3973 to be merged (and backported to a containerd release) so that we can update both?

2020-01-24 11:29 UTC, thaJeztah requested changes
see my comment 🤗

2020-01-24 19:05 UTC, AkihiroSuda commented
updated

2020-01-24 19:07 UTC, AkihiroSuda commented
> Finally; should we wait for containerd/containerd#3973 to be merged (and backported to a containerd release) so that we can update both?

Seems not worth doing. If we need, we can do in a separate PR.

2020-01-25 00:56 UTC, thaJeztah approved these changes
LGTM

2020-01-25 15:58 UTC, tao12345666333 approved these changes
LGTM :+1:

2020-01-25 19:00 UTC, cpuguy83 approved these changes
LGTM

2020-01-25 19:00 UTC, merged