Add stats options to not prime the stats
moby/moby pull request #40478
Opened 2020-02-08 00:08 UTC by cpuguy83

Metrics collectors generally don't need the daemon to prime the stats
with something to compare since they already have something to compare
with.
Before this change, the API does 2 collection cycles (which takes
roughly 2s) in order to provide comparison for CPU usage over 1s. This
was primarily added so that `docker stats --no-stream` had something to
compare against.

Really the CLI should have just made a 2nd call and done the comparison
itself rather than forcing it on all API consumers.
That ship has long sailed, though.

With this change, clients can set an option to just pull a single stat,
which is *at least* a full second faster:

Old:
```
time curl --unix-socket
/go/src/github.com/docker/docker/bundles/test-integration-shell/docker.sock
http://./containers/test/stats?stream=false\&one-shot=false > /dev/null
2>&1

real0m1.864s
user0m0.005s
sys0m0.007s

time curl --unix-socket
/go/src/github.com/docker/docker/bundles/test-integration-shell/docker.sock
http://./containers/test/stats?stream=false\&one-shot=false > /dev/null
2>&1

real0m1.173s
user0m0.010s
sys0m0.006s
```

New:
```
time curl --unix-socket
/go/src/github.com/docker/docker/bundles/test-integration-shell/docker.sock
http://./containers/test/stats?stream=false\&one-shot=true > /dev/null
2>&1
real0m0.680s
user0m0.008s
sys0m0.004s

time curl --unix-socket
/go/src/github.com/docker/docker/bundles/test-integration-shell/docker.sock
http://./containers/test/stats?stream=false\&one-shot=true > /dev/null
2>&1

real0m0.156s
user0m0.007s
sys0m0.007s
```

This fixes issues with downstream's ability to use the stats API to
collect metrics.

Fixes #40437

2020-02-08 03:06 UTC, cpuguy83 commented
I'm wondering if we could just "fix" this for 19.03. Basically just change the cli to make two requests. Old api clients we will still do the old behavior but for 19.03+ we do one.
It will break "--no-stream" on cli's older than 19.03.7, but we can just tell ppl to upgrade.

There is the possibility that other, non-docker cli clients may break.
I don't know.

2020-02-13 19:42 UTC, cpuguy83 commented on api/server/router/container/container_routes.go
> +	if versions.GreaterThanOrEqualTo(httputils.VersionFromContext(ctx), "1.v1") {
lol

2020-02-27 20:05 UTC, tonistiigi requested changes
https://github.com/moby/moby/pull/40478/files#r379079096

Otherwise lgtm

2020-02-27 20:05 UTC, thaJeztah commented on docs/api/version-history.md
> +* `GET /containers/{id}/stats` now accepts a query param (`one-shot`) which, when used with `stream=false` fetches a
Don't forget to update the swagger

2020-02-28 17:55 UTC, cpuguy83 commented on docs/api/version-history.md
> +* `GET /containers/{id}/stats` now accepts a query param (`one-shot`) which, when used with `stream=false` fetches a
Updated swagger.

2020-02-28 17:55 UTC, cpuguy83 commented
Fixed API version typo, should be good to go.

2020-02-29 04:40 UTC, tonistiigi approved these changes

2020-04-16 18:56 UTC, thaJeztah approved these changes
LGTM

2020-04-16 18:57 UTC, merged