Set Init=true by default on container create
moby/moby pull request #40770
Opened 2020-04-03 19:38 UTC by cpuguy83

This means any new containers, unless explicitly specified, created with
API version 1.41 will have init enabled by default. This default can be
controlled by the daemon-level `--init` setting.

2020-04-03 21:23 UTC, AkihiroSuda commented
I feel this is too much "brave". This is likely to break containers with non-tini init.

2020-04-03 21:25 UTC, AkihiroSuda requested changes
Sorry, NOTLGTM

2020-04-06 16:09 UTC, cpuguy83 commented
I understand it is pretty brave.
How can we get to a point where we can provide a better and much more correct default container implementation?

Note that this does not change existing containers and only affects clients using the new API version. Also able to change this based on the value set in the daemon config.
Maybe we could have an exclusion list of some sort as well? Default could have `strings.HasPrefix(cmd, "/sbin/init")`, but make it configurable?

Given that we are not releasing a new version of Docker every quarter like we used to, I wonder if we can go ahead and make changes like this and make sure it's well documented in the release notes.

2020-04-26 07:48 UTC, tao12345666333 commented
Changes in the default behavior may cause confusion, or under certain circumstances will break the working logic of some containers.(may be some specific hack)

But I think we should move forward.  

+1 for this change.

2020-09-08 23:31 UTC, kolyshkin approved these changes
I think it's the right move. 

LGTM (except this needs a rebase -- @cpuguy83)

2020-09-09 00:04 UTC, AkihiroSuda commented
I think this should be enabled only if the image has LABEL=com.docker.image.default.init=true

2023-07-05 22:25 UTC, cpuguy83 commented
This seems too controversial so closing.

2023-07-05 22:25 UTC, closed without merging