plugin: Add No-Lock version of resolvePluginID to fix double Rlock
moby/moby pull request #40867
Opened 2020-04-28 15:53 UTC by BurtonQin

**- What I did**
Fix a double RLock in `GetV2Plugin()` in plugin/store.go.

**- How I did it**
Add a new function `resolvePluginIDNoLock()` which has all the content of the original `resolvePluginID()` except the lock. Then make `resolvePluginID()` call the NoLock version with lock protection. Replace the call to `resolvePluginID()` in `GetV2Plugin()` with the NoLock version.

**- How to verify it**
As the [https://golang.org/pkg/sync/](https://golang.org/pkg/sync/) says about RLock:
`It should not be used for recursive read locking; a blocked Lock call excludes new readers from acquiring the lock.`
So double read lock should also be avoided.

The first lock is in `GetV2Plugin()`. Then it calls `resolvePluginID()`, where the second lock resides.

After the patch, the second lock is removed.

**- Description for the changelog**
Add a new function `resolvePluginIDNoLock()` which has all the content of the original `resolvePluginID()` except the lock. Then make `resolvePluginID()` call the NoLock version with lock protection. Replace the call to `resolvePluginID()` in `GetV2Plugin()` with the NoLock version.

**- A picture of a cute animal (not mandatory but encouraged)**
![rabbit](https://user-images.githubusercontent.com/11943383/80509029-65e2d980-89ab-11ea-842e-86a5f81f75c8.jpg)

2020-04-28 15:57 UTC, cpuguy83 approved these changes
LGTM

2020-04-29 03:21 UTC, BurtonQin commented
According to the report, `resolvePluginID()` is not used. 
It seems that GetV2Plugin() is the only caller of it.

I think the easiest way to fix this is to remove the lock in the old resolvePluginID() and add a comment for lock protection.

2020-05-15 12:04 UTC, thaJeztah requested changes
thanks! changes LGTM, but could you squash the commits? Looks like the second commit is reverting some of the changes that were made in the first commit, and we don't need that intermediate state in the git history 😅 


let me know if you need a hand with that1

2020-05-15 14:42 UTC, BurtonQin commented
Squashed the second commit and modified the msg to make it clear.

2020-05-15 16:06 UTC, thaJeztah approved these changes
LGTM, thanks!

2020-05-15 16:07 UTC, merged