[19.03 backport] Reduce allocations for logfile reader
moby/moby pull request #41130
Opened 2020-06-19 22:03 UTC by kzys

(This is a backport of #40796)

Before this change, the log decoder function provided by the log driver
to logfile would not be able to re-use buffers, causing undeeded
allocations and memory bloat for dockerd.

This change introduces an interface that allows the log driver to manage
it's memory usge more effectively.
This only affects json-file and local log drivers.

`json-file` still is not great just because of how the json decoder in the
stdlib works.
`local` is significantly improved.

2020-06-22 10:51 UTC, thaJeztah requested changes
I think we discussed backporting this one, but considered it too big of a change (and risk) for backporting, so this may need some discussion.

Also looks like the cherry-pick was done without the `-x` option to include a reference to the original commit (so _if_ we decide it's ok to backport, I'd prefer that to be done as well)

ping @cpuguy83

2020-06-22 16:27 UTC, cpuguy83 commented
Agreed, this is a risky backport.

2020-06-22 16:36 UTC, kzys commented
Thanks @thaJeztah and @cpuguy83. I didn't know the discussion. I work at AWS and have a customer who is affected by the issue.

I'm happy to help 20.03 work in that case. Thanks!

2020-06-23 08:44 UTC, thaJeztah commented
> I didn't know the discussion.

I probably should've left a comment on the original PR. We discussed it in our maintainers call, but the original PR didn't have a backport request, so I didn't think of leaving a comment there.

Let me close this backport (at least for now). Thanks for your understanding, and thanks for opening the backport; even though this one was not accepted (for reasons mentioned), don't let that stop you from bringing important fixes to our attention to consider backporting <3

2020-06-23 08:44 UTC, closed without merging