info: improve "WARNING: Running in rootless-mode without cgroup"
moby/moby pull request #41157
Opened 2020-06-26 08:59 UTC by AkihiroSuda

The cgroup v2 mode uses systemd driver by default.
Suggesting to set exec-opt "native.cgroupdriver=systemd" isn't meaningful.

2020-06-26 14:26 UTC, thaJeztah requested changes

2020-06-26 14:26 UTC, thaJeztah commented on daemon/info_unix.go
> +			v.Warnings = append(v.Warnings, "WARNING: Running in rootless-mode without cgroup. Systemd is required to enable cgroup in rootless-mode.")
perhaps `s/cgroup/cgroups/` ?

```suggestion
			v.Warnings = append(v.Warnings, "WARNING: Running in rootless-mode without cgroups. Systemd is required to enable cgroups in rootless-mode.")
```

2020-06-26 14:26 UTC, thaJeztah commented on daemon/info_unix.go
> +			v.Warnings = append(v.Warnings, "WARNING: Running in rootless-mode without cgroup. To enable cgroup in rootless-mode, you need to boot the system in cgroup v2 mode.")
```suggestion
			v.Warnings = append(v.Warnings, "WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.")
```

2020-06-29 12:00 UTC, AkihiroSuda commented on daemon/info_unix.go
> +			v.Warnings = append(v.Warnings, "WARNING: Running in rootless-mode without cgroup. Systemd is required to enable cgroup in rootless-mode.")
fixed

2020-06-29 12:48 UTC, thaJeztah approved these changes
LGTM

2020-07-02 05:09 UTC, AkihiroSuda commented
@cpuguy83 PTAL

2020-07-02 18:35 UTC, tonistiigi approved these changes

2020-07-02 18:35 UTC, merged