Builder: Add 1 buffer to two channels to avoid blocking goroutine
moby/moby pull request #41360
Opened 2020-08-16 04:07 UTC by lzhfromustc

**- What I did**
Avoid two potential goroutine leaks by adding 1 buffer to the channels.
In the code below, if the function returns at line 75, then the child goroutine created at Line 49 will be leaked. 
https://github.com/moby/moby/blob/e9b4655bc98563602d961c72fc62cb20cc143515/builder/dockerfile/containerbackend.go#L48-L56
https://github.com/moby/moby/blob/e9b4655bc98563602d961c72fc62cb20cc143515/builder/dockerfile/containerbackend.go#L72-L76

A similar patch is for errCh in the following code
https://github.com/moby/moby/blob/e9b4655bc98563602d961c72fc62cb20cc143515/integration/plugin/logging/read_test.go#L76-L87

**- How to verify it**
This patch is very safe. After adding one buffer to the channels, the semantics of the program will not be changed because receive will still be blocking, except that the child goroutine can always be ended.
This patch is similar to #40144

**- Description for the changelog**
NONE

2020-08-17 09:51 UTC, thaJeztah commented
Possibly flaky test; let me post here for easier finding back the failure;

```
=== RUN   TestDockerSwarmSuite/TestServiceLogsCompleteness
    --- FAIL: TestDockerSwarmSuite/TestServiceLogsCompleteness (38.43s)
        docker_cli_service_logs_test.go:84: timeout hit after 30s: output, "2020-08-16T04:51:00.614564316Z log test 0\n2020-08-16T04:51:00.614604981Z log test 1\n2020-08-16T04:51:00.614610261Z log test 2\n2020-08-16T04:51:00.614614324Z log test 3\n2020-08-16T04:51:00.614618230Z log test 4\n2020-08-16T04:51:00.614622145Z log test 5\n2020-08-16T04:50:43.675502339Z log test 0\n2020-08-16T04:50:43.675529484Z log test 1\n2020-08-16T04:50:43.675534657Z log test 2\n2020-08-16T04:50:43.675538149Z log test 3\n2020-08-16T04:50:43.675541646Z log test 4\n2020-08-16T04:50:43.675545009Z log test 5\n2020-08-16T04:50:49.243157195Z log test 0\n2020-08-16T04:50:49.243195856Z log test 1\n2020-08-16T04:50:49.243201248Z log test 2\n2020-08-16T04:50:49.243205276Z log test 3\n2020-08-16T04:50:49.243208182Z log test 4\n2020-08-16T04:50:49.243210759Z log test 5\n2020-08-16T04:50:54.919175057Z log test 0\n2020-08-16T04:50:54.919208447Z log test 1\n2020-08-16T04:50:54.919213461Z log test 2\n2020-08-16T04:50:54.919217166Z log test 3\n2020-08-16T04:50:54.919221049Z log test 4\n2020-08-16T04:50:54.919224957Z log test 5\n"
        docker_cli_service_logs_test.go:59: assertion failed: 
            Command:  /usr/local/cli/docker --host unix:///tmp/docker-integration/df55b98991fac.sock service logs -t --raw TestServiceLogsCompleteness
            ExitCode: 1
            Error:    exit status 1
            Stdout:   
            Stderr:   Cannot connect to the Docker daemon at unix:///tmp/docker-integration/df55b98991fac.sock. Is the docker daemon running?
            
            
            Failures:
            ExitCode was 1 expected 0
            Expected no error
```

2020-08-17 09:56 UTC, thaJeztah commented
@lzhfromustc could you change your DCO sign-off to use your real name, instead of your GitHub handle?

```
lzhfromustc <lzhfromustc@gmail.com>
```


You can update your git configuration to use the right name automatically, using;

```bash
git config --global user.name "Ziheng Liu"
```

2020-08-17 09:56 UTC, thaJeztah requested changes
Thanks! Changes itself look good (if green), but left a comment w.r.t. the DCO sign off

2020-08-27 23:00 UTC, lzhfromustc commented
Thanks for reminding! I have changed the signature.

2020-08-27 23:02 UTC, thaJeztah approved these changes
LGTM, thanks!

@AkihiroSuda @cpuguy83 PTAL

2020-09-09 11:16 UTC, thaJeztah commented
@AkihiroSuda @cpuguy83 PTAL

2020-09-13 04:42 UTC, cpuguy83 approved these changes
LGTM

2020-09-13 04:43 UTC, merged