Don't set image on containerd container.
moby/moby pull request #41641
Opened 2020-11-05 21:53 UTC by cpuguy83

We aren't using containerd's image store, so we shouldn't be setting
this value.

This fixes container checkpoints, where containerd attempts to
checkpoint the image since one is set, but the image does not exist in
containerd.

Fixes #41602

2020-11-05 21:53 UTC, cpuguy83 commented
ping @Dudeldu

2020-11-05 21:55 UTC, cpuguy83 commented
Checkpoint tests are disabled in CI (🤷‍♂️)
I also can't verify locally since checkpoint fails for other reasons (criu is throwing an error about iptables).

2020-11-06 01:54 UTC, tianon commented
Looks like this was probably set so that the output of `ctr -n moby c ls` is actually useful/interesting: :disappointed:

```console
/ # ctr -a /var/run/docker/containerd/containerd.sock -n moby c ls
CONTAINER                                                           IMAGE                     RUNTIME                  
0ea20c8634d8b721011adce5ead30e772b6c94b4192a37f4896178ccc78cf5e2    docker.io/library/bash    io.containerd.runc.v2    
```

2020-11-06 01:55 UTC, tianon commented
(Also with this PR it looks like the `withImageName` function is probably now unreferenced/unused?)

2020-11-06 01:57 UTC, tianon commented
@ehazlett any chance we could get you to comment on this? :pray: :heart:

(you appear to have added this back in https://github.com/moby/moby/pull/39082)

2020-11-06 02:51 UTC, tonistiigi approved these changes

2020-11-06 03:10 UTC, ehazlett commented
hey friends :)  Yes this was part of a larger migration effort that didn't materialize.  It should be safe to remove.

❤️

2020-11-06 03:24 UTC, tianon requested changes
Thanks @ehazlett :heart: :heart:

Looks like this is ready for deleting the `withImageName` function at the bottom of the file? :pray: :innocent:

2020-11-06 04:55 UTC, cpuguy83 commented
Should be fixed now

2020-11-06 05:34 UTC, AkihiroSuda approved these changes

2020-11-06 08:34 UTC, Dudeldu commented
@cpuguy83 I tried out your change and it works perfectly. 
Thanks for the quick solution.

2020-11-06 13:58 UTC, thaJeztah approved these changes
LGTM

2020-11-06 13:59 UTC, thaJeztah commented
@tianon LGTY?

2020-11-06 16:43 UTC, tianon approved these changes
LGTM (with a heavy black heart 🖤)

Hopefully someday we can get back to that useful `ctr` output 😅

2020-11-06 16:43 UTC, merged

2020-11-06 17:42 UTC, thaJeztah commented
Should we mention this in the changelog (for users that use `ctr` for debugging purposes?

/cc @tiborvass

2020-11-06 17:56 UTC, cpuguy83 commented
If we really want to we can add a label like `com.docker.image`, but the containerd ID's correlate with Docker container ID's.

2020-11-06 18:07 UTC, tianon commented
Yeah, the label won't show in `ctr c ls` and the IDs correlate, so we're basically just reverting back to the 19.03.x behavior, which IMO makes sense and makes this not need a changelog entry.