swagger.yaml: fix multi-line string indentation
moby/moby pull request #41748
Opened 2020-12-03 14:38 UTC by tmds

A tool I ran on the yaml file didn't like the multi-line string wasn't indented.

2021-03-31 08:58 UTC, tmds commented
@thaJeztah ptal

2021-03-31 12:14 UTC, thaJeztah requested changes
thanks for the ping; looks like I had a review pending, but forgot to submit 😓 .

I see the commit message misses a [DCO sign-off (Signed-off-by line as last line in the commit message)](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work), which causes CI to fail; https://github.com/moby/moby/pull/41748/checks?check_run_id=1493198225

Unfortunately it's not possible to fix commit messages through GitHub's UI, so you'll need to do this from the command line (let me know if you need help).

Could you also update the other API versions accordingly (if they have the same problem)? https://github.com/moby/moby/tree/master/docs/api

2021-03-31 12:14 UTC, thaJeztah commented on api/swagger.yaml
> +              systems, such as SELinux."
Hm; perhaps change to the same format as we use elsewhere for longer descriptions;

```yaml
            description: |
              A list of string values to customize labels for MLS systems, such
              as SELinux.
```

2022-03-05 21:46 UTC, thaJeztah commented
Carrying this as part of https://github.com/moby/moby/pull/43334. Let me close this one

2022-03-05 21:46 UTC, closed without merging