Added Bjarne Stroustrup
moby/moby pull request #41906
Opened 2021-01-20 15:08 UTC by AndersBallegaard

Signed-off-by: Anders Ballegaard <anderstb@hotmail.dk>

2021-01-20 15:12 UTC, thaJeztah commented
Can you also add a female to the list, per: https://github.com/moby/moby/blob/06ca1606e1a09c36bd12ed503b4c99d8a17ca230/pkg/namesgenerator/names-generator.go#L121

2021-01-20 15:13 UTC, thaJeztah requested changes
(see my comment)

2021-01-22 17:15 UTC, thaJeztah requested changes
Thanks for updating; I left one more comment; can you address that (amending the existing commit); perhaps squash the commits as well.

2021-01-22 17:15 UTC, thaJeztah commented on pkg/namesgenerator/names-generator.go
> +		"Bodker",
Can you make this lowercase?

```suggestion
		"bodker",
```

2022-02-11 01:08 UTC, tianon commented
Thank you so much for taking the time to make this contribution!  We're very sorry for how long it has taken us to come to a decision on it, but as of https://github.com/moby/moby/pull/43210 the `namesgenerator` package is now officially "frozen" against new additions.  There is some explanation there as to why it is frozen (and why it has taken us so long to come to a decision on PRs like yours 🙈), but https://github.com/moby/moby/pull/43210#issuecomment-1029934277 is especially good for a longer explanation. :heart:

2022-02-11 01:08 UTC, closed without merging