WIP: Make /sys/fs/cgroup rw
moby/moby pull request #42043
Opened 2021-02-17 20:21 UTC by agowa338

Fixes #42040 

**- What I did**

Makes /sys/fs/cgroup rw. This patch is an only intended as reference as I don't know how to make this change dependent upon the used cgroup version.

It should be rw for cgroup2 and ro for cgroup1 (because of container escapes).

**- How I did it**

**- How to verify it**

**- Description for the changelog**
Allow writing to /sys/fs/cgroup to allow containers to manage there own cgroup spaces and create child spaces. E.g. to run systemd within a container without unnecessary privileges.

2021-02-17 20:25 UTC, thaJeztah commented
/cc @AkihiroSuda @justincormack

2021-02-18 23:52 UTC, AkihiroSuda requested changes
Before changing the default we should have a flag such as `--security-opt cgroupfs-writable=BOOLEAN` to toggle the behavior.

Also, even if we are going to change the default, the default should remain RO when cgroupns is set to the host mode.
And yet I'm not sure whether cgroup2 is really guaranteed to be safely writable. The current version might be safe, but future version might not be.

So I'm reluctant to change the default.

2021-02-19 03:27 UTC, agowa338 commented
@AkihiroSuda You're right, a flag may be a better option, but I don't know the moby code base well enough to implement this. Therefore I changed the default and marked this PR as WIP so that it is clear what configuration I intend to have changed.

But as to my knowledge having the cgroups writeable should be fine for v2.

2021-02-19 09:18 UTC, AkihiroSuda commented
cc @giuseppe @kolyshkin @cyphar FYI

2021-02-19 10:37 UTC, cyphar commented
Since the cgroup the process is in is the same cgroup where the restrictions are set, I don't think it's at all safe to allow containers to write to cgroup files -- that would allow a container to modify its own restrictions. If we created a sub-cgroup that the container was placed inside, maybe that would be safe but I'm not convinced to be honest.

As an aside, I wonder if you can change the devices eBPF program *today* with a read-only mount -- does `bpf(2)` not allow you to operate on a read-only mounted cgroup?

2021-02-19 10:39 UTC, agowa338 commented
Today you cannot set eBPF (and afaik not even with this patch) as that is filtered (at least that's the error you get when you apply this patch and try to start systemd.

2021-02-19 10:46 UTC, cyphar commented
Yes, `bpf(2)` is blocked by the default seccomp profile (unless your container has `CAP_SYS_ADMIN`) -- the reason I mentioned the devices eBPF is because I hadn't considered whether `BPF_PROG_ATTACH` actually obeys read-only mounts for attaching (and a quick look at the code tells me it doesn't, but I haven't tested it yet).

> Ok, I thought docker already creates a sub-cgroup for the containers. That was my fault than. But having cgroup support within containers would still be very valuable.

I would have to think about how we would implement this, since runc is doing cgroup setup and there isn't a nice way to tell runc to configure a cgroup and then move the program into a sub-cgroup...

> If this doesn't even work with sub-cgroups, is there a change to get this possibility upstream into the linux kernel so that docker can use it?

If containers were placed in a sub-cgroup such that the restricted cgroup is a parent, then this should be safe -- Tejun has said that cgroupv2 is safe for delegation, which tells me that the kernel is giving us a guarantee that this is safe.

2021-02-19 10:48 UTC, agowa338 commented
So we depend upon adding a new feature to runc to allow to create sub-cgroup than?

2023-02-08 15:06 UTC, darkyzhou commented
Any updates? I see podman "solves" this by introducing a new option: --security-opt unmask=/sys/fs/cgroup

https://github.com/containers/podman/pull/9536

2024-11-05 22:49 UTC, tianon commented
In re-reading this thread with fresh eyes, it occurs to me that we're discussing two separate things that I think could be disconnected in order to make some progress?

1. in order to enable this _by default_, we need more functionality/UX design in `runc` (harder)

2. in order to make it possible for users to opt into this (without the full "hammer" that is `--privileged`), I _think_ we just need to add a new security opt and check for it in the following block of code?
   https://github.com/moby/moby/blob/f0cec02a403496e2b1dd1aaf12b2530922e210db/daemon/oci_linux.go#L667-L675

(the argument for the latter without necessarily having the former is that there are use cases where the downsides listed above are not as bad, such as containers that are already mostly unconfined from a cgroups perspective -- certainly better than going all the way to privileged!)

2024-11-15 00:25 UTC, kolyshkin commented
In podman, the relevant CLI option is `--security-opt=unmask=/sys/fs/cgroup`, described [here](https://docs.podman.io/en/v5.2.2/markdown/podman-run.1.html) (look for `unmask).

If at all possible, can the option being added be compatible with podman?

2024-11-16 00:23 UTC, tianon commented
(I've replied to that same question over in https://github.com/moby/moby/pull/48828#issuecomment-2480200001 instead where we're reviewing a explicit proposal adding an option :eyes:)

2025-01-23 19:41 UTC, closed without merging