archive.OverlayWhiteoutFormat: support userxattr
moby/moby pull request #42178
Opened 2021-03-20 05:31 UTC by AkihiroSuda

**- What I did**

Fix #42177 .

**- How I did it**

When `overlay2` driver is running with `userxattr` mode, let archiver use `user.*` xattrs instead of `trusted.*` ones.

**- How to verify it**
- Set up Ubuntu 20.10 host with kernel 5.11  (https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11/amd64/)
- Set up rootless docker, with `overlay2` driver
- Make sure `docker --context=rootless pull python:3.9` succeeds. Previously, this was failing with the following I/O error:
```console
$ docker --context=rootless pull python:3.9
3.9: Pulling from library/python
e22122b926a1: Pull complete 
f29e09ae8373: Extracting [==================================================>]  7.832MB/7.832MB
e319e3daef68: Download complete 
e499244fe254: Download complete 
5a6ebed20e89: Download complete 
56b703a5a371: Download complete 
4dd0a64393b6: Download complete 
1d2280ee5e8b: Download complete 
8b6ce844793f: Download complete 
failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/etc/ca-certificates") failed: createDirWithOverlayOpaque("/etc/rdwoo068623238") failed: failed to mkdir /etc/rdwoo068623238/m/d: mkdir /etc/rdwoo068623238/m/d: input/output error
```

**- Description for the changelog**

archive.OverlayWhiteoutFormat: support userxattr

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

2021-03-22 18:21 UTC, thaJeztah requested changes

2021-03-22 18:21 UTC, thaJeztah commented on pkg/archive/archive.go
> +		UserXAttr bool
Is there a specific subset of `user.*` attributes that's used for this? (looks like we need a "allow" / "deny" list?

2021-03-22 18:21 UTC, thaJeztah commented
Need to have a closer look at the code, but IIUC, basically we're "remapping" `trusted.overlay.xx` properties to `user.overlay.xxx` properties, correct? 

Does that mean we must remap both ways and _remove_ the mapped one? i.e., when writing the tar, change `user.overlay.opaque` to `trusted.overlay.opaque` (and remove the `user.overlay.opaque` attribute) - and vice-versa in the non-rootless situation.

Do we need to prevent the `user.overlay` attributes from being committed when creating an archive _in general_ ? i.e.; prevent users from setting these? Not sure if we do the same for the `trusted.` In a non-rootless scenario; mostly wondering if such attributes would cause issues if present in the actual image;

### with buildkit:

```bash
DOCKER_BUILDKIT=1 docker build -t foo:buildkit -<<EOF
FROM alpine
RUN apk add --no-cache attr
RUN mkdir /trusted-attr && attr -s trusted.overlay.opaque -V y /trusted-attr
RUN mkdir /user-attr && attr -s user.overlay.opaque -V y /user-attr
EOF
```

```bash
docker run --rm foo:buildkit sh -c 'attr -l /trusted-attr && attr -l /user-attr'
Attribute "trusted.overlay.opaque" has a 1 byte value for /trusted-attr
Attribute "user.overlay.opaque" has a 1 byte value for /user-attr
```

### Without BuildKit

```bash
DOCKER_BUILDKIT=0 docker build -t foo:classic -<<EOF
FROM alpine
RUN apk add --no-cache attr
RUN mkdir /trusted-attr && attr -s trusted.overlay.opaque -V y /trusted-attr
RUN mkdir /user-attr && attr -s user.overlay.opaque -V y /user-attr
EOF
```

```bash
docker run --rm foo:classic sh -c 'attr -l /trusted-attr && attr -l /user-attr'
# nothing
```


/cc @tonistiigi

2021-03-23 06:44 UTC, AkihiroSuda commented
Alternative PR: https://github.com/moby/moby/pull/42188

2021-03-23 06:44 UTC, closed without merging