improve and update the readme file and correct the grammatical mistake
moby/moby pull request #42278
Opened 2021-04-09 06:08 UTC by aaryan078

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2021-04-09 19:21 UTC, aaryan078 commented
please someone review it

2021-12-03 15:00 UTC, thaJeztah requested changes
Thanks for contributing; I had a quick look at the changes, but the commit is currently missing a DCO sign-off, and there's various changes that don't look correct.

This file needs a cleanup overall, so with only the two punctuation changes remaining in this PR, I think the changes are too marginal for that, so I'll go ahead and close this.

2021-12-03 15:00 UTC, thaJeztah commented on README.md
> +
This doesn't look correct; there should be no empty line between bullets

2021-12-03 15:00 UTC, thaJeztah commented on README.md
> +
Same here (and the ones below)

2021-12-03 15:00 UTC, thaJeztah commented on README.md
> +The releases are supported by the maintainers, community, and users, on a best efforts basis only, and are not intended for customers who want an enterprise or commercial support; Docker EE is the ap
The `an` doesn't look correct here; "users who want enterprise or commercial support" is correct.

That said, `Docker EE` no longer exists, so we should probably remove those bits from this file.

2021-12-03 15:00 UTC, closed without merging