Update runc binary to v1.0.0-rc94
moby/moby pull request #42369
Opened 2021-05-11 02:04 UTC by tao12345666333

full diff opencontainers/runc@v1.0.0-rc93...v1.0.0-rc94

2021-05-11 02:10 UTC, AkihiroSuda requested changes
Please see https://github.com/moby/moby/pull/42308 to fix up the mount path and KernelMemory

2021-05-11 05:45 UTC, tao12345666333 commented
@AkihiroSuda  Should I submit it directly on this PR, or will you separate the commits in #42308

2021-05-11 10:40 UTC, thaJeztah commented
> > Should I submit it directly on this PR, or will you separate the commits in #42308
> 
> You may cherry-pick my commits from #42308 (if you would like).

I opened https://github.com/moby/moby/pull/42370 for the mount path fix, as they should be ok for older runc versions as well  (but the kernel-memory test changes should probably be cherry-picked into this PR)

2021-05-11 15:39 UTC, tao12345666333 commented
I have cherry-picked @AkihiroSuda  's commits. (kernel-memory test changes)
May need to wait #42370 for the mount path fix.

2021-05-12 07:57 UTC, thaJeztah approved these changes
LGTM

yes, this will go green / depends on  https://github.com/moby/moby/pull/42370 to be merged

2021-05-13 00:23 UTC, tianon approved these changes
LGTM

2021-05-13 00:26 UTC, AkihiroSuda approved these changes

2021-05-13 08:35 UTC, YanzhaoLi commented
Hi, will this be patched into docker version 19.03.x? 

BTW, since kuberentes 1.20.x depends on docker 19.03 whose latest containerd version is 1.3.9 which doesn't include runc-1.0.0-rc94.  
So can I just patch the containerd 1.4.5 into docker 19.03? Will that breaking docker or can I have test to verify the compatibility?

2021-05-17 16:51 UTC, tao12345666333 commented
ping @thaJeztah can we merge this?

2021-05-17 19:07 UTC, merged