Update report-issue.sh
moby/moby pull request #42547
Opened 2021-06-22 01:17 UTC by xiaoding945

change which to command

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2021-06-22 13:55 UTC, thaJeztah approved these changes
change itself LGTM

but I'm wondering if instead we should remove this script (I know it was created before GitHub had issue templates, but now that it does, I'm not sure this script adds much value)

@xiaoding945 were you using this script, or just stumbled upon this code?

2021-06-22 13:56 UTC, thaJeztah requested changes
oh; looks like your commit is missing a DCO sign off, which makes CI fail (and is needed to accept your contribution); see https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

2021-06-22 16:30 UTC, tianon commented
+1 for removing the script now 😅

2021-06-23 01:11 UTC, xiaoding945 commented
> change itself LGTM
> 
> but I'm wondering if instead we should remove this script (I know it was created before GitHub had issue templates, but now that it does, I'm not sure this script adds much value)
> 
> @xiaoding945 were you using this script, or just stumbled upon this code?

@thaJeztah  yes， just stumbled upon this code

2021-06-23 01:17 UTC, xiaoding945 commented
> +1 for removing the script now 😅

2021-06-23 01:17 UTC, closed without merging

2021-06-24 07:08 UTC, xiaoding945 commented
> oh; looks like your commit is missing a DCO sign off, which makes CI fail (and is needed to accept your contribution); see https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

@thaJeztah hi，i am a newer in moby. I have two problems need your help. 
First ,if i want to build a docker base image by an iso (or special yum repo) ,which script should i use，does this?https://github.com/moby/moby/blob/master/contrib/mkimage-yum.sh
Second,i want to join slack ,but i visit the url(https://app.mobilize.io/registrations/groups/4316) ,it occurs some wrong
![image](https://user-images.githubusercontent.com/19324666/123218118-e9d81900-d4fd-11eb-9428-2c47ea98082b.png)

thks!