libnetwork: processEndpointCreate: Fix deadlock between getSvcRecords and processEndpointCreate
moby/moby pull request #42569
Opened 2021-06-28 07:03 UTC by steffengy

Another similar case occured with a fixed build. Removed holding multiple locks for processEndpointCreate aswell.

In terms of lock hierarchy I also thought about locking `n.ctrlr.Lock()` before `n.Lock()` in
`getSvcRecords()` to possibly prevent other cases where the locking can't be split like here (e.g. both looks need to be held). 
But that might be not wanted because of data races (accessing networks data before its locked).
If the controller of a network cant change, it probably would be prefered though.

References https://github.com/moby/moby/pull/42545

@thaJeztah

2021-06-28 08:39 UTC, thaJeztah commented
> In terms of lock hierarchy I also thought about locking n.ctrlr.Lock() before n.Lock() in
getSvcRecords() to possibly prevent other cases where the locking can't be split like here (e.g. both looks need to be held).
But that might be not wanted because of data races (accessing networks data before its locked).
If the controller of a network cant change, it probably would be prefered though.


Perhaps if you have an alternative, could you also open a draft PR to see what those changes would look like? Perhaps it can help to "see" the changes, and have a quick discussion on those changes.

2021-06-28 08:39 UTC, thaJeztah approved these changes
LGTM

2021-06-28 21:57 UTC, ongweiloon777 commented
[diff]()

2021-06-29 00:22 UTC, samuelkarp reviewed
Two variable naming changes identified by the linter, but otherwise LGTM.

The other CI failure is the same thing as https://github.com/moby/moby/issues/42484.

2021-06-29 00:22 UTC, samuelkarp commented on libnetwork/store.go
> +	networkId := n.ID()
From the linter:

> libnetwork/store.go:343:2: var `networkId` should be `networkID` (golint)

2021-06-29 00:22 UTC, samuelkarp commented on libnetwork/store.go
> +	endpointId := ep.ID()
From the linter:

> libnetwork/store.go:344:2: var `endpointId` should be `endpointID` (golint)

2021-06-29 00:31 UTC, ongweiloon777 requested changes
rqs

2021-06-29 21:14 UTC, thaJeztah commented
@samuelkarp variable name was updated; PTAL

2021-06-29 21:27 UTC, samuelkarp approved these changes
LGTM

2021-06-30 09:09 UTC, merged