fixes a potential deadlock
moby/moby pull request #42575
Opened 2021-06-29 04:38 UTC by charlesxsh

Signed-off-by: Shihao Xia <charlesxsh@hotmail.com>

**- What I did**
fixes a potential deadlock

**- How I did it**

https://github.com/moby/moby/blob/d12fc17073431ebe74ff0b1b3e5a739301c1760a/daemon/graphdriver/devmapper/devmapper_test.go#L139-L159

If line 148 happened first, there will be no receiver for doneChan created at line 139. In that case, line 144, sending operation of doneChan might be blocked forever.

**- How to verify it**

**- Description for the changelog**

fixes a potential deadlock

**- A picture of a cute animal (not mandatory but encouraged)**

2021-06-30 09:14 UTC, thaJeztah approved these changes
LGTM

2021-07-18 20:02 UTC, songlh commented
could we merge this pull request?

2021-07-19 12:18 UTC, thaJeztah commented
Waiting on a second reviewer to LGTM

@AkihiroSuda @cpuguy83 @kolyshkin ptal

2021-07-19 21:31 UTC, samuelkarp commented
Not LGTM.

It looks like this test is actually testing whether `driver.DeviceSet.cleanupDeletedDevices()` hangs and uses an intentional deadlock as the detection mechanism.  The proposed change here will allow the test to pass even if `driver.DeviceSet.cleanupDeletedDevices()` doesn't successfully release the `driver.DeviceSet` lock.

2021-07-20 14:51 UTC, charlesxsh commented
> Not LGTM.
> 
> It looks like this test is actually testing whether `driver.DeviceSet.cleanupDeletedDevices()` hangs and uses an intentional deadlock as the detection mechanism. The proposed change here will allow the test to pass even if `driver.DeviceSet.cleanupDeletedDevices()` doesn't successfully release the `driver.DeviceSet` lock.

If `driver.DeviceSet.cleanupDeletedDevices()` hangs (driver.DeviceSet has not been released), `case <-time.After(time.Second * 5): ` will be chose and test will fail. The proposed change does not allow test to pass if driver.DeviceSet.cleanupDeletedDevices() doesn't successfully release the driver.DeviceSet lock since child goroutine will be stuck at line 142 and then stuck at line 144 after manual call `driver.DeviceSet.Unlock()` at line 152 (since unbuffer channel send will stuck if no receiver). 

The proposed change simply allow child goroutine to properly exit if timeout happened.

2021-07-21 18:14 UTC, cpuguy83 requested changes
This is a poorly written test because no matter what we'll have a blocking goroutine on failure.
It would be better to let this test timeout properly and panic the test suite, I think.

2021-07-23 23:46 UTC, tianon commented
@songlh as in https://github.com/moby/moby/pull/42576#issuecomment-885964112, I'm curious what your interest here is?  Just asking us to merge a pull request without providing more details on _why_ isn't exactly helpful.

2021-07-29 16:47 UTC, songlh commented
@tianon This bug is found by our dynamic bug detection tool. We want to know programmers decision and feeling about this bug.

2021-09-02 18:45 UTC, thaJeztah commented
Given the discussion above, and that this is only in a test, I'll close this one

2021-09-02 18:45 UTC, closed without merging