Make daemon proxy settings configurable through daemon.json
moby/moby pull request #42647
Opened 2021-07-16 11:49 UTC by aiordache

Added proxy properties to daemon configuration (config file and dockerd flags).

**- How to verify it**

```
$ cat daemon.json 
{
    "http-proxy": "http://proxytest.example.com:80",
    "https-proxy": "https://proxytest.example.com:443"
}

$ dockerd --config-file daemon.json
```

```
$ docker pull busybox
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp: lookup proxytest.example.com on 127.0.0.11:53: no such host

# docker build .     
Sending build context to Docker daemon  89.28MB
Step 1/3 : FROM golang:1.16-alpine AS base
Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp: lookup proxytest.example.com on 127.0.0.11:53: no such host

```

2021-07-16 16:26 UTC, thaJeztah commented on daemon/info.go
> +		NoProxy:            getEnvOrConfig(daemon.configStore.NoProxy, "NO_PROXY", "no_proxy"),
Hm.. but this only changes what's shown in `docker info`, but not actually configures the daemon to use these proxies? 🤔 

FWIW, default behavior; https://github.com/golang/go/blob/912f0750472dd4f674b69ca1616bfaf377af1805/src/net/http/transport.go#L422-L441 / https://github.com/golang/go/blob/912f0750472dd4f674b69ca1616bfaf377af1805/src/net/http/transport.go#L43-L54

(and we are using https://github.com/docker/go-connections for some central/default configuration, which may be relevant)

2021-07-16 16:27 UTC, thaJeztah commented on daemon/info.go
> +		os.Setenv(e, config)
Ah, right. Guess this is the "magic" bit

2021-07-16 16:36 UTC, ongweiloon777 approved these changes

2021-07-16 17:18 UTC, ongweiloon777 approved these changes

2021-07-16 23:55 UTC, tianon commented
Honestly having a really hard time understanding the justification here -- why not use the frankly pretty well standardized environment variables instead?

2021-08-27 16:47 UTC, fredericdalleau approved these changes
LGTM

2021-08-31 13:32 UTC, thaJeztah requested changes
Thanks! Sorry for the late reply on this one. I started a review, and had a branch with changes, but didn't post it, and had to rebase my branch to still work against master. Let me know if you want to take my branch or if I should push it as a separate PR (I left some commits un-squashed to explain the steps, and should probably squash those); https://github.com/moby/moby/compare/master...thaJeztah:proxy_daemon_config_carry?expand=1

2021-08-31 14:45 UTC, tianon commented
> Honestly having a really hard time understanding the justification here -- why not use the frankly pretty well standardized environment variables instead?

To follow up on this thought, the answer is Windows, where adding a variable to a service is anything but straightforward. 😬

2021-09-09 12:07 UTC, thaJeztah commented
Carrying these changes with my review suggestions in https://github.com/moby/moby/pull/42835

2021-09-09 12:07 UTC, closed without merging