Share disk usage computation results between concurrent invocations
moby/moby pull request #42715
Opened 2021-08-06 15:04 UTC by rvolosatovs

**- What I did**
Share disk usage computation results between concurrent invocations instead of throwing error

**- How I did it**
- Introduce and use `pkg/compute.Singleton`, which ensures computations are simultaneously performed by at most one goroutine and the results are propagated to all goroutines simultaneously calling the method. (i.e. if A() is called 20 simultaneously, only do the actual work once and return the computed value to all 20 callers). This package is used by all disk usage computations and therefore the abstraction and minimal loss of type-safety is justified in this case in my opinion. We can also benefit from thoroughly testing the functionality in a fixed location. Once support for generics lands in stable Go, this will be refactored into a type-safe implementation. It is unfortunate, that we have to resort to using `interface{}` here, but that is temporary and consistent with stdlib practices (e.g. `sync.Map` also uses `interface{}`). If so desired, I could also rewrite this into being generated per-object type. I don't think that it is worth it at this point of time, since it introduces unnecessary complexity, but it is an option.
- Extract the disk usage computation functionality for containers and images for consistency with other object types and better separation of concerns. It also fits nicely with the current design.

**- How to verify it**
E.g.
```
docker system df& docker system df& docker system df
```
Or:
```
curl -s --unix-socket /var/run/docker.sock 'http://localhost/system/df?types=image'& curl -s --unix-socket /var/run/docker.sock 'http://localhost/system/df?types=container'& curl -s --unix-socket /var/run/docker.sock 'http://localhost/system/df?types=volume'& curl -s --unix-socket /var/run/docker.sock 'http://localhost/system/df?types=build-cache'& curl -s --unix-socket /var/run/docker.sock 'http://localhost/system/df?types=image&type=container'
```

Such invocations do not error anymore, but just return the result once computed by one of the goroutines

2021-08-06 17:35 UTC, rvolosatovs commented
CI failure unrelated:
```
[2021-08-06T16:10:53.288Z] === Failed

[2021-08-06T16:10:53.288Z] === FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonCorruptedFluentdAddress (0.51s)

[2021-08-06T16:10:53.288Z]     docker_cli_daemon_test.go:1670: assertion failed: 

[2021-08-06T16:10:53.288Z]         Command:  grep invalid fluentd-address corrupted:c:  /go/src/github.com/docker/docker/bundles/test-integration/TestDockerDaemonSuite/TestDaemonCorruptedFluentdAddress/dfd81d374d7e8/docker.log

[2021-08-06T16:10:53.288Z]         ExitCode: 1

[2021-08-06T16:10:53.288Z]         Error:    exit status 1

[2021-08-06T16:10:53.288Z]         Stdout:   

[2021-08-06T16:10:53.288Z]         Stderr:   

[2021-08-06T16:10:53.288Z]         

[2021-08-06T16:10:53.288Z]         Failures:

[2021-08-06T16:10:53.288Z]         ExitCode was 1 expected 0

[2021-08-06T16:10:53.288Z]         Expected no error

[2021-08-06T16:10:53.288Z]     check_test.go:309: [d84ba0c32a1c1] daemon is not started

[2021-08-06T16:10:53.288Z]     --- FAIL: TestDockerDaemonSuite/TestDaemonCorruptedFluentdAddress (0.51s)

[2021-08-06T16:10:53.288Z] 

[2021-08-06T16:10:53.288Z] === FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonCorruptedLogDriverAddress (0.51s)

[2021-08-06T16:10:53.288Z]     docker_cli_daemon_test.go:1662: assertion failed: 

[2021-08-06T16:10:53.288Z]         Command:  grep syslog-address should be in form proto://address /go/src/github.com/docker/docker/bundles/test-integration/TestDockerDaemonSuite/TestDaemonCorruptedLogDriverAddress/d1663412f911e/docker.log

[2021-08-06T16:10:53.288Z]         ExitCode: 1

[2021-08-06T16:10:53.288Z]         Error:    exit status 1

[2021-08-06T16:10:53.288Z]         Stdout:   

[2021-08-06T16:10:53.288Z]         Stderr:   

[2021-08-06T16:10:53.288Z]         

[2021-08-06T16:10:53.288Z]         Failures:

[2021-08-06T16:10:53.288Z]         ExitCode was 1 expected 0

[2021-08-06T16:10:53.288Z]         Expected no error

[2021-08-06T16:10:53.288Z]     check_test.go:309: [dabd09761c86c] daemon is not started

[2021-08-06T16:10:53.288Z]     --- FAIL: TestDockerDaemonSuite/TestDaemonCorruptedLogDriverAddress (0.51s)

[2021-08-06T16:10:53.288Z] 

[2021-08-06T16:10:53.288Z] === FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonWithWrongkey (1.04s)

[2021-08-06T16:10:53.288Z]     docker_cli_daemon_test.go:1236: Missing KeyID message from daemon logs: time="2021-08-06T15:33:43.140499456Z" level=info msg="Starting up"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.144126321Z" level=debug msg="Listener created for HTTP on unix (/tmp/docker-integration/d2d453a171fd3.sock)"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.147093073Z" level=debug msg="Golang's threads limit set to 54990"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.147514636Z" level=info msg="parsed scheme: \"unix\"" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.147529569Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.147565792Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.147592350Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.147583014Z" level=debug msg="metrics API listening on /tmp/dxr/d2d453a171fd3/metrics.sock"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.160002971Z" level=info msg="parsed scheme: \"unix\"" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.160027631Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.160050939Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.160064903Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.161660630Z" level=debug msg="Using default logging driver json-file"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.161680002Z" level=debug msg="[graphdriver] trying provided driver: overlay2"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.162288378Z" level=debug msg="processing event stream" module=libcontainerd namespace=d2d453a171fd3p

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.178674550Z" level=debug msg="backingFs=extfs, projectQuotaSupported=false, indexOff=\"index=off,\", userxattr=\"\"" storage-driver=overlay2

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.178706452Z" level=debug msg="Initialized graph driver overlay2"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.179070636Z" level=debug msg="No quota support for local volumes in /go/src/github.com/docker/docker/bundles/test-integration/TestDockerDaemonSuite/TestDaemonWithWrongkey/d2d453a171fd3/root/volumes: Filesystem does not support, or has not enabled quotas"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240294604Z" level=warning msg="Your kernel does not support swap memory limit"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240321346Z" level=warning msg="Your kernel does not support CPU realtime scheduler"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240331147Z" level=warning msg="Your kernel does not support cgroup blkio weight"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240341825Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240499285Z" level=debug msg="Max Concurrent Downloads: 3"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240512285Z" level=debug msg="Max Concurrent Uploads: 5"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240521757Z" level=debug msg="Max Download Attempts: 5"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240548248Z" level=info msg="Loading containers: start."

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240616430Z" level=debug msg="Option Experimental: false"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240627615Z" level=debug msg="Option DefaultDriver: bridge"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240636684Z" level=debug msg="Option DefaultNetwork: bridge"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240646848Z" level=debug msg="Network Control Plane MTU: 1500"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.240729717Z" level=debug msg="processing event stream" module=libcontainerd namespace=d2d453a171fd3

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.244992116Z" level=debug msg="Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.251933834Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION]"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.254290852Z" level=debug msg="/usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.256383467Z" level=debug msg="/usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]"

[2021-08-06T16:10:53.288Z]         time="2021-08-06T15:33:43.259408925Z" level=debug msg="/usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtyp [...]

2021-08-06 18:29 UTC, cpuguy83 commented
Seems like we can use the `singleflight` package in x/sync.
https://pkg.go.dev/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight#Group.DoChan

2021-08-09 10:51 UTC, rvolosatovs commented
Thanks, didn't know about existence of this package!
Added a `x/sync/singleflight`-based implementation in https://github.com/moby/moby/pull/42715/commits/57b7519ed7c999f83b139ba401d1c2b4cfb72afe.
I do find the previous approach simpler and easier to read, mostly due to the lack of context handling in singleflight. Also, note that the returned channel is never closed and would leak a goroutine if we did not ensure a read on caller side, which means we have to start a goroutine on `ctx.Done()`.
A possible minor advantage, is that we can reuse the "group" for e.g. improving `prune` UX.
I'm fine with both, with a slight preference to the original due to the above. (note, that for "visibility" of the called function, the function could be passed as argument to `Do`, just like with singleflight, and, in fact, that was done in the first iteration of this package)

Does it maybe make sense to add a wrapper for singleflight, which would add easy-to-use context support? (basically just wrapping the `select` block)

What do you think? @cpuguy83 @thaJeztah

2021-08-09 13:30 UTC, thaJeztah reviewed
> I do find the previous approach simpler and easier to read, mostly due to the lack of context handling in singleflight.

Yeah, the handling is slightly more complex. That said, I do like that we won't have to maintain yet-another-package.

> the returned channel is never closed and would leak a goroutine if we did not ensure a read on caller side, which means we have to start a goroutine on ctx.Done().

That's a bit ugly, yes. @cpuguy83 any other suggestions for that?

> A possible minor advantage, is that we can reuse the "group" for e.g. improving prune UX.

Ah, just left a comment about that. Was your idea to reuse the same groups, or to use the same _approach_ ?

> Does it maybe make sense to add a wrapper for singleflight, which would add easy-to-use context support? (basically just wrapping the select block)

Always a bit cautious with abstracting away things too much. You mean something like;

```go
package singleflight

import (
    "context"

    "golang.org/x/sync/singleflight"
)

func Do(ctx context.Context, sf *singleflight.Group, key string, fn func() (interface{}, error)) (interface{}, error)
	ch := sf.DoChan(key, fn)
	select {
	case <-ctx.Done():
		go func() { <-ch }()
		return nil, ctx.Err()
	case res := <-ch:
		if res.Err != nil {
			return nil, res.Err
		}
		return res.Val, nil
	}
}
```

2021-08-09 13:30 UTC, thaJeztah commented on volume/service/service.go
> +		return s.localVolumesSize(ctx)
same here (consider inlining)

2021-08-09 13:30 UTC, thaJeztah commented on daemon/images/service.go
> +		return i.layerDiskUsage(ctx)
Same here (consider inlining)

2021-08-09 15:49 UTC, rvolosatovs commented on daemon/disk_usage.go
> +		return daemon.containerDiskUsage(ctx)
That is an artifact from previous iteration, inlining makes sense indeed with current approach

2021-08-09 15:49 UTC, rvolosatovs commented on daemon/daemon.go
> +	pruneRunning int32
Yes!

2021-08-09 16:17 UTC, rvolosatovs commented
> Ah, just left a comment about that. Was your idea to reuse the same groups, or to use the same _approach_ ?

Given the library API it seems that the expected usage is to reuse the group. I have hard time understanding why so much functionality would be present for key support otherwise.

Personally, reusing anything here does not *seem* like the right approach, but if that's the "idiomatic" usage, then I suppose we should follow.

> Always a bit cautious with abstracting away things too much. You mean something like;
> (example)

Yes, exactly that, but it doesn't seem like it should deserve it's own package. It's something I would like to put in a `internal/syncutil`, if there was such a package.

2021-08-09 16:17 UTC, cpuguy83 commented
I don't see how we'd leak anything since the channel is buffered.

2021-08-09 16:19 UTC, rvolosatovs commented
> I don't see how we'd leak anything since the channel is buffered.

Yes, you're right, we don't actually need the goroutine

2021-08-09 16:31 UTC, thaJeztah commented
For reviewers; use the `?w=1` option to view the diff; it makes the diff a lot easier to review (due to whitespace changes); https://github.com/moby/moby/pull/42715/files?w=1

2021-08-09 17:46 UTC, cpuguy83 approved these changes
LGTM

2021-08-09 17:55 UTC, thaJeztah requested changes
changes look good, but can you squash/combine the first and last commit?

2021-08-09 18:02 UTC, thaJeztah approved these changes
LGTM, thanks!

2021-08-09 19:42 UTC, thaJeztah commented
Hmm

```

[2021-08-09T18:06:13.240Z] 29d5b6a226d2: Download complete
[2021-08-09T18:07:54.461Z] powershell.exe : failed to register layer: re-exec error: exit status 1: output: hcsshim::ProcessUtilityVMImage 
[2021-08-09T18:07:54.461Z] \\?\D:\docker\windowsfilter\1258f08accef9b7f046ebfe52bddc3814446163e842dca420fe8242533da0e06\UtilityVM: To use this container image, you must join the Windows Insider Program. Please see 
[2021-08-09T18:07:54.461Z] https://go.microsoft.com/fwlink/?linkid=850659 for more information.
```

@StefanScherer could this be because the machines were updated?

2021-08-10 08:49 UTC, thaJeztah commented
merged https://github.com/moby/moby/pull/42527. Let me trigger CI again to see if it picks up that change

2021-08-10 11:50 UTC, thaJeztah commented
Yup! All green again now

2021-08-10 11:51 UTC, merged