API: discard `/system/df` `type` parameter pre-1.42
moby/moby pull request #42716
Opened 2021-08-06 15:39 UTC by rvolosatovs

Fixup #42559 

Please provide the following information:
-->

**- What I did**
Ensure the `type` parameter to `/system/df` is discarded for API versions lower than 1.42

**- How I did it**
Check for the version in the endpoint

2021-08-06 15:39 UTC, rvolosatovs commented
@thaJeztah PTAL

2021-08-06 15:41 UTC, thaJeztah approved these changes
LGTM, thanks!

2021-08-06 15:57 UTC, cpuguy83 requested changes

2021-08-06 15:57 UTC, cpuguy83 commented on api/server/router/system/system_routes.go
> +	if typeStrs, ok := r.Form["type"]; !ok || versions.LessThan(version, "1.42") {
This is hard to read (for me).
Can you split this `if` to multiple lines? I think that will help.

So...

```go
types, ok := r.Form["type"]
if versions.LesstThan(version, "1.42") || !ok {
 //
} else {
 //
}
```

2021-08-06 18:21 UTC, cpuguy83 approved these changes
LGTM

2021-08-07 13:45 UTC, thaJeztah commented
Failure on Windows RS5 is unrelated, and known flaky; related https://github.com/moby/moby/issues/42646, https://github.com/moby/moby/pull/42625

```
=== RUN   TestNetworkDBCRUDTableEntries
    networkdb_test.go:314: Entry existence verification test failed for node2(fc4d5ae18199)
2021/08/06 21:26:25 Closing DB instances...
--- FAIL: TestNetworkDBCRUDTableEntries (7.63s)
```

2021-08-07 13:46 UTC, merged