Fix file capabilites droping in Dockerfile
moby/moby pull request #42934
Opened 2021-10-13 15:41 UTC by abdulrahimiliasu

fixes #42655 

**- What I did**
moved copyXattr function out of doCopyXattrs function, so that security capabilities are copied
**- How I did it**
doCopyXattrs() never reached due to copyXattrs boolean being false, as a result file capabilities not being copied.

**- How to verify it**

***Test Case***

```dockerfile
FROM registry1-docker-io.repo.lab.pl.alcatel-lucent.com/library/alpine:latest
RUN apk --no-cache add libcap && setcap cap_net_admin=eip /sbin/apk
RUN setcap -v cap_net_admin=eip /sbin/apk
```

***Test Result***
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM registry1-docker-io.repo.lab.pl.alcatel-lucent.com/library/alpine:latest
latest: Pulling from library/alpine
a0d0a0d46f8b: Pull complete
Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
Status: Downloaded newer image for registry1-docker-io.repo.lab.pl.alcatel-lucent.com/library/alpine:latest
 ---> 14119a10abf4
Step 2/3 : RUN apk --no-cache add libcap && setcap cap_net_admin=eip /sbin/apk
 ---> Running in 923b46395907
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/1) Installing libcap (2.50-r0)
Executing busybox-1.33.1-r3.trigger
OK: 6 MiB in 15 packages
Removing intermediate container 923b46395907
 ---> 97d6ec51d4b3
Step 3/3 : RUN setcap -v cap_net_admin=eip /sbin/apk
 ---> Running in 33260d42c77d
/sbin/apk: OK
Removing intermediate container 33260d42c77d
 ---> 5fc3c8660150
Successfully built 5fc3c8660150
Successfully tagged test:cap
```

**- Description for the changelog**
Fixed issue of file capabilities dropping when moving to next command in Dockerfile  during image building.

2021-10-14 13:08 UTC, abdulrahimiliasu commented
That's correct the Boolean should be set to ```true```  for those capabilities to be copied, but this change only makes sure that the 
"security-capability" attribute are copied. Everything else stay the same. But I do not know the specific reason for ```copyXattrs``` default to ```false```.

2021-11-06 09:34 UTC, szubersk commented
@thaJeztah I can't speak for @sargun but the feeling I get is that copying xattrs has been removed to speed copying up. d2b71b2 `Have VFS graphdriver use accelerated in-kernel copy` introduces two major optimizations: copy_file_range usage to transfer file content without switching from kernel- to userspace and back and xattrs ignoring.

`copy_file_range` can't take care of file attributes (or any other metadata) as it operates only on file content.
```
ssize_t copy_file_range(int fd_in, off64_t *off_in,
                        int fd_out, off64_t *off_out,
                        size_t len, unsigned int flags);
```

`copyXattr` requires one `getxattr(2)` call per file/directory + memory allocation (sometimes two) to store the result. No wonder @sargun was looking for an optimization there.
https://github.com/moby/moby/blob/c09789c1140a3b2e399b0c77c449b34d000e2362/daemon/graphdriver/copy/copy.go#L90-L91
https://github.com/moby/moby/blob/c09789c1140a3b2e399b0c77c449b34d000e2362/pkg/system/xattrs_linux.go#L8-L11

I'd lean towards suggestion of unconditionally enabling xattrs copying as current implementation is simply incorrect.

2021-11-10 13:25 UTC, abdulrahimiliasu commented
I've updated the commit  by changing copyXattrs to ```true``` instead of moving the block  https://github.com/abdulrahimiliasu/moby/blob/97ec8da56369452620dd1ad8ad51bfa2ccc622f1/daemon/graphdriver/copy/copy.go#L263-L265
out of
https://github.com/abdulrahimiliasu/moby/blob/97ec8da56369452620dd1ad8ad51bfa2ccc622f1/daemon/graphdriver/copy/copy.go#L258

2021-11-10 20:26 UTC, szubersk requested changes

2021-11-10 20:26 UTC, szubersk commented on daemon/graphdriver/copy/copy.go
>  		if err := os.Lchown(dstPath, int(stat.Uid), int(stat.Gid)); err != nil {
Changes in this file are irrelevant to the issue. Please consider removing.

2021-11-10 20:41 UTC, sargun commented
You should only copy the security.capability xattr in the VFS graphdriver, and not the trusted.overlay.opaque one.

2021-11-16 08:02 UTC, szubersk approved these changes

2021-11-16 08:08 UTC, szubersk commented
@sargun @thaJeztah Is the PR in current form ok with you?

2022-01-04 13:03 UTC, szubersk commented
@sargun @thaJeztah
Is there an issue that prevent merging this PR?

2022-07-19 23:19 UTC, rightblank commented
Hi, @thaJeztah, could you please help to look at if this could be merged? Thanks?

2022-07-20 00:44 UTC, mikebrow reviewed
nit.. comments for the modified DirCopy() func and field name copyXattrs should be modified to reflect the boolean is just for switching off copying xattr trusted.overlay.opaque

2022-07-20 19:16 UTC, mikebrow approved these changes
LGTM functionally.. just the nit comment regarding variable naming and existing api // comments

2022-07-27 15:22 UTC, thaJeztah commented
I rebased the PR, renamed the `copyXattrs` argument to `copyOpaqueXattrs`, and updated the GoDoc for `CopyDir()`

2022-07-27 15:23 UTC, thaJeztah approved these changes
LGTM, thanks! And sorry for the long delay; this one dropped of my radar, and I saw the PR was still marked with "missing DCO", but that looks to have been resolved since.

2022-07-27 16:00 UTC, mikebrow approved these changes
LGTM

2022-07-27 21:31 UTC, cpuguy83 approved these changes

2022-07-27 21:31 UTC, merged