daemon: fix daemon.Shutdown, daemon.Cleanup not cleaning up overlay2 mounts
moby/moby pull request #43659
Opened 2022-05-29 14:31 UTC by thaJeztah

While working on deprecation of the `aufs` and `overlay` storage-drivers (https://github.com/moby/moby/pull/43637), the `TestCleanupMounts` had to be updated, as it was currently using `aufs` for testing. When rewriting the test to use `overlay2` instead (using an updated `mountsFixture`), I found out that the test was failing, and it appears that only `overlay`, but not `overlay2` was taken into account.

These cleanup functions were added in 05cc737f5411a0effd299429140d031c4ad8dd05 (https://github.com/moby/moby/pull/21637), but at the time the `overlay2` storage driver was not yet implemented;
https://github.com/moby/moby/tree/05cc737f5411a0effd299429140d031c4ad8dd05/daemon/graphdriver

This omission was likely missed in 23e5c94cfb26eb72c097892712d3dbaa93ee9bc0 (https://github.com/moby/moby/pull/22126), because the original implementation re-used the `overlay` storage driver, but later on it was decided to make `overlay2` a separate storage driver.

As a result of the above, `daemon.cleanupMountsByID()` would ignore any `overlay2` mounts during `daemon.Shutdown()` and `daemon.Cleanup()`.

This patch:

- Adds a new `mountsFixtureOverlay2` with example mounts for `overlay2`
- Rewrites the tests to use `gotest.tools` for more informative output on failures.
- Adds the missing regex patterns to `daemon/getCleanPatterns()`. The patterns are added at the start of the list to allow for the fasted match (`overlay2` is the default for most setups, and the code is iterating over possible options).

As a follow-up, we could consider adding additional fixtures for different storage drivers.

Before the fix is applied:

    go test -v -run TestCleanupMounts ./daemon/
    === RUN   TestCleanupMounts
    === RUN   TestCleanupMounts/aufs
    === RUN   TestCleanupMounts/overlay2
    daemon_linux_test.go:135: assertion failed: 0 (unmounted int) != 1 (int): Expected to unmount the shm (and the shm only)
    --- FAIL: TestCleanupMounts (0.01s)
    --- PASS: TestCleanupMounts/aufs (0.00s)
    --- FAIL: TestCleanupMounts/overlay2 (0.01s)
    === RUN   TestCleanupMountsByID
    === RUN   TestCleanupMountsByID/aufs
    === RUN   TestCleanupMountsByID/overlay2
    daemon_linux_test.go:171: assertion failed: 0 (unmounted int) != 1 (int): Expected to unmount the root (and that only)
    --- FAIL: TestCleanupMountsByID (0.00s)
    --- PASS: TestCleanupMountsByID/aufs (0.00s)
    --- FAIL: TestCleanupMountsByID/overlay2 (0.00s)
    FAIL
    FAIL	github.com/docker/docker/daemon	0.054s
    FAIL

With the fix applied:

    go test -v -run TestCleanupMounts ./daemon/
    === RUN   TestCleanupMounts
    === RUN   TestCleanupMounts/aufs
    === RUN   TestCleanupMounts/overlay2
    --- PASS: TestCleanupMounts (0.00s)
    --- PASS: TestCleanupMounts/aufs (0.00s)
    --- PASS: TestCleanupMounts/overlay2 (0.00s)
    === RUN   TestCleanupMountsByID
    === RUN   TestCleanupMountsByID/aufs
    === RUN   TestCleanupMountsByID/overlay2
    --- PASS: TestCleanupMountsByID (0.00s)
    --- PASS: TestCleanupMountsByID/aufs (0.00s)
    --- PASS: TestCleanupMountsByID/overlay2 (0.00s)
    PASS
    ok  	github.com/docker/docker/daemon	0.042s

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2022-05-29 15:17 UTC, neersighted approved these changes

2022-05-29 15:24 UTC, neersighted requested changes
I'm not 100% married to the idea, but I feel it would make the coupling/dependency here more obvious/easier to reason about if the pattern was instead a const string on the driver package, which gets imported and then put through `fmt.Sprintf()`.

It could make this kind of omission far less likely in the future -- on the other hand the graphdriver code is slated to go away Soon:tm:...

2022-05-29 15:28 UTC, thaJeztah commented
I agree; it would be better if the storage driver provided these matches/strings.

For this PR, I'd like to keep the change "minimal" (also to allow backporting if we want to), and we can address improvements as a follow-up.

2022-05-29 16:14 UTC, neersighted approved these changes

2022-05-30 00:01 UTC, samuelkarp approved these changes

2022-05-30 07:43 UTC, rumpl approved these changes

2022-05-30 09:53 UTC, thaJeztah commented
Thanks all for reviewing! I'll bring this one in.

@tonistiigi I tagged you for review as well (as you did the original implementation of this code); I'm merging this one, but let me know if there's follow-ups needed after this

2022-05-30 09:53 UTC, merged

2022-05-30 10:37 UTC, thaJeztah commented on daemon/daemon_linux.go
> +		patterns = append(patterns, "containers/"+id+"/mounts/shm", "containers/"+id+"/shm")
So; this change fixes that, but may mean that the `mountsFixture` used for the `aufs` case is wrong.