api: set default "Builder-Version" to "2" (BuildKit) on Linux
moby/moby pull request #43657
Opened 2022-05-29 12:02 UTC by thaJeztah

Starting with the 22.06 release, buildx is the default client for
docker build, which uses BuildKit as builder.

This patch changes the default builder version as advertised by
the daemon to "2" (BuildKit), so that pre-22.06 CLIs with BuildKit
support (but no buildx installed) also default to using BuildKit
when interacting with a 22.06 (or up) daemon.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2022-05-29 12:06 UTC, albertoEnstein requested changes
W

2022-05-29 12:14 UTC, albertoEnstein approved these changes

2022-05-29 12:32 UTC, thaJeztah commented
Hmmm... github actions having issues, or is it a networking issue inside the Dockerfile?

```
WARNING: MSG:UnableToDownload 
«https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
WARNING: Unable to download the list of available providers. Check your 
internet connection.
Install-Package : No match was found for the specified search criteria and 
package name '7Zip4PowerShell'. Try Get-PackageSource to see all available 
registered package sources.
At line:1 char:3109
+ ... ownloading containerd; Install-Package -Force 7Zip4PowerShell; $locat ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPacka 
   ge:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.Pac 
   kageManagement.Cmdlets.InstallPackage
```

2022-05-29 14:38 UTC, thaJeztah commented
Ah, yes, needed to skip Windows for this (can't start daemons as part of the test)

```
=== Failed
=== FAIL: github.com/docker/docker/integration/system TestPingBuilderHeader (0.02s)
    ping_test.go:105: assertion failed: error is not nil: protocol not available: [d9042f2f0b1bb] could not create daemon client
```

2022-07-16 14:03 UTC, AkihiroSuda commented
What's current status?

2022-07-21 15:18 UTC, thaJeztah commented
oh! I opened this as draft for discussion; wondering if it was safe to do this, or if it needed a wider discussion

/cc @tonistiigi @crazy-max

2022-08-18 18:14 UTC, corhere approved these changes

2022-08-18 18:14 UTC, thaJeztah commented
discussed in the maintainers meeting, and we decided to go ahead with this one

2022-08-18 18:14 UTC, merged