Revert: Added API to set ephemeral port allocator range
moby/moby pull request #44476
Opened 2022-11-16 14:56 UTC by sbuckfelder

Signed-off-by: Scott Buckfelder <buckscot@amazon.com>

Issue : [#44423](https://github.com/moby/moby/issues/44423)

Merges in commit https://github.com/moby/libnetwork/pull/2668 which is a backport of functionality.

**Note For Reviewers** :  I also updated the _hack/dockerfile/install/proxy.installer_ file to now reference moby/libnetwork as opposed to docker/libnetwork.  I'm not terribly confident this was the correct thing to do.

2022-11-16 16:13 UTC, neersighted requested changes
Updating repository references is fine, but the import path is still docker/libnetwork and cannot change.

Everything but the `git clone` needs to revert to the old name.

2022-11-16 16:15 UTC, neersighted commented
Also, could you please rephrase your commit message to conform to the repo convention for vendoring? e.g. https://github.com/moby/moby/commit/25707841695d3bcfae8691e63152ecf4fec5a0fa

2022-11-17 12:19 UTC, sbuckfelder commented
> Also, could you please rephrase your commit message to conform to the repo convention for vendoring? e.g. [2570784](https://github.com/moby/moby/commit/25707841695d3bcfae8691e63152ecf4fec5a0fa)

Updated in new rev

2022-11-17 12:20 UTC, sbuckfelder commented
> Updating repository references is fine, but the import path is still docker/libnetwork and cannot change.
> 
> Everything but the `git clone` needs to revert to the old name.

I believe I was able to follow this advice in the new rev, please let me know if not.

2022-11-17 15:29 UTC, neersighted approved these changes

2022-11-17 15:31 UTC, neersighted commented
This looks good from a changes made standpoint, but fails the vendoring checks. Did you vendor by hand instead of using vndr?

> The result of vndr differs

You should run `hack/vendor.sh` **every** time you touch vendoring; fix that and this should be good to go.

2022-11-23 19:28 UTC, thaJeztah commented
I amended the commit and ran vendor

2022-11-23 19:28 UTC, thaJeztah approved these changes
LGTM (assuming CI is happy)

2022-12-08 18:51 UTC, merged