api: can marshal and unmarshal when args.fields is empty
moby/moby pull request #44668
Opened 2022-12-18 06:27 UTC by masibw

fixes: #44269 

**- What I did**
Can marshal and unmarshal when args.fields is empty.
**- How I did it**
When marshal, use `make(map[string]map[string]bool, 0)` instead of  return `byte[]{}`.
When unmarshal, remove the case of `len(raw) == 0`
**- How to verify it**
I wrote tests.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2022-12-22 21:23 UTC, corhere requested changes
Thank you for contributing! I am fairly confident this change is safe, i.e. won't break compatibility with existing daemons or clients. The "empty string -> empty filter" logic is retained in the `filters.ToJSON` and `filters.FromJSON` functions, which are used in the API client and server, respectively, to handle un/marshaling a filter in a URL query value. The tests need a little attention, however.

2022-12-26 08:47 UTC, masibw commented on api/types/filters/parse.go
> +		args.fields = make(map[string]map[string]bool, 0)
Thank you, change to `[]byte("{}")`

2022-12-26 08:48 UTC, masibw commented on api/types/filters/parse_test.go
> +}
Thank you. Originally I wanted to make sure that I could unmarshal what I marshal, but I changed it because I thought you were right!

2022-12-28 18:34 UTC, corhere approved these changes
@thaJeztah @neersighted PTAL

2022-12-28 21:00 UTC, neersighted approved these changes

2022-12-28 21:01 UTC, neersighted commented
CI failures appear to be routine flakes; I've kicked the jobs again.

2022-12-29 19:12 UTC, corhere commented
The two CI runs which ran to completion had the same two test failures:
 - `TestIntegration/TestMultiStageImplicitFrom/worker=dockerd/frontend=client`
 - `TestIntegration/TestMultiStageImplicitFrom/worker=dockerd/frontend=builtin`

It is possible that this change really is breaking buildkit. I've kicked off another CI run to rule out flakiness as the cause.

2022-12-29 19:46 UTC, neersighted commented
Looks like the last run had the same failure; they appear to be legitimate:

```
     --- FAIL: TestIntegration/TestMultiStageImplicitFrom/worker=dockerd/frontend=client (1.68s)
    --- FAIL: TestIntegration/TestMultiStageImplicitFrom/worker=dockerd/frontend=builtin (1.52s)
```

2022-12-29 19:49 UTC, neersighted commented
I've rebased this onto master as the failures do not reproduce there, hopefully this solves the test failures.

2022-12-29 22:39 UTC, merged