reference: assorted fixes and cleanups
moby/moby pull request #44732
Opened 2023-01-02 12:33 UTC by thaJeztah

Looks like another branch that I didn't push 😂 

### reference: rename variables that collided with type / import

These variables collided with the "repository" and "store" types declared
in this package. Rename the variables colliding with "repository", and
rename the "store" type to "refStore".

### reference: use t.TempDir() for tests

### reference: don't string-match errors in tests, and fix error format

### reference: add test-coverage for digested references

Trying to overwrite a digest with another digest is not allowed, and
cannot be forced.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-01-31 21:34 UTC, neersighted requested changes
LGTM with one minor change: in the tests, we never use `tmpDir` past generating the JSON file path. I think we should just inline the call instead (especially as reusing the `tmpDir` could result in surprising behavior the file has a fixed name).

2023-02-01 17:40 UTC, thaJeztah commented
> with one minor change: in the tests, we never use tmpDir past generating the JSON file path. I think we should just inline the call instead (especially as reusing the tmpDir could result in surprising behavior the file has a fixed name).

Yeah, I was on the fence on those. Whether inlining (`foo := bar(t.TempDir), bla, black)`) would be "too implicit" (easy to miss a tempdir is created) or if it would be more transparent to use a `tmpDir` variable. I agree that for some of these, reusing the tempDir without changing the filename would now work. 

I'll update those that were previously using `os.CreateTemp()` (temp file)

2023-02-01 17:46 UTC, thaJeztah commented
Actually, the remaining one also used a fixed filename, so inlined that one as well 👍 updated PTAL

2023-02-01 19:27 UTC, neersighted approved these changes

2023-03-06 18:20 UTC, neersighted commented
Kicked CI; needs one more LGTM.

2023-03-06 18:37 UTC, thaJeztah commented
Thanks! Yes, did a quick rebase to get a fresh run of CI

@vvoland ptal

2023-03-09 09:55 UTC, vvoland approved these changes

2023-03-09 11:43 UTC, merged