libnetwork: Always use an IPv4 to (re)create default bridge
moby/moby pull request #44806
Opened 2023-01-12 11:06 UTC by akerouanton

When (re)creating the default bridge, libnetwork tries to find the first available network from the default local pool by calling `netutils.FindAvailableNetwork()`. It assumes there's only IPv4 in default-address-pools, and thus end up trying to assign an IPv6 before it's enabled on the bridge (eg. disable_ipv6 sysctl == 1). In such case, the daemon will fail to start and the following message will be logged:

> failed to start daemon: Error initializing network controller: Error creating default "bridge" network: failed to add IPv4 address fc00:1337:1337::1/8

To prevent such mix up `FindAvailableNetwork()` now takes an ipVer parameter and checks if subnets it iterates over are matching ipVer param.

This issue is already fixed by the refactoring done in #43033. But unlike #43033 this PR should be backported to v20.10/v23.0 imho.

Fixes #44220.

**- How to verify it**

Using the following `daemon.json` dockerd should not fail to start:

```json
{
  "default-address-pools": [
    {
      "base": "fc00:1337:1337::0/64",
      "size": 80
    },
    {
      "base": "172.16.0.0/12",
      "size": 24
    }
  ]
}
```

2023-01-12 13:08 UTC, vvoland approved these changes

2023-01-12 14:30 UTC, thaJeztah commented on libnetwork/ipamutils/utils.go
> +)
Wondering if we need to look at these; there's a bunch of ipVersion types now (which is already confusing), and it looks like we're not very consistent either;

```bash
git grep -i ' ipversion'
cmd/docker-proxy/proxy.go:// ipVersion refers to IP version - v4 or v6
cmd/docker-proxy/proxy.go:type ipVersion string
cmd/docker-proxy/proxy.go:      ipv4 ipVersion = "4"
cmd/docker-proxy/proxy.go:      ipv6 ipVersion = "6"
libnetwork/drivers/bridge/bridge_test.go:       for _, version := range ipVersions {
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:type ipVersion int
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:  ipvnone ipVersion = iota
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:func getIPVersion(config *networkConfiguration) ipVersion {
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:  return ipVersion
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:  doEnable := func(ipVer ipVersion) error {
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:func getForwardingKernelParam(ipVer ipVersion, iface string) string {
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:func getBridgeNFKernelParam(ipVer ipVersion) string {
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:func isPacketForwardingEnabled(ipVer ipVersion, iface string) (bool, error) {
libnetwork/drivers/bridge/setup_ip_tables.go:           if ipVersion == iptables.IPv4 {
libnetwork/ipam/allocator.go:   var v ipVersion
libnetwork/ipam/utils.go:type ipVersion int
libnetwork/ipam/utils.go:func getAddressVersion(ip net.IP) ipVersion {
libnetwork/iptables/iptables.go:// IPVersion refers to IP version, v4 or v6
libnetwork/iptables/iptables.go:type IPVersion string
libnetwork/iptables/iptables.go:        IPv4 IPVersion = "IPV4"
libnetwork/iptables/iptables.go:        IPv6 IPVersion = "IPV6"
libnetwork/iptables/iptables.go:// IPTable defines struct with IPVersion
libnetwork/iptables/iptables.go:        Version IPVersion
libnetwork/iptables/iptables.go:func GetIptable(version IPVersion) *IPTable {
libnetwork/portmapper/proxy.go:// ipVersion refers to IP version - v4 or v6
libnetwork/portmapper/proxy.go:type ipVersion string
libnetwork/portmapper/proxy.go: ipv4 ipVersion = "4"
libnetwork/portmapper/proxy.go: ipv6 ipVersion = "6"
libnetwork/portmapper/proxy.go: ipVersion ipVersion
libnetwork/portmapper/proxy.go:         return &dummyProxy{addr: addr, ipVersion: version}, nil
libnetwork/portmapper/proxy.go:         return &dummyProxy{addr: addr, ipVersion: version}, nil
libnetwork/portmapper/proxy.go:         return &dummyProxy{addr: addr, ipVersion: version}, nil
```

- some are strings
- difference in _what_ string they are ("4" / "6" / "IPV4" / "IPV6")
- some are ints

FWIW: not sure if we're able to unify them _all_, and what the best location is for a (possibly) exported and canonical one, but my main concern is to introduce a new _exported_ type (once exported it's basically a published API, which complicates moving/changing after that).

2023-01-12 20:05 UTC, thaJeztah commented on libnetwork/netutils/utils_linux.go
> +func FindAvailableNetwork(ipVer ipamutils.IPVersion, list []*net.IPNet) (*net.IPNet, error) {
Alternative, we could have a filter function that can be passed (in this case filter on IP class)

2023-03-02 17:58 UTC, corhere requested changes

2023-03-02 17:58 UTC, corhere commented on libnetwork/network.go
> +		}); err == nil {
This call to `netutils.FindAvailableNetwork` is being passed a list of length 1. It's used to check whether the pool—singular—returned from `ipam.RequestPool` would conflict with routes in use on the host. The call to `ipam.RequestPool` specifies the address family (IPv4 vs. IPv6), so the question is: why do we have to double-check that `ipam.RequestPool` respected the request? Seems like we should be fixing the root cause, the bug in the IPAM allocator which allocates IPv6 pools when an IPv4 pool is requested.

2023-03-31 07:34 UTC, akerouanton commented
PR https://github.com/moby/moby/pull/44827 fixes the issue reported in https://github.com/moby/moby/issues/44220. Closing.

2023-03-31 07:34 UTC, closed without merging