fix: the logic of the protocol in loadListeners
moby/moby pull request #44823
Opened 2023-01-14 17:17 UTC by tao12345666333

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

**- What I did**

Here introduced a judgment in  https://github.com/moby/moby/commit/5008409b5cebe36690f653b71f171cf4e1ce114c

This will result in the following error.

```
➜  moby sudo /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock                                                                                                                       
INFO[2023-01-15T00:56:52.640211255+08:00] Starting up                                  
WARN[2023-01-15T00:56:52.640525792+08:00] Running experimental build                          
failed to load listeners: bad format fd://, expected PROTO://ADDR
```

The configuration `fd://` is the default configuration for docker.service.
we shouldn't break it
https://github.com/moby/moby/blob/master/contrib/init/systemd/docker.service#LL13C31-L13C36

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-01-14 22:00 UTC, neersighted commented
Hmm, good catch, though I'm not convinced this is the right place to carve out this special case. This also definitely requires a regression test to prevent the same mistake again.

2023-01-14 22:00 UTC, neersighted requested changes
Hmm, good catch, though I'm not convinced this is the right place to carve out this special case. This also definitely requires a regression test to prevent the same mistake again.

2023-01-14 22:06 UTC, neersighted commented
Actually, something fishy is going on:

https://github.com/moby/moby/blob/d62a88eb0d0358d593c0d8c43216f78d5104184c/opts/hosts_test.go#L30-L31

We have a test case explicitly for this -- so we need to investigate why that is failing. There are also other protocols we should accept with no 'address' portion: are those currently failing? If so, the broken tests are doubly concerning:

https://github.com/moby/moby/blob/d62a88eb0d0358d593c0d8c43216f78d5104184c/opts/hosts_test.go#L33
https://github.com/moby/moby/blob/d62a88eb0d0358d593c0d8c43216f78d5104184c/opts/hosts_test.go#L44
https://github.com/moby/moby/blob/d62a88eb0d0358d593c0d8c43216f78d5104184c/opts/hosts_test.go#L46

2023-01-14 23:50 UTC, tao12345666333 commented
Thanks! Even though we have this test case, it doesn't use the `parseHost` or `parseDaemonHost` functions at this point in my modification.

In the previous code, it is not judged whether `addr` is empty.
https://github.com/moby/moby/commit/5008409b5cebe36690f653b71f171cf4e1ce114c#diff-eab6997069d2fc9fd3e50c0721e88a363570b9d3ed03facd987373ab1ac9405bL665-L666


I think I should change the function called to `parseDaemonHost` to clean up a bit here, what do you think?

2023-01-14 23:50 UTC, thaJeztah commented
Could it be the subtests here not capturing the variable? https://github.com/moby/moby/blob/d62a88eb0d0358d593c0d8c43216f78d5104184c/opts/hosts_test.go#L50-L51

2023-01-14 23:54 UTC, tao12345666333 commented
no, `fd://` is a valid configuration.

2023-01-15 00:08 UTC, thaJeztah commented
I'm personally fine with the check added in this PR (this was indeed an oversight of mine), or perhaps remove the check altogether (if we already validate these before this).

That said, we should refactor some of this (I recall I looked at this code as well, when working on https://github.com/moby/moby/pull/43459); I think there's too much  handling happening in `loadListeners()`; it would be better if we did all the parsing and handling before we reach that code, to allow validating the configuration _before_ we even try to start the daemon, and so that `dockerd --validate` already returns configuration errors (if we don't validate this specific case already); https://github.com/moby/moby/blob/803c21f4b20de6533d61a60cb9c359159e3e6a7a/cmd/dockerd/daemon.go#L83-L92

2023-01-15 00:09 UTC, thaJeztah commented
> no, `fd://` is a valid configuration.

Ah, yea, you're right; was wondering for a bit if the test was broken.

2023-01-15 00:11 UTC, thaJeztah commented
Looks like `fd://something` should _not_ be valid though; so some validation is missing in that part; https://github.com/moby/moby/blob/803c21f4b20de6533d61a60cb9c359159e3e6a7a/daemon/listeners/listeners_linux.go#L82-L90

2023-01-15 00:21 UTC, thaJeztah commented
Removed the cherry-pick label because it looks like https://github.com/moby/moby/commit/5008409b5cebe36690f653b71f171cf4e1ce114c (https://github.com/moby/moby/pull/44381) is only in master

2023-01-15 00:29 UTC, tao12345666333 commented
Then I plan to do this:

* Modify the current PR, and remove the check on `addr`. Since the previous code didn't have this check either, here's a quick fix
* Create a new PR to refactor this:
   * Replace the processing logic here with `parseDaemonHost`
   * `fd://something` is an invalid configuration, modify the related test case

WDYT?

2023-01-15 02:02 UTC, neersighted commented
I'd split the difference: use this PR, but change the implementation to the second, and add e2e testing of this area of code (not just `parseDaemonHost`).

2023-01-15 02:37 UTC, tao12345666333 commented
OK, let me add some e2e test cases, thanks

2023-01-18 12:42 UTC, thaJeztah commented
> and add e2e testing of this area of code (not just parseDaemonHost).

Agreed; There's also quite a bit more to look at w.r.t. validation in general. Some quick thoughts on some of that;

- Make sure we're more consistent in where validation (needs to) happen
- Important there is that not _all_ validation has to be a _full_ validation (for better words). What I mean is that validating "format" and "valid input" is sometimes a separate concern; e.g. `https://hello.world/blabla/blablabla` is validly _formatted_ URL, but the URL may not _exist_. Same as `unix:///no/such/socket` being a valid formatted "unix" socket path, but may not exist.
- This distinction is sometimes important. For example, it's OK to validate for a valid formatted input in some areas (e.g. could be the `docker` CLI), but in some areas you don't want to (or are not _able to_) validate everything.
- Not validating _everything_ is fine as long as we catch errors (and ideally "as early as possible")/
- Some things will always remain a bit of a "grey" area (e.g. socket paths [may be "too long"](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars), but the allowed length _may_ depend on how the host is configured. For such cases we must decide (probably on a per-case basis) wether _we_ (`dockerd`) should validate, or if that's something to delegate to the system itself.

2023-01-20 17:23 UTC, tao12345666333 commented
Thanks for your reply, I will do some thinking.

I'll be back from vacation in two days.

2023-03-10 00:48 UTC, closed without merging

2023-03-10 00:48 UTC, neersighted commented
Thanks for working on this! @cpuguy83 ended up picking it up in #45132, and addressed the testing concern there.