libnetwork: clean up vestigial datastore-related code
moby/moby pull request #44875
Opened 2023-01-26 22:55 UTC by corhere

**- What I did**
I cleaned up code related to datastores and their configuration across libnetwork, pruning dead code and refactoring what remained. Highlights:
  - Refactored package `drvregistry` to no longer be an ad-hoc Dependency Injection container for network and IPAM drivers, and created separate types for network driver registries and IPAM driver registries
    - The `PluginGetter` dependency is now injected directly into the remote drivers
    - Removed the vestiges of datastore dependency injection
  - Removed `DatastoreConfig` from `discoverapi` as dynamic datastore discovery is unreachable
  - Threw out much of the dead persistence code from package `ipam`

**- How I did it**
Prove that code is unreachable. Delete the dead code. Repeat.

**- How to verify it**
CI.

**- Description for the changelog**
N/A

**- A picture of a cute animal (not mandatory but encouraged)**

![Cat.](https://user-images.githubusercontent.com/274527/214968924-169b4eb9-53a8-4a27-b364-883e1f9168e5.jpg)

2023-01-26 23:38 UTC, cpuguy83 approved these changes

2023-01-26 23:38 UTC, cpuguy83 commented on libnetwork/driverapi/driverapi.go
> +	Registerer
lol, this type reminds of https://www.youtube.com/watch?v=6kZBJs527-k
"The Rural Juror"

2023-01-27 00:15 UTC, tianon commented on libnetwork/ipams/remote/remote.go
> +
:eyes:

2023-01-27 00:19 UTC, neersighted requested changes
I noticed one missing comma :laughing:

Otherwise, everything seems well-explained, rational, and well-divided into commits. Awesome work, and it's nice to see that (dead) persistence code just fall away.

2023-01-27 00:19 UTC, neersighted commented on libnetwork/drvregistry/ipams.go
> +// registry ready to use.
```suggestion
// registry, ready to use.
```

2023-01-27 00:24 UTC, tianon approved these changes
"Registerer" is a little bit awkward and there are a few trailing newlines at EOfunc, but nothing that I'd personally block this for :sweat_smile:

2023-01-27 00:24 UTC, tianon commented on libnetwork/drvregistry/networks_test.go
> +
:eyes:

2023-01-27 00:24 UTC, tianon commented on libnetwork/drivers/ipvlan/ivmanager/ivmanager.go
> +
:eyes:

2023-01-27 16:09 UTC, vvoland approved these changes

2023-01-27 17:20 UTC, corhere commented
> "Registerer" is a little bit awkward

Nobody's going to confuse that for a concrete type! [Also:](https://pkg.go.dev/github.com/prometheus/client_golang@v1.14.0/prometheus#Registerer)

2023-01-27 17:23 UTC, neersighted approved these changes

2023-01-27 18:26 UTC, merged