layer: NewStoreFromOptions(): include driver-name in error message
moby/moby pull request #44894
Opened 2023-02-01 09:44 UTC by thaJeztah

- relates to https://github.com/moby/moby/issues/15651#issuecomment-1410780071

When reading through some bug reports, I noticed that the error-message for unsupported storage drivers is not very informative, as it does not include the actual storage driver. Some of these errors are used as sentinel errors internally, so improving the error returned by graphdriver.New() may need some additional work, but this patch makes a start by including the name of the graphdriver (if set) in the error-message.

Before this patch:

    dockerd --storage-driver=foobar
    ...
    failed to start daemon: error initializing graphdriver: driver not supported

With this patch:

    dockerd --storage-driver=foobar
    ...
    failed to start daemon: error initializing graphdriver: foobar: driver not supported

It's worth noting that there may be code "in the wild" that perform string- matching on this error (e.g. [balena][1]), which is why I included the name as a separate "component" in the output, to allow matching parts of the error. An alternative _could_ be to put the name of the driver at the end of the error message, but this would still fail if a straight string-match is performed.

[1]: https://github.com/balena-io-modules/balena-preload/blob/3d5c77a4668b688dd21e9d7aec7c333943680adb/lib/preload.ts#L34-L35

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-02-01 10:23 UTC, vvoland reviewed
> An alternative could be to put the name of the driver at the end of the error message, but this would still fail if a straight string-match is performed.

True, but this change breaks **both** straight and substring match.

IMO putting it at the end is better.
It won't break any existing `strings.Contains(err, "error initializing graphdriver: driver not supported")`, because the previous substring would still be there.

And it still makes sense when you read the error:
      failed to start daemon <- why?
      because there was an error initializing graph driver <- what error?
      driver not supported <- which driver?
      foobar

2023-02-02 10:16 UTC, thaJeztah commented
> IMO putting it at the end is better.

Yeah, perhaps I should put it there. I was on the fence as the driver _could_ be returning other kind of errors, and I wasn't sure if for other errors the driver name would get "lost" in a potential other error.

I guess with the current way the errors are handled, there's not too many options to choose from (so we should improve that altogether)

2023-02-03 12:33 UTC, neersighted requested changes
I think we should just go ahead and put the driver name at the end as it's closest to the current behavior.

2023-03-06 12:08 UTC, thaJeztah commented
@neersighted @vvoland updated; I moved the graphdriver name to the end of the error-message

2023-03-06 18:19 UTC, neersighted approved these changes

2023-03-06 18:53 UTC, thaJeztah commented
Hm.. interesting failure (unrelated);

```
=== FAIL: amd64.integration.service TestServicePlugin (1.36s)
    plugin_test.go:49: assertion failed: error is not nil: Error response from daemon: content sha256:82166c50eadae3a22d7700620198ccd6cb7e3e2303396baf01968562a0d1d1ae: already exists
```

2023-03-07 11:14 UTC, thaJeztah commented
@vvoland ptal (all green again 👍)

2023-03-09 09:51 UTC, vvoland approved these changes

2023-03-09 11:44 UTC, merged