update to go1.19.6
moby/moby pull request #44999
Opened 2023-02-14 19:44 UTC by thaJeztah

go1.19.6 (released 2023-02-14) includes security fixes to the crypto/tls, mime/multipart, net/http, and path/filepath packages, as well as bug fixes to the go command, the linker, the runtime, and the crypto/x509, net/http, and time packages. See the Go 1.19.6 milestone on our issue tracker for details:

https://github.com/golang/go/issues?q=milestone%3AGo1.19.6+label%3ACherryPickApproved

From the announcement on the security mailing:

We have just released Go versions 1.20.1 and 1.19.6, minor point releases.

These minor releases include 4 security fixes following the security policy:

- path/filepath: path traversal in filepath.Clean on Windows

  On Windows, the filepath.Clean function could transform an invalid path such
  as a/../c:/b into the valid path c:\b. This transformation of a relative (if
  invalid) path into an absolute path could enable a directory traversal attack.
  The filepath.Clean function will now transform this path into the relative
  (but still invalid) path .\c:\b.

  This is CVE-2022-41722 and Go issue https://go.dev/issue/57274.

- net/http, mime/multipart: denial of service from excessive resource consumption

  Multipart form parsing with mime/multipart.Reader.ReadForm can consume largely unlimited amounts of memory and disk files. This also affects form parsing in the net/http package with the Request methods FormFile, FormValue, ParseMultipartForm, and PostFormValue.

  ReadForm takes a maxMemory parameter, and is documented as storing "up to maxMemory bytes +10MB (reserved for non-file parts) in memory". File parts which cannot be stored in memory are stored on disk in temporary files. The unconfigurable 10MB reserved for non-file parts is excessively large and can potentially open a denial of service vector on its own. However, ReadForm did not properly account for all memory consumed by a parsed form, such as map ntry overhead, part names, and MIME headers, permitting a maliciously crafted form to consume well over 10MB. In addition, ReadForm contained no limit on the number of disk files created, permitting a relatively small request body to create a large number of disk temporary files.

  ReadForm now properly accounts for various forms of memory overhead, and should now stay within its documented limit of 10MB + maxMemory bytes of memory consumption. Users should still be aware that this limit is high and may still be hazardous.

  ReadForm now creates at most one on-disk temporary file, combining multiple form parts into a single temporary file. The mime/multipart.File interface type's documentation states, "If stored on disk, the File's underlying concrete type will be an *os.File.". This is no longer the case when a form contains more than one file part, due to this coalescing of parts into a single file. The previous behavior of using distinct files for each form part may be reenabled with the environment variable GODEBUG=multipartfiles=distinct.

  Users should be aware that multipart.ReadForm and the http.Request methods that call it do not limit the amount of disk consumed by temporary files. Callers can limit the size of form data with http.MaxBytesReader.

  This is CVE-2022-41725 and Go issue https://go.dev/issue/58006.

- crypto/tls: large handshake records may cause panics

  Both clients and servers may send large TLS handshake records which cause servers and clients, respectively, to panic when attempting to construct responses.

  This affects all TLS 1.3 clients, TLS 1.2 clients which explicitly enable session resumption (by setting Config.ClientSessionCache to a non-nil value), and TLS 1.3 servers which request client certificates (by setting Config.ClientAuth
  > = RequestClientCert).

  This is CVE-2022-41724 and Go issue https://go.dev/issue/58001.

- net/http: avoid quadratic complexity in HPACK decoding

  A maliciously crafted HTTP/2 stream could cause excessive CPU consumption in the HPACK decoder, sufficient to cause a denial of service from a small number of small requests.

  This issue is also fixed in golang.org/x/net/http2 v0.7.0, for users manually configuring HTTP/2.

  This is CVE-2022-41723 and Go issue https://go.dev/issue/57855.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-02-14 19:46 UTC, corhere approved these changes

2023-02-14 19:49 UTC, corhere requested changes
Do we want to merge this PR to master given #44620 is in the pipeline?

You missed a couple spots: https://github.com/moby/moby/blob/3ba527d82af53cf752aa6ec39daac14626c41b0f/.github/workflows/.windows.yml#L18 and https://github.com/moby/moby/blob/3ba527d82af53cf752aa6ec39daac14626c41b0f/.github/workflows/test.yml#L18

2023-02-14 19:52 UTC, thaJeztah commented
I'm fine either way; my take was we could get this into master and backport to branches where its needed. Wasn't sure if the other one was already ready to go.

2023-02-14 19:53 UTC, thaJeztah commented
But looks like (not all ?) images are up yet on Docker Hub

2023-02-14 23:18 UTC, neersighted commented
I'd prefer to take this in master so we can cherry-pick -- I would strongly like to avoid branch-specific changes as much as possible.

2023-02-16 23:28 UTC, corhere approved these changes

2023-02-16 23:29 UTC, neersighted approved these changes

2023-02-16 23:31 UTC, thaJeztah commented
> You missed a couple spots:

Thanks; fixed those. I think I got hit by my IDE catching up on "synchronising". 

Goland doesn't always play nice when I move too fast and reverts changes when it made changes while it's still reindexing files; and in that case it sometimes reverts files to the previous state.

(Really annoying!)

2023-02-17 00:19 UTC, merged