Respect --latest option in ContainerList
moby/moby pull request #45189
Opened 2023-03-22 02:24 UTC by preethamrn

**- What I did**
Set the latest value in the docker client query.

**- How to verify it**
Previously ContainerList requests with the Latest flag set would still return all containers. After this change, only the latest container is returned.

**- Description for the changelog**
The `Latest` option which is exported is not used in the ContainerList query. This change fixes that by setting the appropriate value when users set the latest flag.

2023-03-22 11:05 UTC, thaJeztah requested changes

2023-03-22 11:05 UTC, thaJeztah commented on client/container_list.go
> +	}
I'm not sure I understand this change; could you provide more information?

The API does not have a `latest` option; https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerList

Using `--latest` / `-l` on the command-line is effectively a short-hand to set `--limit=1`; https://github.com/docker/cli/blob/bfe87fd39b6b8a6bbf57e1f394238f65f99501b7/cli/command/container/list.go#L79-L81

```go
if opts.nLatest && opts.last == -1 {
	options.Limit = 1
}
```

(we could probably add a warning if both `--latest` and `--limit` / `-n` are set though)

2023-03-22 11:15 UTC, thaJeztah commented
I also had a quick try to see if the `--latest` option works, and it seems to work as expected;

```bash
docker run -d --name one nginx:latest
docker run -d --name two nginx:latest
docker run -d --name three nginx:latest

docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS     NAMES
3ebc1c2ebb96   nginx:latest   "/docker-entrypoint.…"   4 seconds ago   Up 3 seconds   80/tcp    three
16fdc5f1c38a   nginx:latest   "/docker-entrypoint.…"   4 seconds ago   Up 3 seconds   80/tcp    two
267f516caf8f   nginx:latest   "/docker-entrypoint.…"   5 seconds ago   Up 4 seconds   80/tcp    one


docker ps --latest
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS     NAMES
3ebc1c2ebb96   nginx:latest   "/docker-entrypoint.…"   8 seconds ago   Up 7 seconds   80/tcp    three
```

That said, there are some improvements we could make, and we could print a warning if the `--last` / `-n` is also set, because in that case, `--last`  / `-n` takes precedence;

```bash
docker ps --latest --last 2
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS     NAMES
3ebc1c2ebb96   nginx:latest   "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   80/tcp    three
16fdc5f1c38a   nginx:latest   "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   80/tcp    two
```

2023-03-22 17:29 UTC, preethamrn commented
I see. Thanks for the correction. I think we should still support it here because the option is exposed to users in `ContainerListOptions` (https://github.com/moby/moby/blob/master/api/types/client.go#L65) however it is not used in `ContainerList` currently.

I can update my change so that when Latest is set to true, it uses limit 1. Thanks

2023-03-22 18:29 UTC, thaJeztah commented
>  I think we should still support it here because the option is exposed to users in ContainerListOptions (https://github.com/moby/moby/blob/master/api/types/client.go#L65) however it is not used in ContainerList currently.

It looks like that field was introduced in https://github.com/moby/moby/pull/18472 (https://github.com/moby/moby/commit/d05aa418b0466553a24d42896f99176cfa29765f), but never used in the client. That change was part of a _large_ refactor, so probably got missed during review.

I think we could go some ways;

1. Remove the field, or
2. (for now) keep the field but produce an error if it's set
3. (possibly) move the CLI logic to the Client; https://github.com/docker/cli/blob/bfe87fd39b6b8a6bbf57e1f394238f65f99501b7/cli/command/container/list.go#L79-L81

I think in general we want to make the client better, and move more logic to the client (where it makes sense); from that perspective, `3.` could make sense, BUT there's still a lot to be discussed in that area; for this specific example I guess we also need to look if it makes sense to include in the client if it's not really an API option (although perhaps it's fine)

2023-03-24 20:10 UTC, preethamrn commented
Any of those approaches sound reasonable to me. I just wanted to raise this issue in case it was unintended behavior (which it seems like it is).
I'm not very familiar with the codebase so I'll let you make the final call on which approach to take before making further changes. Thanks

2026-05-18 13:48 UTC, thaJeztah commented
Closing, as we deprecated the `options.Latest` field in the client option struct https://github.com/moby/moby/pull/51908

2026-05-18 13:48 UTC, closed without merging