libn/d/overlay: stop programming INPUT ACCEPT rule
moby/moby pull request #45280
Opened 2023-04-05 15:37 UTC by corhere

Encrypted overlay networks are unique in that they are the only kind of network for which libnetwork programs an iptables rule to explicitly accept incoming packets. No other network driver does this. The overlay driver doesn't even do this for unencrypted networks!

Because the ACCEPT rule is appended to the end of INPUT table rather than inserted at the front, the rule can be entirely inert on many common configurations. For example, FirewallD programs an unconditional REJECT rule at the end of the INPUT table, so any ACCEPT rules appended after it have no effect. And on systems where the rule is effective, its presence may subvert the administrator's intentions. In particular, automatically appending the ACCEPT rule could allow incoming traffic which the administrator was expecting to be dropped implicitly with a default-DROP policy.

Let the administrator always have the final say in how incoming encrypted overlay packets are filtered by no longer automatically programming INPUT ACCEPT iptables rules for them.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-04-05 15:44 UTC, neersighted approved these changes
LGTM

2023-04-05 15:49 UTC, akerouanton approved these changes
LGTM

2023-04-05 23:57 UTC, cpuguy83 commented
> Let the administrator always have the final say in how incoming encrypted overlay packets are filtered by no longer automatically programming INPUT ACCEPT iptables rules for them.

I agree, but... how are we harming established UX here?

2023-04-17 18:30 UTC, thaJeztah requested changes
We discussed this, and are okay with this with proper documentation; let's keep this one for the 25.0.0 release

2023-05-25 19:03 UTC, thaJeztah approved these changes
we agreed on merging this for 25; still need to look at docs after this

/cc @akerouanton

2023-05-25 19:03 UTC, merged