Deprecate dockerd api-cors-header parameter
moby/moby pull request #45313
Opened 2023-04-12 11:09 UTC by akerouanton

Only browsers use CORS headers, there's no real use-case for directly accessing Docker API through a browser (ie. without a reverse proxy/middleware, web backend, or anything else doing a HTTP protocol break in the middle) and this is really dangerous. The current implementation doesn't even make the value mandatory. When no value is provided, the CORS middleware falls back to a wildcard, which means "any in-browser JS script can XSS me".

For the record, [this is the original PR](https://github.com/moby/moby/pull/806) that introduced this feature. The original goal/use case was to ease demos (circa 2013) through dockerui (which later became portainer).

I'd like to spark a discussion about whether we want to go through a normal deprecation process. From my side, I think we should remove it and not care with a proper deprecation notice. If someone need this they should know what they do and figure out by themselves how to set up a reverse proxy and ensure their security model is OK.

OTOH, I get that we have a deprecation process for good reasons. At the very least, I think we should not provide any detailed alternatives in the deprecation notice (ie. no more than "use a reverse proxy").

**- Description for the changelog**

- The api-cors-header config parameter has been deprecated.

2023-04-12 11:25 UTC, sam-thibault approved these changes

2023-04-12 12:31 UTC, thaJeztah reviewed
Thanks! Left some suggestions / comments.

I had them drafted locally, so will open a quick PR against your branch (feel free to pick/remove what's not needed)

2023-04-12 12:32 UTC, thaJeztah commented
opened against your fork;

- https://github.com/akerouanton/docker/pull/1

2023-04-12 14:27 UTC, thaJeztah commented
Failure is a known flaky test (kicked CI again)

```
=== FAIL: amd64.integration-cli TestDockerSwarmSuite/TestSwarmLockUnlockCluster (75.80s)
    docker_cli_swarm_test.go:1110: [db848fc4e9cfb] joining swarm manager [d574ec27271fd]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2478
    docker_cli_swarm_test.go:1111: [d74704f900a83] joining swarm manager [d574ec27271fd]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2479
    docker_cli_swarm_test.go:999: timeout hit after 1s: first check never completed
    daemon_swarm.go:162: assertion failed: error is not nil: error during connect: Get "http://%2Ftmp%2Fdocker-integration%2Fd574ec27271fd.sock/v1.43/info": EOF: get swarm info
    --- FAIL: TestDockerSwarmSuite/TestSwarmLockUnlockCluster (75.80s)
```

2023-04-12 14:28 UTC, thaJeztah approved these changes
LGTM

2023-04-12 14:29 UTC, corhere requested changes
> The current implementation doesn't even make the value mandatory. When no value is provided, the CORS middleware falls back to a wildcard, which means "any in-browser JS script or HTML form can CSRF me".

That does not appear to be the case in practice. While the middleware itself converts the empty string to `*`, the daemon config code only enables the CORS middleware when a nonempty string is set. https://github.com/moby/moby/blob/8cf66ed7322fa885ef99c4c044fa23e1727301dc/cmd/dockerd/daemon.go#L558-L561

> there's no real use-case for directly accessing Docker API through a browser (ie. without a reverse proxy/middleware, web backend, or anything else doing a HTTP protocol break in the middle)

Except that authz plugins exist. I don't think we can deprecate the api-cors-header option independently of authz plugins.

2023-04-12 14:31 UTC, thaJeztah commented
@akerouanton can you also open a PR in docker/cli to 

- add it to the deprecated features list https://github.com/docker/cli/blob/master/docs/deprecated.md
- search for other occurrences (e.g. completion scripts; I guess we can already remove these there)
- ^^ maybe split some to separate commits in that PR in case we already want to include the deprecation in our docs to get the message out sooner.

2023-04-12 14:33 UTC, akerouanton commented
> Except that authz plugins exist. I don't think we can deprecate the api-cors-header option independently of authz plugins.

I don't follow you. How does that relate to CORS headers?

2023-04-12 14:36 UTC, corhere commented
Authz plugins provide access control for the Engine API without reverse-proxying, i.e. "doing an HTTP protocol break", potentially making it safe to allow browser-based clients.

2024-05-08 22:43 UTC, corhere approved these changes

2024-05-22 08:07 UTC, thaJeztah commented
@akerouanton Can you also open a PR to add this to the deprecated features (https://github.com/docker/cli/blob/master/docs/deprecated.md)

Perhaps we should also have a note in the API changelog (even though it's not the API schema that's changing, it probably won't hurt for visibility?)

2024-05-28 21:42 UTC, thaJeztah approved these changes
LGTM, thanks!

2024-05-28 21:42 UTC, merged