Fail unpacking images with xattrs to filesystems without xattr support
moby/moby pull request #45464
Opened 2023-05-04 16:56 UTC by corhere

Following up https://github.com/moby/moby/pull/45420#issuecomment-1535047278 I want to put out a strawman to continue that discussion. I'm still weirded out by letting `EPERM` slide, but I'd like to save that discussion for another day.

**- What I did**
Made it a fatal error to untar a file with extended attributes to a destination which does not support extended attributes.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-05-04 19:00 UTC, neersighted approved these changes

2023-05-04 19:22 UTC, thaJeztah requested changes
we discussed this, and because vfs is also a bit of a "last resort", we'd like to provide an escape-hatch for this case ("I_KNOW_WHAT_IM_DOING_GET_ME_OUT_OF_HERE")

2023-05-04 20:06 UTC, thaJeztah commented
Also for "future  self" (and other visitors); we initially had a concern "what happens if I pull an image, and it's extracted to a filesystem without xattr support (so extended attributes get discarded), and after that I would push that image?
But that's not a concern; when the image layers (tar) are constructed to push, only the file content is read from disk, all other properties are taken from the tar split headers (so even though the extended attributes are missing on the filesystem, the layers will re-apply them before pushing).

2023-05-18 19:05 UTC, thaJeztah commented on daemon/graphdriver/vfs/driver.go
> +		case "xattrs":
As discussed, this could be `vfs.xattrs`

2023-05-18 19:05 UTC, tianon approved these changes
:eyes: (looks good minus the naming comment Seb just made)

2023-05-18 19:06 UTC, cpuguy83 approved these changes

2023-05-18 19:07 UTC, thaJeztah commented on daemon/graphdriver/vfs/driver.go
> +			if val != "i_want_broken_containers" {
We discussed the naming of this, and it looks silly, but it makes it without doubt clear "don't use this... ever", so let's go for it

2023-05-18 19:12 UTC, thaJeztah approved these changes
"LGTM" after changing the `vfs`  prefix, and perhaps a `logrus.Warn` if the setting set.

2023-05-18 19:13 UTC, thaJeztah commented on daemon/graphdriver/vfs/driver.go
> +			{"Warranty", "void"},
There's no warranty in ASL2, so probably could be dropped 😉

2023-05-18 21:24 UTC, corhere commented
Note for reviewers: all system-info warnings are logged by the daemon during startup in addition to being included in the `/info` response.
https://github.com/moby/moby/blob/ccd834ea254da112673968a620386717f38bf31a/daemon/daemon.go#L1136-L1139

2023-05-18 21:39 UTC, neersighted approved these changes
LGTM, and the warning language seems to strike a good balance now.

2023-05-19 00:52 UTC, AkihiroSuda approved these changes

2023-05-19 06:38 UTC, thaJeztah commented
Test failure looks related

```
=== FAIL: daemon/graphdriver/vfs TestXattrUnsupportedByBackingFS/xattrs=i_want_broken_containers (0.00s)
    vfs_test.go:98: assertion failed: error is not nil: unknown option xattrs for vfs

2023-05-19 12:21 UTC, merged

2023-05-19 12:22 UTC, neersighted commented
...and that was the wrong button (I was trying to click 'Show all checks' but my brain wasn't quite there yet) -- @corhere, could you figure out the test issue in a follow-up?