daemon: remove fillDriverWarnings()
moby/moby pull request #45574
Opened 2023-05-18 21:58 UTC by thaJeztah

- relates to https://github.com/moby/moby/pull/35514
- relates to https://github.com/moby/moby/pull/43637

### daemon: remove warning for overlay/overlay2 without d_type

commit 0abb8dec3f730f3ad2cc9a161c97968a6bfd0631 (https://github.com/moby/moby/pull/35514) removed support for running overlay/overlay2 on top of a backing filesystem without d_type support, and  turned it into a fatal error when starting the daemon, so there's no need to generate warnings for this situation.

### daemon: remove fillDriverWarnings()

commit dc11d2a2d8e1df0a90ce289f5dd06cad38193073 (https://github.com/moby/moby/pull/43637) removed the devicemapper storage-driver, which was the last remaining driver needing this function, so we can remove it.

2023-05-18 22:09 UTC, corhere requested changes
I'm using fillDriverWarnings in #45464

2023-05-18 22:29 UTC, thaJeztah commented
oh! 🤦 I'm ignorant. Saw your comment, and it didn't connect that you'd be using the function.

I updated, and left the function in place but guess the second commit will cause a few lines of code-churn.

2023-05-19 08:42 UTC, neersighted approved these changes

2023-05-19 16:19 UTC, corhere commented
I'll review after it's been rebased

2023-05-19 16:37 UTC, thaJeztah commented
Oh! LOL putting the rebase fun back into my court 😂 

i'll do a rebase in a bit 🤗 ❤️

2023-05-19 18:46 UTC, thaJeztah commented
@corhere rebased 👍

2023-05-19 18:57 UTC, neersighted approved these changes

2023-05-19 19:02 UTC, corhere approved these changes

2023-05-19 23:04 UTC, merged