fix: hdr.Xattrs deprecated
moby/moby pull request #45640
Opened 2023-05-27 07:04 UTC by testwill

2023-05-27 10:40 UTC, AkihiroSuda commented
Did you test this PR?

2023-05-27 10:41 UTC, AkihiroSuda commented on pkg/archive/archive.go
> +		hdr.PAXRecords["security.capability"] = string(capability[:length])
missing `SCHILY.xattr`

2023-05-30 19:34 UTC, corhere requested changes
@AkihiroSuda is right; [xattr PAXRecords are prefixed with "SCHILY.xattr."](https://pkg.go.dev/archive/tar#Header:~:text=//%20Xattrs%20stores%20extended%20attributes%20as%20PAX%20records%20under%20the%0A%09//%20%22SCHILY.xattr.%22%20namespace.%0A%09//%0A%09//%20The%20following%20are%20semantically%20equivalent%3A%0A%09//%20%20h.Xattrs%5Bkey%5D%20%3D%20value%0A%09//%20%20h.PAXRecords%5B%22SCHILY.xattr.%22%2Bkey%5D%20%3D%20value)

2023-05-30 19:34 UTC, corhere commented on pkg/archive/archive.go
> +	for key, value := range hdr.PAXRecords {
Not all PAXRecords are xattrs. Applying all records as xattrs, especially without first stripping off the "SCHILY.xattr." prefix from the xattr name, is incorrect.

2023-05-30 21:34 UTC, neersighted commented
Relevant, though it does not make the situation better or worse: https://github.com/opencontainers/image-spec/issues/725

2023-05-31 01:06 UTC, closed without merging