use /proc/thread-self for mounting network namespace
moby/moby pull request #45682
Opened 2023-06-02 05:41 UTC by spikecurtis

fixes #45681 

**- What I did**

Fixes an issue where `--net=host` runs would fail if Docker is run within a sysbox container.

**- How I did it**

`--net=host` mounts the network namespace without using `unshare`, but the code uses a call to `unix.Gettid()` for the thread ID, builds the `/proc` path from it, then issues the syscall.  Without `unshare` code on the same goroutine can be run on different OS threads, and it appears the syscall is run on a different thread and fails.

We can simplify and fix the logic by using `/proc/thread-self` instead of querying for the threadID.

**- How to verify it**

c.f. repro steps in #45681 

**- Description for the changelog**

fixed an issue where `--net=host` would fail in restricted environments, for example sysbox

**- A picture of a cute animal (not mandatory but encouraged)**

![IMG_1673](https://github.com/moby/moby/assets/5375600/2004b943-ae94-4737-bd75-8d7c828fffab)

2023-06-02 09:47 UTC, thaJeztah commented
@corhere PTAL 

/cc @ctalledo

2023-06-02 11:47 UTC, corhere requested changes
`/proc/thread-self` does not exist on the oldest kernels we support so cannot be used

2023-06-02 11:53 UTC, corhere commented
If mounting one thread's netns from another thread is the problem, use `runtime.LockOSThread()` to guarantee that the goroutine is running on the same thread for both the gettid and the mount call.

2023-06-05 16:06 UTC, spikecurtis commented
Tried with `runtime.LockOSThread()` and this unfortunately doesn't resolve the issue with sysbox.  It's a mystery to my why `/proc/thread-self` works, but not `/proc/self/task/<tid>` with the correct thread ID.

I think that means my theory for what's wrong is false, so closing this PR.

2023-06-05 16:06 UTC, closed without merging