fix disagreement between seccomp docs and profile reality
moby/moby pull request #45766
Opened 2023-06-18 17:26 UTC by bartier

closes #45518

Hi there, this is my first PR here, so please feel free to point me out if anything is wrong with this contribution. I looked the #45518 issue and I believe this could be a fix.

**- What I did**
Made the change to match what the documentation states for the `name_to_handle_at ` syscall.

**- How I did it**
Guessing a fix

**- How to verify it**
AFAIK, this may be a simple change and the docs is now matching the default profile.

**- Description for the changelog**

Fix disagreement between `name_to_handle_at ` seccomp documentation and default profile

**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://github.com/moby/moby/assets/18057391/a8a3b84f-ccb9-40cf-a22c-512713efd790)

2023-06-22 07:50 UTC, thaJeztah commented
Thanks for contributing! I see nobody posted here yet, but @neersighted has been digging into history (as well as Linux kernel man-pages and source-code) to verify these changes. I think some further digging was still needed, as there were some (very subtle?) cases where this could cause issues (stay tuned 👍)

(Code changes themselves look good 👍, but it may need a rebase to make the `docker-py` tests pass (which had an issue that has been fixed on master), but we can ignore those for the time being)

2023-06-22 19:59 UTC, neersighted requested changes
Thanks for sending this patch!

Since this is both pretty load-bearing (lots of useful software, e.g. systemd want this syscall)/(potentially) security critical, and has been in this state for a very long time, I did some extensive digging.

First, some background on what `name_to_handle_at(2)` and `open_by_handle_at(2)` actually do: this is more-or-less a two-stage `openat(2)`, as [described in the manpage](https://manpages.ubuntu.com/manpages/jammy/en/man2/open_by_handle_at.2.html).

`name_to_handle_at(2)` performs a filesystem lookup, but instead of opening a file, it copies a (opaque) `struct file_handle` to userspace. That handle contains a string, which was [registered](https://elixir.bootlin.com/linux/v5.19.17/source/fs/fhandle.c#L49) in the kernel as part of the system call.

`open_by_handle_at(2)` can then be used to open the path described by that file handle (which is [dereferenced](https://elixir.bootlin.com/linux/v5.19.17/source/fs/fhandle.c#L152) similarly to how it was saved), without doing a filesystem lookup a second time. Note that this does not defend against TOCTOU issues (e.g. the filesystem changing between calls); it merely allows one to pay the cost of resolving a path in the filesystem a single time.

This appears to have been added to the kernel to better support userspace network filesystem servers (which open and close **many** files and thus need all the performance shortcuts they can get), and the kernel implementation actually builds on the infrastructure of the `exportfs` subsystem used for the in-kernel NFS implementation.

The curious among us might find the following parts of the kernel source interesting:
* [fs/fhandle:handle_to_path](https://elixir.bootlin.com/linux/v5.19.17/source/fs/fhandle.c#L167)
* [fs/namei:do_filp_open](https://elixir.bootlin.com/linux/v5.19.17/source/fs/namei.c#L3676)
* [fs/namei:do_file_open_root](https://elixir.bootlin.com/linux/v5.19.17/source/fs/namei.c#L3693)
* [fs/namei:do_open](https://elixir.bootlin.com/linux/v5.19.17/source/fs/namei.c#L3478)

Nonetheless, there are some differences from `openat(2)`: `open_by_handle_at(2)` requires specific [`capabilities(7)`](https://manpages.ubuntu.com/manpages/jammy/en/man7/capabilities.7.html): `CAP_DAC_READ_SEARCH`, but `openat(2)` requires no privilege. Why is that?

First, let's establish what does **not** make `open_by_handle_at(2)` dangerous:
* `open_by_handle_at(2)` does pass a opaque and kernel-provided data structure back in, over the kernel/userspace boundary. However, the kernel is quite resilient to potentially hostile inputs, and in this specific case, `struct file_handle` is just structured data and is safely deserialized -- the kernel never tries to use what it gets back from userspace as a normal internal data structure.
* Permissions are checked (the thing that `CAP_DAC_OVERRIDE` allows skipping) during `open_by_handle_at(2)`, in the common [`do_open`](https://elixir.bootlin.com/linux/v5.19.7/source/fs/namei.c#L3520) used by this entire family of system calls, so there is no risk of a stored `struct file_handle` being used to bypass (Unix) permissions.

If there is no risk of attacking the kernel, or bypassing DAC, what is the risk of this system call then? Well, if the user can construct arbitrary `struct file_handle`s (hint: they can) and pass them to the kernel, there is the risk they manage to forge a handle and open a path that they otherwise could not access. Note that 'access' is not in the Unix permissions sense -- I use 'access' here to mean "open a `dentry` that cannot otherwise be resolved using the visible filesystem." 

It's notable that there are many situations where filesystem access is not limited by permissions (e.g. a program has root), but instead by filesystem visibility:
* `chroot(2)`
* mount namespaces (including `pivot_root(2)`), which are **used in containers** (more on this later)

Indeed, if we look at the history of the patch that introduced these system calls:
* The [initial version of the patch](https://lore.kernel.org/all/1266558149-11460-3-git-send-email-aneesh.kumar@linux.vnet.ibm.com/) required `CAP_SYS_ADMIN` (infamously, ['almost root'](https://lwn.net/Articles/486306/)).
  - The risk of `struct file_handle` being forged was brought up in [one of the earliest reviews](https://lore.kernel.org/all/AD5A6061-9B7B-4B29-A458-822E781C2588@sun.com/).
* The [next version of the patch](https://lore.kernel.org/all/1268932144-14105-1-git-send-email-aneesh.kumar@linux.vnet.ibm.com/) moved to `CAP_DAC_OVERRIDE`.
  - Presumably the logic here was that forging a handle was similar to 'a process that is trusted to ignore Unix permissions'.
* [Subsequent versions](https://lore.kernel.org/all/1275581657-7232-1-git-send-email-aneesh.kumar@linux.vnet.ibm.com/) decreased the capability to `CAP_DAC_READ_SEARCH`.
  - As the only risk here is resolving a path that you otherwise could not, 'read' + 'search' (resolve path) are presumably a more granular fit.
  - The patch does note that `CAP_DAC_SEARCH` would be desirable if it existed, as it would more accurately reflect the threat model.
* [The final, merged version of the patch](https://lore.kernel.org/all/1296328099-23263-1-git-send-email-aneesh.kumar@linux.vnet.ibm.com/) made no changes to the permissions/capabilities model.

Given the above context, it is very clear that `name_to_handle_at(2)` is a safe operation (all it does is return a value that is useless without its sister syscall), and `open_by_handle_at(2)` is the dangerous component. So why is `name_to_handle_at(2)` more restricted?

Before we address that point directly, it helps to think about how Linux containers work (and how they isolate filesystem access). As noted above, we use mount [namespaces(7)](https://manpages.ubuntu.com/manpages/jammy/man7/namespaces.7.html) as part of the containerization. In fact, mount namespaces are one of the most critical forms of isolation making up a container; you can have root inside a container, but you can't use that root access to affect things outside the container if you can't see the filesystem.

This is in fact false if you can abuse `open_by_handle_at(2)` to get access to a path you otherwise could not see in your mount namespace; this is the basis of one of the first container escapes, 'shocker.'

Others have already done an excellent job at explaining the exploit; these links should give more background if it is interesting to you:
* http://stealth.openwall.net/xSports/shocker.c
* https://lxc-users.linuxcontainers.narkive.com/9kzuZR09/container-escape-through-open-by-handle-at-shocker-exploit
* https://medium.com/@fun_cuddles/docker-breakout-exploit-analysis-a274fff0e6b3

This was ultimately solved in Docker by [dropping capabilities by default](https://github.com/moby/moby/commit/9d6875d19d3926faf6287487234ad0b2f1310e9d), beyond a narrow list of innocuous ones (e.g. `CAP_MKNOD`).

Now we understand this family of system calls, and their risk to containers. However, we still haven't puzzled out why `name_to_handle_at(2)` was gated behind `CAP_SYS_ADMIN`; to begin understanding that, let's look at the evolution of the default seccomp profile:
* [The first version](https://github.com/jessfraz/docker/commit/947293a28084cb5ee2e10e4d128c6e2b9d9da89d#diff-617cddaebc1111c35f3ea1b55908653720ec669df60f508bbe182f83bc794a6cR185-R189) of the profile blocked `open_by_handle_at(2)` as it was implicated in shocker.
  - This appears to be something of a 'why not?' situation; the actual escape is solved by dropping the capability, but it doesn't hurt to filter with seccomp as well...
* [A subsequent change](https://github.com/moby/moby/commit/17735c3c98056006b40834d7426d8d90afae5a2c) was to move to an allowlist instead of a denylist; the explicit reference to `open_by_handle_at(2)` was dropped.
* [A later, major refactor](https://github.com/moby/moby/commit/a01c4dc8f85827f32d88522e5153dddc02f11806#diff-6c0d906dbef148d2060ed71a7461907e5601fea78866e4183835c60e5d2ff01aR1627- [...]

2023-06-22 20:01 UTC, neersighted commented
Also, after the above change is made and accepted, this PR will need backports to all branches (I can do this). In addition, we'll need to adjust the [profile in containerd](https://github.com/thaJeztah/containerd/blob/bbb8d3470483c8054fd435d815ba699f94350928/contrib/seccomp/seccomp_default.go#L572); however, I am happy to do that work.

2023-06-23 16:39 UTC, tianon commented
Fantastic summary, and well done on the sleuthing, @neersighted :bow: :+1:

2023-06-26 11:08 UTC, thaJeztah commented
@bartier do you need help / details on making the suggested changes? (I'm sure @neersighted is also happy to update this PR if needed)

2023-06-26 17:35 UTC, bartier commented
Hi @neersighted , thanks for the depth explanation. Also, I have created the PR https://github.com/docker/docs/pull/17623 to match the changes.

Please let me know if I am missing something but I am happy to help.

2023-06-26 18:44 UTC, neersighted commented
Thanks! The change overall looks good to me now; could we update the PR title and description for the new direction, and maybe rephrase the commit message to be a little more obvious (e.g. `remove name_to_handle_at(2) from filtered syscalls`)?

Otherwise, LGTM :+1:

2023-06-26 20:59 UTC, bartier commented
@neersighted I've squashed to 1 commit and changes the PR title. I wonder if it is required to squash the commits as we can merge and squash in the GitHub UI.

2023-06-26 23:33 UTC, corhere commented
> I wonder if it is required to squash the commits as we can merge and squash in the GitHub UI.

We have disabled the "Squash and merge" option on this repository. We want the merge commit to be separate from the PR commit(s), which doesn't happen when GitHub squash-merges a PR.

2023-06-27 02:06 UTC, neersighted commented
Still needs the commit message updated, but otherwise LGTM

2023-06-27 12:50 UTC, bartier commented
@neersighted Changed to match the PR title

2023-06-27 12:58 UTC, neersighted approved these changes
LGTM! Thank you for your patience!

2023-06-27 17:13 UTC, tianon approved these changes

2023-06-27 17:33 UTC, merged

2023-06-27 19:28 UTC, neersighted commented
Backports at:
- https://github.com/moby/moby/pull/45833
- https://github.com/moby/moby/pull/45834
- https://github.com/moby/moby/pull/45835

PTAL @bartier

2023-06-27 19:39 UTC, neersighted commented
containerd PRs at:
- https://github.com/containerd/containerd/pull/8752
- https://github.com/containerd/containerd/pull/8753
- https://github.com/containerd/containerd/pull/8754

2023-06-28 08:06 UTC, thaJeztah commented on profiles/seccomp/default.json
> -				"name_to_handle_at",
@neersighted I noticed we remove this one from the list here, but don't add it to the allow-list, https://github.com/moby/moby/blob/a78c06e3f06e6f55518e1ba2bf9f723cf19d0a65/profiles/seccomp/default_linux.go#L401

Doesn't that mean that it now gets the default (`specs.ActErrno` /  `SCMP_ACT_ERRNO`)?
https://github.com/moby/moby/blob/a78c06e3f06e6f55518e1ba2bf9f723cf19d0a65/profiles/seccomp/default_linux.go#L818