client: remove custom "headers" type (use http.Header), and omit "version" header on API >= 1.30
moby/moby pull request #45923
Opened 2023-07-10 15:44 UTC by thaJeztah

- relates to https://github.com/moby/moby/pull/32388
- relates to https://github.com/moby/moby/pull/40816

### client: ServiceCreate, ServiceUpdate: remove unused "version" header

The "version" header was added in c0afd9c873183604e57282e1cf47605c1f1e4d43 (https://github.com/moby/moby/pull/32388) in docker 17.06, but used the wrong information to get the API version.

This issue was fixed in a9d20916c3d1f5e3c3ddada79af19aee4ec64629 (https://github.com/moby/moby/pull/40816), which switched the API handler code to get the API version from the context. That change is part of Docker Engine 20.10 (API v1.30 and up)

This patch updates the code to only set the header on APi v1.29 and older, as it's not used by newer API versions.

### client: remove custom "headers" type, and use "http.Header" instead

Use `http.Header`, which is more descriptive on intent, and we're already importing the package in the client. Removing the "header" type also fixes  various locations where the type was shadowed by local variables named "headers".

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-07-10 22:49 UTC, corhere requested changes
Until `client.NewClientWithOpts(client.WithVersion("1.29"))` fails with an error, or the import path contains a Go module version (e.g. `github.com/moby/moby/v26/client`), we should continue sending the `version` request header when the client's (configured or negotiated) API version is <= 1.29. I don't buy the argument that the daemon version being EOL means we can start to quietly and subtly break things in the client when used with EOL daemons when the cost of retaining support is trivial.

2023-07-11 11:18 UTC, thaJeztah commented
Updated, and now setting the version header conditionally

2023-07-11 20:09 UTC, corhere approved these changes

2023-07-11 20:29 UTC, neersighted approved these changes

2023-07-11 20:30 UTC, merged