integration/container: use subtests for TestAttach
moby/moby pull request #45937
Opened 2023-07-12 11:17 UTC by thaJeztah

- Combine TestAttach and TestAttach to a single test using sub-tests
- Set up and tear-down the test-environment once
- Remove redundant client.ContainerRemove, as it's taken care of by testEnv.Clean()
- Run both tests in parallel

      make TEST_FILTER=TestAttach DOCKER_GRAPHDRIVER=overlay2 TESTDEBUG=1 test-integration
      Loaded image: busybox:latest
      Loaded image: busybox:glibc
      Loaded image: debian:bullseye-slim
      Loaded image: hello-world:latest
      Loaded image: arm32v7/hello-world:latest
      INFO: Testing against a local daemon
      === RUN   TestAttach
      === RUN   TestAttach/without_TTY
      === PAUSE TestAttach/without_TTY
      === RUN   TestAttach/with_TTY
      === PAUSE TestAttach/with_TTY
      === CONT  TestAttach/without_TTY
      === CONT  TestAttach/with_TTY
      --- PASS: TestAttach (0.00s)
          --- PASS: TestAttach/without_TTY (0.03s)
          --- PASS: TestAttach/with_TTY (0.03s)
      PASS

      DONE 3 tests in 1.347s

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-07-12 11:43 UTC, thaJeztah commented
Looks like CI is broken, because the BuildKit tests don't pin to a minor Go version, so have been updated to go1.19.11;

```
2023-07-12T11:23:35.0244805Z #7 [internal] load metadata for docker.io/library/golang:1.19-alpine3.17
```


Which looks to have a regression;

- https://github.com/moby/moby/issues/45935

2023-07-13 11:36 UTC, vvoland requested changes

2023-07-13 11:36 UTC, vvoland commented on integration/container/attach_test.go
>  	defer setupTest(t)()
Hmmm actually it looks like we already have some tests which have this issue.

2023-07-13 11:36 UTC, vvoland commented on integration/container/attach_test.go
> +			assert.Check(t, mediaType == tc.expectedMediaType)
```suggestion
			assert.Check(t, is.Equal(mediaType, tc.expectedMediaType))
```

2023-07-13 11:55 UTC, vvoland commented on integration/container/attach_test.go
>  	defer setupTest(t)()
Opened: https://github.com/moby/moby/pull/45957

2023-07-13 11:58 UTC, thaJeztah commented on integration/container/attach_test.go
>  	defer setupTest(t)()
Doh! I have a branch somewhere that rewrites the setup test to use t.Cleanup, and I think I did it for this reason.

Let me go find it (or did I already open a PR for it? LOL)

2023-07-13 16:23 UTC, thaJeztah commented on integration/container/attach_test.go
> +			assert.Check(t, mediaType == tc.expectedMediaType)
Good catch; updated

2023-07-17 08:31 UTC, vvoland approved these changes

2023-07-19 17:24 UTC, merged