pkg/chrootarchive: fix Darwin build
moby/moby pull request #46094
Opened 2023-07-27 20:27 UTC by slonopotamus

Before this commit, `doPack`, `doUnpack` and `doUnpackLayer` were not implemented for Darwin, causing build failure.

This change allows all non-Linux Unixes to use FreeBSD reexec-based pack/unpack implementation

See also: moby/buildkit#4059
See also: 8b843732b36541b8b8a11ecb83cf5d51837ae22f

**- What I did**

Allowed FreeBSD chrootarchive implementation to be used on all Unixes (except Linux that has a separate one).

**- How I did it**

Renamed `archive_freebsd.go` to `archive_unix_nonlinux.go` and adjusted `go:build` accordingly.

**- How to verify it**

Run chrootarchive tests on Darwin.

This PR (combined with https://github.com/moby/buildkit/pull/4059) also allows buildkit to compile on Darwin.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2023-07-31 18:28 UTC, thaJeztah commented
Is this still needed (taking https://github.com/containerd/containerd/pull/8789 being reverted into account)? Mostly curious why this package would be imported on macOS

2023-07-31 18:50 UTC, slonopotamus commented
This is unrelated to that containerd PR, this is a prerequisite to compile buildkitd (further changes are happening in moby/buildkit#4059).

2023-08-12 20:16 UTC, slonopotamus commented
@thaJeztah are there any doubts about merging this PR?

2023-09-27 22:59 UTC, AkihiroSuda approved these changes

2023-09-28 12:38 UTC, neersighted requested changes
I'd prefer to take advantage of https://github.com/golang/go/issues/51572; and instead use `unix && !linux`, naming the files `_unix_nolinux.go`.

2023-09-28 12:43 UTC, slonopotamus commented
That feature requires Go >= 1.19, if I read your link properly. I thought Moby still supports 1.18: https://github.com/moby/moby/blob/master/vendor.mod#L7

2023-09-28 12:49 UTC, neersighted commented
The line in the vendor.mod used to be purely informational, and we only bumped it when we knowingly changed the lower bound. The source of truth has always been the `GO_VERSION` in the Dockerfile, which we try to keep at Go n-1, though sometimes it moves faster (see https://github.com/moby/moby/pull/46069).

In this case, I would suggest that you bump it to `go 1.19`; in any case, after Go 1.21 hits the repo, I plan to re-do how we manage Go versions to try and make `vendor.mod` "canonical" as that is the way Go upstream is going.

2023-09-28 13:23 UTC, slonopotamus commented
Done

2023-09-28 15:34 UTC, neersighted commented
https://github.com/moby/moby/pull/46562

2023-09-29 13:51 UTC, neersighted approved these changes

2023-10-12 22:15 UTC, merged