logger/fluentd: remove deprecated fluentd-async-connect option
moby/moby pull request #46114
Opened 2023-07-29 09:49 UTC by akerouanton

**- What I did**

This option was marked as deprecated in cc1f3c750 (released in v20.10). The option `fluentd-async`, introduced in the same commit, should be used instead.

There's no target for removal defined in our docs (cf. https://docs.docker.com/engine/deprecated/#fluentd-async-connect-log-opt), but let's see what other maintainers think about dropping it in v25.0 or v26.0.

**- Description for the changelog**

* The Fluent logger option `fluentd-async-connect option` has been deprecated in v20.10 and is now removed.

2023-07-29 10:59 UTC, thaJeztah requested changes
Thanks! Left a comment 🙈 


> There's no target for removal defined in our docs (cf. https://docs.docker.com/engine/deprecated/#fluentd-async-connect-log-opt), but let's see what other maintainers think about dropping it in v25.0 or v26.0.

Can you open a PR on the CLI repository to add a target removal date? https://github.com/docker/cli/blob/master/docs/deprecated.md

We should also check if there's anything in https://github.com/docker/docs mentioning the old option (and if so, remove)

2023-07-29 10:59 UTC, thaJeztah commented on daemon/logger/fluentd/fluentd.go
> -	asyncConnectKey           = "fluentd-async-connect" // deprecated option (use fluent-async instead)
We probably need a migration step for this on container restore. If we remove this option here, I _think_ existing containers that have the option set will fail to start when starting the daemon after updating.

So in the "restore" part of the daemon (where we restore containers from their config on-disk), we need to patch existing containers and remove the `fluentd-async-connect`, and set the `fluentd-async` option instead (then save the container config).

We had a similar case for the log entries driver (but also needs to be fixed before we can merge that one);

- https://github.com/moby/moby/pull/44442

2025-01-13 17:45 UTC, akerouanton commented on daemon/logger/fluentd/fluentd.go
> -	asyncConnectKey           = "fluentd-async-connect" // deprecated option (use fluent-async instead)
Done

2025-01-13 18:46 UTC, thaJeztah approved these changes
LGTM

2025-01-13 18:47 UTC, merged