c8d/snapshot: Create any platform if not specified
moby/moby pull request #47167
Opened 2024-01-22 15:23 UTC by vvoland

With containerd snapshotters enabled `docker run` currently fails when creating a container from an image that doesn't have the default host platform without an explicit `--platform` selection:

```
$ docker run image:amd64
Unable to find image 'asdf:amd64' locally
docker: Error response from daemon: pull access denied for asdf, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

This is confusing and the graphdriver behavior is much better here, because it runs whatever platform the image has, but prints a warning:

```
$ docker run image:amd64
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

This commits changes the containerd snapshotter behavior to be the same as the graphdriver. This doesn't affect container creation when platform is specified explicitly.

```
$ docker run --rm --platform linux/arm64 asdf:amd64
Unable to find image 'asdf:amd64' locally
docker: Error response from daemon: pull access denied for asdf, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2024-01-22 15:34 UTC, rumpl requested changes
Let’s add a test

2024-01-22 16:07 UTC, thaJeztah commented
Hm. Probably flaky;

```
=== FAIL: github.com/docker/docker/integration/container TestCopyFromContainerPathIsNotDir (0.53s)
    copy_test.go:47: assertion failed: expected an error, got nil
```

2024-01-22 16:17 UTC, vvoland commented
Not flaky, just a Windows test that's not passing (yet) with c8d.

2024-01-22 18:54 UTC, thaJeztah commented
oh! it has the containerd-integration label set. didn't think of that 😅

2024-01-23 10:26 UTC, rumpl approved these changes
Let’s get this one in but think of a nice way to tests these things

2024-01-23 10:57 UTC, laurazard approved these changes
LGTM

2024-01-23 14:25 UTC, vvoland commented
Let me get this in, I'll add a test in a follow up.

2024-01-23 14:25 UTC, merged