Vendor rootlesskit v2
moby/moby pull request #47258
Opened 2024-01-31 05:46 UTC by aepifanov

Vendor rootlesskit v2 and all dependencies

2024-01-31 06:19 UTC, AkihiroSuda approved these changes

2024-01-31 07:59 UTC, thaJeztah requested changes
was this intended for the 23.0 branch?

2024-01-31 14:23 UTC, corhere approved these changes
Yes, it is intended for v23

2024-01-31 16:31 UTC, thaJeztah commented
🤦 looked from my phone and didn't consider who opened the PR. Do we need similar backports for 24 and 25? Otherwise newer versions use an older version of rootlesskit?

2024-01-31 16:36 UTC, aepifanov commented
> 🤦 looked from my phone and didn't consider who opened the PR. Do we need similar backports for 24 and 25? Otherwise newer versions use an older version of rootlesskit?

Sure, I'll take care about it

2024-02-06 12:31 UTC, thaJeztah commented
Also heads-up that there was a regression in v2.0.0; we merged a follow-up that updates it to v2.0.1;

- https://github.com/moby/moby/pull/47332

2024-02-06 13:59 UTC, corhere commented
I think we should hold off until #47248 is resolved as I suspect it is also a rootlesskit/v2 regression

2024-03-14 04:59 UTC, AkihiroSuda commented
> I think we should hold off until #47248 is resolved as I suspect it is also a rootlesskit/v2 regression

- https://github.com/moby/moby/pull/47558

2025-03-19 15:07 UTC, closed without merging