Fixing Erroneous Behavior
moby/moby pull request #47468
Opened 2024-02-28 17:58 UTC by lokesh-katari

**- What I did**

Replaced the usage of `errors.Wrap` with `fmt.Errorf` in the Docker client package to resolve an issue where `errors.Wrap` was causing problems. Additionally, added the `errors` package for error handling, but as it didn't include the `Wrap` method, I used `fmt.Errorf` as an alternative.

![mobyproerror](https://github.com/moby/moby/assets/111894942/fe470ba0-5939-4c73-b574-0c89868766dc)

**- How I did it**
Identified the issue with `errors.Wrap` in the Docker client package and implemented a workaround by replacing it with `fmt.Errorf`. Added the `errors` package for error handling but opted for `fmt.Errorf` due to the absence of the `Wrap` method.

![mobyproafterresolve](https://github.com/moby/moby/assets/111894942/4b5fd88a-982d-4600-bbc0-0d16f045d866)

**- Description for the changelog**

```markdown changelog
Replaced usage of `errors.Wrap` with `fmt.Errorf` in the Docker client package to resolve compatibility issues. Also, added the `errors` package for error handling, using `fmt.Errorf` as an alternative due to the absence of the `Wrap` method.
```

**- A picture of a cute animal (not mandatory but encouraged)**
![cutecat](https://github.com/moby/moby/assets/111894942/7a23783e-2933-4e7f-bc63-929f6c65a486)

2024-02-28 22:59 UTC, thaJeztah commented
What version of Go are you using? The error you're getting would only happen if you're using go1.12 or older; as the `Is()` function is defined for go1.13 and up only; https://github.com/pkg/errors/blob/v0.9.1/go113.go


We currently use `pkg/errors` and the `errors.Wrap()` functions because Go's native error-wrapping is missing certain features that are used in our code; see

- https://github.com/moby/moby/discussions/46358

2024-02-29 01:06 UTC, lokesh-katari commented
![image](https://github.com/moby/moby/assets/111894942/4ce3a3fa-54b8-499e-8b72-68024533687c)

@thaJeztah i have previously using the go 1.21 version when i encountered this error but also after upgrading the go version to 1.22 go the same issue

and the docker version i am using is 25.0.3

thank you

2024-02-29 12:54 UTC, neersighted requested changes
The current error wrapping package is used for a reason; I don't think this change is the right direction. Instead of attempting to solve some of the formatting issues with this PR, would you mind opening an issue to keep troubleshooting your IDE/compiler and interactions with `pkg/errors`?

2024-03-21 17:23 UTC, closed without merging

2024-03-21 17:23 UTC, neersighted commented
Closing this for now.