api/image/list: Add `container-count` parameter
moby/moby pull request #47501
Opened 2024-03-05 16:38 UTC by vvoland

This parameter was already supported for some time in the backend (for purposes related to `docker system prune`).
It was also already present in the `imagetypes.ListOptions` but was never actually handled by the client.

This makes the client respect the `ContainerCount` and set the form field when sending the request.

**- How to verify it**

**- Description for the changelog**

```markdown changelog
`GET /images/json` now supports the `container-count` parameter which makes the response fill the `Containers` field with a count of containers using the image.  
```

**- A picture of a cute animal (not mandatory but encouraged)**

![image](https://github.com/moby/moby/assets/5046555/8ba4e302-f31b-4cea-ab6b-a525c7ce0bfd)

2024-03-05 16:50 UTC, thaJeztah commented
This looks to be similar to https://github.com/moby/moby/pull/43350 - do we have a use-case for this, or should we consider going the other direction (make sure we properly define types for each purpose). ISTR some of the `usage` types were just reusing existing types because someone was lazy to define separate ones 😞

2024-03-05 17:01 UTC, vvoland commented
We don't have an usage yet, I was mostly just fiddling around the multi-platform `image list`, and wanted to use the containers count as an indicator whether the image is used or not, but noticed that setting this field client-side doesn't actually do anything 🙈

2024-03-05 17:04 UTC, neersighted approved these changes

2024-03-05 17:58 UTC, thaJeztah requested changes
I want to have a closer look before we commit to this; leaving a quick "request changes"

2024-04-05 12:14 UTC, vvoland commented on api/server/router/image/image_routes.go
> +	if versions.GreaterThanOrEqualTo(version, "1.45") {
Adjust API version

2024-08-13 08:52 UTC, laurazard approved these changes
LGTM

2024-08-16 11:37 UTC, vvoland commented
Opened an alternative to this: https://github.com/moby/moby/pull/48345

2024-08-16 13:07 UTC, closed without merging