update containerd binary to v1.7.14
moby/moby pull request #47557
Opened 2024-03-13 12:53 UTC by thaJeztah

Update the containerd binary that's used in CI and for the static packages.

- full diff: https://github.com/containerd/containerd/compare/v1.7.13...v1.7.14
- release notes: https://github.com/containerd/containerd/releases/tag/v1.7.14

Welcome to the v1.7.14 release of containerd!

The fourteenth patch release for containerd 1.7 contains various fixes and updates.

Highlights

- Update builds to use go 1.21.8
- Fix various timing issues with docker pusher
- Register imagePullThroughput and count with MiB
- Move high volume event logs to Trace level

Container Runtime Interface (CRI)

- Handle pod transition states gracefully while listing pod stats

Runtime

- Update runc-shim to process exec exits before init

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```markdown changelog
Upgrade containerd to v1.7.14 (static binaries only). [moby/moby#XXXX](https://github.com/moby/moby/pull/XXXX)
```

**- A picture of a cute animal (not mandatory but encouraged)**

2024-03-13 13:17 UTC, vvoland approved these changes

2024-03-13 13:31 UTC, thaJeztah commented
Failure is a known flaky;

```
=== Failed
=== FAIL: amd64.integration.system TestDiskUsage/empty (0.00s)
    disk_usage_test.go:41: assertion failed: 
        --- du
        +++ →
          types.DiskUsage{
        - 	LayersSize: 4096,
        + 	LayersSize: 0,
          	Images:     {},
          	Containers: {},
          	... // 3 identical fields
          }
        
    --- FAIL: TestDiskUsage/empty (0.00s)

=== FAIL: amd64.integration.system TestDiskUsage (2.65s)
```

2024-03-13 22:36 UTC, AkihiroSuda approved these changes

2024-03-14 11:05 UTC, vvoland commented
It seems that the `TestExecCgroup` gets stuck consistently on this one 🤔

2024-03-27 15:59 UTC, vvoland requested changes
Leaving a request changes until the containerd regression is fixed

2024-04-09 11:29 UTC, thaJeztah commented
Superseded by https://github.com/moby/moby/pull/47689

2024-04-09 11:29 UTC, closed without merging