awslogs: Prevent close from being blocked on log
moby/moby pull request #47748
Opened 2024-04-23 18:43 UTC by cpuguy83

Before this change a call to `Close` could be blocked if the the channel used to buffer logs is full.
When this happens the container state will end up wedged causing a deadlock on anything that needs to lock the container state.

This removes the use of a channel which has semantics which are difficult to manage to something more suitable for the situation.

2024-05-08 20:04 UTC, austinvazquez reviewed
@cpuguy83 nice refactor here! Overall changes LGTM. Just had one or two questions but nothing blocking.

2024-05-08 20:11 UTC, cpuguy83 commented on daemon/logger/awslogs/cloudwatchlogs.go
> +		case msg, more := <-chLogs:
This should only return after the buffer is emptied (`more` is true only after the last message is drained).
https://go.dev/play/p/NR4WOn-XUCs

2024-05-08 20:12 UTC, cpuguy83 commented on daemon/logger/loggerutils/queue.go
> +	"github.com/pkg/errors"
We use `pkg/errors` everywhere in moby, mostly because it handles attaching stack traces.

2024-05-09 00:35 UTC, austinvazquez commented on daemon/logger/awslogs/cloudwatchlogs.go
> +		case msg, more := <-chLogs:
Oh nice! TIL, the wording in https://go.dev/tour/concurrency/4 threw me off, but your example proves the correct behavior.

2024-05-10 19:31 UTC, austinvazquez approved these changes
LGTM! Great change.

2024-05-23 18:52 UTC, neersighted requested changes
I'm not sure we need the `closeWait` channel as the entire `Close()` method takes the mutex, and therefore concurrent close should be impossible. It seems like we can just guard the method with a check that the object has not been already closed, and early-return if it has.

Otherwise, LGTM; I particularly like the Close vs. blocked Enqueue semantics.

2024-05-23 18:53 UTC, neersighted commented on daemon/logger/loggerutils/queue.go
> +	//
Blank lines.

2024-06-14 15:28 UTC, vvoland commented
@neersighted LGTY?

2025-01-17 18:45 UTC, neersighted approved these changes

2025-01-17 18:50 UTC, merged