builder: wire up new gc types for buildkit prune functionality
moby/moby pull request #48720
Opened 2024-10-21 20:39 UTC by jsternberg

**- What I did**

This wires up the new gc types that buildkit exposes in version 0.17. The previous flag, `KeepBytes`, was renamed to `ReservedBytes` and two new options, `MaxUsed` and `MinFree` were added.

`MaxUsed` corresponds to the maximum amount of space that buildkit will
use for the build cache and `MinFree` amount of free disk space for the
system to prevent the cache from using that space. This allows greater
configuration of the cache storage usage when used in situations where
docker is not the only service on the system using disk space.

Fixes #48639.

**- How I did it**

Modified the areas marked by @thaJeztah in https://github.com/moby/moby/issues/48639.

**- How to verify it**

Added some test cases to check that the old and new config options work.

**- Description for the changelog**

```markdown changelog
`docker buildx prune` now supports `reserved-space`, `max-used-space` and `min-free-space`, `keep-bytes` filters.
API: `POST /build/prune` renames `keep-bytes` to `reserved-space` and now supports additional prune parameters `max-used-space` and `min-free-space`.
```

**- A picture of a cute animal (not mandatory but encouraged)**

2024-10-22 16:10 UTC, jsternberg commented on builder/builder-next/worker/gc_windows.go
> +func detectDiskSize(_ string) (int64, error) {
Switched to using this implementation. It also means I can just delete both of these files.

2024-10-22 16:10 UTC, jsternberg commented on builder/builder-next/worker/gc.go
> +	defaultMaxUsedSpaceBytes  int64 = 10e9 // 10GB
Done.

2024-10-22 16:22 UTC, jsternberg commented
Updated the swagger API and found a few additional places I missed by grepping for `keep-storage`.

2024-10-24 14:58 UTC, jsternberg commented
Updated the default gc policy code after some offline feedback from @tonistiigi.

2024-10-25 12:02 UTC, vvoland commented on api/server/router/build/build_routes.go
> +		}
cc @thaJeztah

2024-11-14 12:57 UTC, thaJeztah commented on api/server/router/build/build_routes.go
> +		}
Looks like this one dropped of my radar 🙈 


Yes, I'm considering to skip this one for 27.4; IIUC, without this patch, things continue to work "as before", just the new options not being exposed (?).


For these changes above though, possibly we need some API-version gates? (need to look closer)

2025-01-16 21:10 UTC, jsternberg commented
This is rebased now. The failing test doesn't seem to be related.

2025-01-16 22:54 UTC, tonistiigi approved these changes

2025-01-17 17:23 UTC, thompson-shaun commented
@vvoland @thaJeztah - API version check?

2025-01-21 16:03 UTC, vvoland requested changes
New options should be API version gated.

`docs/api/version-history.md` also needs an entry for the newly supported options

2025-01-21 17:55 UTC, jsternberg commented
@vvoland done. I've never done it before so please double check that I did it correctly.

If this is API version-gated, do we need the fallback code for `keep-bytes` to keep functioning?

2025-01-22 10:32 UTC, vvoland reviewed
Thanks, looks good but spotted some minor issues.

Could you also update the description for the release notes to be more human-facing?
Mostly thinking about showing the user how to use it. Something along the lines of "docker buildx prune now supports X, Y and Y",

2025-01-22 10:32 UTC, vvoland commented on api/swagger.yaml
> -          description: "Remove all types of build cache"
I think we accidentally lost the `all` parameter 😅

2025-01-22 10:32 UTC, vvoland commented on api/types/types.go
> -	KeepStorage int64
We probably should keep it as `Deprecated` for at least one version.

2025-01-22 18:07 UTC, jsternberg commented
Done.

2025-01-23 10:46 UTC, vvoland requested changes

2025-01-23 10:46 UTC, vvoland commented on api/types/types.go
> -	KeepStorage int64
Bump, I think this went unaddressed :)

2025-01-23 15:03 UTC, jsternberg commented on api/types/types.go
> -	KeepStorage int64
Ah, I misunderstood the diff. I thought I had kept this attribute.

2025-01-27 11:08 UTC, vvoland requested changes

2025-01-27 11:08 UTC, vvoland commented on api/types/types.go
> +	KeepStorage int64 // Deprecated: deprecated in API 1.48.
for a follow up, should also update: https://github.com/docker/cli/blob/master/docs/deprecated.md

2025-01-27 11:08 UTC, vvoland commented on client/build_prune.go
> -	query.Set("keep-storage", strconv.Itoa(int(opts.KeepStorage)))
We're still keeping `KeepStorage` as deprecated, so we should still set it.

2025-01-30 15:54 UTC, jsternberg commented on client/build_prune.go
> -	query.Set("keep-storage", strconv.Itoa(int(opts.KeepStorage)))
Restored this code.

2025-01-30 19:04 UTC, vvoland approved these changes

2025-01-30 19:04 UTC, vvoland approved these changes
LGTM, thanks!

2025-02-03 16:55 UTC, merged