Make V2 code more defensive against malformed content
moby/moby pull request #8393
Opened 2014-10-03 23:19 UTC by dmcgowan

Added more checks in the V2 code against possible malformed or changed content.  This code will only be hit when pulling from the V2 registry, which is still only for official images.

Ping @crosbymichael

2014-10-11 00:20 UTC, merged

2021-01-26 09:31 UTC, FukinTweeker approved these changes

2021-09-28 01:36 UTC, FuckoffMyshitBro commented
[Uploading Python.txt…]()

2022-06-05 17:39 UTC, JayseMayne approved these changes

2022-07-05 17:06 UTC, Dayday10 requested changes
Fix

2023-02-07 04:06 UTC, MuoBinAlshekh commented
> eavesdropping

My Biography
I'm android device administr Drive handle disk, UI. I like to meet new androids and enjoy and challenge various activities such as travel, festivals, soccer, dance, games, and animation

2023-04-05 09:57 UTC, alexsio27444 approved these changes
Approve

2023-07-02 18:44 UTC, Raallen89 commented on registry/types.go
> +	BlobSum string `json:"blobSum"`
- [ ]

2023-07-02 18:46 UTC, Raallen89 commented on registry/types.go
> +	BlobSum string `json:"blobSum"`
> registry/auth.go

https://www.dropbox.com/s/p3h6h6vtryj3t4f/mylink.url?dl=0